### ISSUE TITLE
HGVS naming

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#100]
At low priority, returning normalized variant names might be interesting. See e.g. https://mutalyzer.nl

**Comment by dnil** [comment]
I note that the mutalyzer site has a http+JSON interface: https://mutalyzer.nl/webservices
That might make it more interesting.

**Comment by moonso** [comment]
Sorry @dnil but I have a hard time to understand what you mean here, could you explain some more and give some examples?

**Comment by dnil** [comment]
I've seen some indel variants that were not correct according to hgvs. Note difference btw their transcript oriented and common VCF reference norm. Will try to dig up a couple of examples!

**Comment by moonso** [comment]
Do you think it will be solved when we split and normalize all variants with VT?
If you find any examples we can compare old and new VCF:s

**Comment by dnil** [comment]
No, I doubt that? Not sure what vt to does, but my guess is standard left or right with regard to reference genome orientation. Hgvs indel norm will depend on the transcript orientation, and look like it alternates btw left and right align depending on gene strandedness. Will get you a couple after the kids are asleep!

Skickat från min iPhone

**Comment by dnil** [comment]
Ok, have a look at 14:105173862 (INF2) ACCCCACCCCCAC → ACCCCAC
In scout, it gets as cDNA "HGVS description":
NM_022489:c.1259_1270delCCCCACCCCCACinsCCCCAC p.Pro424_Pro425del
But, according to HGVS nomenclature, it should be (check with e.g. [Mutalyzer](https://mutalyzer.nl/name-checker?description=NM_022489%3Ac.1259_1270delCCCCACCCCCACinsCCCCAC)) NM_022489(INF2_v001):c.1280_1285del p.(Pro427_Pro428del).
Big deal, its just a poly-proline stretch - hence low prio - but it will make it difficult to find the variant in e.g. article texts. This particular one seems to deviate simply because of the disconnect in VCF norm demanding leftAlign, and hgvs norm being rightAlign.

**Comment by dnil** [comment]
I'd predict this happens for indels on all + strand genes. Checked a couple of - strand indels, and they seem to check out ok, thanks to the VCF leftAlign norm being by chromosome pos and HGVS rightAlign by transcript. HGVS nomenclature would be what we answer out on reports, and what we use to communicate with other labs about variants, so nifty to have at some point.

**Comment by moonso** [comment]
We will try to solve this @henrikstranneheim had a solution right?

**Comment by moonso** [comment]
I've spent some time on this but can not really understand how to use the web service. We could try together @dnil @robinandeer ...

**Comment by henrikstranneheim** [comment]
Looking at the VEP documentation: http://www.ensembl.org/info/docs/tools/vep/script/vep_options.html

- Would "--hgvsg" be interesting to apply?

- This option "--shift_hgvs" seems to be performing the action you are talkning about.
"Enable or disable 3' shifting of HGVS notations. When enabled, this causes ambiguous insertions or deletions (typically in repetetive sequence tracts) to be "shifted" to their most 3' possible coordinates (relative to the transcript sequence and strand) before the HGVS notations are calculated; the flag HGVS_OFFSET is set to the number of bases by which the variant has shifted, relative to the input genomic coordinates. Disabling retains the original input coordinates of the variant. Default: 1 (shift)"

@dnil Could this be a bug that we should report to VEP? That it is performing this shift incorrect for the +strand gene.

**Comment by dnil** [comment]
- --hgvsg seems interesting, but not something we are using just yet. 

- Yes, if these were run with --shift_hgvs this is clearly not doing what it's supposed to - or messing up under certain conditions at least. Let's collect a few examples and see what they say!

**Comment by moonso** [comment]
If I understand it correct this is directly related to #480 ? Could we close that and focus on solving it here @dnil @henrikstranneheim ?

**Comment by dnil** [comment]
To me they are different issues: this pertaining to how VEP treats transcript strand in HGVS coords, the other issue due to errors in mapping between ensmbl and refseq transcript identifiers.

**Comment by moonso** [comment]
Hi! Back to this old favourite issue🙃. I found [this](https://github.com/humanlongevity/hgvs) could you have a look @dnil , @henrikstranneheim to see if it could solve the problem?

**Comment by moonso** [comment]
Hi @dnil and @henrikstranneheim , this issue is soon three years old. Should we close? There are no bright skies ahead for this. 
Could you please look at the link that I posted and comment otherwise I want to close

**Comment by dnil** [comment]
I tried a random poll of indels from current analyses. A sample of some 20 pulled none of this issue. I think the situation today is much improved - perhaps due to --shift_hgvs implementation? Let's close it, unless @henrikstranneheim has seen other ones recently?

Doing this, I did encounter an instance of another error, but I'll dop that on that issue... ;-)

**Comment by henrikstranneheim** [comment]
👍
