### ISSUE TITLE
Request BAM files to remain in Scout for 6 months

### ISSUE THREAD

**Issue by NicoleCMMS** [Clinical-Genomics/scout#1000]
Last week at a GMCK Scout users meeting where there are representatives from clinical genetics, immunology and CMMS we discussed the length of time the BAM files are available in Scout and all three clinics are in agreement that 3 months is too short.  Ideally we would like to have access to them until the case is solved/archived but we understand that there is a lack of data capacity for this.  Would it be possible to extend the availability of these files to 6 months instead of 3?

**Comment by moonso** [comment]
Number 1000 🍰 🍾 👾 Congratulations!!!

**Comment by henrikstranneheim** [comment]
It is not possible in our current cluster. However, the installation of the new cluster with more data storage is progressing nicely so far. We could probably extend the availability once we have migrated there. I do not dare say when have completed the migration, but we are talking months here. We are also looking into software that will increase our ability to reduce the storage footprint of BAMs, but nothing have been decided yet.

**Comment by NicoleCMMS** [comment]
Excellent, good to hear it is on the wish list when the problem with data storage is solved.  Måns it’s always good to celebrate….even the small things in life 😉

Från: Henrik Stranneheim <notifications@github.com>
Skickat: den 11 oktober 2018 07:04
Till: Clinical-Genomics/scout <scout@noreply.github.com>
Kopia: Nicole Lesko <nicole.lesko@sll.se>; Author <author@noreply.github.com>
Ämne: Re: [Clinical-Genomics/scout] Request BAM files to remain in Scout for 6 months (#1000)


It is not possible in our current cluster. However, the installation of the new cluster with more data storage is progressing nicely so far. We could probably extend the availability once we have migrated there. I do not dare say when have completed the migration, but we are talking months here. We are also looking into software that will increase our ability to reduce the storage footprint of BAMs, but nothing have been decided yet.

**Comment by dnil** [comment]
Here is some food for thought regarding implementing user initiated deletion fully. Most cases that do get (marked) solved are indeed solved within a shorter time frame than three months:
<img width="1555" alt="screenshot 2018-10-11 at 16 02 07" src="https://user-images.githubusercontent.com/758570/46811934-034bcd80-cd74-11e8-86a0-4c1d27892d90.png">

The same picture can be seen for archiving, though the tail is even longer here:
<img width="1636" alt="screenshot 2018-10-11 at 16 31 44" src="https://user-images.githubusercontent.com/758570/46811935-034bcd80-cd74-11e8-90c3-8a081a9ad921.png">
(The latter is slightly approximated upwards as the activity log does not explicitly state "archive". Instead I used the time to the latest status change on each archived case.)

We could have saved some 750 case storage months by deleting these as soon as they were finished, but as the total 3 month regime for all cases in the current instance gives some 8388 case storage months, the saving is about 8%. Not enough for another month of storage for remaining cases.

**Comment by moonso** [comment]
Well done @dnil ! This might be something for @ingkebil to see to?

**Comment by henrikstranneheim** [comment]
Nice work Daniel! At least now we now that we should focus on the other options.

**Comment by ingkebil** [comment]
As Henrik says: in our setting this is near to impossible.

Some context on the shelf life of files on our main storage unit:
- fastq files: 100 days
- temporary analysis files: 21 days
- bam files: 100 days
- result files (vcf): 2 years

We can reduce the amount of time we keep the fastq files and augment the amount of time for bam files for now. e.g. take 30 days from the fastq and add them to the bam files.

What I am wondering: how many of the rerun requests are for bam file generation?

**Comment by NicoleCMMS** [comment]
For us at CMMS the majority of the reruns are ordered to enable analysis against an updated version of our databases.  A small number are rerun in order to get the bam files back.



Från: Kenny Billiau <notifications@github.com>
Skickat: den 11 oktober 2018 21:29
Till: Clinical-Genomics/scout <scout@noreply.github.com>
Kopia: Nicole Lesko <nicole.lesko@sll.se>; Author <author@noreply.github.com>
Ämne: Re: [Clinical-Genomics/scout] Request BAM files to remain in Scout for 6 months (#1000)


As Henrik says: in our setting this is near to impossible.

Some context on the shelf life of files on our main storage unit:

  *   fastq files: 100 days
  *   temporary analysis files: 21 days
  *   bam files: 100 days
  *   result files (vcf): 2 years

We can reduce the amount of time we keep the fastq files and augment the amount of time for bam files for now. e.g. take 30 days from the fastq and add them to the bam files.

What I am wondering: how many of the rerun requests are for bam file generation?

**Comment by ingkebil** [comment]
I find it reasonable to hang on to the BAM files for as long as we can and favour deleting fastq files over BAM.

What if we change the the shelf life as such:
- fastq: 30 days
- BAM: 170 days

@emiliaol @vwirta anyone any objections?

**Comment by vwirta** [comment]
This would reruns from fastq more challening.
How easy would it be to go from BAM to fastq? Or start MIP from BAM?

Did you have a more indepth look at Petagene? Could this be part of the solution?

**Comment by ingkebil** [comment]
This would only be a solution for rasta. I don't think we need to keep ourselves to these strict shelf lives on hasta. Yet.

I don't know how much we are rerunning a case in the first 100 days. Querying scout might give us an answer to that. Or querying EOL ;)

**Comment by vwirta** [comment]
Ok, for rasta this sounds like a good quick fix.
Let’s query EOL to get her opinion :)

**Comment by hassanfa** [comment]
IMHO, making an unaligned bam file might be even better solution. Going to aligned bam file from unaligned bam file is fairly straightforward.

**Comment by ingkebil** [comment]
I don't know if that is relevant for Nicole's question? Current focus is only to shelf life of BAM files.

If it is relevant, can we take that up in another thread?

**Comment by hassanfa** [comment]
You're right another thread. But we should remember, aligners are not prefect. If fastq files are removed and only bam files are kept, then possible analysis reruns might be tricky. If a decision is made to keep bam files, a complete bam file which includes unaligned reads has to be an option.

**Comment by northwestwitch** [comment]
What about converting bam to cram files? The format is supported by igv and it would save us a lot of space. Could we start doing it on the new cluster?

**Comment by ingkebil** [comment]
bump @emiliaol :)

**Comment by ingkebil** [comment]
Shelf life of files has been changed to:

    fastq: 30 days
    BAM: 150 days

Please be aware we might have to adjust these numbers to take some pressure off of requested reruns.

Hope that helps.

**Comment by ingkebil** [comment]
Hi Nicole,

shelf life has now been changed to:
- fastq: 30 days
- BAM: 150 days

Please be aware we might have to adjust these numbers depending on the amount of reruns requested.

Hope this helps,
Kenny

**Comment by NicoleCMMS** [comment]
Excellent, thanks!

Nicole

Från: Kenny Billiau <notifications@github.com>
Skickat: den 22 oktober 2018 10:24
Till: Clinical-Genomics/scout <scout@noreply.github.com>
Kopia: Nicole Lesko <nicole.lesko@sll.se>; Author <author@noreply.github.com>
Ämne: Re: [Clinical-Genomics/scout] Request BAM files to remain in Scout for 6 months (#1000)


Hi Nicole,

shelf life has now been changed to:

  *   fastq: 30 days
  *   BAM: 150 days

Please be aware we might have to adjust these numbers depending on the amount of reruns requested.

Hope this helps,
Kenny
