### ISSUE TITLE
Variant Rank Scoring scheme customizations

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#101]
E.g. we would be interested in prioritizing frameshift indels higher than the current model - which is otherwise wonderful.

**Comment by moonso** [comment]
I will define a API for how different institutes can modify there rank score models

**Comment by moonso** [comment]
The technical part of this is done, we will just update the documentation.

**Comment by robinandeer** [comment]
Have we done this or is this a 1.3 feature?

**Comment by moonso** [comment]
It's more or less done, we can include it in 1.3
