### ISSUE TITLE
Slice case data in dashboard

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/scout#1018]
_Filter function_
- [ ] Case(s)/sampleID(s)
- [ ] HPO-term
- [ ] Gene
- [ ] Casual variants
- [ ] Pinned

**Comment by dnil** [comment]
As discussed, we solve this issue by separating it into three parts:
- [ ] dashboard data view will remain as before, and be sliced according to institute, HPO-term, phenotype group
- the cases filter will be extended to include search on phenotype group as well as gene with a causative or pinned variant. See #1065.
- causatives and pinned variants directly - then later all variants when we can solve the complexity involved - will be searched on an updated causatives view: see #1064. Searches on hop terms, phenotype groups and gene.

**Comment by moonso** [comment]
I'll close this since it has been divided into two separate issues
