### ISSUE TITLE
Reintroduce gene inheritance model

### ISSUE THREAD

**Issue by robinandeer** [Clinical-Genomics/scout#102]
- [x] Add gene level inheritance model (CMMS gene) @ingkebil 
- [ ] OMIM phenotype (rename) @robinandeer
- [x] Pick this new annotation up and populate database @moonso 

@vwirta: can we change this in Scout and MIP (very minor changes) and call it bugs that don't require a re-validation?

**Comment by ingkebil** [comment]
Fixed the GeneLists.
Just holler when I can update them in _references_.

**Comment by moonso** [comment]
Could anyone, @robinandeer  or @ingkebil , be a little more specific here?
What needs to be done?

**Comment by robinandeer** [comment]
I'm not sure if @henrikstranneheim is picking this up and annotating it in the VCF?

**Comment by henrikstranneheim** [comment]
Sure is. However, it is recorded as ""Genetic_disease_model" to separate it from the variant inheritance model.

**Comment by henrikstranneheim** [comment]
I'm not sure what you want me to do Robin. All the info is in the vcf taken from the clinical list populated by Kenny. This info should go below variant in the table "Inheritance model" using the display name "Disorder"

**Comment by moonso** [comment]
Is there any file on rasta with an example of `Genetic_disease_model`?
I've tried to look at some but could not find it...
@henrikstranneheim @emmser

**Comment by ingkebil** [comment]
Check out cust003-CMMS.txt, and clinical master list. All CMMS related lists have a chance of having `Genetic_disease_model` filled in.

**Comment by moonso** [comment]
Yes I understand that they are annotated in the gene list files. But it should be annotated in the VCF according to @henrikstranneheim comment above.
