### ISSUE TITLE
Feedback "General Report"

### ISSUE THREAD

**Issue by KickiLagerstedt** [Clinical-Genomics/scout#1021]
I just want to say that we really like the "General report" that we are able to use now when performing SCOUT analysis - it has improved the speed of analysis remarkably and we really like the "dismiss variant" feature as well as the PDF report!

THANK YOU ALL who has been working with this! :1st_place_medal: 

// Kicki & Helena & Anna mm

**Comment by moonso** [comment]
Great work @northwestwitch and @dnil !! 🍰
