### ISSUE TITLE
gnomAD PLi

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#1022]
New pLI scores based on the entire gnomAD 2.1 are now available! https://macarthurlab.org/2018/10/17/gnomad-v2-1/
Should replace old exac pLI table!

**Comment by moonso** [comment]
Could you point to that file?

**Comment by dnil** [comment]
Here, I guess:
https://console.cloud.google.com/storage/browser/gnomad-public/release/2.1/ht/constraint?pli=1

(from gnomAD Downloads page).

**Comment by moonso** [comment]
Hmm in this file we have different pLi scores for different transcripts. Not really sure how to handle that in Scout. Any suggestions?

Also I think pLi scores are included in the rank model so MIP has to update and score per transcript, not sure if it is MIP or VEP who does that, do you know @henrikstranneheim ?

**Comment by henrikstranneheim** [comment]
Not by heart. I will take a look soon, I am about to update VEP in the near future

**Comment by moonso** [comment]
Ping @henrikstranneheim

**Comment by henrikstranneheim** [comment]
There is a gnomad pLI per gene file: Download it: https://storage.googleapis.com/gnomad-public/release/2.1.1/constraint/gnomad.v2.1.1.lof_metrics.by_gene.txt.bgz

which Scout can use. MIP 7.0 is using this one (so we are still on gene level as the VEP plugin currently cannot handle transcript level)

**Comment by henrikstranneheim** [comment]
For SV we are taking the most severe pli score for genes affected by the variant as a proxy:
```
##INFO=<ID=most_severe_pli,Number=1,Type=Float,Description="Most severe pli score.">
most_severe_pli=0.02
```
This part of the SV rank model in MIP 7.1. Display on SV view if relevant

**Comment by Shicheng-Guo** [comment]
Do we have v3.1.1 download link? 

https://storage.googleapis.com/gnomad-public/release/3.1.1/constraint/gnomad.v3.1.1.lof_metrics.by_gene.txt.bgz

**Comment by Shicheng-Guo** [comment]
I downloaded this gnomad.v2.1.1.lof_metrics.by_gene.txt.bgz and find these columns. Anyone can share some information about this p_amr, p_asj? What are these columns for? 

       p_amr      p_asj      p_eas     p_fin      p_nfe p_oth      p_sas

Thanks

![image](https://user-images.githubusercontent.com/6641283/134595433-8b1be669-ee90-4a14-ac98-e18a6ba5d5af.png)

**Comment by northwestwitch** [comment]
Hi! To be sure I think it would be best to ask the GnomAD people, but perhaps [this document](https://www.biorxiv.org/content/biorxiv/early/2020/04/08/531210/DC1/embed/media-1.pdf?download=true) answers your question?

**Comment by dnil** [comment]
5.5 years. Might be a new record.. 😆
