### ISSUE TITLE
PDF-exported gene panels look bad when their genes are shared by too many other panels

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#1031]
Example:

![image](https://user-images.githubusercontent.com/28093618/47452060-8e43b380-d7c9-11e8-8c44-ddf2526e28e1.png)

**Comment by northwestwitch** [comment]
@dnil what do you think if I fix this by printing let's say the numbers of 10 panels and if the gene is present in more, I write + n other panels?

**Comment by dnil** [comment]
Sounds good enough to me! It’s a nice bonus. I’d personally prefer the other panels over say “Disease associated transcripts” or “Mosaicism” in this particular view. Perhaps try cutting some of those columbs now and we can ask at the next user meeting! Regardless, the number of other panels shown needs to be limited to something finite and short of the right margin. 😄

**Comment by northwestwitch** [comment]
You could also plot the table in the landscape sense, but of course it will be spread on more pages. I'll try cutting the other columns because they're mostly empty anyway!

**Comment by dnil** [comment]
Sounds good! One could also group panels that co-occur, but It would be technically more complicated, and is not guaranteed to save space if the panels change too much over time. We could perhaps also sacrifice differentiating between different versions of the same panel, but that's more scary.

**Comment by dnil** [comment]
Or use only the current status, ie latest version of each? That would be defendable.

**Comment by northwestwitch** [comment]
I didn't think about that, but yes, it would be quite easy to do
