### ISSUE TITLE
Chanjo report: show transcripts with missing coverage

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#1032]
Todays mutation round issue. Current coverage report shows only how many transcripts for each gene have incomplete coverage, not which. The view from variants - gene coverage is excellent, but cannot be reached if there are no high-ranked variants to reach the variant page for.

**Comment by henrikstranneheim** [comment]
Does the coverage overview from the gene panel view help? I think it lists all transcripts that descending order with missing transcripts independent of rank score (I think...). Of course your gene has to be in a panel.

**Comment by moonso** [comment]
Ok so can we consider this solved since the genes can be reached from the panels?
