### ISSUE TITLE
Add link to SNPedia

### ISSUE THREAD

**Issue by robinandeer** [Clinical-Genomics/scout#104]
This seems like a very nice resource to add a link out to from the variant page!

Do you think the clinicians you use it?
ping: @moonso @henrikstranneheim 

Example:
http://snpedia.com/index.php/Rs1234

**Comment by henrikstranneheim** [comment]
We can always add it and see what they think.


On 10 May 2015, at 20:38, Robin Andeer <notifications@github.com> wrote:

> This seems like a very nice resource to add a link out to from the variant page!
> 
> Do you think the clinicians you use it?
> ping: @moonso @henrikstranneheim
> 
> Example:
> http://snpedia.com/index.php/Rs1234
> 
> —
> Reply to this email directly or view it on GitHub.
> 

Henrik Stranneheim Ph.D.
Department of Molecular Medicine and Surgery
Karolinska Institute
Science for Life Laboratory


E-mail: henrik.stranneheim@scilifelab.se
Visiting address: 
Science for Life Laboratories - SciLifeLab
Gamma building
Tomtebodavägen 23A
Delivery address:
Science for Life Laboratories - SciLifeLab
Gamma building
Tomtebodavägen 23B
171 65 Solna

**Comment by moonso** [comment]
Yes I think we should add it!
