### ISSUE TITLE
Clinical filter not working properly

### ISSUE THREAD

**Issue by AnnHam** [Clinical-Genomics/scout#1041]
Is clinical filter not working properly after the latest update? There are loads of intronic variants after filtering...

**Comment by northwestwitch** [comment]
You're right! I've touched that code yesterday and I introduced a bug, I'll fix it, thanks!

**Comment by ellikasahlin** [comment]
Do you have any updates on when this might be fixed?

**Comment by northwestwitch** [comment]
We'll fix it today, working on it now. I'll write it down here when it's down. Sorry for the inconvenience!

**Comment by northwestwitch** [comment]
Not yet..

**Comment by moonso** [comment]
It's working again!

**Comment by ellikasahlin** [comment]
Wohoo!
