### ISSUE TITLE
Overlapping SVs hover misinterprets BNDs

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#1046]
BNDs appear to have a very large size (approximation for infinite). They should for the purpose of overlapping only occur in a gene they hit with their start / end coord - size does not matter here.

**Comment by northwestwitch** [comment]
@moonso are you working on this? Otherwise I could take it

**Comment by moonso** [comment]
Hi, this needs some thinking. If the algorithm for choosing what to show gets to complicated it will take a long time to load variants. Exactly which BNDs should we show? Should this apply to all SVs?
