### ISSUE TITLE
Consider adding coverage reports as PDF blobs to database

### ISSUE THREAD

**Issue by robinandeer** [Clinical-Genomics/scout#105]
This would make it more portable and robust.

**Comment by moonso** [comment]
Should we do this now?
This relates to #89 i guess...

**Comment by robinandeer** [comment]
I think the files are small enough so it should work
It will solve problems related to #89, yes
Look into it if you have time!

**Comment by moonso** [comment]
Do you have any idea how this should be done.
It is not possible to just read a PDF right?

**Comment by robinandeer** [comment]
Maybe just read in the content as binary and store in ``BinaryField``?

https://github.com/MongoEngine/mongoengine/blob/master/mongoengine/fields.py#L1224
