### ISSUE TITLE
Add DR (digenic) OMIM inheritance model 

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#1055]
Example: gene SLCO1B1 and SLCO1B3

**Comment by moonso** [comment]
Ok I'll add this. We need to reload all genes to make this work.
ATM the following genes in OMIM have the new inheritance model:

| Mim Number | HGNC Symbol | Models |
| ---------- | ----------- | ------ |
| 602024 | CLCNKA | DR |
| 602023 | CLCNKB | AR, DR |
| 610162 | CCDC28B | AR, DR |
| 605616 | SLC6A20 | AD, AR, DR |
| 608845 | ARL6 | AR, DR |
| 604588 | NEK1 | AR, DR |
| 608893 | SLC6A19 | AD, AR, DR |
| 608331 | SLC36A2 | AD, AR, DR |
| 605514 | PCDH15 | AR, DR |
| 605516 | CDH23 | AD, AR, DR |
| 209901 | BBS1 | AR, DR |
| 603297 | DYNC2H1 | AR, DR |
| 605495 | SLCO1B3 | DR |
| 604843 | SLCO1B1 | DR |
