### ISSUE TITLE
Alert in variant list if there are comments for a variant

### ISSUE THREAD

**Issue by moonso** [Clinical-Genomics/scout#106]
We should add a small symbol in the variant list that indicates that a variant has comments.

**Comment by robinandeer** [comment]
Do you need to implement something in the adapter for this?
Can I just run ``.count`` on the comment query?

**Comment by moonso** [comment]
Well I was thinking about it. 
One way could be that the adapter add events to the variants/cases. In that way it will almost look like it did before so yaou can do:
```python
if variant.comments:
    display symbol
```

**Comment by robinandeer** [comment]
OK! I'll implement this then :+1:
