### ISSUE TITLE
Add detailed variant frequencies

### ISSUE THREAD

**Issue by moonso** [Clinical-Genomics/scout#107]
We should include frequencies for different populations on variant level when it exists.
Also there has been a discussion to use the highest frequency among all populations when scoring since if the varaint is common in any population it should not be disease causing.

Input from clinics?

**Comment by dnil** [comment]
Agree. 
Likely not disease causing for a high-penetrant rare monogenic. Although different genetic backgrounds could add complication, this is common practice, and the preferred mode in the ACMG guidelines: e.g. BS1 - strong benign support - is tagged when >5% is observed any subpopulation.

**Comment by moonso** [comment]
Ok so this is a MIP issue for now.
@henrikstranneheim can you annotate the allele frequencies from different populations when there are such information?

**Comment by moonso** [comment]
ping @henrikstranneheim

**Comment by henrikstranneheim** [comment]
Yeah, I will have to see if I have time for that one.

Skickat från min iPad

**Comment by henrikstranneheim** [comment]
I think we should support two frequencies from EXAC and 1000G: a MAX_AF (MIP will add this to the vcf references for both 1000G and EXAC) and the usual AF. 
If you want to look into more detail one can follow the EXAC link in Scout for subpopulations and the 1000G browser for instance: http://browser.1000genomes.org/Homo_sapiens/Variation/Population?db=core;r=1:128213-129213;source=dbSNP;v=rs545245702;vdb=variation;vf=78547415

However, that requires an RS number. I think the easiest would be to use the same RS as recorded in the 1000G file. 

@moonso : Can you modify GENMOD to include the rs number and MAX_AF in addition to the AF your extracting now from 1000G?

The frequency table in Scout should expand to display both the MAX_AF and AF as well as a link to the 1000G browser.

**Comment by robinandeer** [comment]
I will guess what the model will look like and update the interface
