### ISSUE TITLE
Consider always loading MT variants from research file

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/scout#1070]
As all MT variants are considered clinically relevant would it be possible to always load MT variants from the research file for both snv and SV into the clinical view?

That would solve the issue of variants located in no coding regions like the D-loop which is hard to include in a gene panel.

**Comment by moonso** [comment]
This will be done in MIP , see https://github.com/Clinical-Genomics/MIP/issues/662, so scout does not change internally. For customers this means that when we use mip 7 in production all MT variants from the research VCF, which means ALL mt variants found in the whole genome sequencing, will be loaded both in clinical AND research.
