### ISSUE TITLE
odd variant call for WDR45 in case 18220

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#1078]
1. inheritance model is annotated as AR_comp (the gene is X linked) in the variant list  :(
Other variants on the X chromosome are correct.

2. the GT calls in the father is 0/1 but the reads are 11 (ref)/ 0(Alt)
in the BAM file I can not see the variant  in the father.

Bug or bad luck with the variant callers. All of them are :passed ?
I've pinned the variant so you can easily see it :)

**Comment by 4WGH** [comment]
Sorry.
Noticed now a re-run is pending on this family. Maybe we should wait it is done.

**Comment by moonso** [comment]
Ok I close this and you can reopen if the problem remains?
