### ISSUE TITLE
Coverage report for family 156

### ISSUE THREAD

**Issue by nicolelesko** [Clinical-Genomics/scout#108]
Can we get a coverage report for this family?  For some reason it is not working.

**Comment by robinandeer** [comment]
We are planning to reload a bunch of cases and this should make the coverage report available again

**Comment by robinandeer** [comment]
Now the coverage report is available: https://clinical-db.scilifelab.se:8083/remote/static/home/scout/analysis-data/cust003/156/156.coverage.pdf
