### ISSUE TITLE
Add HGNC primary transcript to disease associated transcripts table

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/scout#1080]
- Rename the disease associated transcript header to: "Transcripts"
with columns "HGMD_transcripts: RefSeqID"  and "HGNC_transcripts: RefSeqID"
- The blue background in primary transcripts can then be removed

**Comment by northwestwitch** [comment]
I might use a  bit of help here. Where do I get the HGMD_transcripts: RefSeqID and HGNC_transcripts: RefSeqID values?

This is what a gene list of a random variant look like in the database:

```
"genes" : [
		{
			"hgnc_id" : 329,
			"transcripts" : [
				{
					"transcript_id" : "ENST00000379370",
					"hgnc_id" : 329,
					"protein_id" : "ENSP00000368678",
					"sift_prediction" : "tolerated",
					"polyphen_prediction" : "unknown",
					"swiss_prot" : "O00468",
					"pfam_domain" : "PF07648",
					"prosite_profile" : "PS51465",
					"smart_domain" : "SM00280",
					"biotype" : "protein_coding",
					"functional_annotations" : [
						"missense_variant"
					],
					"region_annotations" : [
						"exonic"
					],
					"exon" : "8/36",
					"intron" : "",
					"strand" : "+",
					"coding_sequence_name" : "c.1528G>A",
					"protein_sequence_name" : "p.Gly510Ser",
					"is_canonical" : true
				},
				{
					"transcript_id" : "ENST00000466223",
					"hgnc_id" : 329,
					"protein_id" : "",
					"sift_prediction" : "unknown",
					"polyphen_prediction" : "unknown",
					"swiss_prot" : "unknown",
					"biotype" : "retained_intron",
					"functional_annotations" : [
						"upstream_gene_variant"
					],
					"region_annotations" : [
						"upstream"
					],
					"exon" : "",
					"intron" : "",
					"strand" : "+",
					"is_canonical" : false
				},
				{
					"transcript_id" : "ENST00000469403",
					"hgnc_id" : 329,
					"protein_id" : "",
					"sift_prediction" : "unknown",
					"polyphen_prediction" : "unknown",
					"swiss_prot" : "unknown",
					"biotype" : "retained_intron",
					"functional_annotations" : [
						"downstream_gene_variant"
					],
					"region_annotations" : [
						"downstream"
					],
					"exon" : "",
					"intron" : "",
					"strand" : "+",
					"is_canonical" : false
				},
				{
					"transcript_id" : "ENST00000477585",
					"hgnc_id" : 329,
					"protein_id" : "",
					"sift_prediction" : "unknown",
					"polyphen_prediction" : "unknown",
					"swiss_prot" : "unknown",
					"biotype" : "processed_transcript",
					"functional_annotations" : [
						"downstream_gene_variant"
					],
					"region_annotations" : [
						"downstream"
					],
					"exon" : "",
					"intron" : "",
					"strand" : "+",
					"is_canonical" : false
				},
				{
					"transcript_id" : "ENST00000478677",
					"hgnc_id" : 329,
					"protein_id" : "",
					"sift_prediction" : "unknown",
					"polyphen_prediction" : "unknown",
					"swiss_prot" : "unknown",
					"biotype" : "retained_intron",
					"functional_annotations" : [
						"upstream_gene_variant"
					],
					"region_annotations" : [
						"upstream"
					],
					"exon" : "",
					"intron" : "",
					"strand" : "+",
					"is_canonical" : false
				},
				{
					"transcript_id" : "ENST00000479707",
					"hgnc_id" : 329,
					"protein_id" : "",
					"sift_prediction" : "unknown",
					"polyphen_prediction" : "unknown",
					"swiss_prot" : "unknown",
					"biotype" : "retained_intron",
					"functional_annotations" : [
						"upstream_gene_variant"
					],
					"region_annotations" : [
						"upstream"
					],
					"exon" : "",
					"intron" : "",
					"strand" : "+",
					"is_canonical" : false
				}
			],
```

**Comment by northwestwitch** [comment]
While I know where to look for the HGNC RefSeqID, where's the HGMD one? There's a field named HGMD-PUBLIC in the VCF, is it that?

**Comment by henrikstranneheim** [comment]
No, it is the manual one added in the gene panels. Basically the already on display. Nicole wanted to change the title.

**Comment by northwestwitch** [comment]
Ok, so a recap, to be sure:

Take for instance gene ABCB11 (https://scout.scilifelab.se/genes/42).
It is the first gene of this panel: https://scout.scilifelab.se/panels/5be2b988124f63334d723689, with a manual refseqid of NM_003742.2

So when you go to this variant: 
https://scout.scilifelab.se/cust003/18222/147b0f6c7ff5d0a7875346dacb639671

Under "Disease associated transcripts" (---> renamed to Transcripts)
There will be 2 columns:
**HGNC RefSeqID** and **HGMD RefSeqID**
with values: 
NM_003742 AND NM_003742.2

?

**Comment by dnil** [comment]
Just be careful so that the HGNC refseq (which sometimes went as "primary") is still appropriately highlighted on the table. Users have grown accustomed to using that (blue) row for reporting to other places. Some care must be taken in documenting changes here as this has been a source of confusion before. 😅

**Comment by henrikstranneheim** [comment]
This was added after feedback from CMMS, however, it seems like all information is already there in the interface. 
- Blue background is the Scout primary ensembl transcript ID. This maps to several RefSeq IDs where **one or several** will be the manually curated HGNC refseq transcript ID.

- Lacking a manually curated HGNC refseq transcript ID in Scout can be due to:
   - Transcript does not exist in current genome build
   - The variant does not overlap the manually curated HGNC refseq transcript ID

- To discuss:
   - The canonical tag could be renamed to "VEP" to denote that this is the VEP canonical transcript
   - The manually curated HGNC refseq transcript ID can be tagged in the transcript overview table as "HGNC"
   - Suggested for Scout workshop: transcripts - resources, processing and visualization
