### ISSUE TITLE
Visualise structural variations with Samplot?

### ISSUE THREAD

**Issue by moonso** [Clinical-Genomics/scout#1092]
We should checkout [samplot](https://github.com/ryanlayer/samplot) and see if we could use it in the SV view. What do you think @dnil @northwestwitch ?

**Comment by northwestwitch** [comment]
Yeah, I was also looking for the other issue :)

**Comment by moonso** [comment]
Oops! Ok closing this then.

**Comment by dnil** [comment]
Feel free to reopen the old one after consideration.. :)
