### ISSUE TITLE
date in panels hisotry is wrong!

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#1095]
Hi, 
The data of submisssion for panel is wrong.
It looks like we submitterd v.12 in Nov this year and the same day or by few days differece we submitted version 13.  The number of genes fits with the versions but not the dates!

**Comment by northwestwitch** [comment]
I'll check, it could be that when I've updated the code to be more flexible with the versioning I haven't taken care of updating the date of the new version. Thanks for spotting it!
