### ISSUE TITLE
STR view: model & show STR_STATUS from stranger

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#1097]
Display and color STR view rows according to STR_STATUS.
See [stranger GitHub repo](https://github.com/moonso/stranger).
Available from MIP 7.0: [#653](https://github.com/Clinical-Genomics/MIP/issues/653).

**Comment by moonso** [comment]
You or me @dnil ? I can work on it today if you did not already start or have an idea

**Comment by dnil** [comment]
Either! :) Please go ahead - I have some samples to work on today!
