### ISSUE TITLE
Transcripts on sanger order

### ISSUE THREAD

**Issue by 1ctw** [Clinical-Genomics/scout#1099]
There are many transcripts showed in Scout which are not shown in sanger order email. 

Example:

![bild](https://user-images.githubusercontent.com/15033593/49581726-2e593480-f953-11e8-9cb8-0d0cc83cdcd0.png)

![bild](https://user-images.githubusercontent.com/15033593/49581744-3a44f680-f953-11e8-9d82-24a7d229a7d5.png)

**Comment by northwestwitch** [comment]
Hi!

That's because we haven't modified the Sanger order email after we changes
the transcript view. We'll update it!
