### ISSUE TITLE
Known pathologic non-conforming variants

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#1105]
A fair body of knowledge of pathologic variants that currently receive a poor rank is available. Let's implement a system for them, be that by annotation, ranking, separate collection in scout - or perhaps best by a combination of all.

A quick sampling of non-exonic variants that Blueprint genetics annotate (e.g. https://blueprintgenetics.com/tests/panels/hematology/anemia-panel/) has some 30-50% of such variants in ClinVar so far. This helps, but we could do better!

**Comment by moonso** [comment]
This is a bit tricky since most of this functionality needs to be implemented upstream of scout. Ideally the pipeline should handle this and adjust the rank score accordingly. In that way scout would not need any modifications at all.

**Comment by dnil** [comment]
Eh, couldn't we perhaps reuse the mvl structure from Balsamic/Scout-Cancer here? That already has Scout support. @hassanfa: expect questions. 😄

**Comment by moonso** [comment]
Create a page for users to import known pathologic variants. Could you be more specific here? Should the users create a list of known variants and upload or what do you mean? Any input @dnil @northwestwitch @hassanfa

**Comment by hassanfa** [comment]
+1 for importing known pathogenic variants.

IMHO, it can be a simple approach for somatic SNVs: a bed file. There are multiple github issues on MVL/actionable variants. Should we move all the conversation here?

**Comment by dnil** [comment]
@henrikstranneheim and @dnil had a brief discussion, and the current best idea is to create a page in Scout that allows editing of an MVL / known variants/position list that is then used on loading, much like what we do for ClinVar. The list would be open for all to edit, and changes logged with date and user. This makes it a Scout only issue, although a decent sized one. Timeline is undecided, but we are aware that it is a requested feature. Be advised that submission to ClinVar is always an option for variants that you always wish to have loaded.

**Comment by henrikstranneheim** [comment]
@dnil and @northwestwitch: Should we try to flesh out what needs to be done to be able to implement this one?

**Comment by dnil** [comment]
Yeah otw it will sit pending. I could meet up around 14.30 tomorrow - or perhaps directly after the scout user meeting, depending on what happened to that GMS-RD-tekn meeting?

**Comment by moonso** [comment]
14:30 sounds good

**Comment by moonso** [comment]
Great Job @dnil ! Almost legendary status on this one 😄
