### ISSUE TITLE
Flag cases where clinical filter (and clinsig filter in general) misbehaved under the last months 

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#1106]
This is a suggestion from @dnil actually. It would be good for users to know which cases would need some attention because the filter was not working under the last months.

**Comment by northwestwitch** [comment]
Relative issue was #1079

**Comment by moonso** [comment]
We will announce in the next meeting during what period this was affected in the next user meeting. See [agenda](https://github.com/Clinical-Genomics/scout/issues/1087). If users really need a new tag or message we can discuss that in the meeting.
