### ISSUE TITLE
OMIM Gene / Phenotype

### ISSUE THREAD

**Issue by KickiLagerstedt** [Clinical-Genomics/scout#1111]
Update needed?

When looking at this variant (https://scout.scilifelab.se/cust002/F0016360-2/eb40f370677eb4bb39c20479cda9156a) is seems it is inherited AR - but when opening OMIM it is actually two disorders described - one AR and one AD (http://omim.org/entry/610463)

Is it so that we can not trust the OMIM window in SCOUT and should open OMIM for every variant just to be sure?

**Comment by dnil** [comment]
And in particular, it should now only be AD as the AR one is not solid. Was last updated at OMIM in January it would seem. As it starts off with a “?” marked entry, best check to see that nothing went wrong with parsing upon loading @moonso?

**Comment by moonso** [comment]
Hi, I'm investigating this now. I thought we decided to include phenotypes with ´?´ ...

**Comment by dnil** [comment]
Right you are: I would prefer to include only the ones we or our friends wrote ourselves, but.. ;-)

**Comment by moonso** [comment]
This should be fixed now! The disease collection hadn't been updated in a wile, thank you for noticing this
