### ISSUE TITLE
All variants have score 0

### ISSUE THREAD

**Issue by ellikasahlin** [Clinical-Genomics/scout#1122]
Please see case F0027119 (sample ID 2018-28870-02). All variants have score 0. What has happened here?
Ellika

**Comment by northwestwitch** [comment]
Hi Ellika, something must have happened before loading the variants into scout. We'll check and fix the problem ASAP!

**Comment by emmser** [comment]
The reason must have been that the case was set as unaffected in the pedigree. I changed that to affected and re-run the analysis. Now the variants have been scored.

**Comment by ellikasahlin** [comment]
Hi! This has happened again for case F0028569 (sample ID 2018-29733). Thankful for help!
