### ISSUE TITLE
Remove loqusdb python dependency

### ISSUE THREAD

**Issue by patrikgrenfeldt** [Clinical-Genomics/scout#1123]
In order to make the applications less tightly coupled, loqusdb could be removed as a python dependency and instead be used/called via the loqusdb-cli to avoid accidentally using things informally defined as private in loqusdb.

E.g. see integration between cg and loqusdb: https://github.com/Clinical-Genomics/cg/tree/uncouple-loqus

**Comment by moonso** [comment]
This will unfortunately be as straightforward, but I agree that we should decouple!

**Comment by moonso** [comment]
Duplicated in #1422
