### ISSUE TITLE
See all variant callers

### ISSUE THREAD

**Issue by sofievonlanthen** [Clinical-Genomics/scout#1126]
We used to be able to see all variant callers, even if they haven't called the variant, is it possible to bring it back? For example saying "not called" or "filtered", to be reminded of the different callers that are used, both for SNVs and SVs.

**Comment by northwestwitch** [comment]
Is anyone working on this, otherwise I can take it!

**Comment by northwestwitch** [comment]
Ok I see that this happened after #1069. It's easy to fix but I was just wondering why the calls of "BCFtools" are returned as calls of "SAMtools" instead
 
![image](https://user-images.githubusercontent.com/28093618/51472936-40642a80-1d7b-11e9-9838-6550d15cde06.png)

**Comment by dnil** [comment]
I guess since SAMtools, BCFtools, HTSlib: same difference nowadays, but used to be (m)pileup or samtools, so someone stuck with that?

**Comment by dnil** [comment]
Solved by #1132 - will appear on a server near to you in the not too distant future!
