### ISSUE TITLE
Create code to view and download the variants contributing to the dashboard stats.

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#1139]
For instance validated true positive : 279. Include also how many from customer institution and the possibility to download them (just from their own institution) as a list.

This list should include: 
1) Gene name, region and function
2) The HGVS description
3) All information which comes in the GT call box including which variant caller has called the variant
4) Information in the summary box in Scout (ie rank score, CADD score etc)

**Comment by dnil** [comment]
And this is basically done, isn't it?

**Comment by northwestwitch** [comment]
Yes, done, thanks!
