### ISSUE TITLE
Test app views

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#1144]
Test as many app views as possible.

- To do so one must overcome the problem of mocking a valid session -->https://flask-dance.readthedocs.io/en/latest/testing.html

- Testing should be done by sending requests to the server, as described here: http://flask.pocoo.org/docs/1.0/testing/#the-testing-skeleton

**Comment by moonso** [comment]
If we are ever going to close an issue like this they need to be more specific. Could you add the goals that are needed to fulfil for this to be finished?

**Comment by northwestwitch** [comment]
We have started with this and we are at a good point I'd say. The views are not fully covered yet but we don't have to rush it. We could pick one page/view method and write a test for it whenever we have time, for increasing the coverage. I think we can close this issue for now!
