### ISSUE TITLE
Show coveralls coverage for scout

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#1145]

**Comment by northwestwitch** [comment]
Has nothing to do with Flask 1.0.2 but it would be nice to see an improvement in test coverage after the efforts

**Comment by northwestwitch** [comment]
This id done, thanks @dnil

**Comment by dnil** [comment]
And thank you for the review and suggestion! Sorry, I didn't notice you had assigned yourself until now: still, good timing now..

**Comment by northwestwitch** [comment]
No problem :)
