### ISSUE TITLE
Wrong genotyping?

### ISSUE THREAD

**Issue by KickiLagerstedt** [Clinical-Genomics/scout#1153]
https://scout.scilifelab.se/cust002/F0017184/bc115d1382b1281e7d0b29ae0fc7299c

Looking at IGV it seems as the father is the carrier of this variant and not de novo in the child?

**Comment by dnil** [comment]
MIP issue, most likely: ping @henrikstranneheim and @jemten. A complicated call, where a wild-type SNV next to a heterozygous SNV in one parent. The formed MNV is somehow assigned to the child instead. Upon split or already from FreeBayes, one wonders?

**Comment by henrikstranneheim** [comment]
There is a MNV (TT,AC) from freebayes that is only called in the index. With AD=0,0 in the parents even though is looks different in the BAM file. Probably, it looks different in freebayes haplotype algorithm (it does not use the precise aligment) compared to the BAM, leading to difference between the BAM and the vcf. Hard to say.

In the same position (12:120171994) there is a (T,A) called by gatk and bcftools, which is only found in the father, with strong hom ref support in the others. No split has been performed (at least by VT).

**Comment by moonso** [comment]
Moving to [MIP](https://github.com/Clinical-Genomics/MIP/issues/752)
