### ISSUE TITLE
Implement (parts of) manual test protocol in the py.test / flask-test framework

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#1167]
Implement some of the currently manual verification tests (see doc) to be automagically run as "unit" tests.

**Comment by moonso** [comment]
We should make a list here of what bullet points that are worth to implement.

**Comment by dnil** [comment]
Perhaps this is not quite a "small issue", but we could get it going by picking obvious ones that one shouldn't have to do manually / we'd really not see fail from https://github.com/Clinical-Genomics/atlas/blob/master/docs/validations/scout.md and then close the issue knowing that this is an option.

**Comment by dnil** [comment]
Checking the first five says three covered by tests already, one more implemented, and the fifth fails also on manual tests. 😆

**Comment by dnil** [comment]
I will give up on the continuation this - the document doesn't exist any more. It would seem more useful to go through the views / functions and add relevant tests. One way is to work to increase the automated test coverage, another to check more actual view response contents for intended function instead of just covering them as is.
