### ISSUE TITLE
Display rank score and filter by gene on causatives page

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#1169]

**Comment by dnil** [comment]
Also limit the displayed size of small indel variant names. Some are veeery long.

**Comment by dnil** [comment]
And add in zygosity or mode of inheritance. And ACMG + the other classifications if available.

**Comment by northwestwitch** [comment]
Rank score and zygosity is already displayed now. Adding ACMG classification and filter by
