### ISSUE TITLE
Fix gene_variants to display same hgnc symbol and remove weird popups

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#1172]

**Comment by dnil** [comment]
Lets add the popups back instead. They derived from a set of common functions, imported, if not inherited, to both this and other views. Actually is both informative and seems to not slow things down perceptibly. The same imported macros are responsible for falling back to hgnc_id when hgnc_symbol is missing from the variant in the db. I'll see what can be done about that, but not tonight.. 😄
