### ISSUE TITLE
Slice dash interaction with variant level export

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#1175]
- [x] variant export broken for (at least) cust002: using sanger_ordered as a proxy for validation is not enough as variants can be marked true / false at the pin level without a sanger_order.
- [ ] totals on the variants is for a slice. Actually use a sliced query anyway for the export? That is best given the page as it is today, otherwise let's make a more clear boundary btw the sliced and unsliced part.

Sorry, I didn't pay enough attention to this when the two branches merged - and the tests were presumably not geared towards finding this issue.

**Comment by northwestwitch** [comment]
I might have drunk a little wine this evening, but I swear the second point might as well been explained in Chinese! But I guess we'll fix it! :)

**Comment by dnil** [comment]
No worries; I can express it in python instead! Enjoy the wine - you've earned it! 😄

**Comment by northwestwitch** [comment]
I've just found out that in the code I wrote to export validated variants to the excel (point 1) I'm not using 'sanger_ordered' to collect the validated variants to be exported. I'm actually running this query:

```
query = {
            'verb' : 'validate',
            'institute' : institute_id,
        }
```
Over the events collection. This code is in adapter.variant.verified

Something else must go wrong for cust002  then!

**Comment by northwestwitch** [comment]
I've tried to assign myself to institute cust002 on scout-stage database. When my institute is 'cust002' the variant export works for me on stage

**Comment by northwestwitch** [comment]
Looks like point 1 is not an issue, and it's working now.

**Comment by dnil** [comment]
Yep, some glitch after/during updates yesterday? Anyway, good start!

**Comment by dnil** [comment]
Ok.. I stand corrected! Lets use the verb query you supplied instead: this looks very workable!
