### ISSUE TITLE
Remove not causative buttons from Causatives page

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#1178]

**Comment by northwestwitch** [comment]
One should remove the 'not causative' yellow button, right?

![image](https://user-images.githubusercontent.com/28093618/54537186-616b8500-4992-11e9-87f4-ddab8798a300.png)

Could we hide the not causative variants at the bottom of each panel instead? It could still be useful info!

**Comment by dnil** [comment]
Yep, the "Not causative" is misleading! Good with sorting! A column with zygosity and inheritance pattern (also for the "causative" ones) will tell part of the rest of the story: i e whether this is likely a carrier status (possibly unsolicited) finding, or a diagnostic finding waiting to happen!

**Comment by northwestwitch** [comment]
Remember to substring the name of SVs
