### ISSUE TITLE
Show picture on case level with info on how a gene looks like

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#1180]

**Comment by moonso** [comment]
Hi @northwestwitch , could you explain some more? What gene should we picture?

**Comment by northwestwitch** [comment]
It's a comment from a scout user meeting. I think it's about visualizing the linear structure of a gene (with introns and exons I think) and where a certain point mutation occurs in this gene.

**Comment by moonso** [comment]
Ok so this should be on the variant page and not case page then?

**Comment by northwestwitch** [comment]
I don't know, it is open to discussion. There is also the possibility that you'll have different variants on the same gene, so maybe it would be nice to see where they all are. This was the comment I think.

**Comment by moonso** [comment]
But it will be impossible to show all variants in all genes on case level...

**Comment by northwestwitch** [comment]
I'm going to close this because we have no concrete ideas on how and where to have this functionality. We could reopen in the future
