### ISSUE TITLE
Disease associated transcripts disappear when there are many transcripts

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#1182]
See for instance https://scout-stage.scilifelab.se/cust000/643594-300M/914500e4e62673da9edcac3036163f82.

If you look down at the transcript list the first panel disappears: 
![image](https://user-images.githubusercontent.com/28093618/54279608-c9d2f480-4595-11e9-9964-4bfde06cec47.png)

**Comment by moonso** [comment]
@northwestwitch I'm assigning you to a lot of stuff now, feel free to remove/replace assignments if you like 🛩

**Comment by northwestwitch** [comment]
This will likely be fixed by the new layout after we upgrade to the new bootstrap.

**Comment by dnil** [comment]
Is this ok now, @northwestwitch?

**Comment by northwestwitch** [comment]
> Is this ok now, @northwestwitch?

It should be OK, we're not scrolling any more in that panel in the new bootstrap version. Let's close it!
