### ISSUE TITLE
question about validation

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#1183]
Hi,
when we valiadate by Sanger a variant and the results show that there is a mutation, but the annotation of the mutation in Scount is NOT correct. 
Is it a false positive or a false negative?

see the follwing ex.
https://scout.scilifelab.se/cust003/18182/c172c3d60dd749a1b1fc32cf2c7065bc

variant annotated as:                                 c.832_833insCGG p.Glu277_Val278insAla
real variant according to SAnger results     c.893_895dupAGG, p.Glu298dup

**Comment by northwestwitch** [comment]
I would say it's a false positive because the validation is relative to the annotated variant, but the variant which is supposed to be there was not found by sequencing. 
A false negative would be the case when you don't observe the variant by sequencing but you find it by Sanger sequencing.

I think!

**Comment by 4WGH** [comment]
ops!
the choice in Scout between:
not validated
true positive
false positive

I will choose false positive, but it is good to know for  the future if some statistic will be taken out of SCout  :)

**Comment by northwestwitch** [comment]
So c.893_895dupAGG, p.Glu298dup (found by Sanger seq.) would be a false negative, but this is not the annotated variant present in scout.
?

**Comment by henrikstranneheim** [comment]
Are you looking at different transcripts? There is also this one for this variant:
GRCh37
NM_001286074 -> c.895_896insCGG p.Glu298_Val299insAla

Or can you show that NM_004606 has incorrect placement for the gene? The primary transcript seem to have different mapping between genome builds in ensembl.

**Comment by moonso** [comment]
Closing, please reopen if there is any more problems
