### ISSUE TITLE
deletion coordinates

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#1185]
Hi, I've noticed that the coordiantes for one deletion we are interested on are not completely fitting with what I see in IGV
See:
https://scout.scilifelab.se/cust003/19018/sv/variants/833c92ab637c72bedb58b7f87437840f

chr7:146,486,001-146,547,000 deleted region 61kb according to Scout coordinate
chr7:146,486,086-146,547,488 deleted region 61kb according to IGV view

The difference of 86 bp for the upstream BP is not alarming
the difference in 488 bo for the downstream BP is a bit concerning for me

It would be nicve to understand what to expect to be able to do all the relevant cross check when we fidn a deletion. This affect the promer design if we want to confirm it by PCR.

Thanks :)

**Comment by 4WGH** [comment]
https://scout.scilifelab.se/cust003/18250/sv/variants/7bbdb69bc2d54531400233225affa05d

thing here
coordinates are  20:62069001 -62073000 

Could it be that CNVnator round up the coordinates?

**Comment by dnil** [comment]
:smile: Yes, quite right Michela! CNVnator counts coverage in bins of a predetermined size across the genome, and calls variants by segmentation based on deviations also on neighbouring bins. The bins are very similar to probes on a micro-array in this way: they limit the resolution. For many variants, we also have support from readpairs or split reads, which gives much better resolution, but this is called by TIDDIT, Manta or Delly. If we find these matching a CNVnator call, we actually merge them together into one variant. This is probably what you are used to. Sometimes, as when the breakpoints are in low copy repeats, there is no split read information, and you will only see the CNVnator call. Never design primers very close to breakpoints for CNVnator calls: treat them like you would array CNVs.

**Comment by dnil** [comment]
See the Scout user guide, section on variants for more details on this and links to the literature!

**Comment by dnil** [comment]
I'm closing the issue - good luck with verification!

**Comment by 4WGH** [comment]
Thankyou DAniel !



Michela

________________________________
Från: Daniel Nilsson <notifications@github.com>
Skickat: den 15 mars 2019 13:51:01
Till: Clinical-Genomics/scout
Kopia: Michela Barbaro; Author
Ämne: Re: [Clinical-Genomics/scout] deletion coordinates (#1185)


Closed #1185<https://github.com/Clinical-Genomics/scout/issues/1185>.

**Comment by 4WGH** [comment]
thank you DAniel.

1. Suggestion: should we put a "warning" signal that the coordinates are "rounded up" so the beginner user get a sort of warning signal?

**Comment by dnil** [comment]
Sure: doesn't hurt anyone, and may be helpful! There is a flag passed to VCF from the callers that indicate that these are inexact that could be shown. We could investigate if it is loaded in scout, or implement that for new cases.
