### ISSUE TITLE
gnomAD-SV 

### ISSUE THREAD

**Issue by genecracker** [Clinical-Genomics/scout#1186]
See the pre-print on gnomAD-structural variants, based on WGS data from 14,891 individuals

https://www.biorxiv.org/content/10.1101/578674v1

vcf with data is downloadable

**Comment by dnil** [comment]
Thank you Bianca! See issue on MIP, but we missed the VCF!

**Comment by dnil** [comment]
Add keys to frequencies as annotated with new version of SVDB.

**Comment by moonso** [comment]
Ok could anyone write here exactly what the keys will look like and what values they will have (eg float, one value or multiple etc)? @dnil @J35P312 @henrikstranneheim

**Comment by henrikstranneheim** [comment]
```
##INFO=<ID=gnomad_svAF,Number=1,Type=Float,Description="The frequency of the event in the database">

In INFO field: gnomad_svAF=0.010375
```
