### ISSUE TITLE
Display name

### ISSUE THREAD

**Issue by robinandeer** [Clinical-Genomics/scout#119]
I haven't been entirely clear but the display name column in the ped files have been named both as ``display_name`` and ``Display_name``. Only the former is supported in Scout but both are supported in the upload script...

We should settle for something at least - I'm sorry :disappointed: 

Affected line(s)?
https://github.com/Clinical-Genomics/scout/blob/master/scout/ext/backend/utils/get_case.py#L184

**Comment by moonso** [comment]
I think we should use ```display_name``` but that is just me:)

**Comment by robinandeer** [comment]
Let's use that then - it's fine with me
