### ISSUE TITLE
Shared cases no longer visible on institute cases 

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#1192]
BUG: Cases view no longer shows shared cases. Presumably something goes awry with asking for owner rather than collaborator, very likely as a consequence of an only partly thought through tightening of the query for the dashboard view.

**Comment by dnil** [comment]
Thanks to @AnnHam for noticing cases suspiciously not listed on a research institute (cf cust002 vs cust064).

**Comment by northwestwitch** [comment]
I can work on this you are not doing the same @dnil

**Comment by dnil** [comment]
Thanks! Feel free! 👍
