### ISSUE TITLE
Add nice colors to IGV viewer (if it's easily doable)

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#1199]
So it would look like the standalone IGV

**Comment by moonso** [comment]
This is perfekt start for Mikael Laaksonen to work with

**Comment by northwestwitch** [comment]
We should look at the differences between API 1.0 and API 2.0 and if API 2.0 have nice tracks or improvements to be added to the IGV.js browser

**Comment by mikaell** [comment]
GV 1 vs 2
===========

I don't know which of these are new features or not. I wasn't able to find release notes
for the javascript igv version 2 compared to version 1. This is what I could see
when playing around in the gui and reading the documentation.

Redirecting Scout to use igv 2 was a small change to the url. So far I have not run
into any problems.



### Tracks
Colors for paired end reads that are coded by the chromosome on which
their mates can be found.


### New Options
* removable
* headers
* oauthToken

Every kind of track has been extended with some options as well i.e `Wig track -autoscale option`.



### Dependencies removed
Version 2 does away with dependencies. No need to include in the html-file the following.

        <link rel="stylesheet" type="text/css" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/themes/smoothness/jquery-ui.css"/>
        <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
        <link rel="stylesheet" type="text/css" href="https://igv.org/web/release/1.0.9/igv-1.0.9.css">
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/es5-shim/4.5.7/es5-shim.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/es6-shim/0.35.3/es6-shim.js"></script>
        
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js"></script>
        <script src="https://igv.org/web/release/1.0.9/igv-1.0.9.js"></script>

**Comment by dnil** [comment]
Nice! 👍🏻 Then the trackHeight options I tried to introduce at some point may actually work now!

**Comment by northwestwitch** [comment]
@mikaell you could take a look at this pull request to see how you add a parameter to the config file and use it downstream in the software : #1247
