### ISSUE TITLE
New list of cases "research"

### ISSUE THREAD

**Issue by sofievonlanthen** [Clinical-Genomics/scout#1209]
Would it be possible to add another list on top of the "active", "solved" and "archived", for cases that are still active, but more in a research mode. We have several cases that are quite old, that we are still working on, but not actively in a clinical setting. Cases we can't really let go, so want to dig deaper.

**Comment by dnil** [comment]
Sure, we can do something about that! Since it would not be quite obvious where to place a new case that comes in with research open, I would suggest a filter search where you have to type e.g. "research" and get back all cases with research open, split into the current categories as usual? Would that work for you?

**Comment by sofievonlanthen** [comment]
I was thinking that it could also include cases that do not have the research list open, but we are working on them for a longer period of time. Sometimes including making more functional tests or sending samples to other labs for verification, which might take months. It could of course include cases with research list open.  The cases then stay open in the Active list and blocks the view of the cases we are working with actively. If that makes sense?

**Comment by dnil** [comment]
Hm, ok: I see what you are after. Any name suggestion?
The research flag is convenient since it is already in the database. A new mode can be added, but that requires a bit more thought! Would adding an option to filter for case age or such be helpful?

**Comment by sofievonlanthen** [comment]
I was thinking sort of in the same way we have prioritized cases, we could have something similar, but the opposite, not prioritzed, but wont-let-go cases... Need to think about a good name. Our issue is that we have too many active cases, of which some are not that active any more, but not closed if you see what I mean.

**Comment by dnil** [comment]
Right, I know the feeling! More specifically, what is the issue you are having? Hard to navigate among the cases? Or that the notion of "active" is not necessarily correct anymore? What about a search option for age - e.g. being able to hide all cases older than 4 months old?

**Comment by dnil** [comment]
@sofievonlanthen: Ok, so, we've now got the searching part fixed after some detours. It still needs a little reviewing, but should be ready to launch with the next update! After asking around, I will not add any date-wise searches for now. Instead I suggest that you use one of the existing searchable fields to encode this. E.g. you could write "surdeg" in the synopsis of such intermediate cases, and then easily search for them?
