### ISSUE TITLE
Update key names for ClinGen CGH (benign and pathogenic) 

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/scout#1215]
Svdb has been updated in MIP 7 and to accomodate svdb changes and to clarify what has been annotated the input vcf INFO keys for ClinGen CGH has been renamed:
```
clingen_cgh_benign -> clingen_cgh_benignOCC
clingen_cgh_pathogenic -> clingen_cgh_pathogenicOCC
```

**Comment by moonso** [comment]
Hi @henrikstranneheim , how about `clingy_ngi`?

**Comment by henrikstranneheim** [comment]
I have had some discussion with Daniel N and Jesper and forgot to update this issue. We decided to use:
```
##INFO=<ID=clingen_cgh_benign,Number=1,Type=Float,Description="The frequency of the event in the database">
##INFO=<ID=clingen_cgh_pathogenic,Number=1,Type=Float,Description="The frequency of the event in the database">
##INFO=<ID=clingen_ngiAF,Number=1,Type=Float,Description="The frequency of the event in the database">
##INFO=<ID=clingen_ngiOCC,Number=1,Type=Integer,Description="The number of occurances of the event in the database">
##INFO=<ID=clinical_genomics_mipAF,Number=1,Type=Float,Description="The frequency of the event in the database">
##INFO=<ID=clinical_genomics_mipOCC,Number=1,Type=Integer,Description="The number of occurances of the event in the database">
```

@dnil and @J35P312 If you object please say so.

**Comment by dnil** [comment]
Accept for the general polite grinding of teeth about the need for it, I think we are good. 

On that note I also had a conversation w the aCGH ppl. We will likely be able to get an update procedure in place on our side, but the pathogenic ref file will still have to be treated privately, until there is some sort of access review board for clinical reference data in place. I guess we could give contact info in the download instruction.

// Daniel

**Comment by moonso** [comment]
Why do we use both OCC and AF? We do not treat any other frequency like this. I think we should choose to show one of them whenever there is an alternative

**Comment by dnil** [comment]
There is no real need to have both: the cohort total number of individuals (or chromosomes, depending) would be a more informative number.

As soon as the cohorts are large enough (>200?) it is fine to default to AF. 

For another cautionary side note, at some point the clingen_cgh_benign was used - at least in scoring - as a binary item, much like the old Decipher population track. I take it the aCGH files have the normal AF and OCC instead?

**Comment by henrikstranneheim** [comment]
looking at the database files: there is no AF or OCC fields and no sample GT fields. Both benign and patogenic file looks binary to me and that is was svdb seems to produce. Maybe, we have an old version?

In the svrank_model version 1.8 both fields are Integers.
