### ISSUE TITLE
Describe deployment process

### ISSUE THREAD

**Issue by robinandeer** [Clinical-Genomics/scout#122]
Just realized that I'm the only one who knows how to deploy Scout... We should describe this somewhere and preferably script it somehow maybe using fab or similar tools

**Comment by moonso** [comment]
Sound like a good idea!

**Comment by moonso** [comment]
Is this issue still alive?
Is the information in README enough or should we update documentation @robinandeer ?

**Comment by robinandeer** [comment]
We need to describe how to deploy generally and then how we deploy specifically at Clinical

**Comment by robinandeer** [comment]
Maybe just keep this in AMSystems :P
