### ISSUE TITLE
Problem uploading delivery report to scout in production (works on stage)

### ISSUE THREAD

**Issue by patrikgrenfeldt** [Clinical-Genomics/scout#1221]
cg upload delivery-report-to-scout acase
----------------- UPLOAD ----------------------
.../P_main/lib/python3.7/site-packages/sqlalchemy/orm/query.py:2334: SAWarning: Pathed join target File.version has already been joined to; skipping
  "been joined to; skipping" % prop
uploading delivery report /.../delivery-report.html to scout for case: acase
Fetching case acase
Saving report for case acase in database
Saving case acase
Traceback (most recent call last):
  File ".../P_main/bin/cg", line 11, in <module>
    sys.exit(base())
  File ".../P_main/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File ".../python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File ".../python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File ".../python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File ".../python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File ".../python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File ".../python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File ".../python3.7/site-packages/cg/cli/upload.py", line 205, in delivery_report_to_scout
    _add_delivery_report_to_scout(context, report, case_id)
  File ".../python3.7/site-packages/cg/cli/upload.py", line 165, in _add_delivery_report_to_scout
    scout_api.upload_delivery_report(path, case_id, update=True)
  File ".../python3.7/site-packages/cg/apps/scoutapi.py", line 96, in upload_delivery_report
    update=update)
  File ".../python3.7/site-packages/scout/load/report.py", line 48, in load_delivery_report
    return adapter.replace_case(case_obj)
  File ".../python3.7/site-packages/scout/adapter/mongo/case.py", line 440, in replace_case
    return_document=pymongo.ReturnDocument.AFTER
  File ".../python3.7/site-packages/pymongo/collection.py", line 2789, in find_one_and_replace
    session=session, **kwargs)
  File "...ython3.7/site-packages/pymongo/collection.py", line 2652, in __find_and_modify
    acknowledged, _find_and_modify, session)
  File "...ython3.7/site-packages/pymongo/mongo_client.py", line 1102, in _retryable_write
    return self._retry_with_session(retryable, func, s, None)
  File "...b/python3.7/site-packages/pymongo/mongo_client.py", line 1079, in _retry_with_session
    return func(session, sock_info, retryable)
  File "/...python3.7/site-packages/pymongo/collection.py", line 2647, in _find_and_modify
    retryable_write=retryable_write)
  File "...python3.7/site-packages/pymongo/collection.py", line 245, in _command
    retryable_write=retryable_write)
  File "/...python3.7/site-packages/pymongo/pool.py", line 517, in command
    collation=collation)
  File ".../python3.7/site-packages/pymongo/network.py", line 125, in command
    parse_write_concern_error=parse_write_concern_error)
  File "...python3.7/site-packages/pymongo/helpers.py", line 145, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
pymongo.errors.OperationFailure: cannot index parallel arrays [updated_at] [collaborators]

**Comment by northwestwitch** [comment]
I don't think this has to do with the bug of this morning. I'll check!

**Comment by northwestwitch** [comment]
Scout and Scout-stage mongo have different indexes on case collection:
> use scout
switched to db scout

```
> use scout
switched to db scout
> db.case.getIndexes()
[
	{
		"v" : 1,
		"key" : {
			"_id" : 1
		},
		"name" : "_id_",
		"ns" : "scout.case"
	},
	{
		"v" : 1,
		"key" : {
			"_fts" : "text",
			"_ftsx" : 1
		},
		"name" : "synopsis_text",
		"ns" : "scout.case",
		"default_language" : "english",
		"weights" : {
			"synopsis" : 1
		},
		"language_override" : "language",
		"textIndexVersion" : 3
	},
	{
		"v" : 1,
		"key" : {
			"collaborators" : 1
		},
		"name" : "collaborators_1",
		"ns" : "scout.case"
	},
	{
		"v" : 1,
		"key" : {
			"updated_at" : 1
		},
		"name" : "updated_at_1",
		"ns" : "scout.case"
	},
	{
		"v" : 1,
		"key" : {
			"collaborators" : 1,
			"updated_at" : 1
		},
		"name" : "collaborators_1_updated_at_1",
		"ns" : "scout.case"
	}
]
```

```
> use scout-stage
switched to db scout-stage
> db.case.getIndexes()
[
	{
		"v" : 1,
		"key" : {
			"_id" : 1
		},
		"name" : "_id_",
		"ns" : "scout-stage.case"
	},
	{
		"v" : 1,
		"key" : {
			"collaborators" : 1
		},
		"name" : "collaborators_1",
		"ns" : "scout-stage.case"
	},
	{
		"v" : 1,
		"key" : {
			"_fts" : "text",
			"_ftsx" : 1
		},
		"name" : "synopsis_text",
		"ns" : "scout-stage.case",
		"default_language" : "english",
		"weights" : {
			"synopsis" : 1
		},
		"language_override" : "language",
		"textIndexVersion" : 3
	}
]
```

This might be the reason.

**Comment by dnil** [comment]
Are there many entries with arrays for updated_at?

**Comment by northwestwitch** [comment]
> Are there many entries with arrays for updated_at?

I don't know. 
updated_at is not an index in stage. Which are the correct indexes, those on stage or those in production?

**Comment by dnil** [comment]
If cg is not adding more, reverting them to scalars will resolve the issue. If they are plentiful, and we don't quite understand why they are there we need to find another solution.

@moonso was attempting to gently test and reconciliate the indices on stage, on production and the ones that are requested by the current scout master constants file, but I guess it was interrupted by something more pressing.

The actual scout master constants only has one case index, for synopsis. If stage is fine with only indexing for collaborator rather than date, it is probably ok to do so also in production. 

My ideal plan would be to drop that case-collaborator index from stage first and see if it is really needed for speed. There are only thousands of cases after all. If not, we can drop the offending case-collaborator-update_at index from production as well.

**Comment by dnil** [comment]
Hm, in general, it really makes me wonder if the array-valued update_at wasn't brand spanking new rather, and created by cg? No case with both arrays for collaborator and update_at can have been added to production as long as that index was there. Note the previous offending case from @barrystokman: it was also from today. What do the current cg exported config files look like, for these updates? Arrays for update_at?

**Comment by patrikgrenfeldt** [comment]
No, no values at all for updated_at in the scout-config for the case. The new thing from the cg side is that we are no longer providing the delivery report included in the scout-config for the case that we use in the upload but instead we try to add it via the scout-API afterwards, this is what fails currently?

**Comment by dnil** [comment]
Ok, I think that settles it. We should still both 1) harmonise scout stage, production and development indices and 2) strive to use the same functions for loading cases into scout from cg and command line

**Comment by northwestwitch** [comment]
@dnil I think you are right, it's a problem only for cases which have a update_at which is a list. Reading the documentation:
 
Compound Multikey Indexes¶
For a compound multikey index, each indexed document can have at most one indexed field whose value is an array.

In this case you already have one key which is a list (collaborators) so you can't have another.

This is fixable by converting update_at from list to datetime

**Comment by dnil** [comment]
Yep! And PR #1222 should hopefully avoid creating new such arrays when uploading new delivery reports via cg / scout API.
