### ISSUE TITLE
--peddy-ped option in update case cli is not used

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#1224]
It's an option to the command line, but it's not used . Do we need it or can be removed?

**Comment by northwestwitch** [comment]
Ok. I'll implement it into the new cli PR.

**Comment by northwestwitch** [comment]
Mmm.. Tried to load the test case using the ped file (together with peddy_ped, ped_sex, ped_check). It works but it's not creating any key in the case object for a peddy_ped file path.
I've also tried to use the 'scout update case  --peddy-ped blabla' from the CLI. No changes in the case object. 
Bah. I'm leaving this issue open and I will not modify my PR with this code right now. We can go back to this in another moment

**Comment by moonso** [comment]
Hi @northwestwitch , I guess that you have merged your big PR? And is this still an issue?

**Comment by northwestwitch** [comment]
I kept the code as it was. The option is there but it's not used. Not an issue probably because nobody ever complained, but it can be fixed easily. I had a ton of other things to think about at that time. But we can fix it now!

**Comment by moonso** [comment]
I'll remove the option to add those. It's never been used so let's implement it if there is a need in the future.
