### ISSUE TITLE
Long sample names render Madeline.js hard to read

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#1225]
Madeline abbreviates longer sample names. This is sometimes fine, but becomes a bother for trios from eg cust002, where names like 2019-00001-01 2019-00002-01 2019-00003-01 are shown as "2019-000...". Is there a way to configure this nicely, without ending up with e.g. pedigrees from other customers with really long sample names becoming unusable - something like the command line Madeline "--nolabeltruncation" might be going to far.

**Comment by moonso** [comment]
This should be an issue for the part of the pipeline that runs madelaine since scout only displays a static file. I'm moving this to CG in https://github.com/Clinical-Genomics/cg/issues/377.
