### ISSUE TITLE
Somatic variant view change suggestions

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/scout#1231]
This issue summarizes the discussion about changes for somatic variant views on Scout. It is a followup after "Scout for cancer" goal.

Suggested changes for variant viewer:
1. External link addition:
- [ ] cbioportal
- [ ] Cancer Genome Interpreter (we might need to use a local instance of the server)
- [ ] oncokb https://oncokb.org/

2. Changes on "basics" box:
- [ ] Add a tag to variant if it is identified by germline variant caller. This highly is relevant for inherited cancer cases where we have family/trios.
- [ ] Remove ACMG classification.
- [ ] Add other relevant classification tiers: MD Anderson's or MSK IMPACT tier lists (tier 1, 2, 3, 4, etc), MVL tag if variant has been found in a managed variant list, Keep VUS tag.
- [ ] Remove Mosaic tag
- [ ] Reevaluate dismiss options exclusive to somatic. An example: "possible Germline"
3. Gene annotation and gene model:
- [ ] Remove inheritance model for non-inherited cancers. We as well keep this. Lets discuss please.

4. Details related to "GT Call" box:
- [ ] GT call update to include ./. or -/-.
- [ ] AF/VF addition
- [ ] Tags which variant callers called and what are their filters

5. Transcript overview:
- [ ] For gene panel analysis, exact refseq transcript should be marked. This depends on gene panel design of course.
- [ ] Show refseq IDs instead or side-by-side ensembl IDs. Again, gene panel designs are driven by refseq IDs most of the time. And there is sometimes a bit of mismatch between refseq and ensembl.

Thoughts?

**Comment by hassanfa** [comment]
FYI: I am aware transcript overview might be irrelevant, I just wrote down the bullet points. We can dismiss or keep them.

**Comment by northwestwitch** [comment]
Shall we start to split these points into smaller issues, to address them more easily (via PR)?

**Comment by dnil** [comment]
Yep! Just put them in a project perhaps?

**Comment by moonso** [comment]
Hi, I have splitted this on smaller issues so closing here. The transcripts part needs more discussion so lets keep that out for now.
