### ISSUE TITLE
HPO term and Gene Panel combined

### ISSUE THREAD

**Issue by 47KW** [Clinical-Genomics/scout#1232]
When ticking the boxes for HPO term and a default gene panel, the results (variants) depends on the order you choice to "tick"

**Comment by dnil** [comment]
Confirmed; in particular, when filtering several times, HPO terms first work as intended, also with another panel, but adding HPO-panel together with another panel has no effect.

**Comment by northwestwitch** [comment]
Thanks for noticing and reporting the bug, I'll take a look at this!
