### ISSUE TITLE
SV Research view on semi-old case

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#1237]
500 Internal server error on a semi-old SV case this morning:
https://scout.scilifelab.se/cust002/F0005034/sv/variants
Anyone with log access that can shed some light on this? :-)

**Comment by northwestwitch** [comment]
{% block content -%}
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/variants/templates/variants/sv-variants.html", line 90, in block "content"
    {{ variant_row(variant) }}
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/jinja2/runtime.py", line 579, in _invoke
    rv = self._func(*arguments)
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/variants/templates/variants/sv-variants.html", line 261, in template
    {% for annotation in variant.region_annotations[:3] %}
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'region_annotations

**Comment by dnil** [comment]
Lets see if we can recreate this on stage..

**Comment by northwestwitch** [comment]
When is that you get the error, when you click on a specific variant or the SV variants page? Because https://scout.scilifelab.se/cust002/F0005034/sv/variants works for me.

**Comment by dnil** [comment]
Research variants, filter for chr21. That was basically what I tried. Interesting: I thought it was more widespread.

**Comment by northwestwitch** [comment]
I can confirm that research variant filtered by chromosome 21 triggers an error, so same bug everywhere!

**Comment by northwestwitch** [comment]
It probably doesn't have to do with how old the case is, because same bug is in a cust003 case from a month ago. What about the process used to load the research variants?

**Comment by dnil** [comment]
Yep, that or altogether missing genes for a variant?
