### ISSUE TITLE
Add external links to cancer variant view

### ISSUE THREAD

**Issue by moonso** [Clinical-Genomics/scout#1239]
- [ ] cbioportal
- [ ] Cancer Genome Interpreter (we might need to use a local instance of the server)
- [ ] oncokb https://oncokb.org/

Hi @hassanfa, could you fill in here more specific the urls and what is needed to build the url to a specific variant?

**Comment by hassanfa** [comment]
Here is the following:
1. afaik cBioPortal doesn't have stub. Instead they have a web api: https://www.cbioportal.org/webAPI.
2. Cancer genome interpreter has a REST API: https://www.cancergenomeinterpreter.org/rest_api
3. And oncokb is similar to above two: https://oncokb.org/dataAccess

I'll look into this a bit further in the coming days.

**Comment by dnil** [comment]
So where are we with this @hassanfa? Do you want any help?

Seems essentially this is what they are asking for in https://github.com/Clinical-Genomics/scout/issues/1915? MTBP also has CIViC (https://civic.genome.wustl.edu/links/variants/99) but I think that's just about it?

**Comment by hassanfa** [comment]
This thing! cbioportal and onkokb will be in BALSAMIC. Already started downloading cbioportal data: Issue on BALSAMIC: https://github.com/Clinical-Genomics/BALSAMIC/issues/382

CGI is on hold, for now. It is quite relevant, but too much to do now 😛 

MTBP is using an annotation based rule set. I guess Scout will provide this info as part of the filtering scheme at some point.

We can close this if you want.

**Comment by dnil** [comment]
I realised I forgot CIViC yesterday. Adding now. CGI appears a little oldish from the website (last updates from 2016-2018), so I will leave it out. With that we await Clinical-Genomics/BALSAMIC#382, after which we could start using these annotations for ranking / load selection / filtering.
