### ISSUE TITLE
Remove mosaic tag for cancer variants

### ISSUE THREAD

**Issue by moonso** [Clinical-Genomics/scout#1243]

**Comment by northwestwitch** [comment]
@mayabrandi this one!. Mosaic tag needs to be removed from a variant page:
![image](https://user-images.githubusercontent.com/28093618/69618391-1e41d580-103a-11ea-8f62-abca1c52e9b5.png)

**Comment by northwestwitch** [comment]
If @moonso hasn't started with this yet!

**Comment by moonso** [comment]
No I have not!

**Comment by mayabrandi** [comment]
I added a pr for this. #1551
