### ISSUE TITLE
from ESHG 2019 spliceAI

### ISSUE THREAD

**Issue by genecracker** [Clinical-Genomics/scout#1250]
SpliceAI
https://www.cell.com/cell/fulltext/S0092-8674(18)31629-5?_returnURL=https%3A%2F%2Flinkinghub.elsevier.com%2Fretrieve%2Fpii%2FS0092867418316295%3Fshowall%3Dtrue
https://github.com/Illumina/SpliceAI

there should already be a precomputed list of scores for SNV (not for indels)

**Comment by dnil** [comment]
There is an issue for this in MIP; https://github.com/Clinical-Genomics/MIP/issues/775. We'll await its completion, then display this in scout!

**Comment by jemten** [comment]
Hello there!
In the next release of MIP we will annotate single base pair substitutions, 1bp insertions, and 1-4bp deletions within genes with delta scores and delta position from SpliceAI. 
We have used the keys SpliceAI and SpliceAI_DS_max
``` 
##INFO=<ID=SpliceAI,Number=.,Type=String,Description="SpliceAIv1.3 variant annotation. These include delta scores (DS) and delta positions (DP) for acceptor gain (AG), acceptor loss (AL), donor gain (DG), and donor loss (DL). Format: ALLELE|SYMBOL|DS_AG|DS_AL|DS_DG|DS_DL|DP_AG|DP_AL|DP_DG|DP_DL
##INFO=<ID=SpliceAI_DS_max,Number=.,Type=String,Description="calculated by lua:spliceai_max_score(vals) of overlapping values in field SpliceAI
```

**Comment by hassanfa** [comment]
Splice AI is now part of VEP in release 100: https://github.com/Ensembl/ensembl-vep/releases/tag/release%2F100.0 
https://www.ensembl.org/info/docs/tools/vep/script/vep_plugins.html#spliceai

**Comment by jemten** [comment]
Cool!

**Comment by dnil** [comment]
Hi @moonso - about time for this one, right? I don't think you mind that took the liberty to sketch something, see PR. 
It's also about time for #1330.. 

I note from the new rank model that there are more goodies in the VCF, including MaxEntScan and mtaf. It would seem prudent to display them when they are included in ranking. Would be great if someone who knows more exactly about the keys (@jemten @henrikstranneheim ) would create issues, but otherwise we will find out what we can.. 😸

**Comment by dnil** [comment]
Add SWEREFAF / SWEGENAF to that list of interesting values found. Of interest also for SNVs?

**Comment by moonso** [comment]
This is in place right @henrikstranneheim @jemten ?

**Comment by jemten** [comment]
Yes! The SpliceAI annotation is in the CSQ field now: 
```
##INFO=<ID=CSQ,Number=.,Type=String,Description="Consequence annotations from Ensembl VEP. Format: Allele|Consequence|IMPACT|SYMBOL|Gene|Feature_type|Feature|BIOTYPE|EXON|INTRON|HGVSc|HGVSp|cDNA_position|CDS_position|Protein_position|Amino_acids|Codons|Existing_variation|DISTANCE|STRAND|FLAGS|SYMBOL_S OURCE|HGNC_ID|CANONICAL|TSL|APPRIS|CCDS|ENSP|SWISSPROT|TREMBL|UNIPARC|REFSEQ_MATCH|SOURCE|REFSEQ_OFFSET|GIVEN_REF|USED_REF|BAM_EDIT|SIFT|PolyPhen|DOMAINS|HGVS_OFFSET|MOTIF_NAME|MOTIF_POS|HIGH_INF_POS|MOTIF_SCORE_CHANGE|MES-NCSS_downstream_acceptor|MES-NCSS_downstream_donor|MES-NCSS_upstream_acceptor|MES-NCSS_upstream_donor|MES-SWA_acceptor_alt|MES-SWA_acceptor_diff|MES-SWA_acceptor_ref|MES-SWA_acceptor_ref_comp|MES-SWA_donor_alt|MES-SWA_donor_diff|MES-SWA_donor_ref|MES-SWA_donor_ref_comp|MaxEntScan_alt|MaxEntScan_diff|MaxEntScan_ref|SpliceAI_pred_DP_AG|SpliceAI_pred_DP_AL|SpliceAI_pred_DP_DG|SpliceAI_pred_DP_DL|SpliceAI_pred_DS_AG|SpliceAI_pred_DS_AL|SpliceAI_pred_DS_DG|SpliceAI_pred_DS_DL|SpliceAI_pred_SYMBOL|GERP++_NR|GERP++_RS|REVEL_rankscore|phastCons100way_vertebrate|phyloP100way_vertebrate|ExACpLI|LoFtool|CLINVAR|CLINVAR_CLNSIG|CLINVAR_CLNVID|CLINVAR_CLNREVSTAT|genomic_superdups_frac_match">
```


````
##SpliceAI_pred_DP_AG=SpliceAI predicted effect on splicing. Delta position for acceptor gain
##SpliceAI_pred_DP_AL=SpliceAI predicted effect on splicing. Delta position for acceptor loss
##SpliceAI_pred_DP_DG=SpliceAI predicted effect on splicing. Delta position for donor gain
##SpliceAI_pred_DP_DL=SpliceAI predicted effect on splicing. Delta position for donor loss
##SpliceAI_pred_DS_AG=SpliceAI predicted effect on splicing. Delta score for acceptor gain
##SpliceAI_pred_DS_AL=SpliceAI predicted effect on splicing. Delta score for acceptor loss
##SpliceAI_pred_DS_DG=SpliceAI predicted effect on splicing. Delta score for donor gain
##SpliceAI_pred_DS_DL=SpliceAI predicted effect on splicing. Delta score for donor loss
##SpliceAI_pred_SYMBOL=SpliceAI gene symbol
````

**Comment by dnil** [comment]
Nice! I'll rewrite the Scout PR then!
