### ISSUE TITLE
Phenomizer/HPO documentation

### ISSUE THREAD

**Issue by robinandeer** [Clinical-Genomics/scout#126]
From Per Marits:
Jag vore tacksam för en kort instruktion hur jag lägger in HPO-termer i "phenomizer"

**Comment by henrikstranneheim** [comment]
I know that some at CMMS also would like a walk-through.


On 07 Jun 2015, at 18:22, Robin Andeer <notifications@github.com> wrote:

> From Per Marits:
> Jag vore tacksam för en kort instruktion hur jag lägger in HPO-termer i "phenomizer"
> 
> —
> Reply to this email directly or view it on GitHub.
> 

Henrik Stranneheim Ph.D.
Department of Molecular Medicine and Surgery
Karolinska Institute
Science for Life Laboratory


E-mail: henrik.stranneheim@scilifelab.se
Visiting address: 
Science for Life Laboratories - SciLifeLab
Gamma building
Tomtebodavägen 23A
Delivery address:
Science for Life Laboratories - SciLifeLab
Gamma building
Tomtebodavägen 23B
171 65 Solna

**Comment by moonso** [comment]
Hello,

at the case page in Scout there is a box:

![skarmavbild 2015-06-11 kl 07 37 07](https://cloud.githubusercontent.com/assets/405278/8100502/b59f9d0a-100c-11e5-86bb-c3caf9679384.png)

Here one can add and remove phenotypic terms in hpo format, these looks like **HP:0010704**.
[Phenomizer](http://compbio.charite.de/phenomizer/) is a tool for generating HPO terms based on text descriptions of phenotypes.  
So if I go to phenomizer and enter a phenotypic description, looks like this:

![skarmavbild 2015-06-11 kl 07 43 14](https://cloud.githubusercontent.com/assets/405278/8100538/9e9a4b36-100d-11e5-8ec3-4aa57b838ee3.png)

Then i copy the hpo term, **HP:002070** in this case, to the "Phenotype" box in scout and click "add", like:

![skarmavbild 2015-06-11 kl 07 46 04](https://cloud.githubusercontent.com/assets/405278/8100564/f747364a-100d-11e5-8634-27f6a9ea0c86.png)

Add a coouple of terms in this way, the more terms that are added the more accurate gene list will be generated by Scout:

![skarmavbild 2015-06-11 kl 07 51 55](https://cloud.githubusercontent.com/assets/405278/8100628/c4eef678-100e-11e5-80c6-65aab451f21f.png)

Each time a phenotypic term is added or removed the user generated gene list for this case is updated.

To filter the variants based on this gene list, go to variants, bring up the filter and click **HPO Generated Gene List** and then **Filter Variants**.

![skarmavbild 2015-06-11 kl 07 53 33](https://cloud.githubusercontent.com/assets/405278/8100669/4307ab86-100f-11e5-9138-980aafb28093.png)

You will now only see variants that resides in the genes of the user generated gene list.
The result will probably be better if you are looking at the research variants.

Another way of defining gene lists is to write hgnc id:s to a file on your computer. This file should have one hgnc id per row and look like

![skarmavbild 2015-06-11 kl 08 07 16](https://cloud.githubusercontent.com/assets/405278/8100838/edd3884a-1010-11e5-98eb-c876a9fb4e11.png)


You can now upload the file to scout by clicking "Bläddra" and then "Upload" in the filter (see picture above). Now you will only see variants that overlap these genes. In this way the users can define multiple gene lists locally and then reuse them in their analysies.

Hope this helps!

Måns

**Comment by moonso** [comment]
If this little guide is helpful we will move it t the documentation.

**Comment by vwirta** [comment]
Please move to documentation!
