### ISSUE TITLE
Grch38 contig name for export gene panel

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/scout#1276]
Currently Scout produce this gene panel export for genome build 38:
```
##genome_build=38
##gene_panel=MIT,version=12.0,updated_at=2018-02-05,display_name=Mitochondrial nuclear
##gene_panel=mtDNA,version=8.0,updated_at=2015-11-30,display_name=Mitochondrial DNA
##gene_panel=IEM,version=12.0,updated_at=2018-02-05,display_name=Inborn Errors of Metabolism
##contig=1
##contig=2
##contig=3
##contig=4
##contig=5
##contig=6
##contig=7
##contig=8
##contig=9
##contig=10
##contig=11
##contig=12
##contig=13
##contig=14
##contig=15
##contig=16
##contig=17
##contig=18
##contig=19
##contig=20
##contig=21
##contig=22
##contig=X
##contig=MT
```
However, grch38 should have a chromosome prefix = "chr" and MT is now called chrM, see: ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/001/405/GCA_000001405.15_GRCh38/seqs_for_alignment_pipelines.ucsc_ids/GCA_000001405.15_GRCh38_full_analysis_set.fna.fai

We need to add the chromosome prefix and rename MT to M when exporting using grch38.

**Comment by northwestwitch** [comment]
Closing this.
