### ISSUE TITLE
mtDNA report

### ISSUE THREAD

**Issue by 1ctw** [Clinical-Genomics/scout#1278]
Hi Chiara!

We are finally going to use the mtDNA report as originally planned, but I now noticed that there is still a problem with the report. Can you please help me fix this.

The report shows all variants detected in that family, i.e. the variants from the father are also in the report of the child and vice versa. When the variants are from the father they show up as AD Alternative=0 in the report of the child. Could you please make the report only showing the variants that are in the individual it is representing.

A good example is case 19169 where the report for the child 19169-I-2A ends up with 8 variants from the father mixed up with the true variants from the patient.

Thanks!
Helene

**Comment by northwestwitch** [comment]
Hi! 
So to make sure that I've understood: in all reports (affected or parents) I should remove all lines where 'AD alternative' is 0, right?

**Comment by 1ctw** [comment]
Yes, then you have understood it right:)
