### ISSUE TITLE
variant inheritance model not correct. (see file)

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#128]
the variant is heterozygous, but the variant inheritance model is indicated as homo_AR

![fam41](https://cloud.githubusercontent.com/assets/12525201/8057213/8470fb9c-0eaf-11e5-8e83-72efe3cc955b.gif)

**Comment by robinandeer** [comment]
This has been identified as a bug which is related to the issues we've been experiencing in dealing with WGS data. It should be fixed as soon as we get the analysis results back up again
