### ISSUE TITLE
Quality report

### ISSUE THREAD

**Issue by 47KW** [Clinical-Genomics/scout#1287]
Hello
my quality report for Case F0030368 was not correctly reflecting the genepanel it was clinically based on, Cardiolog. Rather, it seems to show OMIM coverage etc. This issue concerns when making a report by pressing "General", not using the "Coverage report" or "Download PDF" buttons.

**Comment by northwestwitch** [comment]
Thanks for opening the issue, I'll take a look!

**Comment by northwestwitch** [comment]
This is fixed now in the code and the change will be in place in the next scout release. Thanks for your help improving scout!
