### ISSUE TITLE
ensBL transript ENST and SeqREf transcrit wrongly associated ?

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#130]
hi for this variant 
https://clinical-db.scilifelab.se:8083/cust003/15047/variants/ba25f792bab229442b25ea240215ac16
the ENsemble transript ENST00000401675 correspond to NM_001301339 not to NM_213720.
At least for what I cans see from USCS. while trying to sort it out why the chagnes reported in the Sanger order do not fit in the reference transcript NM_213720.

this affect variant calling as NM_213720, the reference pathogenic transcript has 21 nt less (=7 aa less)

Mic

**Comment by robinandeer** [comment]
I'm not quite sure how this connection is made in the analysis pipeline
@henrikstranneheim: care to weigh in?

**Comment by 4WGH** [comment]
Additional info: We performed Sanger and none of the 2 variants are present.

**Comment by henrikstranneheim** [comment]
In Ensemble GRCh37:
ENST00000401675—> NM_213720

In Ensemble GRCh38:
ENST00000401675—> NM_001301339

We are still using GRCh37 for a number of reasons, but I am looking into switching. However, there are still a lot of data and references that need liftover (and testing) before the change can be done.

**Comment by moonso** [comment]
Is this still an issue @henrikstranneheim ?

**Comment by henrikstranneheim** [comment]
No
