### ISSUE TITLE
Scout, ranklista, comments

### ISSUE THREAD

**Issue by 47KW** [Clinical-Genomics/scout#1302]
Hej
jag föreslår att det finns en visuell skillnad mellan "comments" i Variantlistans rank-rutan beroende på om kommentaren är global eller lokal.
mvh

**Comment by northwestwitch** [comment]
Hi, just to clarify, you mean this list for instance? 

![image](https://user-images.githubusercontent.com/28093618/64684246-0ae48c80-d485-11e9-8862-9bfdb93fdd71.png)

Do you have any suggestions?

**Comment by vwirta** [comment]
Different colours for the bubble?

**Comment by northwestwitch** [comment]
Or a different shape of the bubble if there are global comments ?

**Comment by 47KW** [comment]
After discussion in the office, this is maybe a non-issue since we are avoiding making global comments in general
😊
Suggest to leave it as it is

/ Håkan

Från: Valtteri Wirta <notifications@github.com>
Skickat: den 11 september 2019 11:22
Till: Clinical-Genomics/scout <scout@noreply.github.com>
Kopia: Håkan Thonberg <hakan.thonberg@sll.se>; Author <author@noreply.github.com>
Ämne: Re: [Clinical-Genomics/scout] Scout, ranklista, comments (#1302)

Different colours for the bubble?

**Comment by northwestwitch** [comment]
Ah ok, it was an easy fix :)

**Comment by 47KW** [comment]
A globe if global and a ….map if local
😉

Från: Chiara Rasi <notifications@github.com>
Skickat: den 11 september 2019 11:26
Till: Clinical-Genomics/scout <scout@noreply.github.com>
Kopia: Håkan Thonberg <hakan.thonberg@sll.se>; Author <author@noreply.github.com>
Ämne: Re: [Clinical-Genomics/scout] Scout, ranklista, comments (#1302)


Or a different shape of the bubble if there are global comments ?

**Comment by northwestwitch** [comment]
What about adding the globe if there are global comments and leaving the comment bubble as it is if it's local?

![image](https://user-images.githubusercontent.com/28093618/64686617-38333980-d489-11e9-8471-59123d9a4541.png)
