### ISSUE TITLE
Search for variants within a chromosomal position

### ISSUE THREAD

**Issue by ViktorHy** [Clinical-Genomics/scout#1303]
Hi!

Suggestion for improvement, currently we are only able to search for variants on a specific chromosome. Would be nice to also be able to search for variants within certain coordinates. Like chr7:1000-1000000. 

If this function is available it is not obvious where/how to do this.

Best wishes
Viktor

**Comment by northwestwitch** [comment]
I'm sure that this functionality won't be too difficult to implement, and it will be useful for many users!

**Comment by dnil** [comment]
Good, and easy enough!

It also ties in with the general region concept. We would like to have regions as a more general entity, much like the panelApp concept, where panels could contain a region with known pathogenic aberrations, but not one defined gene spanning it.
