### ISSUE TITLE
SV variants frequency hover

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#1305]
We now have a decent set of frequencies for SVs, although more are coming. Time to wrap that into a nice hover on the variants page for easy access, and perhaps update the filter fields as well.

**Comment by moonso** [comment]
I'll be happy to work on this, however it would be nice to have an updated test data file with all the new SV frequencies. Would that be possible to fix @henrikstranneheim ?

**Comment by henrikstranneheim** [comment]
There is currently no new ones planned, but they move from being key-value in INFO to INFO/CSQ.

I think I lost the raw test data I used to use in the move from Rasta to Hasta. I will look into it.

**Comment by dnil** [comment]
@moonso I was just aiming to show the ones we already have on the variant page as a hover on the variants view! And if one were to happen to write tests for the import of these keys as per issue #1330, that's a nice bonus.
