### ISSUE TITLE
I see no familes at all in Scout

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#131]
this is what I see.
I had to log in again while working on it. and from then I do not see anythiong.
I've tryied to lot out and log in again , But I'm still logged in......

![michela](https://cloud.githubusercontent.com/assets/12525201/8278986/5def2d1a-18d0-11e5-9b9b-009c92c23486.gif)

**Comment by robinandeer** [comment]
This was the case for a short while. Perhaps if you try reloading the page or closing down the browser, then reopen it.

It has to do with cached pages so it will be resolved either way just given time

**Comment by 4WGH** [comment]
Hi Robin.
 
I've closed the browser, restardted PC. still can not see anything.
I try to logout, I click on sign in, chosse the clinicalgenomics e-mail, and I get to SCout , not families, no request to dogot again my password.
 
:(
 
Any other suggestion?
Seams that Nicole also has still the same problem, just chekced with her
 
 
Michela -----Robin Andeer <notifications@github.com> skrev: ----- 

Till: Clinical-Genomics/scout <scout@noreply.github.com>Från: Robin Andeer <notifications@github.com>Datum: 2015-06-22 14:43Kopia: 4WGH <michela.barbaro@karolinska.se>Ärende: Re: [scout] I see no familes at all in Scout (#131)
This was the case for a short while. Perhaps if you try reloading the page or closing down the browser, then reopen it.
It has to do with cached pages so it will be resolved either way just given time

**Comment by robinandeer** [comment]
This is strange. If it's the problem I think it is then you could try following this guide:
https://support.mozilla.org/en-US/kb/how-clear-firefox-cache#w_clear-the-cache

I will look into how I can make it so you don't have to worry about these things in the future!

**Comment by 4WGH** [comment]
it work!!!
 
thank!
Michela
 
 
 
Michela Barbaro, M.Sc, PhD
Sjukhuskemist
Centrum för Medfödda Metabola Sjukdomar (CMMS)
L7:05
Karolinska Universitetssjukhuset Solna
17176 Stockholm 
-----Robin Andeer <notifications@github.com> skrev: ----- 

Till: Clinical-Genomics/scout <scout@noreply.github.com>Från: Robin Andeer <notifications@github.com>Datum: 2015-06-22 16:33Kopia: 4WGH <michela.barbaro@karolinska.se>Ärende: Re: [scout] I see no familes at all in Scout (#131)
This is strange. If it's the problem I think it is then you could try following this guide:https://support.mozilla.org/en-US/kb/how-clear-firefox-cache#w_clear-the-cache
I will look into how I can make it so you don't have to worry about these things in the future!
