### ISSUE TITLE
See actual genes on GeneList?

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#132]
Is there a way for us to view the actual genes on the GeneLists, without e.g. asking Kenny? 
Links from the gene list version table on each case might be a nice place, but just read access to a repo would do fine!

Cheers!

**Comment by robinandeer** [comment]
Thanks! This is a feature worth discussing
We will likely upload the list of genes during the Scout upload but this will take some time to implement

**Comment by moonso** [comment]
This will be fixed in #162
