### ISSUE TITLE
Error after loading exons on hasta stage (build 38)

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#1323]
I've been trying the command 
```
scout load exons -b 38
```
from hasta stage.

The command works fine:
![image](https://user-images.githubusercontent.com/28093618/64948242-edddfe00-d876-11e9-9f06-205cb0f656c7.png)

But I get an error at the end:
![image](https://user-images.githubusercontent.com/28093618/64948275-0221fb00-d877-11e9-9e53-168f694938e4.png)

**Comment by moonso** [comment]
We solved this together by looking at all indexes
