### ISSUE TITLE
Store "quick" ACMG classifications in acmg collection

### ISSUE THREAD

**Issue by bjhall** [Clinical-Genomics/scout#1325]
This relates to my pull request from last week: https://github.com/Clinical-Genomics/scout/pull/1324

Currently "real" ACMG classifications are stored in the acmg collections, whereas "quick" classifications (when one of the P/LP/VUS/LB/B buttons are pressed on the variant overview page) are stored in the case's document in the case collection.

Is this due to legacy reasons or by design?

I see the following problems with the current situation:

1. If I want to show the quick classifications as in https://github.com/Clinical-Genomics/scout/pull/1324, I'd have to query the case collection as well. Doable but ugly.

2. When cases are removed from Scout, the classifications will be removed along with them, which feels more problematic. 

Any thoughts? If this is by design, feel free to delete this issue!

**Comment by moonso** [comment]
Hi @bjhall , we have discussed this and agree with you. They should be stored in the collection as well.

**Comment by dnil** [comment]
Yep! :+1: I guess the previous was sensible since a variant is only ever classified in relation to a phenotype, and previous classifications without phenotype are not necessarily transferable. Genetics is not predictive. We should be restrictive with displaying LB/B/VUS in a way that rookies - or stressed out specialists - might misinterpret them. But, previous LP/P are important enough to warrant a risk of misinterpretation.

**Comment by moonso** [comment]
Hi @bjhall and @dnil , I'm working on this now and there are some stuff that becomes complicated.

1. If there is a evaluation and then that is changed it will become 2 evaluations. Should we remove the first one then?
1. If a user press `Likely Pathogenic`, changes mind and press `Likely Pathogenic` again there is a complicated situation. Variant should go back to 'unevaluated', however there will now be two evaluation objects in the database. Should both of those be removed?

My is to remove the previous object in first case and remove both in second case. What do you think?

**Comment by dnil** [comment]
Can we let the user revoke a classification; e.g. as (I guess?) one would with dropping an ACMG one? Then things should be rather ok.

One could argue that one user should only be allowed one verdict (of each type) per case-variant, but we don't necessarily need to enforce that.

**Comment by bjhall** [comment]
The easiest solution is probably to only allow one classification per variant, ie. removing all classification except the latest one (which would be in accorandance to Måns' suggestion). The users should probably do full evalations if they have differing opinions anyway, in order to document why they differ.

The other option, I guess, would be to handle the "quick" evaluations more like the "full" ones. Ie. to create a line below the Classify-button with information on when and by whom the classification was made, with a "Delete" link, and never automatically remove anything. 

The more I think about it the more I'm leaning towards option 2...

**Comment by moonso** [comment]
Ok that will work. Do we all agree on only showing classifications P/LP on the variants overview page?

**Comment by northwestwitch** [comment]
I think he wanted to show it on the variants page as in  #1324
