### ISSUE TITLE
Case search seems to not work as expected

### ISSUE THREAD

**Issue by moonso** [Clinical-Genomics/scout#1328]

**Comment by northwestwitch** [comment]
Oh no!

**Comment by dnil** [comment]
Either sth with indexes on the production server, or possibly with gene hgnc symbols not being populated there as on the stage? I think I would start checking the latter, and if so just convert symbols to hgnc_ids before searching with pinned, causative etc?

**Comment by dnil** [comment]
Yes, can confirm the latter. After a fresh local install, the issue on the production server can be reproduced. Something to keep in mind when testing on stage, or on a local db that has been around for.. a while. Will fix, and only search for hgnc_id, but am thinking of checking out early today to get to #FridaysForFuture. Perhaps we shouldn't risk an update today at any rate?
