### ISSUE TITLE
editing the panel at the gene level

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#1335]
I want ot change the manually curated inheritande model in a gene but it is not possible. I gent the wrong type of inheritance model type , see atttached picture

![bild](https://user-images.githubusercontent.com/12525201/65751056-0a492880-e10a-11e9-8e0b-a803cdc7651b.png)

**Comment by northwestwitch** [comment]
Instead of available models in the inheritance checkbox, use these models:
- AD
- AR
- XL
- XD
- XR
- NA
- AD (imprinting)
- digenic
- AEI (allelic expression imbalance)
- Other + free text
