### ISSUE TITLE
window move to  much

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#1336]
![bild](https://user-images.githubusercontent.com/12525201/65751289-8479ad00-e10a-11e9-803b-957717d864fb.png)

If there are many trancript I need to scroll down When I do so the "disease associated transcipts window disappear too. I wish that only the TRanscript overview window move.
It was so a while ago. So I can still see which is the disease associated trancript :)

test here of exemple
https://scout.scilifelab.se/cust003/19153/071b1e54cd6a7ba26c4cffc2af1706cf

**Comment by dnil** [comment]
Sounds very reasonable and doable! :+1:

**Comment by northwestwitch** [comment]
In the new layout it doesn't scroll, see here: https://scout-stage.scilifelab.se/cust003/94/0cd4dd4a1ff603eddb9d4726dc3f8e23 . Maybe it should, but in the way @4WGH suggests. We should work on that layout and not on the current one.

**Comment by northwestwitch** [comment]
Ok I've removed the new layout from scout stage just now because I'm testing stuff, so that you know. I'll put it back in half hour or so

**Comment by moonso** [comment]
Could you close this with the bootstrap 4 PR later @northwestwitch ?

**Comment by moonso** [comment]
I'm closing this since bootstrap4 is merged, reopen if it does not work
