### ISSUE TITLE
Clinical STRs - suggestion

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#1338]
1. could we filter by panel?
so we avoid to see things we should not see.

2. once we go inside the variant could we see to which panels the variatns belog too as we do for the variants from the CLinical SNV and INDELs ?

**Comment by dnil** [comment]
If you could agree on panels, we could fix that. It's a fairly big undertaking, so we should be clear that it is needed.

We've had some discussion back and forth; our senior clinicians are not unanimous. The current status is that it is deemed more important to have a good routine for interpretation and a policy for what to report back in place. Don't click it unless you have thought it through. 

I personally find it difficult separating phenotypes, as some of the traditional late onset disorders cause juvenile forms with different, even more serious character when the expansion is large.

**Comment by 4WGH** [comment]
Sorry can not see how filtering by paneL (for the ones who want) is a problem.
It doesn't not remove the possibility to look at all variants. (for you clinician) :)

**Comment by dnil** [comment]
Its a decent amount of overhead and maintenance for a small, but actively growing number of genes. Just to be sure; are you clear on what genes will go onto your panels?

**Comment by TJO-Lund** [comment]
I also see a great value for us in Lund to be able to filter the STR-view according to the indication at hand. For example when analyzing a child for rare disease (syndrome) we would like to avoid findings in a list of genes we use (as a gene list in Scout) for adult patients with the indication "Neurodegeneration" (which for example includes HTT).

**Comment by dnil** [comment]
Understood. It would be nice to do in conjunction with a more general panel refurbish including those regions. But, this could be handled by e.g. connecting the most plausible gene involved with each expansion as an HGNC-id, and adding filters. Its not done in a wink, but not too bad either.

Food for thought in the meantime, what of juvenile HTT etc? 😉 Would your list(s) include ATXN7 and others with actual variable age of onset, or would you end up with essentially no gain in diagnostic yield?

**Comment by TJO-Lund** [comment]
After discussing this issue today with Hans E., from our end i Lund, this possibility would be nice to have but not essential for our work.

**Comment by dnil** [comment]
Fixed by #2208. This will require a pipeline side upgrade to Stranger v0.7 to actually filter based on genes. Old cases will still display but gene panel/symbol filtering will remain useless - as the old variants have no proper genes assigned. Enjoy!
