### ISSUE TITLE
Variants with wrong ExAC frequencies

### ISSUE THREAD

**Issue by Bianca-T** [Clinical-Genomics/scout#134]
Hi,

I found cases of wrongly assigned ExAC frequencies. See the screeshot below for two examples.
This will affect filtering. Moreover it would be simpler to have "N/A" or "none" for variants that are not reported in ExAC in order to avoid clicking to the ExAC link. 

**Example 1:**
![image](https://cloud.githubusercontent.com/assets/5881356/8417918/f27fed2c-1eaf-11e5-917a-e94619c15ac7.png)
![image](https://cloud.githubusercontent.com/assets/5881356/8417919/f8754d58-1eaf-11e5-9523-1e99cb7fa7be.png)

**Example 2:**
![image](https://cloud.githubusercontent.com/assets/5881356/8417936/199a9fa6-1eb0-11e5-9024-61e7149c03e4.png)
![image](https://cloud.githubusercontent.com/assets/5881356/8417943/241c7ba2-1eb0-11e5-8d2f-9fd563b2bffa.png)

Thanks.

/Bianca

**Comment by robinandeer** [comment]
Hi @Bianca-T!

You are right in that the frequencies differ in these cases. The only reason I can see is that the website is using a more up-to-date version of their database which would explain some differences.

We need to further investigate why we aren't detecting variants that haven't been annotated by ExAC though. I will defer this to @moonso for now (freq = 0.00000 in database)

Thanks again for being very clear in your feedback :+1:

**Comment by vwirta** [comment]
Kicki from Klinisk Genetik reports on a similar observation for F0001505 , variant RAI1. Scout = 0, ExAC = 0.42

[RAI1 variant.pdf | uploaded via ZenHub](https://files.zenhub.io/560d818ae04cf77449953905)

**Comment by moonso** [comment]
I think this is a problem that has to do with indels. When we search for a match we check if the alternative allele for a variant is the same as the alternative allele in the database.
It could be a problem with how these alleles are represented in the vcf format.
We are trying to solve this.

Thank you for spotting the problem!

**Comment by dnil** [comment]
All are indels, and most are non-PASS variants in ExAC. Dunno how you handle the latter on lookups?

**Comment by dnil** [comment]
One more from the choir: 

19-10270746-GA-G Scout-ExAC: 0, ExAC site, through linkout: 0.63, up to 0.79 in subpop.
Multiallelic site in addition to indel, if that may be a clue. 

// Daniel

**Comment by henrikstranneheim** [comment]
The new production code uses VT to decompose multiallelic sites, so this should take care of this issue. It would be nice to rerun one of these samples using the new production code and make sure that the issue is resolved.

**Comment by moonso** [comment]
@emmser can you rerun one if the above cases so we can have a look if the issue is solved?

**Comment by emmser** [comment]
Reruns shall be ordered through SupportSystem and logged i tickets.

**Comment by vwirta** [comment]
Do reruns of cases listed above - check if changes implemented have corrected / solved the issue. 
Send e-mail to clinics of cases that have been rerun.

@b4ckm4n

**Comment by moonso** [comment]
Hello again!
We have investigated this and in our new analysis this will be solved. When the multi allelic calls are splitted and truncated we annotate the ExAC frequency.
For @Bianca-T case we can see this line in the ExAC file:

```
11      111897028       .       GT      G       991765  PASS    AC=3891;AC_AFR=151;AC_AMR=39;AC_Adj=1718;AC_EAS=47;AC_FIN=105;AC_Het=1652;AC_Hom=2;AC_NFE=817;AC_OTH=15;AC_SAS=544;AF=0.038;
```
As you can see ```AF=0.38``` and this is what the new analysis of your case is annotated with, maybe it is not uploaded to scout yet but @emmser or @b4ckm4n will fix this soon.

The ExAC version used here is ```ExAC.r0.3.sites.vep.vcf.gz``` it differs from the ExAC homepage so we will see if we can download a later version soon.

Måns
