### ISSUE TITLE
Causative variants

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#1341]
if would be very usefull to be able to export the list of causative variants in a file compatible with excell .

It would be great that it appears that the CLinVar submission has been done

**Comment by northwestwitch** [comment]
@mayabrandi this is a relatively easy one, check at the code in the dashboard: https://scout-stage.scilifelab.se/dashboard , variant statistics tab.

![image](https://user-images.githubusercontent.com/28093618/67204807-9b13db00-f40e-11e9-85de-1cca9f4e676f.png)

You could add a similar function to the causatives variants page: https://scout-stage.scilifelab.se/cust003/causatives.

**Comment by dnil** [comment]
Closed by #1423! Nicely done!
