### ISSUE TITLE
Dismissed variants for a case should show on research view

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#1344]
If a variant is dismissed on clinical analysis, it should show as such also on research..

**Comment by moonso** [comment]
Should this be shown between cases like ACMG?

**Comment by dnil** [comment]
No, generally that is over the top. Consider actual pathogenic recessive carrier status. Those would be dismissed for most individuals with them. One could consider showing certain categories, such as "technical issue", that would be of interest regardless of phenotype etc.

But, you are onto something good here! Perhaps they should be shown as such *within* the case? Clinical variants can be dismissed on grounds of too little knowledge, novel mutation types etc which would not be applicable to research analysis.
