### ISSUE TITLE
panel history is incorrect

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#1347]
![bild](https://user-images.githubusercontent.com/12525201/65941133-991bb500-e42a-11e9-9124-9bd74b10ab1b.png)

 the dates for the different versions of panels: IEM, MIT, EP, ENDO are incorrecrt 
see picture

v14 correct
v13 correct
v12  should be 2018-02-05
v11 should be 2017-09-XX
v10 correct
v9.4 correct

OBS!!!! for panel PEDHEP we started with version 10,1 (not 10.0!!!!!!)
v14 correct
v13 correct
v12  should be 2018-02-05
v11 should be 2017-09-XX
v10.1 should be 2017-05-03

**Comment by northwestwitch** [comment]
It's not really a bug, if an old bug, that now it's fixed. I'll change the dates in the database.

**Comment by dnil** [comment]
Yeah, perhaps from changes during #1095, which has been resolved.

**Comment by northwestwitch** [comment]
Fixed. For the fields where you have XX I chose the 15th of the month, which is in the middle, hope it is fine!

![image](https://user-images.githubusercontent.com/28093618/66047178-9f438b80-e527-11e9-8a1f-a6ac6e2df3e8.png)

**Comment by northwestwitch** [comment]
Closing this, please reopen if something needs fixing!
