### ISSUE TITLE
Meaning of variants "not loaded"

### ISSUE THREAD

**Issue by Bianca-T** [Clinical-Genomics/scout#135]
Hi,

What is the meaning of variants "not loaded" among list of variants tagged as AR_comp?
See screenshot below for clarity.

Thanks,
Bianca

![image](https://cloud.githubusercontent.com/assets/5881356/8419207/4dd7a248-1eb8-11e5-9538-c79046fc2724.png)

**Comment by robinandeer** [comment]
We only load the 5000 top ranked variants by default. If a compound pair is specified as "Not loaded" it means that the rank score has placed it below this cutoff and is likely not of interest. We can possibly load more variants upon request.

ps. thanks for uploading the screenshot! :smiley:  ds.
