### ISSUE TITLE
Wrong position in a transcript

### ISSUE THREAD

**Issue by 47KW** [Clinical-Genomics/scout#1353]
Hi,
the variant annotation to HGNC primary transcript is incorrect. c.4708 should be c.4711 for NM_000068

https://scout.scilifelab.se/cust002/F0013714/8304fc3d8b27fe29a3b8a614812452c2

**Comment by dnil** [comment]
First few ¢: NM_000068 was recently updated to NM_000068.4 (this August) from NM_000068.3 (from march this year) with another 19 bp..

**Comment by moonso** [comment]
Hi, this is annotated in the pipeline before Scout and is dependent on how updated the database that is used for annotating AA-change is. Unfortunately there is nothing we can do about it in Scout so we have to refer you to https://github.com/Clinical-Genomics/MIP
