### ISSUE TITLE
mtDNA variants missing in Scout

### ISSUE THREAD

**Issue by 1ctw** [Clinical-Genomics/scout#1358]
I noticed that there are mtDNA variants still missing in Scout. The variants in the D-loop is still not there but they are in the mtDNA report.

Example case 17031:
40 variants in mtDNA report but only 28 showing up in Scout.

**Comment by northwestwitch** [comment]
Have you tried removing the preselected gene panel in the filters?

**Comment by 1ctw** [comment]
Yes, that doesn´t help...they are still missing.

**Comment by northwestwitch** [comment]
That's weird, if I remove the preselected panel I count 42 variants in the list of the MT variants returned, same number of variants that is in the report.

**Comment by 1ctw** [comment]
I can only see these 28 variants. They are all in genes. The ones in the D-loop is missing here but they are in the report.

**Comment by 1ctw** [comment]
Från: Chiara Rasi <notifications@github.com>
Skickat: den 2 oktober 2019 16:19
Till: Clinical-Genomics/scout <scout@noreply.github.com>
Kopia: Helene Bruhn <helene.bruhn@sll.se>; Author <author@noreply.github.com>
Ämne: Re: [Clinical-Genomics/scout] mtDNA variants missing in Scout (#1358)


That's weird, if I remove the preselected panel I count 42 variants in the list of the MT variants returned, same number of variants that is in the report.

**Comment by 1ctw** [comment]
Jag tried to send you a picutre of what I see above, but you can not see it can you? 

Henrik told me yesterday since we see it in the report, the variants are in Scout back-end but they are not shown front-end (the view I see). Does this make sence for you?

**Comment by northwestwitch** [comment]
Just to be sure we do the same type of search, in the variants page, filters, you look for chromosome:'MT and all other filters are empty?

**Comment by northwestwitch** [comment]
No, sorry I don't see the pic. Im not at the office yet (train problems)
but as soon as I arrive I'll get back to you. We could continue the
discussion by email. Try to send the pic to my email instead.

**Comment by 1ctw** [comment]
Now I understand what you mean:) I am not used to analyze mtDNA like that. We always use panel "Mitochondrial DNA" under Gene Panels in the Filters. When I do as you say I can see them.

**Comment by 1ctw** [comment]
I guess this is because of how we created the gene panel from the beginning. It only contains the parts of mtDNA which have known genes with HGNC symbols.

If we don´t figure out to change the panel somehow we will have to do the analysis as you suggest for mtDNA. Now when we now how it works it is not a big problem.

**Comment by northwestwitch** [comment]
Aaah that's why! Nice that we understood why. 😊

Closing the issue then!

**Comment by northwestwitch** [comment]
Yeah you either update the panel or look for MT chrom. Maybe the latter option is the easiest!

**Comment by dnil** [comment]
This could also be solved with the introduction of Regions to gene panels (cf panelApp). This will be appreciated for leukaemia and certain structural variants as well. Fairly big change, so we should collect use-cases..
