### ISSUE TITLE
Sanger link to variant is not working. FIXED

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#136]
Hi,
in the activity window if appear the following information

Nicole Lesko ordered sanger sequencing for e12902b2d8b26c80678471c63051f518 2 months ago
where "e12902b2d8b26c80678471c63051f5182" looks like a link that would take us to the variant for which Sanger has been ordered, but if I click on it nothing happen.
Is this a bug? or is not supposed to be a link?
thanks for help,
Michela

**Comment by robinandeer** [comment]
Link points to the case instead of the variant

**Comment by moonso** [comment]
Fixed

**Comment by 4WGH** [comment]
great! thanks!
Michela
 
 -----Måns Magnusson <notifications@github.com> skrev: ----- 

Till: Clinical-Genomics/scout <scout@noreply.github.com>Från: Måns Magnusson <notifications@github.com>Datum: 2015-10-21 15:09Kopia: 4WGH <michela.barbaro@karolinska.se>Ärende: Re: [scout] Sanger link to variant is not working (#136)
Fixed
