### ISSUE TITLE
Swap 'next page' and 'previous page' buttons on all variants page

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#1367]
It's more user friendly to have next page on the right and previous page on the left. Now it's the other way around

**Comment by northwestwitch** [comment]
This is basically the problem:
![image](https://user-images.githubusercontent.com/28093618/67082989-934c0080-f19a-11e9-999d-513398726221.png)

We want to have next page on the right, and previous page on the left.
This should be done in 
- variants/variants.html 
- variants/sv-variants.html
- variants/cancer-variants.html
- variants/str-variants.html

**Comment by dnil** [comment]
Closed by #1412.
