### ISSUE TITLE
variant page is occasionally slow again on excessive number of matching cases

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#1376]
See discussion on servers repo (https://github.com/Clinical-Genomics/servers/issues/211), and in particular e.g.

https://scout.scilifelab.se/cust000/GSU734/639d6f1bf56c9a12547c11041d4de1cc

**Comment by moonso** [comment]
@dnil , @northwestwitch could you point to the code block here that you have identified as slow?

**Comment by dnil** [comment]
@northwestwitch has a branch with actual numerical measurement on a per block and variant basis. That worked really well in the general case. I'm just using male intuition (killgissar). It seems an interesting coincidence that the slow variant makes heavy use of observations, so calls to that and esp the controller function observations?

**Comment by northwestwitch** [comment]
I had it this measurement branch, then I removed the measurement code. I'll re-create it!

**Comment by 4WGH** [comment]
problem again today for several users. the uploasd is so slow that for some variantswe get te gaTe error message

**Comment by northwestwitch** [comment]
> problem again today for several users. the uploasd is so slow that for some variantswe get te gaTe error message

Hi! We are aware, we'll try to fix this ASAP!

**Comment by dnil** [comment]
Load on clinical-db is high (>6); LIMS in particular is often quite busy. And mongo is now closing on 50 Mb, so perhaps good to cycle it when you are at it? @ingkebil

**Comment by ingkebil** [comment]
restarted mongodb now.

I've asked IT to up the memory on LIMS (we have some wiggle room) and lock it to a limited amount of cores.

**Comment by northwestwitch** [comment]
> restarted mongodb now.
> 
> I've asked IT to up the memory on LIMS (we have some wiggle room) and lock it to a limited amount of cores.

Thanks!

**Comment by moonso** [comment]
@northwestwitch , could you upload that analysis branch?

**Comment by northwestwitch** [comment]
> @northwestwitch , could you upload that analysis branch? There must be something that we can do about this one, it would be nice if you already did the analysis so don't need to redo it.

https://github.com/Clinical-Genomics/scout/tree/test_variant_speed
