### ISSUE TITLE
Map ClinVar significance terms to numbers

### ISSUE THREAD

**Issue by moonso** [Clinical-Genomics/scout#1377]
This is a suggested mapping, please give your opinion if you have any other idea @henrikstranneheim @dnil . It would be nice to see what mapping you use in Lund @bjhall 

| Term | Number |
| ----- | -------- |
| Pathogenic | 5 |
| Likely pathogenic | 4 |
| Conflicting_interpretations_of_pathogenecity | 3 |
| Uncertain significance | 0 |
| likely benign | 2 |
| benign | 1 |
| affects | 20 |
| association | 21 |
| drug response | 22 |
| other | 23 |
| protective | 24 |
| risk_factor | 25 |
| association_not_found | 26 |
| drug_response | 27 |
| not_provided | 100 |

**Comment by moonso** [comment]
And similar with the review status:

| Term | Number |
| --- | --- |
| reviewed_by_expert_panel | 5 |
| practice_guidelines | 4 |
| criteria_provided | 3 |
| conflicting_interpretations | 3 |
| multiple_submitters | 3 |
| no_conflicts | 3 |
| single_submitter | 3 |
| no_assertion_criteria_provided | 3 |

**Comment by dnil** [comment]
Looks good to me: Swap conflicting and Uncertain significance,

**Comment by moonso** [comment]
What do you mean @dnil ? They are in different tables...

**Comment by moonso** [comment]
Aha you mean 3 and 4 in the first table! What numbers should we use on those?

**Comment by dnil** [comment]
At a meeting.. 

Conflicting_interpretations_of_pathogenecity | 3
Uncertain significance | 0

is weird. Uncertain (VUS) is 3, conflict is typically 1.5, 4.5 or possibly 2.5 or 3.5.

**Comment by moonso** [comment]
Is it important to use same numbers like acmg? Or could we just assign any number. So least interesting would be 1 and pathogenic 12 or something?

**Comment by moonso** [comment]
Ok here is the final solution that I have chosen. It has the advantage that it will work with existing values in the database.

| Term | Number |
| ----- | -------- |
| other | 255 |
| not_provided | 1 |
| drug_response | 6 |
| association_not_found | 13 |
| risk_factor | 12 |
| protective | 11 |
| association | 10 |
| affects | 9 |
| histocompatibility | 7 |
| benign | 2 |
| likely_benign | 3 |
| conflicting_interpretations_of_pathogenicity |8 |
| uncertain_significance | 0 |
| likely_pathogenic | 4 |
| pathogenic | 5 |

**Comment by henrikstranneheim** [comment]
Looks good! It is nice for now to have backwards compatibility. We can then provide another map of how each term should be viewed in clinical significance when updating clinvar and recalculating the status for each variant i.e. if they moved up or down in pathogenicity.
