### ISSUE TITLE
F0026339-2

### ISSUE THREAD

**Issue by KickiLagerstedt** [Clinical-Genomics/scout#1384]
Fel pappa???

Vad betyder det att det är kryss på pappa?
https://scout.scilifelab.se/cust002/F0026339-2

Vi har testat DNA här med polymorfa markörer och pappa är pappa - har vi skickat fel DNA?

// Kicki & Helena

**Comment by northwestwitch** [comment]
@emiliaol could you check this in genotype? I don't have access to the app. Thanks!

**Comment by moahaegglund** [comment]
Hej,

Krysset beror på att släktskapsanalysen i Peddy blir underkänd mellan barn och pappa. Enligt Plink, det andra programmet som kollar släktskap, så är det rätt pappa. Håller på att kollar lite noggrannare på vad det här beror på så jag återkommer.

**Comment by moahaegglund** [comment]
Hej igen,

Bifogar en Excelfil där ni kan se värdena från Peddy för det här caset och tre andra för jämförelse. Pappan har alltså ett högre ibs0-värde (215) än övriga föräldrar som ligger på 0-10 vilket gör att den underkänns.  "ibs0: the number of sites at which the 2 samples shared no alleles (should approach 0 for parent-child pairs).” (Se [här](https://buildmedia.readthedocs.org/media/pdf/pedagree/latest/pedagree.pdf) under ped_check på sid. 8 för mer info om vad de olika kolumnerna i Excelfilen betyder.) 

Enligt Plink är som sagt det här pappan och även variant_integritys father koll ser bra. Vi tror att det är rätt pappa, Troligtvis är det något annat som påverkar Peddy, kanske kan det vara kvalitén på sekvenseringen eller UPD.

[ped_check.xlsx](https://github.com/Clinical-Genomics/scout/files/3729122/ped_check.xlsx)

**Comment by dnil** [comment]
Tack! Bra idé, men det låter spontant lite högt för UPD också; inte ens med chr1 eller 2 borde man komma riktigt dit? Hur var sekvenseringskvalitén; nära gränsen för Q30%, eller såg det normalbra ut?

**Comment by moahaegglund** [comment]
Q30 ligger mellan 92.6-93.2 för respektive lane för pappan, gränsen är på 75 så det är bra kvalitet. Övriga kvalitetsparametrar i MIP-analysen ser också bra ut så på rak arm verkar inte förklaringen ligga i kvalitén heller. Har du någon annan idé?

**Comment by vwirta** [comment]
Kan detta vara mosaicism? 

Om man drar ut antal reads för resp allel för dessa SNPs, kan man se indikation på mosaicism då?

**Comment by dnil** [comment]
Det verkar som Moa vinner! Lite preliminärt en maternell isodisomi chr 12 enl upd.py. Jag skulle jaga en avmaskerad recessiv variant (synbarligen AR_dn kanske?) på chr12..

**Comment by henrikstranneheim** [comment]
Coolt! Täcks detta upp av nuvarande upd och rhocall eller ska vi fundera på att flagga detta mer tydligt i analysen när peddy ger sådana signaler?

**Comment by dnil** [comment]
Mja, i princip täcks det nog på utvecklingssidan. Det borde synas tydligt i chromograph/IGV. Det finns 26 stora UPD-fönster flaggade för chr12, inget för någon annan kromosom. Och normalt inget..

**Comment by henrikstranneheim** [comment]
👍

**Comment by vwirta** [comment]
coolt!

**Comment by moonso** [comment]
Härligt, då var det utrett!
