### ISSUE TITLE
Wrong link on STR varianT page

### ISSUE THREAD

**Issue by moonso** [Clinical-Genomics/scout#1391]
When entering an STR variant the link back to variant list leads to SNV/Indel and not STRs

**Comment by northwestwitch** [comment]
Didn't we fix it already? Probably it was before bootstrap 4 :-/

**Comment by dnil** [comment]
Well, no; I removed the STR-variant page, using the SNV-variant page instead, but that does have that consequence. I would never notice, since I use my browser-back key for getting back to the variant list. Me fix!

**Comment by dnil** [comment]
Will be closed by #1392, which is ready for review!
