### ISSUE TITLE
Inactive cases not shown

### ISSUE THREAD

**Issue by sofievonlanthen** [Clinical-Genomics/scout#1395]
My understanding from the last Scout user meeting was that inactive cases should always show up after prioritized (if it fits within the number of cases shown) before active and archieved cases, not to miss new inactive cases. 
I just realised that doesn't work. We have asked for a re-run of a case, which has now been placed in inactive. However I can't see the inactive cases unless I change the number of cases shown to 200. 
Also, the re-run case in inactive, has not yet been re-run from what I can tell on the analysis date. should it not move to inactive when the re-run is done, rather than when the re-run has been ordered? Just want to have a simpel way to see if a re-run case is ready. 

/Sofie

**Comment by dnil** [comment]
Hi Sofie!

The routine for flagging rerun cases inactive is indeed overzealous. Thank you for noticing! 
- [ ] The intended behaviour is for cases to go inactive when the results are ready, not when you hit rerun. We will fix!

Inactive cases can accumulate. I'm aware of one institute *cough* that are closing on 100 inactive ones to start from. An option to increasing the total number shown is to search for inactive cases, as with ```status:inactive```in the case search box.

Would it be helpful to you if we increase the default number shown to say 300?

Or to invent a little "re-run ready for analysis" badge for cases when a rerun result is uploaded? The latter is a bit more complex, but doable.

**Comment by sofievonlanthen** [comment]
Ok, thanks for fixing the bug with the re-runs. 

Just to make sure I am not missing anything, if you have 2 prioritized cases and 1 inactive, and then maybe 20 ish active ones, and then of course a bunch on archieved and solved, shouldn't you always see the prioritized and inactive cases and  active ones and fill up with the solved/archieved up to 100? Atm it seems to be more like "some of each"?

**Comment by dnil** [comment]
With the current in flow (and fraction of answered cases that are actually ever flagged archive/solved) we have some 700 cases flagged active and 100 inactive. Its not very productive to scroll through those. I would again recommend using a combination of user assignment, notes in synopsis, HPO-terms, variant pinning, status switching (an inactivation button is already waiting in the next release), and searching for the above. Also a LIMS. But, at least our LIMS is somewhat lacking in keeping track of analysis priority, so I would love to hear suggestions here, as long as they don't involve manually reading a long list! 😊

**Comment by dnil** [comment]
Ok, what I did now in a feature branch was to first fix the unexpected behaviour and add another small badge on the cases page.

When this goes live, there will be no change to status when you hit rerun, but a small badge "rerun pending" will appear on the cases list. When the rerun is done and the case gets updated, said case will go inactive if it was previously active or archived. The "rerun pending" badge will then be removed, and replaced with the "rerun" badge.

Sound good?

**Comment by sofievonlanthen** [comment]
Perfect! Thanks Daniel.

------------------------
Sofie Vonlanthen
Molekylärbiolog
Klinisk Immunologi och transfusionsmedicin
F79 Karolinska Universitetsjukhuset, Huddinge
141 86 Stockholm
tel: 072 5955823

Från: Daniel Nilsson <notifications@github.com>
Skickat: den 18 oktober 2019 22:19
Till: Clinical-Genomics/scout <scout@noreply.github.com>
Kopia: Sofie Vonlanthen <sofie.vonlanthen@sll.se>; Author <author@noreply.github.com>
Ämne: Re: [Clinical-Genomics/scout] Inactive cases not shown (#1395)


Ok, what I did now in a feature branch was to first fix the unexpected behaviour and add another small badge on the cases page.

When this goes live, there will be no change to status when you hit rerun, but a small badge "rerun pending" will appear on the cases list. When the rerun is done and the case gets updated, said case will go inactive if it was previously active or archived. The "rerun pending" badge will then be removed, and replaced with the "rerun" badge.

Sound good?
