### ISSUE TITLE
Incompatible with latest mongoegine

### ISSUE THREAD

**Issue by robinandeer** [Clinical-Genomics/scout#140]
MongoEngine 0.10 removes ``get_or_create`` so we should update for this :smiley:

**Comment by moonso** [comment]
Ok, do you have a link to the new release?

**Comment by robinandeer** [comment]
Sure, this is the docs reference:
http://docs.mongoengine.org/guide/querying.html#retrieving-unique-results

**Comment by robinandeer** [comment]
I'm holding off until the adapter is updated with methods to get and create user models
