### ISSUE TITLE
Issues installing scout

### ISSUE THREAD

**Issue by mayabrandi** [Clinical-Genomics/scout#1404]
Im having issues with the installation. The problem is the package  gobject-2.0, which is not found, and which I don't manage to install. When installing, it is suggested that I should add the path to PKG_CONFIG_PATH, but the problem is i cant find the path to where it is installed. Or to be more correct, i don't think it is installed yet, since that is what im trying to do..

Output from running scout:

`(scout) 130-229-12-174-dhcp:scout mayabrandi$ scout setup demo
Traceback (most recent call last):
  File "/Users/mayabrandi/anaconda/envs/scout/bin/scout", line 11, in <module>
    load_entry_point('scout-browser', 'console_scripts', 'scout')()
  File "/Users/mayabrandi/anaconda/envs/scout/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/mayabrandi/anaconda/envs/scout/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/Users/mayabrandi/anaconda/envs/scout/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/Users/mayabrandi/anaconda/envs/scout/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/mayabrandi/opt/scout/scout/commands/__init__.py", line 1, in <module>
    from .base import cli
  File "/Users/mayabrandi/opt/scout/scout/commands/base.py", line 10, in <module>
    from scout.server.app import create_app
  File "/Users/mayabrandi/opt/scout/scout/server/app.py", line 31, in <module>
    from .blueprints import (alignviewers, public, genes, cases, login, variants, panels, dashboard,
  File "/Users/mayabrandi/opt/scout/scout/server/blueprints/cases/__init__.py", line 2, in <module>
    from .views import cases_bp
  File "/Users/mayabrandi/opt/scout/scout/server/blueprints/cases/views.py", line 18, in <module>
    from flask_weasyprint import HTML, render_pdf
  File "/Users/mayabrandi/anaconda/envs/scout/lib/python3.7/site-packages/flask_weasyprint/__init__.py", line 13, in <module>
    import weasyprint
  File "/Users/mayabrandi/anaconda/envs/scout/lib/python3.7/site-packages/weasyprint/__init__.py", line 440, in <module>
    from .css import preprocess_stylesheet  # noqa isort:skip
  File "/Users/mayabrandi/anaconda/envs/scout/lib/python3.7/site-packages/weasyprint/css/__init__.py", line 30, in <module>
    from . import computed_values, media_queries
  File "/Users/mayabrandi/anaconda/envs/scout/lib/python3.7/site-packages/weasyprint/css/computed_values.py", line 17, in <module>
    from .. import text
  File "/Users/mayabrandi/anaconda/envs/scout/lib/python3.7/site-packages/weasyprint/text.py", line 257, in <module>
    'libgobject-2.0.dylib')
  File "/Users/mayabrandi/anaconda/envs/scout/lib/python3.7/site-packages/weasyprint/text.py", line 253, in dlopen
    return ffi.dlopen(names[0])  # pragma: no cover
  File "/Users/mayabrandi/anaconda/envs/scout/lib/python3.7/site-packages/cffi/api.py", line 146, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "/Users/mayabrandi/anaconda/envs/scout/lib/python3.7/site-packages/cffi/api.py", line 828, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "/Users/mayabrandi/anaconda/envs/scout/lib/python3.7/site-packages/cffi/api.py", line 823, in _load_backend_lib
    raise OSError(msg)
OSError: cannot load library 'gobject-2.0': dlopen(gobject-2.0, 2): image not found.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'gobject-2.0'`

**Output from trying to install pygobject:**

`pip install pygobject
Collecting pygobject
  Using cached https://files.pythonhosted.org/packages/46/8a/b183f3edc812d4d28c8b671a922b5bc2863be5d38c56b3ad9155815e78dd/PyGObject-3.34.0.tar.gz
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/mayabrandi/anaconda/envs/scout/bin/python /Users/mayabrandi/anaconda/envs/scout/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/18/rs1z1bd90fn1gx4s00hf66d00002xs/T/pip-build-env-6320oah8/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel pycairo
       cwd: None
  Complete output (56 lines):
  Collecting setuptools
    Using cached https://files.pythonhosted.org/packages/6a/9a/50fadfd53ec909e4399b67c74cc7f4e883488035cfcdb90b685758fa8b34/setuptools-41.4.0-py2.py3-none-any.whl
  Collecting wheel
    Using cached https://files.pythonhosted.org/packages/00/83/b4a77d044e78ad1a45610eb88f745be2fd2c6d658f9798a15e384b7d57c9/wheel-0.33.6-py2.py3-none-any.whl
  Collecting pycairo
    Using cached https://files.pythonhosted.org/packages/48/20/5e83af98eb897935bf7dc39455e892ba866feebb9b7c3b392982866f9958/pycairo-1.18.1.tar.gz
  Building wheels for collected packages: pycairo
    Building wheel for pycairo (setup.py): started
    Building wheel for pycairo (setup.py): finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /Users/mayabrandi/anaconda/envs/scout/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/18/rs1z1bd90fn1gx4s00hf66d00002xs/T/pip-install-hxbh4f0s/pycairo/setup.py'"'"'; __file__='"'"'/private/var/folders/18/rs1z1bd90fn1gx4s00hf66d00002xs/T/pip-install-hxbh4f0s/pycairo/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/18/rs1z1bd90fn1gx4s00hf66d00002xs/T/pip-wheel-g73jrxfe --python-tag cp37
         cwd: /private/var/folders/18/rs1z1bd90fn1gx4s00hf66d00002xs/T/pip-install-hxbh4f0s/pycairo/
    Complete output (15 lines):
    running bdist_wheel
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.7-x86_64-3.7
    creating build/lib.macosx-10.7-x86_64-3.7/cairo
    copying cairo/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/cairo
    copying cairo/__init__.pyi -> build/lib.macosx-10.7-x86_64-3.7/cairo
    copying cairo/py.typed -> build/lib.macosx-10.7-x86_64-3.7/cairo
    running build_ext
    Package gobject-2.0 was not found in the pkg-config search path.
    Perhaps you should add the directory containing `gobject-2.0.pc'
    to the PKG_CONFIG_PATH environment variable
    Package 'gobject-2.0', required by 'cairo', not found
    Command '['pkg-config', '--print-errors', '--exists', 'cairo >= 1.13.1']' returned non-zero exit status 1.
    ----------------------------------------
    ERROR: Failed building wheel for pycairo
    Running setup.py clean for pycairo
  Failed to build pycairo
  Installing collected packages: setuptools, wheel, pycairo
    Running setup.py install for pycairo: started
      Running setup.py install for pycairo: finished with status 'error'
      ERROR: Command errored out with exit status 1:
       command: /Users/mayabrandi/anaconda/envs/scout/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/18/rs1z1bd90fn1gx4s00hf66d00002xs/T/pip-install-hxbh4f0s/pycairo/setup.py'"'"'; __file__='"'"'/private/var/folders/18/rs1z1bd90fn1gx4s00hf66d00002xs/T/pip-install-hxbh4f0s/pycairo/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/18/rs1z1bd90fn1gx4s00hf66d00002xs/T/pip-record-sozcbsn5/install-record.txt --single-version-externally-managed --prefix /private/var/folders/18/rs1z1bd90fn1gx4s00hf66d00002xs/T/pip-build-env-6320oah8/overlay --compile
           cwd: /private/var/folders/18/rs1z1bd90fn1gx4s00hf66d00002xs/T/pip-install-hxbh4f0s/pycairo/
      Complete output (15 lines):
      running install
      running build
      running build_py
      creating build
      creating build/lib.macosx-10.7-x86_64-3.7
      creating build/lib.macosx-10.7-x86_64-3.7/cairo
      copying cairo/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/cairo
      copying cairo/__init__.pyi -> build/lib.macosx-10.7-x86_64-3.7/cairo
      copying cairo/py.typed -> build/lib.macosx-10.7-x86_64-3.7/cairo
      running build_ext
      Package gobject-2.0 was not found in the pkg-config search path.
      Perhaps you should add the directory containing `gobject-2.0.pc'
      to the PKG_CONFIG_PATH environment variable
      Package 'gobject-2.0', required by 'cairo', not found
      Command '['pkg-config', '--print-errors', '--exists', 'cairo >= 1.13.1']' returned non-zero exit status 1.
      ----------------------------------------
  ERROR: Command errored out with exit status 1: /Users/mayabrandi/anaconda/envs/scout/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/18/rs1z1bd90fn1gx4s00hf66d00002xs/T/pip-install-hxbh4f0s/pycairo/setup.py'"'"'; __file__='"'"'/private/var/folders/18/rs1z1bd90fn1gx4s00hf66d00002xs/T/pip-install-hxbh4f0s/pycairo/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/18/rs1z1bd90fn1gx4s00hf66d00002xs/T/pip-record-sozcbsn5/install-record.txt --single-version-externally-managed --prefix /private/var/folders/18/rs1z1bd90fn1gx4s00hf66d00002xs/T/pip-build-env-6320oah8/overlay --compile Check the logs for full command output.
  ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/mayabrandi/anaconda/envs/scout/bin/python /Users/mayabrandi/anaconda/envs/scout/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/18/rs1z1bd90fn1gx4s00hf66d00002xs/T/pip-build-env-6320oah8/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel pycairo Check the logs for full command output.`

**Comment by mayabrandi** [comment]
issue seems to be solved now. I did so many things on the way trying to debug, so its hard to say which of them actually were needed. These were the last two things I did that made it work:

export PKG_CONFIG_PATH='/usr/local/Cellar/glib/2.62.1/lib/pkgconfig/'
conda install -c conda-forge pygobject

**Comment by northwestwitch** [comment]
Nice!!! So we know how to fix it it this happens again!
