### ISSUE TITLE
Gene panel order on case view

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#1406]
Gene panel order logic; eg alphabetical.

**Comment by northwestwitch** [comment]
This looks an easy thing to do for when you have time @mayabrandi

**Comment by northwestwitch** [comment]
Gene panels page is available in the dropdown on the right of the page logo:

![image](https://user-images.githubusercontent.com/28093618/67834908-ebfb9180-fae8-11e9-9ac2-f7daff811ba3.png)

**Comment by dnil** [comment]
Right, this list on the case page is what needs sorting: 
<img width="665" alt="Screenshot 2019-10-30 at 08 15 29" src="https://user-images.githubusercontent.com/758570/67836683-8a89f180-faed-11e9-83ab-cde15f960eae.png">

**Comment by northwestwitch** [comment]
Ahhh I see, removing my previous comment then!

**Comment by northwestwitch** [comment]
> Right, this list on the case page is what needs sorting:
> <img alt="Screenshot 2019-10-30 at 08 15 29" width="665" src="https://user-images.githubusercontent.com/758570/67836683-8a89f180-faed-11e9-83ab-cde15f960eae.png">

Actually if I read the issue title properly I could have guessed :)
