### ISSUE TITLE
Gene popover with phenotypes

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#1407]
Displaying OMIM phenotypes under/with inheritance mode in popover on variants page is requested by clinicians.

**Comment by northwestwitch** [comment]
You could do this one @moonso

**Comment by moonso** [comment]
It's already in place...
<img width="1440" alt="Skärmavbild 2019-10-23 kl  09 35 19" src="https://user-images.githubusercontent.com/405278/67368966-7f2c4880-f578-11e9-8c9d-801c9858f0d1.png">

**Comment by moonso** [comment]
Or do you mean something else?

**Comment by dnil** [comment]
Yeah, add disease descriptions to that as well. Gives a clinician a quick feel for if the variant is phenotypically relevant even if they dont recognise the gene.

**Comment by dnil** [comment]
I had a quick look yesterday - technically its not really hard; just a bit involved in the variant / variants controllers so I paused it. The tricky part I suppose is not getting a hover that covers the whole page... X-) Good luck!

**Comment by moonso** [comment]
Ok... so how should one solve that?

**Comment by dnil** [comment]
Some creativity? E.g. show only the first N, then an ellipsis or text (and 19 other diseases). For the most genes this will be 1-3 disorders. Then some culprits are described as *many* things..

**Comment by dnil** [comment]
It does touch the variants controller, I suppose, unless I misread it and the info is already there?

**Comment by northwestwitch** [comment]
Ok maybe I took the wrong task for now, let's leave for when we merge #1415
