### ISSUE TITLE
SV variants filters query is broken

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#1414]
I noticed while working on another PR. Looks like variant_type filter param is always empty. 
I can fix it in the PR I'm working at!

**Comment by dnil** [comment]
Hm, the SV research list seems blank on SWEDAC-2019-HG-05-Trio-NovaSeq..

**Comment by northwestwitch** [comment]
I can confirm it's my branch, sorry for the scare. Closing this now! :)
