### ISSUE TITLE
gnomAD freq. is wrong

### ISSUE THREAD

**Issue by 47KW** [Clinical-Genomics/scout#1419]
https://scout.scilifelab.se/cust002/F0023816-2/8b1e4d9154dd6f5bad4d608a4ff525ee

**Comment by moonso** [comment]
@henrikstranneheim is this the same thing like before?

**Comment by henrikstranneheim** [comment]
No, it is just that we are using gnomad version 2.0.1 and the gnomad browser is using 2.1.1.

We are planning to update to 2.1.1 for grch37 with the next release of MIP schedule before X-mas.

**Comment by moonso** [comment]
Ok then we have the solution for that. Keep up the good work @47KW !

**Comment by dnil** [comment]
And I'm glad we can now / still reliably see that variant. As common as it is around here, it is still important!
