### ISSUE TITLE
Show Stranger limits on STR view: PATHOLOGIC_MIN, NORMAL_MAX

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#1425]
Thanks @bjhall! See https://github.com/moonso/stranger/pull/13.

**Comment by bjhall** [comment]
I could make an attempt at implementing this (next week...), if no one else feels obliged.

Any opinions on how to present it? Should it simply be two new columns named something like "Minimum units, patholocical" and "Maximum units, normal". I am feeling that there is a better way of showing it...
