### ISSUE TITLE
Kan inte nå HPO fr SCOUT

### ISSUE THREAD

**Issue by KickiLagerstedt** [Clinical-Genomics/scout#1436]
Eller ligger den servern nere bara???

**Comment by dnil** [comment]
Nej, det verkar funka. Kan du ge ett specifikt fall?

**Comment by KickiLagerstedt** [comment]
https://scout.scilifelab.se/cust002/F0032094

Helena når inte heller (F0025037)

**Comment by KickiLagerstedt** [comment]
Dvs när vi trycker på "HPO web" så nås vi av felmeddelande 

"Sorry, we could not find that page. Please ensure your URL is correct or the term you are looking for exists when searching.

If you believe this is a mistake please let us know on our issue tracker."

**Comment by dnil** [comment]
Japp, så rätt! De verkar ha möblerat om hos sig. Vi får ändra från länkar på formen 
´´´https://hpo.jax.org/app/browse/term?id=HP:0002647´´´
till i stil med
´´´https://hpo.jax.org/app/browse/term/HP:0002647´´´
Tack för uppmärksamheten!
