### ISSUE TITLE
All variants page length appears to weave?

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#1440]
Page length changes for different pages if viewed as a normal user, due to variants discarded from access being denied. Rewrite the gene_variants controller..

**Comment by dnil** [comment]
Or perhaps it would be possible to apply jquery.dataTables with pagination?

**Comment by northwestwitch** [comment]
Is this still actual @dnil?

**Comment by dnil** [comment]
I would imagine so: I suppose test with a non-admin and not too well connected account for the full effect of cases trimmed off the list for not being allowed after they are returned from the db adapter!

**Comment by northwestwitch** [comment]
Is "All Variants" this? 

<img width="206" alt="image" src="https://user-images.githubusercontent.com/28093618/168068524-6e303d5e-4f47-4e09-83ad-3782c0d9642e.png">

**Comment by dnil** [comment]
Yeah, exactly! Sorry about the heading. There are a couple of clues in the first comments, e.g. 

> Rewrite the gene_variants controller..

**Comment by northwestwitch** [comment]
No problem, I think the Functionality was named something like "All SNVs and INDELs" at the time. I just wanted to be sure. I'll try to fix what's wrong with it!
