### ISSUE TITLE
Phenotype search is down [dev version]

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#1447]
Entering search terms fires no autocomplete, and searching anyway causes crashes - perhaps on a string decompose expecting an auto-complete style string?

**Comment by northwestwitch** [comment]
In which form is the error, cases, case?

**Comment by dnil** [comment]
Phenotypes!

**Comment by northwestwitch** [comment]
I think autocompletion was never implemented for this page. I don't see any code relative to this in the old scout versions. I'll add it!

**Comment by dnil** [comment]
Ah, ok! Very nice! Still, it crashes upon search, so something is off..

**Comment by northwestwitch** [comment]
I'll fix it
