### ISSUE TITLE
Scout-Stage - Saknar genpanel i sidovyn

### ISSUE THREAD

**Issue by KickiLagerstedt** [Clinical-Genomics/scout#1449]
Ta med vilken genpanel som är förvald.
För mörk färg - gör den ljusare

(kan inte stoppa in bild...)

**Comment by dnil** [comment]
Bra idé med default-panel mer i blickfånget! 

Vi får ha omröstning om färgerna. Det är precis samma som bakgrunden på nästan alla appar på mitt skrivbord, så förstår inte riktigt varför. Motivera gärna!
