### ISSUE TITLE
Panel selectpicker in some disorder [dev version]

### ISSUE THREAD

**Issue by KickiLagerstedt** [Clinical-Genomics/scout#1450]
Gjorde först en HPO sökning - allt frid och fröjd
Sedan vill jag titta på CTD-panelen - går att öppna sidan men sedan när man trycker "Clinical Filter" så hoppar den tillbaka till HPO panelen som förvald.

https://scout-stage.scilifelab.se/cust002/F0032094/variants

Är antagligen OK - bara inte van vid att det är så.

**Comment by KickiLagerstedt** [comment]
Sedan när man ska byta panel är panelerna "huller om buller" - går det att få den i en lista???

**Comment by KickiLagerstedt** [comment]
den = dem

**Comment by KickiLagerstedt** [comment]
Sedan hittar jag inget mer...

**Comment by KickiLagerstedt** [comment]
Sedan hittar jag inget mer...

**Comment by dnil** [comment]
Tack Kicki! Vi kan titta på det tillsammans vid tillfälle, men det låter nog som förväntat beteende. Precis som tidigare så är clinical filter låst till den förvalda panelen. Det som är nytt är att man kan välja att HPO-panelen ska vara förvald. Den förblir sedan det till man väljer bort det.

Om listordningen: det är nog i princip samma som i productionsversionen; se #1406? Isf är det på gång!

**Comment by KickiLagerstedt** [comment]
Nix - inte samma

Genpanelerna ligger huller om buller - skickar bild via mail!

**Comment by dnil** [comment]
![image](https://user-images.githubusercontent.com/758570/68200948-2a012580-ffc1-11e9-87ba-238a77461c62.png)

Ah, jag förstår! Jepp, sådana har vi haft fler av. Tack!

**Comment by dnil** [comment]
Hm, panel names are sometimes really short. Do you know @northwestwitch; do we have to make the selectpicker really short - like col-1 or so - or is there some config option for this?

**Comment by northwestwitch** [comment]
Hi, the reason is a conflict between our css and and the css from the multiselect js library. In fact if you remove this part
```
ul li {
  font-size: 16px;
  display: inline-block;
  padding: 5px 15px;
  height: 50px;
}
```
from the b4_styles.css the multiselect looks nice.

The problem is that if you remove that style part then scout style becomes messy, especially the top bar. It can be fixed but the ul li from scout must be renamed with some custom name and the changes should be applied to all pages.
