### ISSUE TITLE
Scout-Stage Coverage report

### ISSUE THREAD

**Issue by KickiLagerstedt** [Clinical-Genomics/scout#1451]
Det är lite tunnt med info...

https://scout-stage.scilifelab.se/reports/report?sample_id=ACC6318A6&level=10&panel_name=Connective+Tissue+Diseases+%2855.0%29

**Comment by dnil** [comment]
Tack, vi kikar på det - troligen bara lite knas vid uppladdningen på en bakväg.

**Comment by dnil** [comment]
Jo, det verkar så. Uppladdningen av Chanjo-täckning görs separat via cg. Detta fungerar just nu inte i testmiljön, verkar det, men är helt ok i produktion.

```
$ cg upload coverage liveguinea
...
File "/home/proj/bin/conda/envs/S_main/lib/python3.7/site-packages/cg/meta/upload/coverage.py", line 30, in data
    hk_coverage = self.hk.files(version=hk_version.id,
AttributeError: 'NoneType' object has no attribute 'id'
'```
