### ISSUE TITLE
Scout - Stage Ang research list

### ISSUE THREAD

**Issue by KickiLagerstedt** [Clinical-Genomics/scout#1454]
Om man "beställt" Research list så måste man aktivt trycka på pilen för att kunna se att detta är beställt.

Går det att få, som idag, att man ser det om det är valt?

**Comment by KickiLagerstedt** [comment]
Whoops - nu syns det....
Sorry

https://scout-stage.scilifelab.se/cust002/F0032094#

**Comment by dnil** [comment]
Nja, nog bara efter att du själv valt att fälla ut den. Det går definitivt att få den utfälld som standard; borde gå att sätta den utfälld om forskning är beställt.

**Comment by moonso** [comment]
It took me more than one hour to fix this 😆 , but I learned some bootstrap on the way!
