### ISSUE TITLE
Scout for cancer workshop (2019-11-06) notes

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#1460]
**Important features (MVP):**
- Variant Ranking is important
- Scout for cancer and Scout for rare diseases on difference instances and also different institutes so no mix-up of rare cases and cancer ones.
- Introduce a badge for cancer in cases table and search for cancer cases in the cases search
- Chanjo report for cancer cases: modify depth of coverage thresholds.
- Define relevant phenotype groups, HPO terms and cohorts (custom at the institute level)
- Define well how the Ranking is done
- Swegen frequency alongside ExAC or other databases frequencies. Use "Frequencies" instead of ExAC in table header.
- Dump Swegen  frequencies in our database
- Cancer ACMG/AMP different from ACMG for classification of variants
- Pre-fill ACMG/AMP if possible, when possible. Is it feasible.
- Another button for showing SVs
- Wig tracks in igv
- Gene models can be removed in cancer (variant view)
-  Add Swegen in the table of Frequency (variant view)
- Gene specific databases (Braca tp53) could be added
- Investigate what N/A means in local observations, is it 0? Make it clearer in the pages
- GT call : Genotype (GT) is always ./. for tumors, fix it in another way?
- Add filter variants by chromosome and position
- Show genotype calls by caller
- Add institutes and accounts for users
- Add balsamic report to the reports that can be exported

**Nice to have features:**
- Flag variants as germline when info is available
- Ranking of variants based on HPO terms or OMIM diagnosis provided by users. Ranking performed directly in Scout.

**Comment by dnil** [comment]
- [ ] HPO clinical filter button needs to go to "cancer" variants..
- [ ] ACMG/AMP for the classification page.

**Comment by moonso** [comment]
These are all in their own issues now
