### ISSUE TITLE
Quality scores for SVs

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#1464]
As a user of Scout, I would like SV quality scores to be clearly represented and the scale documented. -1 is not a great way to report SV GQ. Likely present on the VCF but may require specialized parsing compared to the SNV GQs.

**Comment by dnil** [comment]
Right @sofievonlanten?

**Comment by moonso** [comment]
How is the quality represented in the SV vcfs? Do you have any input here @henrikstranneheim ?

**Comment by henrikstranneheim** [comment]
I think it is mainly dependent on which caller actually called the variant. They all have their own way of representing GQ. I think Manta always ouputs GQ or another key called MinGQ (filtered). I believe TIDDIT and CNVnator does not output the GQ field. Is that correct @dnil @J35P312 ?

**Comment by sofievonlanthen** [comment]
Would be great to know what the GQ value actually means. I have found variants that have -1 as a value that are true SV, slightly confusing. So if the variant is only called by CNVnator, there will not be an output to GQ?

**Comment by dnil** [comment]
TIDDIT produces a variant level quality in the VCF quality column; also some fairly useful data on number of split and paired reads on each variant (GT). That should be very similar on Manta.
CNVnator produces RD fraction estimates and probability values that could potentially be recast into a quality value - but not in this issue.. 😄
