### ISSUE TITLE
Clincal exome report export - Feature request

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#147]
After going through a case in scout, we typically sit down and write up a short report on the findings, much like the current comments and log. It would save time if I could get a "report" with the top variants (down to some user defined rank threshold) on a long list with the variant comments displayed; e g a pdf or html page. That would also increase my interest in diligently commenting all variants in the interface.

**Comment by dnil** [comment]
E.g. { Gene, Transcript, HGVS } (from "transcript overview"), Frequencies. Chr, Genotype call, Omim Phenotypes, {Rank-score, CADD score} (from "Summary" ), Comments for a very good prototype. For the pretty-pretty version, start with basically a dump of the case page, and merge with coverage report. 
But let's run that by some of the others as well to see what they think would be most useful!

**Comment by robinandeer** [comment]
We should definitely discuss this more before setting a timeline for the completion
Intersting idea :)

**Comment by moonso** [comment]
We can bring this up at the meeting 26/4

**Comment by moonso** [comment]
I hope that this could be a good thing for @patrikgrenfeldt to start with

**Comment by dnil** [comment]
:+1: 
It might be easier to start from #605? But, not really needed. Just a pdf writer for anything touched plus general info will do wonders.

**Comment by dnil** [comment]
Solved by #802! :+1:

**Comment by moonso** [comment]
🎆 🍾 This one should be celebrated!! Almost 3 years old 🙈
