### ISSUE TITLE
dismissed variants

### ISSUE THREAD

**Issue by genecracker** [Clinical-Genomics/scout#1473]
Hi,

When generating a report in the new scout, the table of the dismissed variants does not show why they were dismissed. (I have only checked one case) 

![image](https://user-images.githubusercontent.com/5881356/68573264-b0a57f00-0467-11ea-875f-08d833cc9972.png)

Kind regards,
Bianca

**Comment by dnil** [comment]
Thank you @genecracker! There's bound to be quite a few of the kind now.

**Comment by 4WGH** [comment]
fam 19220 is affected by this :(
can you help me with this?

**Comment by dnil** [comment]
Thank you for the report! (And sorry for accidentally marking this as closed - it was not a user_id-related problem. We will investigate this next, after the old case version number issue.

**Comment by 4WGH** [comment]
19208 same prob.
