### ISSUE TITLE
assign yourself

### ISSUE THREAD

**Issue by genecracker** [Clinical-Genomics/scout#1476]
Hi!

I tried to assign myself to a case, and while I see that happening in the activity log (for as many times as I clicked on "assign me"), my name does not show up in the main list of cases. 

Kind regards,
Bianca

**Comment by dnil** [comment]
Hi Bianca! This is for the same issue as the one where you didn't see your institute - you being logged in as your old, duplicate user. We'll fix, but I think I'll move this to the other issue and close here to keep us focused. Thanks for letting us know!
