### ISSUE TITLE
CILNSIG field not working. FIXED

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/scout#148]
Scouts CLINSIG field does not report what is actually found in the raw vcf. 

1       155261709       rs116100695     G       A       3842.06 PASS    1000GAF=0.00159744;AC=1;AF=0.500;AN=2;BaseQRankSum=6.74;CADD=20.9;CLNSIG=5

Shows in Scout as 1: not provided for family 15095.

**Comment by henrikstranneheim** [comment]
The entry should also be renamed in Scout, for example to "Clinvar" or "Clinvar_CLNSIG"

**Comment by vwirta** [comment]
Show if 5 exists.

**Comment by moonso** [comment]
We will now search through the clnsig annotations and see if we can find 5.
If we find 5 we show this otherwise we show nothing

**Comment by henrikstranneheim** [comment]
Remember that the CLNSIG is a list of values, i.e. CLNSIG=5|c|y|5 and the accessions follow the same pattern. We want to show all 5:s and IDs.

> On 06 Nov 2015, at 10:45, Måns Magnusson <notifications@github.com> wrote:
> 
> We will now search through the clnsig annotations and see if we can find 5.
> If we find 5 we show this otherwise we show nothing
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/Clinical-Genomics/scout/issues/148#issuecomment-154364533>.
> 

Henrik Stranneheim Ph.D.
Department of Molecular Medicine and Surgery
Karolinska Institute
Science for Life Laboratory


E-mail: henrik.stranneheim@scilifelab.se <mailto:henstr18@kth.se>
Visiting address: 
Science for Life Laboratory - SciLifeLab
Gamma building
Tomtebodavägen 23A
Delivery address:
Science for Life Laboratory - SciLifeLab
Gamma building
Tomtebodavägen 23B
171 65 Solna

**Comment by moonso** [comment]
What ids:?

**Comment by henrikstranneheim** [comment]
Sorry! Accessions i.e “##INFO=<ID=SnpSift_CLNACC,Number=.,Type=String,Description="Variant Accession and Versions”>"
CLNSIG=3|0
SnpSift_CLNACC=RCV000152385.1|RCV000172372.2

> On 06 Nov 2015, at 10:55, Måns Magnusson <notifications@github.com> wrote:
> 
> What ids:?
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/Clinical-Genomics/scout/issues/148#issuecomment-154367200>.
> 

Henrik Stranneheim Ph.D.
Department of Molecular Medicine and Surgery
Karolinska Institute
Science for Life Laboratory


E-mail: henrik.stranneheim@scilifelab.se <mailto:henstr18@kth.se>
Visiting address: 
Science for Life Laboratory - SciLifeLab
Gamma building
Tomtebodavägen 23A
Delivery address:
Science for Life Laboratory - SciLifeLab
Gamma building
Tomtebodavägen 23B
171 65 Solna

**Comment by henrikstranneheim** [comment]
CLNSIG field is still showing the wrong annotation and display name
