### ISSUE TITLE
Assignees tag not working

### ISSUE THREAD

**Issue by sofievonlanthen** [Clinical-Genomics/scout#1480]
Assigning to cases don't seem to work in the new Scout. We have all assigned ourselves to new cases, but can't see this in the list of cases, the assignees name won't show up (although I can see at the bottom of the page at the activity tracking that I assigned myself to a case).

/Sofie

**Comment by dnil** [comment]
See #1472 again (and #1476). Once we have your alternative account locked down, you will be fine again.
