### ISSUE TITLE
Can't remove comments

### ISSUE THREAD

**Issue by sofievonlanthen** [Clinical-Genomics/scout#1481]
In new Scout, we can't remove our own comments created on the case page. Is there a reason for this or a bug? Old comments can still be removed (as long as it is our own comment). 

/Sofie

**Comment by dnil** [comment]
I think that says you are with Bianca in having two different accounts, and one is suddenly accessible. We can hopefully resolve that tonight. See #1472 - but I'll keep this open until we have investigated further! Thank you for the report!

**Comment by dnil** [comment]
Ok, this now seems to be working again. Let us know if you have more issues with it @sofievonlanthen and @genecracker!
Fixed by #1484
