### ISSUE TITLE
Can't open old cases

### ISSUE THREAD

**Issue by sofievonlanthen** [Clinical-Genomics/scout#1482]
I tried to open an old case from 2017 (417701600542), but get "internal server error". Is there a limit how old cases we can open in new scout? Not the BAM file, just wanted to check the pinned variants. 

/Sofie

**Comment by dnil** [comment]
That old case was unfortunately loaded with a floating point version id. See issue #1475. Its a fairly simple fix, so let us know if you are in a hurry, otw we fix this after the user_id / acmg / comments issue. I will close this issue, but thank you for reporting it: there was essentially no way you could know they were the same problem without having access to the server logs.
