### ISSUE TITLE
Error loading data track in IGV

### ISSUE THREAD

**Issue by 1ctw** [Clinical-Genomics/scout#1483]
In case 17121-1 there is a problem with viewing variants in IGV. Error message : "Error loading data track" or just a blank page below the reference sequence. Browsers tested: Firefox, Chrome, Explorer, Edge.

**Comment by dnil** [comment]
Thank you for noticing! IGV view in general seems to be working for some random cases I picked. We will have a look!

**Comment by dnil** [comment]
Ping @ingkebil @emiliaol. Other cases appear to have their IGV view intact, but not this one. Other recent reruns also seem to load bam files just fine. The scout db bam file entry for the case loos good at a glance. The bam file pointed to is a little on the small side, but at least the index seems very readable. Can you find anything unusual from your perspective? Any extended permissions in play, like SELinux over the DAC?

**Comment by ingkebil** [comment]
Permissions are fine:

Hasta
```
[0|0|2901] [kenny.billiau@hasta:~] [P_main] 4s $ ll /home/proj/production/housekeeper-bundles/amazedshiner/2019-10-09/ACC5965A1_lanes_1234_sorted_md_brecal.bam
-rw-rw----+ 2 hiseq.clinical hasta-rare-disease 48225445634 Oct 11 06:26 /home/proj/production/housekeeper-bundles/amazedshiner/2019-10-09/ACC5965A1_lanes_1234_sorted_md_brecal.bam
[0|0|2901] [kenny.billiau@hasta:~] [P_main] $ getfacl /home/proj/production/housekeeper-bundles/amazedshiner/2019-10-09/ACC5965A1_lanes_1234_sorted_md_brecal.bam                              
getfacl: Removing leading '/' from absolute path names
# file: home/proj/production/housekeeper-bundles/amazedshiner/2019-10-09/ACC5965A1_lanes_1234_sorted_md_brecal.bam
# owner: hiseq.clinical
# group: hasta-rare-disease
user::rw-
user:hiseq.clinical:rwx         #effective:rw-
user:kenny.billiau:rwx          #effective:rw-
group::rwx                      #effective:rw-
mask::rw-
other::---
```

clinical-db
```
[hiseq.clinical@hippocampus ~]$ ll /home/proj/production/housekeeper-bundles/amazedshiner/2019-10-09/ACC5965A1_lanes_1234_sorted_md_brecal.bam
-rwxrwxr-x. 1 hiseq.clinical users 48225445634 Oct 11 06:26 /home/proj/production/housekeeper-bundles/amazedshiner/2019-10-09/ACC5965A1_lanes_1234_sorted_md_brecal.bam
[hiseq.clinical@hippocampus ~]$ getfacl /home/proj/production/housekeeper-bundles/amazedshiner/
2019-10-09/ACC5965A1_lanes_1234_sorted_md_brecal.bam                                           
getfacl: Removing leading '/' from absolute path names
# file: home/proj/production/housekeeper-bundles/amazedshiner/2019-10-09/ACC5965A1_lanes_1234_sorted_md_brecal.bam
# owner: hiseq.clinical
# group: users
user::rwx
group::rwx
other::r-x
```

**Comment by northwestwitch** [comment]
This is still not fixed. I'm inspecting the page and I found some javascript error coming from igv:
![image](https://user-images.githubusercontent.com/28093618/70042731-ae929400-15bf-11ea-8875-5a56233df40e.png)

An error in the bam header? ping @henrikstranneheim

**Comment by dnil** [comment]
Opens fine in ordinary IGV..

**Comment by northwestwitch** [comment]
Ok then we should probably look inside the issues of igv.js, I think I saw this error message before

**Comment by northwestwitch** [comment]
I tried to understand what's wrong with this track visualization, unfortunately I haven't found any difference between this bam file and the tracks that work. Maybe re-running the sample would help fixing the issue?

**Comment by 1ctw** [comment]
We have been able to answer out this case despite the IGV problems. The case is not solved so we will probably rerun again but not now. Maybe you better close this issue for now.

**Comment by northwestwitch** [comment]
Ok then, closing this for now!
