### ISSUE TITLE
Previously classified as Pathogenic

### ISSUE THREAD

**Issue by 1ctw** [Clinical-Genomics/scout#1487]
Pinned variant in gene XDH in case 19194 now has to symbols for ACMG classification in variant list. One for "Pathogenic" which is blue and one "Previously classified as Pathogenic" which is grey. A bug? We have not seen this variant in any other case.

![bild](https://user-images.githubusercontent.com/15033593/68651588-ff1a5280-0527-11ea-996e-63d2e04f608e.png)

**Comment by dnil** [comment]
Thank you @1ctw! It would seem that HB has classified this variant as Pathogenic, so the current "blue" one is correct, but since it has only been seen in this case it would have been less confusing not seeing the "grey" previously classified label as well. We'll have a look at that!

**Comment by dnil** [comment]
Ok, that was the intention all along, fortunately. It just needs a little bit of fixing.
