### ISSUE TITLE
HPO gene panel lists all genes in the browser

### ISSUE THREAD

**Issue by AnnHam** [Clinical-Genomics/scout#1488]
When creating a HPO gene panel (1011 genes), 1 phenotypes ) - all the genes are listed in the browser - you need to scroll down to the very end to analyze your HPO gene panel...

**Comment by dnil** [comment]
I would make a lot of sense to have that as a fixed size and scrollable card. Thank you @AnnHam!

**Comment by dnil** [comment]
In the meantime, happy scrolling! 😅

**Comment by dnil** [comment]
More requests for this and similar panels: see https://github.com/Clinical-Genomics/scout/issues/1540 and #1497. 😄

**Comment by northwestwitch** [comment]
@mayabrandi the easies way to add the scroll would be using the overflow class of Bootstrap : https://getbootstrap.com/docs/4.3/utilities/overflow/

**Comment by mayabrandi** [comment]
Ill close this one. Soved by #1546
