### ISSUE TITLE
Scout for general use?

### ISSUE THREAD

**Issue by guillermo-carrasco** [Clinical-Genomics/scout#149]
Hi!

Quick question: How usable is Scout outside clinical genomics? Last time we talked about this I recall that you (@robinandeer) told me that it was still quite tight to MIP output. 

If that's still the case, is it in your roadmap to generalize it? Maybe I could help :)

Thanks!

**Comment by moonso** [comment]
Hello!
Yes it is dependent on our pipeline but i have started to make a "portable" version. 
It would be fantastic if you would like to help us on this, we should meet.

**Comment by guillermo-carrasco** [comment]
Hi Måns!

Is there any possibility to see scout in action? Any test data/docker container/vagrant vm we can use to have a quick look at Scout? We can meet and talk about it, but this way other people in my team could have a quick look to scout.

Tack tack!

**Comment by moonso** [comment]
I guess we can make a user so you can access some non sensitive data.
What do you think @robinandeer ?

**Comment by robinandeer** [comment]
Our servers are quite restrictive when it comes to access from external IP-addresses. I think putting some finishing touches on a Vagrant environment would be ideal

That wouldn't let you load your own data but you'll be able to click around in the interface at least

I'll get back to you on that

Would you be specifically interested in a Docker setup or are just throwing that in bc of the buzz-factor? :wink:

**Comment by guillermo-carrasco** [comment]
heh, vagrant/Docker, anything would work :) 

I'd really appreciate this, thanks a lot Robin!

**Comment by robinandeer** [comment]
Wow, we really need to clean up here...

Anyways, if you have time I've made some modifications that you could help us test out. @moonso: you are free to try it out as well

1.  Checkout the branch "demo-setup"
2. Make sure you've installed Ansible and Vagrant
3. Run:

```bash
$ ansible-galaxy install robinandeer.miniconda
$ ansible-galaxy install nodesource.node
$ vagrant up
# Mac specific
$ open http://localhost:5023/
```

This should hopefully do the trick :persevere:

**Comment by moonso** [comment]
```bash
$ ansible-galaxy install robinandeer.miniconda
- downloading role 'miniconda', owned by robinandeer
- downloading role from https://github.com/robinandeer/ansible-miniconda/archive/v0.4.tar.gz
- extracting robinandeer.miniconda to /etc/ansible/roles/robinandeer.miniconda
- error: you do not have permission to modify files in /etc/ansible/roles/robinandeer.miniconda
- robinandeer.miniconda was NOT installed successfully.
- you can use --ignore-errors to skip failed roles.
$ ansible-galaxy install robinandeer.miniconda --ignore-errors
- downloading role 'miniconda', owned by robinandeer
- downloading role from https://github.com/robinandeer/ansible-miniconda/archive/v0.4.tar.gz
- extracting robinandeer.miniconda to /etc/ansible/roles/robinandeer.miniconda
- error: you do not have permission to modify files in /etc/ansible/roles/robinandeer.miniconda
- robinandeer.miniconda was NOT installed successfully.
````
?

**Comment by robinandeer** [comment]
You seem to have installed Ansible globally so you'd need to run the command as `sudo` to get around the permissions error.

**Comment by guillermo-carrasco** [comment]
Thanks a lot Robin for this. I'm having troubles provisioning the VM. I got this message at the first try:

```
TASK: [scout-dev | install global npm dependencies] ***************************
failed: [default] => (item=coffee-script) => {"failed": true, "item": "coffee-script"}
msg: Failed to find required executable npm
failed: [default] => (item=gulp) => {"failed": true, "item": "gulp"}
msg: Failed to find required executable npm

FATAL: all hosts have already failed -- aborting
```

Then I installed npm in the VM and I'm getting a long error trace now:

```
ASK: [scout-dev | install global npm dependencies] ***************************
failed: [default] => (item=coffee-script) => {"cmd": "/usr/bin/npm install --global coffee-script", "failed": true, "item": "coffee-script", "rc": 1}
stderr: npm http GET https://registry.npmjs.org/coffee-script

npm ERR! Error: failed to fetch from registry: coffee-script
npm ERR!     at /usr/share/npm/lib/utils/npm-registry-client/get.

....
```

I thought I'd let you know before I keep trying, thanks again!

**Comment by robinandeer** [comment]
I'm an idiot, I left some lines commented out in the commit 
pull and try again

**Comment by robinandeer** [comment]
I've updated the README with FULL instructions!
I forgot one of the Ansible Galaxy installs.

**Comment by guillermo-carrasco** [comment]
Thanks again!

It seemed to install now, though lots of warnings in the shell provisioning step. [Check here](https://gist.github.com/guillermo-carrasco/d7509b4da1583cc89d32).

Awesome though! I can navigate the interface, yay!

![screen shot 2015-09-24 at 11 04 19](https://cloud.githubusercontent.com/assets/1574147/10069362/1ae14014-62ac-11e5-89ee-4022a468c429.png)

**Comment by dnil** [comment]
Awsome!

I just had to try that. I’m not quite there yet - still getting npm related errors during “vagrant up”:

npm WARN peerDependencies The peer dependency insert-css@^0.2.0 included from vue-loader will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN prefer global coffee-script@1.10.0 should be installed with -g
npm WARN optional dep failed, continuing fsevents@1.0.0
npm WARN deprecated pangyp@2.3.2: use node-gyp@3+, it does all the things
npm ERR! Linux 3.2.0-23-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! path ../coffee-script/bin/cake
npm ERR! code EPROTO
npm ERR! errno -71

npm ERR! EPROTO, symlink '../coffee-script/bin/cake'

Tried fresh scout dir, fresh hashicorp/precise64 box? What am I missing? Thanks a bunch!

**Comment by dnil** [comment]
Ok, it's actually in quite decent shape anyway! After a `npm install -g coffee-script` on the virtual machine, I could 
`vagrant@precise64:~/miniconda$ source bin/activate prod`
 `python manage.py -c "$(pwd)/instance/scout.cfg" vagrant`
getting to a state where I would need that GOOGLE_CONSUMER_KEY!

**Comment by robinandeer** [comment]
Hi @dnil!

I'll have to look into that error..
When you run the server you should run with the login stuff disabled - use the config you find here: https://github.com/Clinical-Genomics/scout/blob/demo-setup/provision/roles/scout-dev/files/demo.cfg

It's copied during provisioning so you could try if this command works better already:
`python /vagrant/manage.py -c /home/vagrant/demo.cfg vagrant`

**Comment by dnil** [comment]
Thanks, that indeed gets me around the login part, but it seems I’m missing a few style related things, and no demo case to be found. I’m guessing the provisioning stopped after choking at that npm coffee-script point and never got to some later things?

**Comment by dnil** [comment]
Running the /vagrant/provision/post-setup.sh cleared things up a bit and got a case loaded.
Still, missing a lot of style on the pages. Seems the gulp builds are not going well.
gulp --gulpfile /vagrant/Gulpfile.js build
module.js:338
    throw err;
          ^
Error: Cannot find module 'gulp-sass’

**Comment by dnil** [comment]
Ok, must be a gulp issue.

npm installing the gulp extras got me further.
several have an optional dependency fsevents failing, and gulp-webpack having been rebranded webpack-stream. Should be ok anyway. I’m now stuck with some vue error.

gulp --gulpfile /vagrant/Gulpfile.js build 
...
ERROR in ./assets/coffee/app.vue
Module build failed: TypeError: undefined is not a function
  at Object.Vue (/vagrant/node_modules/vue/src/vue.js:19:8)
 @ ./assets/coffee/main.js 4:31-51
...

**Comment by robinandeer** [comment]
`npm` is usually very good at resolving these issues but I will do a drive and update our dependencies to more recent versions and then this problem should go away :)

**Comment by moonso** [comment]
We are moving in the other direction now, scout for specific use :smile_cat: 
But the general scout will be :tada: [puzzle](https://github.com/robinandeer/puzzle),
please try it!

**Comment by guillermo-carrasco** [comment]
:bow:
