### ISSUE TITLE
Bootstrap issues

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#1497]
- [x] mouse pointer focus and focus highlighting misaligned on the cases page (Firefox only?)
<img width="932" alt="Screenshot 2019-11-17 at 11 26 55" src="https://user-images.githubusercontent.com/758570/69006295-57d55b00-092d-11ea-833f-983bb201fb39.png">
 I don't see this issue @dnil Neither on firefox or chrome.. /MB

Tested on chrome and firefox (70.0.1) and I can'r re-create the issue either /CR

- [ ] gene column becomes overcrowded
What do you mean? /MB

- [x] variant pages: dismiss controls should be more prominently displayed: at least the same as variant tag etc
Think this one is being solved by PR #1546 /MB

~~- [ ] gene panel list on the variant page becomes too large, taking more space than is warranted by its importance.~~ Will be fixed in ~~#1540~~ #1488.

- [ ] search button on dashboard page unaligned
Seems to be fixed already? /MB

- [x] admin view on dashboard does not show validation stats on the second page
I need some help to understand the issue here. /MB

**Comment by mayabrandi** [comment]
witch table/tables are you referring to here? @dnil @northwestwitch

**Comment by northwestwitch** [comment]
Gene panels could also be scrollable if there's many panels:
![image](https://user-images.githubusercontent.com/28093618/69424711-9aca7080-0d29-11ea-9a93-9e29e3385489.png)

compound variants could be also scrollable, see here: https://scout-stage.scilifelab.se/cust003/18069/24874c4fbc5cfad98ff06c6fbf1397c7

Transcripts could be a long list, for instance this one: https://scout-stage.scilifelab.se/cust003/18069/1cfd5e10272dfce7c9810177e5670a2d and there are some even longer

Overlapping SNVs in structural variants pages: https://scout-stage.scilifelab.se/cust003/18069/sv/variants/2f3f686b52728d36b9f2ac78f72387d8

What else @dnil?

**Comment by dnil** [comment]
> Transcripts could be a long list,
Exactly; looks like it is called "Transcript overview".

Then we need to do something about the Gene panel view on the variant page: 
![Screenshot 2019-11-22 at 13 21 58](https://user-images.githubusercontent.com/758570/69425441-25f83600-0d2b-11ea-9a39-64a4948786bc.png)
Not sure making that scrollable is the best, but it does take too much space for its prime position now.

**Comment by mayabrandi** [comment]
More or less, wherever lists seem to get long? Maybe set overflow and max-witdth on all lists at least?

**Comment by dnil** [comment]
> I don't see this issue @dnil Neither on firefox or chrome.. /MB

It is still there, and appears after a short term of use. Try scrolling rapidly through cases for an institute with many cases on stage.

**Comment by dnil** [comment]
>>  gene column becomes overcrowded
> What do you mean? /MB

Sorry, that might have seemed a very obvious note during the meeting. On the variants page, when a variant touches multiple genes, they get printed without indication there are more than one there:

<img width="528" alt="Screenshot 2019-11-26 at 17 11 47" src="https://user-images.githubusercontent.com/758570/69651260-16048d00-1070-11ea-853c-dba786108ae1.png">

Compare e.g. the SV variants view: 

<img width="378" alt="Screenshot 2019-11-26 at 17 14 08" src="https://user-images.githubusercontent.com/758570/69651367-41877780-1070-11ea-98bc-e2fceaad6187.png">

**Comment by dnil** [comment]
>>  search button on dashboard page unaligned
> Seems to be fixed already? /MB

Agreed! :+1: 
But, perhaps we could fix the dropdown to be more to size while we are looking at it, otherwise it's kind of hard to tell: 
<img width="507" alt="Screenshot 2019-11-26 at 17 15 26" src="https://user-images.githubusercontent.com/758570/69651559-90cda800-1070-11ea-8397-aa62fd7442b2.png">

**Comment by dnil** [comment]
> > admin view on dashboard does not show validation stats on the second page

> I need some help to understand the issue here. /MB

So this is weird for admins / all institutes on the second tab: 
<img width="1097" alt="Screenshot 2019-11-26 at 17 17 34" src="https://user-images.githubusercontent.com/758570/69651743-d7bb9d80-1070-11ea-8d98-3020d1e36c1b.png">

When e.g. on the third tab:
<img width="668" alt="Screenshot 2019-11-26 at 17 18 57" src="https://user-images.githubusercontent.com/758570/69651811-f15ce500-1070-11ea-944a-024be4397887.png">

Or by just selecting a single institute, on the second tab again:
<img width="560" alt="Screenshot 2019-11-26 at 17 19 46" src="https://user-images.githubusercontent.com/758570/69651886-0c2f5980-1071-11ea-9cf7-82e3b640c98a.png">
