### ISSUE TITLE
Overlapping SV on variant list

### ISSUE THREAD

**Issue by sofievonlanthen** [Clinical-Genomics/scout#1499]
The variant list contains the tag for overlapping structural variants for some variants, but when looking on the variant page, there are no overlapping structural variants. 

Example: 219701400158
Variant in TSC2

/Sofie

**Comment by ielvers** [comment]
I'm actually having a hard time finding an example where the SV is listed on the variant page. I can only find cases where the variant list shows the overlapping SV tag, but the variant page says there are no overlapping structural variants.

More examples:
sample 19225, variants in NOTCH2 (SV is an intronic insertion, length n.d.)
sample 19230, variant in TJP2 (SV is an intronic deletion)
sample 17121-1, variant in TMLHE (SV is an exonic duplication)
sample 17121-1, variant in NALCN (SV is an exonic BND)
sample 17121-1, variant in FARS2 (SV is an intronic deletion)
sample 17082, variants in EXT1 (SV is an intronic BND)

**Comment by dnil** [comment]
I have a hunch this is related to finding variants by gene/gene_symbol/hgnc_id and region.. @moonso would find this quickest, but he's really supposed to be doing other things. If you wish to procrastinate M, this is a good one, but otherwise we will get to it anyway.

**Comment by northwestwitch** [comment]
I remember I've been re-writing the code to find overlapping SVs in the variants page. I could also have a look at the code next week!

**Comment by ielvers** [comment]
Also when looking at SVs, the overview page lists Gene(s) but when looking at the SV page it says "no overlapping SNVs found".
Example: case 19164, I would expect SV https://scout.scilifelab.se/cust003/19164/sv/variants/bcf4d36b407ec963984fa7f287380cb4 to link to SNV https://scout.scilifelab.se/cust003/19164/33fb23f29b1d5659d1cddf86be4c8262
Thank you :)
