### ISSUE TITLE
STR calls layout

### ISSUE THREAD

**Issue by 47KW** [Clinical-Genomics/scout#1501]
Suggested improvements for the STR layout:
- [x] The link to IGV viewer "button" has lost its boundaries, square
- [x] sort the calls by gene-name or numerically by Chr. and Position. (put the IGV-button outside?)
- [x] make the list viewed as single row for each repeat with both alleles (genotype)
- [x] dont use the term rank since its not really a rank
- [x] remove the chromosome postions from certain repeat-names
- [x] add RFC1 😉

**Comment by dnil** [comment]
Thank you Dr @47KW! We will ponder this: especially 1 we will fix as soon as time allows. The other ones are more pipeline issues, that we could of course polish away in scout, but that I would rather distribute out on the respective pipeline components. 

I am not sure how to solve 3 for general family structures? Ideas? Fairly straightforward for singletons or trios, although it would be preferable to have the pipeline solve it, and eg integrate with other variants in the gene etc..

**Comment by 47KW** [comment]
Will contemplate over 3). Some things are easy, others are more rewarding 😉
Can you call alleles without referring to the reference and then that would make to alleles show up as two rows?



Från: Daniel Nilsson <notifications@github.com>
Skickat: den 13 november 2019 11:14
Till: Clinical-Genomics/scout <scout@noreply.github.com>
Kopia: Håkan Thonberg <hakan.thonberg@sll.se>; Mention <mention@noreply.github.com>
Ämne: Re: [Clinical-Genomics/scout] STR calls layout (#1501)


Thank you Dr @47KW<https://github.com/47KW>! We will ponder this: especially 1 we will fix as soon as time allows. The other ones are more pipeline issues, that we could of course polish away in scout, but that I would rather distribute out on the respective pipeline components.

I am not sure how to solve 3 for general family structures? Ideas? Fairly straightforward for singletons or trios, although it would be preferable to have the pipeline solve it, and eg integrate with other variants in the gene etc..

**Comment by northwestwitch** [comment]
I'm working on this (the things that are quite easy to fix at least). Question: 
**remove the chromosome postions from certain repeat-names**

Could you provide an example of how the name is now it is now and how you would like to have it instead?

**Comment by dnil** [comment]
Sorry, let me try to annotate what I did so far:

> * [ ]  The link to IGV viewer "button" has lost its boundaries, square

We (@northwestwitch?) will fix in scout!

> * [ ]  sort the calls by gene-name or numerically by Chr. and Position. (put the IGV-button outside?)
> * [ ]  dont use the term rank since its not really a rank

Add a straightforward ranking through stranger. See Stranger issue: https://github.com/moonso/stranger/issues/14

> * [ ]  make the list viewed as single row for each repeat with both alleles (genotype)

Complicated. We'll keep thinking! 

> * [ ]  remove the chromosome postions from certain repeat-names
> * [ ]  add RFC1 😉
Both of these are largely solved by updating ExHu and references to the latest version. Presumably ready for MIP8 already?

**Comment by northwestwitch** [comment]
@dnil if you are already working in this I could pick some other issue

**Comment by henrikstranneheim** [comment]
MIP 8 uses:
- expansionhunter version 3.1.2
- grch37_expansionhunter_variant_catalog_-3.0.0-.json

Let us know if you want to make updates.

**Comment by dnil** [comment]
Thanks! Updates to refs have been to 3.0.1 for some time now. Will add one for 3.1.2!

**Comment by dnil** [comment]
@northwestwitch Do go ahead: the button should just be a class issue I would guess. If you have a good suggestion for how to display the different alleles in both singletons and extended families that would be welcome!

**Comment by henrikstranneheim** [comment]
@dnil Great! Let me know when the ref for 3.1.2 is ready for downloading and testing.

**Comment by dnil** [comment]
@henrikstranneheim :+1: It will appear on references as usual!

**Comment by dnil** [comment]
@northwestwitch One thought is to add in the allele sizes directly adjacent to the ref/normal GT calls. And possibly group multiple calls to the same locus on the same table row, but that *may* get more messy.

**Comment by dnil** [comment]
Ok @henrikstranneheim! New refs available as a PR for a test spin on reference-files. The reference files should normally track ExHu versions, so new ones in the v3.1.2 subdirectory. If possible, use Stranger v0.5.5 or later to enable transfer of pathogenic range to VCF and Scout. Ehr, pending a full release package in Stranger I note - me fix!

**Comment by henrikstranneheim** [comment]
@dnil or @moonso  Could you update pypi for stranger to v0.5.5 so I can make an update to the pipeline?

**Comment by moonso** [comment]
@henrikstranneheim should be on pypi now

**Comment by henrikstranneheim** [comment]
Expansionhunter variant catalog and stranger have been updated in MIP and works on hasta

**Comment by dnil** [comment]
Ok, so that concludes it on the development side! @47KW I'm afraid you will as usual have to wait a little bit before all the goodies arrive on your side. Validation on the MIP side is ongoing, which will when deployed fix some of your issues for new cases. And we should be releasing a patch or minor release of Scout within a week or so which will at least make STRs prettier for all cases! Thanks a bunch for the input! Keep it up!
