### ISSUE TITLE
Scout user meeting 22/1 - 2020

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#1502]
1. Current updates - production
*Causatives*
- Rank score model in causatives page
- Display GT and allele depth in causatives table.
*Phenotypes*
- Exportable HPO terms from phenotypes page
*Cases*
- All prioritized cases are shown on cases page
*Case*
- Add or modify individuals' age or tissue type from case page
- Sort gene panel list on case view.
- Fix error when a gene is added to an empty dynamic gene panel
- Fix crash when attempting to add genes on incorrect format to dynamic gene panel
*Variants*
- ***Overlapping variants will now be visible on variant page again***
*Variant - tag*
- Manual rank variant tags could be saved in a "Select a tag"-state, a problem in the variants view.
- AMP guideline tiers for cancer variants
- Removed Mosaic Tag from Cancer variants
- New mosaicism tag option
*Variant*
- Adds scroll for the transcript tab
- Same case evaluations are no longer shown as gray previous evaluations on the variants page
- Links to GENEMANIA
*Variant evaluation*
- Fix missing classification comments and links in evaluations page
*Research*
- Shadow clinical assessments also on research variants display
- Fixed issue with opening research variants
- Stay on research pages, even if reset, next first buttons are pressed..
*STR variants*
- Improved str variants view : sorting by locus, grouped by allele.
- Display locus name on STR variant page [dev]
* Note MIP7 issue with trio STR entries sometimes missing when multiple individuals split and merge to the same length
*Reports*
- Delivery report PDF export
- Included primary reference transcript in general report
- Included partial causative variants in general report
- Fixed layout in general report PDF export and several pages
*CLI and IGV*
- Added CLI option to query cases on time since case event was added
- Support for CRAM alignment files ***Mention SPRING and data storage plans***
- Allow loading of custom annotations in VCF using the SCOUT_CUSTOM info tag.
*MatchMaker*
- Improved MatchMaker pages, including visible patient contacts email address
*Dashboard*
- Fixed issue on the case statistics view. The validation bars didn't show up when all institutes were selected. Now they do. ***Reminder to mark causative (and not archive solved cases unless intended)***

For next release:
- Slightly darker page background
- Clinvar submissions accessible to all users of an institute
- Display locus name on STR variant page
- Avoid flickering comment popovers in variant list
- decouple loqusdb - loqusdb for SV!
- Allow users to customize institute settings
- Submit SVs (max 3 genes) to MatchMaker
MIP8:
- Parse REVEL score from vep annotated CSQ fields
- Parse GERP, phastCons and phyloP annotations from vep annotated CSQ fields
- Alternative key GNOMADAF_popmax for Gnomad popmax allele frequency
- Fixed an issued with parsed conservation values from CSQ

CI and QC:
- Automatic suggestions on how to improve the code on Pull Requests
- Coverage calculated on Pull Request commits instead of last push commit
2. MIP8 and MIP8.1 - features and timeline
3. Status on new server hardware for web services
4. Plans for DB server upgrade

**Comment by northwestwitch** [comment]
Edit age and tissue and the case become inactive, bug!

**Comment by dnil** [comment]
We forgot to book next meeting. Around MIP8 release perhaps?

**Comment by henrikstranneheim** [comment]
6 weeks from now around 4 of mars. How does that sound?

**Comment by dnil** [comment]
Yep: fine with me!
