### ISSUE TITLE
Display analysisType in case view (i.e. WES or WGS). FIXED

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/scout#151]

**Comment by moonso** [comment]
- [ ] Add a new field to case model ```analysis_type```
- [ ] A badge to case and cases

**Comment by moonso** [comment]
@henrikstranneheim is the analysistype specified in qc_sample_info?
If not, can you add it.
Alternatives should be ```wgs, wes, mixed or unknown```

**Comment by henrikstranneheim** [comment]
It is as 'analysisType'. However you will have to recode it as entries are: genomes and exomes.
Theses are not easy to change and would require a rerun of all samples. 
It can never be unknown and mixed are always processed as genomes. 

Skickat från min iPad
