### ISSUE TITLE
research page 2 is a clinical page

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#1514]
Hi , see the exemple of fam 83
If we are on the research page and click on "next" the fololowing page is a clinical page.

initial page
https://scout.scilifelab.se/cust003/83/variants?variant_type=research
click on "NEXT"
https://scout.scilifelab.se/cust003/83/variants
this come up: on top it states clinical SNV and INDEL

thanksfor help

**Comment by dnil** [comment]
Thanks for the report! We will look into it. I’m relieved it wasn’t the other way around, but we do want to support research as well!

**Comment by 4WGH** [comment]
thanks!
Paulina who is going throug our research family noticed it :)

________________________________
Från: Daniel Nilsson <notifications@github.com>
Skickat: den 15 november 2019 10:41
Till: Clinical-Genomics/scout <scout@noreply.github.com>
Kopia: Michela Barbaro <michela.barbaro@sll.se>; Author <author@noreply.github.com>
Ämne: Re: [Clinical-Genomics/scout] research page 2 is a clinical page (#1514)


Thanks for the report! We will look into it. I’m relieved it wasn’t the other way around, but we do want to support research as well!

**Comment by ielvers** [comment]
Hi,

This also happens to family 25.

/ Elin through Ingegerd

**Comment by ielvers** [comment]
To clarify: from page 2 and onwards it says "Clinical SNV and INDELs" on top but all variants are displayed (no filter).
In research mode, variants in family 25 are also ranked different compared to two weeks ago. But we'll create a separate issue for that.
Thank you :)
- Ingegerd

**Comment by dominykabat** [comment]
Hej, I think the same thing happens when you try to filter research variants by something. For example, when on 'Research SNV and INDELs' I select a filter and pressing Filter Variants it returns me to 'Clinical SNVs/Indels' (no research variants displayed)

Dominyka

**Comment by dnil** [comment]
Yeah, it appears a variable that separates the two views is now being mistakenly dropped on that form. When it is not found, the default is to use clinical. We will try to fix it soon-ish!

I realise we did not have any of the research users test the new version before-hand, only the clinic users. That is something to learn from for next larger update. Thanks for all the feed-back!
