### ISSUE TITLE
variant prioritization changed without rerun or notification

### ISSUE THREAD

**Issue by ielvers** [Clinical-Genomics/scout#1516]
Hi,

When looking in family 25 (research list) Elin noticed that the score and therefore order (rank) of variants has changed compared to when she copied the list 10 days ago.

/ Elin and Ingegerd

**Comment by moonso** [comment]
Hi, there is no possibility that the score has changed without rerunning a case. It is nothing that Scout does on its own. For us to be able to follow up you need to be more specific, link to variants etc.

**Comment by moonso** [comment]
Ok so @ielvers I'm closing this for now. Please reopen if there are any supporting links etc for this one
