### ISSUE TITLE
comment to variant missing? FIXED

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#152]
Hi;
I can see a dot indicating that ther eis a comment for a variant, but once I click to go inside the variant there is not comment ( I know that there should be..., as I written it in fam 15089)
Look at the 2 screen shots
![skarmklipp1](https://cloud.githubusercontent.com/assets/12525201/10104846/ff68e944-63ab-11e5-9aa9-07b1af051651.PNG)
![Uploading Skärmklipp2.PNG…]()

michela

**Comment by robinandeer** [comment]
I can't find the same variant

But for this one it works:
https://clinical-db.scilifelab.se:8083/cust003/15015/variants/d44549baf5fe8241c50dcb78485d7489

and originally:
https://clinical-db.scilifelab.se:8083/cust003/41/variants/f8ab5a3dc18b745c5dc54627c032b0d6

**Comment by robinandeer** [comment]
OK, the problem is in the "has_comments" method... It should look for either global comments or comments for the family

**Comment by robinandeer** [comment]
We will only show the indicator if there are global comments for the variant

**Comment by 4WGH** [comment]
ok!
thanks,
Michela
 
 
-----Robin Andeer <notifications@github.com> skrev: ----- 

Till: Clinical-Genomics/scout <scout@noreply.github.com>Från: Robin Andeer <notifications@github.com>Datum: 2015-10-21 13:29Kopia: 4WGH <michela.barbaro@karolinska.se>Ärende: Re: [scout] comment to variant missing? (#152)
We will only show the indicator if there are global comments for the variant
