### ISSUE TITLE
Some cytoband-related code is executed in background also on demo patient

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#1522]
This is more a question than an issue.
I'm testing some stuff on a local instance of Scout and noticed that there is some background code executed for the demo patient:

![image](https://user-images.githubusercontent.com/28093618/69008376-f1ab0100-0949-11ea-9248-5cea2c70e3a8.png)

Is this supposed to run for every patient, also those without the pertinent tracks?

**Comment by dnil** [comment]
I seem to recall there is some testing for presence of one file to determine if anything should be shown. It is mostly just legacy. It would likely be possible to do that only if appropriate variables are set on the case now.

**Comment by northwestwitch** [comment]
Looking at the source code of the demo case page for other reasons, and there are a lot of errors in the javascript code: 
![image](https://user-images.githubusercontent.com/28093618/69241946-257f6400-0ba0-11ea-8bd7-20df5b96fb0a.png)

We should definitely handle the absence of chromogram tracks tracks better..

**Comment by northwestwitch** [comment]
I don't know if this one was fixed. You could check @mikaell

**Comment by mikaell** [comment]
Oh! Some backlog I've forgotten about 😀

**Comment by mikaell** [comment]
After investigating I found a fix @dnil made, `28d28b3d`. This is merged and deploy.
>    Fix crash on case page w/o ideogram files.
