### ISSUE TITLE
load institute message is a bit confusing

### ISSUE THREAD

**Issue by emiliaol** [Clinical-Genomics/scout#1523]
The `scout load institute` CLI command makes it seem like the display name for the newly created institute will be the internal name. The institute is however correctly added with the desired display name to the db.

![Skärmavbild 2019-11-18 kl  09 27 33](https://user-images.githubusercontent.com/12113434/69036339-f58c6100-09e5-11ea-91ea-1b608976bdf5.png)

**Comment by dnil** [comment]
Thanks for the Argentina!

**Comment by emiliaol** [comment]
Thanks guys!
