### ISSUE TITLE
BCFTools making weird calls: Ref 10 Alt. 2

### ISSUE THREAD

**Issue by 47KW** [Clinical-Genomics/scout#1524]
https://scout.scilifelab.se/igv?sample=2019-26950-02&build=grch37&bam=%2Fhome%2Fproj%2Fproduction%2Fhousekeeper-bundles%2Ffinerkid%2F2019-11-10%2FACC6347A6_lanes_1234_sorted_md_brecal.bam&bai=%2Fhome%2Fproj%2Fproduction%2Fhousekeeper-bundles%2Ffinerkid%2F2019-11-10%2FACC6347A6_lanes_1234_sorted_md_brecal.bam.bai&contig=1&start=74808758&stop=74808858&center_guide=T

**Comment by dnil** [comment]
Japp, helt klart! Fast om jag skulle bedöma så är det nog inte homozygot referens på alla positioner däromkring heller, så tycker nog att det är lite bra att den iaf hostar lite när de andra avropsprogrammen tiger:
<img width="1579" alt="Screenshot 2019-11-18 at 10 32 55" src="https://user-images.githubusercontent.com/758570/69040869-de05a600-09ee-11ea-8f10-08af1a53f8b0.png">

**Comment by 47KW** [comment]
TWIST Exom….
Det ä väl soft-clippat adapter som syns? Borde hårdklippas?

BCFTools avropat en hel hög med skumma saker i tre case som jag kollat på. Känsla det inte var så innan….men endast en känsla.
Låga ”Allele depth” på avropen som inte stämmer med IGV vy…
https://scout.scilifelab.se/igv?sample=2019-26765-04&build=grch37&bam=%2Fhome%2Fproj%2Fproduction%2Fhousekeeper-bundles%2Fpickedshark%2F2019-11-10%2FACC6347A5_lanes_1234_sorted_md_brecal.bam&bai=%2Fhome%2Fproj%2Fproduction%2Fhousekeeper-bundles%2Fpickedshark%2F2019-11-10%2FACC6347A5_lanes_1234_sorted_md_brecal.bam.bai&contig=9&start=79820218&stop=79820318&center_guide=T


Från: Daniel Nilsson <notifications@github.com>
Skickat: den 18 november 2019 10:34
Till: Clinical-Genomics/scout <scout@noreply.github.com>
Kopia: Håkan Thonberg <hakan.thonberg@sll.se>; Author <author@noreply.github.com>
Ämne: Re: [Clinical-Genomics/scout] BCFTools making weird calls: Ref 10 Alt. 2 (#1524)


Japp, helt klart! Fast om jag skulle bedöma så är det nog inte homozygot referens på alla positioner däromkring heller, så tycker nog att det är lite bra att den iaf hostar lite när de andra avropsprogrammen tiger:
[Screenshot 2019-11-18 at 10 32 55]<https://user-images.githubusercontent.com/758570/69040869-de05a600-09ee-11ea-8f10-08af1a53f8b0.png>

**Comment by dnil** [comment]
Mm, möjligt att den inte lirar så bra med twist kanske? Var det dåligt med DNA eller varför går de som exom?!

**Comment by 47KW** [comment]
Det är Kardio-panel som vi kör som TWIST exom
Tror att det inte lirar så bra …..

Från: Daniel Nilsson <notifications@github.com>
Skickat: den 18 november 2019 11:04
Till: Clinical-Genomics/scout <scout@noreply.github.com>
Kopia: Håkan Thonberg <hakan.thonberg@sll.se>; Author <author@noreply.github.com>
Ämne: Re: [Clinical-Genomics/scout] BCFTools making weird calls: Ref 10 Alt. 2 (#1524)


Mm, möjligt att den inte lirar så bra med twist kanske? Var det dåligt med DNA eller varför går de som exom?!

**Comment by dnil** [comment]
Oki; jag tycker som sagt att vi ser till att få till en lite ordentligare lokal db med twist-exom, men det får ligga på MIP-sidan. Det är möjligt att bcftools inte gör nytta där - eller alls när vi inte har Agilent exom längre. Vi får gemensamt samla vidare på eventuella ställen där den är ensam om ett riktigt fynd, så hoppas vi vi kan stänga av den eller bara filtrera bort det lokala bruset sedan!
