### ISSUE TITLE
Enable export on HPO term view

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#1528]
To facilitate the exchange of phenotypes with the clinical system, we would like to export HPO-term ids (HP:0000001) and Term names ("All") from scout. I think the current table view could actually be coerced to do that much like when exporting causatives.

**Comment by moonso** [comment]
Will this do?:
```csv
#hpo_id\tdescription
HP:0000012\tUrinary urgency
```

**Comment by dnil** [comment]
😄No, but I might have guessed. Still, that won’t help the clinic admins terribly - effectively meaning they would have to write a ticket for the list. We won’t have use for it until summer 2020 sometime anyway methinks.

**Comment by northwestwitch** [comment]
I can work on this if you haven't started yet @moonso
