### ISSUE TITLE
comments on patogenicity page are not saved

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#1534]
https://scout.scilifelab.se/cust003/18117/7df2dd00bf8311ded986d3205ef87812
for this variant I had written a comment under PS3 Functional damage (HQ), but I can not see it any longer once I go in here:

https://scout.scilifelab.se/evaluations/5dd40a3b124f63a9b5e68580

a Bug?

**Comment by northwestwitch** [comment]
I think the comment is saved but the area where it should be is not showing. We'll fix it, thanks for reporting it.

**Comment by moonso** [comment]
Yes, I have checked and it exists in the database @4WGH, there is a comment about mRNA analysis right? So like @northwestwitch said we need to display the comment when bringing up the evaluation. Nice find!
