### ISSUE TITLE
Research page 2 continues being a clinical page

### ISSUE THREAD

**Issue by 19SC** [Clinical-Genomics/scout#1539]
Hi,

I saw that you closed the issue "research page 2 is a clinical page #1514", but the problem isn't solved yet, right? I continue to have the clinical page instead of the research page, for example:

Fam 81:
(page 1) https://scout.scilifelab.se/cust003/81/variants?variant_type=research
(page 2) https://scout.scilifelab.se/cust003/81/variants

Thank you for your help.

**Comment by dnil** [comment]
Hi,

this might be a bit confusing to new users. We close issues when we have solved them in development of Scout. That does not mean that they are deployed to your particular instance (clinical genomics Solna) just yet!

Sorry, you will have to live with it for just a little longer. That update should be happening later this week, possibly even today. All our local users will be notified by email before a new release is going live. Thank you for your patience! :)

**Comment by 19SC** [comment]
Ok, thank you :).
