### ISSUE TITLE
Clinical filter suddenly changed

### ISSUE THREAD

**Issue by nicolelesko** [Clinical-Genomics/scout#154]
The clinical filter does not keep missense variants as it should.  Not sure if there are other variants included or excluded.

**Comment by robinandeer** [comment]
Hi @nicolelesko, thank you for the bug report

We are on top of this - it should be fixed very soon

**Comment by robinandeer** [comment]
Scout has been updated to fix this issue and you can also load more variants

@henrikstranneheim: can you review this update?

**Comment by henrikstranneheim** [comment]
Clinical filter bug seems fixed.

Filter bug:

- You can now load more variants with retained filtering options. So this seems ok
 
- Related to this: I noticed that the first 50 are removed from the view as the next 50 are displayed and there seems to be no way of going back, except using the browsers navigation button. this is perfectly fine for this hot fix , but maybe we should discuss if you would keep the original 50 and complement with the next 50. Something for the next Scout meeting perhaps.


On 01 Oct 2015, at 11:29, Robin Andeer <notifications@github.com> wrote:

> Scout has been updated to fix this issue and you can also load more variants
> 
> @henrikstranneheim: can you review this update?
> 
> —
> Reply to this email directly or view it on GitHub.
> 

Henrik Stranneheim Ph.D.
Department of Molecular Medicine and Surgery
Karolinska Institute
Science for Life Laboratory


E-mail: henrik.stranneheim@scilifelab.se
Visiting address: 
Science for Life Laboratory - SciLifeLab
Gamma building
Tomtebodavägen 23A
Delivery address:
Science for Life Laboratory - SciLifeLab
Gamma building
Tomtebodavägen 23B
171 65 Solna
