### ISSUE TITLE
Introduce scroll over long lists of items

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#1540]
For instance the long list of gene generated when you create an HPO gene panel.

For instance look at this case: https://scout-stage.scilifelab.se/cust000/F0000310-validation#phenotypes_panel

**Comment by dnil** [comment]
That is already on issue #1497 - but its better with separate issues, so just keep this issue and take it off that other list!

**Comment by dnil** [comment]
Better yet, solve all of them on #1488! I'll close this and reference for a nice mess of links. Please read old issues! 😜

**Comment by mayabrandi** [comment]
Okej
