### ISSUE TITLE
Wrong date on local observations archive

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/scout#1559]
For a recently uploaded case the date should be "2019-11-04" instead of "2017-05-31". Questions is if this is parsed somewhere or hardcoded (most likely)?

**Comment by northwestwitch** [comment]
Ahem..

![image](https://user-images.githubusercontent.com/28093618/69805978-29376a00-11e2-11ea-9e0d-063ea6a3dadd.png)

**Comment by dnil** [comment]
<img width="561" alt="Screenshot 2019-11-28 at 13 19 34" src="https://user-images.githubusercontent.com/758570/69805822-cf36a480-11e1-11ea-870f-b508110ab2d5.png">

🤣 I won't ask why this is so, but let's fix it. Is meaningful data (date, max alleles, max cases) exported in any file?

**Comment by northwestwitch** [comment]
> <img alt="Screenshot 2019-11-28 at 13 19 34" width="561" src="https://user-images.githubusercontent.com/758570/69805822-cf36a480-11e1-11ea-870f-b508110ab2d5.png">
> 
> 🤣 I won't ask why this is so, but let's fix it. Is meaningful data (date, max alleles, max cases) exported in any file?

Hahahaha exactly!!!

**Comment by dnil** [comment]
🤣

**Comment by moonso** [comment]
I'll check if it is possible to parse this from the VCF
