### ISSUE TITLE
New name for header in genemap2

### ISSUE THREAD

**Issue by ninanorgren** [Clinical-Genomics/scout#1562]
It seems OMIM has made an update to their formats, when running setup it crashes claiming there is no key called 'Mim Number', in the file scout/parse/omim.py. (Sorry that I cannot print all the error output, as the ensembl server is still down I cannot get far enough to reach this error again). But looking at the genemap2 file it looks like the column name is now 'MIM Number'.

**Comment by dnil** [comment]
Yep - quite right and well described! Thank you for reporting. This is fixed in current master, but not yet in the release. See issue #1544 and PR #1545!

**Comment by ninanorgren** [comment]
Ah, sorry didn't see that. Seems I didn't update to the current version
