### ISSUE TITLE
Always show affected patient in the top FIXED

### ISSUE THREAD

**Issue by moonso** [Clinical-Genomics/scout#157]
In every case where cases are listed (gt calls etc), allways show affected patient in the top.

**Comment by moonso** [comment]
Ensure that the individuals are sorted in the correct order in the database

**Comment by moonso** [comment]
@robinandeer it says that this is fixed in master, if that is correct can you close?

**Comment by robinandeer** [comment]
I guess I didn't have to do anything special now so; yes :)
