### ISSUE TITLE
Submit genes to MME when variant is SV variant

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#1583]
Allow submission of SNVs only

**Comment by dnil** [comment]
Booooring! 😜

**Comment by northwestwitch** [comment]
Eh I know, that's me! An alternative might be allowing the submission of the gene name only, when the SV contains one gene..

**Comment by dnil** [comment]
Well, its probably more up to how the other end handles anything beyond a small variant. I do like the latter suggestion better - if it is possible. It would at least cover say single exon to single gene deletions!

**Comment by northwestwitch** [comment]
Ok, then I'll fix it so any SV that has one gene will be converted to a gene-only submission.

**Comment by northwestwitch** [comment]
Actually, SVs are not conforming to the MME api so it is not even possible to submit them at the moment:

![image](https://user-images.githubusercontent.com/28093618/70713636-b997a380-1ce6-11ea-9343-a971efc37847.png)

With this fix will be at least possible to submit data at the gene level
