### ISSUE TITLE
ftplib problem

### ISSUE THREAD

**Issue by parlar** [Clinical-Genomics/scout#1591]
The ```get_request()``` function in ```request.py``` does not alwas manage to download the 'hgnc_complete_set.txt' file from ebi during the initial database setup.

Sometimes it works, sometimes it doesn't, at least here within our hospital environment. At the university it works fine, so it seems to be some incompatibility with our network infrastructure but perhaps also with other corporate environments?

It turns out that urllib.request does not handle FTP requests itself, they are referred to ftplib. I have tried to find a solution for the problem with ftplib did not succeed. I have tried both python 3.6.8 and 3.8.0 and the problem persists in both these releases. However, I did try another ftp library (ftpretty) that worked flawlessly.

It's definately messier but should we use some other lib for ftp downloads?

**Comment by northwestwitch** [comment]
Hi Pär! 
I don't know about the others, but I personally have anything against using another library instead  of ftplib. If you tested ftpretty and it works we could include that instead. If you have some working code already could you create a pull request? We'll try to review it this week!

**Comment by northwestwitch** [comment]
Another feasible alternative would be changing the code to re-introduce the option to provide an already downloaded file. We had it like this before!

**Comment by dnil** [comment]
The option to use existing files is not a bad idea: I sometimes feel embarrassed for re-downloading again while testing.

But I also agree on libraries - as far as I know we have no particular attachment to ftplib. It does appear sort of standard, and ftpretty a more recent development. Still, whatever works: if you already tried it, just make a PR for it we will review and test! :+1:

**Comment by parlar** [comment]
I guess the possibility to use already downloaded files would solve also the other issue that I just entered: https://github.com/Clinical-Genomics/scout/issues/1592

On the other hand, making things simple and smooth for new users seems attractive too so they (we!) don't have to download everything manually first. I can implement both things if you think I should. It should only take minutes.

**Comment by northwestwitch** [comment]
I've just spoken to @moonso and he offered to reintroduce the code to provide downloaded files (he already knows this part of the code well)

**Comment by moonso** [comment]
Hi @parlar , I can implement to upload with static files. If you want to do the ftp-thing feel free to open a PR!

**Comment by parlar** [comment]
Brilliant, thanks!

**Comment by parlar** [comment]
Good morning, @moonso et al! Just so that I understand, changes have now been included to better handle when the Ensemble REST service is down. But is the question of using pre-downloaded data files for setup still open?

**Comment by dnil** [comment]
Yep, still open, but not quite as urgent! @moonso called dibs on this, as he wrote the old version of the code that actually did this. From the sidelines, if you beat him to reintroducing it, there is no harm done. 😺

**Comment by moonso** [comment]
Oh I kind of forgot about it. Sure I will add this. I guess the files needs to be downloaded with scout to follow the correct format. And there are quite a number of files to include...

**Comment by parlar** [comment]
Sound good! (and hint taken.. :) ) @moonso , I could give it a go if you have problems finding time. My grasp of the scout code base is somewhat limited but I should be able to figure things out I think.

**Comment by moonso** [comment]
I'm working on it today @parlar so you can wait with the contribution 😄
