### ISSUE TITLE
Repeat locus name on STR call page

### ISSUE THREAD

**Issue by 47KW** [Clinical-Genomics/scout#1601]
Could we please have the repeat locus name on the "call page"? This link would for instance benefit from reading "DIP2B" somewhere in the Basics-box.

https://scout.scilifelab.se/cust002/F0032628/c51147e856c3ec1d236df6adb9187e7c?str=yes

**Comment by northwestwitch** [comment]
Sure, it should be quite easy!

**Comment by 47KW** [comment]
Great start on the new easy year of 2020.

Thanks a lot!

Från: Chiara Rasi <notifications@github.com>
Skickat: den 2 januari 2020 10:07
Till: Clinical-Genomics/scout <scout@noreply.github.com>
Kopia: Håkan Thonberg <hakan.thonberg@sll.se>; Author <author@noreply.github.com>
Ämne: Re: [Clinical-Genomics/scout] Repeat locus name on STR call page (#1601)


Sure, it should be quite easy!
