### ISSUE TITLE
Comments being labelled old without a rerun being requested

### ISSUE THREAD

**Issue by NicoleCMMS** [Clinical-Genomics/scout#1606]
Family 19266 was uploaded to Scout on 8 January and the data was analysed in the afternoon by Anna Wredenberg and myself. On 9 January I noticed that our comments had been labelled as 'old'. All of the variants that were dismissed are still present which indicates that the data has not been rerun. Henrik suggested I report this as an issue ;-)

**Comment by dnil** [comment]
I might not have the full picture, but I think you are better of with a ticket to production to figure this one out? There are two delivery reports for the case, one conspicuously from 9/1, indicating that a rerun had been uploaded, and the other from 23/12. The amateur sleuth in me wants to wager that a somewhat incomplete version was managed in time for the holidays and that the more recent upload is complete and ready for customer analysis? At any rate, I don't quite see what we can help you with from a developer perspective? Please just let us know if I'm missing something. Closing this for now!

**Comment by dnil** [comment]
Well, ok, thinking one step further, perhaps Scout could e.g. be more strict in limiting certain uploads from production. I still kind of feel that this would be better discussed in a ticket or by phone first to figure out what we should change!

**Comment by NicoleCMMS** [comment]
Yes you are correct Daniel. This family was delivered before Christmas to allow us to look at mtDNA variants but coverage of the nuclear genome was low so more sequencing was performed before carrying out a second upload. We were informed on 8/1 that this was complete and that is when the analysis of IEM-panel was carried out. Is it so that the delivery report is sometimes uploaded later?  If this is so is it the uploading of the delivery report which triggers the 'old' comments?

**Comment by dnil** [comment]
Right! The logic for showing that OLD label is simply a check if the comment is older than the last update to the case. Separate upload of a delivery report is counted as an update to the case, so that would fit. 

Again, a ticket or phonemail to the production team is a good way to get support on this, as it has little to do with the functionality in scout. From my experience a case is first partially loaded, manually checked and possibly updated before an delivery report is issued and sent to the customer. Sometimes a few h or days can pass between initial upload and delivery, depending on any number of factors. 

Let us know if we can do anything to make this more transparent / logical in scout! Perhaps a "pre-delivery" status for cases would be helpful? @emiliaol @moonso

**Comment by emiliaol** [comment]
Are you sure the upload of the delivery report triggers a the "old" flagging? All delivery reports are uploaded separately after the cases have been checked in scout by us and marked as delivered in our lims. Are then all comments old if they are made before the upload of the delivery report? I usually don't look at a case in scout at this point so I don't know.

**Comment by NicoleCMMS** [comment]
Yes this is something I noticed a number of times now.  The latest case was family 20009. I specifically checked and confirmed that the delivery report had not been uploaded in Scout before going through the case and making comments. Later the same day I noticed that my comments had been tagged ‘old’ and the delivery report had been uploaded. There may of course be other triggers but this is at least one potential cause.

Sorry haven’t managed to make a ticket of this yet…..do you still need a ticket or can you take this from issues?

Nicole

Från: emiliaol <notifications@github.com>
Skickat: den 16 januari 2020 09:45
Till: Clinical-Genomics/scout <scout@noreply.github.com>
Kopia: Nicole Lesko <nicole.lesko@sll.se>; Author <author@noreply.github.com>
Ämne: Re: [Clinical-Genomics/scout] Comments being labelled old without a rerun being requested (#1606)


Are you sure the upload of the delivery report triggers a the "old" flagging? All delivery reports are uploaded separately after the cases have been checked in scout by us and marked as delivered in our lims. Are then all comments old if they are made before the upload of the delivery report? I usually don't look at a case in scout at this point so I don't know.

**Comment by dnil** [comment]
I think we have understood the issue, right @emiliaol? Normally only a short time passes between the uploads, and you may have been the first to notice. I suppose this will change as more people work in scout every day. If you feel this is a problem, do say so, and we could try to think of a nice way to illustrate the status of the case, or solve it with a behind the scenes procedure e.g. uploading to a test environment first to confirm that everything looks good before releasing the delivery report?
