### ISSUE TITLE
Conservation and REVEL scores annotations

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/scout#1608]
MIP 8 have removed snpeff - now these annotations are calculated using VEP. As such they are now part of the CSQ field instead of the vcf INFO field.

```
GERP++_NR|GERP++_RS|REVEL_rankscore|phastCons100way_vertebrate|phyloP100way_vertebrate is
```

**Comment by northwestwitch** [comment]
This is a bit more tricky because we still want to maintain backward compatibility so I guess we should allow for both types of parsing: from the INFO and the CSQ field, right?
