### ISSUE TITLE
Highlight causative transcript(s) FIXED

### ISSUE THREAD

**Issue by moonso** [Clinical-Genomics/scout#161]
These should be highlighted on variant level

**Comment by dnil** [comment]
canonical transcript would be a great fallback for genes where this is not available.

**Comment by moonso** [comment]
@dnil , @henrikstranneheim How do we get the canonical transcript?

**Comment by dnil** [comment]
Hgnc (genenames.org) have a single curated transcript which is the de facto standard transcript for setting up single gene tests, with the refSeq mildly preferred over ensembl - and a REST to retrieve them (http://www.genenames.org/help/rest-web-service-help). They don't make explicit claims about disease causation - this is about standardized nomenclature.
Still, for the genes I checked, they did get the preferred, relevant transcript.  I'd say this makes an acceptable fallback, but perhaps "HGNC transcript" is a better name for it than canonical.

Ensembl have a well defined "canonical transcript" (http://www.ensembl.org/Help/Glossary?id=346) themselves. Often, but not always what we want. 


Skickat från min iPad

**Comment by henrikstranneheim** [comment]
My suggestion would be to include the canonical transcript from HGNC or Ensembl when building the clinical master list, using the same rules we have for phenotypic model. 

We should include Kenny in this discussion.

On 15 Oct 2015, at 00:03, Daniel Nilsson <notifications@github.com> wrote:

> 
> Hgnc (genenames.org) have a single curated transcript which is the de facto standard transcript for setting up single gene tests, with the refSeq mildly preferred over ensembl - and a REST to retrieve them (http://www.genenames.org/help/rest-web-service-help). They don't make explicit claims about disease causation - this is about standardized nomenclature.
> Still, for the genes I checked, they did get the preferred, relevant transcript. I'd say this makes an acceptable fallback, but perhaps "HGNC transcript" is a better name for it than canonical.
> 
> Ensembl have a well defined "canonical transcript" (http://www.ensembl.org/Help/Glossary?id=346) themselves. Often, but not always what we want. 
> 
> 
> Skickat från min iPad
> 
> > 14 okt. 2015 kl. 21:14 skrev Måns Magnusson <notifications@github.com>:
> > 
> > @dnil , @henrikstranneheim How do we get the canonical transcript?
> > 
> > —
> > Reply to this email directly or view it on GitHub.
> > 
> —
> Reply to this email directly or view it on GitHub.
> 

Henrik Stranneheim Ph.D.
Department of Molecular Medicine and Surgery
Karolinska Institute
Science for Life Laboratory


E-mail: henrik.stranneheim@scilifelab.se
Visiting address: 
Science for Life Laboratory - SciLifeLab
Gamma building
Tomtebodavägen 23A
Delivery address:
Science for Life Laboratory - SciLifeLab
Gamma building
Tomtebodavägen 23B
171 65 Solna

**Comment by ingkebil** [comment]
Hi,

Sounds like something that'd be rather easy to include in the gene list.
In a Gene list we have a field called Ensemble_transcript_ID which could be
used for this if we go for ensembl transcripts. Now this is annually
curated field only filled in from cmms as far as know.

I already query genenames.org to fetch HGNC aliases to enable me to query
ensembl more easily, so it wouldn't be such a problem to add a query or to
extend that one to fetch the transcript information.

Omim also provides a list called morbidmap that has a ensembl transcript
(grch38 tho) listed. Just putting this out there.

If we want to add such a field in the gene list, suggestions on the name
are welcome,

Wkr,
Kenny

Composed and sent on the road

**Comment by henrikstranneheim** [comment]
This info should go under “Disease_associated_transcript” and follow the same rules with cmms precedence for manually curated genes.

The HGNC website seems to be temporarily down. Is the HGNC transcript in refSeq format? If so let’s use that one.

/H

On 15 Oct 2015, at 08:40, Kenny Billiau <notifications@github.com> wrote:

> Hi,
> 
> Sounds like something that'd be rather easy to include in the gene list.
> In a Gene list we have a field called Ensemble_transcript_ID which could be
> used for this if we go for ensembl transcripts. Now this is annually
> curated field only filled in from cmms as far as know.
> 
> I already query genenames.org to fetch HGNC aliases to enable me to query
> ensembl more easily, so it wouldn't be such a problem to add a query or to
> extend that one to fetch the transcript information.
> 
> Omim also provides a list called morbidmap that has a ensembl transcript
> (grch38 tho) listed. Just putting this out there.
> 
> If we want to add such a field in the gene list, suggestions on the name
> are welcome,
> 
> Wkr,
> Kenny
> 
> Composed and sent on the road
> On Oct 15, 2015 6:24 AM, "henrikstranneheim" <notifications@github.com>
> wrote:
> 
> > My suggestion would be to include the canonical transcript from HGNC or
> > Ensembl when building the clinical master list, using the same rules we
> > have for phenotypic model.
> >
> > We should include Kenny in this discussion.
> >
> > On 15 Oct 2015, at 00:03, Daniel Nilsson <notifications@github.com> wrote:
> >
> > >
> > > Hgnc (genenames.org) have a single curated transcript which is the de
> > facto standard transcript for setting up single gene tests, with the refSeq
> > mildly preferred over ensembl - and a REST to retrieve them (
> > http://www.genenames.org/help/rest-web-service-help). They don't make
> > explicit claims about disease causation - this is about standardized
> > nomenclature.
> > > Still, for the genes I checked, they did get the preferred, relevant
> > transcript. I'd say this makes an acceptable fallback, but perhaps "HGNC
> > transcript" is a better name for it than canonical.
> > >
> > > Ensembl have a well defined "canonical transcript" (
> > http://www.ensembl.org/Help/Glossary?id=346) themselves. Often, but not
> > always what we want.
> > >
> > >
> > > Skickat från min iPad
> > >
> > > > 14 okt. 2015 kl. 21:14 skrev Måns Magnusson <notifications@github.com
> > >:
> > > >
> > > > @dnil , @henrikstranneheim How do we get the canonical transcript?
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub.
> > > >
> > > —
> > > Reply to this email directly or view it on GitHub.
> > >
> >
> > Henrik Stranneheim Ph.D.
> > Department of Molecular Medicine and Surgery
> > Karolinska Institute
> > Science for Life Laboratory
> >
> >
> > E-mail: henrik.stranneheim@scilifelab.se
> > Visiting address:
> > Science for Life Laboratory - SciLifeLab
> > Gamma building
> > Tomtebodavägen 23A
> > Delivery address:
> > Science for Life Laboratory - SciLifeLab
> > Gamma building
> > Tomtebodavägen 23B
> > 171 65 Solna
> >
> >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/Clinical-Genomics/scout/issues/161#issuecomment-148277066>
> > .
> >
> —
> Reply to this email directly or view it on GitHub.
> 

Henrik Stranneheim Ph.D.
Department of Molecular Medicine and Surgery
Karolinska Institute
Science for Life Laboratory


E-mail: henrik.stranneheim@scilifelab.se
Visiting address: 
Science for Life Laboratory - SciLifeLab
Gamma building
Tomtebodavägen 23A
Delivery address:
Science for Life Laboratory - SciLifeLab
Gamma building
Tomtebodavägen 23B
171 65 Solna

**Comment by dnil** [comment]
HGNC have several - based on genbank, with best match in refSeq and ENSembl. Agree on refSeq, 
and that any locally curated gets precedence!

Interesting with the morbidmap transcript - I couldn’t find any docs though?

**Comment by moonso** [comment]
- [ ] Add ``ìs_canonical``` to transcript model
- [ ] Display the transcript in color if it is canonical

**Comment by moonso** [comment]
We will start to annotate this when we move to external database for region annotations

**Comment by dnil** [comment]
Ah, I just noticed that VEP annotates its take (ENSEMBL?) on canonical transcript with flag --canonical.S If this holds out as appropriate transcripts, it seems more appropriate to call it at the variant annotation step than leave it for gene lists.

**Comment by moonso** [comment]
Agree! That sounds like a nice solution. What do you think @henrikstranneheim ?

**Comment by henrikstranneheim** [comment]
I agree. It is good to include it in a process that is already set up for simplicity. I have added the flag to the default VEP features. VEP annotates the canonical transcript with a "YES".

**Comment by moonso** [comment]
We will pick `CANONICAL` from VEP annotation to begin with

**Comment by robinandeer** [comment]
DONE

**Comment by henrikstranneheim** [comment]
Kind reminder to not forget this:
This info should go under “Disease_associated_transcript” and follow the same rules with cmms precedence for manually curated genes and then fall back on CANONICAL.

**Comment by robinandeer** [comment]
@moonso: is that accessible from the model?
