### ISSUE TITLE
In Managed variant lIst disappears (cancer variants filters)

### ISSUE THREAD

**Issue by patrikgrenfeldt** [Clinical-Genomics/scout#1612]
From https://github.com/Clinical-Genomics/scout/issues/1460

**Comment by northwestwitch** [comment]
Does anybody remember what this issue was about, the title is really cryptic..

**Comment by hassanfa** [comment]
I don't remember either. But if it is a filter that doesn't show up, I'm sure it will popup again :-)

**Comment by patrikgrenfeldt** [comment]
@dnil could you add any details on this issue?

**Comment by northwestwitch** [comment]
covfefe

**Comment by dnil** [comment]
> covfefe

🤣 Well, do the MVL annotations disappear? I don't think we have any MSK_MVL in the test case: perhaps a good start could be to add one such?

**Comment by dnil** [comment]
..and the original bug report was likely about not staying on/returning to the cancer variants page after all types of clicking back and forth? Likely there is some place where this is/was not cared for, e.g. the navigation bar/next-buttons etc on the cancer variant page?

**Comment by hassanfa** [comment]
Mvl bed files can be found here. I can also prepare a vcf if you'd like it that way.https://github.com/Clinical-Genomics/BALSAMIC/tree/master/BALSAMIC/assets/MVL

**Comment by dnil** [comment]
I thought mostly just spice one of them into the demo case vcf? I had a quick click-through on the cancer variants page and variant page but can't find any remaining links that don't lead to the cancer version. I think it is safe to close this covfefe, possibly after adding a demo MVL variant.

**Comment by moonso** [comment]
Let's close this and feel free to open as issue that describes the actual problem

**Comment by dnil** [comment]
..also I think there is a fair chance it is now fixed after e.g. #1681 and some others. But hard to tell.. 😆
