### ISSUE TITLE
Show both RD and cancer loqus frequencies on the cancer page

### ISSUE THREAD

**Issue by patrikgrenfeldt** [Clinical-Genomics/scout#1617]
From https://github.com/Clinical-Genomics/scout/issues/1460

**Comment by moonso** [comment]
This would require two loqus connections (to the two different instances) as it looks today

**Comment by dnil** [comment]
-[x] Multiple loqus connections are possible since #1984. Next steps would be
-[ ] to init and 
-[ ] enable loqus data collection for Balsamic in CG. 
-[ ] configure Scout to point appropriate institutes to the corresponding loqus
