### ISSUE TITLE
Clinvar submissions

### ISSUE THREAD

**Issue by AnnHam** [Clinical-Genomics/scout#1625]
I want all users at Clinical Genetics (cust 002) to see my "variant data" that I want to submit to ClinVar. So we can make a bulk input for submssion of variants (in a "submission CSV file"). 

(tested with another user and she can't see the variant that I marked in the "mirror-clinvar-scout-site" - https://scout.scilifelab.se/cust002/clinvar_submissions)

**Comment by northwestwitch** [comment]
It should be quite easy to fix, I'll take a look at it ASAP!
