### ISSUE TITLE
Some issues with the new CI lint?

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#1627]
```The command "git reset --soft ${TRAVIS_COMMIT_RANGE%...*} && git lint" exited with 1.```

**Comment by patrikgrenfeldt** [comment]
![image](https://user-images.githubusercontent.com/6697636/72619098-d73ad700-393c-11ea-89b4-9a9870a7925d.png)

Git lint will give a non-zero exit code if it has suggestions on how to improve the code, if all linting is OK (green) then it will exit with 0 and this job will be successful. 

Do you have any suggestions on changing and improving?

**Comment by dnil** [comment]
Ah, thank you! That is.. ehr.. very thorough. I kind of thought it would reserve that for run errors -after all finding whitespace style offence is sort of its job. And the "tidy" part is also expected?

**Comment by patrikgrenfeldt** [comment]
Tidy seems to be installed but not recognized, I'll see if I can figure out why
