### ISSUE TITLE
Try out GitHub actions!

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#1628]
It should be fairly simple to migrate from travis to actions. See e.g. 
https://github.com/actions/starter-workflows/blob/master/ci/python-app.yml
I suppose there are now mongo-enabled 

A couple of additional suggestions would be to automate docs generation - and perhaps docker generation once that is merged.

**Comment by moonso** [comment]
I will close this with #1821 , we have tried it out:D We can open other issues around releases and autogenerated docs in the future
