### ISSUE TITLE
QoL changes to Variant list view for cancer cases

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/scout#1629]
During a brief discussion today with Chiara, Patrick, and Mikael, we come up with a small list of changes that we thought it would be useful to clear up some Variant list view for cancer cases. These items are:

- [x] Pop. Freq. column is named "Exac", either remove it or replace it with actual COSMIC variants that are matching. I think removing it with Cosmic ID or count of COSMIC variants is more reasonable. Since we already have gnomadAF in filters, removing it won't harm.
Column example of how it can be:
![image](https://user-images.githubusercontent.com/1086877/72622574-c9d51b00-3943-11ea-8af4-125bf59b26c6.png)

- [x] When there is no matching Normal sample, the value of Normal column is ambiguous. Showing "N/A" instead of "N/A /" is much better. Example of removing "/": 
![image](https://user-images.githubusercontent.com/1086877/72622365-56330e00-3943-11ea-879d-919cd5d34163.png)
~~- [ ] Add custom sorting per column. i.e click a column will rearrange the list.~~
- [x] Remove pedigree section from cancer cases: 
![image](https://user-images.githubusercontent.com/1086877/75860969-f8785980-5dfc-11ea-8d69-08c7e0fd0d95.png)
- [x] Genes names are not showing up in the Variant ID. This should be consistent, regardless of variant type or missing gene. Example of how it is right now:
![image](https://user-images.githubusercontent.com/1086877/72622622-e5402600-3943-11ea-9583-160ad7c710a0.png)

- [x] Header for second column is: `Variant:Transcript:Exon:HGVS`. It is not matching the actual value of the column which is: `Gene:Transcript:Exon:HGVS`. And related to previous case, sometimes gene names are not showing up. ![image](https://user-images.githubusercontent.com/1086877/72622306-3bf93000-3943-11ea-9849-882ad1497652.png)

- [x] Only show 2 decimals instead of 4-5 decimals in AF for Tumor and Normal. Example:
![image](https://user-images.githubusercontent.com/1086877/72623201-f8072a80-3944-11ea-8160-43b55b44b9fe.png)

~~- [ ] Ranks in Cancer view are not ranks, and it creates confusion sometimes. Column header shouldn't be called "Rank" if there is not rankscore used.~~

Clarification (everyone knows but just to keep it clean): Gene name refers to "Approved Gene Symbol", or "HGNC Symbol", or "Name2" (UCSC's database column name". Also see here: https://www.ebi.ac.uk/miriam/main/collections/MIR:00000362

**Comment by hassanfa** [comment]
@mikaell @patrikgrenfeldt Did I miss anything?

**Comment by hassanfa** [comment]
We also discussed other stuff such as providing annotations from cbioportal, oncokb and other databases, but I would leave that for future.

**Comment by mikaell** [comment]
> @mikaell @patrikgrenfeldt Did I miss anything?

I don't think so. Let's start here. I'm installing a separate Scour for cancer and started playing around.

**Comment by hassanfa** [comment]
Thinking about Exac column, it might still be used in some cases. It would be great to try out and see if we can squeeze COSMIC there, or just show the count of cosmic variants in hover-text.

**Comment by mikaell** [comment]
> Thinking about Exac column, it might still be used in some cases. It would be great to try out and see if we can squeeze COSMIC there, or just show the count of cosmic variants in hover-text.

Hi,
Does COSMIC have a interface i.e. SOAP, REST or similar?

Or do you have some other idea how it should be accessed? This seems like a bigger task than the others on the list, maybe make a separate feature request?

**Comment by hassanfa** [comment]
As far as I know, COSMIC doesn't have those. Right now in Scout, COSMIC variants are pointed to it via https://cancer.sanger.ac.uk/cosmic/mutation/overview?id= 
https://github.com/Clinical-Genomics/scout/blob/5d3977b9383ce347de1f946314076da544fd0e91/scout/server/links.py#L350-L368

So to access COSM7298707, the URL will be https://cancer.sanger.ac.uk/cosmic/mutation/overview?id=7298707 and their website redirects to  https://cancer.sanger.ac.uk/cosmic/mutation/overview?id=20490211

Note: COSMIC is retiring their old COSM{[1-9]+} to COSV{[1-9]+} See https://github.com/Clinical-Genomics/scout/issues/1304

**Comment by hassanfa** [comment]
I found an example of missing gene names in Variant list view, on second column

https://scout.scilifelab.se/cust087/noblebee/cancer/variants?variant_type=clinical&gene_panels=lymphoma_6

Gene name is not being picked up for SAMHD1:
![image](https://user-images.githubusercontent.com/1086877/75554831-627ab280-5a3b-11ea-8296-c215f613df03.png)

**Comment by hassanfa** [comment]
After talking to @mikaell I noticed Scout is taking only first COSMIC ID to show in URL: https://github.com/Clinical-Genomics/scout/blob/5d3977b9383ce347de1f946314076da544fd0e91/scout/server/links.py#L350-L370

It might miss other overlapping cosmic ids and thus miss to show it. Probably remove single URL, and construct URL based on list of cosmic IDs instead.
