### ISSUE TITLE
Wrong ID in family 14048

### ISSUE THREAD

**Issue by 1ctw** [Clinical-Genomics/scout#163]
Family 14048 has wrong ID, see dump.
![14048](https://cloud.githubusercontent.com/assets/15033593/10368027/a6c219c8-6dd3-11e5-94e5-4bf190ba9900.GIF)
/Helene

**Comment by moonso** [comment]
Wrong in ped file, can you fix @emmser ?

**Comment by emmser** [comment]
Fixed ped
