### ISSUE TITLE
Form validation in age and tissue type case form

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#1633]
- [x] Validate age and tissue type form on case page.
- [x] Fix bug that inactivate case when values are submitted using this form 
- [x] The inactivate case feature also appears on other case level changes, e.g. matchmaker submission

Error message for the first part of the issue:
File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/cases/views.py", line 446, in update_individual
    controllers.update_individuals(store, institute_obj, case_obj, user_obj, ind_id, age, tissue)
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/cases/controllers.py", line 451, in update_individuals
    subject['age'] = round(float(age), 1)
ValueError: could not convert string to float:

**Comment by dnil** [comment]
The inactivate case feature also appears on other case level changes, e.g. matchmaker submission.

**Comment by northwestwitch** [comment]
This fix becomes urgent!

**Comment by northwestwitch** [comment]
This is very weird, for validation is already in place for age and tissue type fields and it is very complicated to input an age which is not a number. But if you manage to do it the form submission is blocked correctly with an error message (as it should be). Must be some very old browser from the hospital!

**Comment by northwestwitch** [comment]
Ahhh the error is in the tissue field, found it!

**Comment by northwestwitch** [comment]
> Ahhh the error is in the tissue field, found it!

It wasnt exactly that, but it should be fixed now
