### ISSUE TITLE
UI bug

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/scout#1636]
There is a tiny bug where institute name changes after selecting tab for clinvar submissions.

Steps:
1. click on institute:
![image](https://user-images.githubusercontent.com/1086877/72809759-90125600-3c5c-11ea-8e8f-3c36d345586d.png)
2. click on an institute, here i clicked on "clinical genomics"
![image](https://user-images.githubusercontent.com/1086877/72809799-a6201680-3c5c-11ea-83a6-ed5e03f50ec6.png)
3. Now that clinvar submssions shows up, click on "clinvar submission". clinical genomics changes to cust000 cases:
![image](https://user-images.githubusercontent.com/1086877/72809856-c6e86c00-3c5c-11ea-8477-bf804dd89a38.png)

**Comment by northwestwitch** [comment]
Thanks @hassanfa!
