### ISSUE TITLE
Disable temporarily the PEP8 compliance and lintfree controls for PRs?

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#1638]
I'd like to temporarily stop the Travis CI checks for PEP8 compliance and litfree for PRs. The idea is to be able to flexibly review and merge all the PRs which are open at the moment. Since we have accumulated a lot of open PRs and new issues it would be good to be able review and merge regardless of these latests checks.

The problem is that only admins (@moonso) is able to force merge at the moment and I don't know the others but personally I could use some help to speed up the whole process. So either other people become admin or we stop the tests and we reintroduce them after we release a new version of scout.

I'm sure we have a lot of things to learn by introducing the best practices and I'm very positive to use the checks in the near future but I feel like I have way too much work at the moment and I don't really have the time to fix aso formatting issues..

What do you think?

**Comment by dnil** [comment]
Agreed! Unless we clone @moonso - or give us all admin access, which I would not recommend - this is the only viable option. I'd suggest nerfing the travis tests to run the lint and black tests, but always return success. That way we can look through the output if there is time, and learn, but not get stopped over someone other than the language designers idea of what equal signs and what commas can have whitespaces around them.

**Comment by northwestwitch** [comment]
And also unless there is a very easy way to pass these tests, like the pre-commit install, which I tried but it didn't work because of a missing config file, that I successively provised but it was not reallu appreciated by the commands and didn't work

**Comment by dnil** [comment]
I would still not like that we can't agree to merge even if there are some extra whitespace in a commit from somewhere without a pre-commit hook or applying that locally. I don't quite see the gain there. Still all for eventually blacking and keeping a check, but one that can be bypassed as needed.

**Comment by dnil** [comment]
I read through some more of the big lint outputs. There are actual errors caught in it: things that need be corrected. Not anything just yet that would not have been caught if the test coverage was 100%, but it isn't, so this does have merit. Lets go through and add issues / correct. The quality is going to improve from this @patrikgrenfeldt so feel good about it. But we can't have it blocking merges in the meantime

**Comment by dnil** [comment]
E.g. ```scout/server/utils.py:97:12: E0602: Undefined variable 'crom' (undefined-variable)```
