### ISSUE TITLE
Fix size of selects and input fields which became smaller after bootstrap 4

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#1644]
Check on cases and variants page

**Comment by moonso** [comment]
Looks like this is fixed in #1668:

![Skärmavbild 2020-02-05 kl  09 22 12](https://user-images.githubusercontent.com/405278/73823661-05ebf500-47f9-11ea-9cf3-8c0d813f8dc8.png)

**Comment by moonso** [comment]
[Set](https://developer.snapappointments.com/bootstrap-select/examples/) 'width: 'auto'
