### ISSUE TITLE
IGV pointer slightly off variant

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#1645]
See if something might be done

**Comment by dnil** [comment]
Appears more common with indels?

**Comment by northwestwitch** [comment]
I think I might have seen it also in plain SNVs..

**Comment by moonso** [comment]
I consider @mikaell as our IGV expert now so will assign him to these 😬 , feel free to remove yourself if you disagree.

**Comment by dnil** [comment]
There are not much details here, but I have a feeling this might be covered by #2345 (and possibly in a few cases #2170). Closing for now.

**Comment by mikaell** [comment]
I'm certainly no expert in IGV. But I can give it a shot if it's still an issue. Got some other more urgent stuff on my table right now though. Let me know if this is critical (marked as _closed_ so I assume not).

**Comment by northwestwitch** [comment]
This is fixed now @mikaell , fixed today by #2346

**Comment by dnil** [comment]
Thanks, and sorry fo jumping in - we got another similar issue, and we realised they were very likely the same! We'll reopen and make sure to ping you if it re-appears!
