### ISSUE TITLE
Make MatchMaker result view scrollable

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#1654]
- [ ] NOT URGENT. Sometimes matching patients have a long list of contacts and they will not be displayed well in the space available for this field. The list can be copied and visualized somewhere else anyway, and probably this won't happen that often.
- [ ] Other small improvement: make the MatchMaker node select a little prettier because now it looks like this:

![image](https://user-images.githubusercontent.com/28093618/73269895-f4459480-41dd-11ea-90d5-9435f652e73e.png)

**Comment by elevu** [comment]
Done!
