### ISSUE TITLE
Add cram_path to scout load case

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/scout#1655]
Since Scout now supports both bam and cram under the "bam_path" it seems inappropriate to add a anything that is not a BAM file under the "bam_path".

I would therefore like to add another key called "cram_path" to the scout config.

If it does not matter to Scout if the alignment file is in BAM or CRAM - then I think we should consider replacing the keys "bam_path" and "cram_path" with "alignment_file_path" (or something similiar) and deffer the need to check the format until it is actually required (for instance in IGV). But since that requires a major bump, I suggest we start with adding a "cram_path" key. What do you think? @northwestwitch @moonso @dnil

**Comment by northwestwitch** [comment]
As we discussed earlier today I am open to generalize and name alignments as alignment_file_path, but I think we should also allow to parse from the  "bam_path" key, otherwise we won't be able to load any bam/cram files from the old cases.  I suggest we keep the parsing of the **bam_path** and add the generic **alignment_file_path**. Then we update the documentation and we explain that **alignment_file_path** means bam and cram files

**Comment by dnil** [comment]
:+1: Don't feel too bad about passing CRAM files to bam_path - I have seen considerably longer semantic stretches for option names. But good to add a more agnostic alias.

**Comment by northwestwitch** [comment]
> Don't feel too bad about passing CRAM files to bam_path

I never felt bad about it, not even for a minute! :)

**Comment by henrikstranneheim** [comment]
Sounds good! I will add the bam_paths and cram_paths going from housekeeper to the the "alignment_file_path" key.

**Comment by moonso** [comment]
I didn't understand the conclusion of your conversation :) Why not reuse `bam_path` ? It will never happen that one use both cram and bam for a case. And we can support both formats by checking if it is a bam or cram when loading.

**Comment by henrikstranneheim** [comment]
It is a minor detail, but a cram path is not a bam path even if Scout uses it like they are the same internally. It does not seem logical to load another type of format under a explicit key, like that. It also does not make it evident that Scout can load crams as well, since there is no cram_path key. This does not really have to do with the code, even though I at least would be surprised to look up the value for bam_path and see a different format coming out.

If we use a more agnostic "alignment_path" then, the program/user that creates the config is free to choose to load BAM or CRAM without going against the explicit "bam_path" key. Scout can then handle this internally, and decide when it matter what format was supplied as late as possible (for instance in loading into IGV). 

Does it make sense?

**Comment by dnil** [comment]
I very much agree on the principle, but in pragmatic practice would save this for very rainy day?

**Comment by henrikstranneheim** [comment]
That very rainy day is coming very soon in Clinical-Genomics/cg#533 and is already on Scout-stage. 😄 The upstream code is much easier to understand and maintain if we could at least provide a more agnostic key for alignment files.
