### ISSUE TITLE
Coverage test passes even if coverage goes down

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#1666]
I've noticed that all recent pull requests pass coveralls test and get the green icon regardless of the coverage. Shouldn't the test show the red cross if coverage goes down? 

Suggested tests for the PR fixing this:
1. Remove 2 tests. Expected result--> Coveralls fails because of coverage down (coveralls report published)
1. Reintroduce 1 test. Expected result--> Coveralls fails because of coverage down in comparison with master (coveralls report updated)
1. Reintroduce last test -> Coveralls passes because coverage doesn't change from master. (coveralls report updated).

**Comment by dnil** [comment]
Yes, great isn’t it? 😉 It’s a consequence of moving coveralls to a on-success operation. The status is already determined when coveralls starts. We could just move it back to be a separate process again, or move it in within the tested script part of one other processes - eg the PR test where it lives now.

**Comment by northwestwitch** [comment]
Whichever makes it fail again if coverage goes down is fine by me

**Comment by northwestwitch** [comment]
Tested to update the current open PRs, after updating them with the code of this one. Apparently this fix didn't work. I have the impression that the last commit of a branch is still compared against the one immediately before, and not master.

**Comment by patrikgrenfeldt** [comment]
> Yes, great isn’t it? 😉 It’s a consequence of moving coveralls to a on-success operation. ...

@dnil How do you know that is a consequence of moving coveralls to a on-success operation?

**Comment by dnil** [comment]
Hm, no, I don't really. I would not have written that if I had done some homework on it. Poorly phrased killgissning. When you ask, I have a recollection it was actually on-success before as well, albeit on different process level. I don't even know why the coveralls report is or was pulled on the GitHub / travis test results card as if it were a separate test. I don't think we explicitly define that. So some default at play?

**Comment by northwestwitch** [comment]
This is fixed now

**Comment by patrikgrenfeldt** [comment]
> Hm, no, I don't really. I would not have written that if I had done some homework on it. Poorly phrased killgissning. When you ask, I have a recollection it was actually on-success before as well, albeit on different process level. I don't even know why the coveralls report is or was pulled on the GitHub / travis test results card as if it were a separate test. I don't think we explicitly define that. So some default at play?

The only thing I think was different was that coverage was not uploaded on the build of the merge-build, a.k.a. PR. We do that again now and Chiara seems happy with the result..
