### ISSUE TITLE
Store pathogenic variants in own collection

### ISSUE THREAD

**Issue by moonso** [Clinical-Genomics/scout#167]
Pathogenic variants should be added when case is solved and closed

**Comment by robinandeer** [comment]
Tell me if we should show this somehow, or is this only for internal purposes?

**Comment by moonso** [comment]
I'm not completely sure if we will store them in their own collection but they will be accessible.
Is there anything more we want to do with them except exporting?

**Comment by henrikstranneheim** [comment]
They should be accessible for the aggregate data layer and as you said exportable for downstream analysis.

**Comment by moonso** [comment]
I consider this covered in #320 so closing
