### ISSUE TITLE
Editable fields on individual level in Cancer view

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/scout#1670]
This is similar to the recent change that Chiara added to Scout: Tissue type

- A solid tumor sample can have sub-types or an more precise tumor-type after analysis. The idea is to be able to either add a new tumor-type to the list of tumor-types or just change it to a completely new value:  1. List of tumor-types can be extracted from TCGA or NCI or OMIM. 2. Cell abnormality type: https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C12913&viewMode=All&siblings=false 
 Tumor_type is a bit vague at the moment, and it might be worthwhile to review this with correct terminology (abnormal cell types).

- Tumor purity: tumor purity estimate from order form can be forwarded to Scout. However, secondary analysis or post order form additions are possible. It might be useful to be able to update this value as well.

I talked to Chiara about this, and one solution of adding tumor-type, cell-type, etc can be to add them to list of constants.

I'll followup with more details as soon as I get more feedback.

**Comment by northwestwitch** [comment]
See #1581

**Comment by northwestwitch** [comment]
I could start with this today!

**Comment by northwestwitch** [comment]
- [ ] Editable tumor purity is a number in the range 0.1 - 0.9. Alert if it's less than 0.2
- [ ] Editable tissue
- [ ] Normal should have tumor type as N/A
- [ ] Editable tumor type

**Comment by northwestwitch** [comment]
@hassanfa question: now tumor purity is saved as a fraction, example 90/90, should it be converted to a number? But it can't be one because max is 0.9, suggestions?

**Comment by hassanfa** [comment]
That's cellularity: Tumor cell/Total cell ratio. It can be shown as a ratio or percentage that we discussed.

Let's have it as what we discussed: 0.1-1 for editable field. I know I said 0.9, but can we please have it 1? Thanks.

**Comment by hassanfa** [comment]
Just to make my previous comment clear, I might have written it hastily: we are discarding 90/90 format and using a decimal format instead, e.g. 0.3.

**Comment by northwestwitch** [comment]
> That's cellularity: Tumor cell/Total cell ratio. It can be shown as a ratio or percentage that we discussed.
> 
> Let's have it as what we discussed: 0.1-1 for editable field. I know I said 0.9, but can we please have it 1? Thanks.

Ok!

**Comment by northwestwitch** [comment]
> Just to make my previous comment clear, I might have written it hastily: we are discarding 90/90 format and using a decimal format instead, e.g. 0.3.

Ok, I'll fix the demo case as well then!

**Comment by northwestwitch** [comment]
Or not?, do you still want to save it as 90/90 in the database, or 1?

**Comment by hassanfa** [comment]
1
