### ISSUE TITLE
Add HGVS next to gene pinned

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#1676]
Add HGVS next to gene pinned because variants on the same gene will look the same.
Note - also important for cancer cases: transcript names are not so easy to read...

**Comment by christacosta** [comment]
This has not been updated for cancer scout in yesterday's release. Please add gene name and cDNA change also for us!

**Comment by dnil** [comment]
Thanks for the report! We will investigate..

**Comment by northwestwitch** [comment]
This is fixed in the currwnt master, we just have to deploy

**Comment by northwestwitch** [comment]
I'm sorry I answered to the wrong issue, this is not done yet

**Comment by northwestwitch** [comment]
We could include this small fix in the fix release of today, I'll create the PR now!

**Comment by dnil** [comment]
It turns out this was more difficult than I suspected: the db descriptions for the cancer variant genes are not quite complete. We will for the sake of time only introduce a simple fix today, showing gene numbers and HGVS, but will get back to you and this in the next release!

**Comment by dnil** [comment]
Looking good now: 

<img width="590" alt="Screenshot 2020-02-20 at 20 43 34" src="https://user-images.githubusercontent.com/758570/74972826-bc1f2380-5422-11ea-83f1-92f2272a1898.png">
