### ISSUE TITLE
question about causative- CLin Var

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#1678]
How can I see which variants have been submitted to clin Var ?

See case 1, ADK, the variant has been submitted to ClinVar in 2017
(https://www.ncbi.nlm.nih.gov/clinvar/variation/29603/)

There not info about it (that I can find) neither at the variant page nor in the "causatives" page

**Comment by dnil** [comment]
Hi there,

I think the original Magnus B ADK variant slightly predated Scout? 😊 I'm most likely missing something here. Lets start off by going through the most obvious:

- In general, all ClinVar **matches** presently show up under the variant "Summary" section, like so:

<img width="1075" alt="Screenshot 2020-02-03 at 12 41 52" src="https://user-images.githubusercontent.com/758570/73650598-cef3d300-4682-11ea-998a-f0d70225d435.png">

- If you have an ongoing ClinVar **submission** from Scout, it will show on the top nav bar on the Institute level, like so:

<img width="1492" alt="Screenshot 2020-02-03 at 12 44 35" src="https://user-images.githubusercontent.com/758570/73650809-4d507500-4683-11ea-956d-04c1ab1888be.png">

But, I think you might have known this. Did you have like a trial submission started for the ADK variant that went away, or what is the present issue? Cheers!

**Comment by 4WGH** [comment]
Thank Daniel! yes I new already.

I'm just making a strategy to start submitting to ClinVar from CMMS. Did some test with Chiara in september. But I notice now there is not an easy way at the variant level to see that a submission has been started or done.
We did a test for cases 19054 and 19162. Submission visible at "clinvar submissions page" , not submitted. No warning comes up if I try to submit the again. 

ADK was the only variatn alreasy submitted I could look at.... 
Do you have any other I can look at?

No need to find a solution now but it can be good to know I need to take note or have a way to save the info about the variants/cases already submitted. Expecially if we will make bulk submission.

anyway we will test with few to see what happens and I can spot out what we may need :)

**Comment by northwestwitch** [comment]
Hi Michela, the idea is that once you are ready for the final submission to clinvar you close the submission object in scout using the yellow "close submission" button in the submissions page:

![image](https://user-images.githubusercontent.com/28093618/73654515-35c9ba00-468c-11ea-95f9-bf6bd173b3f0.png)

This way you will know that the submission in in progress and no variants should be added to a submission already in progress (on clinvar). Any other variant that you want to submit after that will be part of another submission object (open)

**Comment by northwestwitch** [comment]
There is no current way to see if a variant is submitted at the variant level (but this should be easily fixable), anyway you can see relatively easily at the case level which cases and which variants belong to a clinvar submission, see on the right column of the case on the bottom:

![image](https://user-images.githubusercontent.com/28093618/73654792-dcae5600-468c-11ea-928a-61e3d0a20f98.png)

So if you have many variants to submit to clinvar, my suggestion is that you proceed at the case level, and from there you add the variants to an open submission object. Once you have added all the stuff you want to submit, you close the submission on scout and you download the file and continue on the clinvar pages with those.

**Comment by northwestwitch** [comment]
I forgot to add that the behavior you see: it is possible to submit to clinvar the same variant twice, it is intended (by me at least).
The thing is you might be interested to submit a certain variant to clinvar as pathogenic for a certain disease, but benign for another. If we lock clinvar submissions for a variant if it belongs to a submission object then this can't be possible.

**Comment by dnil** [comment]
Thanks @northwestwitch! If this becomes an issue we can as suggested add a note about local clinvar submission status to the variant level as well. As there are already a few ways to see this - notably at the case level - and the database isn't quite swimming in variants submitted this way yet, lets close this and reopen when needed!

**Comment by dnil** [comment]
And thank you for reporting @4WGH!
