### ISSUE TITLE
2020-03-04 9-10 Scout user meeting

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#1679]
KS Solna, BioClinicum, J8:10, Tantal 

**New features and bugfixes since last time**:
1. Display hgvs coordinates on pinned and causatives
1. Clear panel pending changes
1. Fixed ACMG classification not showing for some causatives
1. Fixed discrepancy between the manual disease transcripts and those in database in gene-edit page
1. Fixed First IGV button in str variants page
1. Cancer case activates on SNV variants (also STRs)
1. Fix bug which caused IGV.js to use hg19 reference files for hg38 data
1. Drop downs have correct size
1. SV variant links now take you to the SV variant page again
1. Cancer variant view has cleaner table data entries for "N/A" data
1. Fixed same case repetition in variant local observations
1. Allows for upload of OMIM-AUTO gene panel from static files without api-key
1. Allows for updating database tables after downloading definition files first.
1. Editable tumor purity and Tissue type for cancer cases

**New bugs since last time**:
1. Missing delivery report for recent cases (fixed in next release)
1. bug when adding a gene to existing panel (fixed in next release)

**Upcoming features in next release**
1. ClinVar SNVs track in IGV
1. Add SMA view with SMN Copy Number data

**MIP CG roadmap - 8.0 / 8.1 / 8.2 - and when you can expect to see the new features in Scout.**
*In production*
1. Turned off bcftools mpileup
1. Supply CRAM instead of BAM to Scout (70% storage reduction) 
1. Added SMNCopyNumberCaller to MIP for SMN calling with WGS data
1. Added vcf2cytosure blacklist file for grch37
1. Multiqc report in Scout
1. Adds upd for trios
1. Adds chromograph for chromosome visualization
1. Automated gender estimation for WGS for samples with unknown gender
1. Containerized entire workflow
1. Faster and more efficient processing (WGS 13-17 h)

**BALSAMIC CG roadmap: next release**
- cbioportal annotations for recurring variants
- _in silico_ tumor purity estimate
- MSI estimate for targeted sequencing
- Multiqc report
- CNV calls as SVs and plots

**Comment by moonso** [comment]
Should we invite cancer people or start up a separate meeting for them?

**Comment by hassanfa** [comment]
It would be great to include cancer scout + BALSAMIC roadmap as well.

**Comment by moonso** [comment]
Feel free to add to the agenda @hassanfa 😄

**Comment by sofievonlanthen** [comment]
4. Ability to see case numbers from other customers if same variant (without access)?

**Comment by northwestwitch** [comment]
1. Activity show variants in a better format (HGVS)
1. Cosmic track in IGV
1. Hotspots in IGV
