### ISSUE TITLE
Show Pinned status etc on cancer variants list 

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#1680]
Some obvious variant level events are missing from the cancer variants list. Thank you for pointing this out!

**Comment by northwestwitch** [comment]
Is nobody is working on this I could take it

**Comment by dnil** [comment]
Måns (with some help from me) are refactoring several of those views - and fixing issues as we go. I don't think we touch the cancer variants much, but the broa approach is somewhat based on the assumption you would not be working this week.. :wink:

**Comment by northwestwitch** [comment]
It's OK, I have time, but I understand if you don't want me creating conflicts on those files, I can pick something else!

**Comment by moonso** [comment]
@northwestwitch feel free as soon as #1668 is merged. It is ready

**Comment by northwestwitch** [comment]
Working on this now!
