### ISSUE TITLE
Display exon number and VAF % on the variant page

### ISSUE THREAD

**Issue by christacosta** [Clinical-Genomics/scout#1682]
For Cancer scout it would be useful to have the table tab called “Transcripts" somewhere more visible. 
Also the actual VAF % would be nice if shown on the variant page and not only the variant list.

**Comment by moonso** [comment]
@hassanfa are these present in the VCF atm? How and where should they be picked up?

**Comment by hassanfa** [comment]
Yes they are FORMAT/AF. We already show GT, AD, and some other values in variant page (table). Would be nice to show AF in that table also.

To pick them up, it is the same way it is being picked up for variantlist page.

**Comment by moonso** [comment]
Ok that sounds straight forward! It would be nice to have some updated example files from balsamic to include in the test files bundle under `scout/demo` @hassanfa . Could you create that with at most a couple of hundred variants

**Comment by hassanfa** [comment]
Sure thing! I'll add one, through PR right?

**Comment by keyvanelhami** [comment]
@moonso @hassanfa We got another request regarding VAF filtering in Scout from Emma Tham in ticket [855521](https://clinical-scilifelab.supportsystem.com/scp/tickets.php?id=32295#reply). Would be great if this issue could be prioritized.

**Comment by moonso** [comment]
Ok, you have to remind me if the example files that where requested are added?

**Comment by dnil** [comment]
If I read the initial request correctly, it's a bit of layout and perhaps moving one calculation to a different controller so can likely be done anyway - not that I would mind the update; I think we even have a separate issue for harmonising the cancer example files!

**Comment by hassanfa** [comment]
Yes they are there. A set of tumor only was added recently as well.

I think filtering based VAF might be easier, as we already show it on variant list view. So it is already stored, no?

**Comment by keyvanelhami** [comment]
From Emma Tham:

_I would say that to filter on VAF in N or T is of high priority! It would also be helpful to filter on chromosome._

**Comment by dnil** [comment]
Ah, cheers; that explains the urgency for what seemed a cosmetic issue. It is actually a different thing - a couple of filter boxes for the variants page and query infrastructure that can handle tumor / normal, but perhaps not too difficult. Let’s keep it here for now, but anyone that wants to deal with it separately, feel free!

**Comment by moonso** [comment]
I suggest that Emma Tham creates a Github account so she can participate in these discussions 😃 . Could you help her get going @dnil ?

**Comment by moonso** [comment]
And yes, I agree with @dnil . We are discussing two different topics in one issue

**Comment by hassanfa** [comment]
> Ah, cheers; that explains the urgency for what seemed a cosmetic issue. It is actually a different thing - a couple of filter boxes for the variants page and query infrastructure that can handle tumor / normal, but perhaps not too difficult. Let’s keep it here for now, but anyone that wants to deal with it separately, feel free!

Well i did say VAF filter, 😉 

I actually recommended Keyvan to write it here, as I thought it is similar. Now that I read the text body, I was wrong 😁 Let's move it to another issue. I'll create it.

**Comment by dnil** [comment]
This looks like an old completed issue: exon number is nowadays prominently displayed on the variant page summary, and VAF on the GT table. We have search for both tumor and normal VAF on the variantS page. Closing.
