### ISSUE TITLE
Show internal sample names on the case page, e.g. next to cgh file dl

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#1686]
Download of CGH files is currently unsafe, as file name mixups happen easily, and only internal names are present in the file and on file name. If corresponding sample names/pet names are present on the case page, they can be used for double check. Considered potentially a temporary feature until MIP / CG can write customer names in files for download.

**Comment by dnil** [comment]
(Also ping @henrikstranneheim regarding importance of getting customer sample names into and onto MIP-produced files.)

**Comment by northwestwitch** [comment]
@mikaell this one should also be fairly easy

**Comment by mikaell** [comment]
I'll take it.

**Comment by mikaell** [comment]
Requested feature is merged into scout. See #1982.
