### ISSUE TITLE
sharing case function not working

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#1687]
![bild](https://user-images.githubusercontent.com/12525201/73830213-91b74e80-4804-11ea-956b-2e61fe281bb4.png)

I wish to share a case bu tnothing happen. When i click on the "share case", the simbol rotate but nothing more. :(

**Comment by northwestwitch** [comment]
You just stumbled upon a new functionality! The preselected list of institutes to share cases with is empty. You can pre-populate using the institutes settings: https://scout.scilifelab.se/overview/edit/cust003, last select at the bottom of the page!

**Comment by 4WGH** [comment]
oh how lucky me !
thanks I will look at it

**Comment by 4WGH** [comment]
works!
wow :)

**Comment by northwestwitch** [comment]
We decided to have it this way so it's more secure, and users don't accidentally share cases with institutes that are not among their preselected list!

**Comment by northwestwitch** [comment]
> works!
> wow :)

Nice, closing this now then :)
