### ISSUE TITLE
ACMG classification not appearing in the causatives page, in some cases 

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#1690]
![bild](https://user-images.githubusercontent.com/12525201/73949202-63b43600-48fa-11ea-86c5-6aeea788e256.png)

these CPT2 variants in case 2007 are both classified with ACMG but only for one of them the classification appears.

This appen for several variants, I can see that if there is a "-" the classification has not been done but if the field after "ACMG:" is empty the classification is done but not appearing. See the difference in the pic below

![bild](https://user-images.githubusercontent.com/12525201/73949583-e50bc880-48fa-11ea-9c77-e1ecf3fbcd93.png)

**Comment by dnil** [comment]
Hm, yes, thank you for noticing! If I check a few of these it appears that the not appearing ones are cases where the "quick" classification button has been used, so no detailed data for why the classification was made, as with the Classify-page, is available. The two types of info are stored in slightly different ways in the database. Its not bad to differentiate, but we should clearly show also the "quick" classifications on the causatives page!

**Comment by dnil** [comment]
Thinking about it, it would seem we actually tried to show it as there is a difference with the "ACMG: -" and "ACMG: " ones. Let's call it a bug. 😄

**Comment by 4WGH** [comment]
The CPT2 variant has used the classification system..there are data there..... no "quick" classification

**Comment by dnil** [comment]
Ah, right - thank you! I found a few of those on the stage environment as well now. So some of both; possibly they are related back through a db change to display both types of classifications on the variants page. We'll check & fix!

**Comment by northwestwitch** [comment]
I've found something weird about the acmg code in causatives page. Looks like most of the causative variants have an acmg classification which is an object, but some of them have a just a number. This debugging code is on stage now. I don't know if this is causing this bug, but should be fixed!

![image](https://user-images.githubusercontent.com/28093618/74530679-eeb0b400-4f2a-11ea-9651-81fdb6e80851.png)

**Comment by northwestwitch** [comment]
Yes, that is the problem. I could replicate it by classifying as pathogenic the first 2 causative variants of cust000 on stage (ADAR gene). I'll fix it!

**Comment by dnil** [comment]
Nice! I would guess that is the old "quick" classification system from before reworking it? @moonso?

**Comment by moonso** [comment]
Probably yes

**Comment by northwestwitch** [comment]
Who wrote this very complicated structure I am struggling to wrap my mind around:

![image](https://user-images.githubusercontent.com/28093618/74533591-3981fa00-4f32-11ea-804d-67f0e6b5c3b6.png)


WHAT ABOUT 1 dictionary???? :D

**Comment by dnil** [comment]
I think @robinandeer or @moonso? But I can't quite remember..

**Comment by dnil** [comment]
That's what the "blame" button is for.. 😝 But beware, next time it is your code.. 😉

**Comment by northwestwitch** [comment]
I still haven't been able to pinpoint the error. I'm debugging using a "test" branch on stage and looks like that the variants missing the classification badge are lacking the `acmg_classification` key in the database, but somehow the classification pops up as a number in the causatives html page..
