### ISSUE TITLE
disease associated transcript

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#1692]
![bild](https://user-images.githubusercontent.com/12525201/73969041-f2d14600-491a-11ea-8da8-fa9ec12e43d5.png)
pic from case 19268

why does it look like this?

the gene name should appear only once.

**Comment by moonso** [comment]
It has been like this for long time. How would you like to have it? And why is it a problem like it is now?

**Comment by 4WGH** [comment]
Hi,
I would like to have it like this
CACNA1C: NM_XXXXXX, NM_xxxxxx, NM_xxxxxxxxx

to repeat the gene name is just redondant, and we like clean pages as much as possible :)

**Comment by northwestwitch** [comment]
This should be quite easy to fix!
