### ISSUE TITLE
HPO selection disappear

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#1693]
case 20012
There are 4 HPO terms in the "Added phenotype", I make a list selecting one term at the time
After I select the HPO term, i click on "HPO panel" to update the list, 
![bild](https://user-images.githubusercontent.com/12525201/74017644-e093ee00-4994-11ea-8231-6fcbd776b306.png)

A list is creater but I can not see any longer which term I had select, So I can not see for which term the list has been created.

![bild](https://user-images.githubusercontent.com/12525201/74017439-8eeb6380-4994-11ea-911a-75ebb6c56691.png)

**Comment by dnil** [comment]
Hi! If you hover over "Phenotypes" on the HPO panel you will see which terms were used to request it.

![Screenshot 2020-02-10 at 11 53 27](https://user-images.githubusercontent.com/758570/74144030-3cac7b80-4bfc-11ea-8e13-a93a42413a7d.png)
