### ISSUE TITLE
IGV Viewer button bug

### ISSUE THREAD

**Issue by 47KW** [Clinical-Genomics/scout#1698]
Hello
the first STR on the Clinical STR´s page has a non-functional IGV button.

**Comment by dnil** [comment]
Thanks.. 😸

**Comment by northwestwitch** [comment]
I'll try to fix this one!

**Comment by northwestwitch** [comment]
This error is very weird: the source code shows no difference in the HTML code for all buttons, but when you click on the first one you trigger a GET request instead of a POST one. And the view is not even supposed to accept a GET request now.

**Comment by dnil** [comment]
@northwestwitch: I think the problem is with the interaction with the navigation form.
The initial 
```
% block content_main %}
<form>
```
is still open (and defaults to method="GET" when you get to the first 
```
{% if case.bam_files %}
                <form role="form" action="{{ url_for('alignviewers.igv') }}" target="_blank" method="POST">
```
That is not very well defined, and likely to render a bit differently on different browsers. Just moving the content_main form to the footer macro should help..

**Comment by northwestwitch** [comment]
I've fixed it now with a solution found here: https://stackoverflow.com/questions/37908024/form-sends-get-instead-of-post

**Comment by northwestwitch** [comment]
> @northwestwitch: I think the problem is with the interaction with the navigation form.
> The initial
> 
> ```
> % block content_main %}
> <form>
> ```
> 
> is still open (and defaults to method="GET" when you get to the first
> 
> ```
> {% if case.bam_files %}
>                 <form role="form" action="{{ url_for('alignviewers.igv') }}" target="_blank" method="POST">
> ```
> 
> That is not very well defined, and likely to render a bit differently on different browsers. Just moving the content_main form to the footer macro should help..

Could be!

**Comment by dnil** [comment]
Ah, nice! If it works I'm all for it! I'm guessing the form name change and form method reiteration helps the browser decide which of the two possible (outer or inner) forms the action belongs to. Still think - until disproven - that moving the main form down to the footer would have the same effect.. 😄

**Comment by northwestwitch** [comment]
I can try!

**Comment by northwestwitch** [comment]
Why do we even have a form there I wonder..

**Comment by northwestwitch** [comment]
@dnil you were right, it works perfectly if you remove the outer form. I've just updated #1701

**Comment by dnil** [comment]
💛 Thank you! Just don't forget to put it back into the footer, or we will loose navigation on the page. Check with a trio page to see. 😊

**Comment by northwestwitch** [comment]
Done! 👍
