### ISSUE TITLE
Add path to qc_sample_info in database

### ISSUE THREAD

**Issue by moonso** [Clinical-Genomics/scout#170]
Add a field on case level

**Comment by robinandeer** [comment]
I don't think we need this for anything that Scout is involved in tho

**Comment by vwirta** [comment]
We want to create trending tools for qc data (duplicates, reads, qc etc) somehow. Storing path to qc might make this easier in the future

**Comment by henrikstranneheim** [comment]
It should at least be in moneypenny. 

Skickat från min iPhone

> 21 okt. 2015 kl. 18:59 skrev Valtteri Wirta <notifications@github.com>:
> 
> We want to create trending tools for qc data (duplicates, reads, qc etc) somehow. Storing path to qc might make this easier in the future
> 
> Sent from my iPhone
>

**Comment by moonso** [comment]
I agree @robinandeer we should parse this file in an earlier stage and add the relevant information to ```scout_config.ini``` like we have done before
