### ISSUE TITLE
discordant genotype call   vs reads ? 

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#171]
the Genotype call is 0/1 = heteroz. but the reads for the reference are 0. something odd?
![skarmklipp_151021](https://cloud.githubusercontent.com/assets/12525201/10631219/afc8059c-77dc-11e5-9909-eb158d632ff5.PNG)

**Comment by moonso** [comment]
@henrikstranneheim this is a GATK issue, what do you think?

**Comment by henrikstranneheim** [comment]
There seems to be both an indel and a snv called over the same position, but splitted into two lines in the vcf. Looks like individual 15014-1-6X carries both these alternative alleles, hence the 0/1, but no reference alleles reads. It is a bit odd that GATK splittet this into 2 lines (vt has not processed this sample). @moonso Do you have an idea?

Looks like something is there but you might have to Sanger sequence to figure out if it is indeed both an SNV and indel there.

![screen shot 2015-11-05 at 12 59 10](https://cloud.githubusercontent.com/assets/584738/10967828/996aad58-83bd-11e5-8005-f2965842f875.png)

**Comment by henrikstranneheim** [comment]
BTW: IGV from Scout would be lovely here....

**Comment by dnil** [comment]
:+1: 

My two satoshi on the pileup would be that there is no SNP? Seems all the support comes from the edge of reads, that had they been longer could have fit well in the repeat on the other side of the del? The slightly further extending ones with ,,g,,t,,,,, certainly do have support for this, and the remaining do not speak against it in any way.
