### ISSUE TITLE
Selecting a gene symbol while gene panel is pre-selected, still shows all genes.

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/scout#1710]
Probably a bug, but please confirm.

Title pretty much says it all, and here are the step to reproduce it (I tried this for non-cancer cases, but example below is from a cancer case):

Example case: https://scout.scilifelab.se/cust087/soundstud_rerun_20200113/cancer/variants?variant_type=clinical

1. Open the case, and select SNV/INDEL variants. The make sure TruSight Myeloid is preselected. Click on Filter.

![image](https://user-images.githubusercontent.com/1086877/74517796-0da34c00-4f13-11ea-93c3-0dac934ad751.png)

2. Open filters again, and select a gene that is in gene panel. Say ETV6. After filtering, it still seem to show all the genes.

![image](https://user-images.githubusercontent.com/1086877/74517857-2d3a7480-4f13-11ea-8a65-c3b6c9d78e2f.png)

**Comment by hassanfa** [comment]
@christacosta noticed a similar issue where https://scout.scilifelab.se/cust087/soundstud_rerun_20200113/f8fa94f1ec944f205941d9d3764d0f94?cancer=yes didn't show up when TruSight is preselected, and I think it might be related to this.

**Comment by dnil** [comment]
As far as I understand the description, this is the intended behaviour. The HGNC filter is in ADDITION to any and all selected panels. If you deselect the gene panel, things should work as expected. Please reopen if it does not - I might easily have misunderstood, but this is one of the very most common new user issues! We should probably consider putting it in a popup / tooltip.

:+1: Thanks for keeping a look out! Perhaps I can volunteer myself - or one of our more experienced RD scout users - to sit down and look through a case with some of your new users, and you if you wish! 😊 

![Screenshot 2020-02-14 at 13 48 55](https://user-images.githubusercontent.com/758570/74533041-ed828580-4f30-11ea-9ab3-1e7b0098beff.png)

**Comment by dnil** [comment]
> @christacosta noticed a similar issue where https://scout.scilifelab.se/cust087/soundstud_rerun_20200113/f8fa94f1ec944f205941d9d3764d0f94?cancer=yes didn't show up when TruSight is preselected, and I think it might be related to this.

Specifically ETV6 starts showing up on like page four of the variants list if you keep the default panel selected. Which is of course not easy to understand if you think you are filtering for only ETV6.
