### ISSUE TITLE
HGNC gene mapping in hg38

### ISSUE THREAD

**Issue by bjhall** [Clinical-Genomics/scout#1721]
When using hg38 cases in Scout we have noticed that some genes aren't mapped to the gene symbol. Like this:
![bild](https://user-images.githubusercontent.com/11991860/74819356-8eda5480-5300-11ea-8040-420880aa6907.png)

It seems it is using the hg19 data to do the ID<->symbol mapping, as it is the default of `hgnc_genes()`, `hgnc_gene()` and `hgnc_id()` functions. And in most places where these functions are used, no build version is given.

My naive solution to this would be to, in all places these functions are used, change for example:

```
hgnc_gene = store.hgnc_gene(xxx)
```
to 
```
genome_build = case_obj.get('genome_build', '37')
hgnc_gene = store.hgnc_gene(xxx, build=genome_build)
```

But I'm not confident this is the right solution. Any input appreciated!

**Comment by northwestwitch** [comment]
We are still using build 37 and (correct me if I'm wrong) never tried to upload any case with build=38 so your feedback is very useful and much appreciated! 
All over the code the default value for the build is 37, or at least should be.

For example this is the function that returns a gene :
![image](https://user-images.githubusercontent.com/28093618/74830057-999de500-5312-11ea-8dd9-9ad0a5584fbf.png)

The fix should be relatively easy, we just have to intercept at what level the right build is not passed along. The problem is that it could be in more than one function. You could try to understand where the error is if you want, otherwise one of us could take a look as soon as we have time.

This is definitely a bug so I'll label it as such! Thanks

**Comment by bjhall** [comment]
Yes the hgnc_gene (and related) functions are called all over, that's why I was thinking there could be a better solution. But I'll try to do the dirty work and fix them all! I'll get back to you with a pull request some time this week.

**Comment by northwestwitch** [comment]
I have some time ti look at this today. Let's see if I find some fix!

**Comment by northwestwitch** [comment]
- [ ] ./scout/parse/matchmaker.py:            gene_obj = store.hgnc_gene(hgnc_id)
- [x] ./scout/server/blueprints/variants/controllers.py:                hgnc_gene = store.hgnc_gene(gene_obj["hgnc_id"], build=genome_build)
- [ ] ./scout/server/blueprints/variants/controllers.py:                hgnc_gene = store.hgnc_gene(int(hgnc_symbol))
- [ ] ./scout/server/blueprints/variants/views.py:                hgnc_gene = store.hgnc_gene(int(hgnc_symbol))
- [ ] ./scout/server/blueprints/panels/controllers.py:        gene_obj = store.hgnc_gene(new_gene["hgnc_id"])
- [ ] ./scout/server/blueprints/panels/views.py:        gene_obj = store.hgnc_gene(hgnc_id)
- [ ] ./scout/server/blueprints/panels/views.py:    hgnc_gene = store.hgnc_gene(hgnc_id)
- [x] ./scout/server/blueprints/cases/controllers.py:                    hgnc_gene = store.hgnc_gene(gene_obj["hgnc_id"], build=genome_build)
- [ ] ./scout/server/blueprints/cases/views.py:                hgnc_gene = store.hgnc_gene(int(hgnc_symbol))
- [x] ./scout/server/blueprints/variant/utils.py:        hgnc_gene = store.hgnc_gene(hgnc_id, build=genome_build)
- [x] ./scout/server/blueprints/genes/controllers.py:        record = store.hgnc_gene(hgnc_id, build=build)
- [ ] ./scout/adapter/mongo/variant.py:            hgnc_gene = self.hgnc_gene(hgnc_id)
- [ ] ./scout/load/all.py:        gene_obj = adapter.hgnc_gene(hgnc_id)
- [ ] ./scout/commands/load/variants.py:            gene_obj = adapter.hgnc_gene(hgnc_id)
- [x] ./scout/commands/view/hgnc.py:        result = adapter.hgnc_gene(hgnc_id, build=build)
- [ ] ./scout/build/panel.py:    hgnc_gene = adapter.hgnc_gene(hgnc_id)

**Comment by bjhall** [comment]
Thanks @northwestwitch for looking at this! I started digging in it last week but was slightly overwhelmed by many places that needed to be fixed, and I didn't really understand what some of them were doing. And some of them were not in the context of a case (mainly panel stuff), so I wasn't sure hot to treat those either.

In addition to `hgnc_gene()`, the following functions also take an optional "build" parameter, which as far as I can tell appear to have been left out in a few places throughout the code. I'm not sure if they are relevant, but it's an observation I made...

```hgnc_genes()
hgnc_id()
all_genes()
hgncid_to_gene()
gene_by_alias()
genes_by_alias()
```

**Comment by northwestwitch** [comment]
Thanks, I'll look into these functions as well! It is a bit overwhelming, I agree! The easiest would be to modify in the code the default params from "37" to "38". The problem is that we can't since our pipeline is still using build 37. But fixing here and there it should work!
