### ISSUE TITLE
IGV view in Structural variant is not working properly

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#1724]
![bild](https://user-images.githubusercontent.com/12525201/74849938-a124b480-5339-11ea-91f6-533ea454517f.png)

WE used to have 3 IGV viewer:
1. entire variation
2. breakpoint1
3. breakpoint 2

now there in only one :(
and in not the one for the entire variation. could you check?
Can we have back the 3 opitions?

**Comment by dnil** [comment]
You have landed on the SNV page with an SV. Do you know how you got there? From the causative s page or from some overlapping box? If you let us know we can change it out! Thanks!

**Comment by 4WGH** [comment]
from the structural variant page. i've selected the variant to look at.

![bild](https://user-images.githubusercontent.com/12525201/74867059-4a78a400-5354-11ea-9391-d02955f2b974.png)

**Comment by dnil** [comment]
Thanks.. Yep, its new in 4.12; some unexpected fallout from a unification of pinning mechanics (#1699). We'll fix it along with the other hotfixes to 4.12 tomorrow! Sorry!
