### ISSUE TITLE
Trying to load all variants for a gene removes all clinical variants

### ISSUE THREAD

**Issue by moahaegglund** [Clinical-Genomics/scout#1729]
When running the command to load all variants for a gene (`scout load region`) an error occurs and all clinical variants are removed.

The command `scout load region --case-id hotlemur --hgnc-id 8582` gives the following error:
![image](https://user-images.githubusercontent.com/19236050/74921613-5143fd00-53ce-11ea-8696-67d487225e63.png)

I've tried this command on three cases from cust000 with two different genes and get the same error.

**Comment by dnil** [comment]
Ok, its in scout.load.all.load_region - or in housekeeper / MIP depending on how you view it. It won't load region without an index. So either make an index - or disable STRs for the region upload.

**Comment by northwestwitch** [comment]
Ping @henrikstranneheim

**Comment by henrikstranneheim** [comment]
MIP produces the index, but cg does not pick it up and put it in HK

**Comment by henrikstranneheim** [comment]
I will make an issue

**Comment by henrikstranneheim** [comment]
https://github.com/Clinical-Genomics/cg/issues/561
