### ISSUE TITLE
Local observations displays only the current family

### ISSUE THREAD

**Issue by ielvers** [Clinical-Genomics/scout#1730]
Local observations display only the family I'm looking in, and in one case the family name appears multiple times.

Example 1: the variant is said to have been seen 45 times before and the family I'm looking in is listed 16 times. This is a re-run so I'd expect to see my family once.
case 19173, variant in SLC7A2 with rank 45

Example 2: Helene looked at a variant yesterday with 4 local observations and different family names were listed. Today in the same variant only the ID of the family she's looking at is displayed (but it still says 4 local observations).

![image](https://user-images.githubusercontent.com/57791644/74923800-b4835e80-53d1-11ea-91f8-d2c83deec3e7.png)

**Comment by northwestwitch** [comment]
Confirmed, this is a bug
