### ISSUE TITLE
Long list of local observations within the same sample/analysis

### ISSUE THREAD

**Issue by christacosta** [Clinical-Genomics/scout#1731]
After the release (v4.12) I get a very long list of local observations of some variants but all are in the same sample/analysis (cancer scout). See e.g. https://scout.scilifelab.se/cust087/humblevervet_rerun_20200113/1b4a9ac851fc1b7ac96fc5b55ffba15a?cancer=yes

**Comment by northwestwitch** [comment]
Thanks @christacosta , we are aware of the problem and we'll try to fix the issue ASAP. There's also another issue about this (#1730) so I'm closing this one.
