### ISSUE TITLE
We can't open some of our families

### ISSUE THREAD

**Issue by ielvers** [Clinical-Genomics/scout#1733]
We can't open a few of our families; we get this message:
Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

So far we've gotten this for families
96
144
19255
20025

**Comment by dnil** [comment]
Thanks; its a known issue with cases with pinned variants for a particular set of genes, that is fixed in the 4.12.1 bug fix release candidate (#1727). Release e.t.a later today! Sorry for the inconvenience!

**Comment by dnil** [comment]
I'm going to close this issue for now just to be able to keep track, but please feel free to reopen if the issue resurfaces!
