### ISSUE TITLE
Missed freq for insertions

### ISSUE THREAD

**Issue by 47KW** [Clinical-Genomics/scout#1743]
Daniel,
https://scout.scilifelab.se/cust002/F0032963/sv/variants

https://scout.scilifelab.se/cust002/F0026375/sv/variants

PYGM 75 nt

**Comment by dnil** [comment]
Thank you! I think this is predominantly a Loqus-issue @moonso and @J35P312: it would appear Loqus has an issue with recognising recurring single bp variants (INS here, but perhaps BND as well?).

There was a similar issue with SVDB a while back, so if @henrikstranneheim or someone else has a lot of time, rerunning that static svdb dump with the latest version would be fruitful.

**Comment by moonso** [comment]
Thanks @47KW , what would we do without you 😺 . We'll fix that
