### ISSUE TITLE
Add reference build to panel pages

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#1753]
It should be possible to create gene panels in genome builds other than 37. Everything now in those pages point to genome build 37. I'm thinking about genes mapping differently among builds, genes which are missing in one build but present in another, "gene panels" consisting of chromosome coordinates instead of genes.

**Comment by moonso** [comment]
Hi! I don't really understand. Gene panels only refers to hgnc ids and they are independent of genome build. So why would we like to have a genome build on panels? If the case are analysed in a build we can use that for fetching information about coordinates etc. It should be possible for cases with different genome builds to refer to the same panel. Or am I missing something?

**Comment by northwestwitch** [comment]
Yes, cases with different genome builds should be able to refer to the same panel, where genes have the same hgnc_id regardless of the build. What I mean is that there are many functions that connect cases and variants to panels and all these functions default to build 37 and sometimes don't pass build as a parameter to other functiosn. We need to check that whenever we use panel info to map genes or intervals everything will be rendered in the right genome build.
