### ISSUE TITLE
Display more informative flash messages when a panel creation from file fails

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#1755]
A user was trying to create a new gene panel but couldn't (displayed message was  a generic "something went wrong in creating the panel"). With @moahaegglund we found out that it was because two genes in the panel file are missing in scout database:
- HLA-DRB3(4951)
- HLA-DRB4(4952)

It would be useful that instead of getting the generic error message the user could know what went wrong in the upload. For instance the scout log displays clearly: 
`WARNING hgnc_id 4951 is not in the gene database!`
`WARNING hgnc_id 4952 is not in the gene database!`

**Question, why are not these 2 genes in our database?**

**Comment by dnil** [comment]
Lets see, those two are on alternative loci so not on the regular chr6 build config, right? chr6_cox_hap2 and chr6_mcf_hap5 on hg19. And I wouldn't want to guess what graph they are on in later builds.. 😉

**Comment by dnil** [comment]
@moonso might know why they are not loaded to Scout; I don't particularly see a reason not to? But from a CG Solna perspective I am not so sure we actually map them well: I have a feeling MIP may stop at the main contigs of the genome build @henrikstranneheim?

**Comment by dnil** [comment]
Perhaps this?

```
    try:
        chromosome = gene_info['chromosome']
    except KeyError as err:
        raise KeyError("Gene has to have a chromosome")
```

**Comment by dnil** [comment]
And at the root is this filter when loading genes, transcripts etc to a set of predefined contig names CHROMOSOMES in constants

```
ef fetch_ensembl_genes(build=None):
    """Fetch the ensembl genes
    
    Args:
        build(str): ['37', '38']
    
    Returns:
        result(iterable): Ensembl formated gene lines
    """
    LOG.info("Fetching ensembl genes")

    attributes = [
        "chromosome_name",
        "start_position",
        "end_position",
        "ensembl_gene_id",
        "hgnc_symbol",
        "hgnc_id",
    ]

    filters = {"chromosome_name": CHROMOSOMES}

    return fetch_ensembl_biomart(attributes, filters, build)
```

**Comment by dnil** [comment]
As the gene is not in the db being on 6, but rather on GL000255, it will not be fetched, loaded, parsed or searchable in the scout db...

**Comment by moonso** [comment]
So do you need me to answer or did you find out. It does not necessarily mean that something went during the upload. It is probably because the genes are not fulfilling what we have specified

**Comment by dnil** [comment]
We understand the problem well, and should try to make the errors on panel load known to non-cli users.

As for the genes in question, and more general problem of genes not on the main assembly, the clinic in question should perhaps press the issue on how important it is that we try to address the underlying global problems, to enable load and processing of genes and variants on alternative contigs?

**Comment by henrikstranneheim** [comment]
MIP will use alternative contigs in the mapping, but only use primary contigs downstream of this. So any variants in the alternative contigs will not make it to Scout
