### ISSUE TITLE
OMIM-related tests fail on master branch

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#1766]
I don't know if it's me or something weird is going on o master branch. 
The test:
tests/commands/update/test_update_hpo_cmd fails and it's also duplicated in that fine ..!

**Comment by dnil** [comment]
Weird?! TravisCI has master passing fairly recently: do you have that locally only so far?

**Comment by northwestwitch** [comment]
I've removed the duplicated test on #1761 and now that test works (probably not related) but now I have another failing that branch. OMIM stuff related

**Comment by northwestwitch** [comment]
OMIM is down perhaps!

**Comment by northwestwitch** [comment]
At least the downloads

**Comment by dnil** [comment]
To summarise the discussion: yes, but the test only needs doing once. And should like all other external tests go in a separate not-so-mandatory lane. We leve the latter for a rainy day.

**Comment by northwestwitch** [comment]
Or a sunny day, since it's raining much more than it's sunny but we never do it when it rains

**Comment by dnil** [comment]
I would have said snowy, since it never snows anymore, but then..

**Comment by northwestwitch** [comment]
Also related update commands don't work. Might be related with this: http://compbio.charite.de/jenkins/job/hpo.annotations/1270/
