### ISSUE TITLE
Update chromograph draw with current MIP chromograph settings

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#1776]
- ideogram
- coverage (from TIDDIT)
- UPD_sites
- UPD_regions

**Comment by dnil** [comment]
This is now in sync and can be closed, right @mikaell?

**Comment by mikaell** [comment]
We're only showing UPD Regions at the moment. The UPD Sites files are too chaotic to make any sense of. Though we can add them later if the need arrises. 

Closing this.

(Add new issue for UPD Sites if it should be added).
