### ISSUE TITLE
CLin Var link missing

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#1777]
https://scout.scilifelab.se/cust003/14027/a2aefd060f80b751b3d227e587ffb00f

For several variant the CLinVar info in not appearing. 
Se ex. 
Thought the gnomAD link I can see that the variant is in ClinVar.

I've check some more cases and this seam to be a general issue

**Comment by northwestwitch** [comment]
Yes it's on Clinvar, now you see it also on the clinVar track on IGV viewer. I'll check why the link doesn't show!

**Comment by northwestwitch** [comment]
Where is that the clinVar info should show @4WGH ?

**Comment by 4WGH** [comment]
thanks! we miss it very  much from the variant page

Cool to see it also in the IGV 🙂
________________________________
Från: Chiara Rasi <notifications@github.com>
Skickat: den 6 mars 2020 10:15
Till: Clinical-Genomics/scout <scout@noreply.github.com>
Kopia: Michela Barbaro <michela.barbaro@sll.se>; Author <author@noreply.github.com>
Ämne: Re: [Clinical-Genomics/scout] CLin Var link missing (#1777)


Yes it's on Clinvar, now you see it also on the clinVar track on IGV viewer. I'll check why the link doesn't show!

**Comment by 4WGH** [comment]
![bild](https://user-images.githubusercontent.com/12525201/76070584-137dd180-5f95-11ea-863b-7be5a2ddb557.png)
 it used to be somewhere here.

**Comment by northwestwitch** [comment]
The clinvar info was here: https://github.com/Clinical-Genomics/scout/blob/c608dd86ac19e5423e56dbb33ff8dfaefe2b208d/scout/server/blueprints/variants/templates/variants/variant.html#L398

**Comment by dnil** [comment]
Looks like a MIP/Scout communication issue to me? No CLNSIG, CLNVID, CLNACC or CLNREVSTAT in there, but some conspiciuos looking CSQ-fields by the names of CLINVAR|CLINVAR_CLNSIG|CLINVAR_CLNVID|CLINVAR_CLNREVSTAT? Are there news in the format for MIP8 @henrikstranneheim @jemten?
```
keentroll_gatkcomb_rhocall_vt_af_frqf_cadd_vep_parsed_ranked.selected.vcf.gz

7      103194254       rs149837553     A       G       1221.10 PASS    AC=2;AF=0.333;AN=6;Annotation=RELN;BaseQRankSum=-0.191;CADD=24.1;CSQ=G|missense_variant|MODERATE|RELN|ENSG00000189056|Transcript|ENST00000343529|protein_coding|39/64||ENST00000343529.5:c.5822T>C|ENSP00000345694.5:p.Val1941Ala|5982|5822|1941|V/A|gTt/gCt|||-1||HGNC|9957||||CCDS34722.1|ENSP00000345694|P78509|Q75MM8|UPI0000160333||Ensembl|A|A||deleterious|benign|hmmpanther:PTHR11841||||||0.175|6.07|6.07|0.32053|0.994000|8.947000|1.00|6.538|10.425|5.526|6.534|-3.539|0.336|-3.203|-3.203|-5.122|-1.830|-3.897|-6.952||||281632|Uncertain_significance|281632|criteria_provided&_multiple_submitters&_no_conflicts|,G|missense_variant|MODERATE|RELN|ENSG00000189056|Transcript|ENST00000424685|protein_coding|39/65||ENST00000424685.2:c.5822T>C|ENSP00000388446.2:p.Val1941Ala|5982|5822|1941|V/A|gTt/gCt|||-1||HGNC|9957|||||ENSP00000388446||Q75MM8&J3KQ66|UPI0001AE70CE||Ensembl|A|A||deleterious|possibly_damaging|hmmpanther:PTHR11841||||||0.175|6.07|6.07|0.32053|0.994000|8.947000|1.00|6.538|10.425|5.526|6.534|-3.539|0.336|-3.203|-3.203|-5.122|-1.830|-3.897|-6.952||||281632|Uncertain_significance|281632|criteria_provided&_multiple_submitters&_no_conflicts|,G|missense_variant|MODERATE|RELN|ENSG00000189056|Transcript|ENST00000428762|protein_coding|39/65||ENST00000428762.1:c.5822T>C|ENSP00000392423.1:p.Val1941Ala|5982|5822|1941|V/A|gTt/gCt|||-1||HGNC|9957|YES|||CCDS47680.1|ENSP00000392423|P78509|Q75MM8|UPI00001678BC||Ensembl|A|A||deleterious|benign|hmmpanther:PTHR11841||||||0.175|6.07|6.07|0.32053|0.994000|8.947000|1.00|6.538|10.425|5.526|6.534|-3.539|0.336|-3.203|-3.203|-5.122|-1.830|-3.897|-6.952||||281632|Uncertain_significance|281632|criteria_provided&_multiple_submitters&_no_conflicts|,G|missense_variant|MODERATE|RELN|5649|Transcript|NM_005045.3|protein_coding|39/65||NM_005045.3:c.5822T>C|NP_005036.2:p.Val1941Ala|5982|5822|1941|V/A|gTt/gCt|||-1||EntrezGene|9957|YES||||NP_005036.2|||||RefSeq|A|A||deleterious|benign|||||||0.175|6.07|6.07|0.32053|0.994000|8.947000|1.00|6.538|10.425|5.526|6.534|-3.539|0.336|-3.203|-3.203|-5.122|-1.830|-3.897|-6.952||||281632|Uncertain_significance|281632|criteria_provided&_multiple_submitters&_no_conflicts|,G|missense_variant|MODERATE|RELN|5649|Transcript|NM_173054.2|protein_coding|39/64||NM_173054.2:c.5822T>C|NP_774959.1:p.Val1941Ala|5982|5822|1941|V/A|gTt/gCt|||-1||EntrezGene|9957|||||NP_774959.1|||||RefSeq|A|A||deleterious|benign|||||||0.175|6.07|6.07|0.32053|0.994000|8.947000|1.00|6.538|10.425|5.526|6.534|-3.539|0.336|-3.203|-3.203|-5.122|-1.830|-3.897|-6.952||||281632|Uncertain_significance|281632|criteria_provided&_multiple_submitters&_no_conflicts|;Compounds=keentroll:7_103317537_G_T>23|7_103617757_C_CA>8|7_103424513_C_T>9|7_103456977_A_AACACACACACACAC>24|7_103317546_G_C>24|7_103560513_A_C>4|7_103565432_TACACATACAC_T>10|7_103520883_C_T>11|7_103132200_T_C>9|7_103465074_AGTGTGTGT_A>8|7_103508295_A_AT>11|7_103627810_G_A>9|7_103560517_A_G>3|7_103560519_AC_A>4|7_103148602_A_G>9|7_103479750_C_CTTTTT>8|7_103560515_A_G>3|7_103560532_ATGTG_A>6|7_103129650_G_GGTGTGTGTGTGT>8|7_103502856_T_TTCTA>9|7_103478655_CAAAAA_C>8|7_103512743_A_C>9|7_103560530_G_A>4|7_103357927_C_CA>9|7_103271733_C_CTT>16|7_103333797_T_TG>9|7_103566546_CT_C>8|7_103580800_C_T>9|7_103132297_TCTCTCTCACACACACACACA_T>8|7_103466766_AATGTGTGTGTGTGTGTGTGTGTGT_A>9|7_103466268_G_A>9|7_103560525_TTG_T>4|7_103531571_C_T>9|7_103511405_T_G>9|7_103123991_T_C>9|7_103396065_T_A>9|7_103332129_G_A>9|7_103132355_G_T>9|7_103317547_C_A>24|7_103500085_T_A>9|7_103547861_GGAA_G>11|7_103232073_T_C>24|7_103360620_T_TTG>8|7_103484361_C_G>9|7_103550193_T_TATATATTAAATATATATATTTAATATATATAA>22|7_103560516_T_TGGTCGCC>4|7_103615962_GTATTTATTTATT_G>23|7_103374946_G_C>11|7_103128672_C_G>9|7_103404667_T_G>9;DB;DP=108;ExcessHet=3.0103;FS=0;GNOMADAF=0.00050942;GNOMADAF_popmax=0.0007776;GeneticModels=keentroll:AR_comp|AR_comp_dn;MLEAC=2;MLEAF=0.333;MQ=60;MQRankSum=0;ModelScore=keentroll:61;Obs=3;QD=15.66;RankResult=2|2|0|1|5|3|3|3|1|1;RankScore=keentroll:15;ReadPosRankSum=0.054;SOR=0.652;SPIDEX=0.399;SWEGENAAC_Hemi=0;SWEGENAAC_Het=2;SWEGENAAC_Hom=0;SWEGENAF=0.001;VQSLOD=21.72;culprit=MQ;most_severe_consequence=9957:G|missense_variant GT:AD:DP:GQ:PL  0/1:21,19:40:99:640,0,810       0/1:22,16:38:99:592,0,860       0/0:29,0:29:61:0,61,1182
```

**Comment by northwestwitch** [comment]
Could be that, but the actual HTML code on the variant page is also gone

**Comment by northwestwitch** [comment]
Or not! Wait

**Comment by dnil** [comment]
😸 Huh? No?
<img width="712" alt="Screenshot 2020-03-06 at 11 44 36" src="https://user-images.githubusercontent.com/758570/76076873-fb5f7f80-5f9f-11ea-9318-262d5ba8f91b.png">

**Comment by northwestwitch** [comment]
Yes, it was there all the time. Must be a parsing problem

**Comment by dnil** [comment]
Still, I'm not so sure I'm right either: the vep97 demo example also has those CLINVAR_CLNSIG CSQ:s.

**Comment by dnil** [comment]
Demo case is still on the INFO CLNSIG though..

**Comment by dnil** [comment]
If the MIP folks confirm this is the way they annotate CLINVAR now, we could presumably just add those csq keys to the clinvar parsing?

**Comment by northwestwitch** [comment]
The VCF and the parsing class do use different keys, yes:

![image](https://user-images.githubusercontent.com/28093618/76077295-bbe56300-5fa0-11ea-94b6-c04b69fb8f5f.png)

**Comment by northwestwitch** [comment]
But the analyses already in scout are missing the info now

**Comment by dnil** [comment]
Ok @4WGH - thanks a bunch for the report! Golden! 👍🏻
It would seem a recent change to how ClinVar entries are represented from MIP was not compatible with Scout. We will wait for confirmation from @henrikstranneheim, investigate exactly how far back this goes and how far reaching the consequences are. Hopefully we will have some news on this in the afternoon!

**Comment by jemten** [comment]
Hi there,
In MIP8 we annotate clinvar variants using vep. vep required that we added an extra identifier to indicate the source. That's why CLINVAR_.... It's unfortunate that the information didn't reach the scout team :(

**Comment by northwestwitch** [comment]
I'm opening a PR with the fix now, but might have to re-run cases!
