### ISSUE TITLE
Varsome link for transcripts

### ISSUE THREAD

**Issue by ninanorgren** [Clinical-Genomics/scout#1778]
A lot of the geneticist at our site uses Varsome for looking at specific transcripts and access their rules and filtering. Would it be possible to add a button that links to varsome for a specific transcript? I can help with the implementation, but I'm not sure where the best place to actually place the button would be. Any idea? Transcript overview, on the Transcript tabs over the External links?

**Comment by northwestwitch** [comment]
That sounds as the most appropriate place to me, why not! You could either create a new "links" column or just add a small "v" button in a pre-existent cell!

**Comment by dnil** [comment]
Solved by #1805!

**Comment by dnil** [comment]
Or, well #1862, but anyway.. 😅
