### ISSUE TITLE
ClinVar track in IGV displays pathogenic variant for variant with conflicting interpretation

### ISSUE THREAD

**Issue by sofievonlanthen** [Clinical-Genomics/scout#1781]
We have a variant that is displayed in red colour (ie pathogenic) in the new ClinVar track in IGV. However when looking in ClinVar the variant has conflicting interpretation, but none of the reports says pathogenic or likely pathogenic, all either benign or unknown significance. The ClinVar interpretation is therefore "Conflicting interpretations of pathogenicity". Is this =~pathogen causing the variant to be red in the ClinVar track? 

The ClinVar ID: 133603

/Sofie

**Comment by dnil** [comment]
Interesting: we will have a closer look! We are just using the tracks from UCSC directly, so the color coding in e.g. https://genome-euro.ucsc.edu/cgi-bin/hgTrackUi?hgsid=234580891_McYEIAKIOWxb5VVqXyauuOUjryQ7&c=chr1&g=clinvar should normally apply.

Regarding clinvar, be advised of #1777. We will send an information letter with details about it, but the direct clinvar annotations may be missing for cases from the past two weeks.

**Comment by sofievonlanthen** [comment]
Thanks. I checked the colour coding at USCS, and it looks the same in the browser, but it makes it confusing if conflicting evidence results in pathogenic colouring, unless some of the reports says pathogenic.  

I noticed as well the missing ClinVar link, was just about to write an issue when I saw the #1777 ticket. 
We noticed when a matching case had the ClinVar link but not the current case.

**Comment by dnil** [comment]
I've gone through that as well, and my best guess is they play it safe by giving all conflicting "red" (P/LP) status. I would have preferred those to be gray or even better a fourth color. If you have the time and energy for it, I would advise to talk to UCSC and possibly ClinVar about it. I suppose we could re-parse their track to update the color for "conflicts", but it would be better for everyone if this is changed at the source!

<img width="624" alt="Screenshot 2020-03-06 at 17 27 03" src="https://user-images.githubusercontent.com/758570/76102187-e569b300-5fcf-11ea-8d5b-60de30a23fba.png">

<img width="910" alt="Screenshot 2020-03-06 at 17 26 52" src="https://user-images.githubusercontent.com/758570/76102161-dbe04b00-5fcf-11ea-959b-056629766141.png">

**Comment by northwestwitch** [comment]
Conflicting interpretations perhaps entails that somebody reported the variant as pathogenic so it gets the red color for that reason. Color code, according the UCSC page:
 - Red for pathogenic
-  dark grey for uncertain significance or not provided 
- green for benign

Shall I close the Issue?

**Comment by sofievonlanthen** [comment]
You can close it. The question was why cases that only have conflicting pathogenicity end up red. In the case I was looking at, I couldn't find any reports of pathogenic/likely pathogenic. But I guess I need to talk to UCSC or ClinVar.

**Comment by dnil** [comment]
That'd be great! Let us know if you want us to chime in somewhere.. Cheers, and thanks for noticing!

**Comment by dnil** [comment]
Good news! @sofievonlanthen convinced UCSC to change their ClinVar track color scheme. Here is a test version. Lets try it on stage! 😄 Also, some new cool features underway there for filtering etc - will pass on email. Will play very well with @northwestwitch new version of general track display!

https://genome-test.gi.ucsc.edu/cgi-bin/hgTracks?db=hg19&lastVirtModeType=default&lastVirtModeExtraState=&virtModeType=default&virtMode=0&nonVirtPosition=&position=chr11%3A108121772%2D108121801&hgsid=395008872_0xzUqEGyXk7oE0sMepm0iEWMswwV

<img width="934" alt="Screenshot 2020-03-11 at 17 33 01" src="https://user-images.githubusercontent.com/758570/76440663-75d43900-63be-11ea-945f-3b2f698c82df.png">

**Comment by northwestwitch** [comment]
That's great @sofievonlanthen! 😊

**Comment by dnil** [comment]
And this is another one solved externally! Well done!
