### ISSUE TITLE
Opening IGV on a repeat region sometimes causes the view to crash or stall

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#1783]
Sometimes (could be related when read mate is on another chromosome?) when clicking on a "view mate in split screen" causes the views to crash.

Possibly a javascript error. Make sure to check what the browser page "inspect" options says about it

**Comment by dnil** [comment]
Any connection to what chr the mate is on?

**Comment by northwestwitch** [comment]
> Any connection to what chr the mate is on?

Chr2? It's not even a weird one!

**Comment by dnil** [comment]
Is it reproducible, transient or intermittent?

**Comment by northwestwitch** [comment]
Reproducible I think. 
Case example: cust010, case A1539 igv interval chr12:110021000-110021100.

**Comment by dnil** [comment]
So I wasn't able to crash the browser, but I did note that many reads there go to mates in loooong polyG homopolymer stretches. It is perhaps not so strange to find an issue with those. If you can pinpoint the exact reads that fail, maybe we can see if the issue is with the split screen, the other region or the tags on that particular read?

**Comment by northwestwitch** [comment]
No you are right, I didn't express myself well. The browser doesn't crash but freezes while trying to load the reads. Is this what you saw?

**Comment by dnil** [comment]
Yep; moving around in deep ambiguous repeats is not the best sport of the regular IGV either.  Possibly we could do something with `samplingDepth`and `samplingWindowSize`?

**Comment by dnil** [comment]
If it is a bug, I'd lean towards it being in igv.js? We could mitigate however, but relabelling for now.
