### ISSUE TITLE
New filtering list for research variants only

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/scout#179]
Add MitoCarta gene list as a filtering option for research variants only. 

FYI: MitoCarta gene list will be submitted by CMMS to Clinical genomics.

**Comment by vwirta** [comment]
Provide at least initially as diagnostic gene list.

**Comment by robinandeer** [comment]
Should the clinical panels be available for the research variants?

Will the research panels be annotated in MIP?

**Comment by henrikstranneheim** [comment]
> Should the clinical panels be available for the research variants?
> 
I don’t think so as they have already been vettet in the clinical setting.

> Will the research panels be annotated in MIP?
> 

As far as I know it is only as a filtering step in Scout i.e filter variants on HGNC_symbol that for instance Mitocarta will be used and no other annotation. Since Scout will be aware of all gene lists/panels my initial thought would be that Scout could fetch these HGNC_symbol and include them in the filtering, but that is perhaps not how you have built the gene list filtering today. 

If Kenny adds a column to the cost-000-Research.txt as “Research_db_gene_annotation” then mip can relay that in the research variants just like the clinical variants which have “Clinical_db_gene_annotation"
If you do not think it is easy to add to Scout straight away.


/H
> On 06 Nov 2015, at 11:29, Robin Andeer <notifications@github.com> wrote:
> 
> Should the clinical panels be available for the research variants?
> 
> Will the research panels be annotated in MIP?
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/Clinical-Genomics/scout/issues/179#issuecomment-154373652>.
> 

Henrik Stranneheim Ph.D.
Department of Molecular Medicine and Surgery
Karolinska Institute
Science for Life Laboratory


E-mail: henrik.stranneheim@scilifelab.se <mailto:henstr18@kth.se>
Visiting address: 
Science for Life Laboratory - SciLifeLab
Gamma building
Tomtebodavägen 23A
Delivery address:
Science for Life Laboratory - SciLifeLab
Gamma building
Tomtebodavägen 23B
171 65 Solna
