### ISSUE TITLE
Coverage report emtpy for cancer cases

### ISSUE THREAD

**Issue by christacosta** [Clinical-Genomics/scout#1790]
Is this already known or somehow related to panel sequencing or would it be possible to get an actual coverage report for each case?

**Comment by hassanfa** [comment]
This is done through another software to get the actual coverage (https://github.com/Clinical-Genomics/chanjo).

@moonso Do you know how one can send the coverage report for panel cases from bioinfo workflow to Scout via Chanjo?

**Comment by dnil** [comment]
Do you already have a coverage report from Balsamic that you would like to show? If so it would be rather straightforward to upload that to each case. Or would you rather integrate with Change anyway?

**Comment by hassanfa** [comment]
1. We have coverage, normalized coverage, and per exon coverage plots in form of PDF:
![image](https://user-images.githubusercontent.com/1086877/76414438-989f2700-6397-11ea-8ce3-d59328bbfd21.png)

2. In MultiQC report for each case, there is also a coverage plot.
![image](https://user-images.githubusercontent.com/1086877/76414576-e025b300-6397-11ea-8161-2d116cf80f88.png)

3. I can create a table of coverage for 100X to max_coverageX with reasonable steps.

**Comment by dnil** [comment]
Thanks! These are nice for QC and long term trends, and in general enough to tell that the sequencing of one case worked! We could work with any of them - or instruct users to use multiQC.

You will very soon get requests for coverage of individual genes and transcripts. Then Chanjo will be useful. In principle this is not so difficult.

Would it be ok to have the panels in the same chanjo db as the genomes/exomes? For the single case, all is fine, but aggregate numbers would not make sense. @moonso?

**Comment by dnil** [comment]
This is partly adressed by #2331; closing it for now, but will be revisited with future chanjo / cg updates!
