### ISSUE TITLE
Transcript variants, canonical transcripts and annotations don't match

### ISSUE THREAD

**Issue by christacosta** [Clinical-Genomics/scout#1791]
I don't know if this is a problem only for a few specific variants or genes but I have as an example this variant in the gene CUX1: 
https://scout.scilifelab.se/cust087/topsmarlin_rerun_20200113/2a2b066326a64304739835ffaef7ceb1

In the table "transcript overview" there are several transcripts listed with cDNA annotations. But the annotations and marking of canonical transcripts are not the same as in the transcript table further down. 
For my example variant, this means that I find one annotation in the variant list (c.3248C>T) but another one on the case start page under pinned variants (c.3545C>T). 
Is this something that can be harmonised somehow? Are different annotations chosen for the different pages?
In this case, there is even a discrepancy between the cDNA coordinates when using the same transcript, depending on in which table I look (overview: XM_005250150 c. c.3248C>T; further down XM_005250150.1 c.3545C>T).

**Comment by northwestwitch** [comment]
I think our scout transcripts expert @moonso would be the best candidate to answer this question.

**Comment by dnil** [comment]
There are two possible answers to this. One partial answer is that the ENSEMBL mapping between ENST transcripts and RefSeq is not 100% perfect.
Notice how the c.3248C>T ENST transcript appears to represent multiple RefSeq ones:
<img width="713" alt="Screenshot 2020-03-11 at 18 18 58" src="https://user-images.githubusercontent.com/758570/76444961-fd24ab00-63c4-11ea-8036-d75eb1d6a8ec.png">

In this case, we for reasons I don't quite understand (Balsamic?) also have nice, versioned refseq transcripts loaded. Here we see a different story, with XM_005250150.1 c.3545C>T. 

To make things more complicated though, note that the above ENST mapped refseq transcript is unversioned. That one corresponds to a modern version of the transcript, which is now at XM_005250150.3. 

My tentative verdict is that we should not be loading that XM.1 version, unless there is a very specific reason to keep it? What do you think @hassanfa and @moonso?

**Comment by hassanfa** [comment]
Daniel is right. First one that we see for HGVSc: c.3248C>T is for ENSEMBL annotation. The second HGVSc c.3248C>T is for XM_005250150. That's where there is also a version for this transcript: XM_005250150.1. Refseq transcript versions change quite often (once a year or so), specially in this case that it is XM_ which is a computationally predicted transcript (https://www.ncbi.nlm.nih.gov/books/NBK21091/table/ch18.T.refseq_accession_numbers_and_mole/?report=objectonly)

Maybe we should remove predicted transcript completely, and focus on curated ones only.

Anyway, canonical (those with **C** ) curated transcripts are the ones you should look into.

**Comment by christacosta** [comment]
Thanks for the explanations! I think it would help to have less transcripts in the different tables. Usually it's the canonical or hgnc primary we look at (they are not always the same though in the different tables?). 
But in the example above, the cDNA coordinate of the pinned variant in the case start page was taken from this XM_005250150.1 transcript. Since I couldn't find the same annotation in the transcript table, I was looking into more details in the table further down.

**Comment by hassanfa** [comment]
Alright, I looked into this a bit more. XM_005250150 is marked as the only canonical transcript for CUX1 in VEP annotation version that we're using. That might be the reason for this. 

http://grch37.ensembl.org/Homo_sapiens/Tools/VEP/Results?tl=1kovFKoIQKmy3zHs-12993

**Comment by hassanfa** [comment]
Above link doesn't have canonical, this one does: http://grch37.ensembl.org/Homo_sapiens/Tools/VEP/Results?tl=VSMRJL2qFdDrrSbO-13018

So it is not just Scout or Balsamic, it is the way VEP is annotating XM_...150 as canonical. 
![image](https://user-images.githubusercontent.com/1086877/76527647-e12a1380-646f-11ea-98dd-8ded1ff020d0.png)

**Comment by dnil** [comment]
😄 And to make life more interesting, ENSEMBL "Canonical" is sometimes not the same as the HGNC-preferred reference transcript. ENSEMBL usually pick the longest, most complete transcript, whereas HGNC (and by extension HGVS) try to choose transcripts that are established, connected with disease and/or predominantly expressed in tissues connected to disease. Which in this case is NM_001913.

https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/HGNC:2557

**Comment by hassanfa** [comment]
I'm thinking how we can handle this. Longest transcript can't be the canonical if it is predicted. I'm skeptical of trying to leave it all to VEP and its CANONICAL annotation in CSQ, since it will change from build to build as well.

For now, I'll disable predicted transcripts, and **_not_** filter for CANONICAL transcripts in the analysis.

I know this has been an ongoing challenge for Scout, but I think if we trust HGNC for curated transcript name and VEP for consequences, then we will have it much easier.

**Comment by dnil** [comment]
I think we can close this for now, knowing that we will get a couple of steps further to harmony with hg38 and MANE, and will likely have a slightly different take on what is dissonant at that point. We also have a separate project for a SPOF for transcripts brewing: https://github.com/Clinical-Genomics/schug.
