### ISSUE TITLE
Bigger clinvar variants hide the small ones in IGV track

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#1793]
Example interval: chr21:47,408,993-47,409,093

Looks like bigger things like this deletion hide small clinvar variants:

![image](https://user-images.githubusercontent.com/28093618/76514289-f85d0700-6457-11ea-80ea-e7ea25547213.png)

This is how the same track looks on UCSC browser:

![image](https://user-images.githubusercontent.com/28093618/76514373-1591d580-6458-11ea-98c8-6b4e945cae2d.png)

**Comment by northwestwitch** [comment]
This was fixed today. It was apparently an igv.js bug: https://github.com/igvteam/igv.js/commit/87fd454f4e7cd9ca949d78ef9dacb8bb72da00dc

**Comment by northwestwitch** [comment]
Still not tested, waiting for feedback in here: https://github.com/igvteam/igv.js/issues/1077#event-3164924058

**Comment by jrobinso** [comment]
@northwestwitch If you're able to test in your environment that would be helpful.   You can use either 
```https://igv.org/web/snapshot/dist/igv.js```   
or 
```https://igv.org/web/snapshot/dist/igv.esm.js```
if you use modules.

**Comment by northwestwitch** [comment]
Sure, I'll test and let you know!

**Comment by northwestwitch** [comment]
@jrobinso looks like it's working, this is how it looks like on our server:

![image](https://user-images.githubusercontent.com/28093618/77569100-f2d8d580-6ec9-11ea-96fe-c1f346dc7451.png)

**Comment by dnil** [comment]
Ooh, maybe the SV track will also work now!

**Comment by northwestwitch** [comment]
It does, look here:

![image](https://user-images.githubusercontent.com/28093618/77571472-bb6c2800-6ecd-11ea-9ef8-53bd759caaa5.png)

**Comment by northwestwitch** [comment]
We just have to fix a good compromise on the size of the tracks now! Works perfectly @jrobinso !
