### ISSUE TITLE
reupload of rare disease cases: new variants are all benign/likely benign

### ISSUE THREAD

**Issue by ielvers** [Clinical-Genomics/scout#1794]
I've gone through 2 of our rare disease cases affected by the reupload due to missing ClinVar significance info. Below is a list of new variants with score >=10 in each case. All these new variants are classified as benign / likely benign / uncertain significance in ClinVar, none is pathogenic or likely pathogenic so why was their score bumped up? Thanks!

Case 20028
New variants with score >=10:
COL6A3 - https://scout.scilifelab.se/cust003/20028/c0ae170582c8696fb61b9f6e04f79228 - benign, likely benign
ATP7B - https://scout.scilifelab.se/cust003/20028/f3e5b6f4ae7f8d053e6e27a7e381d535 – benign, likely benign
CASR - https://scout.scilifelab.se/cust003/20028/a910ee3f69e246ed4f306a46e4c4f401 – benign
COL4A1 - https://scout.scilifelab.se/cust003/20028/63d25992e166acfd247ec048ca3a292d – benign

Case 20033
New variants with score >=10:
WFS1 - https://scout.scilifelab.se/cust003/20033/b8f501dcec99692756dc0468e50e9ddb – benign, likely benign
DPYD - https://scout.scilifelab.se/cust003/20033/f076a0769385c4841f9f3df01d944fcc – conflicting interpretations of pathogenicity (benign, likely benign, uncertain significance)
SLC25A12 - https://scout.scilifelab.se/cust003/20033/17c6a96c63845c40c66fb21e31df37ae – conflicting interpretations of pathogenicity (benign, uncertain significance)
CPS1 - https://scout.scilifelab.se/cust003/20033/37f9868a85d9a93800c0e691f4e8cd9d – benign
RYR1 - https://scout.scilifelab.se/cust003/20033/07ab8c648e975efca3a764cfc3141799 – benign

**Comment by henrikstranneheim** [comment]
There has been no rerun of the underlying data so the rank score for these variants are exactly what they were before. There is no change in the prioritization of the variants. The only difference is that the clinvar information is now shown on the variant page:

![Screenshot 2020-03-12 at 14 32 26](https://user-images.githubusercontent.com/584738/76526739-4d0b7c80-646e-11ea-8a9b-3f02b6078b35.png)

For the case 20028 the default threshold for loading variants was 5 for both uploads to Scout. So variants with a rank score >=10 have always been there.

**Comment by ielvers** [comment]
Oh I see! Then I think the difference is whether I used "clinical filter" or filtered for exonic/splicing annotations. My apologies!

**Comment by henrikstranneheim** [comment]
Its great that you provide feedback if you think something is odd 😄 . We need you do do this to find potential bugs that we have missed - so please continue with the excellent 🐛 👀 !
