### ISSUE TITLE
SNVs opening with SV page format - 

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#1809]
i'm looking at  SV
https://scout.scilifelab.se/cust003/19129/sv/variants/5f83844a201326a423507c977143edb5

checking the overlapping coumpound SNVs
If I click on the link for ex for  6_162646183_G_C_clinical 
this take to a page with the format for the SV non for SNV.
See link or screen shot
https://scout.scilifelab.se/cust003/19129/sv/variants/d5748a3a70cad47ddb1ceef542cb5a8e
![bild](https://user-images.githubusercontent.com/12525201/76976237-ff8e8400-6933-11ea-9145-b9d5ff672f2f.png)

A bug?

Michela

**Comment by dnil** [comment]
Thanks! This appears is somewhat related to #1803 - I could look try to fix it in the same PR!

**Comment by dnil** [comment]
It was just caught in a bad state of unification. Not quite general, but a little more so than before. Fixed in #1807.

**Comment by 4WGH** [comment]
when will the correction be implemented in scout?

Michela
________________________________
Från: Daniel Nilsson <notifications@github.com>
Skickat: den 23 mars 2020 08:54
Till: Clinical-Genomics/scout <scout@noreply.github.com>
Kopia: Michela Barbaro <michela.barbaro@sll.se>; Author <author@noreply.github.com>
Ämne: Re: [Clinical-Genomics/scout] SNVs opening with SV page format - (#1809)


Closed #1809<https://github.com/Clinical-Genomics/scout/issues/1809> via dcfc5cc<https://github.com/Clinical-Genomics/scout/commit/dcfc5cc3fb89a77be805ec60b275ae640b0fc2e3>.

**Comment by dnil** [comment]
Hi Michela @4WGH, 

The same procedure as every year James! This is included in a release candidate 4.14 that is being tested as we speak. I would not be surprised if you have an email announcing a release within a couple of hours, or what do you think @moonso? 😄
