### ISSUE TITLE
gene.iobio

### ISSUE THREAD

**Issue by robinandeer** [Clinical-Genomics/scout#182]
New tool that looks like an IGV browser with some builtin stuff for inherited disease
http://gene.iobio.io/?rel0=proband&rel1=mother&rel2=father

ping @henrikstranneheim, @moonso

**Comment by moonso** [comment]
It is beautiful, but I can not find a good way to look at the aligned reads?

**Comment by henrikstranneheim** [comment]
This is lovely for vetting a gene or region instead of variants. It would make a fantastic complement when wanting to analyse a complete gene. It would be great to integrate this into Scout/puzzle. However, It is not a really a replacement to IGV.

**Comment by moonso** [comment]
We know about this, no need for issue
