### ISSUE TITLE
Check that tumor samples come from the same individual.

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#1828]
This check should be performed by the pipeline upstream (ping @hassanfa), but Scout could show the result of the check.

From the notes of the last user meeting (#1679)

**Comment by hassanfa** [comment]
We can move this to BALSAMIC repo. It think this might be useful with paired samples (tumor/normal).

**Comment by northwestwitch** [comment]
Moved to balsamic: https://github.com/Clinical-Genomics/BALSAMIC/issues/300
