### ISSUE TITLE
Local observations visualization displayed as frequencies.

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#1829]
From the notes of the last user meeting (#1679)

**Comment by northwestwitch** [comment]
@mikaell this one pehaps

**Comment by mikaell** [comment]
Ok. Already I'll start looking into this.

**Comment by mikaell** [comment]
This is my proposed implementation -add an extra entry in the Frequencies table.

![image](https://user-images.githubusercontent.com/1150065/86593850-4b724100-bf96-11ea-8236-cd4d3c0bf8e3.png)

How are frequencies calculated? (@dnil)

**Comment by northwestwitch** [comment]
When you find out what exactly is that number (Total nr.) you could perhaps add a tooltip to the text to clarify what the field is..

**Comment by dnil** [comment]
Hm, it isn’t supposed to be? Our locals are generally count based. Obviously one can show counts divided by chromosomes seen, but it is not clear that it will converge on population frequency or what the bias will be. If we must, at least show both counts and ratio, possibly via tooltip as C suggest? @moonso is perhaps a non-vacation goto person for local counts? 😊

**Comment by mikaell** [comment]
Ok, I'll prepare the code infrastructure in the mean time.

**Comment by moonso** [comment]
Hi, we should not display it as frequencies since they are not frequencies. For example we count a variant only once per family regardless of the number of individuals that holds the variant in that family. For more information about this read the [paper](https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-020-03609-z) 😄

**Comment by northwestwitch** [comment]
> For more information about this read the [paper](https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-020-03609-z)

😆 

But then problem fixed. Thanks for the explanation @moonso (and congrats for the paper!)
