### ISSUE TITLE
Problems with VPN connection

### ISSUE THREAD

**Issue by Bianca-T** [Clinical-Genomics/scout#183]
Hi,

I am trying to connect to Scout from outside KI, using VPN connection.
I am properly logged in into the clinicalgenomics.se google account, but I end up this way each time I try to access the database:
![screen shot 2015-10-24 at 16 39 32](https://cloud.githubusercontent.com/assets/5881356/10710979/2594bcbe-7a6e-11e5-86e3-1ff4114b65a8.png)

Do you have any suggestions on how I can fix this problem?

Kind regards,
Bianca

EDIT: I used to access it properly in the past, this is a recent problem

**Comment by vwirta** [comment]
I’ve had similar problems and it helped with changing to a different browser.
Try Firefox

VW
> On 24 okt 2015, at 16:42, Bianca Tesi <notifications@github.com> wrote:
> 
> Hi,
> 
> I am trying to connect to Scout from outside KI, using VPN connection.
> I am properly logged in into the clinicalgenomics.se google account, but I end up this way each time I try to access the database:
>  <https://cloud.githubusercontent.com/assets/5881356/10710979/2594bcbe-7a6e-11e5-86e3-1ff4114b65a8.png>
> Do you have any suggestions on how I can fix this problem?
> 
> Kind regards,
> Bianca
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/Clinical-Genomics/scout/issues/183>.
> 

----
Valtteri Wirta, PhD
Enhetschef / Head of unit, Clinical Genomics, Science for Life Laboratory
valtteri.wirta@scilifelab.se | +46 8 5248 1545 | Box 1031, 171 21 Solna
Visiting address: Tomtebodavägen 23 A, 171 65 Solna

**Comment by Bianca-T** [comment]
Thanks, It worked with Safari.
