### ISSUE TITLE
Local observations for cancer as well (observations in cancer cases).

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#1830]
This might have a duplicate somewhere in the issue list. From the notes of the last user meeting (#1679). 

Fixing this requires having a loqusdb instance containing frequencies of cancer cases (ping @hassanfa again).

**Comment by hassanfa** [comment]
:+1: I think we should do it the same way MIP handles it. Does MIP run it within the pipeline, or is it some post analysis process? Pinging @henrikstranneheim

**Comment by henrikstranneheim** [comment]
It is part of cg as a post analysis process.
