### ISSUE TITLE
Missing gene information in IGV

### ISSUE THREAD

**Issue by sofievonlanthen** [Clinical-Genomics/scout#1834]
I have a SV in a gene (DEL) of 62kb. When looking at the alignment in IGV I can't see the gene information. I have taken the coordinates for the gene from Ensembl and zoomed in, but still no gene information? 
The gene is IGHG1 and according to Ensembl pos: Chr14: 106,202,680-106,209,408. 
Case 820701400054 (Cust004). Scrolling along on Chr 14, I can't see any genes in this area (Chr14q32.33), which is patched in Ensembl. Normal or a bug?
/Sofie

**Comment by dnil** [comment]
Ah @northwestwitch claimed this one. I'll drop it, but note that a base issue is that RefSeq don't acknowledge any protein coding genes here on the default hg19, likely due to the originally iffy state of the sequence. 

<img width="1186" alt="Screenshot 2020-03-25 at 10 41 25" src="https://user-images.githubusercontent.com/758570/77522864-378e4d80-6e85-11ea-8574-ba26bd9663a6.png">

**Comment by northwestwitch** [comment]
@dnil I think your observation answers the question, we are using RefSeq hg19 as a reference for that sample.

**Comment by sofievonlanthen** [comment]
Ah that makes sense. I didn't even noticed that it says Biotype IG C gene instead of protein coding in Ensembl, has almost the same colour coding as protein coding genes, which is confusing. Thanks!

**Comment by dnil** [comment]
The region has alternative contigs etc for hg38 as well, so unfortunately this would not be resolved by just switching genome build either. On the positive side, I guess interpreting variants here is pretty difficult as well, unless it is well established variants? Long reads will help, as might specialised callers for the immune-regions. We will close this for scout for now, but feel encouraged to get back on the thread if you have a suggestion for things we could att to make calling/visualisations easier here!
