### ISSUE TITLE
editing CLin VAr submission

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#1835]
Hi,
 we preprared some variants to submit, we wish to edit what we have written, how do we do it?

https://scout.scilifelab.se/cust003/clinvar_submissions
 from this page?

where?

**Comment by northwestwitch** [comment]
Hi @4WGH! 
Unfortunately there is no option to edit the submission after you have added the variant and case info and you are at that stage. You could do 2 things:

- Remove the variant and add it again to the clinvar submission
- Edit the Excel sheet downloaded from that page before submitting it to clinvar.

Option one might be the preferred one so the submission object will be saved correctly..

Cheers, Chiara

**Comment by 4WGH** [comment]
hemmmm
could we add edit possibility?
sometime one info is missing and we need to go back....
Wish from other person too.

**Comment by northwestwitch** [comment]
We can keep it open and have it as future project. I don't think we will be able to fix it in a while though, we have several other prios at the moment, so I recommend you to one of the 2 ways I suggested above for the time being.

**Comment by 4WGH** [comment]
![bild](https://user-images.githubusercontent.com/12525201/77995037-52e8d500-732b-11ea-9e64-f423c1a1fe27.png)

the excell sheet looks like this .....
not really able to edit it

I've downloaded it from the ClinVar submission page and opened it with excell

Suggestions?

**Comment by 4WGH** [comment]
variant file and case file are saved with the same name:
SUBnummer-date

could we add- "variants" AND "-cases" to disinguish them?

**Comment by dnil** [comment]
I am not an MS Excel expert, but it looks to me like you did not parse it as a csv-file?
In some versions you can do this by choosing "Import" from the menu, in some an automatic dialog is triggered when you open a file with a name ending in ".csv". Can you consult a nearby colleague with experience from this program? I also find that the help search in the Office suite program is handy. Try typing "csv" or "import" there!

**Comment by 4WGH** [comment]
I usually manage to open different type of excell file :(

no question asked :(

can you tell me if you can open it in a hospital PC?

**Comment by 4WGH** [comment]
let it be, Leif with can open it. he has windows 10.

uff!! so frustrating when PC have own life style

**Comment by dnil** [comment]
👏 Good! I was able to open it on an old hospital Windows 7 Enterprise install way back when we were testing this out, but the MS Office was likely different than today.

**Comment by 4WGH** [comment]
Sorry Leif get also the same with with everything in one cell :(

WE are trying different way of opening and saving.

**Comment by 4WGH** [comment]
We found a way! thanks to Leif

DAta, import data från CVS

:)

**Comment by northwestwitch** [comment]
Nice @4WGH . I remember that once the 2 files (case data and variant data) had their own specific name, we should fix that, thanks for the suggestion!
