### ISSUE TITLE
ClinVar - Functional consequences

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#1836]
in the window to submit variant we wonder about the list "functional consequences"
there is a dropdown menu. Does the list come fron ClinVAr?
we have a splice variant and can not find any appropiate choice in the list.
![bild](https://user-images.githubusercontent.com/12525201/77523434-06fae380-6e86-11ea-859c-6f14b9b38aee.png)

**Comment by northwestwitch** [comment]
Hi, that field is not for describing moleculat consequences (e.g. affecting splicing)

Terms of that field might come from:
- Sequence ontology (http://www.sequenceontology.org/browser/obob.cgi), e.g. SO:1000071
- VariO (http://www.variationontology.org/cgi-bin/amivario/browse.cgi), VariO:0397
- LOVD (https://www.lovd.nl/).

Separate multiple terms by a semicolon.


Here's the explanation from the official clinVar Excel sheet:

![image](https://user-images.githubusercontent.com/28093618/77525485-67d7eb00-6e89-11ea-91c6-adf18d5846e0.png)

**Comment by northwestwitch** [comment]
Does it answer your question @4WGH ?

**Comment by 4WGH** [comment]
OK, thanks
