### ISSUE TITLE
List of cases does not show up in Scout

### ISSUE THREAD

**Issue by vwirta** [Clinical-Genomics/scout#184]
No list of cases is generated when logging into Scout. Reported by Giedre (cust002) to VW by e-mail, same error repeated by VW. Direct links to cases seem to work, at least for most cases

**Comment by vwirta** [comment]
Dear Valtteri,

2015-10718 F0003626 

It is really strange. I asked Kicki Lagerstedt and she does not have ny problem. The case above was left as history in my Firefox and I could open it and look at the variants. As soon as I want to see the list of all the cases the window is just empty.

Thanks a lot,

Giedre

**Comment by robinandeer** [comment]
It must be web browser specific so I will need to see what's going on to tell anything,

we are moving away from that however and rendering more on the server so that we avoid problems like this

**Comment by vwirta** [comment]
The problem is both in Chrome and Firefox.
Worked nicely yesterday morning, but not since then. 

Problem both here at my end and also Giedre is observing the same problem.

VW
> On 29 okt 2015, at 10:26, Robin Andeer <notifications@github.com> wrote:
> 
> It must be web browser specific so I will need to see what's going on to tell anything,
> 
> we are moving away from that however and rendering more on the server so that we avoid problems like this
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/Clinical-Genomics/scout/issues/184#issuecomment-152125627>.
> 

----
Valtteri Wirta, PhD
Enhetschef / Head of unit, Clinical Genomics, Science for Life Laboratory
valtteri.wirta@scilifelab.se | +46 8 5248 1545 | Box 1031, 171 21 Solna
Visiting address: Tomtebodavägen 23 A, 171 65 Solna

**Comment by dnil** [comment]
Helena and I second that - we also don’t see the case list today, but if you know your case numbers it’s possible to get to them.

// Daniel

**Comment by dnil** [comment]
Ok, on an update it seems to be working for me in Firefox now, though not for Helena, also w Firefox! 

Thank you!

// Daniel

**Comment by robinandeer** [comment]
Please confirm if the recent fix has resolved the issue!

**Comment by dnil** [comment]
Works for me!

// Daniel

**Comment by vwirta** [comment]
Same here!
Thanks Robin, Kenny et al.

VW

> On 29 okt 2015, at 13:23, Daniel Nilsson <notifications@github.com> wrote:
> 
> Works for me!
> 
> // Daniel
> 
> > On 29 okt 2015, at 13:10, Robin Andeer <notifications@github.com> wrote:
> > 
> > Please confirm if the recent fix has resolved the issue!
> > 
> > —
> > Reply to this email directly or view it on GitHub <https://github.com/Clinical-Genomics/scout/issues/184#issuecomment-152159208>.
> > 
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/Clinical-Genomics/scout/issues/184#issuecomment-152162705>.
> 

----
Valtteri Wirta, PhD
Enhetschef / Head of unit, Clinical Genomics, Science for Life Laboratory
valtteri.wirta@scilifelab.se | +46 8 5248 1545 | Box 1031, 171 21 Solna
Visiting address: Tomtebodavägen 23 A, 171 65 Solna
