### ISSUE TITLE
Deleting last ACMG classification document does not clear ACMG classification level

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#1845]
If an ACMG classification is "deleted" from a variant, it can still be seen on the variants view. :blush:

**Comment by northwestwitch** [comment]
Also in current master?

**Comment by dnil** [comment]
At least current stage for IGV..

**Comment by dnil** [comment]
I realise this may not have been completely unintentional, so not really a but - more of QoL. The classification document can be deleted, but the event stays, and with it the prior classification level until it is changed. One then has to click the set prior classification level to un-classify it with an open acmg level, clear the variant object etc. What do you think: should we help the user by doing the latter automagically when they hit delete, or leave it as is?

**Comment by dnil** [comment]
Meh, let's just do it. It makes relatively little sense to keep it. The risk of someone manually reclassifying without submitting an evaluation exactly when someone deletes the last one seems negligeable.
