### ISSUE TITLE
ClinVar variation identifier

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#1850]
![bild](https://user-images.githubusercontent.com/12525201/78219403-c0c60580-74bf-11ea-9836-db596d028cd9.png)

we got an error message when submitting 
the variant identifer has not the right format (it was autogenerated by scout )

most probably 2 numbers are added in
![bild](https://user-images.githubusercontent.com/12525201/78219590-1ef2e880-74c0-11ea-81fc-451e1863bb97.png)
rs number and ClinVar number

**Comment by northwestwitch** [comment]
This is probably a result of some previous parsing error for the variant of the case. This type of issue was supposed to be fixed some time ago (specifically by this pull request: https://github.com/Clinical-Genomics/scout/commit/927a21acfe4a6bcd593332368785bd44c59a2d4a). Was this variant added to the clinvar submission recently or months ago?

**Comment by 4WGH** [comment]
we are creating the submission today.
The case is however old.

**Comment by northwestwitch** [comment]
Ok but then the problem was not fixed. I'm marking this as a bug.
