### ISSUE TITLE
ClinVAr -case level submission - zygosity

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#1851]
zygosity is an optional feature in CLinVar form.

We need the possibility to leave it empty in the scout submission form
![bild](https://user-images.githubusercontent.com/12525201/78220650-316e2180-74c2-11ea-8ead-8fa8a2df9799.png)

we need it for cases where where comp het is not confirmed by parental samples analysis

**Comment by northwestwitch** [comment]
This can be fixed, but probably won't be included in the next Scout release.

If you need to create the submission files and submit them before our fix please just assign a random value using the scout form and then remove it from the excel file.

**Comment by 4WGH** [comment]
that is what we have done today :)
fixed manually. 

looking forward for the final fix. we can try to submit the proved compuond in the meanwhile
