### ISSUE TITLE
clinVar - variant identifier box

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#1853]
![bild](https://user-images.githubusercontent.com/12525201/78222620-d0484d00-74c5-11ea-8335-737a30b8e844.png)
case 18099
the box for variant identifer is missing

**Comment by northwestwitch** [comment]
This is odd. The box should show whenever the variant is a snv variant. Classifying this as a bug that needs fixing. Please add it manually to the excel file before we fix it. Sorry for the inconvenience!
