### ISSUE TITLE
clin Var excell case file

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#1854]
![bild](https://user-images.githubusercontent.com/12525201/78223014-7f852400-74c6-11ea-9877-86465980f7aa.png)

 we can see the individual ID is our local number not the arbitrarly generated (see the case ID)

![bild](https://user-images.githubusercontent.com/12525201/78223153-b22f1c80-74c6-11ea-8f13-861a30b3aea8.png)

**Comment by northwestwitch** [comment]
The arbitrary generated name is for the case, not the individual. In fact the arbitrary generated name is the same for individuals of the same case, look at primewhale for instance. This is intended since the beginning, so nothing strange here.

Was this a question or a request?

**Comment by 4WGH** [comment]
The indivudual ID go into the ClinVar submission so we should not use our local ID but the arbitray ones. 
![bild](https://user-images.githubusercontent.com/12525201/78247176-b53c0400-74ea-11ea-99f9-d8ea35ed8f11.png)
 see exdplantion from CLinVar for for individual ID

**Comment by northwestwitch** [comment]
I see your point! One solution would be to name the individuals as anonymName_1, anonymName_2 and so on. Would that be ok?

**Comment by 4WGH** [comment]
yes....
can we use the same arbitrary name?
we cam talk over that. not sure I can get all the details connected to this issue
