### ISSUE TITLE
ClinVar revstat string change affects clinical filter 

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#1857]
The ClinVar revstat strings have silently changed to e.g. "multiple_submitters" from "mult", likely with the new csq clinvar. While this is kind of more informative, the clinical filter relied on these to lift known variants regardless of other filter criteria. Hence some clinically relevant, but unseemly looking variants may have been overlooked in analyses. 

See e.g. https://scout.scilifelab.se/cust002/F0027508-2/35601d0679231f6b35d004d076a1b760

**Comment by dnil** [comment]
This was sort of supposed to be fixed by https://github.com/Clinical-Genomics/scout/issues/1160 methinks, but something glitched?

**Comment by northwestwitch** [comment]
We fixed the clinsig value in #1160  (Pathogenic, Likely Pathogenic, 4, 5). The revstat was not addressed. I guess now is the time!

**Comment by dnil** [comment]
Yeah, its been a year, so.. 😜 

Seriously though, I suppose this will have affected all cases since the move to CSQ ClinVar in MIP?

**Comment by northwestwitch** [comment]
Probably!
