### ISSUE TITLE
IGV view lacking Reference track

### ISSUE THREAD

**Issue by 47KW** [Clinical-Genomics/scout#1869]
IGV view lacking Reference track

**Comment by northwestwitch** [comment]
Oh no, this is my fault, I've made changes into the track code. I'll fix it ASAP, sorry!

**Comment by 47KW** [comment]
Thanks Chiara!

/ Håkan

Från: Chiara Rasi <notifications@github.com>
Skickat: den 7 april 2020 15:32
Till: Clinical-Genomics/scout <scout@noreply.github.com>
Kopia: Håkan Thonberg <hakan.thonberg@sll.se>; Author <author@noreply.github.com>
Ämne: Re: [Clinical-Genomics/scout] IGV view lacking Reference track (#1869)


Oh no, this is my fault, I've made changes into the track code. I'll fix it ASAP, sorry!

**Comment by northwestwitch** [comment]
Thanks for reporting the error!

**Comment by dnil** [comment]
Yep, thanks! 🦅 I also looked at the CNV variants PR without noticing..

**Comment by northwestwitch** [comment]
Looks like it's not (entirely) my fault this time. Must be the igv.js version with the bigBed bugfix we introduced in the scout release of yesterday. I've compared the HTML source in both cases (a previous version of scout with the reference, and the one produced by the code now) and the only difference is this line:

With this version it works:
`<script type="text/javascript" src="https://igv.org/web/release/2.3.0-rc1/dist/igv.min.js"></script>`

with this version it doesn't:
`<script type="text/javascript" src="https://igv.org/web/snapshot/dist/igv.js"></script>`

If we revert we'll have the bigBed bug again. I'll write to igv.js and ask when the next version update will happen!

**Comment by northwestwitch** [comment]
Look here, for reference: https://github.com/igvteam/igv.js/issues/1077

**Comment by northwestwitch** [comment]
Looks like reference is back today:

![image](https://user-images.githubusercontent.com/28093618/79212808-6bd3a900-7e48-11ea-8905-aa736083776d.png)

Closing this now, but please reopen if the problem shows up again!
