### ISSUE TITLE
IGV track ClinVar CNV

### ISSUE THREAD

**Issue by 47KW** [Clinical-Genomics/scout#1872]
We would like to have a discussion on the necessity to include ClinVar CNV track in the IGV view. All (majority) of users at Clin Genetics would like to have it removed. It does not provide any useful information. Can it be "collapsed" as default, or removed?
Discuss at user-meet.

**Comment by dnil** [comment]
But it's so nice! 😸 
<img width="1288" alt="Screenshot 2020-04-14 at 11 06 51" src="https://user-images.githubusercontent.com/758570/79206798-28753c80-7e40-11ea-8440-7aa7703c9f38.png">
I do agree it is annoying that they have over-populated it with large events, and that it is not needed as often as its visual real estate does imply. Let's have a discussion, especially with the array ppl about how we can improve it!

**Comment by northwestwitch** [comment]
One cool thing would be to set up at the institute- or even user-level, the tracks that one wants to see. It's doable I think

**Comment by dnil** [comment]
Yes, perhaps even inevitable with this, as the number of potential tracks is large indeed. I would love individual setting of track height, expansion status and track order. It has also been very useful for us to allow users to debate and globally decide on feature presentation. It can help making them better. The two don't have to exclude one another I suppose.

In case of the CNV track, if we could work with igv.js and co, the track providers or ourselves for a way to sort the track to show small events first, that would help. The large events will be covered by vcf2cytosure for the time being. Compare the potentially vital
<img width="929" alt="Screenshot 2020-04-14 at 16 00 45" src="https://user-images.githubusercontent.com/758570/79233444-2a072a80-7e69-11ea-8d5a-0805f88fc05f.png">
to a global
<img width="1213" alt="Screenshot 2020-04-14 at 16 00 33" src="https://user-images.githubusercontent.com/758570/79233447-2b385780-7e69-11ea-9ee6-96ab9c4bc6fd.png">
