### ISSUE TITLE
Filter this in MIP?

### ISSUE THREAD

**Issue by 47KW** [Clinical-Genomics/scout#1877]
Why do we still see this variant?
Curious to understand, I am

https://scout.scilifelab.se/cust002/F0033760/ee19c34d2bf3c9d4c2b967a5c16cdc03

**Comment by northwestwitch** [comment]
Scout loads all variants with a rank score > 5 (unless a different value is specified), this one has 14 so it's expected to be there. Was there any ongoing discussion about this specific variant in MIP?

**Comment by dnil** [comment]
Are you thinking about the rationale for setting the hard cutoff perhaps? The current hard cutoff frequency level (where it would not make the cut and be eligible for loading, regardless of other parameters) is 40%. This variant is at perhaps 20%, so "only" gets a -12 score component for frequency, but e.g. +5 for splicing. Obviously it is removed by eg "clinical filter" or a manual frequency filter. 

The number of really common variants that get a high enough score is still limited. But 40% is high. I believe this is modeled after some common variant over at one of our sister clinics (@henrikstranneheim). "Our" most common recessive founders would be more like 3-5%, so a level of say 10% should be as safe as many of the other assumptions made. We could make it a discussion point at a meeting. It is both computationally and triage-wise helpful to load fewer variants.

**Comment by 47KW** [comment]
Great, thanks for enlightening me. Both C and D

/ Håkan

Från: Daniel Nilsson <notifications@github.com>
Skickat: den 20 april 2020 15:20
Till: Clinical-Genomics/scout <scout@noreply.github.com>
Kopia: Håkan Thonberg <hakan.thonberg@sll.se>; Author <author@noreply.github.com>
Ämne: Re: [Clinical-Genomics/scout] Filter this in MIP? (#1877)


Are you thinking about the rationale for setting the hard cutoff perhaps? The current hard cutoff frequency level (where it would not make the cut and be eligible for loading, regardless of other parameters) is 40%. This variant is at perhaps 20%, so "only" gets a -12 score component for frequency, but e.g. +5 for splicing. Obviously it is removed by eg "clinical filter" or a manual frequency filter.

The number of really common variants that get a high enough score is still limited. But 40% is high. I believe this is modeled after some common variant over at one of our sister clinics (@henrikstranneheim<https://github.com/henrikstranneheim>). "Our" most common recessive founders would be more like 3-5%, so a level of say 10% should be as safe as many of the other assumptions made. We could make it a discussion point at a meeting. It is both computationally and triage-wise helpful to load fewer variants.

**Comment by henrikstranneheim** [comment]
@dnil Exactly so, There was a founder mutation hovering around 35% (I think Michela was involved). We do not want to miss anything so we put the hard cut-off at 40%. This can of course be changed if requested. But I think one should be careful with hard filters and it is better to downprioritize it.

**Comment by dnil** [comment]
Unless you have more thoughts about this @47KW I think we can close this for now and possibly discuss a bit on the next user meeting. Thank you for reporting things that look out of the ordinary!
