### ISSUE TITLE
Scout delivery for cancer

### ISSUE THREAD

**Issue by annaengstrom** [Clinical-Genomics/scout#1878]
Develop Scout for cancer ready for delivery to customers

Define MVP and implement required features

**Comment by dnil** [comment]
Was this intended for the CG repo perhaps? 😊

**Comment by annaengstrom** [comment]
I have no idea, it's a scout action so I thought it was for scout repo?

**Comment by annaengstrom** [comment]
Taken from https://docs.google.com/document/d/1N4oTgJK4J0vOg7x5vlgT24TIdkJrhckxLNnmTb7fiA0/edit#

**Comment by dnil** [comment]
I will likely understand better when I have access to the above document. Was it some kind of action point from a meeting? 

But as for the comments above:

> Develop Scout for cancer ready for delivery to customers
> Define MVP and implement required features

As determined by roll call at previous scout cancer user meetings with a few user groups represented, we were already at MVP with the then current scout version, and have been adding additional features continuously. Could you be a little more specific as to what feature you are asking for or what information you want? Cheers!

**Comment by annaengstrom** [comment]
@emmser or @hassanfa maybe you are more up to date with this? I haven't joined any scout cancer meetings

**Comment by annaengstrom** [comment]
@dnil This is an action from the Clinical Genomics project "Cancer implemented in weekly production"

**Comment by hassanfa** [comment]
This is 99% not scout. CG and housekeeper.

**Comment by dnil** [comment]
Ok,  thanks! I think as for the Scout part, you can likely flag this done, but feel free to add specific requests.

Please have a look at eg the open issues with "Cancer" labels and the "Cancer view" project and see if there are other things needed, and comment if anything needs a higher priority! Also new specific things that you come think of is very welcome! We are currently tracking that one that might be considered close to MVP would be cancer capture kit specific local variant frequencies by loqusdb, e.g. issue #1830, but that will require only a small change to Scout as soon as the corresponding backend in servers and cg is in place.

**Comment by dnil** [comment]
I'll close this for now, but feel free to reopen as needed, and in particular specific requests for features are very welcome at this level!
