### ISSUE TITLE
Phenomizer broken on current master 

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#1896]
Likely collateral damage from #1893.

**Comment by northwestwitch** [comment]
Codefactor fixes in 38 files, immediately before a release.. That's what I call being brave! 🤣

**Comment by dnil** [comment]
Best way of getting them tested! 😝

**Comment by northwestwitch** [comment]
> Best way of getting them tested!

Indeed!

**Comment by dnil** [comment]
Confirmed working on 4.15.1. 😊
