### ISSUE TITLE
Add variant search by cytoband

### ISSUE THREAD

**Issue by TJO-Lund** [Clinical-Genomics/scout#1906]
When using filter (SvFilters) for Clinical Structural Variants in Scout there is no option to use AND instead of OR. This hampers any attempt at refined combinatorial searches. Also, it is not possible to search for chromosomal bands as only chromosome number 1, 2, 3 etc are accepted. Could for example a radio button indicating AND respectively OR be added to filter options in Scout? All the best Tord Jonson (Lund)

**Comment by dnil** [comment]
Hi! Two things here:

1 - use cytobands in sv queries

This is doable, although not super-easy! We already keep a structure with cytobands and coordinates. It is currently build unaware, so will need an update anyway to enable doing both hg19 and hg38 cases in the same instance.

2 - explicit AND / OR in queries

Please state explicitly what queries you would like to support, and we will see what we can do! 

Every toggle increases the risk of someone running an analysis they did not intend. I rarely find I need more than we have in daily practice, although I sometimes miss  "not", "inclusive" and "and/or"-toggle for some fields when trouble-shooting issues. If this is on a research / development basis, consider the use of MongoDB Compass or similar tools to access the database collections directly!

For a bit of reference, variant query currently operate on a three tier basis: top, primary and secondary terms. 

> Requests to filter based on gene panels, hgnc_symbols or coordinate ranges must always be honored. They are always added to query as top level, implicit '$and'.
> There is only 'clinsig' criterion among the primary terms right now. 
>
>  secondary_terms: e.g.  gnomad_frequency, local_obs, clingen_ngi, swegen, spidex_human, cadd_score, genetic_models, mvl_tag, functional_annotations, region_annotations, size, svtype, decipher, depth, alt_count, control_frequency

There are also a couple of special cases spiced in to consider, such as the clinsig confidence check, sv coordinate overlaps and "inclusive" status, referring to wether to include or exclude empty values.

**Comment by dnil** [comment]
I made a new issue for the cytobands-build issue, which will be a prerequisite for point 1..

**Comment by bjhall** [comment]
Regarding the AND/OR thing, @TJO-Lund . Is that still a problem? Most things should be AND by default, but there was a bug for coordinate searches which made it appear to be OR. I fixed that bug back in February https://github.com/Clinical-Genomics/scout/pull/1762

Combining for instance SVtype and coordinates appear to work fine. Could you give an example of where it fails?

**Comment by TJO-Lund** [comment]
Bjhall, thankyou for the reminder! Yes, it works better now and the AND/OR issue may thus be closed for the moment. Can the part of the issue regarding possibility to search by cytoband (in both hg19 and 38) be implemented?

**Comment by northwestwitch** [comment]
I took the liberty of renaming the issue title. Hope it's fine!

**Comment by TJO-Lund** [comment]
ok :-)
