### ISSUE TITLE
[Feature request] Option to show number of filtered variants and export filtered variants table

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/scout#1914]
After applying filters to variants, there is no total count. It is hard to say even if filtered removed anything. It'd be great to show a total count of filtered variants. And then export them in excel format. There is option to export causative variants on institute level but not on case level. Of course one can pin these variants one by one and print out a report, but exporting before pinning can be quite useful.

**Comment by dnil** [comment]
I guess two reasons for why we have previously not done this.

First, the count could be very high - and exported doc dito - eg for a genome with many loaded variants easily in many tens of thousands. But lets evaluate again; it works well enough for cases.

Also we actively try to discourage our clinical users from applying Excel instead of learning and/or communicating what kind of queries they want to perform. So tread carefully.. :wink:

**Comment by dnil** [comment]
Ah, sorry, if this is a customer request, I'd personally vote against the Excel part and instead try to explain to the customer why this is not good practice!

**Comment by northwestwitch** [comment]
yeah, I was about to reply. It could be hundred thousands variants, and an excel export wouldn't do. But I like the filtered number over the total number of variants thing

**Comment by hassanfa** [comment]
It'd be great to only export top 50 or so. Somatic mutations ready to be further evaluated rarely exceed 10s or 20s. It is mainly to be able to take these as archive next to the report of pinned/causative/etc variants.

**Comment by dnil** [comment]
Suggest they interact with variants? And that there are likely thousands of other variants they don't see anyway. In my experience, the customer often does not fully appreciate that they are screening rather than testing?

**Comment by hassanfa** [comment]
True. If we exclude the Excel part, is it possible to show counts? That way we know how many variants are filtered by each filter.

**Comment by northwestwitch** [comment]
> True. If we exclude the Excel part, is it possible to show counts? That way we know how many variants are filtered by each filter.

That should be possible without too much difficulties I think

**Comment by vwirta** [comment]
One reason for requesting the filtered variants table is to allow pathologists integrate variants from Scout to their combined pathology report. 
For many cases the number of variants would probably be low (few to tens), but for other cases it could be higher (eg highly mutated melanoma cases).

One option could be to have a function to export a subset of the variant information for pinned (or otherwise selected) variants

**Comment by dnil** [comment]
I think this stems from initial confusion about how Scout works - or at least how we use the term “filter”. They imagine it is a one fixed automated linearly applied filter that for some mechanistic reason requires a user to press button Filter then button Export, with no stepwise judgement calls. If so we would already provide a simple prefiltered file with no room for edits. No need for an interactive process. They should likely instead be asking for either a final triage report, eg with all variants that have been classified, discussed, dismissed or questioned described. We can do that.

But let’s stay clear of the spreadsheet. This is a typical computer newbie request, and should from
a techno-paternalistic perspective be kindly but firmly denied. It will not benefit the patients, nor the customer in the long run.

VCF export as in the parallel request is slightly better. At least fewer will be tempted to “fix” or “analyse” the files manually. If this is for a set format report, perhaps we can provide a pdf version formatted to their liking they can include?

**Comment by hassanfa** [comment]
The number of filtered variants doesn't show up:
![image](https://user-images.githubusercontent.com/1086877/90636269-a7351880-e22a-11ea-95b7-9b45fd4fbd3c.png)

**Comment by dnil** [comment]
Hi, in what version of Scout are you seeing? This was (hopefully) solved in the release candidate 4.20, but note that the current production (web) instance in Solna is still at 4.19.

**Comment by hassanfa** [comment]
You're right. Hasta is still 4.19. Closing this then.
