### ISSUE TITLE
[BUG] GATK:Pass in report even though there is no GATK caller in cancer cases

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/scout#1916]
It seems report picks up and reports a pinnged variant as `GATK:pass` even though there is no GATK caller used.

Steps to reproduce:
1. open a case in scout-stage with cancer track. e.g. https://scout-stage.scilifelab.se/cust000/KMP-00104_balsamic
2. Go to clinical variants and select a variant.
3. Pin the variant and generate a report: 
![image](https://user-images.githubusercontent.com/1086877/81700430-ee13b500-9468-11ea-8148-9793189628bf.png)

Variant caller that is used is VarDict, but for some reason is showing GATK:pass. It shouldn't show anything.

**Comment by northwestwitch** [comment]
I have a feeling why we default to pass. this should be fixed!

**Comment by hassanfa** [comment]
I tried with an old case on stage, and it didn't show up. So probably a new event? https://scout-stage.scilifelab.se/cust000/20190327_cancer_T_N/case_report

**Comment by northwestwitch** [comment]
The specific moment this started is this: #1800. We weren't considering cancer variants in that moment I think.

**Comment by dnil** [comment]
:blush: likely true!

**Comment by northwestwitch** [comment]
@hassanfa could you provide a mini VCF file to test with? One or 2 variants and the header would be enouth!

**Comment by hassanfa** [comment]
This should work: https://www.github.com/Clinical-Genomics/scout/tree/master/scout%2Fdemo%2Fscout_example_tumor_only.snv.indel.sorted.vcf.gz

**Comment by northwestwitch** [comment]
Thanks, I'll work on this issue today! :)
