### ISSUE TITLE
[Feature request] Add CNV report to the side panel

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/scout#1917]
(it's me again 👺 🚪 )

This is related to last item in #1679 to show CNV plots: to show CNV report on side panel _if possible_ (under mtDNA report)

![image](https://user-images.githubusercontent.com/1086877/81702260-55caff80-946b-11ea-99a8-2d2989506765.png)

- Single PDF to have information about:

    1. Tumor purity plots
    2. B-Allele plots
    3. CNV scatter plots
    4. CNV karyotype plot (diagram plot)

- Things to consider:

    1. Rendering large PDF files of scatter plots of WGS can be time consuming.
    2. Single multipage PDF can be large in size
    3. Downloadable file should be a ZIP file to avoid loading large single PDF in browser

**Comment by northwestwitch** [comment]
Do you have these plots already?

**Comment by northwestwitch** [comment]
Because in that case probably plots should be generated before and made available for download from the sidebar, same as delivery reports etc.

**Comment by hassanfa** [comment]
Yes I do and yes, a zip file of these PDF files will be created in bioinfo workflow. Attaching multiple PDF files here. These are dummy files though, which they will be merged into one:

[dummy_b_allele_purity.pdf](https://github.com/Clinical-Genomics/scout/files/4616203/dummy_b_allele_purity.pdf)

[tumor.merged-scatter.pdf](https://github.com/Clinical-Genomics/scout/files/4616190/tumor.merged-scatter.pdf)

[tumor.merged-diagram.pdf](https://github.com/Clinical-Genomics/scout/files/4616189/tumor.merged-diagram.pdf)

**Comment by northwestwitch** [comment]
Ok but then you provide the path to the zip file in the config file, and when the case is loaded it will be saved in the database (must be fixed), and when users click the download will point to the saved file.

**Comment by dnil** [comment]
Perfect; remember to create corresponding issues in CG/HK to make sure files are propagated to the scout load config!

**Comment by hassanfa** [comment]
Yes Chiara, on my local Scout I use mtDNA report field to supply these but "mtDNA report" field name is not really matching the content...

BALSAMIC is not yet automated via CG/HK 😬

**Comment by dnil** [comment]
This looks very straight-forward! Do you have a name for it you would like for in the load config? CNV_report?

**Comment by hassanfa** [comment]
I don't feel easy to lock it to a program name like we do for `peddy` and `multiqc`, softwares come and go but format stays 😛 . I have some suggestions to reflect the fact that this is for cnv/cna: `cnv_report`, `cnv_diagrams`, `cnv_plot`, or just `cnv`.

I think `cnv_report` is best.

**Comment by hassanfa** [comment]
fyi, the file will be a PDF for now. But I was talking to Chiara a while ago and I thought maybe a html would also be fun to consider. Similar to what multiqc provides: an interactive and simple cnv_report.html

**Comment by northwestwitch** [comment]
@hassan from our previous discussion I've understood that the CNV report might be consisting of more than one file, and that's why we want to return a zipped file. Is that so?

**Comment by hassanfa** [comment]
Continuation from PR: Lets have it a single PDF to download. Files are rather small in size, so I guess it'll be easier to have them unzipped?

**Comment by northwestwitch** [comment]
> Continuation from PR: Lets have it a single PDF to download. Files are rather small in size, so I guess it'll be easier to have them unzipped?

Direct download that is
