### ISSUE TITLE
Make it possible to edit one's own comments in Scout

### ISSUE THREAD

**Issue by TJO-Lund** [Clinical-Genomics/scout#1918]
It would be great if it could be made possible to edit your own comments in Scout as it would save a lot of time, at least for me. Today the only way to correct for errors (typos etc) is to copy paste the old comment, correct and delete the old one.  What do you think - can this be done?

**Comment by northwestwitch** [comment]
Hi and thanks for the suggestion! 
I think many of our users in Stockholm are relying on their  comments a lot when it comes to planning strategies (for example variant verifications) and analyzing cases in general. Comments are used as notes and decisions are taken based on your notes and those of their colleagues.  Stockholm users take also advantage of the functionality of **global comments**, that allows you to see if a variant that you observe in one of your cases was also found and received comments in a case from another institute. 
For this reason I'm not sure all users will be thrilled at the idea of editing previous comments (even if they are their own). On the other hand I also understand the frustration of not being able to fix typos when they occur.
This is just a suggestion and if someone has ideas please do comment, but what we could do is making comments editable for a defined period of time, for instance 24h. This could be done relatively easy I think. What do you say?

**Comment by TJO-Lund** [comment]
A 24h window for editing should meet both ends and I agree this could be an optimal solution.

**Comment by TJO-Lund** [comment]
Are we agreed on implementeation of a 24h editing window? If so, when can this be implemented?

**Comment by dnil** [comment]
This sounds like a great thing to discuss at a user meeting. We can fix it fairly easily, I suppose currently one could just delete and make a new entry anyway, so for most use cases it does not matter terribly either way. But perhaps it does have some implications for the audit trail?

**Comment by dnil** [comment]
There wasn't exactly a great opposition to this at the meeting, so lets go ahead!

**Comment by northwestwitch** [comment]
This can be split into 2 smaller tasks: 
- [ ] Make case comments editable
- [ ] Make variants comment editable

**Comment by TJO-Lund** [comment]
We are looking forward to seeing this implemented. Thank you for looking into it!
