### ISSUE TITLE
[Feature request] Filter cancer variants based on chr, start and end

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/scout#1926]
Customer request to filter variants based on chromosome, start and end. This will show variants that fall within the defined range. I suggest to only consider if start position falls in between the defined region.

So probably there is no need to consider if the whole length of a large indel falls within defined region.

**Comment by northwestwitch** [comment]
Hi @mikaell I don't know if you have started with this yet, but we have recently made a change in the code you might be looking at in this PR (Filter models), you might want to pull the recent master and take a look at https://github.com/Clinical-Genomics/scout/blob/master/scout/server/blueprints/variants/forms.py

Long story short, chromosome field is now a select input

**Comment by mikaell** [comment]
Thanks @northwestwitch!

I've started looking at this. But no back-end code written yet.

**Comment by mikaell** [comment]
> Hi @mikaell I don't know if you have started with this yet, but we have recently made a change in the code you might be looking at in this PR (Filter models), you might want to pull the recent master and take a look at https://github.com/Clinical-Genomics/scout/blob/master/scout/server/blueprints/variants/forms.py
> 
> Long story short, chromosome field is now a select input

Thanks! Have started, but not done any backend coding yet.

**Comment by mikaell** [comment]
Merged to master 8/6-20.
