### ISSUE TITLE
fam 19081 inactive, not re-runned?

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#1929]
Hi,
 this family is again in Scout as inactive, but we look at it with v.15 of EP panel (=last version of our panel)
I've noticed that the are more variants uploaded then before. what has happened?
I can see all dismissed variants as well not dismissed (too many to have missed them)

**Comment by dnil** [comment]
Hi! On the surface, this sounds more like an issue for a ticket or a call to your colleagues. If I interpret the activity log (bottom of the case page) correctly, NL ordered the rerun on 200508, the rerun was completed and uploaded yesterday. It is flagged as a rerun in the case listing.
<img width="804" alt="Screenshot 2020-05-22 at 10 35 57" src="https://user-images.githubusercontent.com/758570/82648530-12655380-9c18-11ea-83af-1f2cecccbe54.png"> 
The new delivery report is not up yet, so let's see what it contains, but the previous run is more than a year old.

But, I see your worry - there could be any number of strange things going on, from big changes in pipeline or gene panel, over errors on loading, to an issue with the new keeping-variants-flagged-on-load mechanics I Scout. We'll take a look!

**Comment by 4WGH** [comment]
in 2 persons we looked at the re-run with v15 on 2020-05-15!!!!!!

I was surprised to see it again inactive today. SO I've looked into it.
Several not dismissed variants came up (not added with version 15 but earlier versionsof panel) From this my worries.

Why the delivery report is not up?

**Comment by dnil** [comment]
There are several small things combining here I think, but an issue it becomes and we are grateful that you report it!

First line of asking about the delivery report is normally a ticket to production, but I can ask since we are here. From what I can see, there was only one rerun this year, which was completed on 2020-05-19, and uploaded two days later.

The delivery reports have not been generated from CG for this case since the first rerun - or at least not added to Housekeeper and the Scout load config. That is clearly an issue - either a manual routine or a software issue! We can forward this to CG if we don't get a good answer!

As for the original issue with new variants, this will involve a bit too much personal data to post in detail on the web, but from looking at a few of the "new" top candidates, I would guess this is mostly due to changes in the rank model. The new top ones are indels (that we have worked to give higher scores), or variants that do not conform to the inheritance models (that are relatively less penalised now). Have a look again and tell me what you think. If you still find strange variants in there that should have been there before, we can have a look or forward this to GenMod or MIP for a second opinion.

**Comment by 4WGH** [comment]
I still think something is strange here.

I can see which variants were dismissed when the fam was analysed with panel version 14 (EP+IEM) in September (we have saved an analysis report).

There are more dismissed variants now (speaking in favour that when I've look at this fam on 2020-05-12 and Tommy on 2020-05-15 we look at a re-run.
In addition I find impossible we both have missed the first variant on the actual list that is a de novo frameshift variant.

The question is what were we looking at on may  12th and 15th? I did not take out an analysis report (bad of me!!!).

Michela

________________________________
Från: Daniel Nilsson <notifications@github.com>
Skickat: den 22 maj 2020 11:20
Till: Clinical-Genomics/scout <scout@noreply.github.com>
Kopia: Michela Barbaro <michela.barbaro@sll.se>; Author <author@noreply.github.com>
Ämne: Re: [Clinical-Genomics/scout] fam 19081 inactive, not re-runned? (#1929)


There are several small things combining here I think, but an issue it becomes and we are grateful that you report it!

First line of asking about the delivery report is normally a ticket to production, but I can ask since we are here. From what I can see, there was only one rerun this year, which was completed on 2020-05-19, and uploaded two days later.

The delivery reports have not been generated from CG for this case since the first rerun - or at least not added to Housekeeper and the Scout load config. That is clearly an issue - either a manual routine or a software issue! We can forward this to CG if we don't get a good answer!

As for the original issue with new variants, this will involve a bit too much personal data to post in detail on the web, but from looking at a few of the "new" top candidates, I would guess this is mostly due to changes in the rank model. The new top ones are indels (that we have worked to give higher scores), or variants that do not conform to the inheritance models (that are relatively less penalised now). Have a look again and tell me what you think. If you still find strange variants in there that should have been there before, we can have a look or forward this to GenMod or MIP for a second opinion.

**Comment by dnil** [comment]
Ok, I hear you - but don’t see a Scout issue to fix here.

I didn’t get a reply on the local chat - possibly some national hollidays underway? ;) The Scout DBbshows four reruns, only the recent one this year, same with Housekeeper. I would suggest sending a ticket to the support system. Someone may remember or have an entry in Statusdb/Trailblazer about something out of the ordinary with this case! I’ll close this for now, but let’s reopen if we get more info and it pointa towards some kind of bug. Thank you for reporting!

**Comment by northwestwitch** [comment]
@4WGH I've also replied to your ticket on support system. I've checked today and the newest delivery report is available:
 
![image](https://user-images.githubusercontent.com/28093618/84137335-d837e680-aa4c-11ea-9df6-27de21293556.png)

This case has 4 analyses and only 2 delivery reports. I don't think the missing two reports were ever present for this case, see database:

![image](https://user-images.githubusercontent.com/28093618/84137476-0ae1df00-aa4d-11ea-952f-e8230ebe628b.png)

**Comment by 4WGH** [comment]
but they should 🙂


Michela
________________________________
Från: Chiara Rasi <notifications@github.com>
Skickat: den 9 juni 2020 12:31
Till: Clinical-Genomics/scout <scout@noreply.github.com>
Kopia: Michela Barbaro <michela.barbaro@sll.se>; Mention <mention@noreply.github.com>
Ämne: Re: [Clinical-Genomics/scout] fam 19081 inactive, not re-runned? (#1929)


@4WGH<https://github.com/4WGH> I've also replied to your ticket on support system. I've checked today and the newest delivery report is available:

[image]<https://user-images.githubusercontent.com/28093618/84137335-d837e680-aa4c-11ea-9df6-27de21293556.png>

This case has 4 analyses and only 2 delivery reports. I don't think the missing two reports were ever present for this case, see database:

[image]<https://user-images.githubusercontent.com/28093618/84137476-0ae1df00-aa4d-11ea-952f-e8230ebe628b.png>
