### ISSUE TITLE
Mouse over for dismissed variants

### ISSUE THREAD

**Issue by TJO-Lund** [Clinical-Genomics/scout#1939]
On variant-pages "Clinical SNV and INDELS" and "Clinical structural variants" dismissed variants are marked with grey color. Is it possible to incorporate Mouse-over (like we have for Comments) so that it can easily be seen which frase/frases that have been used to dismiss each variant?
This would save some time in subsequent steps in our workflow in Lund as it would no longer be neccessary to open a variantpage to see which frases were used.

**Comment by dnil** [comment]
Sure! Have you seen the corresponding research page clinical sneak-peek-view, with a badge and hover? Compare PR #1558. Perhaps we should enable this also for the clinical view?

**Comment by TJO-Lund** [comment]
Sounds good and this is what I had in mind. How can it be implemeneted?

**Comment by dnil** [comment]
If you want to take a look, there are functions for this called from the variants view controller. They are currently only geared towards populating a "clinical_assessments" entity for the research case view, and then another set populate "evaluations" for the clinical view. It would be very possible to connect the two. Easy to intermediate somewhere..
