### ISSUE TITLE
[Feature request] Hover text on Variant list columns

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/scout#1940]
Some columns in Variant list are quite self explanatory, but there are some that don't say exactly what each value means. Example: Tumor column in cancer-view. It shows AF on top, then alt allele count separated by `|`  and reference allele count.

It'd be nice to discuss whether or not to show these values when hover mouse over it.

**Comment by dnil** [comment]
Yep! And does connect to #1941 and #1937 - it makes me a little nervous to see fractions, counts and % mixed on the same page.
