### ISSUE TITLE
Update phenotypes after new HPO release (2020-06-08)

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#1955]
https://github.com/obophenotype/human-phenotype-ontology/releases/tag/v2020-06-08

From today, check that phenotype parsing still works.

Checklist of commands to to be verified:

- [x] `scout setup database --api-key working_api_key`
- [x] `scout update genes --api-key working_api_key`
- [x] `scout update diseases --api-key working_api_key`
- [x] `scout update omim --institute cust000 --api-key working_api_key`
- [x]  `scout download everything --api-key working_api_key` (should download `hpo.obo`, `phenotype_to_genes.txt`, `genes_to_phenotype.txt` + the other usual files)
- [x] `scout download hpo` should download `hpo.obo`, `phenotype_to_genes.txt`, `genes_to_phenotype.txt`
- [x] `scout download omim --api-key working_api_key` should download `genemap2.txt`, `mim2genes.txt`, `phenotype_to_genes.txt`

**Comment by dnil** [comment]
It's that time again.. 😅

**Comment by northwestwitch** [comment]
> It's that time again.. 😅

Yes!

**Comment by northwestwitch** [comment]
Oh no, the very first test is failing!

scout setup database --api-key working_api_key

![image](https://user-images.githubusercontent.com/28093618/84022183-1e764280-a986-11ea-9763-36ed7395667c.png)

**Comment by northwestwitch** [comment]
Let's hope that the OMIM key is expired and we don't have to fix the parsing!

**Comment by dnil** [comment]
Nailbiter, but either way likely sth to fix. We should fail earlier if this is a key issue.. 😊

**Comment by northwestwitch** [comment]
It's the key!!!! I was using an expired one. Tested with another and first command works! 😀 

![image](https://user-images.githubusercontent.com/28093618/84023375-449ce200-a988-11ea-91bd-cd3ba3446c23.png)

**Comment by northwestwitch** [comment]
Ok. I'll continue with the checklist. When my key is rejected I'll use the one of @moonso 😎

**Comment by northwestwitch** [comment]
scout update genes --api-key working_api_key: 🆗 

![image](https://user-images.githubusercontent.com/28093618/84023969-5337c900-a989-11ea-9cc6-843a5fa1f25f.png)

**Comment by northwestwitch** [comment]
Looks like the command `scout download everything --api-key working_api_key` is not working. tested with 2 different OMIM keys, (mine and Måns) and it gives the same error:

![image](https://user-images.githubusercontent.com/28093618/84030348-31900f00-a994-11ea-8734-4da1dde114a9.png)

**Comment by northwestwitch** [comment]
`scout download hpo` works 🆗 (it doesn't require the use of the OMIM key):

![image](https://user-images.githubusercontent.com/28093618/84030677-b844ec00-a994-11ea-8044-8befbabfbdef.png)

`scout download omim --api-key working_api_key` is also working 🆗 

![image](https://user-images.githubusercontent.com/28093618/84030991-35706100-a995-11ea-9940-39fb766c1d8d.png)

**Comment by northwestwitch** [comment]
The "download everything" command was fixed by #1958. I'm going to rename this issue to "update HPO", so we remember that we have to update the phenotypes in Scout prod (and stage)

**Comment by dnil** [comment]
Either when testing https://github.com/Clinical-Genomics/servers/pull/366 or next release deploy perhaps?

**Comment by henrikstranneheim** [comment]
I will be happy to test this in the servers PR. Hoping to manage that later this week (thursday/friday)

**Comment by northwestwitch** [comment]
> I will be happy to test this in the servers PR. Hoping to manage that later this week (thursday/friday)

We have to ask production team when it's a good time for them

**Comment by northwestwitch** [comment]
To be done after fixing this: https://github.com/Clinical-Genomics/servers/issues/375

**Comment by northwestwitch** [comment]
I'm still waiting to get a new OMIM key. Today I've sent them a reminder, let's hope someone replies before the end of next week, before I really want to update Scout definitions before the beginning of my vacations.

**Comment by northwestwitch** [comment]
Updating phenotypes and all today in the afternoon!

**Comment by northwestwitch** [comment]
Updated genes, diseases and OMIM right now. It went well for all 3. Closing this issue now.
