### ISSUE TITLE
Push and pull conflicts in the same branch caused by github actions

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#1960]
The current situation is very annoying:
- You work on a branch and push the commit changes to remote on github.
- Github actions (black) reformat and modify the remote
- in the meanwhile you work some more locally
- When you push your local changes to remote it tells you that you have to pull first
- You pull and get a ton of conflicts to fix (with you own branch!!)

This is super annoying and must be fixed.

**Comment by dnil** [comment]
Agree in principle! So you still see this after the merge of #1948 when using the pre-commit hook? I got the feeling mine relaxed after that, but I have only made a small number of commits to PRs so can't say I know.

**Comment by northwestwitch** [comment]
Yes, unfortunately 😢

**Comment by northwestwitch** [comment]
The problem is that if there is even a slight change (for instance a new lines) between your local and the remote (reformatted by the actions), then you have to merge conflicts in huge chunks of code that you modified on your local.

**Comment by dnil** [comment]
The thing I don't get is why you would get these big differences in the first place? Assuming line length and black release version is now aligned, the situation you describe is when you touched code that still has an old version of either between the two pushes. Or is there something else at play? One suggestion to solve it if that is the case would be a re-black of the whole code again to reset what has been altered by the old pre-commit hook settings - or perhaps missed the first time around.

**Comment by northwestwitch** [comment]
In general I don't get so many differences but perhaps it's because I'm doing extensive refactoring in the PR I'm working at. Let's see

**Comment by dnil** [comment]
Hm, I still think I'm missing a piece of the puzzle. You could get conflicts against your actual own work, if that has changed substantially since last push, but you should only get that in case the black magic actions jumped in. The way we have it rigged now, it is only supposed to happen if the file was not blacked prior to first push? Lets keep this open and collect incidents when this happened perhaps?

**Comment by northwestwitch** [comment]
Haven't had this problem in a while, so I'm going to close this issue!

**Comment by dnil** [comment]
There appears to be some kind of loophole that can trigger it; it happened once last week for me. But as long as it is rare it doesn't really matter much. Let's reopen if it returns.
