### ISSUE TITLE
general report- pdf not working well

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#1974]
in fam 20101

the online page look like this (the table goes slightly outside the margin
![bild](https://user-images.githubusercontent.com/12525201/85690752-2c40fd00-b6d4-11ea-8a16-3bb9806560c2.png)

the pdf format is even worse. EDIT - try for yourself.

**Comment by dnil** [comment]
Can you supply browser version and operating system? Did you use any unusual screen or window size?

It looks good on my end, but that's also an N=1. 😸

<img width="852" alt="Screenshot 2020-06-25 at 11 13 29" src="https://user-images.githubusercontent.com/758570/85691662-fea88380-b6d4-11ea-8bd4-2bce02e143df.png">

**Comment by dnil** [comment]
But, yeah, the pdf is not in a good state. At least a local lib issue. Let's check and see if it affects more reports, and if it persists in different envs. Thanks!

**Comment by dnil** [comment]
It is perhaps not my place to make the judgement between patient confidentiality and urgency of this issue, but may I suggest again that you provide either a toy example or send reports such as this, that lean more towards the Solna instance, as tickets to the support system. This is free to read for all of Internet.

**Comment by 4WGH** [comment]
good point!!!! 
thanks
How can I remove the pdf?

**Comment by dnil** [comment]
Fixed! 😊

**Comment by 4WGH** [comment]
the browser is Firefox, no idea how to check version
Window 7 operating system

**Comment by northwestwitch** [comment]
PDF version looks ugly also on Chrome. I strongly suspect it's this long list of genes, separated by commas but no space that might be cause it.

![image](https://user-images.githubusercontent.com/28093618/85694859-ce161900-b6d7-11ea-8ee1-1bda8af2349c.png)

**Comment by dnil** [comment]
Generally you will find versions on GUI tools by selecting the "About" menu item. LabIT can help you upgrade if you have been left behind on updates (mine is on 77.0.1; I know someone @ klingen (HM?) had an issue with her Firefox not beeing kept up to date.. Leave an issue in Navet, or go find your friendly neighbour sysadmin.

**Comment by dnil** [comment]
And yeah, I think you are right @northwestwitch; the minimum width calculation could be based on word wrapping and not deal with long strings. Probably that then allows the family info to escape its bounding box, and not wrap on the "-" in the individual ids since there is suddenly some other item. That could definitely happen in latex, and I suspect the layout algorithm is similar: who wouldn't copy Knuth?

**Comment by dnil** [comment]
Right - fingers crossed!

No me neither, but his craft is solid. Still going strong at  10001 base 3 with updating his The Art of Computer Programming (https://sv.m.wikipedia.org/wiki/The_Art_of_Computer_Programming) it seems, although nowadays more people refer to StackOverflow than it. 😄

**Comment by northwestwitch** [comment]
> nowadays more people refer to StackOverflow than it

Yeah I wonder why.. 😆 Anyway, the only complicated thing is to understand where to introduces spaces in users comment whenever they write a stream of consciousness.. I'll try to fix something

**Comment by dnil** [comment]
StackOverflow lists e.g. CSS "word-wrap: break-word;" and "overflow-wrap: break-word". I suppose the question becomes which ones the pdf renderer (and possibly our favourite browsers) support?

**Comment by northwestwitch** [comment]
I was thinking introduce a space after every comma, whenever the space is missing. That way the text gets distributed over multiple lines. The only situation this is not working is where there is a super long unique word non separated by spaces

**Comment by northwestwitch** [comment]
The problem I'm seeing in the code is that we have to fix not only the comments from cases, but also those from the variants, because the same thing could happen there as well.

**Comment by dnil** [comment]
Yep. If the text areas would get either of those classes in css, at least for the reports, that might be it, conditions as above.

**Comment by dnil** [comment]
https://www.techrepublic.com/blog/web-designer/css3-new-properties-for-text-overflow-and-text-wrap/
> "Word-wrap is probably not going to be the most widely used CSS3 property but it definitely has a practical use, for example, in controlling the styling of comment sections within blog posts or forms."

**Comment by northwestwitch** [comment]
I've drafted a fix, jinja-style

**Comment by northwestwitch** [comment]
> https://www.techrepublic.com/blog/web-designer/css3-new-properties-for-text-overflow-and-text-wrap/

I'm open to this solution as long as it doesn't cut the words in the sentence

**Comment by dnil** [comment]
I noticed while testing out that also the regular layout is somewhat sensitive to this. Try adding a very long word into comment boxes etc. *cringe*

**Comment by northwestwitch** [comment]
> also the regular layout is somewhat sensitive to this

I know, I was pretending everything was fine! 😄

**Comment by dnil** [comment]
bootstrap has a class text-break that deals with this (adding browser specific word-break css) 
https://getbootstrap.com/docs/4.3/utilities/text/#word-break

**Comment by dnil** [comment]
One could just add text-break to the comment displaying boxes, and be done?

**Comment by northwestwitch** [comment]
Yes, let's try!

**Comment by northwestwitch** [comment]
Looks like the text-break works fine!
![image](https://user-images.githubusercontent.com/28093618/85725110-1a238680-b6f5-11ea-868b-8a303fae113e.png)

**Comment by dnil** [comment]
Yes, it works like a charm for the main pages. And the comments box is just one component in the global utils, so a one-liner. Then there's the report.

**Comment by dnil** [comment]
Before:
<img width="683" alt="Screenshot 2020-06-25 at 15 03 02" src="https://user-images.githubusercontent.com/758570/85725302-47703480-b6f5-11ea-9db9-7767a18a52a6.png">
After:
<img width="1566" alt="Screenshot 2020-06-25 at 15 03 12" src="https://user-images.githubusercontent.com/758570/85725297-46d79e00-b6f5-11ea-8314-3fdd6d1b8232.png">
😄

**Comment by dnil** [comment]
Yes!
<img width="970" alt="Screenshot 2020-06-25 at 15 08 22" src="https://user-images.githubusercontent.com/758570/85725853-ce251180-b6f5-11ea-8719-ce89619fa797.png">

**Comment by northwestwitch** [comment]
I bet who writes a comment like that @dnil would also have a diagnosis..

**Comment by dnil** [comment]
🤣 Most likely..

**Comment by dnil** [comment]
And thanks - I really like this way better! Starting to edit the input feels a little risky. This will be nicely supportive of different screen sizes, long words and what not.

**Comment by northwestwitch** [comment]
> I really like this way better!

Me too! Thank you!
