### ISSUE TITLE
Rankscore is not displayed

### ISSUE THREAD

**Issue by 47KW** [Clinical-Genomics/scout#1980]
https://scout.scilifelab.se/cust002/F0035200/variants

**Comment by northwestwitch** [comment]
Oh no! Could be that the case was loaded even if the pipeline was not running until the end? I'll check with production team. Let's hope it's an isolated case! Thanks!

**Comment by northwestwitch** [comment]
I saw that you opened a ticket in our support system. Since it's going to be rerun I'm closing this issue. We can reopen if it still looks weird afterwards!

**Comment by 47KW** [comment]
Great,
It was explained to me as a consequence of us labelling the case as unknown rather than affected.

/ Håkan

Från: Chiara Rasi <notifications@github.com>
Skickat: den 3 juli 2020 09:04
Till: Clinical-Genomics/scout <scout@noreply.github.com>
Kopia: Håkan Thonberg <hakan.thonberg@sll.se>; Author <author@noreply.github.com>
Ämne: Re: [Clinical-Genomics/scout] Rankscore is not displayed (#1980)


I saw that you opened a ticket in our support system. Since it's going to be rerun I'm closing this issue. We can reopen if it still looks weird afterwards!

**Comment by northwestwitch** [comment]
> It was explained to me as a consequence of us labelling the case as unknown rather than affected.

Ah OK! It totally makes sense!
