### ISSUE TITLE
gene not found when we want to add a panel - URGENT

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#1986]
this the massage
![image](https://user-images.githubusercontent.com/12525201/87135619-9348df00-c29a-11ea-8c6f-99f4adf5a812.png)

the gene is in HGNC
https://www.genenames.org/tools/search/#!/all?query=NOTCH2NLC

what to do?

**Comment by northwestwitch** [comment]
Hi!

Looks like we have just one version of this gene in Scout, the one from build 38:
 
![image](https://user-images.githubusercontent.com/28093618/87137242-e2900f00-c29c-11ea-8423-a3f91290b8cc.png)

I'll see what can be done, but unfortunately I don't think we can have a fix today.

**Comment by northwestwitch** [comment]
I think the main problem here is that the genes in the database are taken from Ensembl. This gene is in Ensembl in genome build 38, but it's missing in build 37. Here's its page: https://www.ensembl.org/Homo_sapiens/Gene/Summary?db=core;g=ENSG00000286219;r=1:149390614-149468030, where is says `Stable ID ENSG00000286219 not present in GRCh37.`

I don't know how to fix this, any idea @moonso ?

**Comment by dnil** [comment]
Cheers from vacation! Its poorly represented on 37. We eg had to skip the known repeat expansion in it for 37, and only run it for 38.

**Comment by 4WGH** [comment]
I think we can survive without it for now.
But it would be good to discuss this issue after summer.
We were mainly interested in the repat expansion on this gene.

I will not add to v16 of IEM




________________________________
Från: Daniel Nilsson <notifications@github.com>
Skickat: den 10 juli 2020 11:29
Till: Clinical-Genomics/scout <scout@noreply.github.com>
Kopia: Michela Barbaro <michela.barbaro@sll.se>; Author <author@noreply.github.com>
Ämne: Re: [Clinical-Genomics/scout] gene not found when we want to add a panel - URGENT (#1986)


Cheers from vacation! Its poorly represented on 37. We eg had to skip the known repeat expansion in it for 37, and only run it for 38.

**Comment by northwestwitch** [comment]
A workaround would be implementing panels containing custom regions: #1907. Or switching to genome build 38.

**Comment by dnil** [comment]
Sounds wise. The repeat expansion locus is not really in the 37 sequence. It should however work fine out of the box when we switch to 38. I also would not generally trust any variant in the gene on 37 without careful analysis, given the state of the assembly with that gene family family/pseudo gene, even if we were to force load them from that region.

**Comment by moonso** [comment]
The switch to 38 will most definitely happen during 2020 so I think we can close this issue
