### ISSUE TITLE
question about local observations

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#1988]
![image](https://user-images.githubusercontent.com/12525201/87179801-a16d1e80-c2df-11ea-8404-d1c99a727d02.png)

If I look at this variant, identified in a case runned in 2019

I see that there is a 1  also in the archive 2017-05-31

Does it mean there should be one more case with this variant? in addition to the one analyzed in 2019?

**Comment by henrikstranneheim** [comment]
No, it should be the same variant I.e only found once.

**Comment by 4WGH** [comment]
ok, thank for the answer.

Could you give  (probably again, but nobody remember here) the difference between the "local obsevations" and the "local observation (archive 2017-05-31).

By your abswer we understand we misinterpret it.



Michela
________________________________
Från: Henrik Stranneheim <notifications@github.com>
Skickat: den 10 juli 2020 20:06
Till: Clinical-Genomics/scout <scout@noreply.github.com>
Kopia: Michela Barbaro <michela.barbaro@sll.se>; Author <author@noreply.github.com>
Ämne: Re: [Clinical-Genomics/scout] question about local observations (#1988)


No, it should be the same variant I.e only found once.

**Comment by henrikstranneheim** [comment]
They are both part of the same loqus database. The archive is an export of the loqus database at a certain time interval (Scout is actually showing the wrong date and number of cases for the archive - but let's ignore this right now). The archived version is used in the rank model with genmod and MIP. The "local observation" is incrementally updated with an affected sample every time a new case is analysed and uploaded to Scout. The archive thus does not hold all available observation counts, but a subset present at the time point of the export.
