### ISSUE TITLE
Filter using public databases

### ISSUE THREAD

**Issue by EmmTha** [Clinical-Genomics/scout#2003]
Balsamic used 2020-08-01
PROBLEM: In balsamic there is available data on population allele frequencies from  1000G, ExAc, local observations, but to get gnomAD data I need to click to the gnoMAD site (i.e. it does not look like any allele frequencies are stored in SCOUT). However, when I filter in balsamic data, I can only use "gnomAD" (same as MIP), but this is rather useless as many many variants come up in the list with gnomAD AF as high as 50% and many have high ExAc/100G/local obs. 

SOLUTION: Add filter based on local observations and ExAc/100G

**Comment by dnil** [comment]
Ok, could we have a list of current frequencies and archived local obs present on BALSAMIC cases and the key to the most authoritative (gnomAD, likely?) you would like the frequency filter to act on, and we should be able to change the cancer filter query to act on that without further ado!

**Comment by hassanfa** [comment]
Frequencies are from VEP annotation: https://www.ensembl.org/info/docs/tools/vep/vep_formats.html#other_fields 

I can't find ExAc there, but 1kg is there. We already have a pop. freq. in filters, maybe this filter can be a bit more descriptive?

**Comment by dnil** [comment]
GnomAD filter for somatic variants exists and seem to be loading stably; perhaps just a legacy/leftover issue? Closing this for now, but feel free to reopen if I got it backwards!
