### ISSUE TITLE
Dismiss variants

### ISSUE THREAD

**Issue by EmmTha** [Clinical-Genomics/scout#2004]
Balsamic accessed 2020-08-01

PROBLEM: In order to dismiss a variant, I need to open the variant page and select dismiss variant

FUTURE DEVELOPMENT?: In the future, would it be possible to dismiss a variant directly in the first interface (i.e. variant list), without opening the variant page? For some, I can see directly when I hold the cursor over the “ExAc” column that they are too common to be true cancer variants and would like to dismiss them directly without having to wait for the variant page to open.

**Comment by elevu** [comment]
Hi @EmmTha , thank you for the feedback! 
We added this feature to Scout, from the next release it will be possible to dismiss a variant directly from the list.
