### ISSUE TITLE
"The Panel" as default

### ISSUE THREAD

**Issue by EmmTha** [Clinical-Genomics/scout#2005]
Balsamic accessed 2020-08-01

POSSIBLE BUG?: When I use balsamic, "The Panel" is selected as default. It is very unclear to me what "the Panel" is. 

SOLUTION: As I guess that most times we use the GMCK solid panel, perhaps this could be default?. 
Even better if in addition, different cancer panels could be selected as a drop down list (GMCK panel and MSKI and then others as we add them perhaps leukemia SNV/SV, sarcoma...)

**Comment by dnil** [comment]
For the rare disorders we preselect the desired default panel in the Orderportal (CGweb), which is then propagated to Scout via the case input files. For most orders, this is one of a small set of clinical panels that are always run with MIP each time.

From my point of view there is nothing preventing Balsamic from claiming to have run with any number of panels when presenting a case for loading, e.g. GMCK Solid as default, but with any number of the other cancer panels marked as analysed. Then this would automagically appear in Scout. How does that sound to you @hassanfa? Its a matter of updating the load config yaml.

There are other ways as well, including but not limited to allowing arbitrary gene lists in Scout, which has its pros and cons. The most obvious con then being that we cannot at that stage guarantee that the gene was actually included in the analysis.

**Comment by hassanfa** [comment]
Desired default panel in order portal works just fine. However, this also related to #1637 and seems to be a popular feature to request.

List of genes to include in config.yaml is not an issue. Do you by any chance know how we add gene panels to our cg+scout+cgweb ecosystem? Do we use cg to do so? Maybe @henrikstranneheim knows more about this.

**Comment by henrikstranneheim** [comment]
Panels are defined, stored and updated in Scout. Cg queries scout to get the most updated ones and hands them over to the next application

**Comment by hassanfa** [comment]
but how does orderportal knows about Scout panels?

**Comment by henrikstranneheim** [comment]
I guess @patrikgrenfeldt should know best

**Comment by patrikgrenfeldt** [comment]
The orderportal curently has a table of panels, this table needs to be updated whenever there is a new panel that we want to include.

**Comment by henrikstranneheim** [comment]
Not related to scout but I think we should write down the procedure to add a new panel to the system at clinical genomics in atlas.

**Comment by dnil** [comment]
If it is somehow difficult in cg we *could* make it a part of Scout, say by allowing the users to flag which of the panels are to be possible to order, and have an option to the panel export command that allows cg to request only them.
