### ISSUE TITLE
Institute page is not scaling to full page

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/scout#2019]
Institute page does not show properly. I don't know how to explain it 😁 , screenshot shows what I mean:
![image](https://user-images.githubusercontent.com/1086877/90631262-b1531900-e222-11ea-8ed9-8aa23dea1f94.png)

Half of the page is empty, and there is a scroller on the side which doesn't extend to full page.

**Comment by elevu** [comment]
Fixed with the next release
