### ISSUE TITLE
Overview/gene_variants Times Out

### ISSUE THREAD

**Issue by mikaell** [Clinical-Genomics/scout#2020]
Enter a search term in <HGNC Symbols> that does not exist in the database, click Filter Variants, the server will timeout and return 504 "Gateway Time-out".

**Comment by dnil** [comment]
Oops, that was not intended! But more precisely what kind of search term? 😊 

Missing enes appears covered with a flash, and the rest return quickly on local - I suppose one or the other is not well indexed on prod. Also, going outside the partial index immediately causes a slowdown in search large enough that this would certainly happen. We have tried to guard against that a bit with conditions on the searches, but it may still be possible!
