### ISSUE TITLE
Saved filters fail to load and throw an error.

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/scout#2021]
Scout version: 4.19
Tested on Stage, Scout version: 4.20

Saved filters do not work and it throws a weird error:

![image](https://user-images.githubusercontent.com/1086877/90635892-15c5a680-e22a-11ea-949b-f0e37cb53171.png)

test case (it is not a patient sample):
https://scout.scilifelab.se/cust087/calmpuma/cancer/variants?expand_search=True

**Comment by hassanfa** [comment]
Error: `Content of field 'csrf_token' has not a valid format`

**Comment by dnil** [comment]
Thanks! Looks like it works for RD: we'll check!

**Comment by northwestwitch** [comment]
It's probably only in cancer variants, because that form is validated. Rare case variants form is not yet validated upon submission. Must be fixed anyway.
