### ISSUE TITLE
Comments return to anchor?

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#2024]
Commenting does not always return to anchor, possibly because of an issue with the reuse of the card. Would be nice of one does not have to scroll all the way back down again.

**Comment by elevu** [comment]
Would you like the view to return to the comment panel after a comment is submitted?

**Comment by dnil** [comment]
Yes; especially nice for the actions that happen far down on a page, and that are potentially not the last thing happening with that particular variant/case.

**Comment by elevu** [comment]
Done on https://github.com/Clinical-Genomics/scout/pull/2132
