### ISSUE TITLE
Feature Request: Scout support for reporting multiple types of analyses

### ISSUE THREAD

**Issue by Mropat** [Clinical-Genomics/scout#2035]
Hello!

Sometimes a situation does arise, when we are requested to upload different types of analysis for the same case (MIP+BALSAMIC, _MIP DNA+RNA?_). 
The current Scout behavior is to overwrite the report with the latest uploaded one. The workaround currently, is to manually check whether a report for a different analysis has been uploaded already, and create a report with modified case id. This however, complicates automating the Scout delivery for BALSAMIC. 

The solution I'd like to see, is for Scout to be able to distinguish between different report types on upload, and not overwrite the reports generated from different analyses. The customer ideally should be able to have a separate rare disease and cancer view.

**Comment by henrikstranneheim** [comment]
This has been handled upstream of Scout, with the new grouping functionality and can be handled by extending the `scout case update` cmd even more. 

I will close this one. Please reopen if you disagree or open a more specific issue with further suggestions on how to improve this.
