### ISSUE TITLE
15067

### ISSUE THREAD

**Issue by nicolelesko** [Clinical-Genomics/scout#205]
Cannot perform a HPO search in this family.  Research list of variants is open, does this have anything to do with the problem?

**Comment by robinandeer** [comment]
Hi,

we are gonna improve this soon but the error comes from the HPO id that is annotated for that case: `HPO:0003198 `

It should say `HP:0003198` (lose the "O") - apparently we aren't doing any sanity checks there :P

Delete the old entry and add the correct ID and it should work!
