### ISSUE TITLE
Wrong panels

### ISSUE THREAD

**Issue by 47KW** [Clinical-Genomics/scout#2052]
https://scout.scilifelab.se/cust002/F0035835
looks like something is wrong with associations between customers (Clinics) and the genpanels...
For this case, I can only choose a panel that was created for another customer Geriatrik/Thonberg Cust054?

**Comment by northwestwitch** [comment]
This is likely an error that happened at the moment the scout upload file was created, moving it to cg : https://github.com/Clinical-Genomics/cg/issues/718

**Comment by 47KW** [comment]
the same applies to case "actualpig"
F0035200

**Comment by northwestwitch** [comment]
Oh no! We'll fix asap!

**Comment by dnil** [comment]
Perhaps an inexperienced customer (me) checking "ND" as the panel when ordering, rather than whatever the clinical genetics Neurodeg panel "NEURODEG"? 😊

**Comment by dnil** [comment]
Thanks @northwestwitch - and sorry @47KW! Perhaps we could consider retiring the ND list from the order portal options by now?

**Comment by northwestwitch** [comment]
Ah ok! I got scared because lately we changed the file of the panel master list and the timing of this error was just perfect..

**Comment by dnil** [comment]
May still be worth checking that it was NEURODEG that made it there rather than ND then, but at least this seems plausible to me. 😊

**Comment by 47KW** [comment]
I favour that explaination

Från: Daniel Nilsson <notifications@github.com>
Skickat: den 27 augusti 2020 13:58
Till: Clinical-Genomics/scout <scout@noreply.github.com>
Kopia: Håkan Thonberg <hakan.thonberg@sll.se>; Author <author@noreply.github.com>
Ämne: Re: [Clinical-Genomics/scout] Wrong panels (#2052)


Perhaps an inexperienced customer (me) checking "ND" as the panel when ordering, rather than whatever the clinical genetics Neurodeg panel "NEURODEG"? 😊

**Comment by 47KW** [comment]
Perfect timing of an error!

*lol*

Från: Chiara Rasi <notifications@github.com>
Skickat: den 27 augusti 2020 14:03
Till: Clinical-Genomics/scout <scout@noreply.github.com>
Kopia: Håkan Thonberg <hakan.thonberg@sll.se>; Mention <mention@noreply.github.com>
Ämne: Re: [Clinical-Genomics/scout] Wrong panels (#2052)


Ah ok! I got scared because lately we changed the file of the panel master list and the timing of this error was just perfect..

**Comment by 47KW** [comment]
I think you should remove that old panel if its still in Clinical Genetics list, yes!


Från: Daniel Nilsson <notifications@github.com>
Skickat: den 27 augusti 2020 14:04
Till: Clinical-Genomics/scout <scout@noreply.github.com>
Kopia: Håkan Thonberg <hakan.thonberg@sll.se>; Mention <mention@noreply.github.com>
Ämne: Re: [Clinical-Genomics/scout] Wrong panels (#2052)


May still be worth checking that it was NEURODEG that made it there rather than ND then, but at least this seems plausible to me. 😊

**Comment by dnil** [comment]
👍 Good. We don't want to remove it from Scout, since that would interfere with looking at old case, but it should be hidden in Orderportalen / CG-web.
