### ISSUE TITLE
How are case pedigree figures generated?

### ISSUE THREAD

**Issue by andreaswallberg** [Clinical-Genomics/scout#2053]
Dear developers,

I wonder if pedigree figures are normally generated automatically from the info in the case config yaml file or built externally with Madeline (by hand or an interpreter?) and side-loaded along with the rest of the data.

The 643594 example makes it seem like the pedigree is static and loaded with the case.

**Comment by northwestwitch** [comment]
Hi, yes you figured it out right: pedigrees are generated externally and the link to these xml files is provided in the config file used to upload the case.
How you create these files is really up to you. They're created by some other software as part of our pipeline, but you can create them also manually using Madeline 2.
