### ISSUE TITLE
Reintroduce branch status check for PRs

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#2063]
Due to some changes in the settings we don't have any more the "Require branches to be up-to-date before merging" option for the PRs:

![image](https://user-images.githubusercontent.com/28093618/91975596-ee89d180-ed1f-11ea-83bc-0b7cdacb6693.png)

Was the option removed for any specific reason? I'd like to reintroduce it but I can't because I'm not admin. @moonso or @dnil ?

**Comment by dnil** [comment]
I agree - I thought them fairly handy, and it also helped ensure testing procedures since one always tests the latest merge candidate rather than just the branch. As it is now we only get the conflict notices from github. I
You can always do it from the CLI if you wish - just merge master into the branch - but it is very easy to forget or ignore.

I think only @moonso is admin?

**Comment by moonso** [comment]
I'll add that back. Might be me who removed it for some reason...

**Comment by northwestwitch** [comment]
Thanks!

**Comment by dnil** [comment]
Looks good! Thank you!

**Comment by northwestwitch** [comment]
Very good with the option to refresh the branch, but there's a couple of things that are still cumbersome:
- Merging is possible only if coveralls passes
- Another review is required if code changes after an approving review.

In the first case we might need to merge and deploy fast when we have a bug, and in this situation we don't care much about the coverage. Second case is also a problem because we often update the changelog immediately before merging, and after the review. Sorry I didn't think about it yesterday!

Could you help fixing this @moonso ?

**Comment by moonso** [comment]
Fixed!

BTW I added this Action to CG: https://github.com/marketplace/actions/changelog-enforcer
It's really nice with a reminder to upload the changelog

**Comment by northwestwitch** [comment]
Thank you! 🙏

**Comment by dnil** [comment]
Skip-Changelog ftw! 😉 

Seriously, good idea!
