### ISSUE TITLE
SV variants table header labels..

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#2064]
At some point after 4.19 the SV variants labels broke slightly for current master; perhaps when fixing dismiss variants? Missing Score I suppose.

![Screenshot 2020-09-02 at 17 25 56](https://user-images.githubusercontent.com/758570/92003690-a085c580-ed41-11ea-8c84-ad0e5ca28545.png)

**Comment by northwestwitch** [comment]
Good catch, I didn't realize when reviewing!

**Comment by elevu** [comment]
oohh, saw this issue today since I realised I didn't enable new issue notification. I will fix it tomorrow!

**Comment by northwestwitch** [comment]
This was fixed by #2071. Closing
