### ISSUE TITLE
Pagination: previous

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#2067]
Especially for cancer, but hey, why not generally. See https://github.com/Clinical-Genomics/scout/issues/2047

**Comment by heronikdin** [comment]
The problem for cancer view is that we do not have a ranking system yet as the RD Group, and we often need to go back and forth from all the variants observed. In general for cancer view, we have between 5-10 variants for each case which are causative, so the list is already long.

**Comment by hassanfa** [comment]
Also to add this, pre-filtering for cancer cases is improving and number of variants dropped compared to previous releases of BALSAMIC.

But with filters working again for cancer samples, this should be easier.
