### ISSUE TITLE
Highlight panel matching genes in variants gene column

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#2068]
>For some samples there are many genes in the variant list. It is very hard to distinguish if a variant is true or not if there >are so many genes within one column. I have discussed this with Hassan, and apparently there are some transcript errors >causing this. Is there any way to come around this problem? (ex: "bossponge variant nr 1126).

Fairly sure this happens already before Scout loading, and likely in VEP so hard for us to control. But, we could perhaps try to highlight the genes that were on the panel and caused the variant to show?

Current situation:
![Screenshot 2020-09-03 at 16 41 25](https://user-images.githubusercontent.com/758570/92129894-63363c00-ee04-11ea-82f8-6feb3509d35d.png)

How about either **boldfacing** or just showing matching genes plus an ellipsis, much like for the SV view?

**Comment by heronikdin** [comment]
Boldfacing would be good, I am not sure how the SV view looks like? Are there any examples easy to show?
