### ISSUE TITLE
removal of dismissed variants 

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#2073]
Can we have a botton to clear up the dismissed variants?

Ex. I start dismissing variant in a case, and for any reason I want to start again. Or someelse had look at the case and I want to do it again from scratch. Or we forgotten to ask to remove the dismissed variants when we ordered a re-run. Or we orderer a re-run in scout instreasd of making a ticket.

Without the need to re-run the case 👍  just pressind a botton

**Comment by elevu** [comment]
I can take this one!
