### ISSUE TITLE
A strategy to investigate remissions and relapses

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/scout#2075]
In cancer case we will have remissions and relapses ( of course reruns see #2072 is also related ). The idea is to help users with the ability to track between these two states.

As a user the following questions are the ones I'd like to be able to answer when encountering a remission/relapse analysis:
1. Persistent information between reuploads, see #2072 
1. Are my pinned variants still there? What's the difference if they are still there?
1. Compare between old pinned variant and new pinned variant. Is this just some export variant functionality. Exporting variants in Excel is already implemented, possibility to compare between two exports?
1. Can linked variants do an automatic comparison? i.e. linking two cases to each other will trigger a hypothetical compare feature of Scout. For example, I tag one as remission/relapse and the other base.
1. Can we have relapse/remission vs first analysis in single IGV view?
1. TBD

(I'll add more as soon as I can think about more stuff to add)

**Comment by dnil** [comment]
I think we can basically close this for now with #2109 / #2072 and revisit when that has been tried for a while and see if like a comparison view is still desired. Holler if I'm wrong! 😊
