### ISSUE TITLE
bug on date of upload?

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#208]
Hi!
I've noticed that the last 3 days these familes have been uploaded every day.
= yesterday there was 2015-11-16, the day before 2015-11-15, today 2015-11-17 but we are not aware we asked for a new upload.
what is happening?
[uploads_issue.pptx](https://github.com/Clinical-Genomics/scout/files/36678/uploads_issue.pptx)

Michela

**Comment by moonso** [comment]
@b4ckm4n , @emmser , @robinandeer ?

**Comment by robinandeer** [comment]
@moonso: we have identified this issue as having to do with cases that were initially uploaded under "cust000" and thereafter moved manually "cust003". When the script finds the analysis again the code identifies it as a new case and processed with the re-upload - do you perhaps we should implement something covering this case?

@4WGH: this is an unfortunate issue but the analysis data is the same so there's nothing new added even if the date is updated.

**Comment by vwirta** [comment]
@robinandeer did you do changes to this on Friday?

**Comment by robinandeer** [comment]
This shouldn't be an issue anymore, we fixed it by editing the files on the filesystem
