### ISSUE TITLE
Bug "Use HPO list for clinical filter "??

### ISSUE THREAD

**Issue by KickiLagerstedt** [Clinical-Genomics/scout#2082]
Using the function "Use HPO list for clinical filter " does not seem to work - I get all variants from default panel.....

Not good   :=(

**Comment by dnil** [comment]
Thanks for reporting.. That touches one of the major things updated this time, so while bad not strange. We'll fix!

**Comment by KickiLagerstedt** [comment]
Toppen! 
:=)

**Comment by dnil** [comment]
In the meantime, filtering with panel "HPO" - or constructing a filter of your own containing the "HPO" panel still work.

**Comment by KickiLagerstedt** [comment]
Toppen! 
:=)

**Comment by KickiLagerstedt** [comment]
Toppen! 
:=)

**Comment by northwestwitch** [comment]
I'm taking this if nobody started with it!
