### ISSUE TITLE
Missing OMIM phenotypes info from the genes cell in variants page?

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#2089]
Check and fix!

**Comment by dnil** [comment]
I started looking, but it so far eludes me: somehow the variant gene objects no longer get populated with disease terms ("phenotypes") although those are present in the db and can be seen on e.g. the disease_term page. I guess next I try and see if something went south with the switch in gene panel handling and variant_gene population, but it shouldn't really.

**Comment by northwestwitch** [comment]
The old way to load genes is not really working any more, so it might be a problem to compare how the variants were populated before and after the change

**Comment by dnil** [comment]
Btw does anyone feel nostalgic about this one (@moonso), or can we remove it? I can't figure out how to call it from the cli as it stands now, but maybe I'm just confused from debugging?

https://github.com/Clinical-Genomics/scout/blob/f70306b1ee8e8ba7cb048e9438ec93d54f3a0922/scout/parse/omim.py#L399

**Comment by northwestwitch** [comment]
Didn't know we had a morbid file..

**Comment by dnil** [comment]
4 years ago Im sure we did! 😄

**Comment by dnil** [comment]
Thanks; cleanup of obsolete things is good for simplifying future maintenance, and potentially increasing test coverage? If you have insights to the issue they most are welcome, but this was working not too long ago, so it should be solvable - only elusive at the moment..
