### ISSUE TITLE
database versioning

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#209]

**Comment by moonso** [comment]
This will come in the new update, see #150

**Comment by 4WGH** [comment]
?

**Comment by ingkebil** [comment]
just to elaborate: it is strange that the database version goes from 6.2 to 6.3 and back to 6.2 even though the upload dates only go up?

Also, I have checked the version of the gene list in production at the upload date and that doesn't seem to correspond with the upload dates either:
Oct 21 6.4
Jun 5 6.3
May 18 6.2

**Comment by robinandeer** [comment]
See #210

**Comment by 4WGH** [comment]
As long as we have this issue going on it may be good if Kenny tell me when a new version is used so I can cross check the data fit. (new family should have the newest version)? or is it OTT?
