### ISSUE TITLE
database version not consequential 

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#210]
we have noticed the following in-congruence on the database version reported in scout.
family 15080, uploaded 2015-08-30 version 6.2
familiy 15102, uploaded 2015-09-23 version 6.3
family 15044 uploaded 2015-11-12 8or 17) version 6.2

This could be connected to the previous issued with upload date.
Kenny looked into this and the versions do not correspond correctly...
The version used todat is 6.5
Something to investigate before we upgrade to version 7 of the database :)

Michela
PS same issue as issue#209, but It got closed before I could finish to edit it, so i'm not sure the answer I've got was correct. Sorry to bother you again but it is an important issue!

**Comment by robinandeer** [comment]
Sorry about that, this is indeed related to #208! The upload date is not directly related to the database version. As I tried to explain in the other issue, the data for these falsely re-uploaded cases is based on old data - they have not actually been rerun.
