### ISSUE TITLE
KeyError in event["verb"] = VERBS_MAP[event["verb"]]

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#2103]
When we introduce new events in feature branches, the stage database becomes populated with events that will crash a trunk version. I suggest we catch the exception and possibly make a visible note of the event rather than crash. This would also work to more quickly stabilise a situation where we would have to revert a version introducing a new event in production.

**Comment by northwestwitch** [comment]
Good suggestion!

**Comment by dnil** [comment]
Closed by #2109
