### ISSUE TITLE
CLI command to view exons seems not working

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#2104]
Check the command:
`scout view exons`

that returns just one exon:

{'_id': ObjectId('5f633f4f582d613b6c72dc65'),
 'build': '37',
 'chrom': '19',
 'end': 58864804,
 'exon_id': '19-58864770-58864804',
 'hgnc_id': 5,
 'rank': 1,
 'start': 58864770,
 'strand': -1,
 'transcript': 'ENST00000263100'}

This command might be redundant since we already have `scout export exons`, so check what's the difference between the 2.

**Comment by northwestwitch** [comment]
Ok now I'm really confused. I've checked on the database and the exon collection of the production db is *EMPTY*.  The one of stage db has only exons from build 38.. 🤔

**Comment by northwestwitch** [comment]
Update on this one. It might not be a bug, but just us that didn't load the exons. I'm running the scout load exons on stage now. Then I'll see if the export works.

 If everything is fine I'll run it on prod as well

**Comment by northwestwitch** [comment]
It was that. Shame on me, but an easy (partial) fix!
After loading the exons, the `scout export exons ` command works, but the `scout view exons` one doesn't.

l'll just leave the issue open and rename it because it needs fixing, but it's less urgent

**Comment by dnil** [comment]
Sounds good - check with @moonso otherwise - I still think he was the last one touching that?

**Comment by northwestwitch** [comment]
> Sounds good - check with @moonso otherwise - I still think he was the last one touching that?

He wrote the code to load exons and to export them (with `scout export`), and both things work. It's the view command that needs a check.

**Comment by moonso** [comment]
Hi, great that it worked! The `view` vs `export` is a bit vague. The first idea was that `view` where supposed to be used when doing human inspections of stuff in the database, so readable format. The `export` commands was more for serialising things. Since I guess none of them are used so much one could give it a thought and perhaps merge them.

**Comment by northwestwitch** [comment]
I think that if we merge them we should still keep the option to query just for one gene, instead of all exons.

**Comment by dnil** [comment]
I agree that was one of the ideas, but its unclear to me how or if the flow of information is automated - @moonso again? I guess via cg. It would be the tool uploading runs to chanjo anyway, so why not also pull exon info from scout to upload? But then it would be in trouble if the exon db is empty on prod? Perhaps that part was never implemented, only done a few times manually?

Scout afaik currently only speaks indirectly to chanjo via chanjo-report, and can then only give gene symbols, not new exon definitions.

**Comment by dnil** [comment]
ok so two parts
- [ ] scout view exons without options (possibly with an empty exon db) does not produce the expected result
- [ ] possibly harmonise view exons and export exons, but from @moonso's answer I think it may not be necessary?
