### ISSUE TITLE
No warning when searching for gene not in clinical list

### ISSUE THREAD

**Issue by ielvers** [Clinical-Genomics/scout#2105]
Hi,
When I search for the gene RFK I don't get the usual warning that it is not in the clinical list so I interpret the empty list as a lack of variants, but when manually looking in the OMIM-AUTO panel it is not in the list.

**Comment by dnil** [comment]
Hi @ielvers! What case are you working on? I agree RFK shouldn't be in OMIM, and I still get the warning on a random case.
![Screenshot 2020-09-17 at 13 09 10](https://user-images.githubusercontent.com/758570/93462788-2760a380-f8e7-11ea-9c83-3784f8eab573.png)

**Comment by ielvers** [comment]
Interesting! I was looking in 20165. We don't get the warning in other newer cases either (20035, 20170, 20172 tested). We get the warning though in an older case (19098 run April 2019) - but in another old case (19244 run Nov 2019) we get a list with a variant in RFK.

**Comment by dnil** [comment]
Ah, the gene appears to be present on the mitocarta gene-panel, so whenever you have a case that has been run with it, it will appear as a "clinical" gene, although all genes on the Mitocarta surely have not been linked to disease.

**Comment by ielvers** [comment]
Aha! Thank you Daniel - super helpful! But we still have some questionmarks.
We checked two other genes that are not in OMIM-AUTO but are included in Mitocarta (and hence should give a warning in older but not newer samples).
PDP2 - no warning for new cases (20165, 20171). No warning in semi-old case (19244) and no warning in old-old case (19098 that gave a warning for RFK).
MPC2 - no warning in new case (20165), no warning in semi-old case (19244), warning "not in clinical list" in one old-old case (19098).

So PDP2 should give a warning in case 19098 from April 2019 (before Mitocarta was added), but it doesn't. Any ideas why that is happening?

**Comment by northwestwitch** [comment]
PDP2 is in PID Candidates, a quite old panel having the gene since quite a long time perhaps so that all 3 cases where runned with it perhaps?

MPC2 is only in Mitocarta (20165 and 19244 runned with the panel), 19098 no.

Hope this helps!

**Comment by ielvers** [comment]
Thank you guys! It really helps to know what's going on. We have to discuss this a bit more among ourselves since this means that we may unintentionally search for genes that we're not supposed to look at without research consent from the patient.
