### ISSUE TITLE
Strs variants page is looking really weird for a case on stage

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#2110]
![image](https://user-images.githubusercontent.com/28093618/93587284-f301eb80-f9a9-11ea-9a79-1f417c1a8bdf.png)
 The case is this one: https://scout-stage.scilifelab.se/cust000/643594-300M/str/variants?variant_type=clinical

Perhaps there is something wrong just with this case, because I haven't seen the behavior in another one, but I'll just drop it here so we can check!

**Comment by dnil** [comment]
Hm, this is a MIP9 reupload I guess.. What branch was this on?

**Comment by northwestwitch** [comment]
Master!

**Comment by dnil** [comment]
Hmm, so this would be the first time we test reuploading a case with edited comments, right? Also it may or may not have been reuploaded with master on hasta: might as well have been 4.21.2..

**Comment by northwestwitch** [comment]
Yes, on Hasta it's still 4.21.2 (latest release)

**Comment by northwestwitch** [comment]
I'm going to take a look at this one too
