### ISSUE TITLE
Clinvar - New clinsig values do not have internal representation

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/scout#2112]
When loading a case with clinvar annotations from: /home/proj/stage/rare-disease/references/references_9.0/grch37_clinvar_reformated_-20200905-.vcf.gz corrsponding to clinvar file: clinvar_20200905.vcf.gz. Scout yields these warnings:
<img width="1383" alt="Screenshot 2020-09-19 at 10 24 56" src="https://user-images.githubusercontent.com/584738/93662693-66ffca80-fa62-11ea-937b-20e15e2dd59e.png">

**Comment by northwestwitch** [comment]
While trying to fix this, I've realized that this might be a bug that we had from before that is not connected to MIP9, but I'm not sure. We should check some old case with a variant having that ClinVar significance value..

**Comment by dnil** [comment]
But.. but.. surely someone would have tested it if they switched ClinVar file?

**Comment by dnil** [comment]
Hm, still, I guess: they may have been rare enough before that one test case did not have them?

**Comment by northwestwitch** [comment]
I guess so

**Comment by henrikstranneheim** [comment]
Reuploading case strongbison and vitalmouse progress without any errors! Well done!

**Comment by northwestwitch** [comment]
@henrikstranneheim do you plan to start using MIP9 in production someday soon? Because we should release a new scout then!

**Comment by henrikstranneheim** [comment]
@northwestwitch As in want to deploy asap

**Comment by henrikstranneheim** [comment]
A new release as soon as possible would be great

**Comment by northwestwitch** [comment]
@mikaell @elevu @dnil let's have one today. Is there anything else we need to merge before releasing what we already have on master?

**Comment by dnil** [comment]
> While trying to fix this, I've realized that this might be a bug that we had from before that is not connected to MIP9, but I'm not sure. We should check some old case with a variant having that ClinVar significance value..

How about this one? I guess just grep:ing for clinsig and `\&` a few vcf from bundles of varying age might give something away?

**Comment by dnil** [comment]
(And checking regarding release..)

**Comment by dnil** [comment]
Nah, all PRs are currently feature ones, and not extremely urgent ones, and we are not tracking any serious bugs. I guess the view exons remake might constitute a bug fix, so your call on that one is welcome! Otherwise focusing on MIP9 compatibility (plus the already included like editable comments) sounds like a plan!
