### ISSUE TITLE
Update track formats memento

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#2118]
Something is amiss with bigwig display at the moment. If TIDDIT_coverage from MIP9 is loaded for a case, TIDDIT_coverage is displayed as something akin to `grapthType: "points"` although IGV.js default is `"bar"`. When one is at it, add sample name to the UPD, coverage and rhocall track display names. 

See initial tests in branch https://github.com/Clinical-Genomics/scout/tree/update_track_formats

Has so far only tested with the MIP bws; they look just fine in regular IGV, and other bws look good on some IGV.js. Without more tests it is hard to know if this is an issue with the files, config or some arcane version/interaction issue.

This feature will be disabled in initial CG for MIP9, so not a rush.

**Comment by northwestwitch** [comment]
Was this one fixed in #2192 or is not related?

**Comment by dnil** [comment]
No, it is likely still pending. There was a fix on igv.js a little while back with wigs and indexes that may possibly have helped, but until further investigation it is still pending. It is a little weird that the tracks load, but no config option seems to make it look like the regular app edition. I guess it will so slowly be easier to test now that CG is passing more of the files through.

**Comment by dnil** [comment]
At this point, this can be considered a duplicate of #1386.
