### ISSUE TITLE
Warnings about CLINSIG while uploading a dummy case

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/scout#2123]
While testing this PR: https://github.com/Clinical-Genomics/scout/pull/2117 I noticed some strange warnings about clinsig. Please see the screenshot below:

![image](https://user-images.githubusercontent.com/1086877/93986664-e9e89400-fd86-11ea-8b2e-0be8ec287ecd.png)

Case name on stage is: actualgecko and cust000

**Comment by northwestwitch** [comment]
Another clinsig issue, possibly easily fixable like #2112. Which scout version were you testing on. I know that it's a branch from @elevu, but is it up to date with current master?

**Comment by northwestwitch** [comment]
@hassanfa could you point me to the VCF files used that gave you the warnings?

**Comment by northwestwitch** [comment]
Never mind, I found it! :)

**Comment by northwestwitch** [comment]
Testing this now and I can confirm that the warning still exists in current master, fixing it!
