### ISSUE TITLE
"Symbol mis-match" when uploading new gene panel to Scout

### ISSUE THREAD

**Issue by keyvanelhami** [Clinical-Genomics/scout#2126]
When uploading the attached csv-file to Scout, I get below error message. I believe the db needs to be updated?

<img width="1339" alt="Screen Shot 2020-09-24 at 2 39 35 PM" src="https://user-images.githubusercontent.com/26735714/94146136-cbac9200-fe73-11ea-8fe4-f08009a5a56c.png">

```
##panel_id=Lymfoid_genepanel_v1.0	
##institute=cust087	
##version=1.0	
##date=2020-09-24	
##display_name=Lymfoid genepanel v1.0	
#hgnc_id	hgnc_symbol
795	ATM
914	B2M
591	BIRC3
1097	BRAF
1133	BTK
16393	CARD11
1698	CD79A
1699	CD79B
7067	CIITA
2348	CREBBP
2561	CXCR4
3239	EGR2
3527	EZH2
4381	GNA13
5362	ID3
5383	IDH2
6193	JAK3
6347	KLF2
7562	MYD88
7799	NFKBIE
7881	NOTCH1
7882	NOTCH2
9065	PLCG1
9066	PLCG2
17284	POT1
667	RHOA
10388	RPS15
19902	RRAGC
10768	SF3B1
10769	SF3B1
19383	SOCS1
11364	STAT3
11367	STAT5B
11633	TCF3
11640	TCF3
25941	TET2
11896	TNFAIP3
11912	TNFRSF14
11998	TP53
12033	TRAF3
12825	XPO1
6840	MAP2K1
```

**Comment by northwestwitch** [comment]
Hi!
It's probably because both genes are duplicated in your list, with different hgnc ids. You should probably check which ID is official at the moment and go for it!

**Comment by keyvanelhami** [comment]
Thanks Chiara. I will check the customer and try to re-upload the gene-list

**Comment by northwestwitch** [comment]
From ensembl: 
http://grch37.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000071564;r=19:1609291-1652604

http://grch37.ensembl.org/Homo_sapiens/Gene/Summary?db=core;g=ENSG00000115524;r=2:198254508-198299815

**Comment by keyvanelhami** [comment]
Solved!

**Comment by dnil** [comment]
Perfect! genenames.org is also your friend in these situations!
