### ISSUE TITLE
ClinVar missing from variant page? part 1

### ISSUE THREAD

**Issue by AnnHam** [Clinical-Genomics/scout#2129]
ClinVar info missing from variant page?

F0001604 - variant in CACNA1A (c.1747C>T) I can't find it in ClinVar, but it's marked (red) in IGV-pileup. There is another variant i the amino acid just next to it (https://www.ncbi.nlm.nih.gov/clinvar/variation/848756/).

**Comment by dnil** [comment]
Hi again! If I read the transcript numbers correctly it's actually the same?

<img width="1079" alt="Screenshot 2020-09-28 at 14 29 40" src="https://user-images.githubusercontent.com/758570/94432636-556f9e80-0197-11eb-9fa8-e6e43bd61e7d.png">

Its listed as being from feb 2020, and the case analysed with MIP8, so I think we can write it off with old reference files. But thank you for keeping a vigil - lets return to it as soon as MIP9 deploy and the current ClinVar situation is resolved.

**Comment by henrikstranneheim** [comment]
MIP 9 was deployed last week and uses a clinvar ref from 2020-09-05. If these types of issues occur with newly analyzed cases please open an issue and we will look into it ASAP.
