### ISSUE TITLE
ClinVar missing from variant page? part 2

### ISSUE THREAD

**Issue by AnnHam** [Clinical-Genomics/scout#2130]
ClinVar info missing from variant page? I can see it marked red in IGV-pileup. Is there an issue with ClinVar? 

F0035154-2 - variant in OTOGL c.1051C>T (https://www.ncbi.nlm.nih.gov/clinvar/variation/667382/) it's in ClinVar since April 2018.

**Comment by dnil** [comment]
Yep, that one should be there; from 2018, still MIP8 so old ClinVar ref, but surely newer than 2018. Checking vcf.

**Comment by dnil** [comment]
(Oh, it was actually not submitted until 2019, though the evaluation is dated 2018, so perhaps same issue actually. But, lets see..)
<img width="721" alt="Screenshot 2020-09-28 at 14 41 37" src="https://user-images.githubusercontent.com/758570/94433625-e5faae80-0198-11eb-9ec1-c4ae1255a50f.png">

**Comment by dnil** [comment]
No CLINVAR annotation for the variant in question on VCF, so the issue is with MIP references rather than Scout.

**Comment by dnil** [comment]
In particular, the ClinVar reference file for that version of MIP was from `ClinVar="201810"`. so likely before submission of this variant. 😞

**Comment by dnil** [comment]
New references will be around very soonish, so don't despair!
