### ISSUE TITLE
Make the update individuals command more user-friendly

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#2133]
Sometimes it is necessary to update the alignment path for an individual of a case.

Scout has a dedicated command to do that: `scout update individual`, that accepts the following inputs:
 -c, --case-id TEXT     [required]
 -i, --ind-id TEXT     [required]
 -a, --alignment-path PATH Replace alignment file

case id is already displayed on the case web page so it's fine,  but the --ind-id is not the same as the individual display name that can be seen on the case page. It's the `individual_id` values instead. It would be nice to change it into individual display name so that it would be much easier for prod team to run the command independently.

**Comment by hassanfa** [comment]
Is it possible to update _any_ value? E.g. using `scout update individual/case KEY=VALUE`

**Comment by northwestwitch** [comment]
So far, no. Just the alignment. Good idea!

**Comment by northwestwitch** [comment]
This is the demo individual for instance:

![image](https://user-images.githubusercontent.com/28093618/94657138-4c024580-0301-11eb-91dc-6e3c4aa9de57.png)

I see some stuff that would be good to update from the cli: sex, phenotype, mt_bam, vcf2cytosure, rhocall, tiddit and upd tracks, tissue_type.

**Comment by dnil** [comment]
Good stuff both! The command could optionally take a small json for updates of several values, rather than having to repeat several cli calls with key=value?

**Comment by hassanfa** [comment]
cool! Some sort of comment would be nice as well to append to `cli_update_comment`. Like `scout update case --config "KEY=VALUE" --comment "Updating KEY for XXX reason"` or `scout update case --config-file a_json_file_with_limited_info.json --comment "Updating multiple values based on customer request ticket XXXX"`

**Comment by northwestwitch** [comment]
Didn't even know that we had a cli update comment command! 😮

**Comment by hassanfa** [comment]
No, I mean it could be good to have one cli update comment option. It can come handy for automation even. When case re-runs manually or in an automated way.

Problem with KEY=VALUE will be for nested dictionaries. Neat stuff! But it can be abused so badly haha

**Comment by northwestwitch** [comment]
Ahhh Ok now I understand. I don't know how easy that would be, because comments are usually associated to a specific scout user. And it's not obvious that the person performing the update is a scout user for that institute..

**Comment by northwestwitch** [comment]
On the other hand, how often does it happen that you need to change many key/values for an individual? The command is rarely used and in general you change one thing. Wouldn't be preparing the json file an overkill for the usual ticket-associated tasks? I'm thinking that if we keep the command simple (update one key/value at the time) might avoid prod team coming to ask develop team members to ask question about the process (and ultimately update values directly in the database), that is actually what I'd like to avoid in the first place..

**Comment by hassanfa** [comment]
I know if there is a JSON, I'd abuse it and end up creating more issues here. One key at a time is quite nice idea actually.

**Comment by hassanfa** [comment]
Validating input JSON, making sure all the keys exists, etc... problems can happen.

**Comment by northwestwitch** [comment]
> Validating input JSON, making sure all the keys exists, etc... problems can happen.

The format of the key values! 😱
