### ISSUE TITLE
Round CADD..

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#2134]
![Screenshot 2020-10-01 at 12 00 11](https://user-images.githubusercontent.com/758570/94795623-dfa94400-03dd-11eb-8e70-ef8976a81eef.png)
😊

**Comment by northwestwitch** [comment]
to how many decimals, one?

**Comment by dnil** [comment]
Sounds about right; it used to be an int, but alternatively I'd ask @jemten or someone else who has read up on the latest development to know what is reasonable!

**Comment by dnil** [comment]
![Screenshot 2020-10-01 at 12 35 28](https://user-images.githubusercontent.com/758570/94799028-cce53e00-03e2-11eb-81b3-663ff352de58.png) 😆

**Comment by northwestwitch** [comment]
ugly!
