### ISSUE TITLE
Access to VCF from pinned variants? 

### ISSUE THREAD

**Issue by heronikdin** [Clinical-Genomics/scout#2144]
Hi from cust087!

I was wondering if it is possble somehow to get a VCF for pinned variants? We are looking into a portal (www.mtbp.org) where you can upload your VCF and get some more information such as drugs related to the condition in clinical trials, actionability of genes, tier classification etc etc. 

Thank you!

**Comment by northwestwitch** [comment]
Hi!
We have already a similar issue opened and not yet addressed: https://github.com/Clinical-Genomics/scout/issues/1915.

If it's OK for you I'll close this one and keep in mind that this is still to be done!
