### ISSUE TITLE
Document day-to-day chanjo integration / scout export

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#2145]
Integration with chanjo is a nice feature, but it would be helpful with a few pointers on best practice for integration, such as `scout export exons > scout.exon.bed` to `chanjo link scout.exon.bed` as the format of the latter can be a little involved. One for you @moonso? Specifically from Linda K @ Umeå, who got a sketch to an answer only.. 😅

**Comment by moonso** [comment]
Sounds like a good idea. I guess that most of the interactions are more of sketches in the docs unfortunately

**Comment by dnil** [comment]
This feels a bit obsolete with chanjo2 around.
