### ISSUE TITLE
dbVar ucsc track that for igv viewer

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/scout#2147]
A new structural variant track is available for hg19 and hg38 from dbVar: https://genome.ucsc.edu/goldenPath/newsarch.html#100520

It might be useful for Scout. What do you think? Gnomad, decipher, and 1kg phase 3 SVs are included.

**Comment by northwestwitch** [comment]
Great! We can add it. And if users don't want to see it they can deselect it in the track settings (new feature from next Scout release).

**Comment by northwestwitch** [comment]
Link to FTP data: https://www.ncbi.nlm.nih.gov/dbvar/content/ftp_manifest/#assemblies

**Comment by northwestwitch** [comment]
This will be fixed after merging #2154 and finding a proper host to the tracks that I'm now hosting on my private Amazon account, see the mentioned PR

**Comment by northwestwitch** [comment]
This was fixed in the PR mentioned above, closing the issue!
