### ISSUE TITLE
HPO October release...

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#2158]
Looks benign, but lets test just in case.

[obophenotype/human-phenotype-ontology] Release v2020-10-12 - 2020-10-12 release

Repository: obophenotype/human-phenotype-ontology · Tag: v2020-10-12 · Commit: 4c61a8d · Released by: drseb

October 2020 release

https://github.com/obophenotype/human-phenotype-ontology/raw/master/src/ontology/reports/hpodiff_hp_2020-08-11_to_hp_2020-10-12.xlsx

**Comment by northwestwitch** [comment]
Nooo, I runned the updates last Friday! But let's test locally and on stage, I agree!

**Comment by northwestwitch** [comment]
I'm closing this one as there's a fresh release from December. About time for us to update!
