### ISSUE TITLE
Use Orphanet to describe diseases, together with OMIM

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#2159]
To do:
- Download all Orphanet diseases and add them to the database (different collection from the OMIM one?)

- HPO terms to Orphanet diseases data is included in the genes_to_phenotype.txt file already used to couple genes to OMIM diseases:

![image](https://user-images.githubusercontent.com/28093618/95955705-90134100-0dfd-11eb-81b0-4013d98e19ae.png)

- Make terms available at the case level to assign diseases

**Comment by northwestwitch** [comment]
@TereseBo assigning this issue to you but let's discuss about first. 

- The first step would be parsing also orphanet terms from the files downloaded from OMIM and saving them into the database
- The tricky thing would be fixing the scout code so that whenever OMIM terms are used , the presence of Orphanet terms doesn't mess up with what the user is doing (modify the database query that returns diseases to only return omim terms)

**Comment by northwestwitch** [comment]
@TereseBo the function in the code where the disease terms are parsed and only the OMIM ones are collected for now is this: https://github.com/Clinical-Genomics/scout/blob/319150a50722aecdf6f16f2b738ec4b4a8512a33/scout/parse/hpo_mappings.py#L77

And the file that is parsed by this function is the one named phenotypes.hpoa

**Comment by northwestwitch** [comment]
Posting here the chat with @TereseBo, so we can all discuss about this and better understand how stuff work:

> I have a question: the disease_terms included in the database seem to be the omim-terms listed as a phenotype in the file mim2genes, the ones listed as predominantly phenotypes are not included in the database. However they are included in the phenotype.hpoa file, I just wanted to verify that they are to be excluded while all orpha-codes are included?

Isn'r phenotypes.hpoa the main file where the OMIM terms are also collected? I assumed mim2genes is the file connecting OMIM terms to associated genes, and for this reason it doesn't contain OMIM terms which have no associated genes?

**Comment by TereseBo** [comment]
If I understand it correctly the disease_terms are created from the mim2genes.txt and then the disease_annotations are extracted from phenotype.hpoa and then it is parsed and combined to a disease object only if the annotation disease_id is found in the data from the mim2genes.

**Comment by northwestwitch** [comment]
> If I understand it correctly the disease_terms are created from the mim2genes.txt and then the disease_annotations are extracted from phenotype.hpoa and then it is parsed and combined to a disease object only if the annotation disease_id is found in the data from the mim2genes.

Ok, if the OMIM terms in phenotype.hpoa are more and they are instead collected from mim2genes I guess we need to fix this and collect all terms initially from phenotype.hpoa. This is also what I do in PatientMatcher(https://github.com/Clinical-Genomics/patientMatcher/blob/main/patientMatcher/utils/disease.py).

**Comment by northwestwitch** [comment]
phenotye.hpoa format, for reference: https://hpo.jax.org/app/data/annotation-format

**Comment by TereseBo** [comment]
I will look in to it, but is it possible for OMIM phenotypes to be present in the mim2genes but missing in the phenotype.hpoa if they for example are not connected to HPO terms? But then again it  should be very unlikely for a disease to be registered and not have known symptoms so I'm probably overthinking

**Comment by TereseBo** [comment]
And I have apparently been tired: it's the genemap2 file that is used.

**Comment by northwestwitch** [comment]
> And I have apparently been tired: it's the genemap2 file that is used.

Ok, I'm going to take a look at the parsing of diseases as well. I'm not really sure what is taken from what. Also the naming of the functions we are using could be misleading. Perhaps we should rename these parsing function according to which file they parse.

**Comment by northwestwitch** [comment]
We might also want to check this resource: https://github.com/Orphanet/Orphadata_aggregated/tree/master

For instance to collect all genes connected to a ORPHA disease.

**Comment by TereseBo** [comment]
Download of Orphadata files was implemented in #4241 and 

Orpha codes was added to Scout by #4262 which also introduced the need for some further adjustments #4316, #4354,  #4356 and #4371 before being fully integrated.
