### ISSUE TITLE
Add synopsis, phenotype_terms and cohorts to load config

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#2162]
StarLIMS can now export new fields to the order json files going over to CG. We wish to be able to load these into Scout for new cases: 
- synopsis: list(str)
- phenotype_terms: list(str)
- cohorts: list(str)

**Comment by northwestwitch** [comment]
I'm planning to work on this. Questions:
- Synopsis is a list of single words or a list of sentences?
- Phenotype terms are a list of HP terms like HP:number ?
- Cohort should be something like ["pedhep", mito", ..], right?

**Comment by moonso** [comment]
Synopsis is just `str` I guess

**Comment by dnil** [comment]
Ah, no, array of str actually: Synopsis becomes a note type in the LIMS, and users could theoretically add multiple such notes in different places on a case..

**Comment by dnil** [comment]
I've sent you the specs over email @northwestwitch - thanks for picking this one up!

**Comment by northwestwitch** [comment]
> I've sent you the specs over email @northwestwitch - thanks for picking this one up!

Thank you!
