### ISSUE TITLE
Access to cust064

### ISSUE THREAD

**Issue by ellikasahlin** [Clinical-Genomics/scout#2163]
Hi!

Me and Eini Westenius need access to cust064 (KG /research /Lindstrand).

Can you please help? 

ellika.sahlin@clinicalgenomics.se
eini.westenius@clinicalgenomics.se

Thanks in advance!
Ellika

**Comment by dnil** [comment]
Sure thing! I understand it is confusing to have two places to direct requests. Please use the Clinical Genomics support system for issues like these, that pertain to local configuration, specifics of cases and ordering etc. The GitHub is intended as a more public forum (for our huge international user base🤣) where questions regarding the function of the software, requests for improvements or changes are made. No harm done - mostly the same ppl on the receiver anyway.

**Comment by dnil** [comment]
Should be working now. Closing; please just shout if there are any issues.

**Comment by ellikasahlin** [comment]
Oops, sorry! And thank you!
Ellika


Från: Daniel Nilsson <notifications@github.com>
Skickat: den 19 oktober 2020 10:23
Till: Clinical-Genomics/scout <scout@noreply.github.com>
Kopia: Ellika Sahlin <ellika.sahlin@ki.se>; Author <author@noreply.github.com>
Ämne: Re: [Clinical-Genomics/scout] Access to cust064 (#2163)


Sure thing! I understand it is confusing to have two places to direct requests. Please use the Clinical Genomics support system for issues like these, that pertain to local configuration, specifics of cases and ordering etc. The GitHub is intended as a more public forum (for our huge international user base🤣) where questions regarding the function of the software, requests for improvements or changes are made. No harm done - mostly the same ppl on the receiver anyway.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FClinical-Genomics%2Fscout%2Fissues%2F2163%23issuecomment-711829326&data=04%7C01%7Cellika.sahlin%40ki.se%7C99700ba02d8e48874e6408d874083fd0%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C637386926063035321%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=MlaDjkQlz1RCGJr1KHzpy21ivnIBsvPvBMtd5jbD1L0%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAEO6DM3AZJM237CNZW3FWLDSLPZPZANCNFSM4SVZTBBQ&data=04%7C01%7Cellika.sahlin%40ki.se%7C99700ba02d8e48874e6408d874083fd0%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C637386926063045324%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=2IuCr87uEmySFdI3%2BNH%2FmxSR5PaTUUUYF3Nnx2kmSGU%3D&reserved=0>.



När du skickar e-post till Karolinska Institutet (KI) innebär detta att KI kommer att behandla dina personuppgifter. Här finns information om hur KI behandlar personuppgifter<https://ki.se/medarbetare/integritetsskyddspolicy>.


Sending email to Karolinska Institutet (KI) will result in KI processing your personal data. You can read more about KI’s processing of personal data here<https://ki.se/en/staff/data-protection-policy>.
