### ISSUE TITLE
STR pagination broken on master..

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#2166]
I think a new positional argument was introduced for the variants controller recently, but not on str variants, which regrettably does not formally inherit it? Just a reminder - will fix in STR filters update.

**Comment by northwestwitch** [comment]
Is it also on prod?

**Comment by dnil** [comment]
Nope, should be fine; no rush - we should just have the fix in before releasing/deploying current master. I just noticed during testing of said other fix with str filters.

**Comment by northwestwitch** [comment]
Hi @dnil have you started working on this? Otherwise I can take it.

**Comment by dnil** [comment]
Yeah, I think I solved it as part of the STR filters PR. Two other prio tasks in queue, then I'll get back to this. End of the week approx..

**Comment by dnil** [comment]
Fixed by #2209!
