### ISSUE TITLE
Link to pLi Score(ExAC) 

### ISSUE THREAD

**Issue by AnnHam** [Clinical-Genomics/scout#2167]
Link to pLi Score(ExAC) no longer available - redirected to gnomAD - could you change link to gnomAD instead?(https://scout.scilifelab.se/genes/XXXX) 
(XXXX=HGNC ID)

**Comment by dnil** [comment]
Quite right - it was caught on #1022 - but we’ll investigate the current status! There was also a related issue where we waited for more input in #1571.

**Comment by northwestwitch** [comment]
I could start working on this one!

**Comment by northwestwitch** [comment]
I need some guidance with this one. Is the pli score available in the VCF file?

**Comment by northwestwitch** [comment]
Looks like it's in the INFO field:

```
##ExACpLI=ExACpLI value for gene
##INFO=<ID=CSQ,Number=.,Type=String,Description="Consequence annotations from Ensembl VEP. Format: Allele|Consequence|IMPACT|SYMBOL|Gene|Feature_type|Feature|BIOTYPE|EXON|INTRON|HGVSc|HGVSp|cDNA_position|CDS_position|Protein_position|Amino_acids|Codons|Existing_variation|DISTANCE|STRAND|FLAGS|SYMBOL_SOURCE|HGNC_ID|CANONICAL|TSL|APPRIS|CCDS|ENSP|SWISSPROT|TREMBL|UNIPARC|REFSEQ_MATCH|SOURCE|REFSEQ_OFFSET|GIVEN_REF|USED_REF|BAM_EDIT|SIFT|PolyPhen|DOMAINS|HGVS_OFFSET|MOTIF_NAME|MOTIF_POS|HIGH_INF_POS|MOTIF_SCORE_CHANGE|LoFtool|GERP++_NR|GERP++_RS|REVEL_rankscore|phastCons100way_vertebrate|phyloP100way_vertebrate|SpliceAI_pred_DP_AG|SpliceAI_pred_DP_AL|SpliceAI_pred_DP_DG|SpliceAI_pred_DP_DL|SpliceAI_pred_DS_AG|SpliceAI_pred_DS_AL|SpliceAI_pred_DS_DG|SpliceAI_pred_DS_DL|SpliceAI_pred_SYMBOL|MES-NCSS_downstream_acceptor|MES-NCSS_downstream_donor|MES-NCSS_upstream_acceptor|MES-NCSS_upstream_donor|MES-SWA_acceptor_alt|MES-SWA_acceptor_diff|MES-SWA_acceptor_ref|MES-SWA_acceptor_ref_comp|MES-SWA_donor_alt|MES-SWA_donor_diff|MES-SWA_donor_ref|MES-SWA_donor_ref_comp|MaxEntScan_alt|MaxEntScan_diff|MaxEntScan_ref|ExACpLI|genomic_superdups_frac_match|CLINVAR|CLINVAR_CLNSIG|CLINVAR_CLNVID|CLINVAR_CLNREVSTAT">
```

**Comment by dnil** [comment]
Two things here: one is a selected aggregate (versioned/static) number on each variant present in the VCF as per #1022. Check back with MIP team if this is missing / altered / fixed yet? 

Then more to the point here there is a general link out on each gene, to the source of the same static values, giving a) a current version b) more details, eg counts of missense/nonsense variants observed in normal population. Links currently should be like ```https://gnomad.broadinstitute.org/gene/GENESYMBOL?dataset=gnomad_r2_1```. 

![Screenshot 2020-11-10 at 10 41 16](https://user-images.githubusercontent.com/758570/98657033-b61afb00-2341-11eb-8235-ef1f0c7f05b7.png)

**Comment by northwestwitch** [comment]
Ah Ok, so I don't need to parse anything?

**Comment by dnil** [comment]
Oh, and I forgot that we also have local parsing of the pLI from ExAC in Scout, and store it per gene, as part of the general download/parse package. I suggest you let this be about the link only, and make the current ExAC gene links point to the gnomAD 2.1 counterparts!

**Comment by northwestwitch** [comment]
> I suggest you let this be about the link only

Yes, thanks! 🙏

**Comment by dnil** [comment]
This one: 
![Screenshot 2020-11-10 at 10 52 20](https://user-images.githubusercontent.com/758570/98658240-1d857a80-2343-11eb-8a4e-ff0d18fa77de.png)
If I would have done it, I would have rounded the float considerably as well.. 😄

**Comment by northwestwitch** [comment]
Are you working on this already? Because I haven't started yet!

**Comment by dnil** [comment]
Hehe, I'm just helping you here, but sure, why not. 😆 Thanks for the suggestion.

The next step would then be to solve #1022 and actually dl the gnomad reference instead of exac reference.
