### ISSUE TITLE
Download of HPO gene panel 

### ISSUE THREAD

**Issue by AnnHam** [Clinical-Genomics/scout#2168]
When downloading the generated "HPO gene panel list" you now get a long list in excel with "HGNC symbol,HGNC ID,Description" - 

When reporting our results to the referral physician we add this list as an attached document (pdf). 

To save us some time making this list - could it be possible to:

1. Have all genes in alphabetical order (now it's random/alphabetical per HPO = a mess)
2. Only the HGNC symbol
3. HPO-terms used as headline (i.e. Overgrowth HP:0001548, Macrocephaly HP:0000256)
4. Not one gene per row, but a comprehensive list of genes separated with a comma (i.e. Gene A, Gene B, Gene C...) 
5. In a pdf document

**Comment by dnil** [comment]
Sure! We could also offer this as an option for the regular panels; the catch for completely replacing the current format is the more richly annotated panels (IEM etc) where a more complete table is expected.

**Comment by northwestwitch** [comment]
I can work on this one!

**Comment by northwestwitch** [comment]
Hi @KickiLagerstedt you're the one who first requested (at least officially) this functionality. Would that work for you to change the format of the exported genes as described above?
