### ISSUE TITLE
variant comments

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#217]
https://clinical-db.scilifelab.se:8083/cust003/15126/clinical?gene_lists=IEM&gene_lists=EP

fam 15126 I can see a blue dot near the CEP89 gen but no comment inside.

can not remember if it should be like that or if it is a bug.

**Comment by moonso** [comment]
Hello! This is the same as #152 , right?
In that case it will be fixed when we update scout

**Comment by robinandeer** [comment]
Yep!
