### ISSUE TITLE
Unable to upload wgs-balsamic to Scout

### ISSUE THREAD

**Issue by keyvanelhami** [Clinical-Genomics/scout#2174]
When using an old yaml-file:
`/home/proj/production/cancer/cases/toughdingo_2019-xx-xx/analysis/scout/toughdingo.scout.yaml`

I am copying and converting and adjusting it to a new yaml-file:
`/home/proj/production/cancer/cases/fullgibbon/analysis/scout/fullgibbon.scout.yaml`

I am unable to upload the last yaml-file since the variant has SOMATIC but not somatic score in the vep-annotated vcf-file:

```
Traceback (most recent call last):
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/scout/adapter/mongo/variant_loader.py", line 643, in load_variants
    sample_info=sample_info,
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/scout/adapter/mongo/variant_loader.py", line 429, in _load_variants
    category=category,
  File "/home/proj/bin/conda/envs/P_main/lib/python3.7/site-packages/scout/parse/variant/variant.py", line 219, in parse_variant
    parsed_variant["somatic_score"] = int(somatic_score)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
2020-11-03 14:39:59 hasta.scilifelab.se scout.adapter.mongo.variant_loader[241498] WARNING Deleting inserted variants
2020-11-03 14:39:59 hasta.scilifelab.se scout.adapter.mongo.variant[241498] INFO Deleting old clinical  variants for case fullgibbon_balsamic
2020-11-03 14:39:59 hasta.scilifelab.se scout.adapter.mongo.variant[241498] INFO 633 variants deleted
2020-11-03 14:39:59 hasta.scilifelab.se scout.commands.load.case[241498] ERROR Something went wrong during loading
2020-11-03 14:39:59 hasta.scilifelab.se scout.commands.load.case[241498] WARNING int() argument must be a string, a bytes-like object or a number, not 'NoneType'
Aborted!
```

**Comment by dnil** [comment]
Thanks for reporting! It would be very simple to just bypass silently. As far as I know this is not shown or used anywhere in Scout currently? What would be your desired new behaviour?

Is this change of tags intended behaviour as from some Balsamic version, but should work with old ones as well? Would you like to display the somatic flag and/or score somewhere, or should we just keep on keeping track of them?

**Comment by northwestwitch** [comment]
The code in question is here here: https://github.com/Clinical-Genomics/scout/blob/b8df771913e085bdce7a7c3226651e3d88f0de03/scout/parse/variant/variant.py#L215

It assumes that when a variant is SOMATIC then it also has SOMATICSCORE. But in this case it's not true.

I'm reading the Illumina instructions here: https://support.illumina.com/content/dam/illumina-support/documents/documentation/cancer_analysis/fasttrack-cancer-analysis-services-guide-15040893-01.pdf

I don't have access to the specific VCF causing the error but might be that it's the case described at page 11: 
```
If the SV junction is part of an EVENT (ie, a multiadjacency variant),
this field provides the SOMATICSCORE value only for the
adjacency in question.
```
??

**Comment by hassanfa** [comment]
We have uploaded same type of output from same file to Scout (toughdingo). Scout doesn't also say which variant is causing the error. It is slightly cryptic in the error. It would've been awesome to report which variant and with what value is the problem.

**Comment by northwestwitch** [comment]
I could make a small PR that prints which variant it is. When installed on hasta stage if you try to upload the same VCF you should see the message. Would that be useful?

**Comment by dnil** [comment]
The VCF in question doesn't even have SOMATICSCORE in the header INFO field, only SOMATIC (very likely from Manta, but unclear why it no longer writes SOMATICSCORE?). And the same goes for the actual variants. To confuse things, the VCF also has a SOMATIC field in the VEP CSQ, but I'm guessing thats a very different, as the INFO one is populated by other means?

When was it last loaded? Must have been some time ago if the VCF didn't change - the update to cancer SVs was like 9-10 months ago, and this has been handled the same way all that time?

Are you sure you did not simply load only the SNV VCF last time around?

**Comment by dnil** [comment]
Ok, so it seems you are trying to load the Sentieon one this time, not Balsamic?

``` cat /home/proj/production/cancer/cases/fullgibbon/analysis/scout/fullgibbon.scout.yaml 
analysis_date: '2020-01-15 16:53:01.298673'
...
track: cancer
vcf_cancer: /home/proj/production/cancer/cases/fullgibbon/analysis/vep/SNV.somatic.fullgibbon.tnscope.pass.vcf.gz

##SentieonCommandLine.TNscope=<ID=TNscope,Version="sentieon-genomics-201911",Date="2020-10-26T22:13:35Z",CommandLine="/home/proj/bin/sentieon/sentieon-genomics-201911/libexec/driver -t 24 -r /home/proj/production/cancer/reference/hg19/genome/human_g1k_v37.fasta -i /home/proj/production/cancer/cases/fullgibbon/analysis/bam/concatenated_ACC5821A11_XXXXXX_R.dedup.realign.bam -q /home/proj/production/cancer/cases/fullgibbon/analysis/bam/concatenated_ACC5821A11_XXXXXX_R.dedup.realign.recal_data.table --algo TNscope --tumor_sample concatenated_ACC5821A11_XXXXXX_R --dbsnp /home/proj/production/cancer/reference/hg19/variants/dbsnp_grch37_b138.vcf.gz /home/proj/production/cancer/cases/fullgibbon/analysis/vcf/SNV.somatic.fullgibbon.tnscope.vcf.gz">
...

```

My guess is it fails on the first SV variant it finds in that file (which is a mixed SV and SNV VCF). In particular:
```
1       724511  bnd_25426 ... SVTYPE=BND;MATEID=bnd_25427;SOMATIC;CSQ=BND|
```
Please separate your SV and SNVs, or make an issue/PR arguing for mixed files!

**Comment by dnil** [comment]
@keyvanelhami I'll give you a branch that can load this file in a moment, since there is no reason not to allow loading those AS SVs. But please take care to always only load SNV VCFs as SNV VCFs and split your SVs out into a separate SV VCF. This has caused confusion for the customers before, as the SV variants will not display as expected on the SNV view!

**Comment by hassanfa** [comment]
SV/SNV separation is causing some troubles recently (recent BALSAMIC release doesn't instruct variant callers to disable SV calls). It is in my backlog to split them properly.

**Comment by dnil** [comment]
Removing the constraint on "somatic" calls needing a "somatic_score" tentatively seems to have done the trick for loading. We are some 70k variants into the stage test now but the full 5M will take some time. 

This will not work terribly well in production for two well discussed reasons:
- separation of SV and SNV
- no ranking has been applied, and only "pass" level filtering from the looks of the given VCF file. Last time around for this case, you had a 6k variant filtered file. That sounded more in the reasonable ballpark for analysis! 😄

**Comment by dnil** [comment]
This was automagically closed. I do think it was the remaining fix for Scout for this issue, but please feel free to reopen and correct if needed! 😊
