### ISSUE TITLE
Problems with orderportalen when ordering balsamic + analysis 

### ISSUE THREAD

**Issue by heronikdin** [Clinical-Genomics/scout#2175]
Hi all! 

I have talked with Kristina Lagerstedt and patrik grenfeldt to try and solve this issue, I am now hoping someone can help me since we are not getting any further. 

For the TWIST myeloid samples we are trying to setup the same flow for ordering as the RD team. Meaning, we export a json file to orderportalen and then submit the order. However, when we choose "balsamic + analysis" instead of MIP, we get this message for samples ”please remove or save sample from case ”FXXXX”. Please note that there are no squares that are marked red, so in theory everything with the sample information is correct. And if we choose "MIP + analysis" the error message dissapears? So there seems to be something wrong with balsamic flow in orderportalen. 

Please ask me if something is unclear, but this is extremely important to solve as we want to start sending the myeloid samples to clinical genomics very soon... we are already behind schedule. Gitub doesnt allow me to upload the json file, so I dont know how to share it. If needed I can email it! 

Best Regards, HEro

**Comment by northwestwitch** [comment]
Hi @heronikdin I have never worked with orderportal so I'm not really sure how to solve this problem. I'm moving to cgweb pages, since the problem has to be fixed in another software and not Scout.

**Comment by northwestwitch** [comment]
Closing the issue here. Hopefully will fix it soon!

**Comment by elevu** [comment]
@heronikdin replying here since I cannot tag you in the other issue, could you send me the json file at eleonora.maccacaro@scilifelab.se ?

**Comment by heronikdin** [comment]
> Hi @heronikdin I have never worked with orderportal so I'm not really sure how to solve this problem. I'm moving to cgweb pages, since the problem has to be fixed in another software and not Scout.

Thank you @northwestwitch  :)
