### ISSUE TITLE
Add list type to gene lists in scout_config

### ISSUE THREAD

**Issue by moonso** [Clinical-Genomics/scout#218]
@ingkebil @robinandeer  this should be done by mip2scout

**Comment by moonso** [comment]
```type``` can be ```'research'``` or  ```'clinical'```

**Comment by robinandeer** [comment]
I agree! Do you know if we can pick this up from QC sample info? 

Can't use my computer unless I buy a charger but...

**Comment by moonso** [comment]
Not sure, we should ask @henrikstranneheim

**Comment by henrikstranneheim** [comment]
Research lists are under the key "RangeFile" and clinical lists are under the key "SelectFile" in qc_sampleInfo.

**Comment by robinandeer** [comment]
Added here: 7e70c8e3b93fc5d6bc67af20d1a02952d8574447
