### ISSUE TITLE
Set up a webhook to build and push a new Docker image to Docker hub every time the repo changes

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#2181]
I'm not sure how to do it, need to google

**Comment by moonso** [comment]
I created one based on version bump, have a look at https://github.com/Clinical-Genomics/housekeeper/blob/master/.github/workflows/build_and_publish.yml in the bottom of the file

**Comment by northwestwitch** [comment]
@moonso do I need to create those secrets somewhere? It's complaining that it can't log in

**Comment by northwestwitch** [comment]
yes, I need to set the DOCKER_USERNAME and DOCKER_PASSWORD secrets on this repo. But I'm not admin, could you do it when you have time?

**Comment by moonso** [comment]
Is this going to be hosted under clingen then?

**Comment by northwestwitch** [comment]
> Is this going to be hosted under clingen then?

Yes, it already is!

**Comment by moonso** [comment]
I have added `DOCKER_USERNAME` and `DOCKER_PASSWORD` to secrets now @northwestwitch

**Comment by northwestwitch** [comment]
> I have added `DOCKER_USERNAME` and `DOCKER_PASSWORD` to secrets now @northwestwitch

Thanks!
