### ISSUE TITLE
Submit variants to beacon directly

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#2185]
- Beacon will be --> https://github.com/Clinical-Genomics/cgbeacon2
- Create a role for users so only allowed users can send data to the beacon
- Create a button so when user clicks on submit they'll submit a link to the VCF file and the list of all genes to filter by.
- Only variants from affected individuals from a case will be collected and inserted into the beacon database.
- Create option to remove all variants from a case

**Comment by northwestwitch** [comment]
Does it sound like a good plan @henrikstranneheim ?

**Comment by henrikstranneheim** [comment]
Overall sounds good!

Some questions:
- Can they choose `clinical` or `research`, `snv|indel`, `sv` VCF (all, single)?
- Is the gene filter done by panel or can you submit your own list? Do you have to filter? It would be most powerful if they submitt the entire VCF(s).
- Why only affected individuals? Would we bias it if we allow all members to be submitted? We can send more info that just allele counts now.
- Can we add HPO-terms and other info as well or is it still just allele counts?

**Comment by northwestwitch** [comment]
Point-to-point replying:

> Some questions:
> 
> * Can they choose `clinical` or `research`, `snv|indel`, `sv` VCF (all, single)?

The could, why not? The default could be clinical SNVs/SVs and then they could switch to research vars if they want to.

> * Is the gene filter done by panel or can you submit your own list? Do you have to filter? It would be most powerful if they submitt the entire VCF(s).

I was thinking that the default gene list would be all genes in the default panels used to run the case.. ?

> * Why only affected individuals? Would we bias it if we allow all members to be submitted? We can send more info that just allele counts now.

Perhaps the user could choose to send all family or just the affected. The beacon doesn't really care, since it just accepts the list of samples to be used for variants extraction in the VCF

> * Can we add HPO-terms and other info as well or is it still just allele counts?

No, beacon version 1 doesn't accept phenotype terms. Beacon version 2 API on the other hand is implementing a broader spectrum of terms that will be stored and provided according to the 3 levels of clearance the query user has. v2 will have more info at the biosample level, where one could also specify phenotype: https://github.com/ga4gh-beacon/specification-v2/blob/master/beacon.yaml#L135. 
The technology is using phenopackets and sound much more complicated then the v1. Haven't started working on support for version 2 yet since they're still debating how it should be.

**Comment by henrikstranneheim** [comment]
> > * Can they choose `clinical` or `research`, `snv|indel`, `sv` VCF (all, single)?
> 
> The could, why not? The default could be clinical SNVs/SVs and then they could switch to research vars if they want to.

👍 

> > * Is the gene filter done by panel or can you submit your own list? Do you have to filter? It would be most powerful if they submitt the entire VCF(s).
> 
> I was thinking that the default gene list would be all genes in the default panels used to run the case.. ? But whole VCF could be submitted as well. the beacon doesn't care, you just don't send any genes.

The default sounds good, and I think that it would be good to be able to load entire VCFs (in a bright an shiny future, it will be uncontroversial) 

> > * Why only affected individuals? Would we bias it if we allow all members to be submitted? We can send more info that just allele counts now.
> 
> Perhaps the user could choose to send all family or just the affected. The beacon doesn't really care, since it just accepts the list of samples to be used for variants extraction in the VCF

👍 

> 
> > * Can we add HPO-terms and other info as well or is it still just allele counts?
> 
> No, beacon version 1 doesn't accept phenotype terms. Beacon version 2 API on the other hand is implementing a broader spectrum of terms that will be stored and provided according to the 3 levels of clearance the query user has. v2 will have more info at the biosample level, where one could also specify phenotype: https://github.com/ga4gh-beacon/specification-v2/blob/master/beacon.yaml#L135.
> The technology is using phenopackets and sounds much more complicated then the v1. Haven't started working on support for version 2 yet since they're still debating how it should be.

Yes lets wait and see how it goes, before we do anything.

**Comment by northwestwitch** [comment]
Waiting for this https://github.com/Clinical-Genomics/cgbeacon2/issues/109 to be in place first
