### ISSUE TITLE
Simplifying how config files or variables are passed?

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#2188]
I'll just drop it here. Yesterday I had such a hard time to figure out a way to pass the config file (and choosing which one) to containerized scout instances. We have such a messy way to pass these params to the app:

- When launching the **web server in production** we use an environmental variable named SCOUT_CONFIG that contains the path to a python file :https://github.com/Clinical-Genomics/scout/blob/b516befd39802718c36649346fdca234c8f75d41/scout/server/auto.py#L12

- When launching the **command line in production** we are forced to pass 2 config files: a yaml file and a python file. The yaml file contains the parameters for connecting to mongodb, the python file all the rest.  Take a look at the config files here: https://github.com/Clinical-Genomics/servers/tree/master/config/clinical-db.scilifelab.se
Everything can be incorporated in the python config file but we left it like this because if we remove the yaml config file as a parameter we have to release a major.

- **To launch both cli and server one file is more than enough (the python config!).**

- Having **config params as environmental variables** would be extremely good if we deploy scout on containers.

So my suggestion is when we move to the new server we could release a major where we remove support for the yaml config file and we add support for env variables params instead. Any idea at this regard?

**Comment by mikaell** [comment]
How about using MongoDB for storing configuration instead?

A way to link main python process to the db is needed, but then writing, reading and an easy overview and manipulation. This also allows for easy decoupling and reusability in our other softwares.

```
import config

config.read(xyz)
```

**Comment by northwestwitch** [comment]
I guess this is fixed now that we have deployed on a VM via Docker. Closing this issue
