### ISSUE TITLE
Create a collection containing all causative variants

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#2202]
The idea is upload less variants than what we do today (database is HUGE). Rank scout used for uploading variants is currently 5 and we would like to use a higher rank score (10?). If any variant was marked as causative and has score < 5 then it wouldn't be uploaded with the new settings. Including all causatives into a collection (where users might actively add variants of their choice, not necessarily from Scout), would allow that variant to be uploaded if it's found in another case.

If there is a causative with very low rank score that is not uploaded the user might always ask to load the research variants

**Comment by 4WGH** [comment]
HI, we all at CMMS are not really sure of the consequences of this. WE feel worried about removing known causative. Can we discuss this at a scout meeting?

**Comment by northwestwitch** [comment]
> HI, we all at CMMS are not really sure of the consequences of this. WE feel worried about removing known causative. Can we discuss this at a scout meeting?

Sure! The thing is we are changing server and we need to move the Scout database to a new one. The database is way too big and we'd like to do some cleaning. Basically removing **low-ranked variants that are not causative/pinned/commented/classified** from old cases that are solved or archived, so no worries!

But of course we'll discuss about it during the next meeting!
