### ISSUE TITLE
Deprecate load_scout?

### ISSUE THREAD

**Issue by moonso** [Clinical-Genomics/scout#2204]
There is a mysterious function called load scout in https://github.com/Clinical-Genomics/scout/blob/a5d0ee537ea1b7487740a0195078c7e9641c0df7/scout/load/all.py#L137

This has for a long time been used by the application CG to load cases into Scout. However that is now changed to using the more clean CLI api `scout load case`.

Perhaps it is time to deprecate that function if it is not used by other parts of the code or other collaborators. Maybe send out the question to representatives in Lund (@bjhall @ViktorHy @mhkc ) and Umeå (@ninanorgren ): 

How do you load cases into Scout?

**Comment by bjhall** [comment]
We're using the CLI, so deprecate away!

**Comment by northwestwitch** [comment]
What about you @leahkemp?

**Comment by leahkemp** [comment]
Thanks for checking with me @northwestwitch I've been using `scout load case` exclusively, so no problem by me!
