### ISSUE TITLE
Scout links to the wrong place when pressing different 'buttons'

### ISSUE THREAD

**Issue by emmser** [Clinical-Genomics/scout#221]
Scout often links back to the institution side when I'm trying to go somewhere else. It is solved by going backwards in the browser and then try again.

**Comment by robinandeer** [comment]
What do you mean by _often_ specifically? Can you provide an example of when this happens?

**Comment by vwirta** [comment]
I've witnessed this at several occasions (ca 5 times) during the weeks before Christmas. Always Emma's computer and Emma's profile.

**Comment by robinandeer** [comment]
It seems to be limited to about two weeks before christmas. We will deal with the issue if it appears again
