### ISSUE TITLE
Incorporate IARC TP53 database into Cancer Scout? 

### ISSUE THREAD

**Issue by heronikdin** [Clinical-Genomics/scout#2216]
Hi from cust 087! 

I was wondering if it is possible to integrate this database: [https://p53.iarc.fr/TP53GeneVariations.aspx](url) into Scout? We have the COSMIC link now, but this database is focused on TP53 variants and is of great importance to the clinicians within hematology/cancer. 

Best Regards, HEro

**Comment by dnil** [comment]
Lets see what can be done! If nothing else, they offer downloads so that would be possible to add via Balsamic. 

How about http://mutantp53.broadinstitute.org that they also recommend? That one has a simple REST api and can easily be linked. Is that interesting? Is it complementary or the same?

**Comment by hassanfa** [comment]
👍🏽 I think there is an interest to annotate based on known data sources. This could definitely be done in Balsamic side.

The data that they have seems to be some sort of tabulated txt file (i.e. not VCF): https://p53.iarc.fr/TP53SomaticMutations.aspx 

Maybe we can transfer this issue to Balsamic? But before doing so, how can we show this in Scout side? We have a `cosmic` tag.

I am thinking to have an evidence column: https://www.cbioportal.org/results/mutations?cancer_study_list=5c8a7d55e4b046111fee2296&case_set_id=all&gene_list=TP53 
screenshot here: 
![image](https://user-images.githubusercontent.com/1086877/100459768-4e490c00-30c6-11eb-9d49-06d16e369d0f.png)

It would be lovely to have icons for our favorite databases. CiViC and some cbioportal are on the horizon for Balsamic, maybe we can process and add tp53 one as well.

**Comment by northwestwitch** [comment]
> Maybe we can transfer this issue to Balsamic? 

Yes!

> I am thinking to have an evidence column: https://www.cbioportal.org/results/mutations?

That would be nice!

> It would be lovely to have icons for our favorite databases. CiViC and some cbioportal are on the horizon for Balsamic, maybe we can process and add tp53 one as well.

Yes, if it's not copyright infringement 😄

**Comment by dnil** [comment]
How about making a new issue in BALSAMIC linking to this? I think we can cover part of the request already with the current annotation to an extent, with a general link to the IARC tp53 page - in a gene context - plus direct links to any protein modifications through the Broad mutantp53. 

At any rate we should not spend too much effort on this exact page. From their news

> "28/08/2020 -  The IARC TP53 Database project will be transferred to another institution. The current version of the database (R20, July 2019) will remain accessible until February 2021 to allow users to download all available data. IARC thanks all contributors and data providers who made the success of this resource."

But, great! Scout can pick up most any tag that can be encoded on the VCF. If VEP can annotate any of them, we can pick it from the CSQ, otherwise a simple INFO tag should be enough for most cases. Just give them a reasonable name, and get back to us and we'll display it, be that in a column on the variants page or just on the variant page in an appropriate context! CiViC e.g. might fit rather well next to ClinVar there.. We currently treat Cosmic as a frequency annotation, and could keep building on those dbs that are more down that avenue

**Comment by hassanfa** [comment]
Sounds good. Can I please ask you to very briefly describe and add an issue in BALSAMIC? A bullet point with wishlist would be super. I'll try my best to address it asap.

**Comment by dnil** [comment]
If it was up to me, I'd say please focus on CIViC, OncoKB and possibly cbioportal first if this IARC resource is to expire/move labs in Feb 2021. Also, while most important, it is only one gene. We'll add links to IARC from the gene and to MutatnTP53 to the variant on the cancer variant page for now. If you don't mind terribly I think I could address #1239 at the same time. I would touch the same functions.

**Comment by hassanfa** [comment]
Adding cancer related databases to Scout is a great start.

**Comment by dnil** [comment]
Yes, and it is logical to start here so users can get a feel for what they want out of them. But as soon as priorities permit it will be really nice to have those annotated on the vcfs out of Balsamic / MIP. That way the information can be used for ranking, selective loading, filtering etc.

**Comment by heronikdin** [comment]
> Lets see what can be done! If nothing else, they offer downloads so that would be possible to add via Balsamic.
> 
> How about http://mutantp53.broadinstitute.org that they also recommend? That one has a simple REST api and can easily be linked. Is that interesting? Is it complementary or the same?
> 
> _edit_ It appears to be protein change only, but perhaps still of some interest. Deep linking into the iarc.fr interface does not seem easy, but I think we can forward the request for annotation to Balsamic - or what do you say @hassanfa?

If it is easy to incorporate into scout I do not mind, it is a nice complement but not what is recognized by clinicans.

**Comment by heronikdin** [comment]
> If it was up to me, I'd say please focus on CIViC, OncoKB and possibly cbioportal first if this IARC resource is to expire/move labs in Feb 2021. Also, while most important, it is only one gene. We'll add links to IARC from the gene and to MutatnTP53 to the variant on the cancer variant page for now. If you don't mind terribly I think I could address #1239 at the same time. I would touch the same functions.

Thank you for this info,I had no idea it would expire, and I agree on maybe focusing on the other portals. Thank you for the input, sounds great! I think in general it is of great interest as Hassan mentioned to incorporate cancer linked databases into scout.

**Comment by dnil** [comment]
Any others that you would like linked while we're at it @heronikdin? I did OncoKB (gene), CBioPortal (gene and variant), mutatntp53 (I e Broads IARC missense for variants) and the French IARC (gene): https://github.com/Clinical-Genomics/scout/pull/2218

**Comment by dnil** [comment]
> If it is easy to incorporate into scout I do not mind, it is a nice complement but not what is recognized by clinicans.

Mm, it seems the Broad MutanTP53 one is the same underlying IARC data, but only for missense?

**Comment by heronikdin** [comment]
> Any others that you would like linked while we're at it @heronikdin? I did OncoKB (gene), CBioPortal (gene and variant), mutatntp53 (I e Broads IARC missense for variants) and the French IARC (gene): #2218

we are also using [https://www.mycancergenome.org/](url) sometimes, but I dont know how much we can fit in?

**Comment by heronikdin** [comment]
> > If it is easy to incorporate into scout I do not mind, it is a nice complement but not what is recognized by clinicans.
> 
> Mm, it seems the Broad MutanTP53 one is the same underlying IARC data, but only for missense?

sorry, what did you mean? I didnt really follow...

**Comment by heronikdin** [comment]
> > Any others that you would like linked while we're at it @heronikdin? I did OncoKB (gene), CBioPortal (gene and variant), mutatntp53 (I e Broads IARC missense for variants) and the French IARC (gene): #2218
> 
> we are also using [https://www.mycancergenome.org/](url) sometimes, but I dont know how much we can fit in?

This site has ALOT of great info but I dont know if it is easy to take in aswell? But as said, a really good page with clinical trials, drugs, genes etc etc.

**Comment by hassanfa** [comment]
> > Any others that you would like linked while we're at it @heronikdin? I did OncoKB (gene), CBioPortal (gene and variant), mutatntp53 (I e Broads IARC missense for variants) and the French IARC (gene): #2218
> 
> we are also using [https://www.mycancergenome.org/](url) sometimes, but I dont know how much we can fit in?

mycancergenome is a great resource. I think this can also be added to Scout. stub uri seems to be https://www.mycancergenome.org/content/alteration and for say BRAF V600R: https://www.mycancergenome.org/content/alteration/braf-v600r (from their example).

**Comment by dnil** [comment]
Thank you; this is what it looks like in the dev version now:
![Screenshot 2020-11-30 at 18 20 45](https://user-images.githubusercontent.com/758570/100642501-23b2b980-3339-11eb-9d0c-0c0982dcad98.png)

**Comment by heronikdin** [comment]
> Thank you; this is what it looks like in the dev version now:
> ![Screenshot 2020-11-30 at 18 20 45](https://user-images.githubusercontent.com/758570/100642501-23b2b980-3339-11eb-9d0c-0c0982dcad98.png)

What is the "dev" version...?

**Comment by dnil** [comment]
The current "master" branch of this repository. It is the version building up to becoming the next production release in Solna. Expect to see it live sometime before Christmas!

**Comment by heronikdin** [comment]
> The current "master" branch of this repository. It is the version building up to becoming the next production release in Solna. Expect to see it live sometime before Christmas!

Fantastic! Thank you :)
