### ISSUE TITLE
KNOWN ISSUES with new version of Scout

### ISSUE THREAD

**Issue by ingkebil** [Clinical-Genomics/scout#222]
- [x] 1. In the gene list overview: too many gene lists are loaded here. This does not affect the analysis and is only a problem with the overview. @moonso 
- [x] 2. Coverage report does not render. @robinandeer
- [x] 3. Genes in gene list are not sorted #220
- [x] 4. Scout often links back to the institution side when trying to go somewhere else #221

**Comment by robinandeer** [comment]
2. This was an issue in the "chanjo-report" package which has been fixed and we are now depending on the new version of that package.
