### ISSUE TITLE
Cannot add OMIM gene ID to cases

### ISSUE THREAD

**Issue by Leif-glitch** [Clinical-Genomics/scout#2225]
I have been adding OMIM phenootype and gene IDs' prepparing for a Clinvar submission. During this process i could not add the gene ID in the Case page and just get an error message, see below. 

![image](https://user-images.githubusercontent.com/63041167/100721166-48ea0b00-33bf-11eb-81fa-93be8153a759.png)

I tried to repeat this for both families (11 and 213) but also for a newer family (20193) but it does not work for any so far.

![image](https://user-images.githubusercontent.com/63041167/100721374-89e21f80-33bf-11eb-80ab-62815b9c4bbb.png)

Is there a general error regarding this function?

**Comment by northwestwitch** [comment]
Hi @Leif-glitch,  it's quite hard to understand the OMIM term you tried to add to the case from the picture, could you write it here? And is it just that term or also other terms?

**Comment by northwestwitch** [comment]
Or perhaps I don't have the functionality so clear in my mind. What is that one types inside OMIM genes and what should be shown once it's saved?

**Comment by northwestwitch** [comment]
All clear, just spoke with Michela

**Comment by northwestwitch** [comment]
I went back in time and 2 years ago (scout version release-4.1.4) to see how it worked and what was disrupted.

Let's take for instance this OMIM term: https://omim.org/entry/180200 that has this OMIM gene:
https://omim.org/entry/614041

OMIM term in Scout accepted anything as long as it had a prefix OMIM: 

![image](https://user-images.githubusercontent.com/28093618/101375148-5a478180-38af-11eb-9830-849cb6b3d6d1.png)

So you could type either the disease 180200 or the gene 614041:

![image](https://user-images.githubusercontent.com/28093618/101374986-279d8900-38af-11eb-8ad3-52eea9fe87dd.png)

Which is conceptually wrong because it should accept only the OMIM gene. The problem is that we don't save OMIM gene ID in the database for the OMIM terms, only the gene hgnc id (9884 for the gene RB1):

![image](https://user-images.githubusercontent.com/28093618/101375534-cde98e80-38af-11eb-87c9-1ece4b520c89.png).

Since we have no way to check that the OMIM gene is correct we should probably just leave it as free text and it will be up o the user to provide the right term

**Comment by dnil** [comment]
Mhm, that field has ever felt more than a little redundant for anything but searches or link out. What in particular does it get written to on the submission forms? The Gene symbol for ClinVar is and must be HGNC. I actually thought it was just a relatively unused field that someone had wished to have there as a fallback for cases when no condition was available, e.g. a new disease gene where an OMIM gene may be available, or possibly when multiple ambiguous conditions exist and one simply doesn't what to choose whatever RASopathy-like condition the patient might have?

**Comment by northwestwitch** [comment]
The OMIM gene is not used in ClinVar submission form, only the OMIM diagnosis (180200) see for instance the form for the case above:

![image](https://user-images.githubusercontent.com/28093618/101378267-2e2dff80-38b3-11eb-9a06-e274a3f9f4f0.png)

Why do you need the OMIM genes for ClinVar @Leif-glitch @4WGH ?

**Comment by 4WGH** [comment]
I can not rember why but it was a whish from the doctors when we staterd to submitt variants to ClinVar.
Could it be that sometime in not strait forward from the phenotype name what is the connected gene?

or in a case like this one: we need to speocify which is the gene of interest : ACADVL and not DVL2.
[cid:49904836-6ebe-487a-9aa3-c027817a12af]
________________________________
Från: Chiara Rasi <notifications@github.com>
Skickat: den 7 december 2020 17:43
Till: Clinical-Genomics/scout <scout@noreply.github.com>
Kopia: Michela Barbaro <michela.barbaro@sll.se>; Mention <mention@noreply.github.com>
Ämne: Re: [Clinical-Genomics/scout] Cannot add OMIM gene ID to cases (#2225)


The OMIM gene is not used in ClinVar submission form, only the OMIM diagnosis (180200) see for instance the form for the case above:

[image]<https://user-images.githubusercontent.com/28093618/101378267-2e2dff80-38b3-11eb-9a06-e274a3f9f4f0.png>

Why do you need the OMIM genes for ClinVar @Leif-glitch<https://github.com/Leif-glitch> @4WGH<https://github.com/4WGH> ?

**Comment by northwestwitch** [comment]
Reading the instructions from ClinVar submission spreadsheet, when it comes to specifying the associated phenotype, it doesn't mention anything about OMIM genes, just the condition ID, specified by OMIM, OMIM, MeSH, MedGen, UMLS, Orphanet, HPO, MONDO IDs.
  

![image](https://user-images.githubusercontent.com/28093618/101459357-6c213700-3938-11eb-8f8d-17033f51097d.png)

The gene name is reported instead in another column, the one named gene. This column accepts HGNC gene symbols, and in Scout is the first field of the figure I posted above.

![image](https://user-images.githubusercontent.com/28093618/101459661-d043fb00-3938-11eb-8837-56dbaa14c667.png)

If a clinician wants to check that the OMIM diagnosis is accurate during a ClinVar submission, she/he can click on the link on the OMIM term and a new browser page will open to the OMIM term that contains all the specifics, including genes:

![image](https://user-images.githubusercontent.com/28093618/101460063-5f511300-3939-11eb-941d-3c5402472a27.png)


The OMIM gene form is bugged and I'll fix it to accept any numerical value, but I don't think you need it for submitting to ClinVar

**Comment by northwestwitch** [comment]
This bug is fixed, from next scout version you'll be able to add OMIM gene ids (numerical IDs). Just keep in mind that these IDs are not validated by scout, so it's up to the user to enter correct values.
