### ISSUE TITLE
December 2020 release of the HPO

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#2240]
New release yesterday, we need to update : https://github.com/obophenotype/human-phenotype-ontology/releases/tag/v2020-12-07

**Comment by dnil** [comment]
🤞 that it is only a local load needed..

**Comment by northwestwitch** [comment]
Shall we update tonight? Sounds like a good time given that hasta will be down

**Comment by dnil** [comment]
As soon as its back stably seems like a Good Plan!

**Comment by northwestwitch** [comment]
> As soon as its back stably seems like a Good Plan!

What, HPO or Hasta? I'd test it on stage database first

**Comment by dnil** [comment]
Good, then agreed, it should really be quite independent of hasta.

**Comment by northwestwitch** [comment]
Hasta was up again before I had time to run the commands, so I missed the window. Let's update some other time, to be coordinated with production
