### ISSUE TITLE
TP53 variant link appears to load query page

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#2244]
The TP53 variant link appears to sometimes load query page on http://mutantp53.broadinstitute.org, rather than variant page directly, though it works on direct GET of that link from an established session. Investigate! Some parameter, like frequency that needs to be set once on mutantp53??

**Comment by hassanfa** [comment]
Could this be solved in Bioinfo analysis stage? In case Scout doesn't want to do lots of GET requests?

**Comment by dnil** [comment]
I think we should do both! In this case, the GET is user initiated, so no large overhead.  For ranking / scoring / filtering, we definately would like it to done at an earlier annotation stage - issuing multiple GETs to external resources for each and  variants would make the system very brittle.

**Comment by dnil** [comment]
First time visits to the TP53 page apparently get redirected to their banner page rather than responding to the query. The next visit from the same browser works as intended, also with other variants queries. Unclear if this can be avoided?

**Comment by northwestwitch** [comment]
I don't know if it's the same thing but looks like variants which DON'T have the protein description in the HGVS field are failing to load the mutantp53 page. 

For instance the link for this variant works:

![image](https://user-images.githubusercontent.com/28093618/102072749-9bd1b280-3e02-11eb-95cc-11c88f4495b0.png)
https://scout.scilifelab.se/cust002/F0034775/6cd4a32a68c7e32b532680693d3138ed


The link for this other variant doesn't:
![image](https://user-images.githubusercontent.com/28093618/102072828-b310a000-3e02-11eb-9291-1f86c53a3002.png)
https://scout.scilifelab.se/cust002/F0033853/6d39112f8f328f8bc67bb33388adbfcc

**Comment by dnil** [comment]
Ah, no, not the same. The idea was that the TP53 link should not be made if no HGVS_P was available. Perhaps it is an empty string, space or sth else here, or the None test is not quite working. It would not exactly be the first time. I'll check!

**Comment by dnil** [comment]
Thanks, the latter is being fixed in a new PR, but the original issue still sort of remains.
For the first visit during a session (unclear how long), the site will offer a redirect to "http://mutantp53.broadinstitute.org/heatMap/login" instead of answering the query. Repeating the query will go to the right place though..
