### ISSUE TITLE
HPO gene list pdf contains genes not in clinical panels

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#2246]
HPO gene list pdf export may include genes not on any clinical panel. This is sometimes desired (as when research has been opened to allow full HPO search) and sometimes not (as when using HPO to further narrow a large clinical panel). 

This is somewhat philosophical, as the gene lists are used clinically, but there is merit in only including genes that have actually be triaged, for future proofing the reports. If one of the HPO genes will be added to the clinical panel next year, it would be a problem to have reported is as investigated when it wasn't.

Investigate adding a toggle?

**Comment by northwestwitch** [comment]
This was nicely fixed by you, @dnil, in #2486. Closing this issue
