### ISSUE TITLE
Alignment view

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/scout#225]
Would be great to get the vcffile track in the alignment view as well and a coverage track

**Comment by robinandeer** [comment]
VCF file must be loaded as a whole for each variant so we need to think about how we do this

**Comment by robinandeer** [comment]
Let's sit down together with this @moonso or perhaps @guillermo-carrasco would like to join as this would be used in https://github.com/robinandeer/puzzle as well :)

**Comment by moonso** [comment]
This is still a fairly hard problem, this is the reason why nothing happens.
We could start by trying to create a VCF file with all variants from the gene that the variant belongs to and then load that into the alignment browser
