### ISSUE TITLE
Is `/scout/server/userpanel.py` in use?

### ISSUE THREAD

**Issue by mikaell** [Clinical-Genomics/scout#2263]
Is /scout/server/userpanel.py in use? The module declares one function `parse_panel(csv_stream): -> genes:List`.

It is not covered by any tests and I could not find it when grepping the codebase.

```
$ grep -rin parse_panel\( *
build/lib/scout/server/userpanel.py:5:def parse_panel(csv_stream):
scout/server/userpanel.py:5:def parse_panel(csv_stream):
grep: tests/parse/.#test_parse_panel.py: No such file or directory

$ grep -rin userpanel *
Binary file dist/scout_browser-4.27-py3.7.egg matches
Binary file dist/scout_browser-4.27-py3.8.egg matches
Binary file dist/scout_browser-4.23-py3.7.egg matches
Binary file dist/scout_browser-4.25-py3.7.egg matches
Binary file scout/server/__pycache__/userpanel.cpython-37.pyc matches
scout_browser.egg-info/SOURCES.txt:387:scout/server/userpanel.py
grep: tests/parse/.#test_parse_panel.py: No such file or directory

```

**Comment by dnil** [comment]
No, apparently not! Nice find!
`git grep parse_panel ` agrees, and a quick look at "blame" looks like it was made by Robin four years ago. I'd guess it was made obsolete by the panel load/parse cli. It looks perfectly safe to cut it - we can always revert.

**Comment by mikaell** [comment]
I'll remove it.

**Comment by mikaell** [comment]
Created pr #2272.
