### ISSUE TITLE
Link to 'Clinical variants' does not limit results to expected gene list

### ISSUE THREAD

**Issue by vwirta** [Clinical-Genomics/scout#227]
When clicking the 'Clinical variants' link from the list of cases page, the linked page does not have the predefined gene list selected.

**Comment by robinandeer** [comment]
Can you give us an example (link) on when this happens. We could not replicate this

**Comment by vwirta** [comment]
Is the new Scout still online? Unable to login to try replicate

**Comment by vwirta** [comment]
too quick to close :)

**Comment by robinandeer** [comment]
Sorry, it's up again @vwirta :smiley:

**Comment by robinandeer** [comment]
I still can't replicate this. Perhaps it was related to when some links randomly took the user back to the index page?

**Comment by vwirta** [comment]
This seems to work for some cases as expected, but not for all.
Going from here: https://clinical-db.scilifelab.se:8081/cust003
to case 15053 'clinical variants' lists all variants without a predefined gene list. This was the only example I could find right now.

Going to case 15035-miptest works as expected.

Something how MIP was run?

**Comment by vwirta** [comment]
This seems to work as expected in the new version of Scout. Closing.
