### ISSUE TITLE
Outdated oauth configuration in README

### ISSUE THREAD

**Issue by mhkc** [Clinical-Genomics/scout#2283]
The Oauth configuration described in the README is outdated. Current implementation requires the Oauth v2 variables `client_id`, `client_secret` and `discovery_url`.

Scout does not validate these variables or crash if they are not set.

**Comment by northwestwitch** [comment]
Yes, sorry for that, we need to fix that page!

You can find updated info here: https://github.com/Clinical-Genomics/scout/blob/577d1aba4e6ba677b1bf551273dfece608f5f4b8/docs/admin-guide/login-system.md
