### ISSUE TITLE
My Cancer genome link does not work

### ISSUE THREAD

**Issue by heronikdin** [Clinical-Genomics/scout#2286]
Hi! 
MCG link button does not work, I get this message all the time: 

![image](https://user-images.githubusercontent.com/62098218/104440443-a82c6500-5592-11eb-80c0-b6d4f9c11fb6.png)

Can you please help or do you know what the issue is? 

Regards, Hero

**Comment by northwestwitch** [comment]
Hi @heronikdin. Do you have a specific variant with links not working? I've tested this ones:
https://scout.scilifelab.se/cust087/unitedaphid/27b33e25b3b4931bce6f7f54455504fd 
https://scout.scilifelab.se/cust087/awakekoala/63832ccc0e66b89a75126aa551161d40

and they seem to work

**Comment by heronikdin** [comment]
Hi @northwestwitch 
Ok, thats good to know, so basically if the vriant is not there I will get an error message and if it is there it will surely come up? Just making sure, becasue many variant I have looked up does not come up. 

Regards, HEro

**Comment by northwestwitch** [comment]
I'm not sure, I never used My Cancer Genome. Have you tried searching those with the link that doesn't work using the search form: https://www.mycancergenome.org/content/biomarkers/ ?

**Comment by dnil** [comment]
Thanks for the report @heronikdin! There may absolutely be some mismatch with the variant nomenclature - you know how picky things can be with different variant types, transcripts, transcript versions, hgvs normalisation etc - so a couple of non-working examples will be brilliant!

**Comment by heronikdin** [comment]
ok, let me get back to you on that. I will use the link you send @northwestwitch and compare. 

Thanks!

**Comment by northwestwitch** [comment]
This one doesn't work: https://scout.scilifelab.se/cust087/F0037910/c84da1539be5e01a3abb674d3cfb8ecc

**Comment by dnil** [comment]
Nor this for instance: https://scout.scilifelab.se/cust087/awakekoala/97a89ff3796a065a2327fca002f72480

A quick search at MCG finds none of them. Coincidentally, we are currently listening in on a seminar about TP53 mutation, and it was not on that list either.. 😉

**Comment by dnil** [comment]
We can make these more adaptive as soon as annotation of them are integrated into Balsamic. In theory, even without pre-annotation, we could also poll MCG for existence of the variant before adding the link out, but that would slow the system down a bit.

**Comment by northwestwitch** [comment]
Sounds like a good plan @dnil (checking in the VCF annotation). This is not the only link that doesn't work if the data is not present on the external server and if we start to check them all before loading the page it will be significantly slower I think.. So I suggest we go with the Balsamic annotation (is it already on balsamic task list?)

**Comment by dnil** [comment]
I'd say it is at least mentioned here: https://github.com/Clinical-Genomics/BALSAMIC/issues/1249. Let's close for now and revisit when a direct or proxy annotation for this is present on Balsamic VCFs. We do have the blind link outs for now.
