### ISSUE TITLE
mtDNA deletion analysis

### ISSUE THREAD

**Issue by NicoleCMMS** [Clinical-Genomics/scout#2291]
Notes from a meeting today with Daniel Nilsson, Henrik Stranneheim, Anna Wredenberg and Nicole Lesko:

- discussed how best to identify mtDNA deletions in muscle WGS samples.  Current approach is identification of read pairs that are separated by >3 kb but <15 kb and compare this to 'normal read pairs' which are <3 kb but >15 kb. 

- decided to run this analysis on all muscle samples currently run by WGS in order to compare normal versus samples known to contain mtDNA deletions (both single and multiple deletions).

- will also test lowering the length of the read pairs from 3 kb to ~1.2 kb for the calling of abnormal reads.

- once data has been collected it can be plotted to see the normal spread of deleted mtDNA and differences between age groups can be determined. A few positive controls have been sequenced within this material which have previously been shown to contain mtDNA deletions by Southern blot....unfortunately there are not many cases!  However, any outliers observed in this data can subsequently be analysed by Southern blot in order to determine if we have missed some cases in the past. 

- information to be retrieved from Scout should if possible include subject name, gender, phenotype, analysis date, tissue and age.

Did I forget anything?

**Comment by dnil** [comment]
Thanks @NicoleCMMS; the action item for this repo (Scout) will be adding discordant read pair measures to the MT report, but first after analysis completes, and presumably we have a name for the variables from MIP / mitoSign. Until then it will rest here.

**Comment by dnil** [comment]
This is now available from MIP 11! Files are delivered to HK as `<sampleID>, scout, mitodel`. Will need
- [ ] CG integration for the scout load config
- [ ] parsing
- [ ] a place to display it (e.g. in the mt-report)
