### ISSUE TITLE
New Scout: Sanger ordering

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#230]
I did a test to order Sanger.
The link now work and send back to the variant: Great!
But I've not received the e-mail with the order. I do not know it if is because we are testing or a bug. So I let you know :)

**Comment by robinandeer** [comment]
Great :smiley: 

It's set up so that I receive the email for the testing version

However, you should receive a confirmation email to your "@clinicalgenomics.se" email that you use to login to Scout
