### ISSUE TITLE
Structural variants alignment in IGV shows entire genome

### ISSUE THREAD

**Issue by ielvers** [Clinical-Genomics/scout#2305]
Hi,
When looking at structural variants, I can view the individual breakpoints in IGV but when I click the IGV button to view the entire SV, I get the whole genome (it used to be an overview of the region with the SV including both breakpoints). This is not case-specific and it's been like this for a couple of weeks.
It's obviously not a big issue, but I hope it can be reverted to the previous settings. Thank you!

**Comment by dnil** [comment]
Thank you - I can confirm this is a general problem with so far unknown origin; we haven't changed that precise function lately. We will check: perhaps something to do with the version bump of IGV, or an indirect consequence!

**Comment by dnil** [comment]
Thank you again! 👍  

This should now be solved on the development version. We are planning a new production release for the end of the week. At any rate you will find this in the next production release.
