### ISSUE TITLE
Broken tooltips on case page

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#2307]
On current master, not prod

**Comment by dnil** [comment]
Oops? That is probably me - I added some with the group cases PR. 😓 

I have meetings most day, so if you have time, feel free - otherwise I'll fix tomorrow!

**Comment by northwestwitch** [comment]
Looks like it's this js function:

![image](https://user-images.githubusercontent.com/28093618/105972271-bc408e00-608b-11eb-91cf-3e1fdc70a023.png)

![image](https://user-images.githubusercontent.com/28093618/105972327-ce223100-608b-11eb-8dd7-3ebb2ea2e9d4.png)

I don't think it was you @dnil!

**Comment by dnil** [comment]
😅 Off the hook then - the danger of importing stuff instead..  But same applies work wise! 😸

**Comment by northwestwitch** [comment]
It happens whenever there are no associated panels to a case. In my case I was testing something else on the cancer demo case. Found a solution, I'll open a PR soon
