### ISSUE TITLE
IGV gene track 

### ISSUE THREAD

**Issue by AnnHam** [Clinical-Genomics/scout#2323]
Hej, when looking at the GCH1 gene in IGV I'm now missing the gene (the blue exon/intron) in the IGV gene track. See attached file with screenshot before and after the update(?) - Update IGV.js to latest (v2.7.4). (It's the same result when my colleagues check the same region in IGV for other cases). 

[GCH1_IGV.pdf](https://github.com/Clinical-Genomics/scout/files/5894306/GCH1_IGV.pdf)

**Comment by dnil** [comment]
There we go! Finally something to bug fix - right @northwestwitch!

Seriously, thanks, will check!

**Comment by northwestwitch** [comment]
Thanks @AnnHam, we'll work on it!

**Comment by dnil** [comment]
Its one of those intermittent things as well; zooming and changing settings a bit back and forth brings the track back.

**Comment by dnil** [comment]
Yep, it is very reproducible, but zooming out until you see the whole gene, then zooming back in appears to solve it for me. You could try that as a workaround for now @AnnHam, and we'll get back to you once we have more info..

**Comment by northwestwitch** [comment]
Yes, the zooming out and in again works for me as well, let's check if there's an issue with this version of igv.js

**Comment by northwestwitch** [comment]
Doesn't look they have any specific open issue about this. Before opening an issue in their repo we could check how their [development branch code](https://igv.org/web/snapshot/dist/igv.js) performs and if it's fine we could revert to the previous version and update when they release the next version. Or we could revert and open an issue in their repo now.

**Comment by dnil** [comment]
Yeah I see it working in igv.js 2.7.0, breaking from 2.7.1 onwards. Have not tried dev yet.

**Comment by northwestwitch** [comment]
Here: https://github.com/igvteam/igv.js/issues/1261
