### ISSUE TITLE
 Unify codebase with molecuar diagnostics Lund

### ISSUE THREAD

**Issue by mhkc** [Clinical-Genomics/scout#2324]
We in Lund has made the following changes to Scout code base. For more information please look at [our fork](https://github.com/Clinical-Genomics-Lund/scout/tree/production).
- [x] Removed genome build from DECIPHER button
- [x] Added button that opens [GENS ](https://github.com/Clinical-Genomics-Lund/gens)to case view and SV variant view. https://github.com/Clinical-Genomics/scout/pull/2368
- [ ] Added button for correcting family metadata and submit a reanalysis of VCF files. https://github.com/Clinical-Genomics/scout/pull/2371
- [x] Added Dockerfile. Refactor LoqusDB settings parsing and introducing Loqus queries via REST API #2349 
- [x] Added link for primer ordering to Sanger sequencing request email
- [ ] Custom variant evaluation terms (manual rank and dismiss options) 
**NOTE: there might be more to come**

Most things are minor changes and could be solved by allowing to add custom fields. The "edit metadata and submit for reanalysis" is more elaborate and should be an optional feature. However it would require that we define a "standard RESTapi" which Scout uses to communicate with a custom service that each site is responsible for setting up. This might be a feature that could be implemented in the future.

**Comment by northwestwitch** [comment]
OK! I was afraid it would me much more different, but this is very mergeable I think! 
That note on the other hand .. 😆

**Comment by mhkc** [comment]
How do you think the very Lund specific changes (Gens & rerunner) should be implemented?

I guess the easiest solution would be to only display the integration if related variables are set in the config. 
Another, more involved, method could be to expand the ability to define custom data fields in the case yaml file.

**Comment by dnil** [comment]
Display-if-available sounds the absolute best! That way everyone else can also use the integration as soon as they get off their butts and start using Gens & rerunner! 😸

**Comment by northwestwitch** [comment]
I wouldn't mind start using Gens in Stockholm as well, and fixing rerunner to be general enough to send requests to our [cg](https://github.com/Clinical-Genomics/cg) software

**Comment by dnil** [comment]
Same here.. Gems is a little complicated for us as it is right now with how cases are stored, but it would be changeable if someone has the interest. We could have a a project student on that one - @moonso, wouldn't you like to supervise one formally before you are defending perhaps? Or you C? You know array data well enough!

**Comment by northwestwitch** [comment]
Yes, that would be fun!

**Comment by bjhall** [comment]
This PR fixes the DECIPHER button confusion: https://github.com/Clinical-Genomics/scout/pull/2347

So you can scratch that from the list @mhkc

**Comment by bjhall** [comment]
And this fixes the Sanger ordering emails: https://github.com/Clinical-Genomics/scout/pull/2348

**Comment by bjhall** [comment]
I realized there is one more thing that needs to be sorted out related to this issue. We've discussed this before, but I don't think we found a good solution.

It relates to `CALLERS` in `scout/constants/__init__.py`. To me this is configuration stuff and should not be hardcoded (since different sites will always be using different callers). 

Similarly we've changed the `DISSMISS_VARIANT_OPTIONS` in `scout/constants/variant_tags.py`. In this case I do, however, think it would be nice if the geneticist of the different sites could agree on a set of terms that would work for everyone... But that might be easier said than done.

**Comment by dnil** [comment]
Much agree! The latter one would be an interesting exercise; it took our different clinics a while to converge even though they were borrowed fairly cleanly from previous lab systems for classical techniques (Sanger, aCGH). We will have to alter handling of those in a few places I guess, especially thinking ahead to potentially sharing case- and classification data. Then we may need a mapping between the different site classifications if we can't agree. Still, ACMG will be interchangeable so not the end of the world.
