### ISSUE TITLE
Coverage and QC report complementary/replacement to Chanjo report

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/scout#2328]
Long story short, Chanjo doesn't work for panels. QC+coverage report is an HTML file generated by BALSAMIC via cg: https://github.com/Clinical-Genomics/cg/issues/930

What's needed:
- Preferably a tag in Scout config file to reflect coverage and qc report
- Disable Chanjo report if above file is not in the config (the new report will replace that)
- Report is HTML, should I convert it to PDF? (I prefer HTML)

Thoughts?

**Comment by hassanfa** [comment]
Report looks like this on a dummy Scout case: https://scout.scilifelab.se/cust666/coverage_test/multiqc

**Comment by dnil** [comment]
Closed by #2331 I believe @hassanfa? Thank you!
