### ISSUE TITLE
IGV error message + sometimes missing gene track

### ISSUE THREAD

**Issue by ielvers** [Clinical-Genomics/scout#2332]
Every time I open IGV I get an error message:
Cannot read property 'startsWith' of undefined: https://cors-anywhere.herokuapp.com/https://s3-eu-west-1.amazonaws.com/pfigshare-u-files/25777457/GRCh37.variant_call.clinical.pathogenic_or_likely_pathogenic.vcf.gz

I've also noticed that the gene track is missing in IGV in all variants I've checked in case 21012, whereas in cases 21010 and 21013 the gene is sometimes displayed and sometimes not. It appears like there's less variants (but sometimes a few) in the ClinVar track when the gene track is missing.

Case 21012, random exonic variant missing the gene track and showing the error message:
![image](https://user-images.githubusercontent.com/57791644/106716473-c409b080-65fe-11eb-9dcb-5f6a35cd311f.png)
(variant https://scout.scilifelab.se/cust003/21012/1875e64db0ae49921a4a52cdf4057624)

Thank you!

**Comment by dnil** [comment]
Thanks! We have updated IGV.js and added some track related things lately.

 Two things here:
- the gene-track-not-showing is known (#2323). While we wait for the IGV.js team to fix, we will revert IGV.js to before that problem with the next release of Scout (#2329) - likely already this week. In the meantime, if you zoom out and back in again the genes reappear.
- the fig share error is very interesting! We haven't seen that one before. It is working from over here. Are you on the hospital network or on a VPN from somewhere else? You can try disabling that track using the Settings button next to the IGV button, uncheck the dbVar one and hit Save. Next time you open you should not see it.
-

**Comment by ielvers** [comment]
Thank you! Yes I'm on the hospital network and my officemates get the same error message. Your track disabling solution works perfectly. Thanks for your help!

**Comment by northwestwitch** [comment]
The fig sharing error is likely due to this: https://github.com/Rob--W/cors-anywhere/issues/301. It needs fixing and in the meanwhile we might need to remove the dbVar track that used this service.

**Comment by northwestwitch** [comment]
possible solution: https://gist.github.com/enjalot/2904124

**Comment by dnil** [comment]
Ok, closing this for now with #2333. The changes as usual go into our development "master" first, and will be reach you with the next Scout release - possibly tomorrow, but soonish at least.
