### ISSUE TITLE
Allow users to register to our mailing list

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#2336]
It would be nice to have a form allowing users to subscribe to our mailing list, since not all Scout users are registered as customers of Clinical Genomics Solna

**Comment by dnil** [comment]
Ping @moonso?

**Comment by moonso** [comment]
I leave the decision in your hands. Do you want me to make you both admins on the existing one?

**Comment by dnil** [comment]
Thats fine I think? I can check later if we can create new groups for CG as well; "worst" case I suppose we can do that off the regular scilifelab google account anyway. Then we can argue a bit about the best way to divide it. Preserving @vwirta's view of one list distinctly serving Solna CG Scout customers is a given.

**Comment by moonso** [comment]
Great, I've made you `manager` @dnil , @northwestwitch already was. I could not make you owner cause I don't have the permission and I could not see who is owner.

**Comment by northwestwitch** [comment]
Thanks @moonso, could you post here or privately the link to the scout group?
