### ISSUE TITLE
Long scrollable list views loose top/bottom fields in safari

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#234]
I'm having trouble navigating to the top/bottom of long lists, as in Transcripts or Proteins, in Safari. Seems to be working fine in Firefox. Might be a Safari-feature more than a Scout one; but perhaps there is some magic attribute to be set to amend it?

E.g. 
https://clinical-db.scilifelab.se:8081/cust002/F0001933-miptest/variants/9f779c6ac88f21591ca4c3214006cfc6

**Comment by robinandeer** [comment]
Good catch @dnil!

I made a mistake in the CSS but hadn't noticed :P
