### ISSUE TITLE
CANCER scout: Remoxe exac --> change to gnomad

### ISSUE THREAD

**Issue by heronikdin** [Clinical-Genomics/scout#2340]
Hi! 
As promised, an issue related to what we discussed regarding exac and gnomag, I think @hassanfa and I have talked about this before. 
The issue lies here, we would like to see the gnomad frequencies instead of the exac freq. For instance, in the pic below you can see that we have made a global comment on that the variant is present in approx 70-80% of the population (based on gnomad).
![image](https://user-images.githubusercontent.com/62098218/107023696-492fc980-67a7-11eb-85b8-4172b7104bd6.png)

Do you know what the status of this issue is @hassanfa ? 

Regards ,HEro

**Comment by hassanfa** [comment]
I think We should rename Exac to something more general, not just gnomAD. How about `Pop. Freq`? Although, COSMIC will not fit in `Pop. Freq` definition.

**Comment by heronikdin** [comment]
works for me! @hassanfa As long as the variants found that are common can be filtered out, instead of a global comment :)

**Comment by heronikdin** [comment]
Wow... is there a tracking of all the spelling errors  I am making and trying to spell it correctly whilst creating an issue!!! Sorry about that!

**Comment by hassanfa** [comment]
> Wow... is there a tracking of all the spelling errors I am making and trying to spell it correctly whilst creating an issue!!! Sorry about that!

You should see my issue :-) Github tracks everything! 😂
