### ISSUE TITLE
Add transcript fusion report link to reports section in existing case page

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/scout#2343]
**Background**
When analysing an individual it is common to start with a DNA analysis. However, often a causative variant is not found and the same individual also are subjected to a RNA analysis. 

**Challenge**
Currently, there is no way to combine the output from the standard DNA analysis with the selected output from a RNA analysis in Scout. It would be great to be able to update the DNA case view with information on transcript fusions in the form of a pdf report that can be viewed/downloaded from Scout.

**Suggested solution**
- Add the option in `scout case update` to also be able to upload a link pointing to a transcript fusion report from a secondary analysis to an already existing case.
- Also support this from the scout load config
- Add the optional transcript fusion report to the reports section in an already existing DNA analysis case.

**Comment by dnil** [comment]
Do you have a key name already from MIP or cg? Otw we just invent one and map it in cg later.

**Comment by henrikstranneheim** [comment]
Hmm, seems like the MIP RNA tags were lost in the migration to Hermes. We will have to reimplement them in Hermes and cg for the report. 
However, I guess we can agree on a key name here and then use that throughout. @jemten Do you have a suggestion?

**Comment by jemten** [comment]
> However, I guess we can agree on a key name here and then use that throughout. @jemten Do you have a suggestion?
`fusion-report` or `arriba-report` maybe?

**Comment by northwestwitch** [comment]
Is this a tsv file?

**Comment by jemten** [comment]
It's a pdf. I could generate a vcf as well

**Comment by northwestwitch** [comment]
Damn, I assumes it was a tsv 🤔

**Comment by jemten** [comment]
We could give you a tsv a well if you want ;)

**Comment by northwestwitch** [comment]
Naaa, it's very easy to change it into pdf in my PR, but I  appreciate the offer, thanks 😁
