### ISSUE TITLE
Display RNA alignment data in snv/indels variants view on existing case

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/scout#2344]
**Background**
When analysing an individual it is common to start with a DNA analysis. However, often a causative variant is not found and the same individual also are subjected to a RNA analysis. 

**Challenge**
Currently, there is no way to combine the output from the standard DNA analysis with the alignment output from a RNA analysis in Scout. It would be great to be able to update the DNA snv/indel view with alignment information for the RNA analysis in the form of a Sashimi plot: https://software.broadinstitute.org/software/igv/Sashimi. So when clicking the IGV (RNA) button you can go directly to a Sashimi plot of the gene(s) in question to look at the splice junctions across the samples in the case.

**Suggested solution**
- [ ] Add the option in `scout update case` to also be able to upload a link pointing to an alignment file (BAM|CRAM + index) from a secondary analysis to an already existing case.
- [ ] Also support this from the scout load config
- [ ] Add button for RNA Sashimi plots in IGV on the snv/indel variants view

**Comment by northwestwitch** [comment]
Check this thread from igv.js: https://github.com/igvteam/igv.js/issues/67

**Comment by northwestwitch** [comment]
The specifics for the splice junctions track in igv.js: https://github.com/igvteam/igv.js/wiki/Splice-Junctions

**Comment by dnil** [comment]
Exactly! I think the splice junctions will be fine for now; we would not need to rush with an experimental version of Sashimi, right @henrikstranneheim?

**Comment by henrikstranneheim** [comment]
Yes, I think that splice junctions would be great! And we can update whenever the igv.js has Sashimi available. I will go and vote right away.

**Comment by northwestwitch** [comment]
I could start digging into this. Do we have any file that we could modify and include in the Scout demo @henrikstranneheim @jemten ?

**Comment by jemten** [comment]
Any cram file with RNA data would do right or does it have to be matched to a DNA cram?

**Comment by dnil** [comment]
Yes, ideal obviously if it matches but not required! Thanks!
