### ISSUE TITLE
IGV button is not linking to the right position

### ISSUE THREAD

**Issue by heronikdin** [Clinical-Genomics/scout#2345]
Hi! 
hope someone can help me! 
The button for IGV once you click on a variant does not take you to the correct position. Instead you have to "drag" your way to the right position. Can this be solved? 

BEst Regards, HEro

**Comment by dnil** [comment]
Thanks for reporting! That sounds awful! Can you give an example? It seems to be working nicely for a few random variants I tried?

**Comment by heronikdin** [comment]
Kicki had one case: https://scout.scilifelab.se/cust087/F0038239/23fec561f778752caab26e3f000e6820 
and also said that they are having the same problem on the rare disease page? This is not for all the variants, but some... and of course I cant find the good examples now. I will update this issue when I find more. Slightly embarssed now!

**Comment by northwestwitch** [comment]
Thanks @heronikdin, it's a good example. I'm not 100% sure it depends on our code but I'll try to fiddle a bit with the tracks later and if it's not us we should definitely let the igv developers know!

**Comment by dnil** [comment]
Yeah, the different sizes of insertions and deletions could affect centering. In particular end_position does not appear to be quite correct on the reference with insertions: it appears to amount to insert start + insert length. We can have a look at the variant parsing of insertions - it is likely not quite correct there. Mental note: make sure that any change to parsing does match loqusdb lookups of these events. There this is used as a clever way to differentiating different variants. For now we could decide to always center on the start of the (indel) variant instead on the igv view - or change adaptively depending on the variant type.
