### ISSUE TITLE
Scout database update 2021-02-11 💯 

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#2354]
- [x] `scout update hpo`
![image](https://user-images.githubusercontent.com/28093618/107637234-16d21080-6c6e-11eb-98c0-6e8d465a7103.png)

- [x] scout update diseases --api-key our_omim_key
![image](https://user-images.githubusercontent.com/28093618/107637542-8fd16800-6c6e-11eb-9db1-e1bb1d6aef7c.png)

- [x] scout update genes --api-key our_omim_key
![image](https://user-images.githubusercontent.com/28093618/107638334-b93ec380-6c6f-11eb-8b66-f2cf7a8d4cea.png)
There was an index error but the genes look hopefully

- [x] scout update omim --api-key our_omim_key --institute cust002
![image](https://user-images.githubusercontent.com/28093618/107638995-9bbe2980-6c70-11eb-85e8-ee489ac1fa13.png)

**Comment by northwestwitch** [comment]
fix #2341 and fix #2240.

Note the index update error on step 3. Leaving this issue open

**Comment by dnil** [comment]
Its $gte in the db, $gt on constants. Potato potato. 😅
