### ISSUE TITLE
Loading gene panels

### ISSUE THREAD

**Issue by robinandeer** [Clinical-Genomics/scout#236]
The gene panels get loaded multiple times when you reload cases and the model doesn't seem to define any restrictions on unique fields.

How can a gene panel be uniquely identified? "panel_name" and "version"? We should also check the database if a gene panel already exists before loading it all over again :)

**Comment by moonso** [comment]
Hmm ok I'll have a look into this one

**Comment by robinandeer** [comment]
I will use CCDS as base
