### ISSUE TITLE
Move some resources from scout to external services

### ISSUE THREAD

**Issue by moonso** [Clinical-Genomics/scout#2367]
Hi, there are several of the resources that are used in scout that is relevant for others to query. Instead of adding loads of code to to a scout API (be it REST or CLI) it would be nice to move that into its own resources (microservices?) that lives in their own containers outside of scout.

In specific my suggestion is

## Services (maybe you want to add something here?)

- HPO terms definition
- Gene definition
- Diseases (OMIM)
- Gene panels

## Suggested plan

It could be fairly easy to duplicate the code for these to resources outside scout, put in containers with REST Apis and then start to modify scout to use the services.

## Benefits

- Refactored code
- Information that scout use internally will be easy to access from outside of scout
- Service data can be updated independents of scout
- Service development and deployment can be done independently of Scout.

Any thoughts?

**Comment by northwestwitch** [comment]
Do you want to move only the code that handles those database collections outside Scout or also the collections, like in dedicated databases?

I think that complicates a lot the situation of somebody who wants to install Scout without containers and has no associated software to interact with it, like cg, chanjo, matchmaker etc

**Comment by northwestwitch** [comment]
Unless you install those databases/services in the cloud and make them available to anybody who has a Scout instance, so they don't have to take care of creating, curating and interfacing with them.

 We could do that, as it's not sensitive data..

**Comment by moonso** [comment]
> Do you want to move only the code that handles those database collections outside Scout or also the collections, like in dedicated databases?

Yes I mean that all the collections/data should belong to the service so that would remove those collections from Scout.

> Unless you install those databases/services in the cloud and make them available to anybody who has a Scout instance, so they don't have to take care of creating and curating them and interfacing Scout with them.

Yes that is a good point! Hosting maintained versions in the cloud.

> We could do that, as it's not sensitive data..

Just my thought, these services will be fairly easy to implement and maintain as we don't need to handle authentication etc

**Comment by northwestwitch** [comment]
It could work, but I see 2 main problems here:

- The data in these collections should be available always and quickly when you load cases, and think if you have a slow connection or the online service is down.
- Gene panels are maintained by users, so you need to establish some authentication system if you want to users to be able to create and modify them from Scout.

**Comment by moonso** [comment]
There are benefits of this but of course some hazards as well. It will make setup slightly more complicated, but on the other hand we are working towards a more containerised way of doing things.

> The data in these collections should be available always and quickly when you load cases, and think if you have a slow connection or the online service is down.

I think that any production setup of scout will use a local container with the service in question. It is nice to have to option to skip this if only trying things out.

> Gene panels are maintained by users, so you need to establish some authentication system if you want users to be able to create and modify them from Scout.

Perhaps one could make a read only API that does not require authentication since data is not sensitive and enforce authentication on the POST requests

**Comment by moonso** [comment]
I close this and we can revisit if I gets interesting in the future. I agree that it will make development for different users more complicated and that is to big of a drawback
