### ISSUE TITLE
Include VUS in variant tag application 

### ISSUE THREAD

**Issue by heronikdin** [Clinical-Genomics/scout#2379]
Hi! 

Is it possible to include variant of unknown significance (VUS) in the variant tag menu? We are missing it today... 

![image](https://user-images.githubusercontent.com/62098218/108509991-3eecef80-72be-11eb-8858-a4c4bde34d9b.png)

Hälsningar Hero!

**Comment by dnil** [comment]
Absolutely! You can ACMG classify as VUS if you wish as well, in the meantime, but I do realise the two are different so we'll add it! There is a difference between known unknowns, unknown unknowns and systematically classified unknowns!

**Comment by heronikdin** [comment]
Thank you!
