### ISSUE TITLE
Can't create a gene panel

### ISSUE THREAD

**Issue by heronikdin** [Clinical-Genomics/scout#2380]
Hi! 

I would like to create a gene panel for 3 WES samples that have been uploaded in cancer scout. I have tried to upload the CSV file (created in HGNC), in scout but I keep getting this error message: 

![image](https://user-images.githubusercontent.com/62098218/108693671-64683c00-74fe-11eb-8e83-72c32ddf8849.png)

Can someone please help me?

**Comment by heronikdin** [comment]
So @dnil helped me and all is good in the hood :)

**Comment by dnil** [comment]
Well done! To summarise, the csv files need 1) a column with hgnc_id 2) only one kind of separator character in the header line 3) hgnc id is just an integer, not including the "HGNC:" prefix 4)pure loci without gene mapping cannot be handled on panels (yet). Bravely fought - and really not very informative error messages. Sorry about that..
