### ISSUE TITLE
Update information exposed in cancer variant view

### ISSUE THREAD

**Issue by mhkc** [Clinical-Genomics/scout#2386]
Suggestions on how to improve the cancer variant view

 - Move basic information to summary pane
 - Promote comment pane
 - Remove or demote OMIM, Severity, Gene annotation, conservation and gene models pane
 - Dont show panes such as rank score if there are no information to display
 - Make a dedicated QC pane with mappability and GT calls
 - Change local observations into all cases where the variant had been observed.

**Comment by dnil** [comment]
The last point (local observations with links to cases) is contentious and needs careful discussion with your clinicians - and likely more per-institute config options. The issues are at least a) cross institute unsolicited findings b) within institute cross gene panels unsolicited findings. The obvious counter arguments are higher triage quality, important health impacting actionable unsolicited findings etc, but we have had to change back and forth a few times as the ethical pendulum swings.
