### ISSUE TITLE
Manual inheritance model for a gene missing in recent but not slightly older cases, exists in panel

### ISSUE THREAD

**Issue by ielvers** [Clinical-Genomics/scout#2389]
The gene NALCN has a manual inheritance model reported, but it doesn't come up in a variant in a very recent case: https://scout.scilifelab.se/cust003/20258/15110f4d775eb4139b51447983056d1f
When I look in the panel (https://scout.scilifelab.se/panels/IEM) and in our local copy of the panel submission file for IEM version 16, manual inheritance is specified. 
In another recent case it doesn't appear either: https://scout.scilifelab.se/cust003/21038/8ee3f5973c668a19f01736b5e5889581
But in a slightly older case, same panel version, manual inheritance is specified for this gene: https://scout.scilifelab.se/cust003/20256/93c761713c41015bcdeea0a3623ca6c8

Any brilliant ideas of what the reason for this could be? :)
Thank you!

**Comment by dnil** [comment]
That sounds odd! Conditionally wrong is tricky, but we will investigate.
We don't do manual inheritance on very many panels so it is great that you keep track - thank you!

**Comment by dnil** [comment]
Hm, sorry @ielvers, can you help me up to speed: I see NALCN with one AD and one AR disease from OMIM and [AD, AR] as manual on both IEM v16 and latest (v17). No difference? What should I be seeing?

**Comment by ielvers** [comment]
Sorry for being unclear! Variants from comment above.
Recent case 
![image](https://user-images.githubusercontent.com/57791644/108966968-30685480-767f-11eb-8640-260a58feb905.png)

Slightly older case
![image](https://user-images.githubusercontent.com/57791644/108967042-4c6bf600-767f-11eb-86b7-e6df8f018dd9.png)

**Comment by dnil** [comment]
Are you talking about the manual disease associated transcript perhaps?

**Comment by dnil** [comment]
Slightly different MIP versions 9.1.2 vs 9.1.1, and loading dates a couple of months apart so also loaded with Scout some versions apart for parsing those runs. In this particular case it didn't really hurt, but I imagine you are missing a lot of current manual inheritance annotation. Thanks again!

**Comment by dnil** [comment]
This was tricky, but I *think* I have a clue now. The gene in question is on the default gene panel for the case where the extra manual information is correctly fetched but not where it is missing. I think we at some point (maybe always?) rationalised away fetching the info for the additional panels, and only populate it for the default panels. I'll experiment a bit, but unfortunately I'll have to fix the demo case panel parsing first to be able to do that, so it will not be ready today. To be continued! 😊

**Comment by dnil** [comment]
Yes, that is the issue. If you add IEM (or some other panel with manual inheritance annotations for the gene) to the default gene panels for the case, it will show: 

Test case with OMIM-AUTO default has no manual inheritance annotation:
![Screenshot 2021-02-24 at 18 41 38](https://user-images.githubusercontent.com/758570/109042199-2f134800-76d0-11eb-87e8-49b46053e3f5.png)

Selecting IEM:
![Screenshot 2021-02-24 at 18 41 06](https://user-images.githubusercontent.com/758570/109042226-38041980-76d0-11eb-9046-de5a0a1b189b.png)

Gives the info, as expected:
![Screenshot 2021-02-24 at 18 40 42](https://user-images.githubusercontent.com/758570/109042149-23c01c80-76d0-11eb-8ccc-67abb18cc944.png)

I'm starting to feel this is more of a poorly documented feature than a bug? I'm starting to think someone has actually thought rather well about this one.

I was initially about to fix it by pulling in all manual info added to any panel, but realise it could be a problem if we display info from other panels? Eg if the patterns are relevant for a different disorder - or there are conflicts in primary disease transcripts between different disorders?

What do you think?

**Comment by dnil** [comment]
Perhaps I just add a little tooltip text to those boxes, describing the feature?

**Comment by ielvers** [comment]
I knew you'd be able to solve this, but you still keep surprising me with your brilliance :) 

I actually really appreciate that the manually assigned disease transcript only appears for genes in the gene panel I'm looking at, so I'd like to keep it that way. In this case we didn't realize that IEM wasn't the default panel anymore. A tooltip sounds like a great idea!

Thank you, Daniel!

**Comment by dnil** [comment]
😆 Thank you brilliant user! I'll add a tooltip to the development version. Next production release will be next week at the earliest.
