### ISSUE TITLE
Make ranking optional for Cancer variants

### ISSUE THREAD

**Issue by mhkc** [Clinical-Genomics/scout#2393]
Scout is at the moment opinionated on how variants should be sorted resulting in the tool being less powerful users who haven't defined a rank scoring model. Supporting both a rank-based and a filtering based ordering of variants would increase the utility of Scout and lower the threshold for adopting it.

## Alterations
 - Hide ranking column if no ranking model is used
 - Allow sorting on columns
 - Allow default filtering criteria

**Comment by dnil** [comment]
This has gone a bit stale, and some of it was adressed in #2385 etc. It looks more like we are moving towards more ranking also in the cancer cases.
