### ISSUE TITLE
Add VAF info exported variant excel file? 

### ISSUE THREAD

**Issue by heronikdin** [Clinical-Genomics/scout#2398]
Hi! 
 When you export variants from the variant page to excel, the HGNC transcript does not come up, instead some other prefereed transcript comes up. Can this be changed, or can a column be added for the HGNC transcript? 

Hälsningar Hero

**Comment by dnil** [comment]
Yeah, it’s the canonical transcript (as indicated by VEP / ENSEMBL) - typically the longest. We can  add that - it was recently discussed with ET and KW - but note that the export function is primarily intended for research, where canonical is often desireable. If you use it clinically, let us know and we can try to mitigate whatever it is you feel you need a spreadsheet for! 😊

**Comment by heronikdin** [comment]
Hi! :) We would really much like to have the HGNC transkript as the export step is actually making life much easier for us during the report step (ie decreasing manual transfer of the variants).

**Comment by dnil** [comment]
Ok, sure - I don’t think it’s biggie. You’ll have to show me some day what you do with it and why you wouldn’t just rather have that on some format in the general case report! If it is pasting selected variants to LIMS maybe we can figure out a direct import system there - or add like a copy to clipboard button on the variants?

**Comment by heronikdin** [comment]
Thank you Daniel! I would be happy to show you why we would like to have it, and then you might actually have a more brilliant idea :)

**Comment by heronikdin** [comment]
one more thing! Could we include VAF in the excel file...? :)

**Comment by bjhall** [comment]
I would like to second this request! I've never used to export functionality before but needed it today. Unfortunately the transcript selection logic made it less than useful. 

Selecting canonical is in principle ok, but VEP often marks multiple transcripts as canonical and it appears that the export randomly selects one of them. Often weird non-coding (but canonical) transcripts are selected, as shown here:

![bild](https://user-images.githubusercontent.com/11991860/110591189-0a5fab80-8179-11eb-9a32-412ec278880d.png)

@dnil I can probably find some time to work on this, but can we reach a consensus on how to fix it. Using the primary transcript would be my preferred solution, unless it breaks someones workflow on your side.

**Comment by dnil** [comment]
Hah! I didn't know they had those oddball nc-ones flagged canonical, though I was aware of some long, but rarely relevant protein coding ones. 

Thank you in advance then! Primary sounds perfectly acceptable to me; that way it also harmonises with the clinical side. Perhaps check so we/HGNC have a sensible fallback for the non-manually curated ones, but I seem to recall they are all populated with sth at least.

One of the researchers asked for both canonical and primary in response to this, and I guess why not if it is just a table?

**Comment by northwestwitch** [comment]
I can start look into this one today!

**Comment by northwestwitch** [comment]
reopening this, since we added the primary HGNC transcript to the export but not the VAF. I will also rename the issue accordingly then!
