### ISSUE TITLE
Send users to the order portal when they click "Request rerun"

### ISSUE THREAD

**Issue by henningonsbring** [Clinical-Genomics/scout#2401]
Re-runs can be ordered in two ways:
1) When customers are viewing a case on Scout they can click "Request rerun"
2) Via the orderportal

I suggest we replace the "Request rerun"-button on Scout with a link that send users to the order portal where they can fill in their order for a re-run. This update will save production a lot of time since re-runs ordered via the order portal starts automatically, while the ones originating from Scout has to be started manually. Additionally orders placed via order portal are more likely to be correct from start. Re-runs requested from scout are often started with incomplete information, leading to that the analysis fail, which in turn cost production a lot of time.

Before implementing this change there are a few things we need to do:
- Discuss with key customers what they think, this change will make placing an order for re-runs a bit more time consuming for them
- Come up with good argument to tell the customers when we do this change. For example we should inform the customers that this change is done so they will get their analysis faster, since request via scout leads to analyses that often fail, while re-runs ordered via the order portal are more likely to finish without problems
- Consider how to handle the re-run orders for customers that do not have access to the order portal. Are there such customers (Lund?)? Can we give them access to the order portal?

**Comment by dnil** [comment]
Absolutely! The Lund ppl are actually working on a nice rerun solution as well - see #2371 - so they are well covered, at least in a bit.

We could also consider something very similar, and/or showing one or two options depending on local config and wether or not we have managed to integrate our starts with the rerunner app.

But, given, let’s investigate forwarding to orderportalen, and see if we could even pre-populate a rerun order to some extent when they get there?
