### ISSUE TITLE
Scout dev meeting 19/3

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#2403]
- Message queues: consumers and producers for Scout?
- Integration of local branches from Lund 
    - General / RD
    - Cancer integration
- Conditions on timing for next major
- View/controller refactor, API, models with pydantic, react test for simple view

**Comment by hassanfa** [comment]
Hi, is there a Zoom link or agenda for this meeting?

**Comment by dnil** [comment]
Here's a link: https://ki-se.zoom.us/j/69675951444?pwd=WXFCWkFvQnFJMDRWOWloNXZ3VGFwUT09
I left a couple of suggestions above; feel very free to add more!

**Comment by hassanfa** [comment]
Thanks. I forgot to ask, what time is it?

**Comment by dnil** [comment]
13.00~14.00 methinks!
