### ISSUE TITLE
Limit Refseq transcripts displayed?

### ISSUE THREAD

**Issue by ielvers** [Clinical-Genomics/scout#2404]
Hello Scout team!

Since one of the latest updates, way more Refseq transcripts are included in the Transcript overview for each variant. This makes it considerably harder to quickly identify the relevant transcript. Could you please consider not displaying the XM transcripts in the Transcript overview? If they're still included in the Transcripts lists at the bottom of the variant page no information is lost, but it would make things much cleaner.

Example from variant https://scout.scilifelab.se/cust003/21048/1b812e5af199db0eb3a7ccace5185311
![image](https://user-images.githubusercontent.com/57791644/109510363-335dad80-7aa2-11eb-9f26-bdd8b2b7e79f.png)

Thank you :)

**Comment by northwestwitch** [comment]
That can certainly be done and easily @ielvers!

**Comment by dnil** [comment]
Just remember the XM transcript can be (but usually isn't) primary, canonical or disease associated. 😄

**Comment by ielvers** [comment]
Thank you :)

**Comment by northwestwitch** [comment]
Hi @ielvers I'm working on this issues. Would it be OK to have those "uninteresting" in lighter color instead? Because perhaps some other users might still find them informative, see discussion [here](https://github.com/Clinical-Genomics/scout/pull/2411)

**Comment by ielvers** [comment]
A quick poll in the office here says that 4/4 people would appreciate the XM transcripts gone, but that a lighter color is a good compromise :) 
On a related note, would it be an option to move the Varsome, cBioPortal etc links up to where the ClinVar link is? That would make more space in the Transcript overview box.

Also, would it be possible to always display the canonical transcript? I sometimes come across variants that are far from the canonical transcript and they end up not getting any annotation at all in the Transcript overview box. See for example
https://scout.scilifelab.se/cust003/21044/0dd30729579dc5de61f90933de766c36

**Comment by dnil** [comment]
And if I tell your roomies there are currently 96 genes on my local db that have an XM_ transcript for their HGNC primary, what is the counter argument? 😊 

Always-show: do you mean for general reference, like on the [gene page](https://scout.scilifelab.se/genes/20376) or [ENSEMBL gene page link](http://grch37.ensembl.org/Homo_sapiens/Gene/Summary?db=core;g=ENSG00000144455;r=3:3742498-4508965)? I mean, it wouldn't really have any variant to show on the canonical or primary transcript?

**Comment by dnil** [comment]
To be fair, many of them are actually pseudogene entries, but like CLEC20A, MUC8, CCDC194?

**Comment by dnil** [comment]
And a bunch of others, but no disease associated genes among the non-pseudogenes. Fine, then I guess we are good for now, so I don't actually mind very much either way! 👍

**Comment by ielvers** [comment]
Whatever you decide (lighter color or removal), we're happy.

Regarding the always-show, I mean that sometimes the transcript overview is completely empty (like in my example), or only contains one of the two genes that a variant was annotated to. I think I've only encountered this maybe four or five times, so my n is limited, and without having any evidence I don't recall it happening before this year. Anyway, when I come across such a variant it makes me doubt whether the variant is very far away from the canonical/primary transcript or if something else went wrong and that's why nothing is displayed. I'm was hoping there would be a quick fix for this confusion, like always displaying the canonical/primary transcript and the HGVS details for that transcript - but if the HGVS field is empty maybe it wouldn't solve the problem anyway.

**Comment by dnil** [comment]
Would a placeholder message pointing to the transcript table help - like "Not in flagged transcripts - see table below"?

**Comment by ielvers** [comment]
That would be great! Awesome solution!

**Comment by ielvers** [comment]
Although - I know I've seen variants where two genes appear in the Basics box in the upper left corner, but only one of those genes is listed in the Transcript overview. I'm not sure what would be a good phrase for such cases.

**Comment by dnil** [comment]
Ah, right, yes that could also happen. Perhaps a general link down to the transcripts tab then to indicate its not all?

**Comment by ielvers** [comment]
That sounds good! Would it be possible to also include the canonical/primary transcript in the Transcripts tab? Then we could easily see that the variant is only exonic in transcripts we're not interested in (when the transcript we've manually picked as disease-associated is missing in the list I have to go to Ensembl and double-check that the variant really is far outside this transcript).

**Comment by dnil** [comment]
Ah, oops, the "empty" badge is always showing for the VEP RefSeq annotation. 
![Screenshot 2021-03-04 at 12 00 11](https://user-images.githubusercontent.com/758570/109954183-4f9b5d80-7ce1-11eb-84cc-5c0e121be616.png)
While it serves a reminder, much like the tooltip hover, we should probably fix that. 😊
