### ISSUE TITLE
Problems with variants and HGNC transcript

### ISSUE THREAD

**Issue by heronikdin** [Clinical-Genomics/scout#2408]
Hi! 

Regarding this case and the TET2 variant: https://scout.scilifelab.se/cust087/F0038566-2/9c927453ca8940c9f777573ee41b5123?cancer=yes. I dont see the HGNC transcript which we are using, there is a transcript NM_001127208 which shows a likely pathogenic variant? 

Compare with this, same case same TET2 gene, but here I have the HGNC transcript (NM_017628)  which is reported in dataabases.. 
https://scout.scilifelab.se/cust087/F0038566-2/84e77107c0249e8bae83ad0d0ddbd178?cancer=yes 

Can someone help me understand this? 

hälsningar Hero

**Comment by dnil** [comment]
Absolutely! Ask a besserwisser colleague! :wink: 
Hey thats me, so I'll answer, but I'm sure Håkan, Agne and maybe Kicki would also have had a field day explaining this. 😄  

To see why, try going to the IGV.js view and possibly make the gene track a little higher - or use the UCSC view or Alamut to get an overview. Notice how there are like two (well, three counting the AS) main transcript forms, with the 5' being common and the 3' not so much? Your variants are around 106156k and 106182k ballpark, so one of them is in both, one only in the longer form. Like so:
![Screenshot 2021-03-02 at 12 30 41](https://user-images.githubusercontent.com/758570/109642928-d6bacb00-7b53-11eb-8f10-8fe8a7bd54ca.png)
I'll close it with this, but do reopen if I misunderstood you! 😊
