### ISSUE TITLE
Slow loading of variantS page

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#2410]
Is it my impression or now it is slower to load variants page from the case overview?

This is a screenshot of what happens under the hood, why is the case fetched every time a variant gets populated with data?

![image](https://user-images.githubusercontent.com/28093618/109770993-97948480-7bfc-11eb-84e4-691bf1fd0519.png)

**Comment by dnil** [comment]
Locally, I have a hasta-like situation where the first load of basically any view is really slow (db connect/wakeup?), but then the ketchup is fine, which makes it a little hard to judge performance. Perhaps time for timing a bit again?

But for the specifics, once should be enough during the parsing for one page! I would guess with you that there is a missing conditional on the variant_case population (for e.g. prepping bams for strs) or shadowing comments for other assessments and case groups?

**Comment by northwestwitch** [comment]
The think is I found myself in a hasta-like situation locally without even realizing it, so something must have happened when we merged one of the latest PRs..

**Comment by dnil** [comment]
Good call - let's check where things branch off into refactor of saving case/variant counts (I think that was around when it started for me, but I still write that off as slow local db starts), case_groups and  shadowing assessments. Even if it seems semi-ok on clinical-db, that could be better hw masking a problem.

**Comment by northwestwitch** [comment]
Can't reproduce this situation an more, closing the issue!
