### ISSUE TITLE
Improve the looks of group of cases

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#2418]
Group label and "bind other case" button, that is only showing "bind other" (chrome)

![image](https://user-images.githubusercontent.com/28093618/109933774-0f7db000-7ccc-11eb-9dde-201f246c96eb.png)

**Comment by dnil** [comment]
Good, only tested with Safari really - and also likely on a much wider window..

**Comment by northwestwitch** [comment]
I don't think it's a big deal, we can fix it later
