### ISSUE TITLE
New release failed to create an image to upload to Docker Hub

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#2419]
See the output from the github action:

![image](https://user-images.githubusercontent.com/28093618/109948986-2546a180-7cdb-11eb-8589-d697d6108822.png)

**Comment by northwestwitch** [comment]
Specifics of the error:

```
copying src/cryptography/py.typed -> build/lib.linux-x86_64-3.8/cryptography
  running build_ext
  generating cffi module 'build/temp.linux-x86_64-3.8/_padding.c'
  creating build/temp.linux-x86_64-3.8
  generating cffi module 'build/temp.linux-x86_64-3.8/_openssl.c'
  running build_rust

      =============================DEBUG ASSISTANCE=============================
      If you are seeing a compilation error please try the following steps to
      successfully install cryptography:
      1) Upgrade to the latest pip and try again. This will fix errors for most
         users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
      2) Read https://cryptography.io/en/latest/installation.html for specific
         instructions for your platform.
      3) Check our frequently asked questions for more information:
         https://cryptography.io/en/latest/faq.html
      4) Ensure you have a recent Rust toolchain installed:
         https://cryptography.io/en/latest/installation.html#rust
      5) If you are experiencing issues with Rust for *this release only* you may
         set the environment variable `CRYPTOGRAPHY_DONT_BUILD_RUST=1`.
      =============================DEBUG ASSISTANCE=============================

  error: Can not find Rust compiler
  ----------------------------------------
  ERROR: Failed building wheel for cryptography
```

**Comment by hassanfa** [comment]
which cryptography version are you using? I had a not so dissimilar issue with it: https://github.com/Clinical-Genomics/BALSAMIC/issues/549#issuecomment-775017628

They changed the requirements after release `3.4`

**Comment by northwestwitch** [comment]
I'm not sure, it's a github action. It failed also today when we were installing scout on clinical-db prod (cryptography==3.3.1).
On stage the installation worked and it had cryptography==2.4.2

The other difference was that prod had a much older version of pip, and we solved a bit rustically by upgrading pip. I wouldn't like to freeze stuff but we might have to do it if we don't find another solution.

I might fix the Dockerfile by switching from Alpine to some other slim distro, but I'd like it to fix it for good on Scout deirectly. See also here: https://github.com/python-poetry/poetry/issues/3661

**Comment by northwestwitch** [comment]
This is the ultimate issue: https://github.com/pyca/cryptography/issues/5771 in cryptography

**Comment by northwestwitch** [comment]
> They changed the requirements after release `3.4`

I think they should have make a major, have you read the complaints? Hell broke loose when they made that release. I'll make a PR to freeze cryptography as well, unless somebody has a better idea.

**Comment by dnil** [comment]
Yeah, seems from the comments they actually dont use semantic versioning; it said "non-compatible". I guess it will sort itself in a while after some huffing and puffing about the relative merits of Rust vs platform coverage. Freezing until then - or until finding another nice base distro image - must be fine. A n00b-suggestion would be to try a vanilla ubuntu, like we have for testing here on Actions, but perhaps that doesn't play well for inside Docker? 😊

**Comment by dnil** [comment]
(I do like gentoo and derivates - used to have that on my main home system after Stampede).

**Comment by northwestwitch** [comment]
@dnil changing distro in the Docker hub might work, but installation of scout in a virtual env (like today) might still fail, I'd rather fix scout instead.

**Comment by dnil** [comment]
On the same thread, ubuntu 18.04 had the old pip, but ubuntu 20.04 seems to start from 20-something, which is above the pip v19.1 when this would auto-resolve on common platforms.

**Comment by dnil** [comment]
https://xkcd.com/2347/

**Comment by northwestwitch** [comment]
> https://xkcd.com/2347/

So true! I guess I need to check my other repos now 🙄
