### ISSUE TITLE
HPO gene panel download offline?

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#2440]
Something is off with HPO gene panel downloads; reported by Hafdis H for https://scout.scilifelab.se/cust002/F0038096 and reproduces with just adding a single gene on stage for https://scout-stage.scilifelab.se/cust002/F0013248-3.

🕵🏻‍♂️ HPO gene table? pdf generation?

**Comment by northwestwitch** [comment]
Yes, the page is completely blank!
