### ISSUE TITLE
cvs file for ClinVar submission (to Chiara)

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#2443]
instructions on how to handle the files downloaded from SCout for CLinVar submission 

[ClinVar instruction for .cvs files from Scout.pptx](https://github.com/Clinical-Genomics/scout/files/6148781/ClinVar.instruction.for.cvs.files.from.Scout.pptx)

For users have a Swedish PC with Windows 10

**Comment by northwestwitch** [comment]
Add instructions to clinvar howto in Scout
