### ISSUE TITLE
HPO gene list dl includes non-clinical genes..

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#2445]
@annham noticed that we (still/again) have genes that are not on the clinical list on the downloadable HPO gene list. This is not ideal, as these genes are not triaged if searches are made on the clinical page. Even if it would be appropriate for e.g. the research panel. Let's see if we can find a good solution, perhaps filtering away the non-clinical automatically, or add an option to do so.

**Comment by northwestwitch** [comment]
Right! We didn't fix this yet. Perhaps we can fix it before the next release. I'll also think about a solution!

**Comment by dnil** [comment]
Also, she noted that flashes with "non-clinical" genes were disabled for direct access to the HPO list, and only shown if one first filters with HPO-panel, and then once more with regular filter with HPO genes appended to the filters form HGNC symbols field. Also not very consistent. I'll fix that at the same time..
