### ISSUE TITLE
Default and custom inheritance models are not displayed on a newly created gene panel

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#2447]
They're only available after a user modifies gene by gene.

For instance try to create a new gene panel based on the demo one. Even if one specifies the inheritance models in the text file, they're not visible in the panel's gene list.

If the genes of the panel are edited later, the inheritance models are correctly displayed.

**Comment by dnil** [comment]
Right, right - it's not being set correctly on load. 😆 I actually saw that when troubleshooting that show manual inheritance model issue, but forgot immediately when that turned out a feature.

**Comment by northwestwitch** [comment]
I'm including a fix in the panel PR
