### ISSUE TITLE
suggeston: show how many genes are included in the panel

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#245]

**Comment by moonso** [comment]
Sure, good idea

**Comment by 4WGH** [comment]
it is nice to see how many genes are included totally.
not a issue but only a suggestion. it can help to cross check we are using the right list.

![skarmklipp](https://cloud.githubusercontent.com/assets/12525201/12612414/ce4b115e-c4f2-11e5-9f4c-0e7e39c9b083.PNG)

**Comment by moonso** [comment]
We will add this to the Februari update
