### ISSUE TITLE
question about transcript

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#2450]
![image](https://user-images.githubusercontent.com/12525201/111475545-79b33d80-872d-11eb-98f3-d58b35ee61f9.png)

The transcript information window has changed lately.
I've noticed some redundancy. see exemple above, where the difference is that a trancript appears twice, once with and once without the version number.
Is there a reason behind this that it would be good for me to know? Or is it a bug?

Thanks for the help :)

Michela

**Comment by northwestwitch** [comment]
Hi! It's not a bug. 
We have made recent changes to the transcript overview (and the relative general report document), basically grouping all transcripts with RefSeq ID by ENSEMBL ID, so there is a line for each of these, with more than one RefSeq Id for each ENSEMBL ID. 

Basically the change is from this situation:
![image](https://user-images.githubusercontent.com/28093618/111497839-b8eb8980-8741-11eb-903e-b4fca1caf6e9.png)

To this one:
![image](https://user-images.githubusercontent.com/28093618/111497882-c30d8800-8741-11eb-828e-645e0034a399.png)



But your specific question is not related to the changes above. Keep in mind that the overview is showing:

- **Transcripts with refseq ID, organized by ENSEMBL (one line for each ENSEMBL ID, one ENSEMBL transcript can have multiple RefSeq ids)**
- **Transcripts with refseq ID, derived from MIP/VEP annotations** 

Regarding your specific case, you have 2 genes, so 2 of the situations described above!

This answer has already been answered nicely [here](https://github.com/Clinical-Genomics/scout/issues/2334), please check that issue!
