### ISSUE TITLE
odd graphis for case 21011

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#2451]
it looks  like the case is not loaded
![image](https://user-images.githubusercontent.com/12525201/111593705-846fe000-87ca-11eb-866e-d4df40571524.png)

but if I scroll down i can see it is under in the page

![image](https://user-images.githubusercontent.com/12525201/111593605-673b1180-87ca-11eb-94b9-8768ab277f81.png)

This happens only with this case. When I've activated and analyzed this case it look as usual. 

This is not a real problem but good to know as you can think the case is not shown, so I think it could be good to report it.

**Comment by northwestwitch** [comment]
Ugly! Thanks for telling us. There must be some component of the view that stretches the page above the borders. Perhaps might be fixed in a combo with #2417

**Comment by dnil** [comment]
It might be the long string issue back with a new take with the new comment formatting. Reproduces on e.g. 
https://scout-stage.scilifelab.se/cust002/F0013248-3.

**Comment by northwestwitch** [comment]
![image](https://user-images.githubusercontent.com/28093618/111608504-93aa5a00-87d9-11eb-9553-c2c3f83b0738.png)
