### ISSUE TITLE
variants in cases not belonging to our lab - how to question

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#2452]
Hi,
we are interested in a variatnt that has 3 local observations.
The observation were not in our cases though, so we can not see which cases carry the variant. How can we do to get this information?

Do the local observation belong to only KUL lab or also othet SCout users? (sorry do not remember this)

Michela

**Comment by dnil** [comment]
Please contact support via phone or email to supply details; eg supportsystem@clinicalgenomics. They can help you out!
