### ISSUE TITLE
gnomAD for mtDNA variants

### ISSUE THREAD

**Issue by bjhall** [Clinical-Genomics/scout#2454]
Fairly recently gnomAD introduced data for mtDNA variants (https://gnomad.broadinstitute.org/blog/2020-11-gnomad-v3-1-mitochondrial-dna-variants/)

It would be nice to show these data for mt variants in Scout. One could of course simply use the same field as for normal variants (gnomAD_AF), but due to the nature of mt variants I propose to introduce two new VCF fields that would be loaded into scout:

`gnomAD_AF_mthom` and for homoplasmic frequencies
`gnomAD_AF_mthet` and for heteroplasmic frequencies

And then simply show them in the "Pop freq" column in the variant list and in the "Frequencies" panel of the variant details page.

We can start implementing this if no one has any objections.

**Comment by hassanfa** [comment]
gnomad VCF file tags are `AF_hom` and `AF_het`, can we preserve the original tag and use `gnomAD_mt_AF_hom` and `gnomAD_mt_AF_het`?

**Comment by bjhall** [comment]
@hassanfa Absolutely! I have no opinion about the names :).
