### ISSUE TITLE
ACMG classification page

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#2463]
Hi , we at CMMS have a wish for this page.
We have read the attached publication where the PSV1 criteria can be downgraded to
PVS1-strong
PVS1-moderate
PVS1-supp

This downregulation affects the final classification (P, PL, VUS)

It would be great if this can be integrated in the page. 

[humu.23626.pdf](https://github.com/Clinical-Genomics/scout/files/6182432/humu.23626.pdf)

Is it possible?
See suggestion in the pp slide, if of any help 
[PVS1.pptx](https://github.com/Clinical-Genomics/scout/files/6182501/PVS1.pptx)

**Comment by dnil** [comment]
Sure, that sounds very resonable - and very nearly official. We'll have to have a look at how easy it would be to make it backwards compatible. Would adding in those three as "extra" levels, not requiring the specification, but also allowing a plain  PVS1 seem like a possible way forward to you? In the meantime, note that you can of course use the criteria comment field to add modifiers like "PVS1_Moderate" and manually adapt the automatic classification to reflect the downgrade.

**Comment by 4WGH** [comment]
Hi Daniel,
I think we can write our specification of the downgrading in the comment field for PVS1 , so we do not need a comment field for each of "extra " level.

While we wait for the implementation we will manually adapt the classification. There will not be so many I think.

But looking forward this improvment 🙂

Glad you find it resonable 🙂 , I think that many user could find it usefull.
I've been using this system within an European collaboration within the Porfyria field and I found it very usefull and more "realistic" 🙂




________________________________
Från: Daniel Nilsson ***@***.***>
Skickat: den 22 mars 2021 15:55
Till: Clinical-Genomics/scout ***@***.***>
Kopia: Michela Barbaro ***@***.***>; Author ***@***.***>
Ämne: Re: [Clinical-Genomics/scout] ACMG classification page (#2463)


Sure, that sounds very resonable - and very nearly official. We'll have to have a look at how easy it would be to make it backwards compatible. Would adding in those three as "extra" levels, not requiring the specification, but also allowing a plain PVS1 seem like a possible way forward to you? In the meantime, note that you can of course use the criteria comment field to add modifiers like "PVS1_Moderate" and manually adapt the automatic classification to reflect the downgrade.
