### ISSUE TITLE
ClinVar - jumping page - Q of life

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#2468]
![image](https://user-images.githubusercontent.com/12525201/112172373-f3976b00-8bf4-11eb-82cf-086f933cc67d.png)

Hi.
Two small problems

1. when I save the name change the page jump to the top. I need to scroll down every name change (5 time in this case) . It is possible to make the page not to move? In case of large number of variants it can become quite a bit of extra work  :)

2. If I write all 5 namne changes at once, Then I save one.  the other 4 go back to the initial name- This is Ok if it is not solved

**Comment by northwestwitch** [comment]
Hi! Thanks for the feedback!
The first suggestion is quite easy to implement, the second one not so much, so I think we will fix the jumping thing first!

**Comment by 4WGH** [comment]
super,
if the 1 is solved the 2 is not a real problem 🙂
________________________________
Från: Chiara Rasi ***@***.***>
Skickat: den 23 mars 2021 16:38
Till: Clinical-Genomics/scout ***@***.***>
Kopia: Michela Barbaro ***@***.***>; Author ***@***.***>
Ämne: Re: [Clinical-Genomics/scout] ClinVar - jumping page - Q of life (#2468)


Hi! Thanks for the feedback!
The first suggestion is quite easy to implement, the second one not so much, so I think we will fix the jumping thing first!
