### ISSUE TITLE
Clin VAr submission - variant level - condition - 

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#2469]
![image](https://user-images.githubusercontent.com/12525201/112186603-9950d700-8c01-11eb-876d-b925f1f8623c.png)

we have realized now that we have cases  where no OMIM or HPO term can be used for the "condition" field (image to show the condition fiels I refer too)
We have found an appropiate term from Orphanet 
Is it possible to implement SCout submission for this?
I can think different type of solution (more or less manual, more or less difficult :)

Let me know if I can help by showing some exemple :)

**Comment by dnil** [comment]
Right, HPO isn't exactly made for giving exact disease names, rather component phenotypes. In addition to HPO and Orphanet, ClinVar also support MeSH, MedGen, UMLS and MONDO, but they only wish to have one type of descriptor per individual. We could rather easily open a free text field and a selector for the type. I'm a little unsure of the usefulness then though, compared to just changing it in the spreadsheet, if you are anyway not using info otherwise entered into Scout?

If this is of interest, we could add any or more of the above ontologies to the system in general, so they can be used from the case page etc. But that is as you understand a somewhat larger issue, and it would be nice to know it will see good use.

**Comment by 4WGH** [comment]
It would be much more easier/usefull to have it in the Scout submission form and not to have to modify the excell sheet 🙂

Think about preparing 40 variants, 20 cases and having to go back (again!) to look for information to fill in.  Quite risky.

so far OMIM , HPO have been the most used. But we had to go to orphated for one case and I suspect we will need for some more patients. Usefull also for new disease gene for which there is no OMIM 🙂





________________________________
Från: Daniel Nilsson ***@***.***>
Skickat: den 23 mars 2021 18:27
Till: Clinical-Genomics/scout ***@***.***>
Kopia: Michela Barbaro ***@***.***>; Author ***@***.***>
Ämne: Re: [Clinical-Genomics/scout] Clin VAr submission - variant level - condition - (#2469)


Right, HPO isn't exactly made for giving exact disease names, rather component phenotypes. In addition to HPO and Orphanet, ClinVar also support MeSH, MedGen, UMLS and MONDO, but they only wish to have one type of descriptor per individual. We could rather easily open a free text field and a selector for the type. I'm a little unsure of the usefulness then though, compared to just changing it in the spreadsheet, if you are anyway not using info otherwise entered into Scout?

If this is of interest, we could add any or more of the above ontologies to the system in general, so they can be used from the case page etc. But that is as you understand a somewhat larger issue, and it would be nice to know it will see good use.

**Comment by northwestwitch** [comment]
Hi @4WGH I like the idea of introducing Orphanet to describe diseases, together with OMIM (see #2159) and I've been thinking to introducing the ontology in Scout since a while. But honestly I'm not sure that we will manage to have it in place before you finish the ClinVar submission

**Comment by 4WGH** [comment]
HI,
how is it going with this?
I've submitted variants from EP cases,  For 3 of 12 (25%) we could not use OMIM or HPO for the condition. I've used 2 different Orphanet and a MeSH term. 
I write this to give you and idea how important this can be  :-)

**Comment by northwestwitch** [comment]
Hi, unfortunately parsing and saving Orphanet terms in pur database to make them available in Scout is not something that is going to be in place in the immediate future. It is something planned but we don't have the resources to work on this at the moment. You'd need to continue editing your Clinvar submission manually for now, sorry.

**Comment by 4WGH** [comment]
I understand,
then it would be nice, to make the editing easier and safer if the order of variants in the list and file correspond at the orderI add them to the submission (see issue #2519)
So the variants to edit are in the same order as I enter them  and I can take side notes 🙂 and not having to cross check too many different pages/table 🙂







________________________________
Från: Chiara Rasi ***@***.***>
Skickat: den 26 april 2021 10:40
Till: Clinical-Genomics/scout ***@***.***>
Kopia: Michela Barbaro ***@***.***>; Mention ***@***.***>
Ämne: Re: [Clinical-Genomics/scout] Clin VAr submission - variant level - condition - (#2469)


Hi, unfortunately parsing and saving Orphanet terms in our database to make them available in Scout is not something that is going to be in place in the immediate future. It is something planned but we don't have the resources to work on this at the moment. You'd need to continue editing your Clinvar submission manually for now, sorry.

**Comment by northwestwitch** [comment]
This should be fixed now. In the new ClinVar form you can choose phenotypes from any of the different databases:

<img width="670" alt="image" src="https://user-images.githubusercontent.com/28093618/208923884-12c08711-5d7f-418e-839c-ef8159e3d9aa.png">

Closing this issue, but please reopen if there are related issues!

**Comment by 4WGH** [comment]
Great!!!


thankyou so much!!!!!


Michela
________________________________
Från: Chiara Rasi ***@***.***>
Skickat: den 21 december 2022 15:05
Till: Clinical-Genomics/scout ***@***.***>
Kopia: Michela Barbaro ***@***.***>; Mention ***@***.***>
Ämne: Re: [Clinical-Genomics/scout] Clin VAr submission - variant level - condition - (#2469)


This should be fixed now. In the new ClinVar form you can choose phenotypes from any of the different databases:

[image]<https://user-images.githubusercontent.com/28093618/208923884-12c08711-5d7f-418e-839c-ef8159e3d9aa.png>

Closing this issue, but please reopen if there are related issues!
