### ISSUE TITLE
Expand coverage for genes and transcripts from gene lists

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/scout#247]

**Comment by robinandeer** [comment]
This is my first draft:

![screen shot 2016-02-25 at 10 23 11](https://cloud.githubusercontent.com/assets/1220232/13315232/d6a26014-dba9-11e5-8cd3-99f6884b3c09.png)

/ping @moonso @henrikstranneheim

**Comment by moonso** [comment]
SuperRobin :sheep: !!

**Comment by robinandeer** [comment]
Yay, thank ü :cactus: 

I'll integrate and PR in Scout next

**Comment by ingkebil** [comment]
how comes the completeness at 10x shows up at 100% for all exons except one?

**Comment by ingkebil** [comment]
Otherwise looks really slick! :)

**Comment by robinandeer** [comment]
Looks like the fifth exon isn't covered at all for that gene
