### ISSUE TITLE
Coverage view does not show

### ISSUE THREAD

**Issue by heronikdin** [Clinical-Genomics/scout#2480]
hi,

We do not see the coverage report from the samples uploaded in scout. I have been told to create an issue on here regarding this issue. Please see below. 

![image](https://user-images.githubusercontent.com/62098218/108713537-a8683a80-7518-11eb-8e68-097e7b59dd98.png)

**Comment by patrikgrenfeldt** [comment]
I transferred this issue here, please transfer again if needed

**Comment by northwestwitch** [comment]
Hi Hero, sorry for that!
What case is it, so we can check?

**Comment by northwestwitch** [comment]
And have you checked the other report, the one named "Coverage and QC report"? I am afraid that we forgot to hide a report that is intended just for rare disease cases, and not for cancer.

**Comment by patrikgrenfeldt** [comment]
Should we hide the first coverage report as well as the MT report

**Comment by northwestwitch** [comment]
> Should we hide the first coverage report as well as the MT report

I think so!

**Comment by heronikdin** [comment]
Hi! 
this is what it looks like for all cases uploaded in scout cancer, I think HAssan said that it will be released with next version of balsamic (that was a few months ago). And if it was not seen I should open a ticket in the orderportal... cant remember why that was.

**Comment by northwestwitch** [comment]
Hi again Hero. It is expected that coverage report doesn't contain any data and therefore we should hide it in cancer samples. But you should be able coverage data in the report named **Coverage and QC report**. I've opened some recent cases of cust 087 and that I can see this report.

**Comment by hassanfa** [comment]
> Hi!
> this is what it looks like for all cases uploaded in scout cancer, I think HAssan said that it will be released with next version of balsamic (that was a few months ago). And if it was not seen I should open a ticket in the orderportal... cant remember why that was.

@heronikdin Reason for these confusion: This was actually first meant to go to coverage report, then it went to delivery report, then back to "Coverage  QC report". Thus this caused all these confusion for you and me. It was always there but under different names... Chiara was kind enough to fix it back to "Coverage QC report" so from now on it will be under "Coverage QC report".

Coverage report will, from now on, be under "Coverage and QC report".

**Comment by northwestwitch** [comment]
We're going to remove the empty "Coverage" report now, sorry for the confusion!
