### ISSUE TITLE
Mitochondria contig name hg19 vs hg38

### ISSUE THREAD

**Issue by ViktorHy** [Clinical-Genomics/scout#2481]
In hg38 genome builds contig name for mitochondria is named chrM/M whereas in hg19 it's named chrMT/MT.

Currently scout does not support the M notation and as such we cannot filter against the contig. 

Would it be possible to support both notations?

**Comment by northwestwitch** [comment]
I wasn't aware of that! Of course it should be fixed!

**Comment by dnil** [comment]
Seems we are also using the CHROMSOME ones (i.e. MT) for fetching from biomart. There are not that many genes on M/MT, but are they properly fetched for hg38?

**Comment by bjhall** [comment]
@dnil It appears that the genes are loaded properly from biomart. Ensembl is still calling the chromosome MT. 

I'm quite confused by this. Maybe we're using some strange version of the genome build (but I don't think so)?

@ViktorHy Would renaming M to MT in our fasta solve all these issues or are there other things to consider?

**Comment by henrikstranneheim** [comment]
I think VEP feelt it would be to challenging to change this in all their databases. However, you can use the `--synonyms` to make VEP use a map of chromosome names instead. This is what we do in MIP.
