### ISSUE TITLE
Feature request: remove mtDNA and Coverage report from cancer cases or hide them when note provided

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/scout#2482]
Title pretty much says it all:
![image](https://user-images.githubusercontent.com/1086877/112617526-5cfdc080-8e25-11eb-9b90-6d92fdf35484.png)

None of the cancer cases will have these values set, and I imagine this is not specific for cancer and BALSAMIC.

**Comment by hassanfa** [comment]
This will also avoid confusions such as: https://github.com/Clinical-Genomics/scout/issues/2480 with having too many similar names.

**Comment by northwestwitch** [comment]
Good point, let's remove it in a combo with the the Coverage one!
