### ISSUE TITLE
Clinical filter not working

### ISSUE THREAD

**Issue by nicolelesko** [Clinical-Genomics/scout#249]
Clinical filter seems to be removing variants which shouldn't be removed.  Can you check it is correct?

**Comment by robinandeer** [comment]
@nicolelesko: could you provide more details? Which family did you notice this in? Do you have a specific example of variants that are incorrectly filtered out?

**Comment by 4WGH** [comment]
A practical ex. take fam 16011. if you select clinical filter the variants on MTFMT disappear. there is not reason for that.

**Comment by vwirta** [comment]
@robinandeer can selecting 'Mark checked' add a line into the Activity log?

**Comment by robinandeer** [comment]
@vwirta: it should create an event - is there a case where it doesn't?

**Comment by vwirta** [comment]
@robinandeer I am not sure if there is an event in for example cust003 15102? Is it the 'Updated the status' comment? Can it be made more explicit?

**Comment by robinandeer** [comment]
Yeah, I reused an event-type we already had but I can look into it

**Comment by robinandeer** [comment]
Now there's a separate event logged for updating the checked-status of a case in branch "new-event-checked"
