### ISSUE TITLE
Clin Var - positive feedback!

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#2494]
Hi,
I just want you to know that yesterday we received the first e-mail through ClinVar from a doctor asking about one of the variant we submitted to CLinVAr and classified as pathogenic after WGS analysis and mRNA work characterization 

This make all our work even more worth :)

**Comment by dnil** [comment]
Sharing really helps! Also good for boosting more research into these disorders: we've been contacted with requests to add patients to publication cohorts for detailed genotype-phenotype mapping.
