### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#2495]
When I click in "submitt to CLinVar" for the two GALNS variants in fam 19126 I get an error message: 

Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Comment by 4WGH** [comment]
fam 17017 is also giving probelm now

**Comment by dnil** [comment]
Yeah, thanks and sorry - both appear to be instances of the same issue (https://github.com/Clinical-Genomics/scout/issues/2491). 🐣 It was fixed this morning in the dev track, but we are hesitant to update production right before the holidays. And quite frankly would need to stir up a third person to do so as we have left a couple of computers with access for service over the weekend. 😊

**Comment by 4WGH** [comment]
I will take Easter holiday then :)

It is happening on several variants now 

Happy Easter

**Comment by northwestwitch** [comment]
Hope you have (had) nice holidays. Closing this as it's fixed by the the patch we installed today (4.31.1)
