### ISSUE TITLE
Add link to SO browser in transcripts table and header with sprocket

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/scout#250]
It would be great to have a link to the Sequence Ontology browser from each annotation in the Mutation Type coulmn in the  Transcripts table.
http://www.sequenceontology.org/browser/current_svn/term/SO:0001619

**Comment by robinandeer** [comment]
@moonso I'm guessing this id is not in the model yet - is it in the VCF?

ping @henrikstranneheim

**Comment by moonso** [comment]
We need to get a translation table like:
```
so_term(text) -> so_id(number)
```

**Comment by robinandeer** [comment]
Do you have this in phenomizer? Otherwise skipping 😛

**Comment by moonso** [comment]
We decided to skip this one, to much work for little result
