### ISSUE TITLE
Use Scout as JWT auth server

### ISSUE THREAD

**Issue by mhkc** [Clinical-Genomics/scout#2500]
I am working on adding a JWT based auth system to Gens to secure the interface and API endpoints. This would impact the Gens integration in Scout. Ideally a token would be created when generating the URL to Gens which authenticate the user to access the app. The link in Scout could be opened as a POST request which keeps the token from being presented in the URL.

If a user tries to access Gens through a GET request, the user would be required to login. Again it would be nice if it was possible to use the same database as scout to minimize the redundancy.

**Questions**
 - Is it possible to use Scout as an auth server to create and verify JWT tokens?
 - Would it also be possible to pass the login credentials to Scout to authenticate login attempt using the Scout database?

**Comment by northwestwitch** [comment]
I think both this are possible and not extremely complicated to achieve. Scout is already an auth server. It doesn't implement token authorization but it definitely can. I'll look into it!

**Comment by dnil** [comment]
Right, good stuff - could be nice also for the other extensions as well!

**Comment by northwestwitch** [comment]
> Right, good stuff - could be nice also for the other extensions as well!

Exactly!

**Comment by mhkc** [comment]
Great. Please keep me posted on the progress and let me know if there is anything I can help out with.

Also, should authentication service be part of Scout or a separate service?

**Comment by northwestwitch** [comment]
> Also, should authentication service be part of Scout or a separate service?

Part of Scout I think. I don't think I will have time to work on this in the next couple of weeks, so feel free to start if you feel like it

**Comment by dnil** [comment]
I feel the preferred way to go is to use a common external Auth provider, OAuth or LDAP. At least with Scout and gens this was highly convenient as the shared db connection allowed reuse of the exac same user documents. With https://github.com/Clinical-Genomics/gens/pull/50 done and as a template I think we can tentatively close this issue and revisit in the future if we run into any issues with setting up a shared auth for some other microservice.
