### ISSUE TITLE
Managed variants - question

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#2508]
Hi, we would like to "register" some managed variants.
Where can I read how do they work? 
How can I submitt them?

Sorry to bother you but I can not find the information myself in the Scout user guide :(

**Comment by northwestwitch** [comment]
Hi! You add them either manually one by one or by importing a file.

Go to this page:
https://scout.scilifelab.se/managed_variant and if you want to add one by one use the **Add variant** option, otherwise **Load variants** to load the file.

If you don't have so many it is perhaps easier to save one at the time.

I don't think we have anything about them in the documentation, we should add an howto!

**Comment by 4WGH** [comment]
thanks!
I assume is hg37 coordinates?

who can see them? only CMMS?
can  they be filtered according to panels?

________________________________
Från: Chiara Rasi ***@***.***>
Skickat: den 9 april 2021 10:55
Till: Clinical-Genomics/scout ***@***.***>
Kopia: Michela Barbaro ***@***.***>; Author ***@***.***>
Ämne: Re: [Clinical-Genomics/scout] Managed variants - question (#2508)


Hi! You add them either manually one by one or by importing a file.

Go to this page:
https://scout.scilifelab.se/managed_variant and if you want to add one by one use the Add variant option, otherwise Load variants to load the file.

If you don't have so many it is perhaps easier to save one at the time.

I don't think we have anything about them in the documentation, we should add an howto!

**Comment by northwestwitch** [comment]
Yes, hg37, we are thinking to introduce a genome build for managed variants (or at least a liftover) for when we switch to the new build but it's not in place yet. 

regarding you other questions, please @dnil correct me if I'm wrong:
I think everybody can see them and at the moment they can only be filtered by the items that are in the filters panel (so no gene panels):

![image](https://user-images.githubusercontent.com/28093618/114156976-6e65c300-9923-11eb-95de-0a7af59c78ac.png)

**Comment by dnil** [comment]
Should also be in a howto; we did take that verbally on the Scout user meeting when it was introduced, but everyone can't be there every time so no excuse for having a short text. 

It's whatever-build-you-use-coordinates right now (hg37 for you if you want to use it in Solna) - we will update with a proper build handing soonish. They are global right now, as per discussions on said meetings. I like that, since all will help out collecting, but that could be changed upon new agreement!

Panels is a good idea, I will gladly add that to the filter, but I won't change anything until it sees some use. It was really urgent to have it implemented for some time, and then only a handful of variants showed up during the first months..

**Comment by 4WGH** [comment]
thank you Daniel,
we at CMMS are making a list of variants we want to upload so we are going to use this function 🙂. Therfore I'm asking so many questions  🙂.
We try to avoid to see  not case relevant variants therefore the question about the panel.  Good to know is going to be a possiblity in the future to make them panel filtered.

One more question:
Some variants are common polymophims (with a clinical relevance for us)
This make me think that some of these variants are now  not even uploaded in Scout. Once we make them "managed variants" will they be uploaded? Ingengerd had to manually look for them in a case as they were not uploaded and this is what we hope to overcome making this managed variant list 🙂

Soon you will have a ready "howto" just putting together all your answer to my question  😁

________________________________
Från: Daniel Nilsson ***@***.***>
Skickat: den 9 april 2021 11:08
Till: Clinical-Genomics/scout ***@***.***>
Kopia: Michela Barbaro ***@***.***>; Author ***@***.***>
Ämne: Re: [Clinical-Genomics/scout] Managed variants - question (#2508)


Should also be in a howto; we did take that verbally on the Scout user meeting when it was introduced, but everyone can't be there every time so no excuse for having a short text.

It's whatever-build-you-use-coordinates right now (hg37 for you if you want to use it in Solna) - we will update with a proper build handing soonish. They are global right now, as per discussions on said meetings. I like that, since all will help out collecting, but that could be changed upon new agreement!

Panels is a good idea, I will gladly add that to the filter, but I won't change anything until it sees some use. It was really urgent to have it implemented for some time, and then only a handful of variants showed up during the first months..

**Comment by dnil** [comment]
😁 Yep - we can just refer to this thread instead!

I don't quite understand the part about avoiding seeing variants not in your panel: these are not yet connected to a case, so seing them in this list should not be too stressful? The "managed variants" page will not link to cases. You can find any matches on individual case pages, and even then they will be hidden unless you open the little tab with "Matching managed variants" exactly as "Matching causatives from other cases".
See pictures here: https://github.com/Clinical-Genomics/scout/pull/2155

I'm very close to going on a rant about incidental findings policy, the autonomy principle and the ASHG vs ESHG line of dealing with secondary actionable findings, but I think you are well aware of this.

Yes, managed variants will always load - for cases loaded after the variant was added, obviously. It gets the same priority bypass as MT-variants, clinvar P/LP etc.

**Comment by dnil** [comment]
I wrote something brief in the docs as well; will go live with the next release. Feel free to ask again if there is anything unclear! Looking forward to many interesting variants being managed! 😄

**Comment by dnil** [comment]
Or like Modifier, if its not actually Pathogenic on its own.. 😊
