### ISSUE TITLE
Change "Clinical SNV/INDEL" to "Clinical somatic SNV/INDEL" for cancer view, same for SVs

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/scout#2510]
Is it possible to add word "somatic" to "clinical SNV/INDEL" ?

The reason is we are not going to run MIP for normal sample to get the germline mutations. BASLAMIC already does it for targetseq and whole exome, and we'll do the same for WGS applications.

Thus we'd like to have both germline and somatic in the same view for each cancer case.

i.e. something like this:

![image](https://user-images.githubusercontent.com/1086877/114355035-4b2f5380-9b6f-11eb-8357-6cbc73005d10.png)

So is this technically possible? I mean changing the wording in the cancer view. I'll open another issue for the germline part. (i mean if there is a validation for the texts and buttons and changing wording breaks anything elsewhere).

**Comment by hassanfa** [comment]
We discussed this in meeting with customers regarding WGS project, and it'd be nice to see the possibilities.

**Comment by northwestwitch** [comment]
You can have an if condition that if the case is a cancer case the buttons will look like that
