### ISSUE TITLE
OMIM number not recognized 

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#2518]
https://omim.org/entry/619224

this OMIM phenotype is not accepted in fam 19140
![image](https://user-images.githubusercontent.com/12525201/114454884-620b8f80-9bdb-11eb-803f-ad3571d426f8.png)

If of any help I can see that in the variant page this specific phenotype doesn't appear:
![image](https://user-images.githubusercontent.com/12525201/114455028-8ebfa700-9bdb-11eb-8b17-011da14b63ef.png)

Bug?

**Comment by northwestwitch** [comment]
Not a bug! 😁 Check the date of the Omim term, it was created a month ago, it's too recent to be present in Scout database. Will be probably found after the next official Omim release (and after we update Scout with it)

**Comment by 4WGH** [comment]
ops! that was fast!
the phenotype was known before, therfore I could not undestand...
I can see we are further forward then OMIM 🙂


Thank for the fast reply 🙂

E buonanotte 😉
________________________________
Från: Chiara Rasi ***@***.***>
Skickat: den 12 april 2021 22:36
Till: Clinical-Genomics/scout ***@***.***>
Kopia: Michela Barbaro ***@***.***>; Author ***@***.***>
Ämne: Re: [Clinical-Genomics/scout] OMIM number not recognized (#2518)


Not a bug! 😁 Check the date of the Omim term, it was created a month ago, it's too recent to be present in Scout database. Will be probably found after the next official Omim release (and after we update Scout with it)
