### ISSUE TITLE
Transcripts in ClinVar submission should reflect variant transcripts

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#2520]
fam 18238

![image](https://user-images.githubusercontent.com/12525201/114467109-b0278f80-9be9-11eb-88fd-5c0bc57c3e6b.png)

 Our ref transcript is NM_006005 (also used by CLinvar) 

in th esubmission for only the other one is coming up
![image](https://user-images.githubusercontent.com/12525201/114467239-e5cc7880-9be9-11eb-9e44-c017ea51a36d.png)

sigh :(

bug?

**Comment by 4WGH** [comment]
same problen in fam 19188

**Comment by northwestwitch** [comment]
Thanks for reporting this. The code collecting transcripts for the ClinVar page was not updated in a long time and doesn't reflect the changes we made to the variant transcripts overview. We will update this code as soon as we have time, but for the time being please consider editing this transcript manually in the exported excel sheet.

**Comment by northwestwitch** [comment]
I took the liberty to rename this issue so it reflects exactly what should be done.

**Comment by 4WGH** [comment]
well. It is to dangerous.
In a list of 20 variants have to remember to change transcript.
I will do a manual submission with the Wizard function

thanks
________________________________
Från: Chiara Rasi ***@***.***>
Skickat: den 13 april 2021 08:10
Till: Clinical-Genomics/scout ***@***.***>
Kopia: Michela Barbaro ***@***.***>; Author ***@***.***>
Ämne: Re: [Clinical-Genomics/scout] ClinVar : not all transcript coming up on submission page (#2520)


Thanks for reporting this. The code collecting transcripts for the ClinVar page was not updated in a long time and doesn't reflect the changes we made to the variant transcripts overview. We will update this code as soon as we have time, but for the time being please consider editing this transcript manually in the exported excel sheet.
