### ISSUE TITLE
ClinVar question about a deletion

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#2521]
in fam 17130 there a few bases dletion , listed in the "Clinical SNV and INDELs"

when I do the CLinVar submission the coordinates are not shown....it looks like a CNV report

![image](https://user-images.githubusercontent.com/12525201/114506891-aece8500-9c32-11eb-9d37-e8a701b413d7.png)

It is supposed to look like this? bug?

**Comment by northwestwitch** [comment]
Hi, that's how indels are named in Scout database. If you check at the exported document this variant looks like this:

![image](https://user-images.githubusercontent.com/28093618/114513024-07555080-9c3a-11eb-9887-a0701b7ca5a7.png)

Coordinates and HGVS look OK to me.

**Comment by 4WGH** [comment]
thank
didnt't check the exported file.
can it be made to look the same in the submission?  I need to see what it will be not to have to go to the excelle file everytime something is wrong 🙂


But good to know for now 🙂

thanks
________________________________
Från: Chiara Rasi ***@***.***>
Skickat: den 13 april 2021 09:25
Till: Clinical-Genomics/scout ***@***.***>
Kopia: Michela Barbaro ***@***.***>; Author ***@***.***>
Ämne: Re: [Clinical-Genomics/scout] ClinVar question about a deletion (#2521)


Hi, that's how indels are named in Scout database. If you check at the exported document this variant looks like this:

[image]<https://user-images.githubusercontent.com/28093618/114513024-07555080-9c3a-11eb-9887-a0701b7ca5a7.png>

Coordinates and HGVS look OK to me.
