### ISSUE TITLE
Bad SO term rank for regulatory_region_ablation 

### ISSUE THREAD

**Issue by mhkc** [Clinical-Genomics/scout#2522]
It seems like the rank for the SO term `regulatory_region_ablation ` in scout doesn't corresponds with the [SO term severity](https://m.ensembl.org/info/genome/variation/prediction/predicted_data.html).

`regulatory_region_ablation ` has rank 34 but is estimated to have higher severity (moderate) than its neighbors

[SO TERMS](https://github.com/Clinical-Genomics/scout/blob/fce09756cec34b7cb1ed868d045121bffd445ff6/scout/constants/so_terms.py)

[Assignment of most severe consequence](https://github.com/Clinical-Genomics/scout/blob/fce09756cec34b7cb1ed868d045121bffd445ff6/scout/parse/variant/gene.py#L90)

**Comment by northwestwitch** [comment]
Who's fixing this?

**Comment by mhkc** [comment]
I can

**Comment by dnil** [comment]
:+1: transcript_amplification is also lower than the list has it, but I suspect that one is someones judgement call / experience. Would be nice with some documentation of choices like that. 😊
