### ISSUE TITLE
Almost all prod cases are rerun? -- CG Solna issue --

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#2534]
Check for instance cases from cust003: https://scout.scilifelab.se/cust003. How can it be that almost all their cases are rerun??? Same for cust002.
Cases on scout-stage look OK so should be some parameter used when loading them?

Thanks @emmser for noticing! 🙏

**Comment by dnil** [comment]
cg delivery report upload?

**Comment by dnil** [comment]
Its here:
https://github.com/Clinical-Genomics/scout/blob/4f6a571d608c8464500383e7b994f9fee0af62ba/scout/server/blueprints/institutes/controllers.py#L174

**Comment by dnil** [comment]
Or, well, in the use of the delivery report if you wish, as I guess that is what is triggering the extra analysis being set?

**Comment by northwestwitch** [comment]
Do you want to fix it? Otherwise I can take it this morning

**Comment by dnil** [comment]
Super - please go ahead; I'd rather spend an hour on those filter views! I would have double checked in cg and servers - or with team tr to verify how the uploads are done right now.
