### ISSUE TITLE
Display consensus variant caller support for a given variant FIXED

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/scout#255]
denoted by the 'set=' INFO flag

**Comment by moonso** [comment]
@henrikstranneheim we need documentation on how to handle the different cases.
A quick look gives these different annotations:
```
set=gatk-filterInfreebayes
set=gatk
set=Intersection
set=FilteredInAll
```
I guess there are more alternatives, we need to know what to expect and how to display it...

**Comment by moonso** [comment]
Ok @robinandeer I will add to the model `variant` three new fields like:
```python
gatk=StringField(choices=VARIANT_CALL)
samtools=StringField(choices=VARIANT_CALL)
freebayes=StringField(choices=VARIANT_CALL)
```
where

```python
VARIANT_CALL = (
    'Pass
    'Filtered',
    'Not Found',
    'Not Used',
```

These should be displayed close to the GT call (maybe in the header) with colour labels.
What do you think?

I'll ping you when my part of the branch is ready 🐉 🐴

**Comment by moonso** [comment]
@robinandeer I'm not done but you can do your magic in #294

**Comment by robinandeer** [comment]
hehe

just one problem: the default now appears on old variants so it looks like no caller is used..
