### ISSUE TITLE
Searching for genes only queries grch37

### ISSUE THREAD

**Issue by mhkc** [Clinical-Genomics/scout#2554]
When searching for a gene in /genes the API only queries grch37.

`genes_to_json` doesnt provide a genome build to `hgnc_genes`
https://github.com/Clinical-Genomics/scout/blob/master/scout/server/blueprints/genes/controllers.py#L55

and `hgnc_genes` defaults to grch37
https://github.com/Clinical-Genomics/scout/blob/3d327d64c9fab804cc71b9b285cb30d40fdedf07/scout/adapter/mongo/hgnc.py#L105

**Comment by northwestwitch** [comment]
Fixed in #2560. Closing the issue!
