### ISSUE TITLE
Variant with many reference reads called as few reference reads

### ISSUE THREAD

**Issue by ielvers** [Clinical-Genomics/scout#2555]
I came across this variant:
https://scout.scilifelab.se/cust003/21089/1f366a12b90d391e16eb6a4e94393b0f

That GATK says is supported by very few reference and alternative reads:
![image](https://user-images.githubusercontent.com/57791644/115367197-464d4e00-a1c6-11eb-8845-0ac8390f9c26.png)

But in IGV there are a lot of reference reads (and one alternative):
![image](https://user-images.githubusercontent.com/57791644/115367380-73016580-a1c6-11eb-8af9-3452835673d5.png)

It makes sense that the quality is low, but I was surprised by the reported allele depth. Do you know why it shows up like this?

Thank you!

**Comment by northwestwitch** [comment]
Checked the VCF file and what's shown on Scout is legit: `GT:AD:DP:GQ:PGT:PID:PL:PS	0|1:1,2:3:36:0`.

A guess might be that most of the reads that you see in the igv browser are uninformative? Check this doc: https://gatk.broadinstitute.org/hc/en-us/articles/360035532252-Allele-Depth-AD-is-lower-than-expected

**Comment by ielvers** [comment]
Interesting! Thank you! For this particular variant the AD and DP values match, though. Should I be concerned that IGV only shows one read with the alternative base call while the VCF file says there are two?

**Comment by northwestwitch** [comment]
I wouldn't be so concerned as this is obviously a low quality call.
Assuming that igv.js by default is not hiding reads with low quality mapping, perhaps what happened is that the read was filtered out during the realignment step due to low quality. That would explain the discrepancy between the VCF annotation and the alignment file.

**Comment by northwestwitch** [comment]
ping @henrikstranneheim in case I'm missing something obvious from the pipeline

**Comment by dnil** [comment]
Also note it is in a segdup region:
![Screenshot 2021-04-21 at 16 47 28](https://user-images.githubusercontent.com/758570/115574241-c0163200-a2c1-11eb-9c1c-747c9e5eca93.png)

**Comment by henrikstranneheim** [comment]
I agree with both Daniel and Chiara - I do not see any reason to be concerned.
