### ISSUE TITLE
Add "track" to cases query slice (also dashboard)

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#2557]

**Comment by northwestwitch** [comment]
I was thinking the same myself!

**Comment by northwestwitch** [comment]
But in another PR! 😄

**Comment by dnil** [comment]
Absolutely! It should be all smooth, but with the null-value oddities for it lately, let's do it separately to be sure. I'm reviewing your PR now obviously, so sometime after that.

**Comment by northwestwitch** [comment]
Fixed in #2558, closing
