### ISSUE TITLE
Position for variants and amino acid change

### ISSUE THREAD

**Issue by robinandeer** [Clinical-Genomics/scout#256]
Issue from Jakob Nilsson (cust004). If this something for MIP or Scout?
ping @henrikstranneheim @moonso 

> Hej Robin
> 
> Vi har ibland haft svårt att hitta exakt position för identifierade varianter som presenteras i scout vilket både gör
> bedömningen av den biologiska effekten svårare samt även försvårar när vi skall designa primers för bekräftande sangersekvensering.
> 
> I ett av våra senare fall (815701600398fam) finns en intressant variant i DCLRE1C en Gly till Val i position 91 (c.272G>T) enligt Scout. Tittar man sedan på konsensussekvensen (Q96SD1-1) i Uniprot så finns det ingen Glycin i position 91. Det visar sig då att positionen som anges för sekvensvarianten bygger på en annan isoform av proteinet (Q96SD1-2) där de första 120 aminosyrorna från referensproteinet saknas. Positionen i referensproteinet Gly211Val (c.632G>T) anges också i Scout under transcripts men kommer längre ner i listan. Det skulle underlätta för oss om den angivelse som kommer högst upp Transcript Overview skulle vara kopplad till konsensussekvensen både på genom och protein variant angivelsen.
> 
> Hoppas att det är något som går att ändra utan alltför stor arbetsinsats.
> 
> Bästa hälsningar
> Jakob Nilsson
> Klinisk Immunologi
> Karolinska Universitetssjukhuset Huddinge

**Comment by henrikstranneheim** [comment]
@robinandeer 
The cDNA position and protein positional change is always related to a particular transcript and protein isoform. This is also evident from the "transcrtipt overview" which list both gene and transcript in addition to the amino acid or cDNA change. The purpose of "transcript overview" is to provide a quick summary of the "likely" most important changes for refSeq transcripts. We can list both cDNA and amino acid change there if you would like, although this information is present in the more informative transcript table.
When you order Sanger or look in the transcript table you have HGNC_Symbol;RefSeq_Transcript;ExonNumber;cDNA;AminoAcid, which is usually enough information to order primers. Would you like to have any additional information presented?

**Comment by dnil** [comment]
See also https://github.com/Clinical-Genomics/scout/issues/161 - "highlight causative transcripts" for a discussion on adding canonical transcript markup. That said, it is probably still a Very Good Idea to keep a lookout for damaging variants in real, expressed alternative transcripts, that are not marked e.g. NMD, even though they may not be the one that everyone is using for reference. We had that with a case with MECP2 mutation in an alternative exon. Clear from literature, but not from routine practice using only one canonical transcript.

**Comment by 4WGH** [comment]
to highlight the "causative" or the official "RefSeq" transcript it is still a wish we have too. This info could be taken from HGNC webpage. without need of HGMD :)
If I remember well Kenny though he could retrieve this information

**Comment by moonso** [comment]
Duplicated in #100
