### ISSUE TITLE
partial causative function

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#2562]
![image](https://user-images.githubusercontent.com/12525201/115829850-c1ee0b80-a40f-11eb-9e05-5d1b1c10ee3d.png)

I wish to use partially causative

What can i do if there are not OMIM or HPO that are appropriate?

can we have a free text option? Or the possibility to select the partially causative without being forced to write an explanation?

**Comment by northwestwitch** [comment]
The idea of the partial causative was that the variant could explain the phenotype/diagnosis only in part. Or that was causing a side phenotype of sort. It makes sense to me that it is linked to a phenotype, even if it's not the main phenotype of the patient. What is it causing otherwise 🤔 ?

**Comment by northwestwitch** [comment]
Mmm I don't like much the free text option, as it's not really informative when for instance collecting phenotype info from the database data. And I think it is also redundant as there is already  a "comments" field to describe the variant, so you could use that instead. The comments has also the advantage that if you make the comment global it can be seen in other cases, so it's more helpful in general.

I think the real option would be to make the OMIM/HPO term non-mandatory.

**Comment by dnil** [comment]
Also know that the HPO project accept PRs and suggestions for new terms, so the global best scenario is that you submit the terms you need to them, and we can import them? 😊 I realise that is slower..

**Comment by dnil** [comment]
Here: https://github.com/obophenotype/human-phenotype-ontology/issues

**Comment by 4WGH** [comment]
the non-mandatory option would be optimal :)

**Comment by 4WGH** [comment]
Can we discuss about this? 
I have a partial causative, but no OMIM or HPO to use.
I'm forced to select as causative instead of partial :(

Can you remove the mandatoriness? :)

**Comment by northwestwitch** [comment]
Hi! We can remove the mandatory OMIM or HPO but it will take some time before you'll see it in production. For the time being you could either:

- NOT mark it as causative at all and add a comment instead
- Mark it as causative but add a comment explaining that it's not explaining the phenotype entirely
- Mark it as partial causative and assign a rather broad phenotype (higher up in the HPO or OMIM hierarchy)

In the meanwhile you could open an issue in HPO as suggested by Daniel above so they'll include it in the next release of the ontology
