### ISSUE TITLE
Scout IGV bug, "Unparsable bed record: chr14 23299091"

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/scout#2565]
I click on case, click on variants then variant, and then click on gene. An IGV error pops up:

I'm not even checking chr14, the gene is in chr13: https://scout.scilifelab.se/cust000/balsamic-validation-gmsmyeloid-tumor-only/3771fe578bf95fce211f6a0635c8e444?cancer=yes

![image](https://user-images.githubusercontent.com/1086877/115853902-f8388480-a429-11eb-8119-57613854195b.png)

**Comment by northwestwitch** [comment]
Other genes seem to work fine. It's possibly a bug in igv.js, I'll ask there. Thanks @hassanfa !

**Comment by dnil** [comment]
There have been a few issues on the IGV repo lately with bed compression and streaming. We could try upgrading to latest?

**Comment by northwestwitch** [comment]
We're on version 2.7.5 and the newest is 2.8. Yes, let's try to upgrade!

**Comment by northwestwitch** [comment]
They have fixed now, new igv.js release 2.8.1!
