### ISSUE TITLE
WGS and WES in the same family

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#258]
How are handled the labelling in cases where in a fam there is a mix of WES and WGS data?

**Comment by moonso** [comment]
They will be labeled as WGS.
Is that fine with you?

**Comment by 4WGH** [comment]
my personal opinion is that it would be a bit confusiong.
We try have a meeting here
 
Michela Barbaro, M.Sc, PhD
Sjukhuskemist
Centrum för Medfödda Metabola Sjukdomar (CMMS)
L7:05
Karolinska Universitetssjukhuset Solna
17176 Stockholm 
-----Måns Magnusson <notifications@github.com> skrev: ----- 

Till: Clinical-Genomics/scout <scout@noreply.github.com>Från: Måns Magnusson <notifications@github.com>Datum: 2016-02-19 12:45Kopia: MichelaBarbaro <michela.barbaro@karolinska.se>Ärende: Re: [scout] WGS and WES in the same family (#258)
They will be labeled as WGS.Is that fine with you?

**Comment by moonso** [comment]
Ok, would it be better to have a MIXED label?

**Comment by 4WGH** [comment]
it would be helpfull !
 
Michela-----Måns Magnusson <notifications@github.com> skrev: ----- 

Till: Clinical-Genomics/scout <scout@noreply.github.com>Från: Måns Magnusson <notifications@github.com>Datum: 2016-02-19 13:28Kopia: MichelaBarbaro <michela.barbaro@karolinska.se>Ärende: Re: [scout] WGS and WES in the same family (#258)
Ok, would it be better to have a MIXED label?

**Comment by nicolelesko** [comment]
Mixed would be a good label for CMMS.
Nicole

**Comment by robinandeer** [comment]
- [ ] We will annotate this with a column in the PED file
- [ ] MIP will add a new field in QC sample info "SequencingType"
