### ISSUE TITLE
can not collect covarage report

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#259]
i get this problem from fam 15066 when I try to get the coverage report ....

"Säker anslutning misslyckades

Anslutningen till servern bröts under hämtningen av sidan.

    Sidan du försöker se kan inte visas eftersom autenticiteten för mottagen data inte kan verifieras.
    Kontakta webbplatsens ägare och informera dem om detta problem "

**Comment by moonso** [comment]
@robinandeer , will you have a look?

**Comment by 4WGH** [comment]
now it works!!!
 
Michela
 
Michela Barbaro, M.Sc, PhD
Sjukhuskemist
Centrum för Medfödda Metabola Sjukdomar (CMMS)
L7:05
Karolinska Universitetssjukhuset Solna
17176 Stockholm 
-----Måns Magnusson <notifications@github.com> skrev: ----- 

Till: Clinical-Genomics/scout <scout@noreply.github.com>Från: Måns Magnusson <notifications@github.com>Datum: 2016-02-19 12:47Kopia: MichelaBarbaro <michela.barbaro@karolinska.se>Ärende: Re: [scout] can not collect covarage report (#259)
@robinandeer , will you have a look?

**Comment by moonso** [comment]
:+1:

**Comment by ingkebil** [comment]
Some server updates couldn't wait and this morning the server got rebooted. That might have been the problem. Sorry about the inconvenience.
