### ISSUE TITLE
"in COSMIC and in Clinvar" filter in variant list view.

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/scout#2591]
Emma T and us were discussing filtering variants based on if they are present in COSMIC and/or ClinVar. This is to provide an option to look into variants that have hits in ClinVar and COSMIC before doing further investigation.

PS: I don't have Emma's GitHub account and can't tag her here for further input.

**Comment by hassanfa** [comment]
@mhkc Do you have this in your Cancer view refactor? I didn't see it there, but I thought to ask you as well.

**Comment by northwestwitch** [comment]
Did they want the variants pre-filtered (with a checkbox that is already checked when you first land on the variants page) or should be the filtering not done automatically (checkbox not checked)?

**Comment by hassanfa** [comment]
Empty checkbox is actually quite good.

Also, What a legend! Thanks for adding this feature so quickly.
