### ISSUE TITLE
Make Matchmaker matches page more compact

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#2596]
Not it looks like this:

![image](https://user-images.githubusercontent.com/28093618/117405350-c9cba680-af0b-11eb-895d-b3dd55ea9808.png)

You get a bit lost in the results.

Perhaps it's enough is the matching patients are foldable

**Comment by northwestwitch** [comment]
I'm thinking about a way to simulate an environment to help you fix this one @moedarrah.

To give you an idea how real  pages with MatchMaker results look like we need to:
- [ ] Grant you permissions to use MatchMaker  on stage and then you'll have access to a case with matches.
- [ ] Develop locally connecting Scout to a local image of the MatchMaker

**Comment by northwestwitch** [comment]
@moedarrah now it should work for you to use the MatchMaker. You can check this case here: https://scout-stage.scilifelab.se/cust101/A1383. Click on the MatchMaker link on the sidebar of the case:

![image](https://user-images.githubusercontent.com/28093618/117770582-63a99100-b235-11eb-81ea-ea38167f6fc8.png)

From there you can see past matches.

**Comment by northwestwitch** [comment]
I've fixed the port issue in the MatchMaker, you should be able to connect it to your local scout following these steps:

## Running the MatchMaker demo app:
- `git clone https://github.com/Clinical-Genomics/patientMatcher.git`
- `cd patientMatcher`
- `docker-compose up`

## Fixing Scout to connect to the MatchMaker -from within Scout repo:
- Edit scout/server/config.py by adding these lines:
# MME_ACCEPTS = "application/vnd.ga4gh.matchmaker.v1.0+json"
# MME_URL = "http://localhost:9020"
# MME_TOKEN = "custom_token"

## Granting your local user access over the MatchMaker feature

**Comment by moedarrah** [comment]
I will test it!

**Comment by northwestwitch** [comment]
Here is a docker-compose file that combines Scout and PatientMatcher. I've added also the command the grants the MatchMaker permission to the Scout user so it should create a complete test environment for Scout connected to the MatchMaker:

```
version: '3'
# usage:
# sudo docker-compose up
services:
  mongodb:
    # Lightweight Docker image for MongoDB which makes it easy to create:
    # - admin
    # - database
    # - database user with password
    # when the container is first launched.
    image: vepo/mongo
    container_name: mongo
    networks:
      - custom-net
    environment:
      - AUTH=y
      - ADMIN_USER=root
      - ADMIN_PASS=admin123
      - APPLICATION_DATABASE=pmatcher
      - APPLICATION_USER=pmUser
      - APPLICATION_PASS=pmPassword
    ports:
      - '27013:27017'
    expose:
      - '27017'

  pmatcher-cli:
    container_name: pmatcher-cli
    image: clinicalgenomics/patientmatcher
    environment:
      MONGODB_HOST: mongodb
      PMATCHER_CONFIG: '/home/worker/app/patientMatcher/patientMatcher/instance/config.py'
    depends_on:
      - mongodb
    networks:
      - custom-net
    command: bash -c "pmatcher add client -id test_client -token custom_token -url custom_url && pmatcher add demodata --ensembl_genes"

  pmatcher-web:
    container_name: pmatcher-web
    image: clinicalgenomics/patientmatcher
    environment:
      MONGODB_HOST: mongodb
      PMATCHER_CONFIG: '/home/worker/app/patientMatcher/patientMatcher/instance/config.py'
    depends_on:
      - mongodb
    networks:
      - custom-net
    ports:
      - '9020:9020'
    expose:
      - '9020'
    command: bash -c 'pmatcher run --host 0.0.0.0 -p 9020'

  scout-cli:
    build: .
    container_name: scout-cli
    command: bash -c "
      scout --host mongodb setup demo
      && scout --host mongodb --demo update user -u clark.kent@mail.com -r mme_submitter"
    volumes:
      - ./scout:/home/worker/app/scout
      - ./volumes/scout/data:/home/worker/data
    depends_on:
      - mongodb
    networks:
      - custom-net

  scout-web:
    build: .
    container_name: scout-web
    expose:
      - '5000'
    ports:
      - '5000:5000'
    command: scout --host mongodb --demo serve --host 0.0.0.0
    volumes:
      - ./scout:/home/worker/app/scout
      - ./volumes/scout/data:/home/worker/data
    depends_on:
      - mongodb
      - pmatcher-web
    networks:
      - custom-net

networks:
  custom-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/24
```

**Comment by moedarrah** [comment]
It works!

![Screen Shot 2021-05-12 at 09 47 22](https://user-images.githubusercontent.com/41540288/117938206-10a00e80-b307-11eb-8e9f-418aa0cfbd8b.png)
