### ISSUE TITLE
OMIM information for MED12 is incorrect in hgnc_gene collection

### ISSUE THREAD

**Issue by bjhall** [Clinical-Genomics/scout#2597]
This is a very specific issue. If I had the time I'd investigate it further myself, but I'm not very familiar with these parts of the code base. Hopefully it's not just something wrong on our side! :)

In the `hgnc_gene` collection the gene MED12 (11957) has `phenotypes` and `omim_id` corresponding to a different gene: OPA1 (8140). MED12 appear to have an alias which is `OPA1`, so I suppose that is the reason?

Repro: Go to the MED12 gene page (http://scout_url/genes/11957) and click on the OMIM link. This takes me to the the OMIM page for OPA1 (OMIM-ID: 605290), but expected to come to the page for MED12 (OMIM-ID: 300188)

No idea if other genes are affected.

**Comment by northwestwitch** [comment]
I can't reproduce on out server. The OMIM link from the gene page leads to the right page -> https://www.omim.org/entry/300188

Could be a parsing error happening only for genome build 38?

**Comment by dnil** [comment]
Or has something changed in the reference Dbs over time perhaps? I note both MED12 and OPA1 ok on both 37 and 38  in our collections? We are lagging like one release on HPO in production I believe, and that usually is the trigger for updating all. When did you update last?

**Comment by bjhall** [comment]
I don't know when we updated last time. @mhkc ?

But I tried running `scout update genes` on my dev instance and it appears to fix the problem. So at least it should be fixed in the latest version of OMIM. Could be that we were just unlucky that the data was broken the day we loaded the database. OMIM is updated continuously right?

We could probably close this issue then.

**Comment by dnil** [comment]
That is very possible - OMIM releases break from time to time, though they usually fix it rather quickly when prompted! Ok, super, we'll close for now and reopen if needed. I also quickly checked our stage env which should be up to date since a couple of weeks at least and found no issue.
