### ISSUE TITLE
Fix code according to woke suggestions

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#2604]
There are a lot of complaints on the use of un-sensitive words when you open a pull request at the moment. We should fix the code to get rid of them

**Comment by dnil** [comment]
![Screenshot 2021-05-11 at 08 16 43](https://user-images.githubusercontent.com/758570/117767453-3e1a8880-b231-11eb-813c-4e4fc495bdc0.png)

**Comment by northwestwitch** [comment]
Hahaha but that implies that some evil operator added your name like this. I think it's fine and I'm pretty sure it won't raise any complaint from woke

**Comment by dnil** [comment]
Quite right! That is my regular unprivileged local, but it was what greeted me just after the linter was in place. 🧐

**Comment by northwestwitch** [comment]
> Quite right! That is my regular unprivileged local, but it was what greeted me just after the linter was in place. 🧐

Linter doesn't check the content of the database (that is entirely another story). Not so good for ones you self-esteem, You should switch it back to Clark Kent 😆
