### ISSUE TITLE
Scout user meeting 2/6 9-10

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#2605]
Meeting room link to follow on email.

Agenda items and discussion topics are welcome!
- New features
- Bug debriefings
- New developers
- Reports from pipeline development
- Progress on server farm, hg38, RNA
- Discussion

**Comment by dnil** [comment]
## [4.36]
### Added
- Parse and save splice junction tracks from case config file
- Tooltip in observations panel, explaining that case variants with no link might be old variants, not uploaded after a case rerun
### Fixed
- Warning on overwriting variants with same position was no longer shown
- Increase the height of the dropdowns to 425px
- More indices for the case table as it grows, specifically for causatives queries
- Splice junction tracks not centered over variant genes
- Total number of research variants count
- Update variants stats in case documents every time new variants are loaded
- Bug in flashing warning messages when filtering variants
### Changed
- Clearer warning messages for genes and gene/gene-panels searches in variants filters

## [4.35]
### Added
- A new index for hgnc_symbol in the hgnc_gene collection
- A Pedigree panel in STR page
- Display Tier I and II variants in case view causatives card for cancer cases
### Fixed
- Send partial file data to igv.js when visualizing sashimi plots with splice junction tracks
- Research variants filtering by gene
- Do not attempt to populate annotations for not loaded pinned/causatives
- Add max-height to all dropdowns in filters
### Changed
- Switch off non-clinical gene warnings when filtering research variants
- Don't display OMIM disease card in case view for cancer cases
- Refactored Individuals and Causative card in case view for cancer cases
- Update and style STR case report

## [4.34]
### Added
- Saved filter lock and unlock
- Filters can optionally be marked audited, logging the filter name, user and date on the case events and general report.
- Added `ClinVar hits` and `Cosmic hits` in cancer SNVs filters
- Added `ClinVar hits` to variants filter (rare disease track)
- Load cancer demo case in docker-compose files (default and demo file)
- Inclusive-language check using [woke](https://github.com/get-woke/woke) github action
- Add link to HmtVar for mitochondrial variants (if VCF is annotated with HmtNote)
- Grey background for dismissed compounds in variants list and variant page
- Pin badge for pinned compounds in variants list and variant page
- Support LoqusDB REST API queries
- Add a docker-compose-matchmaker under scout/containers/development to test matchmaker locally
- Script to investigate consequences of symbol search bug
- Added GATK to list of SV and cancer SV callers
### Fixed
- Make MitoMap link work for hg38 again
- Export Variants feature crashing when one of the variants has no primary transcripts
- Redirect to last visited variantS page when dismissing variants from variants list
- Improved matching of SVs Loqus occurrences in other cases
- Remove padding from the list inside (Matching causatives from other cases) panel
- Pass None to get_app function in CLI base since passing script_info to app factory functions was deprecated in Flask 2.0
- Fixed failing tests due to Flask update to version 2.0
- Speed up user events view
- Causative view sort out of memory error
- Use hgnc_id for gene filter query
- Typo in case controllers displaying an error every time a patient is matched against external MatchMaker nodes
- Do not crash while attempting an update for variant documents that are too big (> 16 MB)
- Old STR causatives (and other variants) may not have HGNC symbols - fix sort lambda
- Check if gene_obj has primary_transcript before trying to access it
- Warn if a gene manually searched is in a clinical panel with an outdated name when filtering variants
- ChrPos split js not needed on STR page yet
### Changed
- Remove parsing of case `genome_version`, since it's not used anywhere downstream
- Introduce deprecation warning for Loqus configs that are not dictionaries
- SV clinical filter no longer filters out sub 100 nt variants
- Count cases in LoqusDB by variant type
- Commit pulse repo badge temporarily set to weekly
- Sort ClinVar submissions objects by ascending "Last evaluated" date
- Refactored the MatchMaker integration as an extension
- Replaced some sensitive words as suggested by woke linter
- Documentation for load-configuration rewritten.
- Add styles to MatchMaker matches table
- More detailed info on the data shared in MatchMaker submission form

## [4.33.1]
### Fixed
- Include markdown for release autodeploy docs
- Use standard inheritance model in ClinVar (https://ftp.ncbi.nlm.nih.gov/pub/GTR/standard_terms/Mode_of_inheritance.txt)
- Fix issue crash with variants that have been unflagged causative not being available in other causatives
### Added
### Changed

## [4.33]
### Fixed
- Command line crashing when updating an individual not found in database
- Dashboard page crashing when filters return no data
- Cancer variants filter by chromosome
- /api/v1/genes now searches for genes in all genome builds by default
- Upgraded igv.js to version 2.8.1 (Fixed Unparsable bed record error)
### Added
- Autodeploy docs on release
- Documentation for updating case individuals tracks
- Filter cases and dashboard stats by analysis track
### Changed
- Changed from deprecated db update method
- Pre-selected fields to run queries with in dashboard page
- Do not filter by any institute when first accessing the dashboard
- Removed OMIM panel in case view for cancer cases
- Display Tier I and II variants in case view causatives panel for cancer cases
- Refactored Individuals and Causative panels in case view for cancer cases

## [4.32.1]
### Fixed
- iSort lint check only
### Changed
- Institute cases page crashing when a case has track:Null
### Added

## [4.32]
### Added
- Load and show MITOMAP associated diseases from VCF (INFO field: MitomapAssociatedDiseases, via HmtNote)
- Show variant allele frequencies for mitochondrial variants (GRCh38 cases)
- Extend "public" json API with diseases (OMIM) and phenotypes (HPO)
- HPO gene list download now has option for clinical and non-clinical genes
- Display gene splice junctions data in sashimi plots
- Update case individuals with splice junctions tracks
- Simple Docker compose for development with local build
- Make Phenomodels subpanels collapsible
- User side documentation of cytogenomics features (Gens, Chromograph, vcf2cytosure, rhocall)
- iSort GitHub Action
- Support LoqusDB REST API queries
### Fixed
- Show other causative once, even if several events point to it
- Filtering variants by mitochondrial chromosome for cases with genome build=38
- HPO gene search button triggers any warnings for clinical / non-existing genes also on first search
- Fixed a bug in variants pages caused by MT variants without alt_frequency
- Tests for CADD score parsing function
- Fixed the look of IGV settings on SNV variant page
- Cases analyzed once shown as `rerun`
- Missing case track on case re-upload
- Fixed severity rank for SO term "regulatory region ablation"
### Changed
- Refactor according to CodeFactor - mostly reuse of duplicated code
- Phenomodels language adjustment
- Open variants in a new window (from variants page)
- Open overlapping and compound variants in a new window (from variant page)
- gnomAD link points to gnomAD v.3 (build GRCh38) for mitochondrial variants.
- Display only number of affected genes for dismissed SVs in general report
- Chromosome build check when populating the variants filter chromosome selection
- Display mitochondrial and rare diseases coverage report in cases with missing 'rare' track


## [4.31.1]
### Added
### Changed
- Remove mitochondrial and coverage report from cancer cases sidebar
### Fixed
- ClinVar page when dbSNP id is None

## [4.31]
### Added
- gnomAD annotation field in admin guide
- Export also dynamic panel genes not associated to an HPO term when downloading the HPO panel
- Primary HGNC transcript info in variant export files
- Show variant quality (QUAL field from vcf) in the variant summary
- Load/update PDF gene fusion reports (clinical and research) generated with Arriba
- Support new MANE annotations from VEP (both MANE Select and MANE Plus Clinical)
- Display on case activity the event of a user resetting all dismissed variants
- Support gnomAD population frequencies for mitochondrial variants
- Anchor links in Casedata ClinVar panels to redirect after renaming individuals
### Fixed
- Replace old docs link www.clinicalgenomics.se/scout with new https://clinical-genomics.github.io/scout
- Page formatting issues whenever case and variant comments contain extremely long strings with no spaces
- Chromograph images can be one column and have scrollbar. Removed legacy code.
- Column labels for ClinVar case submission
- Page crashing looking for LoqusDB observation when variant doesn't exist
- Missing inheritance models and custom inheritance models on newly created gene panels
- Accept only numbers in managed variants filter as position and end coordinates
- SNP id format and links in Variant page, ClinVar submission form and general report
- Case groups tooltip triggered only when mouse is on the panel header
### Changed
- A more compact case groups panel
- Added landscape orientation CSS style to cancer coverage and QC demo report
- Improve user documentation to create and save new gene panels
- Removed option to use space as separator when uploading gene panels
- Separating the columns of standard and custom inheritance models in gene panels
- Improved ClinVar instructions for users using non-English Excel

## [4.30.2]
### Added
### Fixed
- Use VEP RefSeq ID if RefSeq list is empty in RefSeq transcripts overview
- Bug creating variant links for variants with no end_chrom
### Changed

## [4.30.1]
### Added
### Fixed
- Cryptography dependency fixed to use version < 3.4
### Changed

## [4.30]
### Added
- Introduced a `reset dismiss variant` verb
- Button to reset all dismissed variants for a case
- Add black border to Chromograph ideograms
- Show ClinVar annotations on variantS page
- Added integration with GENS, copy number visualization tool
- Added a VUS label to the manual classification variant tags
- Add additional information to SNV verification emails
- Tooltips documenting manual annotations from default panels
- Case groups now show bam files from all cases on align view
### Fixed
- Center initial igv view on variant start with SNV/indels
- Don't set initial igv view to negative coordinates
- Display of GQ for SV and STR
- Parsing of AD and related info for STRs
- LoqusDB field in institute settings accepts only existing Loqus instances
- Fix DECIPHER link to work after DECIPHER migrated to GRCh38
- Removed visibility window param from igv.js genes track
- Updated HPO download URL
- Patch HPO download test correctly
- Reference size on STR hover not needed (also wrong)
- Introduced genome build check (allowed values: 37, 38, "37", "38") on case load
- Improve case searching by assignee full name
- Populating the LoqusDB select in institute settings
### Changed
- Cancer variants table header (pop freq etc)
- Only admin users can modify LoqusDB instance in Institute settings
- Style of case synopsis, variants and case comments
- Switched to igv.js 2.7.5
- Do not choke if case is missing research variants when research requested
- Count cases in LoqusDB by variant type
- Introduce deprecation warning for Loqus configs that are not dictionaries
- Improve create new gene panel form validation
- Make XM- transcripts less visible if they don't overlap with transcript refseq_id in variant page
- Color of gene panels and comments panels on cases and variant pages
- Do not choke if case is missing research variants when reserch requested

## [4.29.1]
### Added
### Fixed
- Always load STR variants regardless of RankScore threshold (hotfix)
### Changed

**Comment by hassanfa** [comment]
### BALSAMIC

#### Latest release v7.2.2 (since last Scout user meeting v6.1.2)

1. BALSAMIC is hg38 ready, some of fine tuning remaining but workflow runs end to end without any issues
2. Reduced number of variants uploaded to Scout for all uploads: TN-panel, TN-WGS, T-WGS, T-panel
3. UMI-aware workflow validated and verified
4. Software updates to trimming, qc, and structural variant calling steps
5. Produce ranked variants as research variants (not uploaded to Scout yet)
6. Panel of Normal generation support for CNV calling
7. Lots of improvement to pipeline stability

#### What to expect in the future releases:

1. Upload UMI-corrected variants to Scout
2. WGS CNV calling improvements
2. WGS SV calling improvements
3. Somatic filtering and improvements
4. MSI analysis for TN-WGS and TN-panel
5. CNV calling improvements to low tumor purity
6. Per gene coverage report optimized for target sequencing
7. Improved TMB calculations

**Comment by northwestwitch** [comment]
An extract of the most important features added/fixed/changes in the latest software releases **[4.29.1] - [4.36]**
 
### Added
- [ ] Display gene splice junctions data in sashimi plots [4.32]
- [ ] Parse and save splice junction tracks from case config file [4.36]
- [ ] Tooltip in observations panel, explaining that case variants with no link might be old variants, not uploaded after a case rerun [4.36]
- [ ] A Pedigree panel in STR page [4.35]
- [ ] A new index for hgnc_symbol in the hgnc_gene collection [4.35]
- [ ] Display Tier I and II variants in case view causatives card for cancer cases - Markus [4.35]
- [ ] Saved filter lock and unlock - Daniel [4.34]
- [ ] Filters can optionally be marked audited, logging the filter name, user and date on the case events and general report. [4.34]
- [ ] Added `ClinVar hits` and `Cosmic hits` in cancer SNVs filters [4.34]
- [ ] Added `ClinVar hits` to variants filter (rare disease track) [4.34]
- [ ] Load and show MITOMAP associated diseases from VCF (INFO field: MitomapAssociatedDiseases, via HmtNote) [4.32]
- [ ] Add link to HmtVar for mitochondrial variants (if VCF is annotated with HmtNote) [4.34] (Lund facility)
- [ ] Grey background for dismissed compounds in variants list and variant page [4.34]
- [ ] Pin badge for pinned compounds in variants list and variant page [4.34]
- [ ] Added GATK to list of SV and cancer SV callers [4.34]
- [ ] Filter cases and dashboard stats by analysis track [4.33]
- [ ] Documentation for updating case individuals tracks [4.33]
- [ ] Show variant allele frequencies for mitochondrial variants (GRCh38 cases)  [4.32]
- [ ] HPO gene list download now has option for clinical and non-clinical genes  [4.32]
- [ ] User side documentation of cytogenomics features (Gens, Chromograph, vcf2cytosure, rhocall) [4.32]
- [ ] Support LoqusDB REST API queries [4.34]
- [ ] Primary HGNC transcript info in variant export files [4.31]
- [ ] Show variant quality (QUAL field from vcf) in the variant summary [4.31]
- [ ] Load/update PDF gene fusion reports (clinical and research) generated with [4.31]
- [ ] Support new MANE annotations from VEP (both MANE Select and MANE Plus Clinical) [4.31]
- [ ] Support gnomAD population frequencies for mitochondrial variants [4.31]
- [ ] Added a VUS label to the manual classification variant tags [4.30]
- [ ] Added integration with GENS, copy number visualization tool [4.30]
- [ ] Button to reset all dismissed variants for a case [4.30]
- [ ] Show ClinVar annotations on variantS page [4.30]
- [ ] Case groups now show bam files from all cases on align view [4.30]

### Fixed
- [ ] Warning on overwriting variants with same position was no longer shown [4.36]
- [ ] Increase the height of the dropdowns to 425px [4.36]
- [ ] More indices for the case table as it grows, specifically for causatives queries [4.36]
- [ ] Causative view sort out of memory error [4.34]
- [ ] Total number of research variants count [4.36]
- [ ] Update variants stats in case documents every time new variants are loaded [4.36]
- [ ] Bug in flashing warning messages when filtering variants [4.36]
- [ ] *Use hgnc_id for gene filter query* [4.34]
- [ ] Research variants filtering by gene [4.35] -- Use the script to check which cases were affected (thanks Daniel) [4.35]
- [ ] Export Variants feature crashing when one of the variants has no primary transcripts [4.34]
- [ ] Improved matching of SVs Loqus occurrences in other cases [4.34]
- [ ] Old STR causatives (and other variants) may not have HGNC symbols - fix sort lambda [4.34]
- [ ] Use standard inheritance model in ClinVar (https://ftp.ncbi.nlm.nih.gov/pub/GTR/standard_terms/Mode_of_inheritance.txt) [4.33.1] (ClinVar submissions)
- [ ] Fix issue crash with variants that have been unflagged causative not being available in other causatives [4.33.1]
- [ ] Dashboard page crashing when filters return no data [4.33]
- [ ] Cancer variants filter by chromosome [4.33]
- [ ] api/v1/genes now searches for genes in all genome builds by default [4.33]
- [ ] Filtering variants by mitochondrial chromosome for cases with genome build=38 [4.32]
- [ ] Missing case track on case re-upload [4.32]
- [ ] ClinVar page when dbSNP id is None [4.31.1]
- [ ] Page crashing looking for LoqusDB observation when variant doesn't exist  [4.31]
- [ ] Missing inheritance models and custom inheritance models on newly created gene panels  [4.31]
- [ ] Display of GQ for SV and STR [4.31]
- [ ] Parsing of AD and related info for STRs [4.31]
- [ ] Improve case searching by assignee full name [4.31]
- [ ] Always load STR variants regardless of RankScore threshold (hotfix) [4.29.1]

### Changed
- [ ] Clearer warning messages for genes and gene/gene-panels searches in variants filters [4.36]
- [ ] Switch off non-clinical gene warnings when filtering research variants [4.36]
- [ ] Refactored Individuals and Causative card in case view for cancer cases [4.36]
- [ ] Don't display OMIM disease card in case view for cancer cases [4.36]
- [ ] Update and style STR case report - Moe [4.36]
- [ ] SV clinical filter no longer filters out sub 100 nt variants [4.34]
- [ ] Sort ClinVar submissions objects by ascending "Last evaluated" date [4.34]
- [ ] Pre-selected fields to run queries with in dashboard page [4.33]
- [ ] Removed OMIM panel in case view for cancer cases [4.33]
- [ ] Open variants in a new window (from variants page) [4.32] ***Do you still like this?*** 
- [ ] Open overlapping and compound variants in a new window (from variant page) [4.32]
- [ ] gnomAD link points to gnomAD v.3 (build GRCh38) for mitochondrial variants. [4.32]
- [ ] Remove mitochondrial and coverage report from cancer cases sidebar [4.31.1]
- [ ] Improve user documentation to create and save new gene panels [4.31]
- [ ] Removed option to use space as separator when uploading gene panels [4.31]
- [ ] Cancer variants table header (pop freq etc)  [4.30]
- [ ] Only admin users can modify LoqusDB instance in Institute settings [4.30]
- [ ] Do not choke if case is missing research variants when research requested [4.30]
