### ISSUE TITLE
Copy sequence does not work

### ISSUE THREAD

**Issue by AnnHam** [Clinical-Genomics/scout#2607]
Hej, I would like to be able to copy the visible sequence and paste it into preferred browser or document. Now I get the box with the sequnce but not able to copy/paste... 

![Skärmklipp_copy_seq](https://user-images.githubusercontent.com/32488992/117823527-d9315380-b26d-11eb-88c1-256c63e9faba.PNG)

**Comment by northwestwitch** [comment]
Same procedure works also on Chrome! The right click is the definitive trick 👍🏻

**Comment by dnil** [comment]
Basically the same in Firefox - though one has to double click or hold down mouse over the sequence to get more than one line of sequence. Finish off with right click or keyboard shortcut (though the latter is sometimes a little complicated). 

![Screenshot 2021-05-11 at 15 40 57](https://user-images.githubusercontent.com/758570/117825304-83f64180-b26f-11eb-97b5-ecf789cc539b.png)

**Comment by dnil** [comment]
Closing this for now, but do ping us again if you still have problems with this Anna!
