### ISSUE TITLE
Passing script_info to app factory functions is deprecated  after Flask update to version 2.0 (11-5-21)

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#2611]
This is causing tests to fail (check master after installing the repo on a fresh conda env). I really hope cli commands are not failing as well!

**Comment by northwestwitch** [comment]
Unfortunately the cli is also broken. Until yesterday a command like "scout view" worked:

![image](https://user-images.githubusercontent.com/28093618/117933754-32e35d80-b302-11eb-97a6-d3b39dff095a.png)


Now:

![image](https://user-images.githubusercontent.com/28093618/117933793-3e368900-b302-11eb-8570-6452668a7a11.png)

**Comment by dnil** [comment]
Its one of those days that just feels like a Friday. Oh, wait..

**Comment by northwestwitch** [comment]
> Its one of those days that just feels like a Friday. Oh, wait..

They couldn't know that it's a short week for us, or do you think it's premeditate? 😆

**Comment by dnil** [comment]
Hm, maybe not. Then it has to be the patriarchy opposing the woke inclusive language of Scout by guerrilla creation of enough small critical issues that the amending PR never goes through.
