### ISSUE TITLE
MTRFR not coming up in IEM gene panel

### ISSUE THREAD

**Issue by NicoleCMMS** [Clinical-Genomics/scout#2614]
The gene MTRFR is not coming up the in the clinical list of variants in our IEM panel in patient 19253-I-2A.  When I search specifically for variants in this gene I get up variants that have a high rank score (27) and everything looks normal on the variant page etc.  This gene has recently changed name from C12orf65 to MTRFR but the HGNC number has not changed.  Why are these variants not coming up when a panel is selected?

**Comment by dnil** [comment]
That is a good question - we will take a look!

**Comment by dnil** [comment]
It appears we placed a very large degree of trust in the gene panel symbols. We apply all kinds of verification to manually searched symbols, but very little to the symbols contained in the panels, once they are in place. This is likely as we used to rely on assigning panels to variants on load. That changed as we allowed arbitrary panels and the latest panel version to be used even if they were not on the case on load, about eight months ago. If I'm right, that is a truly painful number of cases and genes. We will investigate this further on Monday and get back to you. Very sorry: this may mean a lot of extra work since there are very realistically missed calls.

At any rate, I have fixed this in an update (#2616). While this is a nasty bug, the potential unforeseen issues from forcing out a hot fix during a long weekend makes me want to wait until beginning of next week with deploying even if it means we knowingly miss some genes until then. Then we can also investigate the possibility of shortlisting the genes/variants of interest.

**Comment by northwestwitch** [comment]
Yes that search by gene name was quite naive. I'll review your PR @dnil so we can have the fix in the next release!

**Comment by dnil** [comment]
This has now been fixed on the development branch. We'll be back with an update on the number of cases and genes affected, possibly variants of interest and let you know ASAP when we can have a release out. Likely tomorrow at the latest.

**Comment by NicoleCMMS** [comment]
Thanks guys for fixing this so fast.  Lets hope we don't have a load of missing variants to go through!

**Comment by dnil** [comment]
Yes, it could potentially be a lot. Fingers crossed, so far it is looking a little better than I feared. The panels are somewhat up to date.

On IEM you have ATP5MD/ATP5MK and G6PC/G6PC1 as well that have changed in addition to C12orf65/MTRFR.

We will be back with more complete lists.

**Comment by dnil** [comment]
Hi again,
the search for variants is slow, but if you want an update, perhaps look at
https://github.com/Clinical-Genomics/scout/pull/2621
where you can get a glimpse of number of genes, cases and panels. There is a clear risk that we will still find variants that will require some manual re-assessment, but at the same time will at least not be in every case. For the current panels, it was about as with IEM, one (e.g. MTRFR) or a couple of genes. For some legacy panels, it was a bit worse, but not that many cases had those as default panels. The live variant query is still running, but should be done tonight. In the meantime we have been correcting other issues with the development release and preparing a production release. 

I'm optimistic that the new production release will be ready for tomorrow afternoon, but we will keep in touch about the timeline!

**Comment by dnil** [comment]
2021-05-17 17:34:16 k1315C02VR0WRHTDH __main__[74680] WARNING 1448 cases out of 3055 were compromised.
2021-05-17 17:34:16 k1315C02VR0WRHTDH __main__[74680] WARNING Panel OMIM-AUTO had 0 symbols compromised
2021-05-17 17:34:16 k1315C02VR0WRHTDH __main__[74680] WARNING Panel Cardiology had 1 symbols compromised
2021-05-17 17:34:16 k1315C02VR0WRHTDH __main__[74680] WARNING Panel CTD had 1 symbols compromised
2021-05-17 17:34:16 k1315C02VR0WRHTDH __main__[74680] WARNING Panel HEARING had 0 symbols compromised
2021-05-17 17:34:16 k1315C02VR0WRHTDH __main__[74680] WARNING Panel EP had 0 symbols compromised
2021-05-17 17:34:16 k1315C02VR0WRHTDH __main__[74680] WARNING Panel IEM had 3 symbols compromised
2021-05-17 17:34:16 k1315C02VR0WRHTDH __main__[74680] WARNING Panel PEDHEP had 3 symbols compromised
2021-05-17 17:34:16 k1315C02VR0WRHTDH __main__[74680] WARNING Panel PID had 4 symbols compromised
2021-05-17 17:34:16 k1315C02VR0WRHTDH __main__[74680] WARNING Panel IBMFS had 5 symbols compromised
2021-05-17 17:34:16 k1315C02VR0WRHTDH __main__[74680] WARNING Panel IF had 1 symbols compromised
2021-05-17 17:34:16 k1315C02VR0WRHTDH __main__[74680] WARNING Panel Inherited cancer had 0 symbols compromised
2021-05-17 17:34:16 k1315C02VR0WRHTDH __main__[74680] WARNING Panel NMD had 1 symbols compromised
2021-05-17 17:34:16 k1315C02VR0WRHTDH __main__[74680] WARNING Panel ET had 0 symbols compromised
2021-05-17 17:34:16 k1315C02VR0WRHTDH __main__[74680] WARNING Panel SKD had 11 symbols compromised
2021-05-17 17:34:16 k1315C02VR0WRHTDH __main__[74680] WARNING Panel CILM had 13 symbols compromised
2021-05-17 17:34:16 k1315C02VR0WRHTDH __main__[74680] WARNING Panel NEURODEG had 0 symbols compromised
2021-05-17 17:34:16 k1315C02VR0WRHTDH __main__[74680] WARNING Panel NOONAN had 0 symbols compromised
2021-05-17 17:34:16 k1315C02VR0WRHTDH __main__[74680] WARNING Panel DSD had 0 symbols compromised
2021-05-17 17:34:16 k1315C02VR0WRHTDH __main__[74680] WARNING Panel DIAB had 0 symbols compromised
2021-05-17 17:34:16 k1315C02VR0WRHTDH __main__[74680] WARNING Panel BRAIN had 1 symbols compromised
2021-05-17 17:34:16 k1315C02VR0WRHTDH __main__[74680] WARNING Panel PAI had 0 symbols compromised
2021-05-17 17:34:16 k1315C02VR0WRHTDH __main__[74680] WARNING Panel HYDRO had 2 symbols compromised
2021-05-17 17:34:16 k1315C02VR0WRHTDH __main__[74680] WARNING Panel NBS-M had 0 symbols compromised
2021-05-17 17:34:16 k1315C02VR0WRHTDH __main__[74680] WARNING Panel IMY had 0 symbols compromised
2021-05-17 17:34:16 k1315C02VR0WRHTDH __main__[74680] WARNING Panel Actionable had 0 symbols compromised
2021-05-17 17:34:16 k1315C02VR0WRHTDH __main__[74680] WARNING Panel ChiCaP_Clinical had 0 symbols compromised
2021-05-17 17:34:16 k1315C02VR0WRHTDH __main__[74680] WARNING Panel ChiCaP Research had 0 symbols compromised
2021-05-17 17:34:16 k1315C02VR0WRHTDH __main__[74680] WARNING Panel MOVE had 0 symbols compromised
2021-05-17 17:34:16 k1315C02VR0WRHTDH __main__[74680] WARNING Panel mtDNA had 0 symbols compromised
2021-05-17 17:34:16 k1315C02VR0WRHTDH __main__[74680] WARNING Panel panel1 had 31 symbols compromised
2021-05-17 17:34:16 k1315C02VR0WRHTDH __main__[74680] WARNING Panel MHT had 0 symbols compromised
2021-05-17 17:34:16 k1315C02VR0WRHTDH __main__[74680] WARNING Panel MIT had 9 symbols compromised
2021-05-17 17:34:16 k1315C02VR0WRHTDH __main__[74680] WARNING Panel PGL had 1 symbols compromised
2021-05-17 17:34:16 k1315C02VR0WRHTDH __main__[74680] WARNING Panel PGLe had 0 symbols compromised
2021-05-17 17:34:16 k1315C02VR0WRHTDH __main__[74680] WARNING Panel ENDO had 0 symbols compromised
2021-05-17 17:34:16 k1315C02VR0WRHTDH __main__[74680] WARNING Panel MSKI had 22 symbols compromised
2021-05-17 17:34:16 k1315C02VR0WRHTDH __main__[74680] WARNING Panel Sarcoma had 0 symbols compromised
2021-05-17 17:34:16 k1315C02VR0WRHTDH __main__[74680] WARNING Panel LEUSNV had 0 symbols compromised
2021-05-17 17:34:16 k1315C02VR0WRHTDH __main__[74680] WARNING Panel NJU had 0 symbols compromised
2021-05-17 17:34:16 k1315C02VR0WRHTDH __main__[74680] WARNING Panel LEUSV had 0 symbols compromised
2021-05-17 17:34:16 k1315C02VR0WRHTDH __main__[74680] WARNING Panel issues:
Case F0029993 panel Cardiology gene symbol ISPD differes from current hgnc symbol CRPPA
Case F0039832 panel CTD gene symbol GUCY1A3 differes from current hgnc symbol GUCY1A1
Case 21118 panel IEM gene symbol ATP5MD differes from current hgnc symbol ATP5MK
Case 21118 panel IEM gene symbol C12orf65 differes from current hgnc symbol MTRFR
Case 21118 panel IEM gene symbol G6PC differes from current hgnc symbol G6PC1
Case 21122 panel PEDHEP gene symbol WDR34 differes from current hgnc symbol DYNC2I2
Case 21122 panel PEDHEP gene symbol WDR60 differes from current hgnc symbol DYNC2I1
Case 21122 panel PEDHEP gene symbol G6PC differes from current hgnc symbol G6PC1
Case 821701400110fam panel PID gene symbol CECR1 differes from current hgnc symbol ADA2
Case 821701400110fam panel PID gene symbol G6PC differes from current hgnc symbol G6PC1
Case 821701400110fam panel PID gene symbol MKL1 differes from current hgnc symbol MRTFA
Case 821701400110fam panel PID gene symbol TMEM173 differes from current hgnc symbol STING1
Case 221701400105fam panel IBMFS gene symbol GIF differes from current hgnc symbol CBLIF
Case 221701400105fam panel IBMFS gene symbol C15ORF41 differes from current hgnc symbol CDIN1
Case 221701400105fam panel IBMFS gene symbol HFE2 differes from current hgnc symbol HJV
Case 221701400105fam panel IBMFS gene symbol CECR1 differes from current hgnc symbol ADA2
Case 221701400105fam panel IBMFS gene symbol FYB differes from current hgnc symbol FYB1
Case F0039880 panel IF gene symbol C12orf65 differes from current hgnc symbol MTRFR
Case F0039846 panel NMD gene symbol C12orf65 differes from current hgnc symbol MTRFR
Case F0039725 panel SKD gene symbol FAM46A differes from current hgnc symbol TENT5A
Case F0039725 panel SKD gene symbol C5orf42 differes from current hgnc symbol CPLANE1
Case F0039725 panel SKD gene symbol TCTEX1D2 differes from current hgnc symbol DYNLT2B
Case F0039725 panel SKD gene symbol IMPAD1 differes from current hgnc symbol BPNT2
Case F0039725 panel SKD gene symbol WDR34 differes from current hgnc symbol DYNC2I2
Case F0039725 panel SKD gene symbol WDR60 differes from current hgnc symbol DYNC2I1
Case F0039725 panel SKD gene symbol ARSE differes from current hgnc symbol ARSL
Case F0039725 panel SKD gene symbol FAM58A differes from current hgnc symbol CCNQ
Case F0039725 panel SKD gene symbol C21ORF2 differes from current hgnc symbol CFAP410
Case F0039725 panel SKD gene symbol WISP3 differes from current hgnc symbol CCN6
Case F0039725 panel SKD gene symbol ICK differes from current hgnc symbol CILK1
Case F0039047 panel CILM gene symbol KIAA0556 differes from current hgnc symbol KATNIP
Case F0039047 panel CILM gene symbol WDR34 differes from current hgnc symbol DYNC2I2
Case F0039047 panel CILM gene symbol TCTEX1D2 differes from current hgnc symbol DYNLT2B
Case F0039047 panel CILM gene symbol WDR60 differes from current hgnc symbol DYNC2I1
Case F0039047 panel CILM gene symbol LRRC6 differes from current hgnc symbol DNAAF11
Case F0039047 panel CILM gene symbol ARMC4 differes from current hgnc symbol ODAD2
Case F0039047 panel CILM gene symbol DYX1C1 differes from current hgnc symbol DNAAF4
Case F0039047 panel CILM gene symbol CCDC151 differes from current hgnc symbol ODAD3
Case F0039047 panel CILM gene symbol CCDC114 differes from current hgnc symbol ODAD1
Case F0039047 panel CILM gene symbol C21orf59 differes from current hgnc symbol CFAP298
Case F0039047 panel CILM gene symbol PIH1D3 differes from current hgnc symbol DNAAF6
Case F0039047 panel CILM gene symbol C5orf42 differes from current hgnc symbol CPLANE1
Case F0039047 panel CILM gene symbol C2orf71 differes from current hgnc symbol PCARE
Case F0038977 panel BRAIN gene symbol KIAA0556 differes from current hgnc symbol KATNIP
Case F0039446 panel HYDRO gene symbol WDR34 differes from current hgnc symbol DYNC2I2
Case F0039446 panel HYDRO gene symbol WDR60 differes from current hgnc symbol DYNC2I1
Case noveliguana panel panel1 gene symbol APOPT1 differes from current hgnc symbol COA8
Case noveliguana panel panel1 gene symbol ARMC4 differes from current hgnc symbol ODAD2
Case noveliguana panel panel1 gene symbol ARSE differes from current hgnc symbol ARSL
Case noveliguana panel panel1 gene symbol C12orf65 differes from current hgnc symbol MTRFR
Case noveliguana panel panel1 gene symbol C21orf59 differes from current hgnc symbol CFAP298
Case noveliguana panel panel1 gene symbol C2orf71 differes from current hgnc symbol PCARE
Case noveliguana panel panel1 gene symbol C5orf42 differes from current hgnc symbol CPLANE1
Case noveliguana panel panel1 gene symbol CCDC114 differes from current hgnc symbol ODAD1
Case noveliguana panel panel1 gene symbol CCDC151 differes from current hgnc symbol ODAD3
Case noveliguana panel panel1 gene symbol FAM58A differes from current hgnc symbol CCNQ
Case noveliguana panel panel1 gene symbol COL4A3BP differes from current hgnc symbol CERT1
Case noveliguana panel panel1 gene symbol DARS differes from current hgnc symbol DARS1
Case noveliguana panel panel1 gene symbol DYX1C1 differes from current hgnc symbol DNAAF4
Case noveliguana panel panel1 gene symbol IARS differes from current hgnc symbol IARS1
Case noveliguana panel panel1 gene symbol IMPAD1 differes from current hgnc symbol BPNT2
Case noveliguana panel panel1 gene symbol ISPD differes from current hgnc symbol CRPPA
Case noveliguana panel panel1 gene symbol KARS differes from current hgnc symbol KARS1
Case noveliguana panel panel1 gene symbol KIF1BP differes from current hgnc symbol KIFBP
Case noveliguana panel panel1 gene symbol LRRC6 differes from current hgnc symbol DNAAF11
Case noveliguana panel panel1 gene symbol MUT differes from current hgnc symbol MMUT
Case noveliguana panel panel1 gene symbol KIAA2022 differes from current hgnc symbol NEXMIF
Case noveliguana panel panel1 gene symbol C4orf26 differes from current hgnc symbol ODAPH
Case noveliguana panel panel1 gene symbol PIH1D3 differes from current hgnc symbol DNAAF6
Case noveliguana panel panel1 gene symbol PROSC differes from current hgnc symbol PLPBP
Case noveliguana panel panel1 gene symbol QARS differes from current hgnc symbol QARS1
Case noveliguana panel panel1 gene symbol FAM134B differes from current hgnc symbol RETREG1
Case noveliguana panel panel1 gene symbol TMEM5 differes from current hgnc symbol RXYLT1
Case noveliguana panel panel1 gene symbol TTC25 differes from current hgnc symbol ODAD4
Case noveliguana panel panel1 gene symbol WDR34 differes from current hgnc symbol DYNC2I2
Case noveliguana panel panel1 gene symbol WDR60 differes from current hgnc symbol DYNC2I1
Case noveliguana panel panel1 gene symbol AARS differes from current hgnc symbol AARS1
Case 49 panel MIT gene symbol USMG5 differes from current hgnc symbol ATP5MK
Case 49 panel MIT gene symbol ATP5D differes from current hgnc symbol ATP5F1D
Case 49 panel MIT gene symbol C19orf70 differes from current hgnc symbol MICOS13
Case 49 panel MIT gene symbol APOPT1 differes from current hgnc symbol COA8
Case 49 panel MIT gene symbol ATP5E differes from current hgnc symbol ATP5F1E
Case 49 panel MIT gene symbol C12ORF65 differes from current hgnc symbol MTRFR
Case 49 panel MIT gene symbol FDX1L differes from current hgnc symbol FDX2
Case 49 panel MIT gene symbol GARS differes from current hgnc symbol GARS1
Case 49 panel MIT gene symbol KARS differes from current hgnc symbol KARS1
Case F0013617-2 panel PGL gene symbol H3F3A differes from current hgnc symbol H3-3A
Case savingcoollamb panel MSKI gene symbol SEPT14 differes from current hgnc symbol SEPTIN14
Case savingcoollamb panel MSKI gene symbol H3F3A differes from current hgnc symbol H3-3A
Case savingcoollamb panel MSKI gene symbol H3F3B differes from current hgnc symbol H3-3B
Case savingcoollamb panel MSKI gene symbol H3F3C differes from current hgnc symbol H3-5
Case savingcoollamb panel MSKI gene symbol HIST1H1C differes from current hgnc symbol H1-2
Case savingcoollamb panel MSKI gene symbol HIST1H1E differes from current hgnc symbol H1-4
Case savingcoollamb panel MSKI gene symbol HIST1H2BC differes from current hgnc symbol H2BC4
Case savingcoollamb panel MSKI gene symbol HIST1H2BD differes from current hgnc symbol H2BC5
Case savingcoollamb panel MSKI gene symbol HIST1H3A differes from current hgnc symbol H3C1
Case savingcoollamb panel MSKI gene symbol HIST1H3B differes from current hgnc symbol H3C2
Case savingcoollamb panel MSKI gene symbol HIST1H3C differes from current hgnc symbol H3C3
Case savingcoollamb panel MSKI gene symbol HIST1H3D differes from current hgnc symbol H3C4
Case savingcoollamb panel MSKI gene symbol HIST1H3E differes from current hgnc symbol H3C6
Case savingcoollamb panel MSKI gene symbol HIST1H3F differes from current hgnc symbol H3C7
Case savingcoollamb panel MSKI gene symbol HIST1H3G differes from current hgnc symbol H3C8
Case savingcoollamb panel MSKI gene symbol HIST1H3H differes from current hgnc symbol H3C10
Case savingcoollamb panel MSKI gene symbol HIST1H3I differes from current hgnc symbol H3C11
Case savingcoollamb panel MSKI gene symbol HIST1H3J differes from current hgnc symbol H3C12
Case savingcoollamb panel MSKI gene symbol HIST2H3D differes from current hgnc symbol H3C13
Case savingcoollamb panel MSKI gene symbol HIST3H3 differes from current hgnc symbol H3-4
Case savingcoollamb panel MSKI gene symbol FAM46C differes from current hgnc symbol TENT5C
Case savingcoollamb panel MSKI gene symbol ACPP differes from current hgnc symbol ACP3

2021-05-17 17:34:16 k1315C02VR0WRHTDH __main__[74680] WARNING Variants of interest: cust002 case propertapir F0039341 variant 21_45745940_A_G_clinical 19.0 ['PFKL', 'CFAP410'].
cust002 case propertapir F0039341 variant 5_37231075_C_T_clinical 17.0 ['CPLANE1'].
cust003 case abovefish 21115 variant 17_41063063_G_A_clinical 17.0 ['G6PC1'].
cust003 case wholekitten 21082 variant 10_105154152_C_A_clinical 17.0 ['ATP5MK'].
cust004 case majorswine 821701400078-trio variant 22_40816431_G_A_clinical 19.0 ['MRTFA'].
cust002 case wholecod F0039187 variant 9_131396570_T_C_clinical 23.0 ['DYNC2I2', 'SPTAN1'].
cust004 case wiseoryx 621701400064fam variant 22_40804309_C_T_clinical 23.0 ['SGSM3', 'MRTFA'].
cust004 case livingelk 821701400078 variant 22_40816431_G_A_clinical 25.0 ['MRTFA'].
cust003 case richracer 51 variant 16_75665388_C_T_clinical 31.0 ['KARS1'].
cust010 case civiljackal A1628 variant 5_138858039_C_A_clinical 24.0 ['STING1'].
cust004 case strongmoth 121701400057fam variant 22_40816954_C_T_clinical 24.0 ['MRTFA'].
cust003 case boldcaiman 19253 variant 12_123741490_A_G_clinical 27.0 ['MTRFR', 'CDK2AP1'].
cust002 case cleardassie F0037544 variant 5_37184968_G_C_clinical 27.0 ['CPLANE1'].
cust010 case vitalmaggot CV030 variant 22_17688144_G_A_clinical 20.0 ['ADA2'].
cust004 case enoughjackal 521701400009fam variant 22_40815202_G_A_clinical 22.0 ['MRTFA'].
cust002 case suitedloon F0036679 variant 4_156634698_G_T_clinical 17.0 ['GUCY1A1'].
cust002 case casualgnat F0038120 variant 5_37226942_T_C_clinical 17.0 ['CPLANE1'].
cust107 case meetmoose F0031389-2 variant 1_226252023_C_T_clinical 18.0 ['H3-3A'].
cust002 case luckysquid F0037832 variant 7_158697866_A_C_clinical 17.0 ['DYNC2I1'].
cust002 case givingspider F0036089 variant 7_16255722_A_G_clinical 23.0 ['CRPPA'].
cust004 case politeocelot 415720603075fam variant 22_17670877_C_T_clinical 16.0 ['ADA2'].
cust002 case tenderracer F0037343 variant 5_37182954_C_T_clinical 25.0 ['CPLANE1'].
cust002 case wiredmacaw F0037697 variant 6_82461558_C_T_clinical 23.0 ['TENT5A'].
cust004 case warmparrot 920701400318fam variant 22_40803270_C_T_clinical 24.0 ['SGSM3', 'MRTFA'].
cust004 case warmparrot 920701400318fam variant 22_17662846_T_C_clinical 19.0 ['ADA2'].
cust002 case upwren F0035255 variant 7_16255722_A_G_clinical 23.0 ['CRPPA'].
cust004 case savedcow 220701400305fam variant 22_40801684_A_G_clinical 22.0 ['SGSM3', 'MRTFA'].
cust002 case expertpika F0008484 variant 7_16317848_C_A_clinical 20.0 ['CRPPA'].
cust002 case livingtoad F0026994 variant 9_131398694_G_A_clinical 21.0 ['DYNC2I2', 'SPTAN1'].
cust002 case onepoodle F0037224 variant 16_27752163_C_T_clinical 20.0 ['KATNIP'].
cust002 case moralpup F0037492 variant 15_55722931_T_A_clinical 17.0 ['DNAAF4'].
cust010 case proudegret CV018 variant 22_40815316_G_A_clinical 27.0 ['MRTFA'].
cust010 case nativemoth CV015 variant 5_138858039_C_A_clinical 18.0 ['STING1'].
cust004 case goodbee 720701400254fam variant 22_40814965_G_T_clinical 16.0 ['MRTFA'].
cust004 case frankasp 720701400270fam variant 15_36872087_A_G_clinical 17.0 ['CDIN1'].
cust002 case clearwasp F0025742 variant 4_156643302_G_A_clinical 20.0 ['GUCY1A1'].
cust002 case brightbird F0037045 variant 5_37244553_AT_A_clinical 21.0 ['CPLANE1'].
cust002 case closegator F0032023 variant 4_156617949_GT_G_clinical 16.0 ['GUCY1A1'].
cust002 case kindjennet F0034815 variant 7_158698749_G_A_clinical 25.0 ['DYNC2I1'].
cust080 case simplemite G000302234 variant 6_26156926_G_A_clinical 27.0 ['H2BC5', 'H1-4'].
cust080 case simplemite G000302234 variant 6_26156968_A_G_clinical 19.0 ['H2BC5', 'H1-4'].
cust080 case simplemite G000302234 variant 6_26157076_A_G_clinical 19.0 ['H2BC5', 'H1-4'].
cust080 case simplemite G000302234 variant 6_26157021_G_C_clinical 18.0 ['H2BC5', 'H1-4'].
cust080 case simplemite G000302234 variant 6_26056185_C_G_clinical 17.0 ['H1-2'].
cust002 case firstalien F0036097 variant 5_37153871_G_T_clinical 18.0 ['CPLANE1'].
cust004 case rightshrimp 320701400188fam variant 22_40803285_C_T_clinical 23.0 ['SGSM3', 'MRTFA'].
cust004 case keenkiwi 420701400194fam variant 15_37001439_G_A_clinical 28.0 ['CDIN1'].
cust080 case coollamb G000309532 variant 6_26158479_A_T_clinical 25.0 ['H2BC5', 'H1-4'].
cust080 case coollamb G000309532 variant 1_149785053_G_T_clinical 22.0 ['H3C13'].
cust080 case coollamb G000309532 variant 6_26158542_G_A_clinical 18.0 ['H2BC5', 'H1-4'].
cust080 case coollamb G000309532 variant 3_132047209_TG_T_clinical 16.0 ['ACP3'].

**Comment by northwestwitch** [comment]
One thing that we should fix is the check that prints a warning whenever the gene is not included in the clinical list. For instance IEM panel contains the old gene name (C12orf65). If we search for gene MTRFR in a case runned with that panel we get this warning:

![image](https://user-images.githubusercontent.com/28093618/118602200-ac6fc580-b7b2-11eb-8552-6d33df024929.png)

A warning to update gene name in panel would be more useful!

**Comment by dnil** [comment]
Yes, a nudge to check on the panel would not hurt, but no warning would also be ok if the hgnc_id matches!

**Comment by northwestwitch** [comment]
Working on this so we include it in the new release!

**Comment by NicoleCMMS** [comment]
So if I have understood correctly something changed 8 months ago and the HGNC symbols were no longer used for filtering of variants within gene panels?  This resulted in genes been missed based on the fact that the gene name changed?  Do you have a proposal how we can check for these missing variants in the various cases?  One important thing to keep in mind is that the gene panel a case is submitted with to Clinical Genomics as default for filtering against is not always the only gene panel to be analysed and answered out.

**Comment by dnil** [comment]
Yes, fairly well described! It was rather that the gene symbols were used instead of the panel names only, but the effect is the same.

It is true that default panels are not the only ones analysed, but it is a decent first approximation. Note first that the same gene appears on several panels. Also, we don't really have a way to know which panels have been used, and could not assume that the whole clinical master list should be checked - that may lead to incidental findings.

To be transparent, a gene name could in theory have changed multiple times during these months, and the panels may have updated several times as well. In practice, we only had a few updates. While I think it covers the bulk of variants of interest, you could see the list of variants more as an indication of the number of interesting variants we are looking at: presumably in the tens from each institute.

The ones listed should probably be checked, and there could certainly be a few more for cases where default gene panel was not used.

Once the update is in place, you will be able to re-check such cases of interest for the affected genes without doing anything special. That would be a bit slow.

A quick option would be using the gene-variants view to check for variants in genes of interest - they were not that many after all - but bear in mind that you could find things in cases where that gene was clinical but not on the panel of interest.

**Comment by dnil** [comment]
I have an email request for variants down to rank 10 as well. I'll start a run for that in the afternoon.

**Comment by NicoleCMMS** [comment]
I followed your suggestion and did a search for variants using the gene filter search (down to rank score 10) and could exclude all the new variants in the IEM and MIT gene panels.  So at least there we know we haven't missed anything :-)

**Comment by dnil** [comment]
Oh by the way, does that mean you guys don't need that list down to rank 10? Or was that another panel? 😊

**Comment by NicoleCMMS** [comment]
Yes sorry there was a lack of communication on our side.  No need to pull out a new list.  I have checked all the genes that were on your list.

**Comment by dnil** [comment]
Super: closing this now, but do let us know if you find anything out of the ordinary!
