### ISSUE TITLE
SV variants with same position not loaded

### ISSUE THREAD

**Issue by ViktorHy** [Clinical-Genomics/scout#2615]
When loading a trio-SV-vcf into scout, we had this situation:

One variant found in parent and child with position chr7:7478750-74813500
and another variant found in the other parent at the same start position chr7:74787501-74810500

Both variants are loaded into the database, but only one is shown in scout. 

Feels like scout should be able to support several variants with the same start position but differentiating end positions. This specific example might not be the most useful, but still displays the issue. This was a variant called in all three individuals that turned out to be an artifact of the gatk-caller. I just imagine if say, manta would make a call at the same position but as a true positive, but have vastly different end position such that it would not overlap 70% with the gatk. 

[bug_report_scout.ped.gz](https://github.com/Clinical-Genomics/scout/files/6479013/bug_report_scout.ped.gz)
[bug_report_scout.vcf.gz](https://github.com/Clinical-Genomics/scout/files/6479014/bug_report_scout.vcf.gz)

**Comment by dnil** [comment]
We tend to rely on svdb merge to solve a lot of these issues for us. 😊

**Comment by ViktorHy** [comment]
It was merged with svdb before.

**Comment by ViktorHy** [comment]
Still, you could have situations where you have identical start positions that are not merged with svdb.

**Comment by dnil** [comment]
Sure, that could happen. We should at the very least warn about it - I certainly don't like that the first variant is silently overwritten. What ends up in the database after parsing is actually just one variant, the last one to be precise, even though the parse output is for two variants, just since they get the same simple ID (same chr, start, ref, alt, type), and the alt is nondescript in the case of the 23k or 26k deletions.

**Comment by dnil** [comment]
Sorry, something is odd with that `insert_many` operation - as I currently understand it, it should really throw a `DuplicateKeyError` and allow us to take it one variant at the time. But possibly that changed when they changed the write_concern things. We were hoping to have something for this release at least, but we'll have to get back to you on this one.

**Comment by dnil** [comment]
There would be several ways to deal with this long term. My current favoured one is 2, but other ideas are most welcome. 

1. in caller, always output `ALT` `BND` string, as per VCF standard (section 5.4 in v4.3). If approximate, indicate this with the `APPROXIMATE` flag. This guarantees effective uniqueness, and requires very limited changes to the code. Old cases can be re-run to update if needed.
2. **post-hoc modify `ALT` to conform to the above standard if it belongs to a nondescript category like `<DEL>`, `<DUP>` or `<CNV>`. May require some modification to code for lookup internally and externally in addition to the obvious loading code.** 
3. post-hoc alter the start coordinate. Not ideal for obvious reasons, and not guaranteed to be properly unique. 
4. post-hoc or in caller alter the ALT to something creative `chr_start_ref_<DEL23000>_clinical`. Not a drop-in fix exactly, but could be worked around to some extent by trying two ALTs on lookup. Not according to any standard.
5. Alter id to include end. Requires full repopulation of database and changes to all lookups internally and externally. Redundant text to each variant id for most variants, as essentially all are already unique with the current schema.
