### ISSUE TITLE
Connect Scout MatchMaker to GeneMatcher MatchMaker

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#2642]
Current situation is that GeneMatcher has no staging environment running ATM. 
But we've tried:
- [x] GeneMatcher matching a test patient against our stage environment: worked.
- [x] GeneMatcher matching a test patient against our prod environment: worked
![image](https://user-images.githubusercontent.com/28093618/118837889-82f38e80-b8c5-11eb-9273-eb4ad845da69.png)
(I've just realized that there is a bug in the page and it displays the name of our server instead of theirs under Node)
- [x] Us sending a test matching request against their prod environment : worked
![image](https://user-images.githubusercontent.com/28093618/118838249-d239bf00-b8c5-11eb-81f4-5c7c9462936f.png)

So I'm just going to add their node to prod so we can start matching!

**Comment by northwestwitch** [comment]
This is in production now:

![image](https://user-images.githubusercontent.com/28093618/118960486-a10fcc00-b963-11eb-9aa0-36982c026e6f.png)

**Comment by henrikstranneheim** [comment]
Well done!
