### ISSUE TITLE
Unable to select /deselect gene panel due to new static "bar" in SCOUT

### ISSUE THREAD

**Issue by KickiLagerstedt** [Clinical-Genomics/scout#2647]
If I want to select a new gene panel in my search (variant list view) I am unable to do that since the new "bar" (static position) covers some of my gene panels. 

I have scrolled down the most I can on page (no variants - so not much to show on page)

I have discussed this with @dnil and he recommended changing the "zoom" on the window - it works - but since I am working on my laptop everything becomes very small. I'll invest in a magnifying glass - but perhaps You can help me??  :=)

![image](https://user-images.githubusercontent.com/17139607/118971426-b3900280-b96f-11eb-9efc-7331fe3d3400.png)

**Comment by dnil** [comment]
The other alternative today is also to first click the dropdown to show the panels, then scroll the whole page until you reach the bottom of the panel dropdown. But that is arcane. We will try to fix: perhaps we could limit the size of the dropdown menu bubble. What do you think @moedarrah?
