### ISSUE TITLE
Disable clinical gene list warning on research search

### ISSUE THREAD

**Issue by NicoleCMMS** [Clinical-Genomics/scout#2649]
I've just tried to search for the gene DNAH14 in the research list in family '19074-muscle' and got an error message that the gene is not included in the clinical list.  Either I have used the filter incorrectly or the filter is not working.  Has something changed in the filter which means we should change how we search?  Took a screenshot of the error message.  Carried out the same search in the clinical list and got the same error message but when looking for a gene in one of our panels it works no problem.

![image](https://user-images.githubusercontent.com/22389583/119032779-dc82b880-b9ac-11eb-97a7-7a0fd51bd18e.png)

**Comment by northwestwitch** [comment]
Hi Nicole, that is just a warning telling you that you are searching a gene outside the clinical panel. It's not associated to the number of results (or lack or results) you get from the filtering. But I agree with you that it might be confusing because if you are watching research variants it's kind of implicit that you are agreeing to see non-clinical genes. We could switch off the warning in these cases!

**Comment by NicoleCMMS** [comment]
Perfect!  Thanks for the explanation and for changing the warning!

**Comment by NicoleCMMS** [comment]
Unfortunately need to open this issue again as the filter does not seem to be working in the research variant list.  Please look at the screenshop attached.  I searched for variants in RYR1 and I know that I should get up at least 5 variants with a rank score over 15 but the filter is not working.  Again am I doing something incorrect?

![Bug](https://user-images.githubusercontent.com/22389583/119143926-76e40a00-ba48-11eb-9143-7ebde8af6058.png)

**Comment by dnil** [comment]
Patience, patience! 😉 Yes, the search list was not populated when that warning was written. @northwestwitch noticed and fixed that as well together with the warning, though we didn't write as much in text. It should all be good in the development version, but I'm afraid you will have to wait until Monday - or find us another really bad bug to motivate a Friday release!

Until then, you can as a workaround look at the clinical variant list instead for the clinical genes, and move back to the research list for non-clinical ones. 😊

**Comment by dnil** [comment]
It is still up, so you could have a spin at the development version and see if it works as you expect: https://scout-stage.scilifelab.se/cust003/15065/variants

**Comment by NicoleCMMS** [comment]
OK couldn't read the unwritten ;-) Have tested in the development version and it works perfectly!  Can wait until Monday.
