### ISSUE TITLE
IGV not working this morning?

### ISSUE THREAD

**Issue by ielvers** [Clinical-Genomics/scout#2688]
Hi! I haven't been able to open IGV all morning. A new tab opens, but nothing is loaded. Is this a hospital issue, or how does it look on your side of the street? :)
(I've logged out and logged in again; it didn't help and my trouble shooting skills ended there)
Thanks!

**Comment by dnil** [comment]
😕 Same here! Likely the ssh mount to the filesystem went down. We'll check and hopefully there is a simple fix.

**Comment by dnil** [comment]
Ah, no, fs is fine. It is a certificate on the IGV.org that has expired. We will probably have to try to find a mirror while they update it.

```
[Error] Failed to load resource: The certificate for this server is invalid. You might be connecting to a server that is pretending to be “igv.org”, which could put your confidential information at risk. (genomes.json, line 0)
[Error] Unhandled Promise Rejection: Error accessing resource: https://igv.org/genomes/genomes.json?randomSeed=0.j3jilitafer&version=2.8.1 Status: 0
	(anonymous function) (igv.min.js:63:178047)
	asyncFunctionResume
	(anonymous function)
	promiseReactionJobWithoutPromise
	promiseReactionJob
```

**Comment by dnil** [comment]
We could also consider a local copy. We did that in the beginning, but this is normally working nicely with a minimum of duplication.

**Comment by dnil** [comment]
https://github.com/igvteam/igv.js/issues/1340

**Comment by dnil** [comment]
A simple fix for you @ielvers is to visit http://igv.org with the same browser you are using for Scout and accept the currently expired certificate, and IGV will load also from the Scout views. We will prepare a fix with a cached version in the meantime.

**Comment by dnil** [comment]
Hm, doing that is probably the simplest solution right now. We do again use a central mirror repo for the igv.js code, but then the fetching of genome data etc is affected by this issue. They actually got a new certificate to replace their old one tonight, but unfortunately gave the name of the wrong server for it.

**Comment by dnil** [comment]
Ok, it looks like the certificate settings have been updated, and everything is back to normal! You may have to close the tab with IGV and reopen to see the cryptography settings switch back from Unsecure to Secure again. Closing this now - as usual, feel free to reopen if you encounter it again!
