### ISSUE TITLE
Dynamisk ACMG-klassning för respektive kriterie

### ISSUE THREAD

**Issue by TJO-Lund** [Clinical-Genomics/scout#2700]
ACMG-klassning, Kan den göras mer levande/dynamisk i Scout. I riktlinjer för t.ex. mitokondriella varianter, McCormick et al., 2020, Specifications of the ACMG-AMP standards and guidelines for mitochondrial DNA variant interpretation (PMID 32906214), används dynamisk klassning där styrka kan ändras på ett kriterie, En möjlighet är en dropdown-meny på varje kriterium (i klassningsvyn för ACMG i Scout) där man kan ändra styrkan från VS, S, M, P. Exempelvis används PM2 endast som stödjande vid mtDNA-varianter. Varsome har denna funktion – på patogenicitets-sidan har de samma nivåer som föreslås ovan, och på benign-sidan så har de "stand-alone" i stället för "very strong". Det finns fler exempel när detta skulle vara till hjälp.

**Comment by dnil** [comment]
Absolutely: see also #2463 for a similar suggestion. As a workaround right now you could use the comment field on each criteria to indicate the strength, and manually adjust the automatic call to reflect the dynamically weighted total. We will also then need to indicate what specification standard each classification is made with - say with a reference, or a dropdown choice of a few common standards - required for ClinVar submission e.g. If someone has some time on their hands, the latter could also be used to guide the automatic classification.

**Comment by dnil** [comment]
For implementing this, ClinGen has a good collection of SVI resources that would fit well with strict alternative models that still conform to the overall format of ACMG classifications: https://clinicalgenome.org/working-groups/sequence-variant-interpretation/. The genes with specific rules are few, but rather interesting.

**Comment by ehre** [comment]
I agree that the SVI page is a good resource. Furthermore, this supports @TJO-Lund 's original request. To take two examples in addition to the PVS1 critieria mentioned in #2463 , we use both the mitochondrial specifications and the specifications for hearing loss found on this page. For hearing loss, it is quite common that we change the weight of PP1 (segregation) according to the expert group's recommendation. We already do as you suggest, @dnil , with comments and manual re-weighting, but it is certainly not optimal. I believe an implementation similar to Varsome would work great, when you activate a criterion you start on the default level but can then manually change the evidence strength (see for instance https://varsome.com/variant/hg38/ATM(NM_000051.4)%3Ac.3510dup?annotation-mode=germline%23acmg_annotation#acmg_annotation )

**Comment by 4WGH** [comment]
I agree with the above wish :)

**Comment by dnil** [comment]
The original request is closed by #3753, semi-automation is duplicate to #582. As for the latter, we are almost there among the legendary issues now - who knows, perhaps we will find time (or an extra pair of hands) this semester!
