### ISSUE TITLE
HPO not working again 

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#271]
I can not add more then 1 term, see screen shot.
When I click on ADD (that look quite odd) the term disappears.

The HPO search at CMMS is very important. We wish high prio if possible .
Thanks
Michela
[HPO_160301.pptx](https://github.com/Clinical-Genomics/scout/files/152455/HPO_160301.pptx)

**Comment by 4WGH** [comment]
in fam 16004 there is a HPO temr. Once I try to filter for the HPO generated gene list I get a message of "serve error, inner peace :) "


:(

**Comment by robinandeer** [comment]
I've noticed this, I believe it's an easy fix - will push it out today!

**Comment by robinandeer** [comment]
@4WGH: This HPO term `HP:0004914` is currently not included in our database, this is why it looks like you can't load more than one term

ping @moonso

**Comment by robinandeer** [comment]
@4WGH: the fix for the first issue is now live - you can use the HPO list again

As for the second problem we will get back but now you will get a warning about it

**Comment by 4WGH** [comment]
fam 16006 there is a HPO gene list, I do the HPO filter no variants come up.
If I search for variant in the PAH gene (included in the HPO gene list) I get a variant....
another type of HPO filter problem?

**Comment by robinandeer** [comment]
There was indeed an error introduced which is now resolved in the production scout

Thank you a lot @4WGH!

**Comment by 4WGH** [comment]
thank you for the swift replay !
