### ISSUE TITLE
Loading spinner to the pages that are a bit slow to load

### ISSUE THREAD

**Issue by moedarrah** [Clinical-Genomics/scout#2712]
When the page is loading, there is nothing that informs the user that the page is loading

**Comment by northwestwitch** [comment]
Slow pages that come to my mind: variantS, diagnoses(https://scout.scilifelab.se/diagnoses), phenotypes (https://scout.scilifelab.se/phenotypes), dashboard (https://scout.scilifelab.se/dashboard) when you select institutes with a lot of cases, ..
