### ISSUE TITLE
Internal error 

### ISSUE THREAD

**Issue by 1ctw** [Clinical-Genomics/scout#2724]
Since this morning there is internal error when trying to open variant pages, both SNV and CNV variants. It would be great if you could check this problem as soon as possible.

**Comment by dnil** [comment]
We are tracking an issue with loqusdb since 5 mins ago - could that be it perhaps?

**Comment by northwestwitch** [comment]
Must be that, the errors are accumulating now!

**Comment by dnil** [comment]
```
[hiseq.clinical@hippocampus ~]$ top
-bash: fork: retry: Resource temporarily unavailable

```

**Comment by northwestwitch** [comment]
This should be fixed now, so I'm closing the issue. Please reopen if the problem occurs again.
Apologies for the inconvenience!
