### ISSUE TITLE
Cant add NOTCH2NLC to gene panels

### ISSUE THREAD

**Issue by mhkc** [Clinical-Genomics/scout#2726]
When trying to add the gene "NOTCH2NLC" to a gene panel scout just flashes the warning "HGNC id not found: 53924" despite it being added to the database.

Its caused by scout not passing genome build parameter to `hgnc_gene` which defaults to grch37.

[https://github.com/Clinical-Genomics/scout/blob/b8ef1230651275c77541920eab5ec9116c71c35a/scout/server/blueprints/panels/views.py#L138](https://github.com/Clinical-Genomics/scout/blob/b8ef1230651275c77541920eab5ec9116c71c35a/scout/server/blueprints/panels/views.py#L138)

**Comment by northwestwitch** [comment]
If nobody has started with this I can take it!

**Comment by dnil** [comment]
There still seems to be an issue with the dynamic gene panel:
![Screenshot 2021-08-19 at 09 59 37](https://user-images.githubusercontent.com/758570/130034983-9a7a9b20-45f0-40f5-9b27-b8da9b280095.png)
Can add 37/38 genes but not hg38-only on v4.37-release-candidate.

**Comment by dnil** [comment]
Well, basically right now you can only add genes from the same build as the case. Perhaps that is not so bad.
