### ISSUE TITLE
Use latest SciLifeLab logotype

### ISSUE THREAD

**Issue by patrikgrenfeldt** [Clinical-Genomics/scout#2735]
Scout is using the old logo:
<img width="412" alt="image" src="https://user-images.githubusercontent.com/6697636/123791561-e36fe580-d8df-11eb-9065-c093a3291015.png">

There is a new logo that should be used instead of the old one:
<img width="483" alt="image" src="https://user-images.githubusercontent.com/6697636/123791651-00a4b400-d8e0-11eb-9ecb-038895e6aeb9.png">

**Comment by patrikgrenfeldt** [comment]
[Link](https://github.com/Clinical-Genomics/cgweb/blob/master/static/scilifelab-logo.png) to logo

**Comment by mikaell** [comment]
I'll take it.
