### ISSUE TITLE
Make logos on Scout home page configurable

### ISSUE THREAD

**Issue by mhkc** [Clinical-Genomics/scout#2739]
For our accreditation we need to remove the SWDAC logo and add a region skåne logo. So we need a proper method for configuring the layout of the login page.

Question: Which organization is responsible for scout, KI, Scilife or both?

**Comment by northwestwitch** [comment]
I'm not sure, @vwirta?

**Comment by northwestwitch** [comment]
Would it work to just add the region Skåne logo? The cool software has a lot of logos from the many companies that use it.. 😁

**Comment by mhkc** [comment]
I dont mind adding the logo. However i do think we need to make the swedac one configurable since we would ultimately like to add the logo that is relevant for us.

**Comment by ehre** [comment]
Yeah why not keep/add all affiliation logos, and perhaps throw in GMS as well? 🥇  But I do want to stress that @mhkc is completely right that for quality reasons we need to be able to configure the accreditation logo.

**Comment by vwirta** [comment]
> I'm not sure, @vwirta?

I never really thought about the logos... 

I'd like to propose that we add text onto the login page above the logos saying 'Developed by:' and all relevant contributors.
Then we remove the Swedac logo from the login page, but keep it in the delivery report (when applicable for the specific analysis).

**Comment by mhkc** [comment]
@vwirta which analysis reports should have the swedac logo?

**Comment by vwirta** [comment]
@mhkc in our case it is the Delivery Reports for the analyses that we have accredited. 
I believe the delivery report generator checks if a certain analysis is flagged as accredited or not in our analysis database.
