### ISSUE TITLE
same transcript with 2 different HGVS description

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#274]
something odd here. same transcript XM_5265956  the variant p.Asp415His (first line) can not have cDNA description c.*1362G>C (second line) in the Transcript overview window.
see screen view

![16025_transcript](https://cloud.githubusercontent.com/assets/12525201/13631801/c6957a52-e5e6-11e5-883c-1e8f1d3f74e6.PNG)

**Comment by henrikstranneheim** [comment]
If you look at the transcript table you will see that there are 2 ensemble transcripts associated with the XM transcript. Hence, there can be 2 different HGVS annotations since it is based on the ENST and not the RefSeq transcript.
