### ISSUE TITLE
Isort Stops PR Checks Quietly Doing Sisyphean Edit

### ISSUE THREAD

**Issue by mikaell** [Clinical-Genomics/scout#2741]
I created a PR (#2737) and noticed that the checks had not finished overnight. 

It seems like Isort exists with a error and stops the execution of checks quietly. 

https://github.com/Clinical-Genomics/scout/runs/2959624096?check_suite_focus=true

![image](https://user-images.githubusercontent.com/1150065/124092970-b0506200-da57-11eb-9d30-1dad6693d43f.png)

Meanwhile the checks in the PR never finish:
![image](https://user-images.githubusercontent.com/1150065/124093073-cb22d680-da57-11eb-976a-61bfa1257c19.png)

The change isort wants to do is the following:
```
diff --git a/tests/parse/test_parse_case.py b/tests/parse/test_parse_case.py
index 6531ed522..d0c4ef8ee 100644
--- a/tests/parse/test_parse_case.py
+++ b/tests/parse/test_parse_case.py
@@ -1,4 +1,4 @@
-from datetime import datetime
+from datetime import datetime
 from pprint import pprint as pp

 import pytest
```

Delete a line and then add the same line once again…

**Comment by dnil** [comment]
It really really wants to keep busy! Well, lets see if restarting helps then. Else perhaps check for non printing characters or other oddness around there - or try recreating on its own?

**Comment by mikaell** [comment]
<--- Fixed!
