### ISSUE TITLE
Connection between SCOUT and new version of Alamut is lost...

### ISSUE THREAD

**Issue by KickiLagerstedt** [Clinical-Genomics/scout#2745]
We have installed the new version of Alamut - AlmutVisualPlus

Due to this we can not "connect" between SCOUT and the new version of the program.

According to @dnil this could be due changes in HTTP-API (and hopefully only this)

Here is their reply regrading this question:

_Dear Kristina,

Actually API in Alamut Visual Plus requires the user or the third-partysoftware to provide its institution ID and API key (this API key is created upon request, I forward your request to our Sales department). You can find all needed information in the user manual on page 63 (https://extranet.interactive-biosoftware.com/User%20Guide%20Alamut%20Visual%20Plus%20v1.2.pdf).

Best,

Thomas_

**Comment by dnil** [comment]
Thanks! A per institute configurable ID and API key seems in order. Alamut requests to default to old behavior if unset.

**Comment by KickiLagerstedt** [comment]
Dear Mrs Lagerstedt Robinson,


Please find below your Alamut Visual Plus API key:

27363363

The API documentation is available here: https://extranet.interactive-biosoftware.com/alamut-visual-plus_API.html <https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fextranet.interactive-biosoftware.com%2Falamut-visual-plus_API.html&data=04%7C01%7Ckristina.lagerstedt%40ki.se%7Cc6ec391057db4a2b38bd08d93fc38665%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C637610931276803714%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=bnlaDoNRvjnaahKqBeKnnzJ27acRwlVVeK14n4ztQb0%3D&reserved=0> 

Best regards

Aurore CASTAGNE
Sales Operation Specialist

**Comment by northwestwitch** [comment]
Thanks @KickiLagerstedt, I've edited your comment to hide the key, in case it was private or something. I'll take a look later today!

**Comment by northwestwitch** [comment]
@KickiLagerstedt I've created a test fix for this issue. I'm going to install it on a demo server of Scout so it can be tested by hospital users. Do you want to be the beta tester?

**Comment by northwestwitch** [comment]
Ot's installed on the stage server now. I've saved an Alamut API key for cust002 now: https://scout-stage.scilifelab.se/cust002/. Could you check when you have time? Thanks!

**Comment by KickiLagerstedt** [comment]
Sorry Chiara - but I do not have time - but I think  Nicole Lesko can try!

**Comment by northwestwitch** [comment]
> Sorry Chiara - but I do not have time - but I think Nicole Lesko can try!

Thanks, I'll ask her!
