### ISSUE TITLE
Spinning "Work Indicator" Keeps on Spinning

### ISSUE THREAD

**Issue by mikaell** [Clinical-Genomics/scout#2751]
The spinning "work indicator" wont disappear. How to trigger the bug:

1. Go to Case page
2. Leave Case page
3. Hit the Back button
-Now returning to the Case page the "work indicator" won't disappear.

![image](https://user-images.githubusercontent.com/1150065/124719605-9e633900-df07-11eb-961b-fc44d336b2a2.png)

**Comment by moedarrah** [comment]
I tested the bug both locally and in stage and it's only happened when working locally. I think the issue has nothing to do with the spinner it's happening because the page is loading. but we can get over the problem by click again at the same link we click on (double click).

**Comment by mikaell** [comment]
Hmm. I can reproduce it on stage using Safari 14.0.1. But with Firefox 88.0.1. So it seems to be browser related. Would be interesting to know how it behaves in other environments. However, not high priority. I suppose it can be closed for now without any further action.
