### ISSUE TITLE
Dissmiss from view of SNV variants

### ISSUE THREAD

**Issue by 29vd** [Clinical-Genomics/scout#2755]
You can dismiss variants from the overview of variants that you get for Clinical SNV and Indels, By ticking the box in front of the genename and then choose a reason for dissmissing in the bottom. However, the reason for dissmissal will be annotated wrong. If I choose "no plausible compound", the tag will be "clinical dismiss"
[Dismiss issue.pdf](https://github.com/Clinical-Genomics/scout/files/6790461/Dismiss.issue.pdf)

**Comment by northwestwitch** [comment]
Confirmed bug, thanks for reporting it! It's easy to fix but unfortunately we are understaffed at the moment and the fix will be deployed in August. Please dismiss using the select present on each variant page to avoid this problem for the moment.
