### ISSUE TITLE
Automatically sending reports via email

### ISSUE THREAD

**Issue by leahkemp** [Clinical-Genomics/scout#2759]
Hi all, thanks again for the great software!

I hope to contribute soon when I have some time.

Prompted by a request from one of the clinicians we're working with to print the reports that scout automatically generates, my lab and I have been thinking about the larger question of whether or not it's a good idea to have sensitive patient data being physically printed and whether it's safer/more secure to encourage clinicians to use digital versions of the reports

We're thinking about a feature in scout that encourages the clinicians to use digital versions of the reports. For example an option to email these reports to a given email address?

What are your thoughts?

Leah

**Comment by northwestwitch** [comment]
Hi Leah!
Sorry for the late reply, it's holiday season and people here are scarce at the moment :) 
It's a good suggestion. I'm not exactly sure how our clinicians handle the reports (I'm sure there is printing at some point) but it would be nice to know what they think about it. 
Question: these emails would be sent by Scout (a unique scout email) or by specific users using the email provided for logging in into Scout? Because this latter option could be tricky if the method chosen for authentication is Google. For instance in our facility we create for each user a Google email like this: name.surname@clinicalgenomics.se, which is not their work email (that you probably would use for emailing these reports)
On the other hand if you log in your users using LDAP you have this issue covered 🤔

**Comment by dnil** [comment]
Hi there! Im also just back from vacation - Sweden is nice and relaxed in that way. It would make some sense to be able to return reports directly for e.g. a LIMS to import.

Likely together with a format more suited for variants like VCF or BED for the mentioned variants as well to simplify their inclusion into a final clinical report.

That said, we usually do not print the reports, but save a copy of the generated PDFs in our LIMS. In some patient flows one page from the report is printed as a placeholder to pass the baton of analysis internally.

My advise would be not to allow an email option for reports. Even if the individuals are pseudonymised with random or running sample numbers or such, the few variants included on reports may still be enough to uniquely identify them, and email is not terribly secure. For a couple of other systems we instead use sftp / scp setups to exchange patient data between the sequencing facility and the clinic.

**Comment by northwestwitch** [comment]
Encrypted emails might be safer, but also quite complicated to achieve (and to exchange!)

**Comment by dnil** [comment]
Yes, public key exchanges etc never took off in the 90s, and were kind of superseded by end-to-end encrypted messaging apps. But sftp is not bad: compare how cg-web retrieves order json's from StarLIMS or Statina delivers structured results for StarLIMS import for the NIPT flow.

**Comment by dnil** [comment]
For Scout, we could add a third option for the report: export for transfer. It would save the pdf to a designated directory on the system that some other process / cronjob would deal with transferring to its destination on the clinical side, using the appropriate credentials.

**Comment by northwestwitch** [comment]
> some other process / cronjob would deal with transferring to its destination on the clinical side, using the appropriate credentials.

Once the case has been marked as solved I guess. Could be done, but doesn't really help other institutes. A bit like the customized reruns triggering issues..

**Comment by dnil** [comment]
> Once the case has been marked as solved I guess.

Yeah, or on click simply, trusting the user to know when would be a good time in their flow. We would often share a report for discussion or a small round - or validation work for uncertain calls - before setting status.

> Could be done, but doesn't really help other institutes. A bit like the customized reruns triggering issues..

Agreed! It quickly spins out into the rest of the infrastructure, with other services to implement, but saving report to a server side file system would be a rather simple thing to implement in Scout if it helps Leah.
