### ISSUE TITLE
Some logos are hidden on the first page

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#2772]
On Safari it looks like this:

![image](https://user-images.githubusercontent.com/28093618/129014124-f04bdbaa-d12a-4e58-a22e-462633fd3b90.png)

On chrome:
![image](https://user-images.githubusercontent.com/28093618/129014166-5aae7593-aadc-4c27-aa1e-0c002957a2b7.png)

**Comment by northwestwitch** [comment]
> On Safari it looks like this:
> 
> ![image](https://user-images.githubusercontent.com/28093618/129014124-f04bdbaa-d12a-4e58-a22e-462633fd3b90.png)
> 
> On chrome:
> ![image](https://user-images.githubusercontent.com/28093618/129014166-5aae7593-aadc-4c27-aa1e-0c002957a2b7.png)

**Comment by northwestwitch** [comment]
It might be a good opportunity to add links to the relative pages of those logos!

**Comment by Spokaren** [comment]
Hi i would like to contribute to this issue

**Comment by northwestwitch** [comment]
Hi and thanks to both! You can read [here](https://github.com/Clinical-Genomics/scout/blob/master/CONTRIBUTING.md) how to contribute to this repository. Might I ask you what brings you to our software? 😀

**Comment by northwestwitch** [comment]
This could be my browser and my zoom level, so I'm closing this issue now. Let's reopen if the page looks funny on someone else's browser!
