### ISSUE TITLE
Variants with no supporting reads

### ISSUE THREAD

**Issue by Bianca-T** [Clinical-Genomics/scout#278]
Hi,

I get variants like the one below in my list.

Best,
Bianca

![screen shot 2016-03-30 at 16 09 56](https://cloud.githubusercontent.com/assets/5881356/14144935/277b82b0-f692-11e5-9e8d-64afb1d95619.png)

**Comment by emmser** [comment]
@henrikstranneheim Can you take a look at this?

**Comment by moonso** [comment]
Hi,

I don't think there is a problem with this variant. The allele depth only shows high quality reads so there are probably reads that support the call.
You can see that the genotype quality is fairly low. In a case like this it is up to the user to say that the variant is uninteresting.
Or do you think we should handle it in a different way @Bianca-T ?

**Comment by Bianca-T** [comment]
Hi Måns,

Is genotype quality taken into account in the ranking?

**Comment by moonso** [comment]
I don't remember if it's done yet, maybe @henrikstranneheim can check? 
But it is no problem to add that

**Comment by 29vd** [comment]
Hi

We have experienced the same with indels recently
[Till SciLife 160331.docx](https://github.com/Clinical-Genomics/scout/files/197634/Till.SciLife.160331.docx)

**Comment by henrikstranneheim** [comment]
@Bianca-T The reason you do not see any AD reads is that this variant is only called with samtools (MIP combines 3 callers: GATK, Freebayes and Samtools). Samtools uses another annotation DP4 to record the same information as the AD field. However, Scout does not read the DP4 field and hence will show AD=0,0 (we will have to think about the best way to fix that). Your variant has 9 high-quality non-reference bases (out of DP=54). 

@Bianca-T An aggregated genotype quality is calculated for all members and scored in the ranking model. An aggregated GT below 20 will add -5 to the rank score. 

@29vd Regarding family 15055. This is a multiallelic call C --> CG,CA that gets splitted. The C --> CG variant is very common and is filtered uppstream of Scout. There is very poor evidence for the C --> CA variant and it is only picked up by GATK, but with no solid support, hence AD=0,0 and "GT=./.". I am suprised GATK recorded it as a variant and it is very likely a false positive.

**Comment by Bianca-T** [comment]
Have you considered a field in scout (maybe under the GT call section) mentioning how many callers support the called variant?

**Comment by henrikstranneheim** [comment]
Here:
#255

**Comment by moonso** [comment]
Fixed in #283
