### ISSUE TITLE
Command docker-compose up -d not working

### ISSUE THREAD

**Issue by elevu** [Clinical-Genomics/scout#2780]
When running the command
`docker-compose up -d`

I get the error `scout/chanjo either does not exist, is not accessible, or is not a valid URL.`

**Comment by northwestwitch** [comment]
Confirmed bug, probably a result of merging #2752. I'll revert the docker-compose to what is was originally (without chanjo integration).
A scout-chanjo integration is already present (but I don't know if it works) under: containers/development/docker-compose-chanjo-report.yml.

I've recently become admin on pypi for chanjo so we could perhaps avoid including complicated installation steps in the docker-compose now @mhkc!

**Comment by northwestwitch** [comment]
I can fix this next week if nobody beats me. I have a very slow internet connection from home today, and it doesn't go really well with the pulling and building of containers from Docker Hub!
