### ISSUE TITLE
A custom param missing in prod and stage config file will hide local observations table when we deploy scout web

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#2781]
See this commit: 
https://github.com/Clinical-Genomics/scout/commit/0a283ebc7b74e206de71e732fd6e357ebc17ed48#diff-f57da8aeea4bac4cd8374cdc4c550502cf8768ba15b7b3d6f6ff424b21076a85

Actions:
- Fix syntax of the param
- Introduce changes so local observations will be shown on Scout and Scout stage @CG Stockholm

**Comment by dnil** [comment]
This looks fixed. Closing!
