### ISSUE TITLE
Add DeepVariant to known Callers

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#2792]
Should be available for both INFO/set parsing and INFO/FOUND_IN.

**Comment by dnil** [comment]
Presumably MIP11 cases will default to DeepVariant, so consider easing the default for missing caller over to DeepVariant as well?

**Comment by dnil** [comment]
The branch above #2793 will fix this if the caller id string is correct. Closing for now: simply reopen @jemten if it needs changing or a default switch is desired.

**Comment by jemten** [comment]
Just to confirm, MIP adds this tag to the info field of all variants called with deepvariant `FOUND_IN=deepvariant`.
