### ISSUE TITLE
Using filters in scout

### ISSUE THREAD

**Issue by terestahl** [Clinical-Genomics/scout#2800]
Hej support,

When trying to filter genes in scout using HGNC Symbols field (I want to be able to create new filters and save the fiters) I get  an answer that I do not understand: “Genes not included in gene panel versions in use when loading this case (clinical list):['A1CF', 'AADAC….”, what does this mean ? how to continue? what to click?

 
Kind regards

Teresita
![1](https://user-images.githubusercontent.com/74291103/130422767-775ad70f-8caf-4ce2-93ab-fabccead6018.jpg)
![2](https://user-images.githubusercontent.com/74291103/130422788-c64f30bf-d715-42f0-9eec-749d716927c5.jpg)

**Comment by northwestwitch** [comment]
Hi!

The messages shown is just a warning, it means: "be aware that these genes were not found in any gene panel used for the case analysis". It's not an error, but just in case you want to avoid incidental findings.

Once you are satisfied with the selected params you have in the filter, you can save the filter by giving it a meaningful name and clicking on the "Save filter" blue button on the bottom part of filters.

**Comment by terestahl** [comment]
Hi again,

OK, good I do not mean it was an error
I want to understand what the answer means
So even if they are not present in other gene panels the blue genes will be saved in my filter and the yellow ones not?

Because one could also think that the genes could have already been filtered out from the list as they are not included in any panels? but this is not the case? Difficult to be sure, but I guess I understand. Just save the filter and I will have the blue genes left to filter the data

Thanks

teresita

**Comment by northwestwitch** [comment]
Yellow genes are those that are not found in Scout database, and won't be used in filtering.
Blue genes are used in filtering and will be used again when you save the filter. If you include in your filter genes are were used in your case analysis, these genes will be also used in filtering, but now shown in the blue warning message above.

**Comment by terestahl** [comment]
OK good thanks for the explanation

**Comment by northwestwitch** [comment]
You're welcome :) Closing the issue now!

**Comment by terestahl** [comment]
I do not want to make issues for small things like this, perhaps better to ask you directly, it was Henrik that told me to do that

**Comment by northwestwitch** [comment]
No worries, an issue on github is not necessarily a real issue. It's
perfectly fine to ask questions there. And it's good to have it answered
there because if someone else is wondering the same, then they can see the
answer instead of asking again. Github issues are the best place to
understand stuff. Could also be that if I don't know the answer someone
else does. And if you look into the past issues perhaps you find an answer
already without the need to ask!

Cheers,
Chiara
