### ISSUE TITLE
Variant page RD frequencies (in particular gnomAD) too far down

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#2807]
Easy enough just to move e.g. the OMIM box down, but I would also suggest just harmonising with the cancer version for the parts that are applicable also to RD.

**Comment by 4WGH** [comment]
can it be place back where it was above the local observation?
so we have frequencies information all together in the same middle column ?
this is the reason is was there :-)

**Comment by Leif-glitch** [comment]
> can it be place back where it was above the local observation?
> so we have frequencies information all together in the same middle column ?
> this is the reason is was there :-)

Good suggestion above. Frequencies should be together on the page preferably with gnomad on top.
