### ISSUE TITLE
Variant classification history missing on variant page

### ISSUE THREAD

**Issue by Leif-glitch** [Clinical-Genomics/scout#2811]
Previously variant classification history was availible beneath ACMG classification with date and person who classified a variant linking to the page with selected ACMG criterias. This seems to be no longer availible on the variant page. 

![image](https://user-images.githubusercontent.com/63041167/130611730-c89b4264-2072-4583-857b-9b62669b996d.png)

**Comment by northwestwitch** [comment]
Right! This is not intended and we'll fix it. Thanks for reporting it!
