### ISSUE TITLE
different inheritance patterns in the pipelines

### ISSUE THREAD

**Issue by ingkebil** [Clinical-Genomics/scout#282]
I got an email from Giedre about following improvement:

I also wonder if it would be possible to have different inheritance patterns in the pipelines
<img width="1275" alt="screen shot 2016-04-12 at 11 18 54" src="https://cloud.githubusercontent.com/assets/239608/14474334/bc924c84-00fc-11e6-97eb-8110d68de531.png">

, so the customer can change it and rerun the data as it is at the Broad Institutes pipeline (see the screenshot). At clinical work we sometimes change our opinion and need rerun of the data in a another inheritance pattern or just consider a differential which could be inherited in another way.

I work at Harvard and work with some data from my bosses lab. Please let me know if you would like me to take more screenshots :), but I suppose you are aware of Browse.
Warm regards,

Giedre

**Comment by henrikstranneheim** [comment]
A variant in the analysis is always annotated with the classical mendelian inheritance models. From Scout you can filter on these models and it will show you the variants following one or more models depending on your filtering settings, i.e. you can do a dynamic search from Scout on this annotation and no reanalysis (pipeline-wise is needed).
