### ISSUE TITLE
SCOUT opens Coverage window upon building "General report" (pdf)

### ISSUE THREAD

**Issue by KickiLagerstedt** [Clinical-Genomics/scout#2829]
If I would like to download the general report - a "flik" for the coverage analysis is automatically opened. 

The general report is downloaded as usual but it is not necessary to open the coverage data...

**Comment by northwestwitch** [comment]
What browser are you using? I can't reproduce it in chrome

**Comment by dnil** [comment]
I have the same in Safari: it's the `target=_blank` for stopping the spinner.

**Comment by dnil** [comment]
..but I agree I see Chrome closing the blank page when it is found empty!
