### ISSUE TITLE
Permission denied issue when viewing coverage/qc and multiqc file on Scout

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/scout#2833]
Report from Hero the following errors happen when viewing the case https://scout.scilifelab.se/cust087/F0041465

![image](https://user-images.githubusercontent.com/1086877/131506804-fd3dfd5e-d556-4035-9db7-3196f0b22521.png)

and

![image](https://user-images.githubusercontent.com/1086877/131506827-007f79a6-adec-4172-8571-da03d539bb35.png)

Is this related to recent Hasta incident?

**Comment by hassanfa** [comment]
writing body text...

**Comment by northwestwitch** [comment]
Probably, could you ask her to check again?

**Comment by dnil** [comment]
Most likely yes. If the fs tunnel was down at the time, that would happen.

**Comment by hassanfa** [comment]
> Probably, could you ask her to check again?

Already did. But i thought it would not hurt to check.

**Comment by dnil** [comment]
Thanks, looks like it is working now for that case. Closing for now, but feel free to reopen if it happens again!
