### ISSUE TITLE
Slow searches in cases with no gene panels

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#2834]
See https://github.com/Clinical-Genomics/scout/issues/2824, but essentially cases with no loaded panels appear to be very slow searching. Perhaps due to basically every gene appearing as non-clinical in each step of checks?

Thanks for the report @terestahl!

> I only tried loading a saved filter that includes  ~1500 genes, in addition to some requirements for functional annotations, allele freq etc, that are also saved in the filter
> And I am trying
> https://scout.scilifelab.se/cust127/GMSB-ST008/cancer/variants

**Comment by dnil** [comment]
I would actually guess this is now working rather ok for you again? At least it is quick when I try it. 😊 
If its ok with you Id like to change this to a QoL refactoring request, and speed it up a little anyway, since some of the current checks are redundant.

**Comment by terestahl** [comment]
yes it is like before now thanks 😊

Skaffa Outlook för Android<https://aka.ms/ghei36>
________________________________

**Comment by dnil** [comment]
Hi, just checking old issues! This should also have been sped up slightly by https://github.com/Clinical-Genomics/scout/pull/2832/files as well. Let us know if it is still an issue. Again, note that gene panels is the way you want to go for long lists: versioning, clearer audit history, proven use-case and being able to click and investigate the genes that make up the list are good features. 😄
