### ISSUE TITLE
Cancer variants are missing ClinVar accession and revstat

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#2836]
I've checked a few and I think I see a pattern. Looks like only the clinical significance is parsed correctly.

To test this:
- on stage or prod, take one RD case and one cancer case
- Go the the variantS list and pick one that has the clinvar tag
- Check that clinvar accession and revstat is missing on the cancer variant but present on the RD one.

In the database, the respective key/value looks like this:

![image](https://user-images.githubusercontent.com/28093618/131618910-2457df9f-b224-4242-ac34-667ee3c26063.png)

This might affect a lot of cancer cases retroactively

**Comment by northwestwitch** [comment]
Checking the VCF header of a cancer case, looks like the accessions has key `ClinVar`, taken from VEP annotation. I don't see any revstat info. 

![image](https://user-images.githubusercontent.com/28093618/131629264-97c971dc-a8ba-4b80-967f-e2da910bf699.png)

**Comment by northwestwitch** [comment]
@hassanfa do you confirm what I see in the comment above?

**Comment by dnil** [comment]
Ping Team BALSAMIC? 😊

**Comment by northwestwitch** [comment]
@khurrammaqbool ?

**Comment by northwestwitch** [comment]
ClinVar info on a RD case looks like this instead:

![image](https://user-images.githubusercontent.com/28093618/131631031-5b35bc00-62d8-4ceb-b3e2-182e2bc50feb.png)

**Comment by hassanfa** [comment]
I don't see any revstat in my demo data. Do you have a case name i can look into?

**Comment by hassanfa** [comment]
we have team 🅱️alsamic! @Clinical-Genomics/balsamic

**Comment by northwestwitch** [comment]
@hassanfa actualgecko, cust000

**Comment by hassanfa** [comment]
the one in production is an old run. probably old version of VEP as well. I'll start a new run, and check there.

**Comment by northwestwitch** [comment]
I start to think that this is no bug and Balsamic just doesn't save ClinVar accession and revstat, just significance

**Comment by hassanfa** [comment]
I think we'll annotate it outside VEP then. The same way we do for gnomad, cosmic, and others.

**Comment by northwestwitch** [comment]
I thought so, but where?

**Comment by northwestwitch** [comment]
Ah you mean it's not something that you currently do but you'll start annotating it from now?

**Comment by hassanfa** [comment]
Yes, start an explicit annotation for these. What tag would you like in INFO?

**Comment by hassanfa** [comment]
Or even better, let me look into ClinVar VCF, and get back to you with options.

**Comment by hassanfa** [comment]
I agree. INFO is much better and easier to process. All three tags are A-ok.

I'll add some more as well:
`ORIGIN` this might come handy to tell where it is coming from. ` unknown; 1 - germline; 2 - somatic; 4 - inherited; 8 - paternal; 16, etc`
`CLNVC` and `CLNVCSO` variant class and sequence ontology for variant.

**Comment by northwestwitch** [comment]
Sounds great, thanks @hassanfa!

**Comment by northwestwitch** [comment]
I'm closing this issue as once the ClinVar annotations will be present in cancer VCF files they will be parsed just like the RD VCF files, with no further action by our side
