### ISSUE TITLE
Bulk dismissing variants from variantS page doesn't work on all browsers

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#2839]
Tested on chrome and it works. I think the problem is Internet Explorer. Perhaps could be easily fixed by changing the javascript code that controls the dismissal options activation depending on the selected variants.

**Comment by dnil** [comment]
I've also asked Emma T over another channel what browser she was using.

**Comment by northwestwitch** [comment]
Thanks I meant to ask her in the customer ticket but your way might be faster!

**Comment by dnil** [comment]
Let's see..

**Comment by northwestwitch** [comment]
It's probably the `disabled` attribute used in the javascript code. It's not supported in IE prior version 8: https://www.w3schools.com/tags/att_option_disabled.asp

The code we use in that function is here: https://github.com/Clinical-Genomics/scout/blob/c3c6b1d1c94ca4e36065a7d61b8425f390d99475/scout/server/blueprints/variants/static/form_scripts.js#L164

**Comment by dnil** [comment]
So, this particular case was fine: the user had a modern browser, and had just not realised that the drop down was clickable.

**Comment by northwestwitch** [comment]
Ok, good to have this issue here for reference, so people will know that the functionality doesn't work on IE 8 or older. Closing it!
