### ISSUE TITLE
Scout missed a COSMIC tag or didn't parse it

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/scout#2844]
variant: https://scout.scilifelab.se/cust091/aliveswift/cancer/fdc84bb51b179c64b4c97008c8662761?cancer=yes

Has a COSMIC variant assigned to it: https://cancer.sanger.ac.uk/cosmic/mutation/overview?id=22870608

I can also see it in the raw uploaded VCF: 
![image](https://user-images.githubusercontent.com/1086877/131805932-09e2b894-e6ae-46ca-8958-720a41441d5c.png)

But Scout failed to parse it or doesn't show the tag at all.

**Comment by northwestwitch** [comment]
Hi I think this might be the same issue described in #2826 (point 3), fixed in #2828

**Comment by northwestwitch** [comment]
But to be sure that it is parsed and saved I'll check in the database!

**Comment by hassanfa** [comment]
Thank you for swift response Chiara.

Can we check this in stage for the latest master?

**Comment by northwestwitch** [comment]
It didn't parse it, checking the database and the key has no value:

![image](https://user-images.githubusercontent.com/28093618/131808233-420dd959-50b2-43ee-af3e-ac3c5902129e.png)

It's a different bug then. We'll fix!

**Comment by hassanfa** [comment]
These are custom VCF, since sample quality was not optimal. I'll Slack you the path.

**Comment by northwestwitch** [comment]
I think I'm understanding why this happens:

Checking the VCF headers: you can have COSMIC IDs annotated in the INFO field (relative to the variant) or in the CSQ (relative to the transcripts):
```
##INFO=<ID=CSQ,Number=.,Type=String,Description="Consequence annotations from Ensembl VEP. Format: Allele|Consequence|IMPACT|SYMBOL|Gene|Feature_type|Feature|BIOTYPE|EXON|INTRON|
HGVSc|HGVSp|cDNA_position|CDS_position|Protein_position|Amino_acids|Codons|Existing_variation|DISTANCE|STRAND|FLAGS|VARIANT_CLASS|SYMBOL_SOURCE|HGNC_ID|CANONICAL|TSL|APPRIS|CCDS|
ENSP|SWISSPROT|TREMBL|UNIPARC|REFSEQ_MATCH|SOURCE|GIVEN_REF|USED_REF|BAM_EDIT|GENE_PHENO|SIFT|PolyPhen|DOMAINS|miRNA|HGVS_OFFSET|AF|AFR_AF|AMR_AF|EAS_AF|EUR_AF|SAS_AF|AA_AF|EA_AF
|gnomAD_AF|gnomAD_AFR_AF|gnomAD_AMR_AF|gnomAD_ASJ_AF|gnomAD_EAS_AF|gnomAD_FIN_AF|gnomAD_NFE_AF|gnomAD_OTH_AF|gnomAD_SAS_AF|MAX_AF|MAX_AF_POPS|CLIN_SIG|SOMATIC|PHENO|PUBMED|MOTIF_
NAME|MOTIF_POS|HIGH_INF_POS|MOTIF_SCORE_CHANGE|COSMIC|COSMIC_CDS|COSMIC_GENE|COSMIC_STRAND|COSMIC_CNT|COSMIC_AA">
##INFO=<ID=COSMIC,Number=.,Type=String,Description="/home/proj/production/cancer/reference/GRCh37/variants/cosmic_coding_muts_v89.vcf.gz (exact)">
##INFO=<ID=COSMIC_CDS,Number=.,Type=String,Description="CDS field from /home/proj/production/cancer/reference/GRCh37/variants/cosmic_coding_muts_v89.vcf.gz">
##INFO=<ID=COSMIC_GENE,Number=.,Type=String,Description="GENE field from /home/proj/production/cancer/reference/GRCh37/variants/cosmic_coding_muts_v89.vcf.gz">
##INFO=<ID=COSMIC_STRAND,Number=.,Type=String,Description="STRAND field from /home/proj/production/cancer/reference/GRCh37/variants/cosmic_coding_muts_v89.vcf.gz">
##INFO=<ID=COSMIC_CNT,Number=.,Type=String,Description="CNT field from /home/proj/production/cancer/reference/GRCh37/variants/cosmic_coding_muts_v89.vcf.gz">
##INFO=<ID=COSMIC_AA,Number=.,Type=String,Description="AA field from /home/proj/production/cancer/reference/GRCh37/variants/cosmic_coding_muts_v89.vcf.gz">
```

A variant that shows (and saves at the variant level in the database) **COSMIC IDs collects these IDs from the info field**.
Your variant is missing COSMIC IDs in the info field but has COSMIC IDs in the CSQ (at the transcript level) and for some reason these IDs and not saved in the variant document. I'm a bit closer to the solution I think!

**Comment by northwestwitch** [comment]
No, actually is the other way around: your variant has data in the INFO field but not in the txs, but you get my point.
