### ISSUE TITLE
validated message not appearing - bug?

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#2854]
![image](https://user-images.githubusercontent.com/12525201/132018337-d411c54c-5e81-4262-a197-8d7a646a3a12.png)

case 21130.
both variant are true positive, for one the is the "validated" tag, not for the other.

mini bug?

**Comment by northwestwitch** [comment]
An half bug I'd say 😉. Thanks for reporting, we'll check!

**Comment by dnil** [comment]
It is likely because one of them has used the CMMS way with "Order Sanger" email and so forth, and the other one has been silently verified only checking the box Klin gen style. The pains of merger? 😄

**Comment by 4WGH** [comment]
I think it should be independent from Sanger order :)
true positice can be confirmed even with other method :)

**Comment by dnil** [comment]
Agreed!
