### ISSUE TITLE
Single-sample case has 2 samples in the IGV variant viewer

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#2867]
Check any variant of this case: https://scout.scilifelab.se/cust087/F0038943-2/

**Comment by christacosta** [comment]
Just a comment: I have created a group for this patient with the current and previous analysis so that we can see both samples in parallel in igv.

**Comment by northwestwitch** [comment]
Aha! Thanks, this is helpuful!

**Comment by northwestwitch** [comment]
Closing this is issue as this is the intended behavior. @hassanfa I didn't consider that the case belongs to a group (check previous comments). Closing this issue now!

**Comment by hassanfa** [comment]
Thanks Christa! Makes sense. We thought it is a bug 😅
