### ISSUE TITLE
Check and flag novel variants if identical to previously seen causative variant

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/scout#288]
Identical equals back-end variant ID (chr_start_stop_ref_alt). It would be great to get a link to the causative variant on the family page

**Comment by moonso** [comment]
Think it will look something like this:
##Case Page
**Variants in genes with previously marked causative variants**
variant_id_1
variant_id_2

##Variant Page
Should be a Red light warning if the variant have been previously marked causative

**Comment by moonso** [comment]
We will solve this in #328
