### ISSUE TITLE
Comment field inserts spaces after punctuation marks

### ISSUE THREAD

**Issue by mhkc** [Clinical-Genomics/scout#2891]
The comment field inserts a space after a punctuation marks. This causes issues when writing gene nomenclature and decimal numbers which can cause the user to misinterpret the results.

Eg: `foo!doo?moo.crow,flow` => `foo! doo? moo. crow, flow`

The padding seems to be applied when rendering the template as the comment is not padded in the database.

**Comment by dnil** [comment]
Hi, this was a "hotfix" to two issues we had with formatting long comments. I guess you never saw them:
https://github.com/Clinical-Genomics/scout/pull/2455 and https://github.com/Clinical-Genomics/scout/pull/1976. This is not the Final Solution, but removing the padding has to address the long word issue in another manner, e.g. by introducing more flexible wrapping to the appropriate comment fields.
