### ISSUE TITLE
login issue

### ISSUE THREAD

**Issue by ielvers** [Clinical-Genomics/scout#2897]
Hi there!
I was using Scout all morning with no issue but about half an hour ago I needed to download a coverage report and got a server network error. When that happens I normally just log out of Scout and then log in again and then downloading works just fine. However now I can't log back in. I can log out and in of my google clinicalgenomics account in the web browser but when I try to log into Scout by clicking here
![image](https://user-images.githubusercontent.com/57791644/135079997-9e1b8580-e414-442d-8ce1-54db75bf3c48.png)
all I get is this:
![image](https://user-images.githubusercontent.com/57791644/135080070-81ec8e94-606e-42f4-9de2-e225a2eff3c3.png)

This happens regardless of whether I'm logged in or logged out of my clinicalgenomics account. I've tried this for 30 minutes now.

Any ideas why this is happening? None of my colleagues dare log out to see if they'll be able to log in again. They're such chickens.

**Comment by dnil** [comment]
Thank you for the report! We have been seeing mysterious errors in the log, especially during the last hour and were just about to investigate who was having trouble! 😸 We'll have a look!

**Comment by dnil** [comment]
```
2021-09-28 13:43:35,899 - scout.server.app - ERROR: Exception on /authorized [GET] [in /home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py:1892]
Traceback (most recent call last):
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
   response = self.full_dispatch_request()
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
   rv = self.handle_user_exception(e)
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
   reraise(exc_type, exc_value, tb)
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
   raise value
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
   rv = self.dispatch_request()
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
   return self.view_functions[rule.endpoint](**req.view_args)
 File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/blueprints/login/views.py", line 103, in authorized
   token = oauth_client.google.authorize_access_token()
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/authlib/integrations/flask_client/remote_app.py", line 74, in authorize_access_token
   params = self.retrieve_access_token_params(flask_req, request_token)
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/authlib/integrations/base_client/base_app.py", line 145, in retrieve_access_token_params
   params = self._retrieve_oauth2_access_token_params(request, params)
 File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/authlib/integrations/base_client/base_app.py", line 126, in _retrieve_oauth2_access_token_params
   raise MismatchingStateError()
authlib.integrations.base_client.errors.MismatchingStateError: mismatching_state: CSRF Warning! State not equal in request and response.
```
And from the server log:
```
authlib.integrations.base_client.errors.MismatchingStateError: mismatching_state: CSRF Warning! State not equal in request and response.
/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/site-packages/werkzeug/wrappers/base_response.py:479: UserWarning: The "b'session'" cookie is too large: the value was 4096 bytes but the header required 26 extra bytes. The final size was 4122 bytes but the limit is 4093 bytes. Browsers may silently ignore cookies larger than this.
```

**Comment by dnil** [comment]
Btw, I can confirm being able to log out and back in again, so Im afraid it not quite as simple as that.

**Comment by northwestwitch** [comment]
@ielvers try cleaning the browser cache, session cookies etc, it might help!

**Comment by dnil** [comment]
Perhaps you could try with clearing cache and cookies for now @ielvers, and log in again? We will try to look into the root cause in the meantime!

**Comment by ielvers** [comment]
Clearing the cache etc worked! Thank you guys - I'll try and remember to do that next time.

**Comment by northwestwitch** [comment]
This could be the cause of this: #2589

**Comment by dnil** [comment]
Super! We don't store much on the sessions anymore "directly" from Scout, basically only user name, email and locale. But there are some js applications that we include, like IGV and jQuery that do. If this happens again, could you perhaps let us know and we can try to replicate the problem?

**Comment by northwestwitch** [comment]
This could be the cause of #

> Indeed, and might live on for a bit depending on the browser used, and perhaps not be an issue for the user until next logout. Question is I guess why the session object got that big to start with: we really dont use it anymore, do we? Unless it is one of the js components?

@ielvers mentioned the coverage report. I guess that could be big if it's a lot of gene info!

**Comment by dnil** [comment]
Genious! Its most likely this, on chanjo-report:

https://github.com/Clinical-Genomics/chanjo-report/blob/af4990c8e7143545d1c68ec4cac3801204fed359/chanjo_report/server/blueprints/report/views.py#L115

**Comment by ielvers** [comment]
About the specific coverage report: this kind of network issue happens maybe once a week and always when I'm downloading a coverage report (but far from every time I download a coverage report). I log out and in again and then it works for another week-ish. This specific coverage report was on the bigger side (two gene panels), but nothing extreme.

**Comment by northwestwitch** [comment]
Thanks @ielvers this was very helpful! We've seen that error message but couldn't couple it with any behavior on Scout. Now we know the reason and we can hopefully fix it!

**Comment by northwestwitch** [comment]
This problem happened again yesterday (got an error email). It's not very easy to solve but I'll try to draft something !

**Comment by dnil** [comment]
Hi, we finally have an attempted fix to chanjo-report merged (https://github.com/Clinical-Genomics/chanjo-report/pull/44), which will be deployed next time we update Scout. Expect it sometime next week. I hope you didn't have to clear cache all too often to keep working.

To keep things simple, we will close this issue now, but we are very keen to hear if it actually worked, so please reopen if you experience this problem again after next release! Thanks!
