### ISSUE TITLE
Partial causative feature and associated HPO-terms

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/scout#291]
Sometimes a variant only explains part of the phenotype. 
A feature that marks variant(s) as partial causative and the option to attach HPO-terms that explain which symptoms that the partial causative variants contribute to would be a great addition. Especially when sharing data.

**Comment by moonso** [comment]
Ok this might be possible but it takes some thinking. How urgent is this one?

**Comment by dnil** [comment]
Ooh, epistemologically complex! :) Some disease symtoms and some mutations are given. Defining an exclusive causality is not easy. After all, there were more genetic variants (and more phenotypic characteristics). Practically depends a bit on how it will be used in the db. Often one would not mind seeing additional phenotype for a mutation. But may be overwhelmed if mutations from all over are brought in by adding some promiscuous symptom when searching for more patients.

**Comment by henrikstranneheim** [comment]
This is not something that will be used for every case. However, the earlier it is introduced (and used) the better the resolution of querying for causal variants and associated phenotypes when looking at aggregated data. I would like to include it in the scheduled update unless the workload is heavy, but that I leave to you to decide.

**Comment by moonso** [comment]
Also something to discuss in next meeting

**Comment by northwestwitch** [comment]
New button on variant page: "Partial Causative" that not put the variant in "solved" mode.

**Comment by moonso** [comment]
Could you add this @northwestwitch , we got a customer request again today about it..
