### ISSUE TITLE
Empty coverage for some cases

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#2916]
Test to check the coverage report of this case:

https://scout.scilifelab.se/cust003/21255

You get an empty report and this error message:
![image](https://user-images.githubusercontent.com/28093618/136747919-9a294d15-1ed5-4f52-a221-545fd29f7d9d.png)

This is probably the cause of this deviation: https://github.com/Clinical-Genomics/Deviations/issues/138

**Comment by dnil** [comment]
Confirmed coverage appears ok until Oct 8th!

**Comment by northwestwitch** [comment]
This is the fix: https://github.com/Clinical-Genomics/servers/pull/673/files. Closing this issue here now.
