### ISSUE TITLE
Add local observation count to variant list page frequency pop-up

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/scout#292]

**Comment by moonso** [comment]
What do you think about this one @robinandeer ?

**Comment by moonso** [comment]
I guess that if are satisfied with information from the loqusdb dump this could be done easy. Otherwise it could slow down the variants page a lot.
Would that be ok @henrikstranneheim ?

**Comment by henrikstranneheim** [comment]
Yes, that would be fine I think as long as it clear that it is the archived version. 

Skickat från min iPhone
