### ISSUE TITLE
scout variant page.

### ISSUE THREAD

**Issue by Leif-glitch** [Clinical-Genomics/scout#2934]
It seems that more changes have been enacted on the scout variant page. The information is now presented in a very confusing order (at least on laptops). 

Conservation is split away from in silico predictions and genotype is on the other side of the screen from  inheritance model (omim)  and gene models inheteritance. This division does not make much sense imho. It is very difficult to work with the current view, especially when we have meetings regarding patients. Is it possible to roll back this edit? I hope i dont sound to harsh!

p.s. It is good to see that the frequencies, gnomad and local, are presented together again.

**Comment by dnil** [comment]
Feedback is welcome, tone is not important - but does establish an ethos. 😉

No worries - fortunately I've checked with several other users who found it improved before I read this. The page is also now very similar to the cancer page, which has been in use for some time. 

Perhaps you could be a bit explicit about screen resolutions and zoom levels that you use during the patient sessions in question? I also mostly work on a laptop, but I probably use different settings?

I agree about the conservation box being a bit isolated. It does not really seem to be used with the current version of MIP though? I haven't seen a score on a modern case? GT and inheritance are intended to be checked together, and are now in one row. If we move the conservation box over to the right, it might be more obvious.

**Comment by 4WGH** [comment]
I think that having 4 windows in not good. 
When we work from lap top the information is splitted in several lines that it is very hard to work. 
The variant HGVS description is quite important to see on the firs screen as before as it is the geneticit way to represent variants and this info is fast preocessed. 

The  same happens with sharing screen program that reduce the width of what is shown.

I would prefer to have things in the same position fopr wirndonw between SNV/DEL and SV pagens rather then with the cancer view....

Homogeneity in style/size and font would also a plus for the eyes :)

Open for discussion for improvment but live, not so easy to do in written format :) 


I hope that you can make sense of what I've written

**Comment by Leif-glitch** [comment]
@dnil Im not able to access https://scout-stage.scilifelab.se/ unfortunatelly, seems like I need a different login

**Comment by dnil** [comment]
So, good enogugh, or do you have some suggestions?
