### ISSUE TITLE
Annotation of compound variants

### ISSUE THREAD

**Issue by KickiLagerstedt** [Clinical-Genomics/scout#2940]
It seems that the function of looking att compound variants (scrolling over the compound variant) is lacking information WHEN the variant affects two different genes. It did work before so...

![image](https://user-images.githubusercontent.com/17139607/138663481-58f1a4a8-301a-4132-aec1-07bbd9849a14.png)

**Comment by northwestwitch** [comment]
Could it be that the specific variants didn't have annotated info? I'm checking multi-gene variants on stage cases, and some variants actually have complete info. See for instance this variant hitting EIF4G1 and EIF2B5:

![image](https://user-images.githubusercontent.com/28093618/140874485-7ae3a690-42b7-4f6a-bf74-20135f0e8456.png)

**Comment by northwestwitch** [comment]
Check for instance the variants of this case: https://scout.scilifelab.se/cust002/F0041920/variants

1) Deselect any gene panel in filters and display all variants
2) Second last variant in the page is hitting 2 genes (MRPS34 MAPK8IP3). This variant has compounds with info displayed correctly..

Does this answer your question @KickiLagerstedt ?

**Comment by northwestwitch** [comment]
I'm going to close this branch now, but please reopen if you are still not convinced @KickiLagerstedt!
