### ISSUE TITLE
Missing inheritance model.

### ISSUE THREAD

**Issue by 29vd** [Clinical-Genomics/scout#2945]
Se  F0040791 - GMPPB och FOXP3 /CCDC22. Varför anges inte inheritance model för dessa varianter. Trodde att detta blev tomt i TRIOs när en fldr hade varianten och inte barnet. Det är inte fallet i denna TRIO och dessa varianter. Varför?
https://scout.scilifelab.se/cust002/F0040791/variants?variant_type=clinical&gene_panels=hpo
https://scout.scilifelab.se/cust002/F0040791/8056c5d351c9d44386da41daeac3a394
https://scout.scilifelab.se/cust002/F0040791/b0a101cab3b732c37d6f1d3dafcc7b62

**Comment by dnil** [comment]
I think this is well answered: please shout again @29vd if you have more to add or want more details! Thanks!
