### ISSUE TITLE
local observations count occasionally missing

### ISSUE THREAD

**Issue by ielvers** [Clinical-Genomics/scout#2959]
Hello!

We've noticed in a few cases that the local observations count is missing for occasional variants. Here is a recent occurrence:

Case 18172-2, rerun 2021-10-21. Variant https://scout.scilifelab.se/cust003/18172-2/88aa0ffdeccea4155eee94a48d0fa672. Two local occurrences reported, one is case 18172 which consists of this individual and her sister (but it wasn't on the clinical list when they were first run).

Case 18172-1, rerun 2021-11-03. This is the sister of 18172-2. The same variant is present (https://scout.scilifelab.se/cust003/18172-1/077a24ba8989348e84c928b62b5ddb83) but the local observation count is N/A.

It's obviously not a big problem, I'm just reporting it.

**Comment by ielvers** [comment]
Umm, edit. I opened the whole list of variants and then went back to the variant of interest and now local observations count is present. I wish I had taken a screen shot.

**Comment by dnil** [comment]
Thanks, we'll try keep an eye on it. We wanted to change the loqus integration anyway. If it's ok perhaps not until next week though, but do shout if it becomes a big issue!

**Comment by ielvers** [comment]
I came across this again, so I'll paste the screenshots here, but this is really not a problem.
It's case 21286. I added some HPO terms and opened the clinical list. I noticed that the local observation count was missing in one variant. And then when I open the variant page again, the local observation count is loaded. 

I screenshotted the whole thing to prove that it's the same variant but the local observations count is the point :)

The first time I opened a variant:
![image](https://user-images.githubusercontent.com/57791644/141423727-706a7f95-3f14-4b0f-9f71-f76ad4ba853a.png)

Then opening the same variant again:
![image](https://user-images.githubusercontent.com/57791644/141422035-57f1b8cd-5410-43f2-ac11-e92a9f0d78d8.png)

Also, in all variants the archive local observation count (Nr obs. and Nr homo.) seems to be reported as N/A when it's 0.

Again, it's not a problem, just an observation.

**Comment by dnil** [comment]
Thank you @ielvers! It is good timing as well, as we are in the process of moving the loqusdb backend over to the new server farm. We will be switching to using loqusdbapi, which has a nice REST API, rather than the CLI-app, which is rather easily overwhelmed by multiple requests within a short time on the current old server. We'll have a look at the 0 vs N/A as well, and see if we can't do something about it when we are at it!

**Comment by dnil** [comment]
So, two things here:
- [ ] try to differentiate 0 or N/A for archive counts
And locally in Solna
- [ ] migrate to loqusdbapi (or if that is an issue elsewhere, use the loqusdb CLI on a machine with a sufficiently high number of threads/processes ceiling)

**Comment by dnil** [comment]
Tried the original variant posted a few times and managed to get a timeout. We can connect this to an old type of log error message, one that I attribute to too-few-threads-available, but that cannot be directly read from the message really. Looks more like occasional issues connecting to the db (and only one of the hosts at that, like if it had an old config).
```
2021-11-12 12:43:55 clinical-db.scilifelab.se loqusdb.commands.cli[42594] INFO Running loqusdb version 2.5
2021-11-12 12:43:55 clinical-db.scilifelab.se mongo_adapter.client[42594] INFO Connecting to uri:mongodb://None:None@cg-mongo1-prod.scilifelab.se:27019
2021-11-12 12:43:55 clinical-db.scilifelab.se mongo_adapter.client[42594] INFO Connection established
2021-11-12 12:43:55 clinical-db.scilifelab.se mongo_adapter.adapter[42594] INFO Use database loqusdb-rd
2021-11-12 12:43:55 clinical-db.scilifelab.se loqusdb.plugins.mongo.case[42594] INFO Fetch number of cases
2021-11-12 12:43:55 clinical-db.scilifelab.se loqusdb.plugins.mongo.case[42594] INFO Fetch all snv cases
2021-11-12 12:43:55 clinical-db.scilifelab.se loqusdb.commands.view[42594] INFO Print in json format
2021-11-12 12:45:24 clinical-db.scilifelab.se loqusdb.commands.cli[42743] INFO Running loqusdb version 2.5
2021-11-12 12:45:24 clinical-db.scilifelab.se mongo_adapter.client[42743] INFO Connecting to uri:mongodb://None:None@cg-mongo1-prod.scilifelab.se:27019
2021-11-12 12:45:24 clinical-db.scilifelab.se loqusdb.commands.cli[42743] WARNING Seems like mongod is not running
Aborted!
2021-11-12 12:45:24 clinical-db.scilifelab.se scout.server.extensions.loqus_extension[17289] ERROR Error calling Loqusdb - Traceback (most recent call last):
  File "/home/hiseq.clinical/SERVER/apps/scout/git/scout/scout/server/extensions/loqus_extension.py", line 37, in execute_command
    output = subprocess.check_output(cmd, shell=False)
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/home/hiseq.clinical/miniconda/envs/prod/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/home/hiseq.clinical/miniconda/envs/P_loqusdb/bin/loqusdb', '--config', '/home/hiseq.clinical/servers/config/clinical-db.scilifelab.se/loqusdb.yaml', 'variants', '--to-json', '--variant-id', '1_226044629_A_C', '--case-count']' returned non-zero exit status 1. 
```

**Comment by dnil** [comment]
Ok, its a ServerSelectionTimeout in mongo_adapter:
https://github.com/Clinical-Genomics/mongo_adapter/blob/859757073d1e567676f8de08048c83fddec09e9a/mongo_adapter/client.py#L39

**Comment by dnil** [comment]
Increasing the timeout (can be passed as an argument to mongo_adapter.get_client(uri=uri, timeout=20) might then solve this particular issue.

**Comment by northwestwitch** [comment]
Aha! The timeout for the actual request is already set as default to 20 by default, see the code: https://github.com/Clinical-Genomics/scout/blob/a28683fbe3773d3382b9fc85c3d79f0ea4090210/scout/utils/scout_requests.py#L20

Increasing that number could work, but could also slow down many other requests in the software (since they share the same code). What comes to my mind:

- Custom timeout for loqus requests
- Having timeout set as a tuple, with the time to connect to server and the time for the response, check [here]( https://www.kite.com/python/answers/how-to-limit-the-response-time-with-the-requests-module-in-python). In this case if the connection to server fails, perhaps retry for n times, then eventually show a meaningful error on the scout page (even better in the variant count table?)
- ?

**Comment by dnil** [comment]
Yes, and the corresponding one for loqus is in mongo_adapter. See this! https://github.com/Clinical-Genomics/mongo_adapter/pull/3/files
