### ISSUE TITLE
Add clinical significance as an filtering option

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/scout#296]
- [ ] CLNSIG
- [ ] CLNREVSTAT
- [ ] Scout causal variants 
`## INFO=<ID=CLNREVSTAT,Number=.,Type=String,Description="no_assertion - No assertion provided, no_criteria - No assertion criteria provided, single - Criteria provided single submitter, mult - Criteria provided multiple submitters no conflicts, conf - Criteria provided conflicting interpretations, exp - Reviewed by expert panel, guideline - Practice guideline">`

**Comment by moonso** [comment]
Could you elaborate a bit @henrikstranneheim ?

**Comment by henrikstranneheim** [comment]
- It would be great to be able to filter on known pathogenic variants .i.e clinvars CLNSIG (scale of 1-5 i think).

- However, each CLNSIG also comes with a review status (CLNREVSTAT) telling something about the evidence for the CLNSIG actually being correct. That is also something that might be intresting to have as a filtering option. CLNREVSTAT should perhaps also be seen in the summary table for the variant next to CLNSIG.  CLNREVSTAT is recorded in the vcf INFO field as a "|" sep list with the same order as CLNSIG. 

- I think we can skip the comment about Scout causual variants here since they will be handled elsewhere.

**Comment by robinandeer** [comment]
done in #332
