### ISSUE TITLE
SVFilters

### ISSUE THREAD

**Issue by terestahl** [Clinical-Genomics/scout#2971]
Hi,

When using SVFilters to select SV variants would it be possible to:
-add the possibility to mark several chromosomes at the same time? Now one can only select one chromosome 
-add the posibility to filter by the AD: allele depth of the alternate allele (or by allele frequency), both for the normal and for the tumor samples? (filtering for the AD of the reference allele both in the normal and tummor sample can also be useful)

This would be VERY useful 

Thanks

Teresita

**Comment by dnil** [comment]
The latter seems straightforward; I can work on that. I am not entirely convinced this will give you what you wish for, as these are short read SVs and the contents of any single INFO or GT field, like AD, will be very caller and caller version sensitive. It seemed you were loading a somantic Manta SV VCF right now, and Im not up to speed on it so I guess I will just trust you there an make the filter. 😁

**Comment by dnil** [comment]
The prio (mark several chromosomes) would be super easy, if it weren't for the coordinate boxes for cytobands. They kind of want to know what chr you are selecting. Maybe we can work around this, but it will require more thinking. Suggestions are welcome!

**Comment by northwestwitch** [comment]
> The prior item (mark several chromosomes) would be super easy, if it weren't for the coordinate boxes for cytobands. They kind of want to know what chr you are selecting. Maybe we can work around this, but it will require more thinking. Suggestions are welcome!

Could be

**Comment by northwestwitch** [comment]
Sorry I've closed this by mistake. I was going to comment that it would be easy to select one or more chromosomes and omitting coordinates. But I don't know how useful as a filter this would be!

**Comment by dnil** [comment]
Maybe we could initially add coords for multiple chr from the js, or just don't add any if more than one is selected. But it might hit some roadblock later. I will have a look when adding the filter anyway.

**Comment by vwirta** [comment]
> Hi,
> 
> When using SVFilters to select SV variants would it be possible to: -add the possibility to mark several chromosomes at the same time? Now one can only select one chromosome -add the posibility to filter by the AD: allele depth of the alternate allele (or by allele frequency), both for the normal and for the tumor samples? (filtering for the AD of the reference allele both in the normal and tummor sample can also be useful)
> 
> This would be VERY useful
> 
> Thanks
> 
> Teresita

Sorry for not commenting this earlier. The SV callers that will be uploaded in the future are both Manta and Delly. We have also ongoing work to look into additional callers, hence it is exactly like @dnil says: complicated because the different variant callers having different elements in their INFO fields. 
I add @khurrammaqbool to this thread as well because he has the best insights into the SV callers in BALSAMIC
