### ISSUE TITLE
Missing SV variants from loqusdbapi from scout calls?

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#2977]
```
curl -X GET "http://localhost:7079/svs/?chrom=17&end_chrom=17&pos=44287865&end=44287937&sv_type=INS" -H "accept: application/json"
{"chrom":"17","observations":2010,"families":["pumpeddeer","clearamoeba","mintserval","tightdoe","briefmantis","majormuskox","famoushyena","nicepig","keensalmon","divinecow","clearguppy","fleetbison","lightwren","primeasp","awakeyak","wholeseal","usableadder","provenmaggot","epichawk","majorraven","deepseal","restedcrab","hardygoblin","livingpup","stablecondor","topghost","lightoriole","tightcicada","caringhound","solidbadger","pickedjennet","frankghoul","funnyghost","neatkodiak","solidbeagle","goldenweevil","nextiguana","eagertetra","quickgopher","fluentsnake","pickedglider","acedragon","politecondor","guidedmako","mintlizard","smoothhawk","trueroughy","holyvervet","minthermit","cleancow"],"total":5328,"end_chrom":"17","end_left":44287937,"end_right":44287937,"sv_type":"INS","length":72,"pos_left":44287865,"pos_right":44287865}
```
but 
![Screenshot 2021-11-12 at 11 45 19](https://user-images.githubusercontent.com/758570/141454634-677da3ea-08e0-43e6-b1c3-05e6ced03b55.png)

And switching to cli, while unreliably, does slowly return:
![Screenshot 2021-11-12 at 11 47 06](https://user-images.githubusercontent.com/758570/141454843-5fd28bf8-badb-4b60-b758-c28b588ba6b0.png)

**Comment by northwestwitch** [comment]
Nice, you nailed a good example!

**Comment by northwestwitch** [comment]
While not fixing the original issue (the query is slow), increasing the query timeout in Scout could actually solve the problem in this software

**Comment by dnil** [comment]
Well, none of these in particular actually register as Slow on the mongo logs, but I suppose there is slow and Slow. It seems absolute for the sv via loqusdb, but mostly ok and only a little erratic for the cli. Actually the stage-rd-api ("default") one now also malfunctions?

**Comment by northwestwitch** [comment]
This looks more and more a mongodb timeout issue. Testing again the connection using the replica set in Scout and increasing the timeout allocated for the connection to MongoDB from 20 to 30 (serverSelectionTimeoutMS) helps and prevents the following error, which I think is the same we are viewing in loqusdb:
`
Database connection error:No replica set members match selector "Primary()", Timeout: 0.02s, Topology Description: <TopologyDescription id: 618e6024c27f8daf89f08c36, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('127.0.0.1', 27011) server_type: Unknown, rtt: None>, <ServerDescription ('127.0.0.1', 27012) server_type: RSSecondary, rtt: 0.011778776999999963>, <ServerDescription ('127.0.0.1', 27013) server_type: Unknown, rtt: None>]>`
