### ISSUE TITLE
suggesion: error message if we try to look for a gene that is not present

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#298]
Can we get an error message, insted of not vairant uploaded, if we type a gen symbol that is not in any Scout list?
This to distinguish between no vatiants in the gene, and typing error or version naming error?

Issue discussed with Robin at the SCout workshop :)

**Comment by robinandeer** [comment]
We need to discuss how to do this @moonso 

Perhaps only do it if there are 0 variants returned from a query.. But that doesn't always answer the question. We really need a list of genes to compare with

**Comment by robinandeer** [comment]
We could use flasks `flash` system and just log some messages? :)

**Comment by 4WGH** [comment]
how it is going with this issue? this is connected to the problem with alias :) and HGNC symbol changing with time

**Comment by robinandeer** [comment]
Indeed, a good start would be to have a list of HGNC ids to compare with but like you say these will change over time so we need to keep track of which ids are relevant for each upload in Scout to be sure we are reporting the correct error. It's a more difficult issue than it seems on the outset but we are looking into solutions that would ship with the next update.

One thing that might work is to store all the gene ids when we load the case in Scout and base the comparison from that.

**Comment by moonso** [comment]
Hi,

i'm working on a solution for this and it should be a part of the next release.

**Comment by moonso** [comment]
We keep this discussion to #315
