### ISSUE TITLE
RNA-seq IGV track improvements 

### ISSUE THREAD

**Issue by 19SC** [Clinical-Genomics/scout#2990]
Hi,

We have analysed our cases that already have the option to see the "RNA splicing" in IGV and we would like to ask you for some possible additions.

Is it possible to add to our menu options in IGV of RNA-seq data the possibility to set the minimum junction coverage that will be displayed? 
Is it possible to include the gene track more than just once? We know that we can move the track around but sometimes in families it would be easier to have more gene tracks to compare.

Thank you for all your help.
Sandrina Correia

**Comment by northwestwitch** [comment]
Hi Sandrina, thanks for your feedback, the  RNA Splicing IGV view is quite new and we could use some help from the user to improve it!
Regarding your questions: 
> Is it possible to add to our menu options in IGV of RNA-seq data the possibility to set the minimum junction coverage that will be displayed?

At the moment it's not possible. Looking at the documentation of the software we use for displaying the tracks, [igv.js](https://github.com/igvteam/igv.js/wiki/Splice-Junctions) we could set a default value for the `minTotalReads` parameter, I think that would be an arbitrary number that can't be changed by the user.

>Is it possible to include the gene track more than just once? We know that we can move the track around but sometimes in families it would be easier to have more gene tracks to compare.

This would be relatively easy to do. We could repeat the gene every 2 sample alignments perhaps?

**Comment by 19SC** [comment]
Setting an arbitrary number in this parameter (minTotalReads) won't be very useful for us. We would like to change this value depending on the gene. Maybe in the future it will be possible. Thanks anyway.

Ok, it seems a good solution the repetition of the gene every 2 samples. 

Thank you again :). 
Sandrina

**Comment by northwestwitch** [comment]
I've modified both title and labels of this issue so it's clearer that it's an actionable thing!
