### ISSUE TITLE
Communicate the date when a gene panel was updated last time to melter

### ISSUE THREAD

**Issue by henningonsbring** [Clinical-Genomics/scout#3001]
[melter](https://github.com/Clinical-Genomics/melter) keeps track of cases flagged for perpetual monitoring in scout and starts new analysis of such cases when appropriate. One criteria for redoing an old analysis is if the gene panel has been updated. To make this feature work scout could communicate which date the gene panel was updated last time (and that could then be compared by melter to when the analysis was done the last time).

This issue can be closed when:
- [ ] scout can communicate to melter the date a gene panel was updated last time
or
- [ ] melter can identify if a gene panel has been updated since the last analysis (with another strategy than mentioned above) - please give suggestions if we should close the issue via this option

**Comment by northwestwitch** [comment]
Shouldn't be that difficult, but how, via command line or REST API?

**Comment by henningonsbring** [comment]
I talked to MR, she thinks REST API should be the best

**Comment by dnil** [comment]
Hi, either is fine really - I eyed just adding it to the cli, specifically e.g. `scout export cases` has flags for like `--research-requested` and could work just the same way.

**Comment by dnil** [comment]
Ah, sorry, wrong issue - this would actually be on `scout export panels`, but all the same.

**Comment by dnil** [comment]
😸 Sure, this could be done either way. But as the API structure might change as well, it will be re-wrapped at a point, and very similar cli endpoints exist.
