### ISSUE TITLE
The Codefactor check stopped executing and it's required to merge PRs

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#3005]
![image](https://user-images.githubusercontent.com/28093618/144030716-387d41df-e134-4f16-8024-7cbe950a8e26.png)

**Comment by dnil** [comment]
I think someone renamed the active default branch without changing it on CodeFactor? Hold on, Ill see if Im allowed to change it there..

**Comment by dnil** [comment]
Ok, I think I managed to change it. Its re-reviewing..

**Comment by dnil** [comment]
![Screenshot 2021-11-30 at 12 11 54](https://user-images.githubusercontent.com/758570/144037106-b7607f0b-6dae-48a4-ac92-d4a723941baf.png)
Here we go! Closing.
