### ISSUE TITLE
Clinvar IGV tracks not loading?

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#3038]
We seem to have an outage of ClinVar tracks. Temporary load issue, or did someone block the resource perhaps?
https://hgdownload.soe.ucsc.edu/gbdb/hg19/bbi/clinvar/clinvarMain.bb. Looks ok on the web?
![Screenshot 2021-12-09 at 16 30 06](https://user-images.githubusercontent.com/758570/145425923-33c94913-87e6-4e0d-ae8f-80623cff3053.png)

**Comment by dnil** [comment]
Looks intermittent! Starting to be back now?!

**Comment by northwestwitch** [comment]
Looks OK now

**Comment by dnil** [comment]
Good, probably was the load yesterday evening. They might be throttling access from the same source. We can think about ways to cache without having to do manual updates in the meantime, but let's close this for now until it becomes a pressing issue again.
