### ISSUE TITLE
HELP! CANT PLACE ORDERS... 

### ISSUE THREAD

**Issue by heronikdin** [Clinical-Genomics/scout#3040]
Hej! 

I hope someone can help me, the orderportal keeps asking me to assign new F names for the samples (these are new samples which I have not sent before)! It does not matter how many times I change the F name, it complains every single time ☹ ☹ ☹ ☹ ☹ . It also keeps saying that the sample exists, which it doesnt, I have not put them in before... Why does the orderportal hate me??? Just a moment before this I could place the ticket #251621. 

![image](https://user-images.githubusercontent.com/62098218/145453206-a94d967c-9e8f-4295-98dd-2a0743651451.png)

**Comment by vwirta** [comment]
The order portal does not hate you, it is just checking samples carefully. 
All four cases have been submitted before, ie they are in our systems. 
Let's discuss in further in the support ticketing system. Closing this issue here.
