### ISSUE TITLE
Personal event history

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#3041]
Show (recent) event activity for a user, making it easy to get back to a case/analysis recently done, or remembering that case with that pinned variant in whatever gene.

**Comment by mikaell** [comment]
How would this feature differ from the Activity panel on the case page?

Is it showing all cases activities gathered on the first page?

**Comment by dnil** [comment]
1. It would be a new feature show all activity for any case and variant but only for the active logged in user.
2. That is a very good start. Additional events will appear in due time, but there is no request for new events here.

**Comment by dnil** [comment]
It could be a new view e.g. under the institutes/overview blueprint collection, and be accessed/linked from the user dropdown on the `templates/layout_bs4` `top_nav_right` menu. 

Certain users have a large number of events, so the view would be paginated.

**Comment by dnil** [comment]
The individual user info now displayed on the Users list page would make a nice addition to such a view:

![Screenshot 2022-02-24 at 12 28 42](https://user-images.githubusercontent.com/758570/155515952-cb547056-2101-43b5-95cf-f39654cdb962.png)

**Comment by mikaell** [comment]
I was thinking in the lines of updating the first page the user arrives to. This would contain a table of 15-25 most recent events. Every table entry would be a link to the case. Full user history would be reachable from the more specific user menu.

A quick and dirty html-hack. 
![image](https://user-images.githubusercontent.com/1150065/155521987-6c152570-272f-4864-976b-18ff864c9f02.png)

**Comment by northwestwitch** [comment]
Just an idea, you might consider to include not every type of recent event in this list. For instance I don't think it would be so informative that we show that the user has dismissed 20 variants of a single case. But if we show that the user has assigned a causative for a case, dismissed a bunch of variants for another (as a single event), commented on another case it would be more helpful I think!

**Comment by mikaell** [comment]
This is what I done so far. Is it moving in the right direction?

- [ ] Don't display events of minor importance
- [ ] Nicer presentation (whole row link, no underline?)
- [ ] Things I've forgotten

![image](https://user-images.githubusercontent.com/1150065/157442472-dfa99ceb-a349-4f19-9aab-081c51492b1e.png)

**Comment by northwestwitch** [comment]
Let's analyze the whole list of events that can be diaplayed:

```
VERBS_MAP = {
    "assign": "was assigned to",
    "unassign": "was unassigned from",
    "status": "updated the status for",
    "comment": "commented on";
    "comment_update": "updated a comment for",
    "synopsis": "updated synopsis for",
    "pin": "pinned variant",
    "unpin": "removed pinned variant",
    "sanger": "ordered sanger sequencing for",
    "cancel_sanger": "cancelled sanger order for", 
    "archive": "archived",
    "open_research": "opened research mode for",
    "reset_research": "canceled research mode request for",
    "mark_causative": "marked causative for",
    "unmark_causative": "unmarked causative for",
    "mark_partial_causative": "mark partial causative for",
    "unmark_partial_causative": "unmarked partial causative for",
    "manual_rank": "updated manual rank for",
    "cancer_tier": "updated cancer tier for",
    "add_phenotype": "added HPO term for",
    "remove_phenotype": "removed HPO term for",
    "remove_variants": "removed variants for",
    "add_case": "added case",
    "update_case": "updated case",
    "update_individual": "updated individuals for",
    "check_case": "marked case as",
    "share": "shared case with",
    "unshare": "revoked access for",
    "rerun": "requested rerun of",
    "rerun_monitor": "requested rerun monitoring for",
    "rerun_unmonitor": "disabled rerun monitoring for",
    "validate": "marked validation status for",
    "update_diagnosis": "updated diagnosis for",
    "add_cohort": "updated cohort for",
    "remove_cohort": "removed cohort for",
    "acmg": "updated ACMG classification for",
    "dismiss_variant": "dismissed variant for",
    "reset_dismiss_variant": "reset dismissed variant status for",
    "reset_dismiss_all_variants": "reset all dismissed variants for",
    "mosaic_tags": "updated mosaic tags for",
    "update_default_panels": "updated default panels for",
    "update_clinical_filter_hpo": "updated clinical filter HPO status for",
    "mme_add": "exported to Matchmaker patient",
    "mme_remove": "removed from Matchmaker patient",
    "filter_stash": "stored a filter for",
    "filter_audit": "marked case audited with filter",
    "update_sample": "updated sample data for",
    "update_case_group_ids": "updated case group ids for",
}
```

All these things reflect into events. I would notify these events by case, like:

```
-----------------------------------------------------
Case 1
-----------------------------------------------------
Edited synopsis. Marked 3 variants as causative, unmarked 1 variant as causative. Dismissed 27 variants.


-----------------------------------------------------
Case 2
-----------------------------------------------------
Commented on case. Commented on 2 variants, requested Sanger for one variant. Sent 1 variant to MatchMaker.


-----------------------------------------------------
Case 3
-----------------------------------------------------
Requested rerun for the case
```


A division by case would be super useful I think, because that way you can easily identify all cases you've been working with lately.

Then you could loop thru the list of verbs and assign a counter to the events of a category, so you report them in general. If one is interested they can enter in the case and check the details.

**Comment by mikaell** [comment]
I see what you mean. There will be a whole lot of <strike>aggregating for-loops </strike> recursive functions😎

**Comment by mikaell** [comment]
To implement the suggestion above (which I think is good) I propose we either redefine or update the VERB macro.

Should have an order of priority (float between 0-1) and convert to f-strings. Which I guess needs to be made into a dict or class.

For example:

```
"id": "comment"
 "string": f"commented on {nof_cases} cases"; 
"order": 0.5
```

**Comment by northwestwitch** [comment]
> To implement the suggestion above (which I think is good) I propose we either redefine or update the VERB macro.

The order could be fixed by reshuffling the key/values in the dictionary perhaps? Just an idea, because VERBS_MAP is used all over the place, and modifying it could be painful..

**Comment by mikaell** [comment]
![image](https://user-images.githubusercontent.com/1150065/162911528-9fea9b64-3f3a-48b0-b1a0-ae389e34502b.png)

This is what I've got so far. Works been a bit slow.

I'm now trying to solve the problem to make the written language informative and condensed and att the same time correct. In the example above (by northwestwitch) the sencenteces in the example do not match the VERBS_MAP macro.

`Edited synopsis. Marked 3 variants as causative, unmarked 1 variant as causative. Dismissed 27 variants.`

"synopsis" ➡️ "updated synopsis for"
"mark_causative" ➡️ "marked causative for"
"unmark_causative" ➡️ "unmarked causative for"
"dismiss_variant": ➡️ "dismissed variant for"

My suggestion is to create a parallel grouping of commands-to-sentences. Implemented as a class. This means we can add custom hierarki (not dependent on order in a list), custom compare functions and string functions, etc. The downside is that it will be a parallel, in functionality very similar to existing dict macro. Or is there another way to go about things?

**Comment by dnil** [comment]
It is already an improvement! As long as it works, is not too hard to update when one adds a new event verb, and not just implemented with special cases in running code it's all good. An actual class sounds great, but just converting the VERBS_MAP to a richer dictionary or adding another (ordered) dictionary is acceptable. Or rewrite the VERBS_MAP ones slightly to make them less free text and more stand alone label-ish ? Like substantive form of the verbs:
"synopsis" -> "Synopsis update"
"assign" -> "User assignment"
Then they could go on both kinds of lists somewhat well. Remember you also have the type of event (case, variant) to help making some choices. Feel very free to chat or call and we can discuss!
