### ISSUE TITLE
disease causative transcript not working

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#305]
Hi I can see the Disease associated transcripts window but no transcript coming up,although annotated in bdCMMS database. Looking into this I've noticed that we have annotated the transcript including the version 
exemple. for PGM1 in dbCMMS is "NM_002633.2" while scout use only "NM_002633"

could this be the reason?

Michela

![skarmklipp](https://cloud.githubusercontent.com/assets/12525201/16382142/e0e4b89c-3c7f-11e6-9a43-0256dfabe04d.PNG)

**Comment by moonso** [comment]
We will look into this

**Comment by dnil** [comment]
Is it a freshly (re)run case?

// Daniel

Skickat från min iPhone

**Comment by 4WGH** [comment]
It was a old case. But in the case updated yeasterday it is working in some but not in other.
I attach the exemple of the not working one. 
![16072_dnajc5](https://cloud.githubusercontent.com/assets/12525201/16445411/d938f1da-3de2-11e6-860a-ec78d0caa501.PNG)

**Comment by moonso** [comment]
Hi,

the gene list that was used does not have a disease associated transcript.
It might be that your version is not in production yet.

Måns

**Comment by ingkebil** [comment]
My bad! I'm fixing this now and I'll be pushing it into production this afternoon.

**Comment by ingkebil** [comment]
This has been fixed in the gene list now.
