### ISSUE TITLE
BAM´s

### ISSUE THREAD

**Issue by 47KW** [Clinical-Genomics/scout#3054]
Hello, we would like to get BAM´s for Case https://scout.scilifelab.se/cust002/F0038299.
Or rather, they shoud be made availabkle for Jesper Eisfeldt.
Tack på förhand

**Comment by dnil** [comment]
Hej! Skriv en ticket i Support system så hjälper de till med export till caesar om det var det du menade! @J35P312 bör annars ha tillgång till bam-filerna på hasta (se `/home/proj/production/housekeeper-bundles/choicesole`)?
