### ISSUE TITLE
local variant: homozygote and hemizygote

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#306]
homozygote and hemizygote are not discriminated for genes on the X chromosomes.

Any plan about this?

**Comment by moonso** [comment]
Not sure how to handle this, what did you have in mind?

**Comment by 4WGH** [comment]
ExAc discriminates between homozygotes (female carriers) and hemizygotes (male carriers). this info could be interesting in some cases.

**Comment by moonso** [comment]
This will not be fixed until we update and rerun all samples in loqusdb, since we are not sure when that will happend we need to remove the issue from milestone 1.6 for now.

**Comment by moonso** [comment]
Fixed in new version of loqusdb
