### ISSUE TITLE
Cannot open individual reserach variants in 4 cases although it has been uploaded

### ISSUE THREAD

**Issue by Annwre** [Clinical-Genomics/scout#307]
Fam 115, 15056, 15067 and 15075 WGS data has been uploaded according to email from clinical genomics, and although the research variant list can be opened, I cant access the individual variants to look at them. When I try to open a variant I get the massage that there is a server problem. Thanks for some help with this, 
Kind regards
Anna Wredenberg 
CMMS

**Comment by henrikstranneheim** [comment]
I can access the research variants for these cases 115, 15056, 15067. 15075 has not been opened yet. @robinandeer Maybe the problem has been solved?

**Comment by robinandeer** [comment]
Most likely the case, I'm sorry for not getting back to this

I'll close it now as solve - please return if the issue reappears
