### ISSUE TITLE
Exporting filtered variants in Scout - "Filter and export" function

### ISSUE THREAD

**Issue by fulyataylan** [Clinical-Genomics/scout#3099]
Hi Scout team!
We want to share filtered variants of unsolved cases with other members in UDNI. Scout's "filter and export" function is very suitable to get a list of filtered variants. However, the exported .csv file would be even better if it has columns for CADD scores, zygosity, gnomAD MAF, and GERP score in addition to the existing columns. Hope this is a doable request. 

Many thanks for taking this request into consideration.

Kind regards,
Fulya

**Comment by northwestwitch** [comment]
Good suggestion! I believe it won't be that complicated to fix!

**Comment by dnil** [comment]
We'll fix, but better practice would be sharing with MatchMaker or Beacon! @northwestwitch has already made a super nice MatchMaker protocol server, patientMatcher. Still sees much less use than warranted via Scout, but it is increasing!

![Screenshot 2022-01-20 at 10 38 36](https://user-images.githubusercontent.com/758570/150313114-5be459f9-5d63-4e57-ac78-87ec85c71f16.png)
