### ISSUE TITLE
Installation fail

### ISSUE THREAD

**Issue by martiliasf** [Clinical-Genomics/scout#310]
Tried to install following the instructions in the Readme. I'm on Ubuntu 16. 

Collecting loqusdb>=0.1.2 (from scout-browser==1.5.1)
  Downloading loqusdb-0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-h8ja2q/loqusdb/setup.py", line 55, in <module>
        install_requires=parse_reqs(),
      File "/tmp/pip-build-h8ja2q/loqusdb/setup.py", line 20, in parse_reqs
        with codecs.open(req_path, 'r') as handle:
      File "/usr/lib/python2.7/codecs.py", line 896, in open
        file = __builtin__.open(filename, mode, buffering)
    IOError: [Errno 2] No such file or directory: u'./requirements.txt'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-h8ja2q/loqusdb/

**Comment by moonso** [comment]
Hi @martiliasf ,

scout is a tool that we use inhouse and it is tightly connected to what we do, we don't really try to make it installable to anyone. 
We have made a lightversion of scout called [puzzle](https://github.com/robinandeer/puzzle) where support problems like this.
Hope you will find it usable.

Regards,

Måns
