### ISSUE TITLE
PDF "Coverage and QC report" from cancer cases doesn't fit the A4 page even in landscape layout

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#3119]
Check [this case](https://scout.scilifelab.se/cust000/NEQAS-somaticWES) suggested by @moahaegglund. 

I've reproduced it locally by:
- Going to the HTML report
- Viewing the source code
- Pasting the code into the "Coverage and QC report" of the demo cancer sample
- Loading this demo cancer sample locally

**Comment by dnil** [comment]
👍 Not even close anymore. Can we demand like a fit-to-page export, or change the font (size) post html generation? Otw in Balsamic, possibly even split the tables into more rows there.

**Comment by northwestwitch** [comment]
I'm working on exporting the files using PDFkit instead of weasyprint. If it works we could swap these libraries and be rid of weasyprint!
