### ISSUE TITLE
Removal of institute cust144 that should not have been created 

### ISSUE THREAD

**Issue by Vince-janv** [Clinical-Genomics/scout#3140]
Upon the creation of the new customer, cust144, he stated that they needed access to scout. The necessary forms were filled out and a scout institute was created. It was then discovered that the customer did not need a scout institute since they would only request fastq files.

Hence the institute cust144 (KS / KMP / CRC) needs to be removed, which cannot be done via the CLI. 

Please remove this institute.

Thanks!

**Comment by dnil** [comment]
Ok, fixed.
Before:
![Screenshot 2022-02-08 at 09 58 30](https://user-images.githubusercontent.com/758570/152952941-d0cc1bb2-8c2b-4e21-bc5f-3463af5497fa.png)
After:
![Screenshot 2022-02-08 at 09 59 20](https://user-images.githubusercontent.com/758570/152952932-3a14e0e9-4d49-4be0-80aa-f253c3c91569.png)

If this happens a few more times, let's make an issue to add some form of remove institute to the cli. It could get a bit complicated if the institute has been in use for some time, has cases, users, panels and so on, so perhaps a retire functionality would be better, as for the panels.

**Comment by Vince-janv** [comment]
Thanks! Perhaps a remove function for "empty" institutes ie. just created, would be useful, and a retire function for institutes that have actually been used.

**Comment by northwestwitch** [comment]
> and a retire function for institutes that have actually been used.

This is a bit tricky because if institutes have been used, they might have associated users, cases and variants, so you'd need to remove all these things otherwise there is some serious bug potential!
