### ISSUE TITLE
HGNC alias

### ISSUE THREAD

**Issue by ingkebil** [Clinical-Genomics/scout#315]
When updating a gene lists, I now silently update an HGNC_symbol to the latest version. I do however append the previously used symbol to a column called 'Alias'. All symbols there are separated by a comma.

@henrikstranneheim : Am I using the right separator in the gene list?
@robinandeer : it would be nice to give a clinician the opportunity to search on alias as well as official HGNC symbol.

**Comment by robinandeer** [comment]
we can discuss how that would work. Maybe we only need to load it once into Scout database. Otherwise we'd like to keep the loading of every case as simple as possible.

**Comment by henrikstranneheim** [comment]
Comma sounds correct!

**Comment by moonso** [comment]
I will solve this in [phizz](https://github.com/moonso/phizz), there will be a table like
alias| hgnc_id
---- | --------
alias1 | hgncid_1
alias2 | hgncid_1

**Comment by moonso** [comment]
Changed my mind, we should do like @robinandeer suggests for now. phizz are under complete rework and will take some time to finish
