### ISSUE TITLE
"Share case" icon doesn't show on case side bar unless you click on it

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#3150]
When case page loads:

![image](https://user-images.githubusercontent.com/28093618/153139262-d0136336-84c0-46d8-80ec-ad5b246dc47c.png)

When you click on it:

![image](https://user-images.githubusercontent.com/28093618/153139374-f688e0ae-2e39-4632-9682-3bc9c3216bd5.png)

**Comment by mikaell** [comment]
At the same time I suggest removing one of the redundant arrows indicating that the view is expandable.
![Screenshot 2022-03-04 at 14 18 53](https://user-images.githubusercontent.com/1150065/156771834-4a929d89-81b2-4edb-8439-0e2046638014.png)

**Comment by northwestwitch** [comment]
Fixed by #3507
