### ISSUE TITLE
Text in pdf conversion page breaks can look funny...

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#3156]
F0032464-DSD_2022-02-10_scout_report.pdf

look into commented variants. the first one look like a SV but is not. it is a SNV  in DMRT1, see below 
https://scout.scilifelab.se/cust002/F0032464-DSD/variants

pleae look alsos into page change where the text is splittesd in 2 pages ....

**Comment by dnil** [comment]
No worries, all good! I hadn't seen those page break things before. Let's keep it open for now and see if there is something simple we can do.

**Comment by 4WGH** [comment]
and the cytoband infor in the SNV variant has confused me

**Comment by northwestwitch** [comment]
It's not yet in production (next week probably with a new release probably), but we have introduced a change in the case PDF export to make the content of the pages a bit smaller (zoom 0.7 %). This will perhaps fix this issue?

**Comment by dnil** [comment]
It might actually! I tried it on the dev server now, and it is at the very least harder to reproduce. 

Current main has this kind of things:
![Screenshot 2022-02-11 at 10 26 12](https://user-images.githubusercontent.com/758570/153567892-6e8af27c-1622-4af2-9f62-ede9b66d1211.png)
This one isn't so bad, but sometimes the split would obscure the text. If I have to guess, without trying to understand PDFKit, the margins do even more than the zoom; when text is just a few pixels misplaced there there is room for it? 🤷 

Let's actually close this for now and revisit it if it happens again with the next release.
