### ISSUE TITLE
cancer variantS filter load filter does not show all values with WTForms>3

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#3162]
Seems some values, like tumor af is not recovered visibly into the form?

**Comment by northwestwitch** [comment]
In which browser did you observe this? I can't reproduce locally with chrome or safari

**Comment by dnil** [comment]
I saw it over the shoulder on Chrome on Win. Could also not reproduce locally or on stage with current versions on chrome or safari on Mac. Will give it a little more time now to see if I can't find it.

**Comment by dnil** [comment]
Hm, I have found something at least, but I dont yet understand it.
![Screenshot 2022-02-15 at 08 16 21](https://user-images.githubusercontent.com/758570/154012110-f1ece7bd-fb7a-4cf8-baa1-dfa5c4ff92c5.png)

But loading the filters doesn't set the form properly:
![Screenshot 2022-02-15 at 08 31 40](https://user-images.githubusercontent.com/758570/154013716-a145aba3-ecd3-4dc4-925b-15bd68b6207d.png)

Notice commas in the numbers instead of decimal points. I am not able to make that happen through the current interface, as form validation flags a "Enter a valid number". This contrasts to my local, where I can enter, save and load both decimal comma and point numbers freely. Perhaps something is off with that form validator?

**Comment by dnil** [comment]
Ah, I think I have also found the difference in behaviour to my local. The rendering of "BetterDecimalField" seems to have changed with some library version. 
Stage:
![Screenshot 2022-02-15 at 08 44 56](https://user-images.githubusercontent.com/758570/154015960-7505cc29-76ba-4bd5-b462-9e42c923b54b.png)
Local:
![Screenshot 2022-02-15 at 08 44 45](https://user-images.githubusercontent.com/758570/154015964-72a00d1c-8e4d-4578-9f7d-da8b939ab0a7.png)

**Comment by dnil** [comment]
Yep, "updating" to WTForms 3 I can now reproduce the issue locally.
![Screenshot 2022-02-15 at 08 49 08](https://user-images.githubusercontent.com/758570/154016566-ebf132c2-0fba-436c-bb90-1b8fcd46108c.png)

**Comment by northwestwitch** [comment]
This could be an issue also in other forms!

**Comment by dnil** [comment]
Yes indeed!

**Comment by northwestwitch** [comment]
Freeze? 🤔

**Comment by dnil** [comment]
That would give some time to understand it better: I was starting to read up, but it is a jungle of `Babel`, `use_locale` and format coercion..

**Comment by northwestwitch** [comment]
> That would give some time to understand it better: I was starting to read up, but it is a jungle of `Babel`, `use_locale` and format coercion..

Yes, looks like we need the time to do some digging, by looking at the changelog after the release of v3.0 it looks like there are quite a number of dangerous changes

**Comment by dnil** [comment]
Ok! I just noticed BetterDecimalField is "our" own homegrown that does in part to the old Decimal field what the new Decimal field does. I could probably fix that then, but if there is more stuff..

**Comment by northwestwitch** [comment]
> Ok! I just noticed BetterDecimalField is "our" own homegrown that does in part to the old Decimal field what the new Decimal field does. I could probably fix that then, but if there is more stuff..

Yes. I think we should freeze and take care of all possibilities when we have a bit more time

**Comment by dnil** [comment]
Ill make a PR, but leave this PR open since it still needs fixing at some point.

**Comment by dnil** [comment]
With the 🥶 this is no longer a bug, but an enhancement that will turn into a bug when we have/want to unfreeze.

**Comment by dnil** [comment]
Fixed by #4127!
