### ISSUE TITLE
Some(?) genes not uploaded if no phenotype in OMIM

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#3181]
We noticed during panel upload of MitoCarta that four genes were missing from the Scout db. They share the distinction of being present in HGNC since quite some time (and in an archive `hgnc.txt` I happened to have since a few updates back), in OMIM (present in `genemap2.txt`), but lacking a phenotype, so NOT in e.g. `genes_to_penotype.txt`or `phenotype_to_genes.txt` or `mim2genes.txt`. Perhaps we take a shortcut too much somewhere, assuming genes present in OMIM are also in one or more of those?

Gene symbols to test with: PIGBOS1, HTD2, PLSCR3 and SELENOO.

**Comment by northwestwitch** [comment]
Now that I've downloaded the resource files: **ensembl_genes_37.txt** and **ensembl_genes_38.txt** I can see that the 4 genes mentioned in the comment above are present only in the latter.

**Comment by dnil** [comment]
Well observed: that is a likely cause. Perhaps we parse the hgnc.txt and genemap2.txt conditional on Ensembl_genes, and before both builds are loaded?

**Comment by dnil** [comment]
They would still not work for the customer then, so low urgency on the issue after that!

**Comment by northwestwitch** [comment]
> Well observed: that is a likely cause. Perhaps we parse the hgnc.txt and genemap2.txt conditional on Ensembl_genes, and before both builds are loaded?

I think the solution might be a bug in the form that searches for a gene. I'll open a PR with a tentative fix!

**Comment by dnil** [comment]
😁 Yes, that could well be - the direct observations were 1) not loading from panel and 2) missing from genes page.

**Comment by dnil** [comment]
Also 3) missing from a database populated with only 37 genes loaded. Explicitly loading build 38 populates them!
