### ISSUE TITLE
Missing data in local observations - archived - SVs only

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#3197]
For structural variants only:

<img width="463" alt="image" src="https://user-images.githubusercontent.com/28093618/156188692-4127c016-7099-47ab-8f7d-41d3900976a1.png">

**Comment by dnil** [comment]
I think the MIP key changed. Probably quite some time ago; see `clinical_genomics_loqusObs` vs `INFO.Obs`. But I have a felling clinical_genomics_mipOCC also changed into something better. I can also have a look tomorrow.

**Comment by northwestwitch** [comment]
Yeah, it's the MIP key that has changed --> `clinical_genomics_loqusObs`

There is also a `clinical_genomics_loqusFrq` that is parsable now. 

This means that all cases since that change in MIP don't have the old obs frequency 😭

**Comment by northwestwitch** [comment]
Ok we have a bunch of new keys:

```
##INFO=<ID=clinical_genomics_loqusFrq,Number=1,Type=Float,Description="The frequency of the event in the database">
##INFO=<ID=clinical_genomics_loqusObs,Number=1,Type=Integer,Description="The number of occurances of the event in the database">
##INFO=<ID=clinical_genomics_mipAF,Number=1,Type=Float,Description="The frequency of the event in the database">
##INFO=<ID=clinical_genomics_mipOCC,Number=1,Type=Integer,Description="The number of occurances of the event in the database">
```
