### ISSUE TITLE
Aggregate view

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/scout#320]
Per institute

_Basic statistics_
- [x] Nr of cases
- [x] Nr of inactive cases
- [x] Nr of active cases
- [x] Nr of solved cases
- [x] Nr of archived cases
- [x] Nr of WES
- [x] Nr of WGS
- [x] Nr individuals

_Case Overview_
Number of cases with:
- [x] HPO-terms
- [x] casuative variant(s)
- [x] Sanger Order/confirmed
- [x] Pinned variants
- [x] Cases with cohort

**Comment by robinandeer** [comment]
<img width="640" alt="screen shot 2017-08-31 at 09 37 12" src="https://user-images.githubusercontent.com/1220232/29911898-fe00b8a6-8e2f-11e7-86a1-9b7ceb7c7cab.png">

**Comment by dnil** [comment]
:+1:

**Comment by henrikstranneheim** [comment]
Fantastic!
