### ISSUE TITLE
js code broken on case page

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#3208]
To reproduce, try to fill in OMIM diagnosis or HPO terms for a case. This problem is on current master, not in prod!

**Comment by northwestwitch** [comment]
Example: this case: https://scout-stage.scilifelab.se/cust003/15001

<img width="695" alt="image" src="https://user-images.githubusercontent.com/28093618/156722708-8a27cc30-ba37-44b6-84b8-6f3021577b0a.png">

**Comment by northwestwitch** [comment]
The failing case has the following thing :

`case["individuals"]["chromograph_images"] : { }`

instead of `case["individuals"]["chromograph_images"]:null` # no value

I can reproduce it locally if I remove chromogram key/values at the individual level:

<img width="539" alt="image" src="https://user-images.githubusercontent.com/28093618/156729317-949ddc89-c5b8-474e-bcaa-dd2242f9ef66.png">

<img width="704" alt="image" src="https://user-images.githubusercontent.com/28093618/156729593-2fa5828c-5ecb-418c-bd37-d980b0f9a23a.png">

**Comment by dnil** [comment]
Its a fairly old one - could it be from a test with a different version of load perhaps?

**Comment by northwestwitch** [comment]
Yes, probably. Should we leave it like this or do I fix it?

**Comment by dnil** [comment]
I guess its safest to fix, but perhaps check a few recent case + cancer cases? If all look good we could test through the rest first to judge what needs to be done now?
