### ISSUE TITLE
Navigation bar institutes level slight inconsistency

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#3211]
The most common way to represent the institutes level is taken from the Cases page view:
![Screenshot 2022-03-04 at 09 49 45](https://user-images.githubusercontent.com/758570/156730666-8ae7088d-1fa5-4b38-b967-597f2cbc9864.png)
But for e.g. the variantS views we have:
![Screenshot 2022-03-04 at 09 49 49](https://user-images.githubusercontent.com/758570/156730671-f6e249ae-4875-4fcc-9021-3bd9870b98eb.png)

It's not necessarily bad to shrink the nav bar size once travelling out the tree, but there is also no real logic to which pages have which version.

**Comment by northwestwitch** [comment]
I like the second case better

**Comment by dnil** [comment]
Yes! Let’s just add like an extra nav item “Cases” when on the actual caseS page, and use just the institute display name consistently for the nav level.
