### ISSUE TITLE
Search and filter cases by diagnoses (OMIM)

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#3221]
Looks like cases are NOT searchable by OMIM terms:

<img width="497" alt="image" src="https://user-images.githubusercontent.com/28093618/156994334-ee44f336-5d3b-44ba-8cbd-ef6b287f9dcd.png">

**Comment by northwestwitch** [comment]
When touching this code, fix also this, by adding "cancer" or "rare" as suggestions

<img width="319" alt="image" src="https://user-images.githubusercontent.com/28093618/156994586-2008a724-1bc6-4ceb-8d66-9163e84a317d.png">

**Comment by northwestwitch** [comment]
Do we want to include this in the new release @dnil ?

**Comment by dnil** [comment]
It would fit, and be rather quick to do. Bug fix wise, we have that chanjo-report fix to get out with some kind of urgency, but it does not seem to affect a large number of cases.
