### ISSUE TITLE
Fix MARRVEL link

### ISSUE THREAD

**Issue by ehre** [Clinical-Genomics/scout#3236]
The current MARRVEL link on the SNV/INDEL variant page doesn't work on genome build GRCh38, since it sends genomic coordinates that MARRVEL interprets as GRCh37. It seems a fix could be to instead send cDNA coordinates, e.g., http://marrvel.org/human/variant/NM_012160.3:c.541A>G

**Comment by northwestwitch** [comment]
Another way would be doing a liftover before creating the link. We do have a liftover module in Scout that can be used to to it --> https://github.com/Clinical-Genomics/scout/blob/c89cc3c0025ea918d1430dec07ccbcd92326ca0d/scout/utils/ensembl_rest_clients.py#L94

**Comment by ehre** [comment]
Whatever works best, you are the experts!
