### ISSUE TITLE
HPO not working

### ISSUE THREAD

**Issue by NicoleCMMS** [Clinical-Genomics/scout#324]
I can import HPO terms but the search for gene lists is not working.

**Comment by robinandeer** [comment]
I got an error from the service we are using "Phenomizer" that the request timed out. It seems like their service is down at the moment so we can't really do much about that then hope it will be up again soon.

I can send an email to see if they have any idea when the service will be up again.

**Comment by robinandeer** [comment]
quick response, service now working again - thanks @drseb!
