### ISSUE TITLE
Page timeout while trying to load IGV alignments for a cancer case

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#3242]
Example: https://scout.scilifelab.se/cust087/F0044719/cancer/66284704a5de993a9407a0781b9a2965

**Comment by northwestwitch** [comment]
The case in question (stabledrum) has an extremely small cram file (5 Mb):

<img width="762" alt="image" src="https://user-images.githubusercontent.com/28093618/158191195-4e96e67c-8549-485c-ab79-94d4a402b62b.png">

That is probably the reason why igv fails.

Same happens with [another case](https://scout.scilifelab.se/cust087/F0044448-2/cancer/variants?variant_type=clinical), which also has very little reads:

<img width="778" alt="image" src="https://user-images.githubusercontent.com/28093618/158191634-3d8ae2a9-15ac-49da-b399-bfbd5ee5a929.png">

Perhaps there is a way to handle these situations instead of having the page to crash!

**Comment by moahaegglund** [comment]
Actually it's the wrong cram file that is uploaded for this case. It should not be the file `tumor_umi_consensusfiltered.merged.cram` but the file named `tumor.merged.cram`, which is a much larger file. This has affected 8 cases today and will be corrected.

**Comment by northwestwitch** [comment]
The reupload using the tumor.merged.cram works, checked the link to the variant above. Closing!
