### ISSUE TITLE
Codecov main cov missing 

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#3248]
Refresh needed after patch, or perhaps there was a typo in the config?

![Screenshot 2022-03-18 at 08 58 01](https://user-images.githubusercontent.com/758570/158960040-5dbe4f83-c803-461e-a9e9-a0203c6a2270.png)

**Comment by northwestwitch** [comment]
I don't get it, main branch was updated 20 mins ago when I merged the other PR:

<img width="430" alt="image" src="https://user-images.githubusercontent.com/28093618/158962140-0d6134b5-60e1-49ca-a435-5443bcb9878b.png">

**Comment by dnil** [comment]
Looks like the config somehow doesn't point to it? Weirdness! The yaml from main is accepted and loaded, it seems as well.

**Comment by dnil** [comment]
Is it that `status.project.branches`?

**Comment by northwestwitch** [comment]
Ahhhhh I think this is the error: https://github.com/Clinical-Genomics/scout/blob/32e304364b37f60a7188959a142fe8f560925ba5/codecov.yaml#L11

**Comment by northwestwitch** [comment]
Docs on flags: https://docs.codecov.com/docs/codecovyml-reference#flags
