### ISSUE TITLE
polyphen 2 not true

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#325]
Hi,
If I remember well polyphen2 prediction should give bakc the wort possible prediction. in this case we have a "benign" prediction in Scout but a "probably damaging" when I run polyphen2 myself.

See 2 files in attachment
![polyphen](https://cloud.githubusercontent.com/assets/12525201/18824817/1804137c-83c5-11e6-9c4e-781aad9e526b.PNG)
![skarmklipp](https://cloud.githubusercontent.com/assets/12525201/18824818/18098f5a-83c5-11e6-88d5-a6c6fc744c2a.PNG)

**Comment by henrikstranneheim** [comment]
The entry comes from VEP using PolyPhen2 v.2.2.2. VEP does not report the subpatch. In the raw data the actual R395G is all encoded benign. Only reason I can see that this would happen is if the subpatch differs between the webtool and VEP.

Sift says deleterious and so does CADD so there is good cause to believe this is damaging to the protein and also for polyPhen to update it's prediction, ;)!

**Comment by 4WGH** [comment]
Hi, I had one more case where the prediction do not fit. Should we consider to update ...VEP or whatever can be updated if possible?
