### ISSUE TITLE
Found a possible security concern

### ISSUE THREAD

**Issue by JamieSlome** [Clinical-Genomics/scout#3250]
Hey there!

I belong to an open source security research community, and a member (@porcupineyhairs) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by northwestwitch** [comment]
Hi and thanks! I've created a [PR](#3251 ) with a security policy page.
You can contact either me (first email in that) or @dnil (second email). Do you have any link where we could check the report that raised the security issue?

**Comment by JamieSlome** [comment]
@northwestwitch - thanks for the response 👍 

You can find the report here:
https://huntr.dev/bounties/7acac778-5ba4-4f02-99e2-e4e17a81e600/

It is private and only accessible to maintainers with repository write permissions!

**Comment by northwestwitch** [comment]
I'll work on a fix for this if you haven't started yet @dnil!

**Comment by JamieSlome** [comment]
@northwestwitch - thanks for the support on this. If possible, could you kindly update the status of the report?
