### ISSUE TITLE
Provide a simple explanation for the spliceAI numbers

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#3256]
For instance what a suspicious value is?

**Comment by dnil** [comment]
All on the [SpliceAI page](https://github.com/Illumina/SpliceAI): "Delta score of a variant, defined as the maximum of (DS_AG, DS_AL, DS_DG, DS_DL), ranges from 0 to 1 and can be interpreted as the probability of the variant being splice-altering. In the paper, a detailed characterization is provided for 0.2 (high recall), 0.5 (recommended), and 0.8 (high precision) cutoffs. Delta position conveys information about the location where splicing changes relative to the variant position (positive values are downstream of the variant, negative values are upstream)."
