### ISSUE TITLE
Add cDNA and protein changes to institute causatives page

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#3259]
Important for cancer cases!

**Comment by dnil** [comment]
Can probably just directly replace the genomic coordinate for the link out, but otw we could also split the list according to Category, and have slightly different info for the different categories.

**Comment by northwestwitch** [comment]
Question: how do we choose a specific cDNA and protein changes among all the possible options given by the multiple transcripts of a variant?

**Comment by dnil** [comment]
Hi, same representation selection as always - compare pretty print variant for the case page or the selection for the variantS list. If I recall correctly, prioritise 1) HGNC primary 2) MANE clinical select and if none of those available 3) ENSEMBL canonical or whatever VEP selects.
