### ISSUE TITLE
vagrant error

### ISSUE THREAD

**Issue by stolpeo** [Clinical-Genomics/scout#326]
Hello,

I tried to install the latest version of scout. I get an error setting up vagrant, see below:

```
$ vagrant provision
/usr/lib/ruby/vendor_ruby/vagrant/util/which.rb:32: warning: Insecure world writable dir /vol/local/data in PATH, mode 040777
[default] Running provisioner: ansible...
 [WARNING]: It is unneccessary to use '{{' in loops, leave variables in loop
expressions bare.


PLAY [all] ******************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [default]

TASK: [common | update apt cache] ********************************************* 
ok: [default]

TASK: [common | install basic packages] *************************************** 
ok: [default] => (item=build-essential,python-pip,python-dev,git,wget,vim,tmux)

TASK: [Stouts.mongodb | Set up configuration parameters 1/3] ****************** 
ok: [default]

TASK: [Stouts.mongodb | Set up configuration parameters 2/3] ****************** 
ok: [default]

TASK: [Stouts.mongodb | Set up configuration parameters 3/3] ****************** 
ok: [default]

TASK: [Stouts.mongodb | include_vars {{ansible_distribution}}.yml] ************ 
ok: [default]

TASK: [Stouts.mongodb | Obtain repository config] ***************************** 
ok: [default]

TASK: [Stouts.mongodb | Add APT key] ****************************************** 
failed: [default] => {"failed": true, "item": ""}
msg: unsupported parameter for module: keyserver

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/stolpeo/playbook.retry

default                    : ok=8    changed=0    unreachable=0    failed=1   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

When I grep for 'keyserver' get this entry:

```
$ less provision/roles/Stouts.mongodb/tasks/install.deb.yml
[...]
- name: Add APT key 
  apt_key: keyserver=keyserver.ubuntu.com id=EA312927
[...]
```

I'm a bit puzzled what is going wrong, the entry seems OK to me but I don't know why it thinks keyserver is a key.

Please tell me if this issue should rather go to ansible.

**Comment by smiller171** [comment]
The issue is with an external role here: https://github.com/andperez/Stouts.mongodb

**Comment by smiller171** [comment]
can you check your ansible version?

**Comment by moonso** [comment]
Hi,

we know that it is very difficult to set up scout in another environment than our local one.
Because of that we have developed [puzzle](https://github.com/robinandeer/puzzle).

It is a lightweight version of scout.
Good luck!

Måns

**Comment by stolpeo** [comment]
Hello, thanks for your replies. My ansible version:

```
$ ansible --version
ansible 1.5.4
```

I will have a look at puzzle. Does it lose a lot of functionality compared to scout?

**Comment by smiller171** [comment]
@stolpeo Your problem is that you are running an extremely old version of Ansible that did not support the `keyserver` parameter in the `apt_key` module. Update Ansible and you should be fine.

This issue should be closed.

**Comment by robinandeer** [comment]
thanks for testing it out!

I've actually moved away largely from setting up dev envs with Vagrant so we will be removing the old and non-up-to-date Vagranfile from the repo

we are working on making Scout easier to install and test out tho so keep an eye out and we'll update the README with clearer instructions to do so soon!
