### ISSUE TITLE
Transcript info on IGV.js refSeq gene track...

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#3280]
The current bed track we use does not seem to provide transcript info. Users request transcript info on click/hover as in default on IGV.

**Comment by dnil** [comment]
Not quite, the info requested in part 1 exon numbers on gene track was solved in IGV.js later, part 2 clinvar ids on clinvar was already there, and part 3 cantering was to be revisited after the update that included 1. We can either test around a bit with that now, and if it looks good simply close that issue and await new examples. 😊

**Comment by northwestwitch** [comment]
> We can either test around a bit with that now, and if it looks good simply close that issue and await new examples

Agreed!

**Comment by dnil** [comment]
Fixed in #3281.
