### ISSUE TITLE
Chromograph new legend link doesn't reach cytogenomics section within cases

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#3284]
If you click on the link:

<img width="461" alt="image" src="https://user-images.githubusercontent.com/28093618/160761619-58052c60-6637-4707-9dec-ec6df14cd941.png">

If only reaches the top of the documentation page, and not the cytogenomics subsection, test:

https://clinical-genomics.github.io/scout/user-guide/cases/#Cytogenomics

**Comment by northwestwitch** [comment]
Ah but wait, it's probably because the updated docs are not deployed yet!

**Comment by northwestwitch** [comment]
Closing!

**Comment by dnil** [comment]
Yes, I was thinking of testing with a local docs link, but worst case its not too far off and can be updated with the next release.

**Comment by northwestwitch** [comment]
I've tested with a markdown preview, as a link from the same page. Should be fine!
