### ISSUE TITLE
Parse REVEL_score, prioritise its display over REVEL_rankscore

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#3287]
Compare https://github.com/Clinical-Genomics/MIP/issues/1981. We should not display more than one REVEL score value, but indicate with a link/marker/text what kind of value it is. If available, it is assumed the user would rather see the `REVEL_score`, but for old cases, `REVEL_rankscore` is a decent fallback if noted as such. 

For an interim period, we may be scoring with `REVEL_rankscore`, but displaying `REVEL_score`, which should be fine.

**Comment by dnil** [comment]
Its really borderline between bug and enhancement, but since the label says 'REVEL score' and links to docs that have no mention of the rankscore, but all the more about the score, it is a little misleading as it is.

**Comment by northwestwitch** [comment]
How urgent is this, should it be added to the upcoming release?

**Comment by dnil** [comment]
Nah, it can wait - we have some really good and semi-urgent stuff pending as well so there will be at least one chance to add it like next week as well.
