### ISSUE TITLE
Variant frequencies not populated in general report

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#3290]
Here is another one to add to your favourite endpoint @northwestwitch!

Frequencies appear missing on general report,
![Screenshot 2022-04-01 at 09 12 21](https://user-images.githubusercontent.com/758570/161214028-32975931-5db3-49fa-8147-da4c59f8ad57.png)

but seen on variant page.
![Screenshot 2022-04-01 at 09 13 10](https://user-images.githubusercontent.com/758570/161214044-0b97cebc-58e6-4b64-8867-d907e3b74d2f.png)

**Comment by northwestwitch** [comment]
And this one as well?
