### ISSUE TITLE
SV callers not populated on general case report

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#3291]
SV callers are not populated either:
![Screenshot 2022-04-01 at 09 19 00](https://user-images.githubusercontent.com/758570/161215172-5ff2e4a5-7350-4834-83b7-d5f9baa696c1.png)

And honestly we should probably do something similar as for the genes with the panels. When multiple genes are on, the panel number grows quickly as well, and single column isn't nice for that:

![Screenshot 2022-04-01 at 09 18 45](https://user-images.githubusercontent.com/758570/161215111-b9c8e714-410c-4c90-b8f5-e1b4da4f9aba.png)

All is well on the variant page(s):
![Screenshot 2022-04-01 at 09 23 06](https://user-images.githubusercontent.com/758570/161215292-87376342-b72a-4772-aef1-8182644bdd82.png)

Examples are from https://scout-stage.scilifelab.se/cust002/F0042222/case_report.

**Comment by northwestwitch** [comment]
Could it be that the callers is another pf these params that we should add i[n the constants](https://github.com/Clinical-Genomics/scout/blob/47604bde0117d4ea9baa2aa31aa8d1eb3ef7a927/scout/constants/variant_tags.py#L1) ??

**Comment by dnil** [comment]
It seems very very likely! :)

**Comment by northwestwitch** [comment]
> It seems very very likely! :)

Oh god how much I hate that code!

**Comment by dnil** [comment]
Lets just change it then! But maybe next release.. 😅

**Comment by northwestwitch** [comment]
@dnil if you already started on the other PR, why don't you fix both issues? It's basically the same problem! If don't have time I can do it instead
