### ISSUE TITLE
Analyze Scout repo on SonarCloud

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#3313]
Would be nice to improve code checks, especially those related to security. We need an organization admin to add the repo on SonarCloud first: https://sonarcloud.io/organizations/clinical-genomics/projects

**Comment by northwestwitch** [comment]
@henrikstranneheim you are an admin for CG GitHub repos on SonarCloud. When you have time, could you add this one as well? Tnx!

**Comment by henrikstranneheim** [comment]
## Added

<img width="1402" alt="Screenshot 2022-05-06 at 10 27 48" src="https://user-images.githubusercontent.com/584738/167095809-231cbc81-78e8-4f7e-9bcb-86ca340d7456.png">

**Comment by dnil** [comment]
Thanks @henrikstranneheim!

**Comment by henrikstranneheim** [comment]
NP! 😄
