### ISSUE TITLE
Audit filter log on report without loading the filter

### ISSUE THREAD

**Issue by christacosta** [Clinical-Genomics/scout#3317]
"Audit filter" : Name, date and user name show up on the report even if the filter was not loaded! I can select a filter, then click "audit filter" and it will show up on the general report. Canit be changed so that this will only happen if I have actually loaded the filter? Alternatively that clicking the audit filter button will also load the actual filter?

**Comment by dnil** [comment]
Perhaps. The first sounds a bit difficult to do, the second could probably be done. But why? I mean, you could write the comment that you did it as well without having done it?

**Comment by dnil** [comment]
Specifically, at least the way I would work, I would probably have loaded the filter at least a few times, while going through multiple pages of variants and messing up along the way having to search again?

**Comment by christacosta** [comment]
Yes that's exactly the point we discussed today. We would like to start using the audit filter function as a safety step. Currently only one person does the actual analysis steps in Scout and there is a risk to miss e.g. loading a filter (we go through 5 filters for debut AML cases, 3-4 of them often have no variants). It would be great to have this as a garantuee that the filter was checked.

**Comment by dnil** [comment]
Gotcha. We'll look into the latter then; while I dont quite see the safety there, at least it would not hurt to also show the "correct" search result when you hit it!
