### ISSUE TITLE
Server-Side Request Forgery (SSRF) in remote_cors 

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#3325]
We knew it was coming. 
Report is here: https://huntr.dev/bounties/352b39da-0f2e-415a-9793-5480cae8bd27/

I have no idea how to fix this vulnerability yet. Have to read about SSRF!

This could help: https://medium.com/poka-techblog/server-side-request-forgery-ssrf-attacks-part-1-the-basics-a42ba5cc244a

**Comment by dnil** [comment]
Indeed, yes. For now we could presumably add authentication and allow CORS-proxy to only a limited set of URLs instead; listing the primary ones should be pretty quick, but Im not sure they dont have follow ups, like for the CDN thingy.
