### ISSUE TITLE
prediction effect for in frame ins/del 

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#333]
could this be implemented in SCout?  See publication link
This would complement the severity prediciton when  SIFT and polyphen can not 

http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0077940

**Comment by moonso** [comment]
Think that this is a question for @henrikstranneheim if it should be included in MIP

**Comment by moonso** [comment]
Please have a look at that @henrikstranneheim

**Comment by dnil** [comment]
It operates with the at first sight counterintuitive result that changes to repeat stretches *are* likely to affect function. Unless in an unordered part of the protein. Interesting!

**Comment by dnil** [comment]
Fig 3 reconciles the world views: one-aa changes to a e.g. a polyQ is not so likely to be disease-causing, but two much more so.

**Comment by 4WGH** [comment]
question about prediction of in frame deletion come up again. 
something to look into?

**Comment by dnil** [comment]
One version seen operational in Lund; Paul P has a working setup running CADD locally on indels - I'm sure he would help iron out any issues we may run into there. SIFT Indel looks nice enough, but CADD seems like a great place to start.

**Comment by henrikstranneheim** [comment]
Decided to:
- Skip SIFT locally for indels as it is not practical to implement in a production setting and will most likely add less than CADD.
- Added dynamic calculation of CADD for indels. VCF key "CADD" as usual.

**Comment by dnil** [comment]
Ok, if the keys are as for regular SNVs, we simply close this issue! Thank you - this should be helpful! :+1:
