### ISSUE TITLE
Variant IDs in MIP11 no longer rsID

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#3331]
Scout assumes the ID column of VCF contain dbSNP rsID. As of MIP11 this appears to be a short variant ID similar to the Scout variant display ID instead (`chr_pos_ref_alt`). This breaks linkout to dbSNP, and looks a little funny:
![Screenshot 2022-05-06 at 16 38 54](https://user-images.githubusercontent.com/758570/167369779-11e62ba1-9f09-4073-baf0-21954fecc548.png)

Presumably the intention is to populate the `INFO.dbSNP` field with the rsID, so we should likely switch parsing the dbSNP id to that as an alternative if the ID column does not match `/rs.*/` (cosmic not considered). From MIP11 VCF:
```
##INFO=<ID=dbSNP,Number=A,Type=String,Description="dbSNP ID of the variant">
```
but this field does not seem populated. Likely VEP needs another switch as well, @jemten?

**Comment by jemten** [comment]
I'll look into it

**Comment by jemten** [comment]
Right that field is added by hmtnote so the Mitochondrial variants have that annotation 😬. 
GATK used to assign the dbSNP ID to the 4th column but as you noticed deepvariant/glnexus doesn't. We can get VEP to add it to the CSQ field. How does that sound @dnil? Or do you want it to be under it's own key in the INFO field?

**Comment by dnil** [comment]
> Right that field is added by hmtnote so the Mitochondrial variants have that annotation 😬. 

Ah, ok!

> GATK used to assign the dbSNP ID to the 4th column but as you noticed deepvariant/glnexus doesn't. We can get VEP to add it to the CSQ field. How does that sound @dnil? Or do you want it to be under it's own key in the INFO field?

CSQ sounds just fine, thanks!
