### ISSUE TITLE
Scout to alamut link does not work

### ISSUE THREAD

**Issue by Leif-glitch** [Clinical-Genomics/scout#3333]
The scout to alamut link in the variant page is nonfunctional and does not open up anything in alamut. attempted on 3 computers and users. 

the page popup gives the following text that usually contains the variant information. 

{
    "apikey": "NNNNNNNN"
}

**Comment by northwestwitch** [comment]
Thanks for reporting the bug, we'll fix!

**Comment by northwestwitch** [comment]
Ok, perhaps doesn't depend from Scout. Unfortunately I have no access to Alamut (from home or from my office @ CG), but if I click on the button the link seems correct, for instance: `http://localhost:10000/show?request=2:100185364C>T`

Could it be that the Alamut key for your institute has expired? Who's responsible for the Alamut software at the hospital?

**Comment by dnil** [comment]
Rumor has hospital IT made some change or other affecting Alamut last week. Checking to see if I can find out more!

**Comment by dnil** [comment]
Ok, its still a little unclear. Alamut does answer nicely locally, both to `localhost:10000?version` with its version, and with the rather cryptic json `apikey` reply above when asked to `?show` or `?search`. It does the same given a completely random API-key, so chances are the API-key has just expired or changed. A new version of Alamut is rolling out to the hospital, latest tomorrow, so hopefully this is related, and we can get a new key soon. @KickiLagerstedt is on it.

With that we could possibly close this issue, but there were some hints in the documentation an "institution" parameter may now be needed. While it didn't help adding it to the GET request, we may need to add it after the update anyway. I'll leave this open until we know.

**Comment by dnil** [comment]
I was able to install the latest version locally. The interface is a little bit more evolved, and actually gives a 401 back for invalid API keys. (I hope they have a max number of allowed faulty requests... 😉) No luck with the previous API-key, so I'm very much guessing we need a new one.

**Comment by dnil** [comment]
API docs here: https://extranet.interactive-biosoftware.com/Alamut_Visual_Plus_API_2.0.0.html
Seems Institution is still optional, so never mind. I can update the docs link from Scout.

**Comment by northwestwitch** [comment]
Nice with the API, perhaps we could make an attempt to revive #1749

**Comment by dnil** [comment]
Yes, though the locking down of the file serve endpoint made it a little more complicated. I can have a look; if I recall correctly the issue last was that Alamut didn't really understand to make a range query, but tried to dl the whole file. That may very well have changed now.

**Comment by dnil** [comment]
Oki, apparently it was a config issue on the Sofia Genetics side; @KickiLagerstedt contacted them, they responded today that it is now reactivated. Works just fine on my end (tested with the latest Alamut Visual Plus 1.5.1 for good measure).

For reference, upon validation, the somewhat cryptic json reply now changes from `apikey: "NNN"` to the accepted request:
![Screenshot 2022-05-12 at 13 50 25](https://user-images.githubusercontent.com/758570/168069621-6f2c4d03-e1b8-4020-94b3-8dce70fffe8c.png)
