### ISSUE TITLE
Filtering in the SV view - wgs-BALSAMIC

### ISSUE THREAD

**Issue by moahaegglund** [Clinical-Genomics/scout#3347]
Transferring from SuSy, please see ticket 907248 in SuSy for the attachment.

Hi,

We started to analyze the WGS- balsamic samples in Scout (cust110). We need your help with filtering in the SV view. It seems that “Tumor alt AF>” doesn’t work? We would like to get the AF column for normal and tumor and also in the exported csv file. As we get many variants and we need tools to narrow them in different ways it would be great if we could sort them in the columns directly in Scout.

I attached here one example where I filtered SV on chr 1.

Grateful for your help!

Regards,
Aleksandra

**Comment by dnil** [comment]
Thanks, it is common for SV callers (eg Tiddit 😊) based heavily on discordant pairs or split reads not to report firm genotypes (hom/het) for germline or by extension VAF for cancer. Some CNV-callers may give an approximation based on coverage. Do you have a recent case that has wgs balsamic SVs that we can look at and check what is available? Cheers!

**Comment by moahaegglund** [comment]
Case F0039890-2, cust110, is the case that Aleksandra gives an example from, a WGS case analysed this week (before the update of balsamic).

**Comment by dnil** [comment]
Yes this seems to be the reason. Manta, which was the only SV caller VCF loaded to Scout for the case in question does not provide an AF or VAF, only some indicator counts on Paried Reads and Split Reads, that one could perhaps interpret depending on the variant type and some rather advanced statistics.

I'll see if I can't find a case from the new version and check what the status is there!

Regardless, we should perhaps consider some more q&a/training sessions with the pipeline developer, a scout team person and the customer?

**Comment by moahaegglund** [comment]
> Regardless, we should perhaps consider some more q&a/training sessions with the pipeline developer, a scout team person and the customer?

This sounds like a good idea! 

Here is a wgs case analysed with version 9: https://scout-stage.scilifelab.se/cust090/829728fam14

**Comment by dnil** [comment]
I couldn't find any AF or VAF in the joint call file from Balsamic 9.0.1 either (checked `brightcalf`). There are perhaps some fields that could help a little for some of the variants, like `CN`, but this is likely in multiples of germline allele copies, and not really geared for mosaic situations. We must ask the pipeline developers (@ashwini06 or @khurrammaqbool might know?) if there are any other useful guesstimates in there. @J35P312 has been looking at that a bit with TIDDIT, but it is not yet in place afaik.

I think I will close this with that, but feel free to reopen if you have suggestions. 

We anyway have an issue open acknowledging the new callers (https://github.com/Clinical-Genomics/scout/issues/3346) so feel free to ping there as well.

**Comment by dnil** [comment]
Thanks for the stage case as well! It was also `9.0.1` with the same situation as `brightcalf`, so this appears to be state of the art. Closing for now, but useful discussion!
