### ISSUE TITLE
CLNSIG not correctly displayed

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/scout#335]
case 16098: 9_133370368_G_T_clinical in gene ASS1 should have pathogenic entry (CLNSIG=5) according to clinvar and annotated vcf file. However, Scout shows 1: not provided.

**Comment by moonso** [comment]
Old issue, can not find the case in new scout. Do you know anything more about this problem @henrikstranneheim ? 
Anyway I will have another look at the CLNSIG information

**Comment by henrikstranneheim** [comment]
Yes, I thing the CLNSIG field is still malfunctioning sometimes. I will try to dig up an example.

Skickat från min iPhone
