### ISSUE TITLE
Gene panel select for institute settings is broken

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#3351]
![Screenshot 2022-05-23 at 18 12 49](https://user-images.githubusercontent.com/758570/169862438-0f6b2e35-c063-4a61-ab56-9dd2be133337.png)

It does not seem farfetched to start looking at the recently patched sorting routine.

**Comment by northwestwitch** [comment]
Ah. I'll take a look!

**Comment by dnil** [comment]
Hehe, I should have assigned. I meant to fix it while you reviewed the other PR. But thank you!
