### ISSUE TITLE
Case type remains in memory when going back to all cases of an institute

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#3357]
Test: on stage, master branch, go to cust000 and then on one cancer case, if you go back to all cases of cust000, then you only see cancer cases.

**Comment by northwestwitch** [comment]
Aha! Bosssponge doesn't originally belong to cust000 but cust087. And so is the case saved in db:

<img width="242" alt="image" src="https://user-images.githubusercontent.com/28093618/170208839-836b863d-ddab-40ce-bb03-ce9b4c50a680.png">

Cust000 is a collaborator instead, check pic above.

When the link to the institute is created it's probably used case owner, and that's why you are going back to a different institute than cust000. It's technically not a bug, but still a bit strange, right?

**Comment by northwestwitch** [comment]
Let's close it for now, then if some user complains we can think about a fix!

**Comment by dnil** [comment]
> Aha! Bosssponge doesn't originally belong to cust000 but cust087

That makes sense! 

>When the link to the institute is created it's probably used case owner, and that's why you are going back to a different institute than cust000. It's technically not a bug, but still a bit strange, right?

It is also not a full going back to the collaborator institute, more like viewing all cases from that institute for which one has collaborator access. Did you check where the change happens? May not be so easy to keep the original institute after diving deeper to variants and back again?

Perhaps a little conditional on the link back or if possible on the caseS page, reverting to an institute in the users own list that was also on the case? But, I agree with closing until someone needs help with it.
