### ISSUE TITLE
Missing "institution" parameter in ALAMUT visual plus requests

### ISSUE THREAD

**Issue by mhkc** [Clinical-Genomics/scout#3361]
The Alamut visual plus request requires _institution_ parameter to work.

The request URL should look like this according to the API specification.

`http://127.0.0.1:10000/search?institution=XXXXXX&apikey=YYYYYYYY&request=NM_000059.3%3Ac.4563A%3EC`

**Comment by northwestwitch** [comment]
Is it the same ALAMUT software we have at KI @dnil?

**Comment by dnil** [comment]
Hi, is this for a forthcoming version? Current Alamut HTTP API (2.0.0) has institution as optional for search. On our side it works without. Do you have problems connecting? Perhaps ask Sofia Genetics to renew your API-key - we had the issue of it going inactive, even though the regular license was ok.

![Screenshot 2022-05-30 at 09 24 20](https://user-images.githubusercontent.com/758570/170939498-2f3ed6a2-edf9-49d1-a342-c590bc6aadb9.png)

**Comment by dnil** [comment]
> Is it the same ALAMUT software we have at KI @dnil?

The same as at KS at least, though the active version span is somewhat large. I'm on 1.5.1 whereas GMCK-RD was on like 1.2 at least last week.

**Comment by dnil** [comment]
Same http-protocol for that span. The HTTP API 1.0 is for an older version of the program.

**Comment by mhkc** [comment]
Never mind. Its working without the institution parameter. My colleague got it to work after restarting his browser.

Sorry to bother you
