### ISSUE TITLE
HPO term non working properly!!!

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#337]
Hi in fam 16079 we added 3 HPO terms. The gene list generated contains more genes then expected. If I export in eXcell the genes from the HPo web site I get totally 34 unique genes. in the HPO generated list in Scout there are mone then 100! There are genes that do not fit at all with the HPo term introduced (this is how we noticed )
Could you please look into this quite fast? not good to look into genes there is NO reason to look into. Thanks!

**Comment by moonso** [comment]
Hi,

When you are adding 3 HPO terms the tool that we use, [phenomizer](http://compbio.charite.de/phenomizer/), will match those with all known phenotypes, that is MIM phenotypes.
And then we will pick all genes that all those phenotypes are associated with.
If you only add 3 HPO terms it will be quiet hard for phenomizer to fin a relevant phenotype so it will probably find to many phenotypes. This is why you get so many potentially unrelated genes.
We can discuss if the users want another way of generating gene lists from HPO terms in the next user meeting.

Måns

**Comment by 4WGH** [comment]
summary from today meeting:
There will be 2 possibilities:
1. A gene list from HPO-term 
2. A gene list created by HPO-phenomizer.
There will be the possibility to export (as pdf?) the analized gene list for documentation on the LIMS  of the final user.

**Comment by moonso** [comment]
Ok so the gene list generated directly from the HPO terms is now ready.
We will then update what is generated by phenomizer soon and hope that all of this will be much more clear

**Comment by moonso** [comment]
Fixed and discussed in the meeting yesterday
