### ISSUE TITLE
White links on white page are invisible

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#3370]
Variant page:

- [ ] Mappability panel:

<img width="290" alt="image" src="https://user-images.githubusercontent.com/28093618/171388460-ce3a021f-b1e6-4499-b9e4-2ceae860b66c.png">

- [ ] Loqusdb panels:

<img width="386" alt="image" src="https://user-images.githubusercontent.com/28093618/171388592-3629572c-d2f4-4bb2-addb-01cc4d87fb01.png">

**Comment by dnil** [comment]
Hihi, good that one of use uses light mode! 👍🏻
