### ISSUE TITLE
Indels not being opened properly in Alamut Visual Plus

### ISSUE THREAD

**Issue by mhkc** [Clinical-Genomics/scout#3375]
Indels are not being opened properly in Alamut Visual Plus version 1.5.1

Alamut API requires indels to be in HGVS format. As far as I have understood it the format should be.

- INDELs longer than 1 nt, `g.<chromosome start position-chromosome end pos>:[del|ins]`
- INDELs 1 nt long, `g.<chromosome start positions>:[del|ins]`
- In case of INDELs in repeated sequences the start coordinate should be the 3` repetition

If its difficult to extract the coordinates of the 3\` repetition one could open the variant using the Scout HGVS description in RefSeq transcript table and the desired transcript. For instance `<MANE transcript>/<HGVS description>`

**Comment by northwestwitch** [comment]
I can try fixing this, but since I don't have access to Alamut I need some help testing!

**Comment by dnil** [comment]
I thought @mhkc wanted it, but otherwise I can also. If you like, you could start and I can test and fix any ahem unlikely issues remaining?

**Comment by northwestwitch** [comment]
I was looking at the examples in here: looks like the official nomenclature contains also transcript name and version before c.etc-etc

**Comment by dnil** [comment]
True enough - that may be an issue especially on hg19. One alternative is clever use of the hgvs to figure out if the genome coord is good or needs renormalisation, but clever solutions seldom maintain well.

**Comment by Jakob37** [comment]
Hi! Our geneticists came back and asked about this one now when the M/MT is getting fixed (they were really happy about that!). 

Any thoughts on whether this one could be implemented, fully or partially? We can help out with testing.

**Comment by dnil** [comment]
Ahem, this one got a bit hidden below high prio. Let's have a look again. 😊

**Comment by dnil** [comment]
Right, the non-repetitive part looks easy enough, whereas the silly diff in left vs right normalisation between most genomics tools and HGVS is more complicated without resorting to some computation.

**Comment by Jakob37** [comment]
> Ahem, this one got a bit hidden below high prio. Let's have a look again. 😊

No worries ;)

> Right, the non-repetitive part looks easy enough, whereas the silly diff in left vs right normalisation between most genomics tools and HGVS is more complicated without resorting to some computation.

OK I see! Annoying with the normalisation-diff. But if straight-forward, getting the non-repetitive parts fixed would probably help them quite a bit here in Lund!
