### ISSUE TITLE
Old cases not showing alignments?

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#3380]
Seems old cases in Solna are not showing either a proper "no alignment file available" or the alignment files?
Cf e.g. https://scout.scilifelab.se/cust002/F0030513. Or F0025784, note especially the RNA part:
![Screenshot 2022-06-07 at 16 00 36](https://user-images.githubusercontent.com/758570/172399684-9af22666-aac1-467f-ad3c-6fe62b41f64e.png)

**Comment by northwestwitch** [comment]
Could be the list of tracks saved in the session? I'll take a look!

**Comment by dnil** [comment]
More that the check for missing files was a little perturbed when the track-saving was introduced, right? E.g. novelwren has alignment files missing from housekeeper, but an IGV button showing..

**Comment by northwestwitch** [comment]
Ha, it's cases with alignments saved in the database but that have been removed on disk.
