### ISSUE TITLE
Appearance that no variants returned after filter

### ISSUE THREAD

**Issue by leahkemp** [Clinical-Genomics/scout#3381]
Hi all, thanks for the great software!

We've noticed a behaviour in scout whereby if you are a few pages in when looking at variants (ie. not on the first page of variants), and then apply a filter that reduces the number of variants to fewer than is able to fill to the current page, on face value it can appear that no variants were returned.

This behaviour should be reproducible with the demo database provided by scout. For case 643594, looking at "Clincial SNV and INDELs", navigate to page 2 of variants, then apply a filter for CADD score of 20. This returns a page that says "No matching variants" while also saying that "Filter returns 6 / 680 variants". This is remedied by clicking the "First page" button to take you back to the first page of variants where the 6 variants can be viewed. I interpret this to mean I'm still on page 2 after the filter is applied, but there are not enough variants after my filter to fill up 2 pages, hence my page is empty.

![no_variants_returned](https://user-images.githubusercontent.com/46519743/172526834-a67f5109-aa94-4265-886c-f5c680fbef6e.gif)

Although this is workaroundable by simply clicking to the first page, it caused some confusion with our collaborators at the hospital and I'd argue it would be more logical to return to the first page when a new filter is applied. What are your thoughts?

I'm using [scout version 4.53](https://github.com/Clinical-Genomics/scout/tree/v4.53)

Let me know if you require any further information or if I can help with testing :)

Leah

**Comment by northwestwitch** [comment]
Hi Leah, thanks for reporting this bug and the nice instructions to reproduce! I believe it's a relatively easy fix. I'll work on it right away!

**Comment by leahkemp** [comment]
Wicked! No problem :)

**Comment by leahkemp** [comment]
Fantastic, I've given it a whirl and it's working as expected, thanks for the prompt fix :)
