### ISSUE TITLE
Access to cram issue

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#3387]
Ping from one of the users unable to see alignments. SAM (Solna hospital), Chrome browser.

<img width="366" alt="Screenshot 2022-06-09 at 08 32 54" src="https://user-images.githubusercontent.com/758570/172780311-363173ac-5a35-4ba0-9627-364163a765ec.png">

Works on my end, and actually worked with Edge for her as well. Asking for a re-login in Chrome to see...

**Comment by northwestwitch** [comment]
Did it work with a re-login?

**Comment by dnil** [comment]
Yep. She moved between networks on the same session. I'd say that is fine, given the extra security, though it would be nice if all pages behaved the same. With shorter login times no-one will have time to notice. 😅
