### ISSUE TITLE
Find a new symbol to indicate tumor-normal somatic cases in cases list

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#3391]
The duos look a little strange on second thought..

![Screenshot 2022-06-09 at 13 01 19](https://user-images.githubusercontent.com/758570/172832162-fd918e10-1172-44f3-be72-35af80426cae.png)

**Comment by northwestwitch** [comment]
What about these 2? 

<img width="319" alt="image" src="https://user-images.githubusercontent.com/28093618/173010924-2ae8c0e9-6844-42d8-94b8-1a49b246a5fd.png">

 and this:

<img width="372" alt="image" src="https://user-images.githubusercontent.com/28093618/173010977-5c77a2d0-a125-4dd9-a2a2-8b2a1228b673.png">

They're here: https://fontawesome.com/icons/categories/medical-health

**Comment by dnil** [comment]
Good! One could do fa-vials as well, but these are better.

**Comment by northwestwitch** [comment]
Yes, we could also keep it simple and just use vial. I'll draft something

**Comment by northwestwitch** [comment]
I think it's actually better with just a vial, they're too small to see a difference anyway in the page:


<img width="1255" alt="image" src="https://user-images.githubusercontent.com/28093618/173014009-4d69072b-f918-4076-8ac6-3a79473373e0.png">

**Comment by vwirta** [comment]
Looks good with the vials!
