### ISSUE TITLE
All variants in a particular gene

### ISSUE THREAD

**Issue by NicoleCMMS** [Clinical-Genomics/scout#340]
Is it possible for us to get all variants in the gene MED17 loaded into Scout for the family 115?

**Comment by robinandeer** [comment]
@moonso?

**Comment by moonso** [comment]
Yes this will be possible in the new update

**Comment by vwirta** [comment]
is this upload of variants for a specific gene (or list of), or is this for all variants in the exome/genome? @moonso

**Comment by moonso** [comment]
Closed by https://github.com/Clinical-Genomics/scout/commit/fdc82292cd25edb40d6e6945469f76f183942b49

**Comment by moonso** [comment]
This is now possible in the new version of scout
