### ISSUE TITLE
New HPO release --> update Scout database!

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#3401]
A new release of the HPO terms is available: https://github.com/obophenotype/human-phenotype-ontology/releases/tag/v2022-06-11

If we manage to create a new Scout release containing #3396 before the summer we could run a database update (genes, OMIM, HPO, OMIM panel)

**Comment by leahkemp** [comment]
Just flagging something which I'm pretty sure relates to this :)

I encountered the following error (with both scout v4.55 and v4.53) when running the `scout setup database` and `scout update hpo` commands:

```bash
ValueError: invalid literal for int() with base 10: 'part_of'
```

It seems related to the last few entries in the file at https://raw.githubusercontent.com/obophenotype/human-phenotype-ontology/v2022-06-11/hp.obo, which have values for the 'id:' field that aren't in the typical "HP:" format such as. HP:5000048.

Here's a little poke around I did looking at the values for "id:" in the new release of HPO terms compared to previous releases that should be reproducible on linux:

```bash
mkdir -p {v2022-06-11,v2022-04-14,v2022-02-14}

wget https://raw.githubusercontent.com/obophenotype/human-phenotype-ontology/v2022-06-11/hp.obo -P ./v2022-06-11/
wget https://raw.githubusercontent.com/obophenotype/human-phenotype-ontology/v2022-04-14/hp.obo -P ./v2022-04-14/
wget https://raw.githubusercontent.com/obophenotype/human-phenotype-ontology/v2022-02-14/hp.obo -P ./v2022-02-14/
```

```bash
grep "id:" ./v2022-06-11/hp.obo | tail
```

My output:

```bash
id: HP:5000036
id: HP:5000037
id: HP:5000038
id: HP:5000039
id: HP:5000041
id: HP:5000042
id: HP:5000043
id: HP:5000044
id: HP:5000045
id: HP:5000046
id: HP:5000047
id: HP:5000048
id: inheres_in
id: inheres_in_part_of
id: part_of
```

```bash
grep "id:" ./v2022-04-14/hp.obo | tail
```

My output:

```bash
id: HP:5000038
id: HP:5000039
id: HP:5000041
id: HP:5000042
id: HP:5000043
id: HP:5000044
id: HP:5000045
id: HP:5000046
id: HP:5000047
id: HP:5000048
```

```bash
grep "id:" ./v2022-02-14/hp.obo | tail
```

My output:

```bash
id: HP:5000038
id: HP:5000039
id: HP:5000041
id: HP:5000042
id: HP:5000043
id: HP:5000044
id: HP:5000045
id: HP:5000046
id: HP:5000047
id: HP:5000048
```

Looks like there are some new values for ID: "id: inheres_in", "id: inheres_in_part_of" and "id: part_of"

None of these are found when grepping for them in the older releases of this file, for example when running:

```bash
grep "part_of" ./v2022-04-14/hp.obo
grep "part_of" ./v2022-02-14/hp.obo
```

Hope this is useful, I'll have a look at this again in the morning with a fresh brain :)

**Comment by dnil** [comment]
Thank you Leah! We haven’t tried yet on our side, super to know! Anything in their docs that explain how they intend these new terms to work? Or just a mistake?

**Comment by northwestwitch** [comment]
## Update HPO terms:
`scout update hpo --hpoterms scout_downloads/hpo.obo --hpo-to-genes scout_downloads/phenotype_to_genes.txt`

##  Update OMIM terms:
`scout update diseases -f scout_downloads`

## Update genes:
`scout update genes -f scout_downloads`

## Update OMIM panel:
`scout  update omim --institute cust002 --genemap2 scout_downloads/genemap2.txt --mim2genes scout_downloads/mim2genes.txt`
