### ISSUE TITLE
Ordered Sanger disappears after reanalysis

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/scout#341]
It would be great if the Sanger info is persistent

**Comment by moonso** [comment]
This could be tricky but I agree that it should be solved.
It is related to #372 , if we get that to work this might not be a problem 🍶

**Comment by moonso** [comment]
Closed by https://github.com/Clinical-Genomics/scout/commit/de767648e838554277d16ea8c3503cab601a418d
