### ISSUE TITLE
Ahem, visited link color/assignment to certain buttons..

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#3415]
<img width="395" alt="Screenshot 2022-06-14 at 11 49 17" src="https://user-images.githubusercontent.com/758570/173552247-90966570-216e-4f13-b57b-9c599493db81.png">

**Comment by northwestwitch** [comment]
oh no!

**Comment by dnil** [comment]
All a:visited on with class btn-secondary. Perhaps easiest just to pick another visited color, but any solution is welcome!

**Comment by mikaell** [comment]
Tough they are links, you interact with this element as a button. I would suggest not giving it a visited colour at all. This is common in many web interfaces.

**Comment by dnil** [comment]
Exactly, everything that is app-like should not get visited, only things that are hypertext-ish. Like I guess the variantS page to some extent. But not most of the other controls.
