### ISSUE TITLE
"Disease associated transcripts" missing?

### ISSUE THREAD

**Issue by 1ctw** [Clinical-Genomics/scout#3416]
I miss the field for the CMMS "Disease associated transcript" in updated Scout.

![image](https://user-images.githubusercontent.com/15033593/173554905-70b2b118-a3d0-4008-b056-2a416a8270f2.png)

It has been above the field "RefSeq transcripts" earlier.

**Comment by northwestwitch** [comment]
I'll check, thanks for reporting!

**Comment by northwestwitch** [comment]
@1ctw you mean that the "Disease associated transcripts" panel is gone now or that it's missing info?

**Comment by 1ctw** [comment]
The panel is gone, isn´t it? The screen shot above is from an older case but it is missing in new cases.

**Comment by northwestwitch** [comment]
Mmm some cases still have it, check this one for instance: https://scout.scilifelab.se/cust003/22019/df2cb91b2f84ba519c487b0386e6049a

**Comment by 1ctw** [comment]
Now I also see that it is there in some cases. It seem to depend on whether a CMMS panel is selected on the first page of the case or not. Could that be the reason? I get different variant pages, with or without this panel, if I choose the panel on the front page or in the filter...

**Comment by 1ctw** [comment]
I now discussed this with Nicole and she says this is nothing new. I noticed the problem when I was analysing an HPO panel and missed the disease associated transcripts for the genes I know are genes in the IEM panel. I can solve this by choosing panels on the front page even if I let the HPO override it in the analysis. Then this is not a big problem. I guess you can close the issue then. Thanks for checking!

**Comment by northwestwitch** [comment]
> I now discussed this with Nicole and she says this is nothing new. I noticed the problem when I was analysing an HPO panel and missed the disease associated transcripts for the genes I know are genes in the IEM panel. I can solve this by choosing panels on the front page even if I let the HPO override it in the analysis. Then this is not a big problem. I guess you can close the issue then. Thanks for checking!

No problem! I wasn't aware of this and it's always good to know!

**Comment by northwestwitch** [comment]
It's probably because that typo info is added "on the fly" from the selected gene panels when you navigate to a variant page. So yes, the behavior you see makes sense!
