### ISSUE TITLE
Question about variant submitted to CLinVAR

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#3422]
![image](https://user-images.githubusercontent.com/12525201/173631896-da3e0e3b-94a9-4b08-97d0-812edec79706.png)
 Super coll that I can see  the variant has been submittedto CLinVar. This works for variant we submit throug SCout I assume.

If we happen to use the Wizard submisson (no via Scout) how can I label that the variant has been submitted to Clinvar?

**Comment by dnil** [comment]
It will show up as a variant matching to clinvar on new cases once the next update to MIP goes through, so no need during that time. If you need it sooner, just ask the support to update MIP references with a new clinvar download!
