### ISSUE TITLE
Text in login button not visible

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#3424]
Purple text on blue is not very visible:

<img width="230" alt="image" src="https://user-images.githubusercontent.com/28093618/173743395-eba2fead-1e3a-49f6-ab5d-254ca74ed36f.png">

**Comment by mikaell** [comment]
I suggest we should treat these as buttons and not as links. That is, we don't change the color after visit. Problem solved and UX more coherent and modern.

**Comment by northwestwitch** [comment]
The problem is that these links styled as buttons are all over the place and to fix them you have to go in each page and modify the text. And the buttons themselves have no problem (we follow the bootstrap 5 specifics anyway). The problems occurs when in the css we specify that the visited links must have a specific color. I've created a PR with a quick fix. We can revisit with a better solution (either changing the buttons or as @dnil suggested yesterday by applying the link visited color only to some element of the page, like the list of variantS)

**Comment by northwestwitch** [comment]
@mikaell here's the bootstrap docs page: https://getbootstrap.com/docs/5.0/components/buttons/#button-tags

**Comment by dnil** [comment]
Agree in principle, all about a smooth and lazy maintainable implementation. How about adding like a `:not(btn)` to the `a:visited` color CSS?

**Comment by northwestwitch** [comment]
> Agree in principle, all about a smooth and lazy maintainable implementation. How about adding like a `:not(btn)` to the `a:visited` color CSS?

Yes, does it work?

**Comment by northwestwitch** [comment]
> Yes, does it work?

I could try it later in #3425

**Comment by dnil** [comment]
It should, could naturally have some other unforeseen effect. 😆 But let's try it later!

**Comment by northwestwitch** [comment]
Didn't work. https://sonarcloud.io/project/issues?resolved=false&pullRequest=3425&id=Clinical-Genomics_scout&open=AYFmkmnR3LEydSZ3hlK8

I'm going to try something else
