### ISSUE TITLE
Managed / matching causative gene list two-step?

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#3428]
The matching causatives and managed variants lists for a case are a potential concern for users, as they can reveal disease variants not necessarily connected to the referral at hand. They serve a form of safety net not to miss clear known disease variants from differential diagnoses that were overlooked when choosing the gene panel, not well connected via HPO etc.

The variants are currently hidden for the user, until they choose to view it.

We propose to make this process a two step one, where the user first choses that they wish to see variants presented in aggregate according to panel, then again approve to see the genes and variants actually involved.

**Comment by northwestwitch** [comment]
This has been partly addressed in #3611. There is also another issue about this #3600. Should we close one of them (or both?)

**Comment by dnil** [comment]
Lets close this at least: if the users need more on the same track, we can open a new one.
