### ISSUE TITLE
Frequency filter on SVs (local obs)

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#3429]
The filter pages for some variant types (SV, somatic) does not have a local archive AF filter option, even if the pipelines now support it. Let's add it where applicable!

**Comment by dnil** [comment]
Ok, sorry, I got the cancer part wrong. It didn't make it to the current Balsamic release. Still pending; we'll add the filter option when there is data to filter! We can still add a RD SV filter options for CG local, probably replacing e.g. SweGen or the local research NGI collection which are now both considerably smaller.

**Comment by northwestwitch** [comment]
This was fixed in #3479. Closing this issue!
