### ISSUE TITLE
SpliceAI hover..

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#3441]
..gets a silly text split when None:

![Screenshot 2022-06-16 at 10 13 42](https://user-images.githubusercontent.com/758570/174024831-b6f7234d-82d3-442e-b7d6-2afdd27f8744.png)

Hardly urgent though.

**Comment by northwestwitch** [comment]
Oh no!

**Comment by northwestwitch** [comment]
Is that a variant with multiple genes?

**Comment by dnil** [comment]
Yes!

**Comment by northwestwitch** [comment]
I can try to fix it, we can't update the database right now anyway..
