### ISSUE TITLE
Sanger ordered - Bugg???

### ISSUE THREAD

**Issue by KickiLagerstedt** [Clinical-Genomics/scout#3463]
När man beställer Sangersekvenering avseende en variant syns detta inte längre på första sidan. Bugg eller medvetet val???

https://scout.scilifelab.se/cust003/22178

![image](https://user-images.githubusercontent.com/17139607/174809331-e8c4bc08-ef8a-4031-a721-9cfe612b01e1.png)

![image](https://user-images.githubusercontent.com/17139607/174809462-4c3cac63-d668-4ee3-8eaa-2eefc6bbc1d3.png)

**Comment by KickiLagerstedt** [comment]
When ordering Sanger sequencing regarding a variant this is no longer visible on the first page. 

![image](https://user-images.githubusercontent.com/17139607/174810057-59a42816-c93c-4aa7-8768-e064677f225b.png)

**Comment by dnil** [comment]
Switch to the dark side! 😉 No, sorry, we are aware, and its fixed in the dev release, see https://github.com/Clinical-Genomics/scout/issues/3447. But thanks for letting us know!

**Comment by northwestwitch** [comment]
> When ordering Sanger sequencing regarding a variant this is no longer visible on the first page.
> 
> ![image](https://user-images.githubusercontent.com/17139607/174810057-59a42816-c93c-4aa7-8768-e064677f225b.png)

The bug pic is so cute @KickiLagerstedt !
