### ISSUE TITLE
Access to bam files via IGV viewer in Scout not working

### ISSUE THREAD

**Issue by NicoleCMMS** [Clinical-Genomics/scout#3464]
Is this a general problem or just for us at CMMS? Cannot access bam files via IGV viewer in a number of cases.

**Comment by NicoleCMMS** [comment]
22163-2

**Comment by dnil** [comment]
All good on this side (I'm at the hospital today). 
![Screenshot 2022-06-21 at 16 12 19](https://user-images.githubusercontent.com/758570/174821074-394e7927-2f57-43d2-93ac-b44e96eef382.png)

Did you move the computer between networks recently, or have a pre-update session running? Perhaps just try logging out of scout and in again!

**Comment by NicoleCMMS** [comment]
Restarted chrome and it is working again.  Sorry for bothering you!

**Comment by dnil** [comment]
No worries! The problems that solve themselves are the best! 😄
