### ISSUE TITLE
Add consanguinous score F-score

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/scout#349]
Collect from qcmetrics:
InbreedingFactor:
        Sample_InbreedingFactor:
          - ADM1059A1:-0.2015
          - ADM1059A2:0.01709
          - ADM1059A3:-0.1969

Values above 0.05 indicate consanguinity.

**Comment by moonso** [comment]
Is this in place?
How should we handle the results?
Where and what should we show?

**Comment by moonso** [comment]
Could you please update us on this one @henrikstranneheim ?

**Comment by henrikstranneheim** [comment]
It is in place. I think we should collapse the information per case and just say no consanguineous members if none is above the threshold. If there are consanguinity state it and list the members that are above the threshold. 

Skickat från min iPhone
