### ISSUE TITLE
variant in a gene not in my panel

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#3496]
![image](https://user-images.githubusercontent.com/12525201/177199171-f9ca2e0d-a525-425f-a939-f90168988bb8.png)

My panel is IF, This variants come up after filtering. I can not see why.... The gene belongs to another panel...

**Comment by northwestwitch** [comment]
Hi! Which filters did you use in your search? Looks like the gene is not in you panel yet (it's in the pending changes), but it is in another panel used to analyse that case ([PID candidates](https://scout.scilifelab.se/panels/628cd7d6ab09a99dee6709f5?case_id=amusedgrouse&institute_id=cust002))

**Comment by 4WGH** [comment]
Intellektuell funktionsnedsättning v.6

**Comment by 4WGH** [comment]
I can see now that the gene is in v.7, but this case is analyzed med v.6.

I think anyway this is the explanation :)

**Comment by northwestwitch** [comment]
Ah yes, that makes sense!

**Comment by northwestwitch** [comment]
OK, closing this, but reopen if there is something else to discuss! 🖖🏻
