### ISSUE TITLE
Search all panels -and version- which contain a given gene

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#3497]
In panelS page

**Comment by mikaell** [comment]
Basic functionality working. According to what I could understand of this sparse specification 😃

![image](https://user-images.githubusercontent.com/1150065/179520386-58dd0a2c-f1b9-40ad-adb0-9800ddc8ab68.png)

-[ ] Better presentation and layout
-[ ] Submit reloads the webpage to display results, can this be solved with javascript instead?
-[ ] Look into support for searching different versions.

**Comment by mikaell** [comment]
Minor improvements to layout. Leaving this for now until I get some feedback.


![image](https://user-images.githubusercontent.com/1150065/179693621-76ccacfe-1184-4a74-b122-b2e0114d5c4b.png)

**Comment by northwestwitch** [comment]
Fixed by #3506
