### ISSUE TITLE
Cannot view coverage from variant page for case 15121, Gene: SLC12A1

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/scout#351]

**Comment by moonso** [comment]
Do you know anything about this @robinandeer ?

**Comment by moonso** [comment]
Just tested this and it worked, had to be a temporary problem...

![skarmavbild 2016-11-14 kl 11 28 10](https://cloud.githubusercontent.com/assets/405278/20261315/85a10bec-aa5d-11e6-8909-919f2a1d2ed4.png)
