### ISSUE TITLE
Flask-Login 0.6.2 Will Break Tests

### ISSUE THREAD

**Issue by mikaell** [Clinical-Genomics/scout#3510]
Latest version of Flask-login, release on June 25th (0.6.2) will break our test suite. 0.6.1 works.

Test
```
pytest tests/server/blueprints/alignviewers/test_alignviewers_views.py::test_igv_not_authorized
```

Will not return unauthorised `403`, as expected, but OK `200`. This will cause the test to fail
```
FAILED tests/server/blueprints/alignviewers/test_alignviewers_views.py::test_igv_not_authorized - assert 200 == 403
```

Suggested different approaches to solve this. 
* Freeze flask-login, only
* Freeze all flask associated packages
* Find bug or workaround

**Comment by mikaell** [comment]
The root cause seems to be that session globals have moved from `flask._request_ctx_stack` to `flask.g` (of reasons for me unclear). 

Altering below functions will make the tests pass i.e. return unauthorized

```
flask_login/login_manager.py 

    def _update_request_context_with_user(self, user=None):
        """Store the given user as ctx.user."""
        # 0.5.0 Works
        ctx = _request_ctx_stack.top
        ctx.user = self.anonymous_user() if user is None else user

        # 0.6.2:DOES NOT WORK
        # if user is None:
        #     user = self.anonymous_user()

        # g._login_user = user
```

and
```
flask_login/utils.py

# 0.6.2: DOES NOT WORK
# def _get_user():
#     print('***GETUSER***')
#     if has_request_context():
#         if "_login_user" not in g:
#             current_app.login_manager._load_user()

#         return g._login_user
#     print('- - -')
#     return None

# 0.5.0 WORKS
def _get_user():
    print('***GETUSER 0.5.0***')
    if has_request_context() and not hasattr(_request_ctx_stack.top, "user"):
        current_app.login_manager._load_user()

    return getattr(_request_ctx_stack.top, "user", None)



```

**Comment by mikaell** [comment]
Breaks here. So, do we want to move to Flask 2.2?
```
commit 359fb004f153635952a7d32ded1bbd6d74ec2561
Author: David Lord <davidism@gmail.com>
Date:   Mon Jul 25 07:27:59 2022 -0700

    store user on g instead of app_ctx_stack.top

    Fixes compatibility with Flask 2.2
```

**Comment by northwestwitch** [comment]
I can reproduce this problem locally after having installed scout i a fresh conda env with python 3.8. Perhaps we can fix the issue directly in the code so we don 't need to freeze any library? I can give it a try. Otherwise we can freeze Flask-login temporarily before we find a solution!

**Comment by northwestwitch** [comment]
I've found out that the update of Flask-Login or Flask itself don't affect the app. It's just the tests that use [the flask auto-login fixture](https://github.com/Clinical-Genomics/scout/blob/77ccd686f27128c3b5296a250ce07f05147bef3c/tests/server/conftest.py#L78).

I'll open a PR to create another auto-login fixture starting from a user object that is not admin and is not allowed to see stuff from the demo institute
