### ISSUE TITLE
BAM files missing

### ISSUE THREAD

**Issue by sofievonlanthen** [Clinical-Genomics/scout#3511]
There seems to be an issue this morning visualising the alignments in IGV (for all cases) Any known problem?

**Comment by dnil** [comment]
Hi, yes, hasta is down for an unplanned reboot, and file mounts to Scout, Statina are thus down. Once the cluster is up, the mounts can be reestablished and Scout restarted. Fingers crossed! The routine includes some emails when things go back to normal.

**Comment by sofievonlanthen** [comment]
Great, thanks for the quick reply!

**Comment by dnil** [comment]
For an update, SciLifeLab IT support is working on the cluster reboot which is stuck on some GPFS issue, with unclear prognosis.
I'm at the clinic for two weeks, so also following at a distance. You can always try the support-system if you need more exact info!

**Comment by dnil** [comment]
The cluster is back, verification tests ongoing.
