### ISSUE TITLE
str-variant view uses a template that doesn't exist

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#3530]
This one: https://github.com/Clinical-Genomics/scout/blob/87cea1dbc0465f6f0959ee684cbf885a08164c56/scout/server/blueprints/variant/views.py#L108

We don't see any errors because the `variant.str_variant` view is not used. Should we remove it?

**Comment by dnil** [comment]
Can't remember - maybe it only exists on one of my branches. I can check in a bit!

**Comment by northwestwitch** [comment]
I don't think it's used. If you try to use it you get error because the html template doesn't exist
