### ISSUE TITLE
PanelApp panels: both high confidence (green) and lower confidence (green, amber and red)

### ISSUE THREAD

**Issue by leahkemp** [Clinical-Genomics/scout#3536]
Hi all!

One of our collaborators using scout asked after a possible feature request.

Basically implementing the ability to have a two tier system to first filter for variants by a high confidence PanelApp panel (comprised of genes on the green list). Then if nothing is found, having the ability to filter for variants by a PanelApp panel which includes lower confidence genes (comprised of genes on the green, amber and red lists). As far as I understand, only genes on the high confidence/green list for PanelApp panels are currently utilised in scout.

Apologies if this feature is already available in scout somewhere, I couldn't find anything along these lines in the docs or admin configuration files.

What are your thoughts?

**Comment by dnil** [comment]
Hi Leah! Good to hear from you!

We seldom go outside the Green for panel app on clinical cases, unless there is special competence in an area, in which we usually have a custom panel in the first place. But for research and I guess the occasional pressing case, why not!

We should be able to add loading panelApp panels on amber or red and add those with like almost the same name plus the confidence code? Any feelings about wether to include all at that level and above (like the green plus amber for amber) or just the amber genes in a smaller panel? Both could fit into a workflow I guess. Perhaps the panelApp interface will decide it for us.

**Comment by northwestwitch** [comment]
We could add --level [green(default), amber, red] to the CLI command. Shouldn't be too complicated. We could edit the Panel display name to display the selected color. This way one could have a green version or a red version of the same panel?

**Comment by leahkemp** [comment]
I imagined the situation where we "include all at that level and above (like the green plus amber for amber)" :)
