### ISSUE TITLE
Make "Show variants present only in unaffected" checked by default

### ISSUE THREAD

**Issue by andreaswallberg** [Clinical-Genomics/scout#3541]
Dear developers,

We continue using Scout in teaching and I have rolled forward to the latest code. To not break our lab, I need to have "Show variants present only in unaffected" checked by default in the "Clinical SNV and INDELs" page.

This page is controlled in `scout/server/blueprints/variants/templates/variants/utils.html` but I do not know if there is a way update the html to pass a setting to automatically have it checked when the page loads.

```
{% macro filter_form_footer(form, result_size, total_variants, more_variants, page, nvars) %}
<div class="card-footer text-center">
  <input type="hidden" id="expand_search" name="expand_search">
  <div class="row">
    <div class="col-4">
      <div class="form-check d-flex justify-content-start">
        {{ form.hide_dismissed(class="form-check-input") }}
        {{ form.hide_dismissed.label(class="form-check-label ms-2") }}
      </div>
      <div class="form-check d-flex justify-content-start">
        {{ form.show_unaffected(class="form-check-input") }}
        {{ form.show_unaffected.label(class="form-check-label ms-2", **{'data-bs-toggle': 'tooltip', 'title':'This filter applies only to cases with more than one sample. When this is unchecked, only variants that are predicted by callers to be present in an affected individual genotype are shown.'}) }}
      </div>
    </div>
    <div class="col-4 d-flex justify-content-center">
      Filter returns {{result_size}} / {{ total_variants }} variants.
    </div>
    <div class="col-4 d-flex justify-content-end">
      Showing {%if more_variants %}page {{page}}{%else%}last page{% endif %} with {{nvars}} variants.
    </div>
  </div>
</div>
{% endmacro %}
```

Can someone please help?

![image](https://user-images.githubusercontent.com/1176066/186099828-2f372b83-9cf6-4b7f-ad49-546bb782a638.png)

**Comment by northwestwitch** [comment]
Hej Andreas, the fix is easy enough and sounds like a good suggestion. Should be fine to fix as long as it doesn't interfere with how the vast majority of the clinicians on other sites. I think it should be fine if we describe the change clerarly on the changelog and perhaps we mention it during the next user meeting?

**Comment by andreaswallberg** [comment]
Great!

In the meantime, can you suggest how I tweak the code to accomplish this?

Presumably, an argument can be passed to:

`{{ form.show_unaffected(class="form-check-input") }}`

I checked the docs but did not find a way to do it myself:
https://getbootstrap.com/docs/4.0/components/forms/#validation

**Comment by northwestwitch** [comment]
Ah wait, sorry, I misread. You want to only show the variants in the unaffected individuals by default, not those in the affected? Then it's not so easy, since I guess most clinicians are interested in variants in the affected. 🤔

**Comment by northwestwitch** [comment]
Perhaps we can introduce a new settings option on the institute page, so that it applies only to your institute

**Comment by northwestwitch** [comment]
Another (perhaps simpler) solution would be to check it automatically whenever you have no affected individuals in your case..

**Comment by northwestwitch** [comment]
> To clarify, I want all variants to be shown by default

Ah OK, then it's not even the case of "Show variants present only in unaffected", because what you get if you check that checkbox is variants that are are uniquely present in unaffected. 
Let's think about a solution!

**Comment by dnil** [comment]
It is still not perfectly clear why, but I think he wants no particular filtering for affected status, i.e. `show_unaffected is not False`. Then a per institute default setting as you suggested should work just fine!

**Comment by andreaswallberg** [comment]
We use the platform differently from how it is used in a true clinical setting.

In our case, we only have a few hand-crafted variants per case that students are stepping through to observe genotypes across pedigrees and verify how they match pathologies and patterns of inheritance and the affected individuals and such. I just want to make sure all variants are shown per default.

**Comment by northwestwitch** [comment]
We have now introduced a change in the software so it will be able to automatically show all variants for a case (checkbox preselected). There will be a new option in the Institute settings page to do so, check [here](https://github.com/Clinical-Genomics/scout/pull/3542#issue-1347939678). This new feature will be available from the next release (in a few days?).
