### ISSUE TITLE
Causative and validated variants pages are not easy to read when they contain huge SVs

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#3546]
Example:

<img width="797" alt="image" src="https://user-images.githubusercontent.com/28093618/186587725-73fd71a3-141c-4de0-9a3c-19ac8c27a9c1.png">

**Comment by northwestwitch** [comment]
Perhaps fix as in #3522?

**Comment by dnil** [comment]
Yes, that is a consistent solution. At some point we need a function to pick representative generals from that list (like matching phenotype, being on the panel, being in a panel, being disease genes, being at the edge of the event for balanced ones, …).
