### ISSUE TITLE
Allow for hyphens in "Panel ID"

### ISSUE THREAD

**Issue by ehre** [Clinical-Genomics/scout#3548]
When creating a new gene panel from the user interface, the internal field "Panel ID" allows for underscores but not for hyphens ("bindestreck", see attached image). For reasons beyond my understanding (perhaps @mhkc can fill in), underscores don't work in our pipeline in Lund, so our bioinformaticians have changed to hyphens in the backend. With increasing use of gene panels, however, we would appreciate if an end user could assign Panel ID with hyphens from start and reduce unnecessary work load on our bioinformaticians. In summary, if there are no technical counter arguments, please allow for hyphens in the field "Panel ID"!

![Panel ID](https://user-images.githubusercontent.com/12267779/186590121-7ec680b8-5c96-421c-bd06-8494cb90b9af.png)

**Comment by dnil** [comment]
Hi! I think that was to avoid errors on the storage engine with special characters; dots specifically were incorrectly interpreted. But let's test with hyphens - they are probably fine too!

I found https://github.com/Clinical-Genomics/scout/issues/2400 - do you remember anything else @northwestwitch?

**Comment by northwestwitch** [comment]
> I found #2400 - do you remember anything else @northwestwitch?

Sorry I've just read you comment.  I think you are not allowed to use `.` or `$`, other chars should be fine

**Comment by dnil** [comment]
Good, I just let hyphens pass as well for now. We do export these at CG for use in MIP etc. Famous last words, I don't see hyphens doing anything, but if we start talking `/|()[]%*$ˆ`, that might be another story. Nice not to have to think too much about escaping mechanics for different shell/perl/nf use cases. 😅
