### ISSUE TITLE
Clinical HPO SV (sic!) variants

### ISSUE THREAD

**Issue by ehre** [Clinical-Genomics/scout#3568]
When we have created a HPO gene panel, there is a shortcut button to "Clinical HPO SNV variants" on the case overview page. We request to add another button to the corresponding page for structural variants, i.e. a "Clinical HPO SV variants".

Additionally, on the variantS pages filters settings, the button "HPO gene list" works as expected for SNV/indels, but not for SVs (nothing happens in the SV list if that button is pressed).

**Comment by dnil** [comment]
Thank you @ehre! Two things, slightly connected if I'm not mistaken, but lets see. 

1) Ofcourse, will add a button!
2) Bummer, wonder when than broke. 🙄 We will try to figure that out too when fixing. In the meantime, selecting the HPO list from the gene panel dropdown works, as does checking the "use HPO for clinical filter" toggle, and then using Clinical filter on the variantS page (which I guess is the most common use case for us). Thanks a bunch!

**Comment by ehre** [comment]
1. Great!
2. Could it be just in our Scout instance? I can confirm that selecting the list from the dropdown works. We don't use "clinical filter" in our routine workflows, so that part is more obscure to me.

**Comment by dnil** [comment]
2. Nah, its broken here as well. Presumably collateral damage from some other fix, but let's see.
