### ISSUE TITLE
Functional annotations overlapping frequencies

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#3575]
When checking the new version, this came up;
![Screenshot 2022-09-07 at 14 56 39](https://user-images.githubusercontent.com/758570/189047702-0b5b7226-935e-46e6-821f-6f4b67ded886.png)

We should wrap/fix column width or give prio to freq worst case: it is the more important info.

**Comment by northwestwitch** [comment]
Ah!

**Comment by northwestwitch** [comment]
It's the 2 cols region|function for SV tables, right?

**Comment by dnil** [comment]
Yes, exactly! We could just move the freq column a couple of steps left in the table, to like before the region one. The gene column gets somewhat redundant anyway when the region/function have gene symbols in them,

**Comment by northwestwitch** [comment]
But I wouldn't remove the genes cell, because when the SV variants have > 30 genes not all genes are shown in these 2 overlapping cells:

<img width="531" alt="image" src="https://user-images.githubusercontent.com/28093618/189049606-df694512-983f-462f-abb1-8ef3504aec6e.png">
