### ISSUE TITLE
Gene panel overview coverage for HPO panels

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#3581]
It currently seems only possible to get to the Coverage report, not Coverage overview for a dynamic panel. Let's add a button or two?

Thanks and credits to Sofie S in Lund for noticing!

**Comment by ehre** [comment]
Thanks to your intel recently, @dnil , we also just realized that we can get coverage info for individual genes using the format: http://"scoutinstance"/reports/genes/"HGNC ID"?sample_id="sample id"
In addition to coverage overview for a dynamic panel, perhaps it is also possible to get these types of links from e.g., the gene pages?

**Comment by dnil** [comment]
Indeed @ehre - it is available from the variant page, here:

![Screenshot 2022-09-09 at 10 54 37](https://user-images.githubusercontent.com/758570/189312303-2bdcf227-a855-40a9-84ec-72e2170505b9.png)

**Comment by northwestwitch** [comment]
I was posting the same pic. I realize it's not obvious, so perhaps we could add a label before that gene?

**Comment by dnil** [comment]
I also feel we should bump the tutorial video walkthrough up a notch on the prio list. 😊

**Comment by dnil** [comment]
For those that dont know, @genecracker made two lovely sets of videos for our students, but they are hosted behind walls at the KI education platforms. We have been saying we should do public ones since forever..

**Comment by northwestwitch** [comment]
> behind walls at the KI education platforms

Behind walls because of the content?

**Comment by dnil** [comment]
The first because of content - it was for cases with research permits and for med students, but not comfy to share to all. The second instalment just for convenience I think: it was made with public data (NIST samples with spiked in pathogenic variants).

**Comment by ehre** [comment]
Ha, ok :) I was not aware of the coverage link from the variant page, and neither were our CLG's. So perhaps you should add a label as @northwestwitch suggests and we all need to watch that video ... At the same time, when we have a specific variant I guess we rather use IGV for quality checks, so we would need to be able to get to gene info even if (and especially when) we don't have a called variant in that particular gene. But I guess that will be solved if you add coverage overview for a dynamic (HPO) panel. Thanks!

**Comment by northwestwitch** [comment]
> So perhaps you should add a label as @northwestwitch suggests

Done: https://github.com/Clinical-Genomics/scout/pull/3582#issuecomment-1241716676. It looks like a button that says "Coverage". Will be available in the next release (beginning of next week)

**Comment by dnil** [comment]
@ehre, sure; the intent for the link-made-button is mostly for compound recessives where you have found one and start thinking if maybe there is a region not so well covered.
