### ISSUE TITLE
STR loci and gene lists

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#3583]
It is a recurring problem for the clinicians that the panels don't differentiate between different variant types. One thing that would help in the meantime (and that causes manual work for clinical report writing) is marking what genes on a panel had STR loci called for the case. This would be reported/shown on a separate section and/or a special format for the gene symbol on the pdf gene panel reports for a case (static and dynamic). The list report view would have to accept also a case in addition to the panel.

**Comment by northwestwitch** [comment]
I'm considering working on this today, but I need to understand better. For panels, you mean dynamic HPO panels? Because if it's "official" gene panels one could always go to the STRs page, choose a specific panel and export with the "filter and export".

>This would be reported/shown on a separate section and/or a special format for the gene symbol on the pdf gene panel reports for a case (static and dynamic)

What is this report, this one?

<img width="601" alt="image" src="https://user-images.githubusercontent.com/28093618/196617943-21b631e6-5241-4f23-b24e-8280f43c8905.png">

**Comment by dnil** [comment]
Yes, its nice for those; I was thinking of the "static" case specific panel; like the pdf from here:
<img width="659" alt="Screenshot 2022-10-19 at 09 13 56" src="https://user-images.githubusercontent.com/758570/196622181-461f57e5-5e29-4532-b233-560f18fc1248.png">
<img width="839" alt="Screenshot 2022-10-19 at 09 13 40" src="https://user-images.githubusercontent.com/758570/196622250-7f6412b2-a71b-415a-bd71-891619cfb5f8.png">

My ideal for the future would be a report of the stuff that can be (or even has been if combined with e.g. tagging filters audited) analysed for the case. This would be a dense version of the above pdf, with mostly just sorted gene symbols, but where the genes also covered by STR analysis are highlighted and/or in a separate row as well, like:

# My Panel 2.1
## Last update, number of genes and other panel meta data

### SNV and SV genes
ARGH, BMP1, ...

### Genes on panel with STR analysis available
AR, ATXN1, ...

{if SMN1,SMN2 on list  available and SMNCopyNumber loaded} 
### SMN Copy Number
SMN1, SMN2

{if trio / chromograph UPD images available} 
### UPD analysis

**Comment by northwestwitch** [comment]
Ok! I see. You go on a panel and from there you provide a case. Then you download a document with all occuring variants in that panel, by variant type!

**Comment by dnil** [comment]
> Ok! I see. You go on a panel and from there you provide a case. Then you download a document with all occuring variants in that panel, by variant type!

Almost! I think you have it, but just to be sure:

You go on a panel and from there you provide a case. Then you download a document with all genes in that panel, by variant type. Since we don't have a good separation of variant type on the panels, a proxy in the case of STRs could be genes in the panel for which there are variants.

**Comment by northwestwitch** [comment]
Yes I got it, thanks!

**Comment by northwestwitch** [comment]
Since we are already touching this code, we have a good opportunity to fix these badges on gene panel export that are not really readable:

<img width="476" alt="image" src="https://user-images.githubusercontent.com/28093618/196633966-df32af88-0493-4a1d-bc49-8c4cfc51cf0d.png">
