### ISSUE TITLE
Scout entrypoint /static sets duplicated response headers causing 502 errors

### ISSUE THREAD

**Issue by mhkc** [Clinical-Genomics/scout#3584]
Scout respond with duplicated headers when IGV ask the `/static` entrypoint for a bam file resulting in 502 errors and that tracks are not displayed in IGV.

**Error from NGINX**
`2022/09/09 09:28:20 [warn] 32#32: *4064 upstream sent duplicate header line: "Content-type: application/octet-stream", previous value: "Content-Type: text/html; charset=utf-8", ignored while reading response header from upstream, client: 10.231.229.34, server: , request: "GET /remote/static?file=%2Faccess%2Fwgs%2Fbam%2F9313-22_dedup.bam HTTP/1.1", upstream: "http://172.22.0.11:5000/remote/static?file=%2Faccess%2Fwgs%2Fbam%2F9313-22_dedup.bam", host: "cmdscout2.lund.skane.se"`
`2022/09/09 09:28:20 [error] 32#32: *4064 upstream sent duplicate header line: "Content-Length: 26", previous value: "Content-Length: 26" while reading response header from upstream, client: 10.231.229.34, server: , request: "GET /remote/static?file=%2Faccess%2Fwgs%2Fbam%2F9313-22_dedup.bam HTTP/1.1", upstream: "http://172.22.0.11:5000/remote/static?file=%2Faccess%2Fwgs%2Fbam%2F9313-22_dedup.bam", host: "cmdscout2.lund.skane.se"`

**Error is caused by** 
Scout just append Content-Type and Content-Length resulting in these headers being duplicated. Link to relevant [code](https://github.com/Clinical-Genomics/scout/blob/b0ef15f4737d0c801154c1991b52ff5cab4f5c83/scout/server/blueprints/alignviewers/partial.py#L61)

Headers before append statements
```
Content-Type: text/html; charset=utf-8
Content-Length: 26
```

Headers after
```
Content-Type: text/html; charset=utf-8
Content-Length: 26
Content-type: application/octet-stream
Accept-Ranges: bytes
Content-Range: bytes 3285-3310/45531713695
Content-Length: 26
```

**Comment by northwestwitch** [comment]
@mhkc offered to fix! 🙏🏻
