### ISSUE TITLE
Gene panels in alphabetical order - also in "pop-up-list"

### ISSUE THREAD

**Issue by ehre** [Clinical-Genomics/scout#3589]
You previously solved an issue about displaying gene panels in alphabetical order on various Scout pages - great! However, we have noted that in the "pop-up-list" on the case page, the gene panels are still not arranged alphabetically. With an ever increasing number of panels, it would be appreciated to solve this as well. 

![image](https://user-images.githubusercontent.com/12267779/189371303-4448d593-d218-4538-9976-56f6c482f4d4.png)

**Comment by northwestwitch** [comment]
I have the feeling we had this fixed some time ago. Perhaps we reverted the code by mistake? Anyway, we'll fix. Thanks for reporting it!
