### ISSUE TITLE
Customer wants to be able to filter CANCER SVs by tumor or normal alt freq

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#3595]
But tumor or normal alt freq looks like this:

<img width="117" alt="image" src="https://user-images.githubusercontent.com/28093618/191691779-c9378b8b-f1fa-4314-843c-b4e2b3fa8838.png">

Example: https://scout.scilifelab.se/cust109/F0041632-1/cancer/sv-variants?variant_type=clinical

**Comment by dnil** [comment]
Hm, is said customer SV caller savvy? They understand that what numbers they see on those columns for SV is very different from what they see on SNVs, strongly caller and variant type dependent? I dont quite see how a filter like that would be very useful in Scout. For a Balsamic quality hardfilter possibly, but my feeling is this is about something other than what the customer thinks they are getting?

**Comment by northwestwitch** [comment]
Mmm perhaps not? Let's move this discussion on the PR page!

**Comment by dnil** [comment]
Ok, after the discussion with pipeline developers, I agree we disable the VAF filter for SVs for now. We could also add a tooltip to the header alerting the user to the different nature of the beasts they have in that column compared to on the SNV page.

**Comment by northwestwitch** [comment]
> We could also add a tooltip to the SV column header Tumor - Normal alerting the user to the different nature of the beasts they have in that column compared to on the SNV page.

Sounds good, any suggestion for the tooltip text (I am writing a PR to remove VAF filter and I could add it in there)

**Comment by dnil** [comment]
I can write the long version, and maybe you can find a condensed form? 😆 

Counts are sums of read depth, split read and discordant read pair evidence, and may be comparable between tumor and normal, but not between variants. Count relation to VAF is not well understood and varies with variant type and caller. See variant page for more details.
