### ISSUE TITLE
Disable dynamic coverage buttons / links when unavailable

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#3598]
We currently display dynamic coverage buttons for Solna somatic cases, even though they are not in the db, since Chanjo is configured for RD and RD only. It would be useful to have a config option to supress them for e.g. certain track types.

**Comment by mikaell** [comment]
> display dynamic coverage buttons

Which button in the GUI is this?

**Comment by northwestwitch** [comment]
> Which button in the GUI is this? Where? (As soon as I've found it, this should be a simple fix).

Check this previous PR: https://github.com/Clinical-Genomics/scout/pull/3588

**Comment by mikaell** [comment]
Ready for review: https://github.com/Clinical-Genomics/scout/pull/3606

**Comment by northwestwitch** [comment]
This was fixed by #3606, closing!
