### ISSUE TITLE
Matching causatives

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#3600]
Try to make the matching causatives sharper in differentiating causatives in relevant panels from panels likely to result in incidental findings for the institute.

**Comment by ehre** [comment]
A related thought (I can open a separate issue if you prefer): Should perhaps "managed variants" also be visible only in relevant gene panels? I had a discussion last week with a Stockholm colleague and we seem to have the same problem with incidental findings for this category.

**Comment by ehre** [comment]
Not sure what you mean with "ran with OMIM", but yes, it is definitely a question for us as well. To answer your question, it is important to understand all use cases, but from my perspective perhaps one way would be to only show matching causatives and managed variants in genes that are included in the chosen gene panel(s) per default, with an option to "open up" if you are in exploratory mode?

**Comment by dnil** [comment]
I think you started with more open mendeliome analysis, less panels, but nice that things converge!

Right, that is kind of the way it is intended currently: an extra click is needed to look, and the causatives from within your selected panel would be visible on the variant lists anyway. The (even more open) initial use-case was to avoid missing causative variants from phenotypically partially overlapping panels.

**Comment by ehre** [comment]
Ah ok. Well, that is the typical procedure for complex trios, but all our single WGS analyses run on panels (i.e., the majority of requests). The thing with managed variants, as you know, is that they are displayed separately so you currently see them on all investigations, but if you can make them to just show up on panels where the gene is included would be good, IMHO.

**Comment by dnil** [comment]
We'll give it another shot at a proper balance point. The thing is that several customers (typically with a few, somewhat related panels) find it useful. At the very least we could add an optional limit-to-panels on a per institute basis.

**Comment by dnil** [comment]
Comment from Sofie S: also ensure that the list of matching causatives only includes variants that are currently marked causative, not other cases that just have the variant. 

This could be in line with a more restrictive use of the functionality, and should probably be optional. It has been very practical a few times to go directly to old cold cases when a new causative is established.

**Comment by northwestwitch** [comment]
> A related thought (I can open a separate issue if you prefer): Should perhaps "managed variants" also be visible only in relevant gene panels? I had a discussion last week with a Stockholm colleague and we seem to have the same problem with incidental findings for this category.

I've started working on this issue and I have a comment about managed variants. This category of variants was created as a list of genomic coordinates meant to be independent from genes (otherwise you would use gene panels for including variants of interest in searches). They could be SNVs or large SVs and for this reason (and the fact that there is no connection with gene panels) it is very problematic to filter matches in this type of variants by gene panels. I think it would be perhaps easier to do as suggested by @sofievonlanthen  in #3379 --> setting the list of managed variants  by institute or something like this

**Comment by ehre** [comment]
I  see. However, we also use managed variants to assure that we don't miss variants that get a very low rank score in Scout, typically well known risk factors that are too common in the population to fit Scouts "RD-centric" scoring system.

**Comment by northwestwitch** [comment]
> see. However, we also use managed variants to assure that we don't miss variants that get a very low rank score in Scout, typically well known risk factors that are too common in the population to fit Scouts "RD-centric" scoring system.

I think I've found a way. I've opened a PR to start fixing this issue now!

**Comment by northwestwitch** [comment]
Perhaps we can also close this issue now that we have #3611 in place?

**Comment by northwestwitch** [comment]
Nobody seems to disagree (read above), so let's close this issue
