### ISSUE TITLE
Additional archived category

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#3605]
Request from Lund. Sometimes they have duplicate cases, like a trio plus one with a parent with mild phenotype also set as affected, where only one case may be actually analysed in the end. Currently when archived, these will count as unsolved. An additional archive category that does not count towards unsolved in the statistics is desired.

**Comment by northwestwitch** [comment]
Like a "Solved" but without a candidate variant?

**Comment by dnil** [comment]
Which would then still count towards "solved" for the stats, but otherwise yes. (And we have a couple of vars that can't be marked yet, like SMN or SVs not called but found on visualisation, so we probably dont want to use that as a feature).

**Comment by dnil** [comment]
Like an opt out for statistics for the case?

**Comment by dnil** [comment]
Yes, that is the gist!

**Comment by dnil** [comment]
Which behaves like archived in basically all aspects except not being included in summary statistics for the analysts.
