### ISSUE TITLE
Show analysis_type on Verification / Causatives

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#3615]
It would be useful to be able to stratify verifications on analysis type on export in particular, but it is probably fairly interesting to see and sort in the table as well. Available on each individual.

**Comment by northwestwitch** [comment]
You mean variants displayed on these pages?

<img width="200" alt="image" src="https://user-images.githubusercontent.com/28093618/194229850-70f08a3f-41ff-4817-b974-60abcdc9ec56.png">

**Comment by dnil** [comment]
Yeah, like an additional column with WGS, WES etc from the individual in question.
