### ISSUE TITLE
Managed variant edit dropdown population broken

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#3619]
Presumably since bs5, but who knows.

![Screenshot 2022-10-06 at 11 17 05](https://user-images.githubusercontent.com/758570/194275267-aecf5cc4-9864-41dd-9dc6-884fba50e379.png)

How to reproduce:
- add a managed variant which is not on chr1 or an SNV subtype.
- manually attempt to edit it and note that the dropdowns preset start at chr1 and SNV, not your variants value

**Comment by northwestwitch** [comment]
This is fixed now. Closing
