### ISSUE TITLE
Kinship N/A and no de novo variants

### ISSUE THREAD

**Issue by MUebe** [Clinical-Genomics/scout#3639]
Hi!
We are suspecting something is not right with one of our recent trio analyses (CMMS): 
Kinship is displayed as N/A for both parents.
When we looked for a previously found variant from the single-analysis, we could not find any variants in this gene.
De novo search filters return no variants at all (unlikely?!).
Thanks in advance for feedback and help!

**Comment by dnil** [comment]
Hi, we can have a look, just post a case id! But if it is the one case I suspect you may fare better contacting support at cg in Solna and/or reconfirming that all was as you expected with the order in Orderportalen!

**Comment by dnil** [comment]
Couldn't help it; had a look. I think you are referring to `meettick`, right? It looks good on inheritance if you check a few rare variants (with perhaps some bias for one of the parents, but both can be seen). The pedigree file for the analysis has none of the individuals marked as being related to eachother though - its ordered as a small cohort study of affected and unaffected if you will. Place a rerun-order in orderportalen identifying the parents and you should be fine in a few days. Closing this, but do reopen if I guessed the wrong case or something. Cheers!

**Comment by MUebe** [comment]
Thanks for the help! 
I have just one more question regarding this case (meettick). A variant in ADRA2B was pinned in the single-analysis, but is not coming up now when looking for variants in this gene. I assume this is because the variant was ranked too lowly in the trio. Is there a way to display all variants in the gene regardless of the ranking (may be useful for other genes and cases as well)?

**Comment by northwestwitch** [comment]
Hello again, yes, it's probably because it ranked quite low. In these cases what you do is opening a ticket in our support system and ask us to load all variants in that gene for that given case.

Kind regards,
Chiara

**Comment by MUebe** [comment]
Thanks! :)

**Comment by dnil** [comment]
Yeah, the variants that do not fit the inheritance pattern (AD inherited from unaffected - or present in unaffected cohort members before the rerun) should receive a fairly big malus score from that. Support ticket to upload all is best in general, but of course you can sneak a peek in IGV at the read level data as well.
