### ISSUE TITLE
Non-admin user saving settings on institute settings page clears loqusdb settings

### ISSUE THREAD

**Issue by NicoleCMMS** [Clinical-Genomics/scout#3640]
Hi,
In the cases uploaded over the weekend we are missing the local observations. Hope this is easy to fix :-)
Nicole

**Comment by dnil** [comment]
Eh, which case and which view, sorry? I see local variants on the variants list of your most recent cases?

<img width="529" alt="Screenshot 2022-10-24 at 12 40 12" src="https://user-images.githubusercontent.com/758570/197508140-220bb458-dcd9-4695-8717-f31f8e9b9778.png">

**Comment by dnil** [comment]
Oh, did you mean the live loqusdb view? You had it turned off for your institute for some reason - I've reselected it for you now. You can change the loqus data source at any time on the Institute settings page, though for RD in Solna there are not that many dbs to choose from. 😊 

All good now?

**Comment by dnil** [comment]
If this keeps happening for you, we could consider locking the institute settings to a few selected admins for each Institute. So far, the flexibility has been good, but...

**Comment by 1ctw** [comment]
It appears that all institute settings have been cleared automatically?

**Comment by NicoleCMMS** [comment]
Yes all looks good again, thanks!  However I don't have the ability to add/remove the loqus data source in the settings for CMMS.  It must have been somebody with a higher admin status then me.

**Comment by dnil** [comment]
Great, closing then. I dont think it was you, but you should have the ability to: all Institute users are equal in that regard! Just click the dropdown and then the selected "default" loqus db. It then becomes unchecked, and if you now save the settings, you will no longer see any loqus hits on the variant page.

**Comment by dnil** [comment]
@1ctw, sorry, I didn't quite follow you - what do you base that inference on? I see most of the settings filled in (email, cohorts, Alamut key etc), all of which would require a little bit of effort to restore correctly?

**Comment by 1ctw** [comment]
Sorry, but I just meant that this morning "Gene panels available for variants filtering" was missing in the Settings and then also the Settings regarding locus data source was emptied for CMMS. What I meant was that I thought it happened during the update last week and was not changed by us, but I may be wrong.

You write that all institute users should be able to select locus db. Could you please specify were the dropdown for that is located? This is what I can see in the Genereal Institute Settings page. 
![image](https://user-images.githubusercontent.com/15033593/197515918-fdaea17a-e21b-4c5a-b40f-162ce8952d9f.png)
Thanks for your help!

**Comment by dnil** [comment]
Hm, sorry @1ctw - I take that back - it appears only users with admin status will see the loqus and alamut key fields nowadays. There is a risk that might also mean that it might reset under certain conditions when non-admin users save to the page. We will check; as usual thanks for reporting!

**Comment by dnil** [comment]
Yep, that's it. Non admin users can clear the alamut database when changing other options, since the backend parts are not aware that the frontend parts don't show the loqusdb dropdown to non admin users.

Thanks @1ctw and @NicoleCMMS; will fix.
