### ISSUE TITLE
Upcoming changes to ClinVar's submission spreadsheet templates

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#3642]
Dear ClinVar submitter,

To streamline the process of submission to ClinVar, we are changing how submitters provide new files for assertion criteria and how they indicate which assertion criteria applies to submissions that use our submission spreadsheet templates.

Providing new files for assertion criteria:

New files for assertion criteria will be uploaded on your landing page in the ClinVar Submission Portal, independent of a submission.
Assertion criteria for a submission will be indicated on the Assertion criteria tab in the Submission Portal.
Only one assertion criteria document (a citation or a file) may be reported for a submission, and the assertion criteria must apply to all records in that submission.
Previously reported assertion methods will still be available for use in submissions.
New submission spreadsheet templates:
The new spreadsheet templates (versions L1.7 and 4.3) no longer include the following columns:

Assertion method
Assertion method citation
Previous versions of the templates will no longer be supported. Adopting these new templates into your workflow will be required for all future file submissions to ClinVar, so please familiarize yourself with the updated templates. We anticipate releasing these changes to the submission templates and the Submission Portal in mid-November.

**Comment by northwestwitch** [comment]
I should fix #3572 accordingly I guess

**Comment by dnil** [comment]
I suppose - or perhaps even better with a separate PR since they have not actually changed yet: "mid November"..
