### ISSUE TITLE
Modify CLI command to load any type of report

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#3649]
The scout load command at the moment is used to load a lot of things:

```
Usage: scout load [OPTIONS] COMMAND [ARGS]...

  Load items into the scout database.

Options:
  --help  Show this message and exit.

Commands:
  case                Load a case
  cnv-report          Add CNV report report to an existing case.
  coverage-qc-report  Add coverage and qc report to an existing case.
  cytobands           Load cytobands
  delivery-report     Add delivery report to an existing case.
  exons               Load exons
  gene-fusion-report  Add or update a gene fusion report (clinical or...
  institute           Load a institute
  panel               Load a gene panel
  region              Load variants from region
  research            Upload research variants
  user                Load a user
  variants            Upload variants to existing case
```

Since the beginning, the options of this command have been increasing in number, and now we need to add one more for the RNA QC reports (#3647). I think it would be best if we could dedicate a specific command to load reports, with the option to load custom reports that don't belong to the existing categories (CNV, coverage-qc-report, delivery-report, gene-fusion-report). This way the existing command would be simplified and the new command would allow to load any document for a case.

**Comment by dnil** [comment]
Closed by #3650! Well done!
