### ISSUE TITLE
New RNA reports in Scout

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#3658]
RNA data already supported by Scout:
- A pdf report produced by Arriba, loaded at the case level, ~~with the key `gene_fusion_report ` (or `gene_fusion_report_research ` if it's based on research data)~~ Suggested name: `arriba_report`
- `splice_junctions_bed` and `rna_coverage_bigwig` -> igv tracks saved at the case.individual level

New reports and data to be included:
- [ ] Another fusion report file in HTML format produced by FusionReport (this is the fusion summary that collects metrics from different methods: arriba, pizzly, starfusion, fusioncatcher, squid). This should be the primary summary report. Suggested name: `fusion_report`. 
- [ ] Another fusion report HTML file produced by FusionInspector (this provides a detailed visualization of all fusions found). Suggested name: `fusion_inspector`. 
- [ ] RNA multiqc file, also HTML file, work in progress, see #3650 
- [ ] .tsv file from Fusion Inspector -> convert into variants-like data and load as if they were scout variants

**Comment by fevac** [comment]
I am uncertain about the names for each report. To me `fusion_report` and `fusion_inspector` are the most important/informative reports since they collect the information from several tools. I would suggest renaming the report produced by Arriba, is this something you want to avoid (as this is already implemented)?

**Comment by dnil** [comment]
Yeah, exactly: I’m afraid changing it retroactively for all the already loaded ones is a bit of a pain. It’s doable, but if it’s just for the name we would rather spend the effort where it counts. 

Perhaps the pipeline or programs used to produce the reports have more names / parts to them?

**Comment by northwestwitch** [comment]
To rename the key `gene_fusion_report` and `gene_fusion_report_research` to `arriba_report_something` one could always write a script to add a new key/value to the cases and then remove the old keys/values. This is totally doable for us, but what if other facilities started to use those key/values as well? We would mess up with their data..

**Comment by fevac** [comment]
ok, then, what about:
- leave arriba as: `gene_fusion_report`
- fusion report: `gene_fusion_summary`
- fusion inspector: `gene_fusion_inspector`

@jemten what do you think?

**Comment by dnil** [comment]
It would not hurt with a little "RNA" in the key. The pipeline is named `nf-core/rnafusion`, so perhaps 
they could be `RNAfusion_report` and `RNAfusion_inspector`?

**Comment by fevac** [comment]
Good point. I like that.

**Comment by northwestwitch** [comment]
I've merged the PR to simplify loading of case reports in Scout. Now we can basically add items to [this list](https://github.com/Clinical-Genomics/scout/blob/0503f04a9b9de734ca428fdfd4d7acd0907af755/scout/constants/case_tags.py#L3) and the reports should be loaded with the command `scout load report <report-type>`.

I'm not sure if these reports will be loaded when provided in the case config file when loading/updating a case..
