### ISSUE TITLE
Loop thru constants.CUSTOM_CASE_REPORTS when loading a case via yaml config file

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#3662]
So that if the case contains any of the reports from CUSTOM_CASE_REPORTS the values will be collected and saved in case document automatically.

**Comment by northwestwitch** [comment]
I'm starting to realize that this issue wants to do the very opposite of the pydantic parsing of the config file. 

The problem is that when you declare the pydantic model you are [already supposed to know the names all the possible fields](https://github.com/Clinical-Genomics/scout/blob/290e1db6a1b4d95ab0bc0ab27ebc495a4e992225/scout/parse/models.py#L297) that will be found on the config file. Instead we would like to set dynamic fields according to the keys found on CUSTOM_CASE_REPORTS.

I don't know if this fix would be possible, I haven't found a solution yet

**Comment by dnil** [comment]
I see your point. Maybe there is some nice trick for it in Pydantic, but afaik one would need to add like a general array or dict for the reports with the types and filenames. Which is a fairly big change to the config files and data structure. I suppose it would still not be so bad if we have to add the key it to two places?

**Comment by northwestwitch** [comment]
Something like this perhaps: https://github.com/pydantic/pydantic/issues/1937

**Comment by northwestwitch** [comment]
Ok, doing something like the option in previous comment is possible and it's probably working. But I don't think we should go that way: we have chosen the strict pydantic model for a reason and it doesn't make sense to me to start adding conditions to it now. I think we should keep adding every new report to the pydantic model manually. This way we also have better control over all the available fields. Closing this issue now!
