### ISSUE TITLE
extra , in expected inheritance column

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#367]
happening on the newlly uploaded case 16130. probablt a bug?
See pic
![skarmklipp](https://cloud.githubusercontent.com/assets/12525201/19887031/67b8285e-a026-11e6-89d5-6945a0ac725d.PNG)

**Comment by moonso** [comment]
Hi,

we also noted this earlier today. There is a problem with the latest version of the gene list file.
We will handle this as soon as possible, the only thing that will be affected for now is when scout will try to compare the expected inheritance to the observed inheritance on the variant level.

This is something to adress at the meeting tomorrow.

Måns

**Comment by ingkebil** [comment]
Hi,

I've updated the CML to remove the prepended inheritance model,

wkr,
Kenny

**Comment by robinandeer** [comment]
this is not affecting any filtering and we are rerunning the cases in time
