### ISSUE TITLE
Panel extent report, outdated genes without whitespace look odd at line end.

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#3679]
<img width="1303" alt="Screenshot 2022-11-23 at 11 24 25" src="https://user-images.githubusercontent.com/758570/203523691-e44a71a8-5286-4d12-9b31-6925db317a56.png">

Suggested action: add whitespace.

**Comment by northwestwitch** [comment]
Where is this, on case page or also on panel page?

**Comment by dnil** [comment]
Specifically on the new case specific panel extent report pdf. For the case / panel pages tooltip I think it is ok without whitespace, right?
