### ISSUE TITLE
disease associated transcript not appearing in Scout - CMMS

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#368]
![skarmklipp](https://cloud.githubusercontent.com/assets/12525201/19887304/eb836f62-a027-11e6-95d6-8fe8de5889db.PNG)

there is in the gene panel file provided.

**Comment by moonso** [comment]
Not sure why this does not work, we have reworked this in the new scout so it will not be any problem.

**Comment by moonso** [comment]
This should be fixed now
