### ISSUE TITLE
Not loading BAM files

### ISSUE THREAD

**Issue by MUebe** [Clinical-Genomics/scout#3697]
Hi!
I seem to not be able to access the BAM files for the case driventiger.
This time, I can access IGV but getting error:
Access forbidden: /remote/static?file=%2Fhome%2Fproj%2Fproduction%2Fhousekeeper-bundles%2Fdriventiger%2F2022-11-30%2FACC10833A9_lanes_11223344_sorted_md.cram&someRandomSeed=0.c6ea566mdsr
(in case that helps)
Thanks in advance for helping! :)
Malin

**Comment by dnil** [comment]
Hi @MUebe, 

the case in question seems to have decently healthy cram files from a few clicks to test. Are you on the hospital network? Have you switched locations or network in the same scout session by any chance? This sounds like a CORS problem. Perhaps you could try logging out and back in again and see if the error persists?

![Screenshot 2022-12-02 at 15 55 35](https://user-images.githubusercontent.com/758570/205321505-9cff4981-da10-46f9-8ea9-211b44a439f0.png)

**Comment by MUebe** [comment]
Ah, I logged out and now cannot log in (Internal server error)...

**Comment by MUebe** [comment]
Now it seems to work, restarted everything.
