### ISSUE TITLE
Set condition_type in ClinVar upload based on condition terms used

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#3699]
For adding a clinvar submission, if an OMIM diagnosis is selected for the case, it is not possible to add other types of phenotype term, like picking an HPO instead. It would make sense to lock in the condition type based on that instead then, since there is a strict if clause anyway. 

![Screenshot 2022-12-05 at 09 04 17](https://user-images.githubusercontent.com/758570/205585593-715c04f9-72aa-4d76-a337-d18fc55b17e5.png)

As it is, the user must take care not to do this, which would fail verification.
![Screenshot 2022-12-05 at 09 13 07](https://user-images.githubusercontent.com/758570/205586791-0507e05d-f899-4010-b145-551c4dc70ab4.png)

**Comment by northwestwitch** [comment]
True! An easy fix would be to ask the user to only type the ID (for instance 00000191 instead of HP:00000191) and then we fix the values by adding HP: when parsing the form.

**Comment by dnil** [comment]
I was just thinking to set condition type statically in the form based on the `{% if %}` at 
https://github.com/Clinical-Genomics/scout/blob/a37be70719d8b133cb49b0870872eb0ba61d7a5e/scout/server/blueprints/clinvar/templates/multistep_add_variant.html#L204

Alternatively, for manual entry, we could parse the terms for CURIE prefix, and set the Condition type accordingly?

**Comment by dnil** [comment]
Right, good call!
