### ISSUE TITLE
Unselecting all IGV tracks gives unexpected default

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#3704]
![Screenshot 2022-12-06 at 14 54 57](https://user-images.githubusercontent.com/758570/205931087-b3d4831f-29a2-4711-b78b-d385d94bd9ae.png)
![Screenshot 2022-12-06 at 14 55 23](https://user-images.githubusercontent.com/758570/205931195-97173de4-9804-4930-9add-9a369129a7cf.png)

**Comment by northwestwitch** [comment]
I guess the issue is at this line: https://github.com/Clinical-Genomics/scout/blob/1f8456593066c2b997c632b2706300704e1005c4/scout/server/blueprints/alignviewers/controllers.py#L218
