### ISSUE TITLE
New GENS case name key for queries

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#3705]
Add a `case_name` with the case name to complement the earlier sample display name as a query GET parameter when linking out to GENS (case and SV variant page). Is display name or internal name intended, @raysloks? I'm guessing the easier way is internal id (pet name), as this is unique across all institutes.

**Comment by raysloks** [comment]
Yes, I had intended to use the pet name, but while implementing it in Gens I got it confused and used `display_name` instead. I think I'll update Gens to use the internal id, so perhaps `case_id` may be a better name for the parameter?
