### ISSUE TITLE
compound partner level filter

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#374]
Hi, 

sitting with the clinical genetics folks discussing scout and returned to an old issue - couldn't find it here though. We would very much like to be able to filter (or adjust rank) for strong compound pairs. We would like to be able to screen for variants where *both* fulfill criteria such as rare, nonsense or known pathogenic etc. See also https://github.com/moonso/genmod/issues/41
Either solving it pre-loading or post-loading is fine. Ability to filter on aggregate compound score might be enough? Then one could include the AR_compounds for a suspected AR-trio without being swamped with potential carrier variants..

Cheers!

// Daniel

**Comment by moonso** [comment]
Ok so this can be solved after we update the code in scout.
We need to know which are most preferable to filter on.
Combined score is fine, functional and regional should also be fine.
I guess that the frequencies are sort of embedded in the rank_score/combined_score. 

What do you think @dnil ?

**Comment by dnil** [comment]
Functional and regional is good! I still think freq and perhaps CADD would be wished for. While I agree on them being included in the combined score, it is somehow a little off right now. It doesn't reflect my sense of how causation occurs. E.g. even if one variant is very clearly causative (and perhaps should be the top AD candidate) the second one still normally needs to be causative for disease. Otherwise its just one more carrier status mutations, that we all carry a bunch of. 

Thresholds (filter) solves part of that. Perhaps a multiplicative or otherwise non-linear combination model would help as well?

 E.g. 

combined_AR_comp = score_var_A * score_var_B / normfactor

Or something like 

gated_AR_comp = sigmoid[ score_var_B > 10] * score_var_A + sigmoid[ score_var_A > 10 ] * score_var_B

where sigmoid[x>N] is some appropriate nonlinear function, gating to a high value for x > N and a near-zero or perhaps even a negative for x < N.

**Comment by dnil** [comment]
..or just "clinical filter" the other variant as well? That's an established threshold.

**Comment by moonso** [comment]
Right now this looks a bit problematic again but we will try to find a way..
