### ISSUE TITLE
Mitodel is not yet available for Solna users

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#3769]
Doesn't depend entirely on Scout, but I'll just drop it here for now!

**Comment by dnil** [comment]
This should now have been addressed in https://github.com/Clinical-Genomics/cg/pull/1714 (details here https://github.com/Clinical-Genomics/cg/issues/1586). Looks all good on stage. I have not seen it on prod yet, but if it should still be missing next week we a bit of reopening to do. 😄
