### ISSUE TITLE
Add mosaicism tag button

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/scout#377]

**Comment by henrikstranneheim** [comment]
Actually we need 2 buttons:

- Suspected mosaicism
- Validate/not_validated mosaicism

**Comment by moonso** [comment]
Button on what?

**Comment by henrikstranneheim** [comment]
On variant level to enable tagging of mosaicism that we see in the alignment view. This would enable tracking of true/false and suspected mosaicism in the entire dataset. Perhaps one should add them is a separate collection for faster retrieval.

**Comment by moonso** [comment]
Hmm I'm really not sure how this could be done, let's discuss on next meeting 26/4

**Comment by northwestwitch** [comment]
One unique variant can be mosaic or not

**Comment by 4WGH** [comment]
Hi, 
here come a suggestion about the mosaicism: where to locate it and possible comments

it is relevant to have this info for variants that are pinned and for which we annotate the SAnger validation. 
Have a look and please come with more comments. 

[mosaicism.pptx](https://github.com/Clinical-Genomics/scout/files/2123411/mosaicism.pptx)

**Comment by dnil** [comment]
Nice illustration! All those alternatives are not mutually exclusive, so a MultiSelect then!

**Comment by 4WGH** [comment]
Thanks!
feel free to correct my typos (sorrry for that!)
and even add more alternatives if you need :)
I've ordered the alternative with the more likely on top :)

**Comment by 4WGH** [comment]
can we add:
not visibile at reads inspection? (or something similar)
When I have a trio with a de novo I always cross check if I see a sign of mosaicism on the parents in IGV. it would be nice to have the possibility to register in scout that the check is done :)

**Comment by moonso** [comment]
Could @dnil or @northwestwitch take over this one?
