### ISSUE TITLE
Causatives page mixes in matching causatives

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#3771]
At some point it appears we started pulling matching causative onto the CausativeS page. Can be verified locally with e.g. two cases with the same variants.
![Screenshot 2023-01-18 at 20 38 26](https://user-images.githubusercontent.com/758570/213278114-7e3e1a76-33af-4b94-82b9-3722e5a4c19c.png)

**Comment by northwestwitch** [comment]
oh no, I'll fix!
