### ISSUE TITLE
Panel version update for fractional values

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#3779]
We currently update with an int(1) each version, but if the version in is already a float / semantic version-like tuple we should probably increment the lower fraction instead. The form validation also currently locks to integer increments from previous value; at the very least the user should be able to adjust or round a fractional number if relevant. Thank you @ehre!
<img width="612" alt="Screenshot 2023-01-26 at 14 06 51" src="https://user-images.githubusercontent.com/758570/214845504-df5f7f23-199f-427e-a4b0-0df4bdd6a630.png">

**Comment by northwestwitch** [comment]
Do we want to include a fix for this in the upcoming release?

**Comment by dnil** [comment]
It's not very urgent, but it is a kind of bug. I will try to get to rounding off the current PRs first. The causatives page is really in the need of getting it's patch out.

That gene panel gene comment edit and display is very tempting as well, but we should wait one more release with that.
