### ISSUE TITLE
Link to gnomAD SV from SV variant page

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#3788]
Seems the link is only produced for SNVs!

**Comment by dnil** [comment]
They are way too rare, I suppose due to their "quality filtering". But e.g. here:
https://scout.scilifelab.se/cust002/F0032106-Research/sv/variants/94e40fd57e433ff4efcd6afc80d036ce

**Comment by northwestwitch** [comment]
Another example, for testing on stage: https://scout-stage.scilifelab.se/cust000/F0009130-mip7/sv/variants/17ffc4567a660efab974bbd32bbe7d33
