### ISSUE TITLE
Removed gene panels still visible

### ISSUE THREAD

**Issue by ehre** [Clinical-Genomics/scout#3793]
Hi,

I'm not sure whether this may be a per-institute setting thing, but I'll start with reporting here. I noticed that deleted gene panels are still visible both on the variantS page (see screenshot) and also on the corresponding variant page (under "gene panels"). In this screen shot, all the panels "Utvecklingsstorning", "panelapp-intellectual-disability" and "panelapp-intellectual-disability-v3" were removed since long before this case was loaded into Scout, and none of those panels are visible in the Gene panels dropdown list on the variantS page.

![image](https://user-images.githubusercontent.com/12267779/216328143-f6fc9945-15a2-43de-9f29-b41bd5fb25e9.png)

**Comment by dnil** [comment]
I think you are very right - they still exist and we don't check if they are hidden in those tooltips!

**Comment by ehre** [comment]
And if I was not completely clear, the same thing here:
![image](https://user-images.githubusercontent.com/12267779/216330040-3da04b1e-9b9d-4df1-a5a8-b849a2fd6085.png)

**Comment by dnil** [comment]
And on the case general report as well I guess?

**Comment by ehre** [comment]
Dunno, don't use reports.

**Comment by dnil** [comment]
It doesn't look too bad, but there are a few things to do, e.g. also not including the hidden ones in the summed number. I think we will let it slip to after the 4.63 update after all, especially if you are anyway a safe few versions behind on updates, you will have several goodies to enjoy. 😄
