### ISSUE TITLE
Avoid using ClinVar apitest from Scout prod - redirect data from scout-stage to apitest

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#3795]
That corresponds to the preClinVar `dry_run` endpoint, not the `validate` one. 

They look the same to me but on their docs they say that the validate one should be used only for building the pipeline, not for testing each single submission.

**Comment by dnil** [comment]
Also we should probably switch to the validate one for stage submissions so we can test more freely if there are problems with the code!

**Comment by northwestwitch** [comment]
> Also we should probably switch to the validate one (corresponding to `/apitest/`) for stage submissions so we can test more freely if there are problems with the code!

I was thinking on ways to do this: how do you know that you are running a dev instance of scout from within the extensions?

**Comment by northwestwitch** [comment]
> > Also we should probably switch to the validate one (corresponding to `/apitest/`) for stage submissions so we can test more freely if there are problems with the code!
> 
> I was thinking on ways to do this: how do you know that you are running a dev instance of scout from within the extensions?

Perhaps, by adding the ClinVar submission URL in the scout config file. use the one that points to prod on scout prod and the testapi one for stage..

**Comment by northwestwitch** [comment]
> That corresponds to the preClinVar `dry_run` endpoint, not the `validate` one.
> 
> They look the same to me but on their docs they say that the validate one should be used only for building the pipeline, not for testing each single submission.

This apparently can't be done, because the dry-run endpoint doesn't return any usable SUB ID

**Comment by dnil** [comment]
> This apparently can't be done, because the dry-run endpoint doesn't return any usable SUB ID

Ok, then at least reality seems to conform to the current documentation, which is nice in its own way.

**Comment by northwestwitch** [comment]
This was solved by removing the validation when submitting to ClinVar step both on stage and prod (#3959). Closing
