### ISSUE TITLE
ACMG classification PVS1

### ISSUE THREAD

**Issue by KickiLagerstedt** [Clinical-Genomics/scout#3804]
Hi!

Could we integrate this link in the classification window?
http://autopvs1.genetics.bgi.com/

![image](https://user-images.githubusercontent.com/17139607/217245740-df33e01f-7168-4f5e-b388-d17817efcceb.png)

**Comment by dnil** [comment]
The code is open and available (https://github.com/JiguangPeng/autopvs1), so in theory one could arrange setting up a local version as well, but just adding the link is rather easy so let's start there and and see what the demand is like..

**Comment by northwestwitch** [comment]
I was thinking to work on this today. I'd rather use the working instance of the link you provided instead of creating and maintaining our own: one less service to take care of. 
Where do you want the link, IN the classification tool or somewhere in the variant page?

**Comment by northwestwitch** [comment]
@dnil  I've just realized that you assigned to this issue immediately before me. Never mind then, I can of course review!
