### ISSUE TITLE
ACMG classification criteria PS4

### ISSUE THREAD

**Issue by KickiLagerstedt** [Clinical-Genomics/scout#3805]
https://www.medcalc.org/calc/odds_ratio.php

Kanske även lägga till texten; "PS4 can be used as a moderate level of evidence if the variant has been previously identified in multiple (two or more) unrelated affected individuals, or as a supporting level of evidence if previously identified in one unrelated affected individual, and has not been reported in gnomAD."

![image](https://user-images.githubusercontent.com/17139607/217252361-4616f283-0116-4127-96b5-3b58253cdaad.png)

**Comment by dnil** [comment]
Not happy about the double use of gnomAD though - it would likely be in use in PM2?

**Comment by dnil** [comment]
Ok, right! Reading again, and I guess for the downgraded level it will good enough. Its all a matter of likelihood...
