### ISSUE TITLE
Managed variant filter next button resets filter..

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#3806]
After filtering with managed variants, the next page button clears filter and retrieves from the whole collection...

**Comment by northwestwitch** [comment]
I can work on this if you haven't started @dnil

**Comment by dnil** [comment]
I'm over at `loqusdb` at the moment, so feel free!

**Comment by northwestwitch** [comment]
I think the problem with this one is that even if the filter form fields get populated in the controller (using the request.form), they get a reset as soon as the data goes to the template. In fact there a lot of javascript going on on page load there.

Perhaps lets try to minimize the js
