### ISSUE TITLE
future idea: for re-runs

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#381]
when a re-run is uploaded all comments get a "OLD" label which is very good!
However it is not possible to see what is the difference between the previous run and the new.
it could be a new version of database, or a new assigment of affected or unaffected. it could be good  to know what has been changed.
Just an idea..... for future development  :)

**Comment by moonso** [comment]
Hi,

could you provide a list of things that you would like to see?
Then we can discuss which of these that we can display.

**Comment by 4WGH** [comment]
The reason for this it to make us able to see what the differences are between the different runs.
what I can immediately think about is :
 
1. database/panel version
2. if the assigment affected, not affected, or missing has been changed.
 
these 2 are the 2 major reason we ask for a re-run.
 
Maybe the rank score system could also appear.
 
 
 
 
 
 
Michela -----Måns Magnusson <notifications@github.com> skrev: ----- 

Till: Clinical-Genomics/scout <scout@noreply.github.com>Från: Måns Magnusson <notifications@github.com>Datum: 2016-12-14 14:50Kopia: MichelaBarbaro <michela.barbaro@karolinska.se>, Author <author@noreply.github.com>Ärende: Re: [Clinical-Genomics/scout] future idea: for re-runs (#381)
Hi,
could you provide a list of things that you would like to see?Then we can discuss which of these that we can display.

**Comment by 4WGH** [comment]
1. panel version
2. who was assiged as affected, unaffect or not specified (X)
3. MIP?
4. re-run after bug sovling (ex when some variants were missed out.

it would be good if other can help with what can be important to know.

**Comment by moonso** [comment]
Ok I moved stuff from here to #442 so lets continue the discussion there
