### ISSUE TITLE
IGV error, not loading data track

### ISSUE THREAD

**Issue by ielvers** [Clinical-Genomics/scout#3825]
Good morning! 
I'm getting an error message in IGV, and it's not loading data tracks. Same message in two different cases, and both for SNVs and SVs (except RandomSeed value differs). This is the message:

![image](https://user-images.githubusercontent.com/57791644/221117022-837883fe-190e-4564-887e-7b5f8b112ed0.png)

**Comment by dnil** [comment]
Good morning! The most likely explanation is that your computer has moved between networks in an unlucky fashion. It should resolve with logging out from Scout and back in again. IGV.js for cram files is working fine over on my end, so do shout if it persists!

**Comment by dnil** [comment]
I closed this as we have seen it before, but please just reopen if you still encounter problems after logging back in (and perhaps making sure your network is configured as per usual).
