### ISSUE TITLE
View Sanger order without canceling

### ISSUE THREAD

**Issue by ielvers** [Clinical-Genomics/scout#3826]
Hi,

For a variant where Sanger verification has been ordered, if I press the "Sanger pending" button I cannot close the info box without canceling the sanger order. There are three ways to close the info box - "Send Sanger cancel request", "Close", or the little "x" in the top corner. Clicking on either of these cancels the Sanger order. I think in the past "Close" did not send a cancel request? 

I noticed that by clicking outside the info box it closes without canceling Sanger. But I think if there was a more obvious way of just closing the info box, less accidental Sanger verification cancellations would occur.

Thank you!

**Comment by dnil** [comment]
Thank you - sounds like a plan!
