### ISSUE TITLE
case and global comment in general report are not diffentiated

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#3827]
Hi, we have just noticed that in the pdf general report the comments at the variant level are not differentiated if they are at the case level or it is a global commnet. 
This can be confusing. 

see ex in fam F0026209-4, variant in ABCA4.

**Comment by dnil** [comment]
Ah, yes, at some point we had like a badge with `global` for the global ones. Perhaps we can try to make sure that appears at all relevant comments? In a way, one would like to choose wether to include the global ones or not, but that makes for a rather complicated interface to use.
