### ISSUE TITLE
ClinVar last sub not closing and sort order

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#3828]
I just had the experience of the new submission created not closing on successful submission. The seemingly new submission was also sorted as older than the last submitted one on the clinvar submissionS page. I guess this is partly related to #3787, but it seems there are also situations where the close-current-open-and-make-a-new strategy does not work. See https://scout.scilifelab.se/cust002/clinvar_submissions, where 63f8c5bb6484f8d15a5f18b1 was created last, and is actually submitted, while it shows later in the list and still as `open`.

**Comment by northwestwitch** [comment]
Once the submission is sent it is marked as `submitted` and becomes green, so the behavior (it is not closed and doesn't become gray) is intended. I made it like this to distinguish from the submissions that are closed but unfinished (some other used in the same institute, a a distinct list of variants to be processed later, etc).
But the behavior of 63f8c5bb6484f8d15a5f18b1 is weird, I'll check. And I'll also create a better sorting!

**Comment by northwestwitch** [comment]
So far I haven't found a reason why 63f8c5bb6484f8d15a5f18b1 is closed instead of submitted. @dnil are you 100% sure that it wasn't submitted and then it was closed manually?

**Comment by northwestwitch** [comment]
Would have been useful to register associated events, but where do you visualize them?

**Comment by dnil** [comment]
> So far I haven't found a reason why 63f8c5bb6484f8d15a5f18b1 is closed instead of submitted. @dnil are you 100% sure that it wasn't submitted and then it was closed manually?

Yes, on my side, but in theory someone else could of course have closed it in parallel. But if it seems to work with a bit of nonlinear close, submit and open, we can leave it for now and try to pinpoint the issue later. Could have been some unfortunate edge case.

**Comment by northwestwitch** [comment]
In my PR I've ordered the submissions to have the submitted ones on the bottom. That would help preventing someone opening and closing it again by mistake

**Comment by northwestwitch** [comment]
Closing this now, as #3831 should have fixed it. but let's reopen if it's not the case
