### ISSUE TITLE
Edit and update time on comments

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#3833]
Avoid this 
<img width="419" alt="Screenshot 2023-03-01 at 09 26 23" src="https://user-images.githubusercontent.com/758570/222084807-8129ae14-6b8e-4b55-9d6a-f54fbfc4c97d.png">
which leads to `EDITED` being flagged way to often on comments.

**Comment by northwestwitch** [comment]
Ah it's the same?

**Comment by dnil** [comment]
Almost... 'now()' was called twice for the same event. I'll drop a PR, just need to finish something else! 😅
