### ISSUE TITLE
Deprecation warning: pkg_resources is deprecated as an API #20

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#3844]
We use it in the demo folder to to build the path to the demo files. Here is a migration guide to fix the problem -> https://importlib-resources.readthedocs.io/en/latest/migration.html#pkg-resources-resource-filename

**Comment by dnil** [comment]
Good time to fix https://github.com/Clinical-Genomics/scout/issues/1394. 😊 Doesn't have to be in the same PR, just conceptually related as the demo is one of the things suffering relative path start issues.
