### ISSUE TITLE
specific gene coverage not coming up

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#385]
Hi. I can not get the coverage for the OPLAH gene in fam 16149. The coverage for GSS gene is working.
A bug?

I click on the gene name in the panel list to get the coverage.

Thank for help,
Michela

**Comment by 4WGH** [comment]
Hi!
I need the coverage for this gene to be able to write the patient answer. Can I have a time extimation for the solving of this bug?
Or do I need to make a ticket?
Thanks
Michela

**Comment by henrikstranneheim** [comment]
Solved by rerunning with new version of Scout.
