### ISSUE TITLE
Retrieving stored DNA

### ISSUE THREAD

**Issue by MUebe** [Clinical-Genomics/scout#3853]
Hi!
I know this is not a Scout issue, but we are wondering if it is possible to retrieve some of the saved DNA that has been sent for sequencing previously. Not sure who is the best person to ask. We are thankful for any help!
Regards,
Malin

**Comment by northwestwitch** [comment]
Hi Malin, I think it would be best if you open a ticket in our support system: https://clinical-scilifelab.supportsystem.com/scp/login.php

Hope it helps!
