### ISSUE TITLE
Replace code that downloads genes, exons and transcripts from Ensembl with schug lib

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#3856]
We now have a dedicated repository to take care of these downloads: https://github.com/Clinical-Genomics/schug

We can replace big chunks of code in scout with just a few lines.

It is either downloading the files from a schug instance: https://schug-stage.scilifelab.se/docs or installing schug as a lib and using it inside scout (it is on PyPI).

I prefer the second option because this way all other facilities using scout would not be forced to deploy schug themselves or ask us to open our instance to them for updating those collections

**Comment by northwestwitch** [comment]
Removing the blocked tag as schug is now using pydantic2 (chanjo2 is fine for now because of frozen dep in poetry.lock file

**Comment by dnil** [comment]
> chanjo2 is fine for now because of frozen dep in poetry.lock file
😅
