### ISSUE TITLE
Can not dismiss structural variant on first page anymore...

### ISSUE THREAD

**Issue by KickiLagerstedt** [Clinical-Genomics/scout#3859]
Works still om SNV 
![image](https://user-images.githubusercontent.com/17139607/226540188-a161f5eb-95d5-40eb-b1ce-e52c6125d74d.png)
view

https://scout.scilifelab.se/cust002/F0052195/sv/variants?variant_type=clinical&gene_panels=hpo

**Comment by northwestwitch** [comment]
Ah I see, the option to restore the dismiss bar is hidden in the variants filters view for SVs. Try opening the filters window and select "Toggle dismiss bar", on the right bottom corner of the filters view:

<img width="287" alt="image" src="https://user-images.githubusercontent.com/28093618/226541552-de2c0cf2-4d8d-445f-9628-01a08c271376.png">

We'll make it more visible, sorry!

**Comment by dnil** [comment]
Oopsie, it seems it is being reset on SV page reloads. My bad I guess, sorry! Will fix!
