### ISSUE TITLE
Gene(s) field not so visible on SV variantS page

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#3861]
<img width="747" alt="image" src="https://user-images.githubusercontent.com/28093618/226558541-1fbf2b49-1edb-46ad-80a2-2ba4c6e7d5c3.png">

**Comment by dnil** [comment]
Looks good here! 😊 

![Screenshot 2023-03-21 at 10 05 43](https://user-images.githubusercontent.com/758570/226560392-7593ee6c-e4c2-4ec0-9b1a-72d05c3cd558.png)

**Comment by northwestwitch** [comment]
> Looks good here! 😊
> 
> ![Screenshot 2023-03-21 at 10 05 43](https://user-images.githubusercontent.com/758570/226560392-7593ee6c-e4c2-4ec0-9b1a-72d05c3cd558.png)

From the dark side everything looks good!
