### ISSUE TITLE
Safe variant matching does not work as (we) intended

### ISSUE THREAD

**Issue by ehre** [Clinical-Genomics/scout#3873]
It seems that we misunderstood each other when it comes to the feature "safe variant matching" (#3611 #3428 ). Our intention (my own and @SofieCMD Sofie Samuelsson's) was that on a **case-level basis** only see matching causatives and managed variants that are included in the selected gene panel/s. So, for instance, if we run a case with the Epilepsy panel selected, we would only see matching causatives from within the Epilepsy panel but not from the Cardiomyopathy panel. The functionality now seems to be that on the **institute-level** for all cases only show matching causatives from selected panels. We don't really see the need for this functionality, we run all our RD WGS cases in the same institute so we will need pretty much all genes (at least all OMIM-AUTO + PanelApp Green genes) to display matching causatives on the institute level. Comments, thoughts?

**Comment by northwestwitch** [comment]
I understand what you mean. When I worked on the feature I had the feeling that our users here in Stockholm were open to see variants from panels (not too) different from the ones used for running the analysis. For instance seeing other RD-related panels but not the cancer ones for an institute with RD cases. But I might be wrong? I don't know. Did we have any feedback on this from customers at @dnil?

**Comment by northwestwitch** [comment]
We can always add another layer of safe matching where the user chooses safe matching based on the case panels.

**Comment by dnil** [comment]
Hi! We have not heard much really after the issues leading to the feature. It was well received on introduction but I don't think it is being used for very many institutes yet.

I think I still have a bit of trouble visualizing your use case. For any given case, the variants on panels the case was run with would be visible on the variants lists anyway? So much as here, you actually select panels a little bit out of routine, having e.g. PanelApp Green or OMIM which might bring an unintended matching causative? I don't quite see how we could arrange a feature for a given case the end result would be different from what you already have with deciding if you want to look at the matching causatives? 

From the sound of it, perhaps dividing work into different institutes might be an option for you? It does get crowded with all cases eventually anyway. The local use-case is for especially marking some panels that we feel we have local expertise on and are ready to assess variants in. So the hereditary cancers can then be on one institute, eg with a set of panels from different cancer syndromes allowed to safely match. And cardiology cases can be on another, perhaps with a set of general neuromuscular and metabolic panels that are allowed to safely match. But neither would then show up as matching causatives in the pther institute.

Ok, but if we would try to help you without you using different institutes. You can already choose to ignore matching causatives, but you do not so you need something from it. How about a function for showing matching causatives only from the default panels? I still hope those variants would be super evident when triaging the default panels, but I guess for weird synonymous or intergenic variants it might be good?

**Comment by northwestwitch** [comment]
> I think I still have a bit of trouble visualizing your use case. For any given case, the variants on panels the case was run with would be visible on the variants lists anyway?

I think it's more like that they want to be sure not to see any other panel except those used in the case, because now they see all those that are selected for the institute, and could be that somebody edits these institute safe panels without them knowing.

**Comment by ehre** [comment]
Yes, well. The situation we are leaving is that **all** matching variants in **any** gene are visible on **all** cases. So to follow @dnil 's line of thought that we only need to "look in the variant list" would of course be a possibility - if we completely disabled the function of displaying matching causatives. I still think that from a convenience and safety perspective it would be nice to see a relevant matching variant already on the case page. Of course I agree that a variant with high rank score (as is typically the case) would be hard to miss, but a lower ranking variant (such as the ones we now have as managed variants) might be less obvious.

Finally, I think it would be rather difficult to do "phenotype based institutes" as you suggest, too many overlaps between different phenotype groups to be practical, I would say. We already run main stream hereditary cancer in a separate institute, but that's mainly because we analyze these on a KAPA-Twist panel and not WGS currently.

**Comment by dnil** [comment]
Ok, I still don't quite get it, but that that doesn't mean we can't fix it so you get something you feel comfortable working with.

The issue presumably at some level goes back either to the prior on how likely one believes it is that a variant is actually causative regardless of the observed phenotype, or possibly to how important one feels it is to get that information.

Anyway, looking back to your wishlist above, how about we implement `1. "Only see matching within selected gene panel/s"` with a separate new feature.

`2. Open up to "similar panels"` would require a definition of similar panels, and is arguably possible to start implementing by separate institutes, or by initially using 1. and manually adding more default panels. Both 
at least for a small number of panels. 

`3. If needed: Completely open analysis` should rather correspond to the current state with Safe filtering turned off.
