### ISSUE TITLE
No SCORE annotation on variants

### ISSUE THREAD

**Issue by KickiLagerstedt** [Clinical-Genomics/scout#3874]
https://scout.scilifelab.se/cust002/F0052391/variants

**No SCORES what so ever - not on SNV or SV....**

**Comment by dnil** [comment]
Hi, I think this might be a case for Orderportalen or the general Support! The case has no affected individual indicated as of loading time, and as there are no scores I'm kind of guessing it was the same when it went through MIP/GenMod. So, likely at the order stage?

**Comment by KickiLagerstedt** [comment]
OK!
