### ISSUE TITLE
Unable to download cgh-file

### ISSUE THREAD

**Issue by KickiLagerstedt** [Clinical-Genomics/scout#3877]
Tried several cases....

![image](https://user-images.githubusercontent.com/17139607/228467985-10eed855-5cf3-4791-8e4c-ad0729b7700b.png)

**Comment by henrikstranneheim** [comment]
In Sthlm the VM hosting the Scout web instance is experiencing issues with the network and some database processes. We have alerted IT and they are looking into it. They have not yet responded with  a cause and a time table

**Comment by KickiLagerstedt** [comment]
Same reason why we can not make the general report? (pdf)

![image](https://user-images.githubusercontent.com/17139607/228475191-9fb4bc8a-4e18-43b2-8216-f76972bf7231.png)

**Comment by northwestwitch** [comment]
> Same reason why we can not make the general report? (pdf)
> 
> ![image](https://user-images.githubusercontent.com/17139607/228475191-9fb4bc8a-4e18-43b2-8216-f76972bf7231.png)

Yes, it's due to the same problem, this specific issue is happening because the PDF version of the report contains also the coverage data, but the database containing the coverage data is down at the moment.

**Comment by dnil** [comment]
You can still dl the html version of the general report (the "link" symbol on the left) and print a pdf from it, but it will be without coverage data until the coverage data server is back.

**Comment by dnil** [comment]
Ok, should be good now. Sorry, and good luck!
