### ISSUE TITLE
coverage report -> server error

### ISSUE THREAD

**Issue by ielvers** [Clinical-Genomics/scout#3878]
Hi,

I'm getting a server error when I try to open coverage reports, "500 Internal server error". General analysis report looks fine, but when I click "download pdf" I get the same server error (if I download it without opening it first it looks just fine).

Thank you,
Ingegerd

**Comment by henrikstranneheim** [comment]
In Sthlm the VM hosting the Scout web instance is experiencing issues with the network and some database processes. We have alerted IT and they are looking into it. They have not yet responded with a cause and a time table

**Comment by ielvers** [comment]
Thank you! :)

**Comment by dnil** [comment]
Ok, looks good now on our end! Thank you to @henrikstranneheim and IT!
