### ISSUE TITLE
add `SOMATICSCORE` for SVs 

### ISSUE THREAD

**Issue by khurrammaqbool** [Clinical-Genomics/scout#3883]
The `VCF` for SVs contains `SOMATICSCORE` computed by manta for tumor-normal cases. It would be nice to have it as a list in the structural variants view in scout.

**Comment by dnil** [comment]
Hm, at the very least it should be loaded and shown on the variant page. It is one caller, and if it was super interesting they kind of could have opted to weigh it into QUAL. But we know a couple of the users do like it!
