### ISSUE TITLE
flag variants with polymorphism in the same codon?

### ISSUE THREAD

**Issue by ielvers** [Clinical-Genomics/scout#3886]
Would it be possible to flag variants where there is another variant affecting the same codon, but this other variant may be a common polymorphism that is not called?
Example case 23109, variant https://scout.scilifelab.se/cust003/23109/d4f81bb9cc7e1fb457a11ea77cda3751
This is called as a Pro -> Ser mutation but due to the common polymorphism next to the called variant, it actually becomes a stop variant.

**Comment by dnil** [comment]
Hi @ielvers! Yes, this is usually referred to as MNV-calling, and generally requires phasing variants to account for alleles on different chromosome copies. Its been on the agenda for some time (see e.g. https://github.com/Clinical-Genomics/scout/issues/1435), but never made it to high prio. The latest call was that we don't do this with MIP but add it to the nf-core/raredisease wishlist.

**Comment by ielvers** [comment]
Thank you!

**Comment by dnil** [comment]
Closing this as duplicate, but its great that you report it - it helps build the case for that it should really be added.
