### ISSUE TITLE
Inefficient db queries makes /institutes slow to load

### ISSUE THREAD

**Issue by mhkc** [Clinical-Genomics/scout#3897]
The `/institutes` view in Scout takes several seconds to load which is likely caused by inefficient query design.

To build up the view Scout

1. Query the user collection to get which institutes the logged-in user has access to
2. For each institute query the case collection for all cases belonging to the institute
3. [Iterate over each resulting case to count the number of cases](https://github.com/Clinical-Genomics/scout/blob/c91a7b7a7317e2778f5cd6fe8b9604c4679c1294/scout/server/blueprints/cases/views.py#L56)

Each query conducted with `store.cases(collaborator=institute_obj["_id"])))` takes roughly 300 ms so the query time glows rapidly as the user has access to more institutes.

**Suggested solutions**

I suggest that we either modify `store.cases` to accept kwargs for data projections so we can use a covered query instead. By using a covered query mongo wouldn't need to read documents from disk which are likely to speed up the query and reduce the amount of data being returned and casted into python types.

Another solution would be to add a collection of aggregated data that are rarely updated. Keeping track of the number of cases per institute could be done when data is added and removed from the database. With this solution, there wouldn't be any need to continuously compute a number that rarely changes every time a user logs in or goes to `/institutes`

**Comment by northwestwitch** [comment]
As I mentioned in our chat I don't find the loading of institutes super slow with our scout, in comparison with other pages, (like variantS for instance) at least, but it could be because I am a system admin and the case filtering is different in that case. I'll try to change my user as a non-admin and add myself as a collaborator of many institutes!

**Comment by northwestwitch** [comment]
How many institutes with how many cases are we talking about @mhkc?

**Comment by mhkc** [comment]
The page takes 11 seconds to load with 16 institutes and a total of 7610 cases

**Comment by dnil** [comment]
You need more institutes and cases then! Its like 5s with >2-3x the cases and ~100 institutes. 😉 


What version of mongodb are you on? Wondering if that compound index might be doing something odd on other versions?

**Comment by dnil** [comment]
If that's it I guess no-one will be sad if we just make a new index on `owner` instead of collaborator. Counting from that should be near instant?

**Comment by northwestwitch** [comment]
I'm working in some code fix. I just want to try if it makes a difference.
