### ISSUE TITLE
External link doesn't work anymore in Cancer Scout

### ISSUE THREAD

**Issue by christacosta** [Clinical-Genomics/scout#3911]
Hello, in cancer Scout the external links to the database "Protein paint" aren't working anymore, it seems like the webpage has changed something. See e.g. KRAS variant in case F0053035:

https://scout.scilifelab.se/cust087/F0053035/cancer/92bd5915df201b20193413814afb1190?cancer=yes 

OLD link: https://pecan.stjude.cloud/proteinpaint/KRAS - "The page you are looking for does not exist."

NEW link (to the whole gene) https://pecan.stjude.cloud/variants/protein-paint?gene=KRAS

We also used to get the link to the exact variant in the RefSeq transcripts table if there are entries of that variant in the database.

**Comment by dnil** [comment]
Thanks a bunch - will fix the gene link!

I don't recall protein paint links for specific variants; TP53, Varsome, Mutalyzer, cbioprotal and mycancergenome are the ones we have on the RefSeq transcript table. Do you happen to know if the stjude have an API for their service somewhere? The "variant search" seems to operate mostly by selecting known variants from a list in the search field, or knowing their id number>

**Comment by christacosta** [comment]
Great, thanks!

Ah acutally I might have gotten them confused, it's cbioprotal that has the variant specific link :D
