### ISSUE TITLE
Institutes without cases are not shown on institutes page

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#3920]
Demo instance of scout with an admin user, if you create an institute named inst001, it DOESN'T show on the instituteS page:

<img width="1435" alt="image" src="https://user-images.githubusercontent.com/28093618/234799552-e50b4a3f-d6cd-446f-8a38-1280af76f1de.png">

But it's there:

<img width="847" alt="image" src="https://user-images.githubusercontent.com/28093618/234799607-7f77f6c5-f589-4e64-aef2-3c15c5e5ec78.png">

**Comment by dnil** [comment]
Ah, yes. Pros and cons - we could do the same as for the different case caregories and show also when there are 0 vases. But it also makes some sense as is to not swamp the list with unused institutes.
