### ISSUE TITLE
Rank model version missing from rank scores on causatives page and exports

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#3933]
We used to have them, so guessing they are mostly lost in refactoring.
<img width="116" alt="Screenshot 2023-05-09 at 16 14 46" src="https://github.com/Clinical-Genomics/scout/assets/758570/9d9017ef-2430-4583-9dcd-77983945e644">

**Comment by northwestwitch** [comment]
Oh no, since when I wonder! I can look into it!
