### ISSUE TITLE
cyVCF2 0.30.20 

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#3940]
![Screenshot 2023-05-17 at 09 40 09](https://github.com/Clinical-Genomics/scout/assets/758570/b2dfc30e-938f-49af-a893-3d136dc57e12)

Freshly released cyvcf2 does not build cleanly on GitHub actions. We are actually relying on a wheel build for the current version, 0.30.18 (0.30.19 was never released to pypi), so could well be that the build as such hasn't been working for a little bit.

**Comment by dnil** [comment]
Frozen in #3918 for tests..

**Comment by northwestwitch** [comment]
Perhaps we could have a PR for fixing it, so all PRs will have working tests!

**Comment by dnil** [comment]
Can do. But surely that small MEI PR will be merged soon.. 

It's not important with that PR being perfect wrt the new data, more that they are there and we don't break anything in the process.

**Comment by dnil** [comment]
Wheel version of 0.30.20 released; nothing to do here! 😁
