### ISSUE TITLE
Request: ClinVar API key in institute settings

### ISSUE THREAD

**Issue by ehre** [Clinical-Genomics/scout#3943]
We would like to be able to save our ClinVar API key in a per-institute setting, so all users within the institute will be able to submit to ClinVar without manually entering the API key.

**Comment by dnil** [comment]
Makes sense: I think we would then introduce a role allowing this, similar to patientmatcher access. We have quite a few users for each institute.. 😊

**Comment by northwestwitch** [comment]
User roles are personal for patientmatcher and it's very doable. Would it work for us in Stockholm to have one single API jey for the whole institute?

**Comment by dnil** [comment]
For each institute, yes, I would think so, but we would prefer a role to allow coordination of effort.

**Comment by ehre** [comment]
I don't know. So is your policy in Stockholm that every single user should apply for their own API key? I'm not sure that's what the ClinVar staff intended?

**Comment by northwestwitch** [comment]
> I don't know. So is your policy in Stockholm that every single user should apply for their own API key?

I don't think we have a clear policy yet, it depends on the group I guess.

On the ClinVar side, they recommend to create a submitters group for your institution: https://www.ncbi.nlm.nih.gov/clinvar/docs/submitter_groups/

It's not specified but I guess each submitter of your institution gets a different key (otherwise why having collaborators in a group in the first place?)

**Comment by ehre** [comment]
Ok, thanks. Since I have an active dialogue with ClinVar on this matter, I asked them if they have any expectations about per-user vs per-group API keys. I'll get back to you when I have received a reply.

**Comment by dnil** [comment]
Good. I expect they would want one key per many users, but I have been wrong about their intentions before. I created a new account with the scilifelab invite @northwestwitch but I can't retrieve the current key (sign esnGvD...). I do however have the option to get a new key for the service account, and it simply made a new one (N4x6FP...) without invalidating the old one. Meaning they could in practice work as personal keys, but it is very much up to the users to maintain it as the keys are not directly user linked.
