### ISSUE TITLE
Remove validation buttons in ClinVar API submission form

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#3947]
At the same time make sure that any error returned from the submission process is clearly shown in Scout (to fix the submission and resubmit it correclty)

**Comment by northwestwitch** [comment]
I'm working on this and it's not working, then I released that preClinVar is down. I wonder since when!

**Comment by dnil** [comment]
Hm, perhaps some aftermath of the downtime last week?

**Comment by dnil** [comment]
But, preClinVar shows as up on cg-prod-services?

**Comment by northwestwitch** [comment]
I can't reach from here: https://preclinvar.scilifelab.se/docs

**Comment by northwestwitch** [comment]
Oh, then it must be my VPN, thanks!

**Comment by dnil** [comment]
It might have some problems but its not entirely down!

**Comment by northwestwitch** [comment]
> Oh, then it must be my VPN, thanks!

Yes, I get some warnings about misconfiguration from Tunnelblick, I'll fix. Thank you!
