### ISSUE TITLE
Failing to load HPO coverage report

### ISSUE THREAD

**Issue by MUebe** [Clinical-Genomics/scout#3957]
Good morning,
I have been trying repeatedly to download the coverage report of the HPO-panel for happygator.
It always ends in timeout, same for my colleague.
Any ideas why this could be happening? The reports for the default panels work fine.
Kind regards,
Malin

**Comment by dnil** [comment]
Interesting; I see the same thing. We'll investigate!

**Comment by dnil** [comment]
The same HPO panel (polymicrogyria, 191 genes) also works fine for a demo trio. Something particular with some of the genes in some of these individuals. I would tentatively suggest we ask support to re-upload the case to chanjo and see if the issue persists?

**Comment by MUebe** [comment]
Does that mean "order a rerun"? (no idea what chanjo is)

**Comment by dnil** [comment]
Try writing to supportsystem@clinicalgenomics.se or use the ticket interface at https://clinical.scilifelab.se! They may ask you to do just that, but if all case files are still up it might be just as easy for them to manually delete and redo the chanjo entries for the case.

[Chanjo](https://chanjo.readthedocs.io/en/latest/) is the coverage calculation system we use. You interact indirectly with it when you ask for a coverage report in Scout, via [chanjo-report](https://github.com/Clinical-Genomics/chanjo-report).

**Comment by MUebe** [comment]
I'll give that a try!

**Comment by dnil** [comment]
Great! Please reopen or at least let us know if this persists and we'll try to help figuring it out.
