### ISSUE TITLE
Something is off with at least the structural variants total counts

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#3967]
Plus somatic dito. Checked around a bit on stage and a found a few NA or incorrect counts. Could "just" be some old case compatibility issue; I have not seen it on recent prod cases.

![Screenshot 2023-05-31 at 16 32 45](https://github.com/Clinical-Genomics/scout/assets/758570/ffdebe73-b5b0-4180-9e69-7c93d9bdc7d5)
![Screenshot 2023-05-31 at 16 42 26](https://github.com/Clinical-Genomics/scout/assets/758570/f1171406-110b-4ca2-a0d8-8fde6ad4b74b)

**Comment by northwestwitch** [comment]
I remember we had this issue with variant counting: https://github.com/Clinical-Genomics/scout/pull/2669

I wonder if we are counting the new MAI variants.. Perhaps not!

**Comment by northwestwitch** [comment]
I'll look into it!

**Comment by northwestwitch** [comment]
This case was uploaded recently and shows the problem: https://scout-stage.scilifelab.se/cust000/SWEDAC-2019-HG-05-Trio-NovaSeq

Let's tag it as a bug!

**Comment by dnil** [comment]
Yes, in that one it does appear quite a bit like the counts for MEI type variants was never done explicitly.

**Comment by dnil** [comment]
But again, it looks all good and comfy for recent uploads to prod. Either a new one, or perhaps something with the case upload functions? Like not recounting properly on reload with new variant types added?
