### ISSUE TITLE
Gene variants view missing region, function annotation, HGVS c.

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#3972]
From prod gene variants:
![Screenshot 2023-06-01 at 13 30 47](https://github.com/Clinical-Genomics/scout/assets/758570/5b386c8d-2bbf-4087-b78f-53894c0558cb)
Some shared population routine that has changed perhaps? Not 100% we had HGVS c, but almost - it would not have made sense with showing splice variants otherwise.

**Comment by northwestwitch** [comment]
Since we are touching that code, let's round cadd scores in the column nearby:

<img width="550" alt="image" src="https://github.com/Clinical-Genomics/scout/assets/28093618/a68b6836-2614-4352-bea8-d8ec72d119eb">
