### ISSUE TITLE
ClinVar API added keys (combined issue with preClinVar)

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#3973]
> Thank you for using the ClinVar Submission API! In early June, we will make some changes to the API submission schema to accommodate some enhancements to submission:
> 
> We will add an attribute, multipleConditionExplanation, for the TraitSetType. This attribute will be required when the trait set has more than one condition. Options will be:
> 
> Uncertain: this indicates that the variant classification is for several related diseases, possibly a spectrum of disease, and you may be uncertain if the variant is associated with only one or more of the diseases.
> Novel disease: this indicates that the variant classification is for a novel disease that is unnamed and only defined by a set of clinical features.
> Co-occurring: this indicates that the variant causes a combination of distinct diseases; this scenario is expected to be rare.
> For more details, please see the updated schema at https://ftp.ncbi.nlm.nih.gov/pub/clinvar/temp/schema/submission_api_json_schema_public.json.
> 
> We expect this update to occur no later than June 8. We will update the announcement banner on the ClinVar Submission Portal web site to indicate the date of this release.

**Comment by dnil** [comment]
This is now active, and becomes a bug when users try to submit cases with more than one condition - or most saliently multiple HPO terms. We should introduce the option, and probably add a message to the user suggesting to add a single, know Disorder term (OMIM or alt medgen or Orphanet).

**Comment by northwestwitch** [comment]
Let's close this one as well
