### ISSUE TITLE
New HPO phenotypes release 2023-06-06 

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#3978]
https://github.com/obophenotype/human-phenotype-ontology/releases/tag/v2023-06-06

**Comment by dnil** [comment]
Good timing; let's update with 4.69. We anyway need to update the CLI with this one.

**Comment by northwestwitch** [comment]
I'm going to test the database updates now!

**Comment by northwestwitch** [comment]
Latest release on hasta stage:

<img width="365" alt="image" src="https://github.com/Clinical-Genomics/scout/assets/28093618/e8850255-782a-4eff-a832-10da142cbabe">

## Download files for updating:

`scout --config /home/proj/stage/servers/config/hasta.scilifelab.se/scout-stage.yaml download everything --api-key xxxxxxx`

## Update HPO terms

`scout  --config /home/proj/stage/servers/config/hasta.scilifelab.se/scout-stage.yaml  update hpo --hpoterms hpo.obo --hpo-to-genes phenotype_to_genes.txt`

<img width="740" alt="image" src="https://github.com/Clinical-Genomics/scout/assets/28093618/c0c66416-5599-42af-a74f-de34b41e5a34">

## Updating OMIM diseases terms

`scout  --config /home/proj/stage/servers/config/hasta.scilifelab.se/scout-stage.yaml  update diseases -f .`

<img width="864" alt="image" src="https://github.com/Clinical-Genomics/scout/assets/28093618/e907d287-5283-49c9-8495-b7619f6407f1">

## Updating genes

`scout --config /home/proj/stage/servers/config/hasta.scilifelab.se/scout-stage.yaml  update genes -f .`

<img width="599" alt="image" src="https://github.com/Clinical-Genomics/scout/assets/28093618/3207b1fb-5f87-4034-94fd-fb97fb68251a">


## Update the OMIM-AUTO panel

`scout --config /home/proj/stage/servers/config/hasta.scilifelab.se/scout-stage.yaml  update omim --institute cust002 --genemap2 genemap2.txt --mim2genes mim2genes.txt`


<img width="895" alt="image" src="https://github.com/Clinical-Genomics/scout/assets/28093618/be7518a4-6378-4c42-8b73-dbd132daf9ce">

OMIM panels is saved with yesterday's date - but fine, I guess

<img width="619" alt="image" src="https://github.com/Clinical-Genomics/scout/assets/28093618/eaaa370e-ab55-432c-b2ad-d34f58bb0924">

## Update the PanelApp green genes panel

`scout --config /home/proj/stage/servers/config/hasta.scilifelab.se/scout-stage.yaml update panelapp-green -i cust002 --force`

<img width="892" alt="image" src="https://github.com/Clinical-Genomics/scout/assets/28093618/d53b79a9-9e80-4347-98ab-b2e37878e629">

**Comment by northwestwitch** [comment]
# Prod updates

## Update HPO terms

`scout update hpo --hpoterms hpo.obo --hpo-to-genes phenotype_to_genes.txt`

<img width="765" alt="image" src="https://github.com/Clinical-Genomics/scout/assets/28093618/256c87bd-60ec-4681-87c5-cb40df80b412">

## Updating OMIM diseases terms

`scout update diseases -f .`

<img width="855" alt="image" src="https://github.com/Clinical-Genomics/scout/assets/28093618/29b59c03-8b79-48a8-8196-451b91f56743">

## Updating genes

`scout update genes -f .`

<img width="773" alt="image" src="https://github.com/Clinical-Genomics/scout/assets/28093618/262f9e2d-18af-480d-8ced-ce426d5975ee">

## Update the OMIM-AUTO panel

`scout update omim --institute cust002 --genemap2 genemap2.txt --mim2genes mim2genes.txt`

<img width="933" alt="image" src="https://github.com/Clinical-Genomics/scout/assets/28093618/9c6989de-83bf-42c5-a23d-ff439fdda3a2">

## Update the PanelApp green genes panel

`scout update panelapp-green -i cust002 --force`

<img width="982" alt="image" src="https://github.com/Clinical-Genomics/scout/assets/28093618/9f568e61-e786-4638-a112-2a9247857c80">
