### ISSUE TITLE
OMIM-AUTO panel gets saved with yesterday's date

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#3986]
I've updated it now but looks like it was done yesterday:

<img width="551" alt="image" src="https://github.com/Clinical-Genomics/scout/assets/28093618/2b83d3dc-b534-4316-956b-ff865a5c5750">

**Comment by dnil** [comment]
Yeah, I think we've had this issue before. If I recall correctly, we use the last update date of the actual OMIM data dump, which is like a nightly for them. I sort of like this: we could just synk with their schedule, or not worry. 😊

**Comment by northwestwitch** [comment]
AH yes, now I remember. Closing! :)
