### ISSUE TITLE
Feature request - Upload of RNA bam to WGS cases

### ISSUE THREAD

**Issue by karlnyr** [Clinical-Genomics/scout#3990]
After a discussion with one of the users of Scout to day I got the message that in order to view the BAM file they have to go through their assigned bioinformatician to get hold of the delivered bim file for a case. They suggested that the associated bam file could be visualized in Scout in the same view as the Sashimi plot as they are more than likely viewing the bam in those regions anyway.

**Comment by northwestwitch** [comment]
> After a discussion with one of the users of Scout to day I got the message that in order to view the BAM file they have to go through their assigned bioinformatician to get hold of the delivered bim file for a case. They suggested that the associated bam file could be visualized in Scout in the same view as the Sashimi plot as they are more than likely viewing the bam in those regions anyway.

That'd be on the WTS cases and not the WGS/WES cases right?

**Comment by dnil** [comment]
No, it's both really, since we usually dont upload WTS only if we have WGS DNA to link the RNA data with. 
We only load the splice track and coverage now, but nothing stops showing the whole RNA cram methinks?

**Comment by dnil** [comment]
Very good point about the WTS though: a related feature we could do at the same time is to add a new little button to show the IGV.js RNA viewer from the case page, mirroring the DNA shortcut, but WTS cases don't have variants yet, so no viewer button.
