### ISSUE TITLE
New HPO release 230617

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#3991]
[2023-06-17 Release](https://github.com/obophenotype/human-phenotype-ontology/releases/tag/v2023-06-17)

Repository: [obophenotype/human-phenotype-ontology](https://github.com/obophenotype/human-phenotype-ontology) · Tag: [v2023-06-17](https://github.com/obophenotype/human-phenotype-ontology/tree/v2023-06-17) · Commit: [f129f49](https://github.com/obophenotype/human-phenotype-ontology/commit/f129f49fb1cc0c2f9f66bace8cb9b2bd92013b1e) · Released by: [matentzn](https://github.com/matentzn)

New with this release

44 new terms, many of which are behavioural phenotypes. This release, soon after the previous one, was performed to accommodate for a user meetup on the subject.

**Comment by northwestwitch** [comment]
Too bad we just updated our database!

**Comment by northwestwitch** [comment]
Let's close this issue, since we have a more recent one describing the latest HPO release!
