### ISSUE TITLE
put a size limit on 'submitted to clinvar' box?

### ISSUE THREAD

**Issue by ielvers** [Clinical-Genomics/scout#3997]
Hi,

Would it be possible to make the 'Variants submitted to ClinVar' box the same size as the 'Pinned variants' box? Thank you!

![image](https://github.com/Clinical-Genomics/scout/assets/57791644/283f3aa2-3f3b-480d-b1aa-61f30562f704)

**Comment by northwestwitch** [comment]
OMG yes! We'll fix! Thanks for reporting the issue!

**Comment by dnil** [comment]
Heh, nice catch! I'm guessing no one ever added more than at most three variants for one patient before! 😅
