### ISSUE TITLE
too many OMIM link to a gene/phenotype

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#400]
Hi, 
looking into fam 16153 variant on PIGA gene
There are several OMIM phenotype. once I click on them the link is to other gene then PIGA....
Could you check?

![skarmklipp](https://cloud.githubusercontent.com/assets/12525201/22018064/425ae9b6-dcad-11e6-95c6-a3016cf91ad5.PNG)

**Comment by moonso** [comment]
This is fixed!
