### ISSUE TITLE
Re-write pydantic classes in Pydantic V2 - (un)freeze dependencies

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#4015]
![Screenshot 2023-07-03 at 16 25 25](https://github.com/Clinical-Genomics/scout/assets/758570/7080e91d-c99d-46bb-8161-c0b275a7da7d)

https://docs.pydantic.dev/dev-v2/migration/
![Screenshot 2023-07-03 at 16 24 30](https://github.com/Clinical-Genomics/scout/assets/758570/be177a36-002e-4558-82a2-7154630713ed)

Freeze termporarily, then migrate..

**Comment by dnil** [comment]
The "bug" part can be fixed with a freeze <2, e.g. as in #4014. That leaves the migration as such as a later enhancement (and perhaps reconsider if we really use it wisely or are good with just type hints?).

**Comment by dnil** [comment]
That.. might be a few. Though several of those are also using strict version control on their deps.

**Comment by northwestwitch** [comment]
I've been trying fixing this but soon realized that the pydantic code we have in scout is a mess, with variables named in weird ways (like images lists are named as variants, and stored under a variable name named "str" - see #3084 - and so on) . We should instead re-write all the pydantic code instead and start fresh.
