### ISSUE TITLE
Add UMI option to cancer VCF upload

### ISSUE THREAD

**Issue by ivadym** [Clinical-Genomics/scout#4021]
### Problem:
Currently, cancer variant VCF uploads do not account for UMIs. To distinguish between cancer VCFs with and without UMIs, we need new options.

### Proposed Solution:

**UI**:
  - Add nav-links for users to identify UMI specific VCFs.

**Command-Line Options**:
  - `--vcf-cancer-umi`
  - `--vcf-cancer-umi-sv`

**Comment by dnil** [comment]
Hi, sorry, I think we are missing a bit of context here? When we discussed this way back when we landed in adding a 'panel-uni' type case that could be used for these.

Is the new option for use with other cases than the 'panel-umi' ones? For having more than one set of VCFs per case? For exome or wgs cases as well or still only panels? Are there any other differences between the UMI VCFs and your regular ones, eg different annotations or special keys you want to store?

**Comment by dnil** [comment]
Compare eg #3369 and similar! 😊

**Comment by ivadym** [comment]
Yes, sorry I wasn't clear enough in the issue.

> Is the new option for use with other cases than the 'panel-umi' ones?

No, the new option is only applicable to `panel-umi` cases.

> For having more than one set of VCFs per case?

The intention is to show results from the `panel` sequencing type in `panel-umi` since we currently lack a method to call SVs while considering UMIs.

>  Are there any other differences between the UMI VCFs and your regular ones, eg different annotations or special keys you want to store?

No, we have already been uploading UMI VCFs using the `vcf-cancer` tag. However, we would like to use a different tag, like `vcf-umi-cancer`, specifically for UMI-related VCFs.

Essentially, for the `panel-umi` sequencing type, we are currently running the balsamic (`panel`) and balsamic-umi (`panel-umi`) workflows. In response to a customer request, we have recently started uploading SVs to that view as well. And we want to ensure that customers are aware of which results consider UMIs and which ones do not.

I'm not sure if a new option is the way to go here, but it seemed like the most straightforward.

**Comment by dnil** [comment]
Ah, ok, I think I see what you have now. Well, why not! Another option might be to add a comment to the cases and delivery reports to explain and document, but one does not have to exclude the other.

I guess uploading a separate case for the same patient with regular non-umi cancer and cancer-sv is not convenient?

Two more questions then, from the top of my head:

- Do you envision having UMI-SV files anytime soon, or indeed at any point?

- Have you thought about/discussed how to handle the backlog of old `panel-umi` cases with umi-variants loaded as regular `cancer`? These would be a little confusing after a change?

**Comment by ivadym** [comment]
We had a meeting to discuss this and I'll do my best to convey all the ideas that were shared.

Opting to upload a separate case appears to be a favorable choice.  However we lack a dedicated UMI workflow, as it is intertwined with the Balsamic one. This setup isn't part of our immediate plans either.

Regarding the UMI-SV files, they aren't currently part of our roadmap. While it's a consideration for the future, it's not something we're planning in the short term.

In the past, we hadn't been including SVs for old panel-UMIs. This changed recently due to a specific customer request. This update has also been communicated to the customer through a dedicated meeting.

This proposal does introduce a departure from the conventional structure of using `panel-umi` and incorporating non-UMI files. However, it doesn't seem likely that we'll be splitting our workflows in the near future. 

What are your thoughts on this? It might be ok to just incorporate this information into the delivery report, if you believe that introducing umi-specific tags would diverge from our current setup.

**Comment by ivadym** [comment]
Closing, not relevant anymore!
