### ISSUE TITLE
Missing mtDNA coverage in Coverage report and mtDNA report in case 22157-muskel-2

### ISSUE THREAD

**Issue by 1ctw** [Clinical-Genomics/scout#4022]
The coverage report for mtDNA for case 22157-muskel-2 is of some reason empty. The  coverage is also missing in the mtDNA report. The coverage seems normal in IGV. We have not had any problems with coverage reports for other cases.

https://scout.scilifelab.se/reports/report?sample_id=ACC12277A5&level=10&panel_name=Mitochondrial+DNA+(8.0)

Could you please check what could be wrong in this case. Thanks for your help.

**Comment by 1ctw** [comment]
![image](https://github.com/Clinical-Genomics/scout/assets/15033593/97f28302-322a-40e6-a627-046fc3fb2425)
This is what it look like when I open it from Scout.

**Comment by 1ctw** [comment]
Thanks Daniel! I will contact them also.

**Comment by dnil** [comment]
This was by the looks of it resolved. We are not 100% sure why, but there is reasonable opportunity for issues either with automation or manual handling prior to Scout/Chanjo, as the sample is from a rerun, and also exists in a trio with two WES cases.
