### ISSUE TITLE
Sort genes in alphabetical order in gene panel view

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/scout#403]

**Comment by NicoleCMMS** [comment]
Can this issue be put on prio?  We cannot search coverage of individual genes in our gene panels without being able to localise the gene.  Thanks!

**Comment by robinandeer** [comment]
you can also search using the browser function: ctrl+F or command+F (mac)

but I'll look into this

**Comment by robinandeer** [comment]
I've solved it!
