### ISSUE TITLE
Cancer germline and somatic loqusdb-observation/frequencies filter fields for cancer cases

### ISSUE THREAD

**Issue by khurrammaqbool** [Clinical-Genomics/scout#4032]
The next `BALSAMIC` release `v13.x.x` (currently in `develop`) will include cancer germline and somatic loqusdb-observations/frequences annotations for SNVs and SVs. Similar to #4017, it will be nice to parse these annotations and make these available as filter fields in Scout.

A. The SNV-VCF for cancer cases include following annotations using `vcfanno`:
1. `Cancer germline SNV observations`:
```
        'annotation': [{
            'file': get_cancer_germline_snv_observations(config),
            'fields': ["Frq", "Obs", "Hom"],
            'ops': ["self", "self", "self"],
            'names': ["Cancer_Germline_Frq", "Cancer_Germline_Obs", "Cancer_Germline_Hom"]
        }]
```
2. `Cancer somatic SNV observations`:
```
        'annotation': [{
            'file': get_cancer_somatic_snv_observations(config),
            'fields': ["Frq", "Obs", "Hom"],
            'ops': ["self", "self", "self"],
            'names': ["Cancer_Somatic_Frq", "Cancer_Somatic_Obs", "Cancer_Somatic_Hom"]
        }]
```

B. The `SV-VCF` for cancer cases includes the following annotations using `svdb`:
1. The relevant flags from `svdb` command-line for `somatic-sv-observations` 
```
--in_occ Obs --out_occ somatic_obs --in_frq Frq --out_frq somatic_frq
```

**Comment by northwestwitch** [comment]
Cool!!!! 🥇
