### ISSUE TITLE
Codeowners restored...

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#4038]
Oopsie... Told-you-so... 😝 

![Screenshot 2023-08-15 at 11 42 21](https://github.com/Clinical-Genomics/scout/assets/758570/e54db7f0-49f4-4e42-bed6-c10e164924a4)

**Comment by northwestwitch** [comment]
My bad, @pbiology asked me which approach to take before merging his PR and I didn't foresee the implications ;)
