### ISSUE TITLE
Expected inh. is X on autosomal chr due to multiple links OMIM data?

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/scout#404]

**Comment by robinandeer** [comment]
which variant do you see this in?

**Comment by robinandeer** [comment]
AXIN2

**Comment by moonso** [comment]
I'm waiting to get login credentials to OMIM and see if we can get better information from the files that they provide

**Comment by moonso** [comment]
We are all aware now why this is happening and the solution.
We will use only omim information but there will still be strange cases
