### ISSUE TITLE
OMIM data account expired

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#4041]
Our official OMIM account has expired so it's not possible to run database updates at the moment. I'll apply for a renewal!

**Comment by dnil** [comment]
Good! I have an active one for the clinic should we need to update in the meantime.

**Comment by northwestwitch** [comment]
I haven't received a reply yet, so I've contacted them via the "Contact us" link. 🤞🏻

**Comment by northwestwitch** [comment]
This is fixed now, closing!
