### ISSUE TITLE
Clinical filter SNVs to include more splice variants

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#4043]
The clinic reports increasingly finding evidence for splice variants being causative. This is so far found outside ClinVar, from own or others RNA studies. Including the most obvious triad of 
```
    "splice_donor_5th_base_variant": {"rank": 16, "region": "splicing"},
    "splice_donor_region_variant": {"rank": 17, "region": "splicing"},
    "splice_polypyrimidine_tract_variant": {"rank": 18, "region": "splicing"},
```
seems to give a modest increase of variants passing clinical filter with 5-10%, depending on the panel at hand.

The suggestion is primarily from @KickiLagerstedt / clingen, so it would be great to hear from a few more, at least in the GMCK-RD group (@NicoleCMMS, @1ctw, @ielvers, @Leif-glitch, @sofievonlanthen). E.g. Lund do AFAIK not use the clinical filter.

**Comment by NicoleCMMS** [comment]
Hej Daniel,

Vi som är på plats från CMMS har diskuterat och tycker det är viktigt att dessa varianter kommer med i clinical filter!  Vi vill gärna testa under en period och blir det för många besvärliga varianter att dismissa kan vi ta upp för diskussion igen.

Hälsningar,
Nicole

Från: Daniel Nilsson ***@***.***>
Skickat: den 17 augusti 2023 10:59
Till: Clinical-Genomics/scout ***@***.***>
Kopia: Nicole Lesko ***@***.***>; Mention ***@***.***>
Ämne: [Clinical-Genomics/scout] Clinical filter SNVs to include more splice variants (Issue #4043)


The clinic reports increasingly finding evidence for splice variants being causative. This is so far found outside ClinVar, from own or others RNA studies. Including the most obvious triad of

    "splice_donor_5th_base_variant": {"rank": 16, "region": "splicing"},

    "splice_donor_region_variant": {"rank": 17, "region": "splicing"},

    "splice_polypyrimidine_tract_variant": {"rank": 18, "region": "splicing"},

seems to give a modest increase of variants passing clinical filter with 5-10%, depending on the panel at hand.

The suggestion is primarily from @KickiLagerstedt<https://github.com/KickiLagerstedt> / clingen, so it would be great to hear from a few more, at least in the GMCK-RD group ***@***.***<https://github.com/NicoleCMMS>, @1ctw<https://github.com/1ctw>, @ielvers<https://github.com/ielvers>, @Leif-glitch<https://github.com/Leif-glitch>, @sofievonlanthen<https://github.com/sofievonlanthen>). E.g. Lund do AFAIK not use the clinical filter.

**Comment by sofievonlanthen** [comment]
Agree with Nicole, happy to test for a while and see if we have a large number of increased variants to sort through. 
//Sofie
