### ISSUE TITLE
Some variant pages won't load (timeout?)

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#405]
E.g. https://clinical-db.scilifelab.se:8083/cust002/F0010579/variants/f3e45cdf7c8c7c91988a3a55eb95d879

Tries to connect for a long time, then returns "The connection to the server was reset while the page was loading." as Firefox has it. "server unexpectedly dropped connection" in Safari. Or most eloquently in chrome: "The page isn’t working ... ERR_EMPTY_RESPONSE".

Other variant pages on the same case load ok.

**Comment by dnil** [comment]
Non-OMIM Morbid gene, it appears - but then other dito load anyway..

**Comment by NicoleCMMS** [comment]
Here is a concrete example to check:
Family 16165
WWOX variant (IEM gene)
Rank 156
This variant and all other WWOX variants in this family refuse to load.

**Comment by robinandeer** [comment]
Woah... 😵  that variant has 1063 compounds LOL

I think you won't need to inspect all of them haha

**Comment by dnil** [comment]
Hehe nope - likely not.. Brings to mind issue #374. Thanks!

**Comment by robinandeer** [comment]
RBFOX1 spans 2.5M bases hahaha - almost everything is intronic tho
