### ISSUE TITLE
gen panel verison not updated 

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#406]
I can see in case 16161 already genes that belong to the updated version of dbCMMs (V10)
EX PDE10A , OCRL and other.
In the case overview is state that version 9 had been used.

Could you cross check with version of database/panel has really been used?
If I look at the date of analysis is 2017-01-12
but the v10 has been submitted 2017-01-16....
This does'nt help me to sort it out :)

Thanks,
Michela

**Comment by robinandeer** [comment]
Hej, that's a very good discovery!

I've fixed the issue but the view loads a bit slow which we will investigate how we can improve early next week.
