### ISSUE TITLE
Freshly loaded case got FSHD activated.

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#4067]
A pydantic None / not existing issue perchance?
![Screenshot 2023-09-05 at 10 23 15](https://github.com/Clinical-Genomics/scout/assets/758570/24464307-6f9c-4d40-9d6e-2a8a43679ca3)

**Comment by northwestwitch** [comment]
I think that's because on cg-vm1 we don't have the super latest branch of the release installed. Try to update the branch

**Comment by northwestwitch** [comment]
No but regardless, we haven't touched the settings of scout, right?

**Comment by dnil** [comment]
No, not yet - it is very likely a mistake with Pydantic for fresh new samples. I usually test with `scout load --update`, and might not have tried that yet.

**Comment by dnil** [comment]
Yes, I can replicate it locally. Will fix.

**Comment by dnil** [comment]
Ok, my interpretation is that this is due to #3857 or a version thereof. That will have to be fixed with more finesse, especially with regards to testing of everything that may have come to depend on it. I think I will try to extend the template test for showing the button for now. It will look really advanced.. 🤣 
<img width="227" alt="Screenshot 2023-09-05 at 11 31 56" src="https://github.com/Clinical-Genomics/scout/assets/758570/12aa678e-79af-42bb-9617-b6d13bdd6d9a">
