### ISSUE TITLE
inheritance model curated at CMMS

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#407]
Hi,
 in our dbCMMS we manually add the inheritance model. This should appear in Scout.
( as for penetrance and mosaicism)

this is particularly relevant for the newly submitted genes that do not have info in OMIM.

Michela

**Comment by robinandeer** [comment]
Hi,

We will add the information about inheritance model to next to the OMIM information.

The manual incomplete penetrance is shown under "Incomplete penetrance" > "Manual" in the variant view.

Where would you like to see "mosicism" appear?

@moonso: we don't seem to store the inheritance model in the gene model for the panels, no?

**Comment by 4WGH** [comment]
the mosaicisim can be added in the widonw where the is the information about the penetrance. Just under.
 
 
Our curated inheritance model Was shown in the previous SCout version see attached screen shot 
This is important for the new gene not reported in OMIM yet
 
Michela
 
 
Michela Barbaro, M.Sc, PhD
Sjukhuskemist
Centrum för Medfödda Metabola Sjukdomar (CMMS)
L7:05
Karolinska Universitetssjukhuset Solna
17176 Stockholm 
-----Robin Andeer <notifications@github.com> skrev: ----- 

Till: Clinical-Genomics/scout <scout@noreply.github.com>Från: Robin Andeer <notifications@github.com>Datum: 2017-01-20 16:15Kopia: MichelaBarbaro <michela.barbaro@karolinska.se>, Author <author@noreply.github.com>Ärende: Re: [Clinical-Genomics/scout] inheritance model curated at CMMS (#407)
Hi,
We will add the information about inheritance model to next to the OMIM information.
The manual incomplete penetrance is shown under "Incomplete penetrance" > "Manual" in the variant view.
Where would you like to see "mosicism" appear?
@moonso: we don't seem to store the inheritance model in the gene model for the panels, no?

**Comment by moonso** [comment]
Backend is ready. We need to reload all the old panels

**Comment by 4WGH** [comment]
how is it going with this issue about the manually curated inheritence? sTill missing this info in case 17015 for a gene introduced with the last version of database. see variant on MBOAT7

**Comment by robinandeer** [comment]
@4WGH: this is now fixed in the production Scout version!

https://clinical-db.scilifelab.se:8083/cust003/17015/variants/6963f436a0daf3976ad6bb5b6d17dca1

We realized we have the information about inheritance models for the most recent panels (v10) but they were not displaying properly! We are sorry about the time it's taken to resolve the issue.
