### ISSUE TITLE
Option to use different build (hg38) as basis for OMIM-AUTO

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#4070]
As it is a few genes are missing from the OMIM-AUTO updates due to the genes not being annotated on the scout default build (hg37). Lets introduce a build option for the `scout update OMIM` and likely `scout update panelapp-green`.

**Comment by northwestwitch** [comment]
I'm currently working on this and I think PanelApp-Green panel doesn't care about genome builds at all, check also my original PR --> https://github.com/Clinical-Genomics/scout/pull/3802/files

**Comment by dnil** [comment]
No, completely agree but without reading the PR, just so we are on the same page: the problem was never the remote resource caring about build, but that we used our local build 37 genes for matching against the remote resource so that they are never added to the panels? Cf NOTCH2NL/C:
![Screenshot 2024-05-28 at 14 57 20](https://github.com/Clinical-Genomics/scout/assets/758570/583b4f29-4383-4d4b-9359-8ac79391c2a6)
and
![Screenshot 2024-05-28 at 14 59 36](https://github.com/Clinical-Genomics/scout/assets/758570/45e4d30b-7386-4cc7-b6f1-7920b3e8c51b)
but not
![Screenshot 2024-05-28 at 14 56 59](https://github.com/Clinical-Genomics/scout/assets/758570/984f2a45-d6b5-4515-8696-c643ec9130d6)

**Comment by northwestwitch** [comment]
> t we used our local build 37 genes for matching against the remote resource so that they are never added to the panels? Cf NOTCH2NL/C:

I'll check the where it collects the genes, perhaps we have some build="37"set as function param. Thanks!

**Comment by northwestwitch** [comment]
I think the gene NOTCH2NL (shown in the Panel-all screenshot) is not the same gene named NOTCH2NLC that is missing in scout build 37? 

NOTCH2NL should correspond to [NOTCH2NLA](https://www.ncbi.nlm.nih.gov/gene/388677), which is present in scout in both builds.

And actually when you try to load a panel with NOTCH2NL from PanelApp it works, but with a warning:

<img width="485" alt="image" src="https://github.com/Clinical-Genomics/scout/assets/28093618/29ce320e-e42a-425a-850d-a3c6b2e835c6">


Let's use another gene that is only present in build 38 -> [**KCNJ18**](https://scout.scilifelab.se/genes/39080)

If you have a local instance with both genome builds, and load a [Panel-app panel with that gene](https://panelapp.genomicsengland.co.uk/panels/229/):
`scout --demo load panel --panel-app --institute cust000 --panel-id 229 --panel-app-confidence red`

<img width="463" alt="image" src="https://github.com/Clinical-Genomics/scout/assets/28093618/3b784148-84e2-4a71-a968-4656e79f8fa7">

I'll work on this fix on a separate PR!
