### ISSUE TITLE
Missing reports

### ISSUE THREAD

**Issue by 1ctw** [Clinical-Genomics/scout#4077]
Delivery reports and Multiqc reports seem to be missing for all cases in Scout.

**Comment by northwestwitch** [comment]
Hello! The problem is very likely related to a problem in reaching the server where all scout analyses are stored. Also bam alignments should be missing. We have contacted the IT to fix ASAP. Sorry for the inconvenience!

**Comment by dnil** [comment]
Reports and alignments are now back online again. Apologies; we are ourselves curious for more of an explanation from IT for more than the superficial cause.
