### ISSUE TITLE
Where do the variants custom images appear in scout demo?

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#4085]
I'm still working on re-writing the scout load pydantic check in pydantic 2 and I don't understand this thing:

The images under the 'str' field [at this line](https://github.com/Clinical-Genomics/scout/blob/f9b49d8cc39c0f036a62ffc87b2d54c3d388bd32/scout/demo/643594.config.yaml#L80C3-L80C3)

That are saved in the case like this:

<img width="909" alt="image" src="https://github.com/Clinical-Genomics/scout/assets/28093618/6027971c-ba8e-406c-b346-d1c65c90d3a4">

Where do they show up??

**Comment by dnil** [comment]
On the case page, near the chromograph images? I believe e.g. Lund uses these for mitochondrial plots, and perhaps some reviewer-like images on STRs.

**Comment by dnil** [comment]
Ah, right, the custom_images case go to the case page, but...

**Comment by northwestwitch** [comment]
> Ah, right, the custom_images case go to the case page, but...

Right?

<img width="339" alt="image" src="https://github.com/Clinical-Genomics/scout/assets/28093618/9246d1df-ff17-404b-89c2-565f5694d704">

**Comment by dnil** [comment]
the strs go on the variant page:

**Comment by dnil** [comment]
https://github.com/Clinical-Genomics/scout/blob/f9b49d8cc39c0f036a62ffc87b2d54c3d388bd32/scout/server/blueprints/variant/templates/variant/variant.html#L171

**Comment by dnil** [comment]
I guess ‘variant’ would be a good substitute for ‘str’ here… 😸

**Comment by northwestwitch** [comment]
AHHHHHH, "str" is the variant category of variant, check it out here:

https://github.com/Clinical-Genomics/scout/blob/f9b49d8cc39c0f036a62ffc87b2d54c3d388bd32/scout/adapter/mongo/case.py#L893

I should fix it before renaming it!
