### ISSUE TITLE
Always load previous causatives

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#4087]
Compare #4086 - although we expect previous causatives to be submitted to ClinVar, there may be a window before submission, during processing and until reference updates for the pipelines that we can cover with a relatively small effort.

**Comment by northwestwitch** [comment]
I remember having the discussion some time ago, when we were planning to remove data for archived cases (which we didn't). Back then I proposed to have an extra collection in the database for causative variants, just for the purpose of loading them when found in other cases, even with low score: #2202

**Comment by dnil** [comment]
I guess it got lost in the discussion of cleanup on old cases with many variants? And perhaps the interest wasn’t the highest with clinvar loading doing the same thing, but possibly with a long lag.

**Comment by dnil** [comment]
The #2202 is still marked ”Solna only”. 😊
