### ISSUE TITLE
HPO number converted to string in database documents

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#4088]
The format of the HPO number has changed from before after we've merged #4064

HPO number is the part after : in an HPO term, for instance 000567 in HP:000567

It now becomes 567. 

The conversion occurs here -> https://github.com/Clinical-Genomics/scout/blob/f9b49d8cc39c0f036a62ffc87b2d54c3d388bd32/scout/models/phenotype_term.py#L23C42-L23C42

It doesn't look like it's creating problems, but it's a bug and we should save it as a string instead

**Comment by northwestwitch** [comment]
> Hm, not so sure? I think it was this way before #4064 as well:

Ah OK, good, [this comment](https://github.com/Clinical-Genomics/scout/blob/17f30b197c7a48f307789e1c97a373140ebe15d5/scout/models/phenotype_term.py#L14) is misleading then. I'll fix this PR accordingly!

**Comment by dnil** [comment]
I believe so: test and prior usage have precedence to me, though the actual uses seems limited beyond an id-key like use.

**Comment by northwestwitch** [comment]
Ok, let's close this issue then!, thanks for checking
