### ISSUE TITLE
Gene annotation and func annotation missing on some compound variants

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#409]
see 2 ex in 2 fam.

https://clinical-db.scilifelab.se:8083/cust003/16170/variants/44bed9bdaaf7e7a0f138276448ecdbca
https://clinical-db.scilifelab.se:8083/cust003/16168/variants/6073ae04e12b443bd53724d49adf3ec7

 it seams to happen for variants that hits 2 genes at the same time. in the compounds some variant get the annotatino some not. (active variants, not the not uploaded)

minor bug?

**Comment by moonso** [comment]
This should have been fixed in the new version so I'm closing.
Please reopen if the problem occurs again
