### ISSUE TITLE
Pretty printing looooong variant names can get a little silly esp on the case page

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#4094]
Eg https://scout.scilifelab.se/cust087/F0054849

**Comment by northwestwitch** [comment]
The same problem happens in the Search SNVs and INDELs page. Depending on how small your screen is (or how much you zoom in) It makes the variant panel to go out of frame:

<img width="908" alt="image" src="https://github.com/Clinical-Genomics/scout/assets/28093618/c2ebb21a-e1e0-41cb-87e0-9ca17fc00475">


<img width="1439" alt="image" src="https://github.com/Clinical-Genomics/scout/assets/28093618/0b0e9ea7-bd6d-4770-bafa-3515218ac48a">
