### ISSUE TITLE
Scout meeting 2017-02-01

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/scout#411]
- [x] How to filter on genes in Scout. Remove panel for querying of single gene.
- [x] New order portal and StarLims export.
- [x] What would you like to see in the Sanger email? #414 
- [x] HPO search (strict or ranked)
- [x] How to simplify gene panel handling in Scout

**Comment by robinandeer** [comment]
- [ ] add chromosome and p-position to SV variants view

**Comment by robinandeer** [comment]
15 mars next meeting
