### ISSUE TITLE
Add diagnosis caused by mtDNA variants in Scout?

### ISSUE THREAD

**Issue by 1ctw** [Clinical-Genomics/scout#4113]
I am trying to add OMIM diagnosis to a patient i Scout to be able to use it as partial causative in the mark causative function. I realized this is not working for OMIM diagnoses caused by mtDNA variants, at least not the ones I tested, e.g.. #545000 (MERRF), #540000 (MELAS),  #520000 (MIDD).

**Comment by dnil** [comment]
Well spotted! All the ones you list lack a formal gene connection in OMIM (for some reason they only describe their mt gene causation in free text, not as disease causing genes?) so the best fix for all would be to ping them to flag them as causative (here: https://www.omim.org/contact), but perhaps we should look into it as well. While we don't have much explicit use for diagnoses without established genes for genotype-phenotype mapping, there could still be merit in being able to flag the OMIM disorders outside the morbid segment from a pure phenotype perspective. For now I guess the best you can do is use HPO-terms for them, plus free text fields.

**Comment by dnil** [comment]
Do report them to OMIM though! They do fix stuff if you do!

**Comment by dnil** [comment]
Good call; there at least seem to be entries for [MELAS](https://www.orpha.net/en/disease/detail/550?name=MELAS&mode=name) and [MERRF](https://www.orpha.net/en/disease/detail/551?name=MERRF&mode=name). Did you contact/hear back from OMIM [1ctw](https://github.com/1ctw)?

**Comment by northwestwitch** [comment]
> Yes, that is a good suggestion. There are several mtDNA diagnoses in Orphanet. I did contact OMIM in October but unfortunately did not hear back.

Nice! I'm closing this issue then, but please reopen if needed
