### ISSUE TITLE
Diagnoses (OMIM terms) have no associated HPO phenotypes

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#4115]
I've just noticed this. It's affecting our courrent prod DB: https://scout.scilifelab.se/diagnoses. This must be a bug no?

**Comment by dnil** [comment]
Yep: that would have been missing many years. It appears it is used in one place though, on the Diagnoses sub panel on the case page. Not one we use a lot, but since we have it at all, it should be correct! 🥇
