### ISSUE TITLE
Diagnoses get stuck on case if the diagnosis term changes..

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#4117]
Attempting to remove a pre disesase-db update disorder:
![Screenshot 2023-10-11 at 10 52 30](https://github.com/Clinical-Genomics/scout/assets/758570/a8ef6d82-0e39-4cb6-8f96-e1339f73bc9e)
Stays stubbornly on the case. 😁

**Comment by northwestwitch** [comment]
Can you include a description on how to reproduce?

**Comment by dnil** [comment]
Hehe, that was more of a placeholder, but the current knowledge would be: add a random disease term as a diagnosis to the case with your September version of the db, then update the db with a recent branch and try to remove the diagnosis from the case.

**Comment by northwestwitch** [comment]
I can work on this one if you haven't started @dnil

**Comment by dnil** [comment]
Sounds great; it is somewhat related to the other diagnoses issues! I think I will try to fix that `re.escape` thing first.

**Comment by northwestwitch** [comment]
> then update the db with a recent branch and try to remove the diagnosis from the case

Should I update the db with the latest files or still those from September?

**Comment by northwestwitch** [comment]
Ok, doesn't matter. I think that an easy for to this is that it should remove the disease from the case regardless if it's in the database or not. Same for the HPO terms I guess!

**Comment by dnil** [comment]
Yeah, remove is remove. I guess there was some consideration since adding disease may implicitly add associated phenotypes?
