### ISSUE TITLE
Missing CLNSIG annotation

### ISSUE THREAD

**Issue by robinandeer** [Clinical-Genomics/scout#412]
> 2016-20130 har en variant i IFITM5 (c.-14C>T) som är patogen, dock hamnar denna variant på rank 661 och CLINSIG säger "not provided" men denna variant finns i Clinvar sen 2015. Hur kommer det sig att den inte plockas upp från Clinsig och rankas högre? Hur funkar det med icke-kodande varianter? Är det alltid så att om man trycker på "Clinical filter" att icke-kodande varianter försvinner?

**Comment by robinandeer** [comment]
cust002
family: F0010326

**Comment by henrikstranneheim** [comment]
This a strange one:

The particular variant is missing from the: ftp://ftp.ncbi.nlm.nih.gov/pub/clinvar/vcf_GRCh37/archive/2016/clinvar_20160502.vcf.gz
which is the clinvar version that has been used with this particular analysis.

However it is present in the hg38 version: ftp://ftp.ncbi.nlm.nih.gov/pub/clinvar/vcf_GRCh38/archive/2016/clinvar_20160502.vcf.gz

as 11	299504	rs587776916	G	A

However in the current ftp version:

GRCh37_clinvar_-2017-01-04-.vcf.gz
11	299504	rs587776916	G	C,T

and

hg38_clinvar_-2017-01-04-.vcf.gz
11	299504	rs587776916	G	A

so there is a variant in the 11:299504 pos but is does not contain any A alt. allele. Which seems to be contradicted by the online web page, which states g.299504G>A (GRCh37)

Anyhow, we should update the clinvar reference to 2017-01-04 asap
