### ISSUE TITLE
hg38_scout_exons.bed export

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/scout#413]

**Comment by moonso** [comment]
Why do we need this now?

**Comment by henrikstranneheim** [comment]
Because we cannot run hg38 in MIP past VEP in the production setting, if we do not have this file.
However, there is no rush with this as it is only the scapis samples that are scheduled so far and they do not need the split into clinical and research.

**Comment by moonso** [comment]
This is fixed, just tell me when and where you need the export
