### ISSUE TITLE
Overlapping SV/SNV/MEI

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#4132]
Hej 
I've noticed today that 
in the SNV variant view we can see "Overlapping SVs"
in the SV variant view we can see "Overlapping SNVs"

in the MEI view we can see "Overlapping SVs" but not "Overlapping SNVs"

Maybe something to check ?

should we show "overlapping MEIs" in SNV and SV variant view?

**Comment by dnil** [comment]
Right, that is https://github.com/Clinical-Genomics/scout/issues/3955. Thank you for noticing and reporting, but better to chime in on that one so we get some momentum.

**Comment by dnil** [comment]
And @4WGH maybe I should ask, did you notice what I missed at first, that current MEI have a size of 1? So they will only meaningfully overlap with SVs. It would be very tempting to add MEIs to the pool of variants that go with SNVs as compounds, but that is a pretty big step unfortunately. And phasing/genotyping on the short read MEIs isn't great, so we may not get much benefit from running them on trios, meaning a lot of extra "false" compounds on both singletons and trios.   I kind of felt we might better wait until we have long read called and phased MEIs to do this..

**Comment by dnil** [comment]
Precisely, overlaps between MEI and SV is doable. Between SNV and MEI makes little sense. SNV-MEI could be compounds instead, but I don't expect it will be good enough with the short read MEI calls that it is worth the effort.
