### ISSUE TITLE
info on the Sanger order

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#414]
Sanger order is working now but we see much less information than before.
transcript NMxxxx, c.xx, p.xx info where very important for us from a quality ensure point of view.

 Can we have them back?
Thanks,
Michela

**Comment by robinandeer** [comment]
Hi,

I made a quick-fix to make it work again but we aim to provide an email with all the necessary information of course :)

I was gonna bring up on the Scout meeting exactly what everyone would like to see - but I can start working on these for now

**Comment by dnil** [comment]
Any chances of attaching a snapshot from the pileup view?

// Daniel

**Comment by robinandeer** [comment]
no not a this moment

but the Sanger email template is now updated to look like before!
