### ISSUE TITLE
GENS link broken

### ISSUE THREAD

**Issue by sofievonlanthen** [Clinical-Genomics/scout#4148]
After the issues yesterday the GENS link seems to not work from the case page, but also the SV variant page. "Bad gateway". 
Known issue?

**Comment by dnil** [comment]
Hi @sofievonlanthen! Gens was disabled during part of the debugging yesterday, and it seems to just be some human error not starting it. We have an internal IT issue for grouping these services so we won't have to remember all of them. It should be working now!

**Comment by sofievonlanthen** [comment]
Perfect, thanks!

**Comment by dnil** [comment]
I see good gens connectivity after restarting gens:
![Screenshot 2023-10-20 at 09 08 41](https://github.com/Clinical-Genomics/scout/assets/758570/b270616c-45d1-4080-84d0-fdaa23eedead)

![Screenshot 2023-10-20 at 09 09 02](https://github.com/Clinical-Genomics/scout/assets/758570/df70a033-9f90-4f5d-a1f4-3f9fb28f2942)

Thank you for reporting!
