### ISSUE TITLE
Scout gunicorn cosuming available RAM on prod server

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#4149]
Looks like there is one or more queriers that are taking up all RAM when one is browsing in the portal. It seems that caseS, case and variantS pages are much slower.

**Comment by northwestwitch** [comment]
Moreover I see this:

<img width="1428" alt="image" src="https://github.com/Clinical-Genomics/scout/assets/28093618/e1131b6b-4412-481b-9154-0420be0a2cff">

Could it be that disease terms have so many associated genes?

**Comment by northwestwitch** [comment]
> Moreover I see this (this data is created when updating the database with scout >4.72)
> 
> <img alt="image" width="1428" src="https://user-images.githubusercontent.com/28093618/276845696-e1131b6b-4412-481b-9154-0420be0a2cff.png">
> Could it be that disease terms have so many associated genes?

**Comment by dnil** [comment]
Haha, thats probably the most immediate stressor! No way they have, something broke there. Probably genes being pulled by the disease having a general HPO term like "Recessive disorder".

**Comment by northwestwitch** [comment]
I'll convert that huge gene List thing in another issue
