### ISSUE TITLE
Broken alamut link to mitochondrial genes on GRHc38

### ISSUE THREAD

**Issue by mhkc** [Clinical-Genomics/scout#4150]
The alamut link in scout is not working properly for variants in mitochondrial genes. This is caused by the gene prefix was changed from **M** to **MT** with GRHc38.

Current alamut url 
`http://localhost:10000/search?apikey=73435198&institution=ASE0046&request=M(GRCh38):3116C%3ET`

Working URL,
`http://localhost:10000/search?apikey=73435198&institution=ASE0046&request=MT(GRCh38):3116C%3ET`

**Suggested solution**

Implement a lookup table with synonymous names so **M** and **MT** are valid prefixes.

**Comment by northwestwitch** [comment]
Thanks for reporting, we'll fix!
