### ISSUE TITLE
QoL: verified badge color

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#4154]
It would be nice if the verified `False positives` took a reddish color. The `True positives` could stay in the greenish ballpark.

![Screenshot 2023-10-20 at 11 46 13](https://github.com/Clinical-Genomics/scout/assets/758570/108c1388-0454-47ed-af97-daa1ad547b99)

**Comment by Esh07** [comment]
Hi, I came across this issue and I'm interested in contributing to it. Is it still available for contribution or has it already been resolved?

Thanks

**Comment by dnil** [comment]
You, and PRs, are very welcome; the issue is not assigned yet, though we perhaps had someone in mind @TereseBo there will be many more like that.

Are you in the disease genomics field or more generally a cs person wanting to contribute?

**Comment by Esh07** [comment]
Thank you for your quick reply, @dnil!

I'm new to open source contributions and excited to get involved. If anyone has already started working on it, that's perfectly fine!

Yes. I come from a cs background.

Cheers.

**Comment by northwestwitch** [comment]
@TereseBo there is this one if @Esh07 hasn't started yet

**Comment by TereseBo** [comment]
I will start working on this issue now

**Comment by TereseBo** [comment]
The badge color for false positives have been changed to red.
