### ISSUE TITLE
API entrypoint for pinning a variant in Scout

### ISSUE THREAD

**Issue by mhkc** [Clinical-Genomics/scout#4157]
I would like an API entrypoint for pinning a variant to a case in scout so I can include this function in accessory softwares such as Gens. It would be really cool if scout exposed functionality through an API to allow for better integration.

**Comment by dnil** [comment]
Good call! We have been deliberating if we should let gens write variants directly, but this would be good for many of them.

As a corollary, do you have any thoughts about what to do with "new" variants discovered in gens or similar, but not called? Allow some variant injection as well?

**Comment by northwestwitch** [comment]
I wonder how to make this work by the point of view of the security. I might be missing something given that I'm not so much into how gens work. When you pin a variant from within scout, you find yourself in the application context, having logged in via google or LDAP. But to serve the endpoint as an API, wouldn't be so secure so you'd need a token or something.. Unless gens is in the same app context?

**Comment by dnil** [comment]
We would have to revisit a common authentication mechanism, but that is sort of needed for some other updates as well. I'm still hopeful we could get this to work without a common context, only with the same users plus oauth2 and possibly a shared secret between gens and scout. gens is privy to scout db read access already, so a user could authenticate once and move rather freely between the two. But a little more is needed for the api-call, agreed!

**Comment by mhkc** [comment]
I agree with the security concerns. As @dnil said we could use Oauth2. We could write a simple authentication service that other applications can use to get an authentication token, and thereby gain access to the Scout API. Applications such as Gens could authenticate itself to the auth-service with with private and public keys.

**Comment by dnil** [comment]
One version of authentication is now in place in Gens (https://github.com/Clinical-Genomics/gens/pull/50). We can try to add a pin api endpoint next!
