### ISSUE TITLE
ClinVar pending submission format change (delayed to January)

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#4186]
The ClinVar API seems to be preparing for form changes in order to better deal with somatic variants. This is most welcome, but  may require some changes to at least preClinVar, but very likely also the variant submission dialog forms in Scout.

https://github.com/ncbi/clinvar

![Screenshot 2023-10-31 at 08 16 01](https://github.com/Clinical-Genomics/scout/assets/758570/032ce0c8-d8fc-471f-857a-67b9d9d17d71)

**Comment by northwestwitch** [comment]
This has happened now. Closing this issue, since I've opened #4391
