### ISSUE TITLE
GnomAD link default changed to hg38 with the v4 release

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#4190]
Let's switch around to give a build only for 37. Also fixes update from v3.1 to 4.0, but note that MT is not available for 4 just yet.

**Comment by KickiLagerstedt** [comment]
:=(

**HJÄLP!** Åtgärda så snart som möjligt - det är jättejobbigt att göra analyser nu i och med att vi klickar upp denna länk nästan på varje variant vi tittar på. Vi måste nu göra en ny sökning på varianten i gnomAD v2.1 för att kunna se frekvens!

**Comment by KickiLagerstedt** [comment]
**Kan ni snälla skicka ut denna info (mail) till alla användare så att ingen gör felbedömningar!**

**Comment by dnil** [comment]
Ok, we'll try to release a patch sooner rather than letting this go with the next update. Note that rhe information displayed in Scout is still correct, and if you frequently visit other sites for other info, it may be time to ask to have that info incorporated in the ordinary display. Is this for popFreqMax, subpopulation histograms, gnomAD quality, or do you cross reference other gnomAD datasets (like the exome frequencies)?
