### ISSUE TITLE
Expanded menu could benefit from increased accessibility

### ISSUE THREAD

**Issue by TereseBo** [Clinical-Genomics/scout#4198]
When opening scout with a width of less than approximately 1000px the top-menu collapses and can be expanded by a single button. The menu which is opened does not have a background colour and the contents are similar in color to the underlying page making it hard to distinguish the buttons. See example img from variant page. The contents of the menu differs on each page but the issue is similar

<img width="557" alt="Screenshot 2023-11-09 at 11 10 01" src="https://github.com/Clinical-Genomics/scout/assets/112548186/8dcc4728-cba5-4376-b950-eb4d1e394ea6">

Perhaps adding a the backgroundcolor of the menu also to the expanded element would solve the issue neatly?

**Comment by dnil** [comment]
Well spotted!
