### ISSUE TITLE
ClinVar submissions page has overflowing element

### ISSUE THREAD

**Issue by TereseBo** [Clinical-Genomics/scout#4199]
In the ClinVar-page the element (form?) which offers the possibility to update Submission ID manually overflows when window is less than approximately 1000px

<img width="876" alt="Screenshot 2023-11-09 at 13 57 45" src="https://github.com/Clinical-Genomics/scout/assets/112548186/3babecab-9a4d-4509-87d5-215b90feddbc">

**Comment by dnil** [comment]
In general, for prettiness, we do assume a user has at least some 1400 px, or maybe 1200 px if we are in a very generous mood. But there is no reason for things to actually stop working b-cause of width, so good catch!
