### ISSUE TITLE
REf Seq not apeearing near to the ENSEMBL FIXED

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#420]
![skarmklipp](https://cloud.githubusercontent.com/assets/12525201/22417119/dde9de62-e6d2-11e6-93b8-720b80efbbbd.PNG)

Ref Seq not coming up here. Very needed whne designing Sanger and to compare transcripts

Thank for help

MIchela

**Comment by robinandeer** [comment]
Hmm.. which case is this relating to? Or just the URL link to the page.

This information is supposed to be filled in dynamically but there might be something going on there...

**Comment by moonso** [comment]
Can we close this @robinandeer ?
