### ISSUE TITLE
Add an Edit-function for authors of ACMG classifications in Scout

### ISSUE THREAD

**Issue by TJO-Lund** [Clinical-Genomics/scout#4208]
Can an Edit-function be added to the ACMG-classification-module in Scout, available to the author of each ACMG-classification? For example, when we have meetings about a variant, with the author of a classification presenting, we would like for the author to be able to edit the ACMG-classification without having to recreate it from scratch. I believe this would also save time for everybody involved in analysis as any minor error means they have to fill in the form "Evidence of pathogenicity" all over.

**Comment by TJO-Lund** [comment]
Our group in Lund wote for the same solution for editing as for regular comments (and I do not see a need for a time-edit-window).

**Comment by TJO-Lund** [comment]
Hi, can I get an update on this issue? It is pretty annoying to have to redo the whole classification, including copying comments, when for example discussing a variant in a meeting.

**Comment by northwestwitch** [comment]
> If I understand you correctly you'd like to have an "edit" button that clicked brings you to the classification form where you have preselected all the choices that led to the old classification? If that's the case I think it won't be possible to edit classifications retroactively because we don't store the choice criteria in the database.
> 
> We can change the code so that we start saving them to edit the new classifications

Ah wait, I lied. I've found where the info is stored now. I'll start working on this feature!
