### ISSUE TITLE
External links on SNV page look weird

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#4211]
<img width="1237" alt="image" src="https://github.com/Clinical-Genomics/scout/assets/28093618/dcbf500a-a74a-49bb-ae1a-2fb9ac5428b5">

**Comment by dnil** [comment]
Ah, yes, the light mode users.. 😉

**Comment by northwestwitch** [comment]
Observed on demo case, SNV variants other than the first one (the TP53 one).

**Comment by dnil** [comment]
I think its the visited color shining through on light; all look fine on dark, visited or not.

**Comment by northwestwitch** [comment]
Right! it is the visited links:

<img width="1171" alt="image" src="https://github.com/Clinical-Genomics/scout/assets/28093618/086c9d57-567d-4f3e-847a-42a875adc4ec">

**Comment by TereseBo** [comment]
Is the aim to remove the change in color for visited links or rather to replace it with something more neutral?

**Comment by northwestwitch** [comment]
> Is the aim to remove the change in color for visited links or rather to replace it with something more neutral?

I'd remove the change of color and make them all look the same, either visited or not

**Comment by dnil** [comment]
Agreed!

**Comment by northwestwitch** [comment]
This is fixed by #4217, closing!
