### ISSUE TITLE
Audit clinical filter on variantS page

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#4219]
Eg add clinical filter to the dropdown, or possibly add a small checkbox/extra button. 

<img width="724" alt="Screenshot 2023-11-21 at 13 06 22" src="https://github.com/Clinical-Genomics/scout/assets/758570/de77252b-584d-496f-be23-739aa0d2bf34">

It is also very relevant to know what variantS type the filter was audited from in general (SNV, STR, SV...), so perhaps add that automagically on the reports rather than having it in the filter name.

**Comment by northwestwitch** [comment]
I'm wondering if it can't be fixed like this: if you are on the mei clinical variants and you audit a filter, then the info you want to add is collected in the event's link.

For instance from this link:

/cust000/643594/mei/variants?category=mei&display_name=appo2&page=1&variant_type=clinical&gene_panels=panel1&_id=65643eab3427eb8d8733c59b

You know that is mei clinical variants. That info can be extracted and added to the report?
