### ISSUE TITLE
Orphanet link not working properly

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#422]
the link goes to the orphanet page but do not show the page for the specific gene it should.

**Comment by moonso** [comment]
Yes I am aware of that, there is now obvious way to build the URL.
Can you have a look @robinandeer ?

**Comment by robinandeer** [comment]
http://www.orpha.net/consor/cgi-bin/OC_Exp.php?Lng=GB&Expert=289290

**Comment by moonso** [comment]
Since we will collect diseases from OMIM only for now on this is not relevant
