### ISSUE TITLE
Display gene panel membership in gene summary table in /variant view for variants related to multiple genes

### ISSUE THREAD

**Issue by alkc** [Clinical-Genomics/scout#4233]
Hej and greetings from Lund,

We received a request from our geneticists regarding displaying gene panel membership for genes in the case of variants from 'Clinical SNV and INDELs' that cover multiple genes.

The illustration below shows what kind of info is requested:

![bild](https://github.com/Clinical-Genomics/scout/assets/13668555/d43b6e8e-d029-40ee-b6cb-30ffb08627b7)

In this case the geneticist is working against a gene panel and wants to know which of the two genes affected by the variant belongs to the panel in question.

The illustration above is the simplest (ui-wise) implementation I can think of.

If you find this as something interesting to add to scout, then I can put in the work to implement it.

**Comment by northwestwitch** [comment]
Good suggestion! Shouldn't be too hard to implement!

**Comment by dnil** [comment]
Sure! Looks like a good spot. If you come up with some version of showing this next to the existing hover on the variantS page or little list with panels matching the variant on the variant page that would be fine.

**Comment by alkc** [comment]
> Sure! Looks like a good spot. If you come up with some version of showing this next to the existing hover on the variantS page 

I thought about that as well. I'll see what I can do!

> or little list with panels matching the variant on the variant page that would be fine.

Would you prefer putting the info into a hovertip instead of an additional column in the summary table?

**Comment by dnil** [comment]
> > Sure! Looks like a good spot. If you come up with some version of showing this next to the existing hover on the variantS page
> 
> I thought about that as well. I'll see what I can do!
> 
> > or little list with panels matching the variant on the variant page that would be fine.
> 
> Would you prefer putting the info into a hovertip instead of an additional column in the summary table?

I think you have some artistic freedom there - it's the same info. If it fits nicely into that table without the page going too wide on multiple panels I think you are good. But a hover there instead saves you having to think about how long the panel lists would get on genes with many associated phenotypes..

**Comment by dnil** [comment]
A hover or a little [...] collapse to open for more than a couple of panels. Remember that most clinical genes would appear on at least three panels (a dedicated panel, OMIM and PANELAPP-GREEN).

**Comment by alkc** [comment]
Good point about the page width - I hadn't thought about the number of gene panels that might end up in the table.

The [...] seems to me like the best approach out of the two, if it fits into the UI. Some data can be displayed immediately to the user while requiring some user interaction to display the rest. The hovertip approach always requires user interaction to get to the panel data.

## Progress/TODO:

- [ ] Add genepanel membership info to variant page gene summary table
- [ ] Extend/complement overlapping genepanel hovertip on variantS page
