### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#4243]
<img width="457" alt="image" src="https://github.com/Clinical-Genomics/scout/assets/28093618/ed063d0a-aa42-4153-9b37-51f0f209f879">

Should be like this:

<img width="360" alt="image" src="https://github.com/Clinical-Genomics/scout/assets/28093618/62c3281e-1e7f-466f-85f5-8954a8b0a63a">

**Comment by northwestwitch** [comment]
Ah look, even of prod the icons are missing. So something must have happened to fontawesome?

**Comment by dnil** [comment]
Yes, the unlock does not show on other pages as well, and the icons on the filters page are wrong!

**Comment by northwestwitch** [comment]
There was a Font Awesome release only 14 hours ago -> https://github.com/FortAwesome/Font-Awesome/releases/tag/6.5.0

Strange coincidence!

**Comment by dnil** [comment]
The clinvar submissions icon is also missing..

**Comment by northwestwitch** [comment]
@dnil if you find out how to fix it before me feel free to create a PR

**Comment by dnil** [comment]
Ill just add an FA update and we can see!
