### ISSUE TITLE
Refactor: internally rename "phenotype" to "disease" when largely referring to disorders / disease ontology terms

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#4255]
As part of the ongoing effort to make the disease and phenotype code more transparent, it would be useful to rename e.g. calls for `get_mim_phenotypes` to `get_mim_diseases`. This would bring the front end and backend terminology closer, make communication easier and avoid mixups between disease- and phenotype ontologies. There are some areas of contention, e.g. when mapping disease terms to phenotype terms; these can stay.

**Comment by northwestwitch** [comment]
I think this is mostly done done, thanks to @TereseBo. Closing now!
