### ISSUE TITLE
Fix pretty_variant() function to display multiple HGVS when a pinned/causative variant contains multiple genes

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#4265]
Because so far what is displayed is all genes + one HGVS only, example:

<img width="153" alt="image" src="https://github.com/Clinical-Genomics/scout/assets/28093618/6dc49460-41de-482b-a0cf-082d17fed833">

**Comment by dnil** [comment]
Ahem, that isn't true in the general case, c f
![Screenshot 2023-12-07 at 11 05 53](https://github.com/Clinical-Genomics/scout/assets/758570/8ee64d26-1464-4221-bead-de4f93e57dec)
but it can happen that the overlapping gene does not have a HGVS generated by VEP - eg from being too far up- or downstream?

**Comment by dnil** [comment]
Yes, compare a "downstream" variant.
![Screenshot 2023-12-07 at 11 23 42](https://github.com/Clinical-Genomics/scout/assets/758570/7ba90363-74ea-471a-b26d-109c62d107a1)
![Screenshot 2023-12-07 at 11 23 56](https://github.com/Clinical-Genomics/scout/assets/758570/f689f089-87a1-4d52-ad8d-9f238bf56198)

Perhaps we could have pretty print print the region annotation ("downstream") if HGVS is blank?

**Comment by northwestwitch** [comment]
Yes, perhaps is just upstream of downstream stuff, I'll check some variants
