### ISSUE TITLE
Add sorting in vcf columns

### ISSUE THREAD

**Issue by fevac** [Clinical-Genomics/scout#4270]
- Can we add sorting options for each of the column in the vcf view?

**Comment by dnil** [comment]
No. This is the first thing each new (research) user asks. What we should do is introduce a simple ranking/scoring system to order variants in rough likelihood of pathogenicity, gene panels to narrow the analysis etc!

**Comment by northwestwitch** [comment]
> No. This is the first thing each new (research) user asks

It's good that you didn't pursue a diplomatic career! 🤣

**Comment by dnil** [comment]
Hehe, indeed. 😊 It was a question and deserves an answer! Ofcourse one could sort on columns, but it defeats the long term utility of the system. Users will learn a complex, likely high variance and hard to performance test set of operations. 

Adding a simple ranking and gene list filter will be super though!
