### ISSUE TITLE
Sanger email feedback

### ISSUE THREAD

**Issue by sofievonlanthen** [Clinical-Genomics/scout#4277]
We use the Sanger-ordering email as a way of keeping track of which Sangers need to be performed to verify variants. The email includes a name of the person ordering the Sanger. Would it be possible for that person to also receive a confirmation when the status of the verification has been changed, e.g. "True positive"? 

 Saves me from having to contact that person to let them know that the Sanger is done.

**Comment by dnil** [comment]
Let's investigate! The user asking for the Sanger should be known from the email creation, and sending upon status change should be fine. That part may get a tad complicated based on not all institutes really using the Sanger email, but if that is the case maybe we could allow enabling it with a checkbox on the institute page.

**Comment by sofievonlanthen** [comment]
For institutes not using the Sanger email at all, I´m thinking they will not get affected by the change. If no sanger mail was sent, no reply will be sent either. 
But a checkbox is a good idea. Some might use the email but not wanting a reply. Happy with that it it´s feasible.

**Comment by northwestwitch** [comment]
> The email includes a name of the person ordering the Sanger. Would it be possible for that person to also receive a confirmation when the status of the verification has been changed, e.g. "True positive"?

Hi Sofie, I guess you contact the person which ordered the verification with their institutional email (for instance the hospital one) and not with the one they use in scout (i.e. somebody@clinicalgenomics.se). Scout database doesn't have access to the former and I don't know how useful if would be to notify them with an email that I guess they don't read regularly?

**Comment by dnil** [comment]
The idea would be to use the Sanger verification email, only it is triggered also by the verification status changing, not only when ordering.

**Comment by northwestwitch** [comment]
> The idea would be to use the Sanger verification email, only it is triggered also by the verification status changing, not only when ordering.

But the Sanger verification email is Sofie's no? And then she contacts the user which ordered the verification, not with the email that is used in scout, but with their "real" email. Or I am missing something?

**Comment by northwestwitch** [comment]
Ah well, one could add other emails to the sanger emails list I guess

**Comment by sofievonlanthen** [comment]
You are right Chiara, we would like it to send an email to the hospital email address, not the clinicalgenomics.se address. I just realise that now, that we don’t use our hospital email addresses to log on to Scout.
Can we access the emails sent to clinicalgenomics.se accounts?

We would like the person ordering the verification to be notified of the change, not everyone.



------------------------
Sofie Vonlanthen, PhD
Sjukhusgenetiker/Clinical Laboratory Geneticist
Klinisk Immunologi och transfusionsmedicin
F79 Karolinska Universitetsjukhuset, Huddinge
141 86 Stockholm, Sweden

***@***.***
tel: +46 (0) 72 595 5823

Från: Chiara Rasi ***@***.***>
Skickat: den 15 januari 2024 11:25
Till: Clinical-Genomics/scout ***@***.***>
Kopia: Sofie Vonlanthen ***@***.***>; Author ***@***.***>
Ämne: Re: [Clinical-Genomics/scout] Sanger email feedback (Issue #4277)


The idea would be to use the Sanger verification email, only it is triggered also by the verification status changing, not only when ordering.

But the Sanger verification email is Sofie's no? And then she contacts the user which ordered the verification, not with the email that is used in scout, but with their "real" email. Or I am missing something?

**Comment by northwestwitch** [comment]
> You are right Chiara, we would like it to send an email to the hospital email address, not the clinicalgenomics.se address. I just realise that now, that we don’t use our hospital email addresses to log on to Scout. Can we access the emails sent to clinicalgenomics.se accounts? 

Yes, the users can use those emails since they are real emails, but I have a feeling this is going to be cumbersome, since they first need to retrieve the password (open a ticket to our customer service), then they's need to remember to open that email once i a while.. I'll try to figure out an easier option, perhaps with a notification on top of the caseS page..!
