### ISSUE TITLE
Variant page suddenly slow on main, not release branch

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#4294]
Some new thing that is unindexed or just loops a bit much?

**Comment by northwestwitch** [comment]
Applies to this case: https://scout-stage.scilifelab.se/cust002/F0013103

**Comment by dnil** [comment]
Its loqusdbapi: confirmed by changing loqus settings for the institute. Also:
```
[daniel.nilsson@cg-vm1 ~]$ curl http://cg-prod-services.scilifelab.se:7079
```
just hangs.

Made a local IT  issue instead, and closing this for now.
https://github.com/Clinical-Genomics/IT-issues/issues/768
