### ISSUE TITLE
Gene description from VCF

### ISSUE THREAD

**Issue by robinandeer** [Clinical-Genomics/scout#43]
@henrikstranneheim wants to put gene description into the variant detail page. I can't find it in the ODM - what's the status?

> Add the vcf annotation “Gene_description” to the variant page where appropriate in layout.

**Comment by moonso** [comment]
@henrikstranneheim  How is the Gene_description field annotated?
If there are multiple genes, is there anyway to see which description belongs to which gene?

**Comment by henrikstranneheim** [comment]
Kenny should have removed all white space and commas from the original entries. 

Overlapping genes will be separated by “,”, which have been added by MIP. 

Let me know if you find any discrepancies.

On 02 Mar 2015, at 16:15, Måns Magnusson <notifications@github.com> wrote:

> @henrikstranneheim How is the Gene_description field annotated?
> If there are multiple genes, is there anyway to see which description belongs to which gene?
> 
> —
> Reply to this email directly or view it on GitHub.
> 

Henrik Stranneheim Ph.D.
Department of Molecular Medicine and Surgery
Karolinska Institute
Science for Life Laboratory
SE-171 65 Solna, Sweden

E-mail: henrik.stranneheim@scilifelab.se
Visiting address: Tometebodavägen 23A

**Comment by ingkebil** [comment]
for the Gene_description, I replace the following with underscores ",:;>| "
See [this](https://github.com/Clinical-Genomics/GeneLists/blob/master/scripts/ensembl.py#L43) module for more details.

**Comment by moonso** [comment]
How do we see which description that belongs to which gene if there are overlapping genes?

**Comment by henrikstranneheim** [comment]
You are right that info is not there.

@Kenny: We need to update the lists to be HGNC_symbol:Gene_description.


On 02 Mar 2015, at 20:52, Kenny Billiau <notifications@github.com> wrote:

> for the Gene_description, I replace the following with underscores ",:;>| "
> See this module for more details.
> 
> —
> Reply to this email directly or view it on GitHub.
> 

Henrik Stranneheim Ph.D.
Department of Molecular Medicine and Surgery
Karolinska Institute
Science for Life Laboratory
SE-171 65 Solna, Sweden

E-mail: henrik.stranneheim@scilifelab.se
Visiting address: Tometebodavägen 23A

**Comment by ingkebil** [comment]
@henrikstranneheim fixed. The list is available at its usual location.
