### ISSUE TITLE
missing HGNC id

### ISSUE THREAD

**Issue by robinandeer** [Clinical-Genomics/scout#430]
I found a gene in NMD panel which has been added without having an exiting entry in our internal gene database!

When you export the panel Scout produces an error - we should probably check if every HGNC id in a panel exists in our database before loading it, right?

Second question is why this gene is not in our database: http://www.genenames.org/cgi-bin/gene_symbol_report?hgnc_id=HGNC:39080 ☹️

**Comment by robinandeer** [comment]
not in GRch37

**Comment by dnil** [comment]
Did you ever find out the ulitmate reason? Not in GRCh37 isn't entirely true - exists in principle at least in .p13, although the unique mappability in our venerable core fasta version appears poor to say the least.
<img width="640" alt="screen shot 2017-02-09 at 14 10 33" src="https://cloud.githubusercontent.com/assets/758570/22793469/37bd6024-eef0-11e6-821a-f2e152987262.png">

**Comment by moonso** [comment]
We use the gene definitions in ensembl biomart 37 and it is not there so I'm afraid we can not include that gene. I guess they don't upgrade the 37 biomart with new releases of 37...

**Comment by dnil** [comment]
Well said - we look forward to it's return in glory in GRCh38! :+1:
