### ISSUE TITLE
Gnomad link to point to v4 for SNVs

### ISSUE THREAD

**Issue by Jakob37** [Clinical-Genomics/scout#4334]
When clicking the gnomAD link for a structural variant we end up on the version 4 page.

But when clicking the gnomAD link for an SNV, we end up on gnomAD version 3 page.

Is there a reason for the difference? Or should the SNV also point to version 4?

It sounded like a significant "quality of life" issue for our geneticists, who extensively use gnomAD and always need to click on to v4 ..

**Comment by dnil** [comment]
Ooh, lets see - I seem to recall we fixed that when they released, but maybe again is the lack of 38 cases in Solna that affect you as well.. 😊

**Comment by dnil** [comment]
Indeed, only fixed for the SVs for 38. Will do.
