### ISSUE TITLE
Empty cases side after clicking "Search"

### ISSUE THREAD

**Issue by Jakob37** [Clinical-Genomics/scout#4335]
In the latest version 4.75 the cases search is initially populated, but after clicking "search" no cases are displayed.

![empty_cases](https://github.com/Clinical-Genomics/scout/assets/7374399/652f23e4-7800-474a-ad2e-c1ca35ffd007)

Edit: Accidental return

**Comment by northwestwitch** [comment]
Ah yes, we are aware, see also #4325. I'm going to fix it now, sorry!

**Comment by Jakob37** [comment]
I see, thanks!

**Comment by northwestwitch** [comment]
I have a fix now, which you can review if you have time ->  #4336
