### ISSUE TITLE
Missing views for Cancer SVs

### ISSUE THREAD

**Issue by ivadym** [Clinical-Genomics/scout#4341]
They may be some missing fields for the SV views:

- [x] Cancer observations (both somatic and germline) are not appearing in the SV view in Scout. However, they are visible for SNVs! It seems that the follwing if statement should also consider cases when `variant.category == "cancer_sv"`: 

  https://github.com/Clinical-Genomics/scout/blob/dc0ed342f22d4f61448262894b2ed2f6f771ab9b/scout/server/blueprints/variant/templates/variant/variant_details.html#L219-L232
  
  Fixed in https://github.com/Clinical-Genomics/scout/pull/4342

- [x] The `Observed` column only shows the `Local` tag when it contains RD local observations, not taking into account the ones from Cancer. A good example is this variant with only Cancer observations: https://scout-stage.scilifelab.se/cust059/G1A1471p10_Balsamic/cancer/becc87e78804ce7da198f49a14dcd70f?cancer=yes
  Fixed: https://github.com/Clinical-Genomics/scout/pull/4348

- [x] The `Pop Freq` column is empty for Cancer Clinical Somatic Structural Variants: https://scout-stage.scilifelab.se/cust059/G1A1471p10_Balsamic/sv/variants/1f8f1489ff2b16b65489ce1d5173043d
  Fixed: https://github.com/Clinical-Genomics/scout/pull/4353

I think it's also worth considering if this issue extends beyond these cases, as it seems that `cancer_sv` is not considered as a proper category to display some data. We should verify if we're expecting to display information also for SVs when the variant category is just `cancer`.

**Comment by northwestwitch** [comment]
Hi @ivadym are you working on this? Otherwise I can help!

**Comment by northwestwitch** [comment]
Hi again. Are you sure the cases described in checkboxes 2 and 3 will not be resolved by changing the settings relative to  cust059?

You need to select the loqusdb instances you want stats from in the settings:

<img width="674" alt="image" src="https://github.com/Clinical-Genomics/scout/assets/28093618/147801e6-bb7e-4418-9144-8df3c7f3b035">

Don't forget to save the settings by clicking on "save settings" at the end of the page

**Comment by ivadym** [comment]
Yes, but that setting seems to only affect what's shown in the `Local observations` component in the variants page:
<img width="503" alt="Screenshot 2024-01-17 at 10 44 41" src="https://github.com/Clinical-Genomics/scout/assets/26309194/f4b63f23-3327-474f-bab9-ac51c2e57ba9">


I'm talking about this one, which misses to report archive observations for Cancer:
<img width="277" alt="Screenshot 2024-01-17 at 10 45 16" src="https://github.com/Clinical-Genomics/scout/assets/26309194/1e8febf3-7fec-43ea-b220-434ded3d63f3">


 I've checked a bit the code and I think we need to add something like this for the observations (update the `observed_cell_general` macro, which currently only shows `local_obs_old`):
<img width="230" alt="Screenshot 2024-01-17 at 10 55 09" src="https://github.com/Clinical-Genomics/scout/assets/26309194/34026b36-a0f8-4346-a7e4-53ca4abbbae8">

Thanks for looking into this! I can work on it once I get access to cg-vm1, but if you have time please go ahead. I could also help with some testing :)

**Comment by northwestwitch** [comment]
Ok, but then we can mark the second checkbox as done, right? The third one might have to do with the variant parsing.

**Comment by ivadym** [comment]
Sorry, I'm not being clear enough.

In point 2, the variant I mentioned lacks the expected `Local` tag in the `Observed` column on the `cancer/variants` page:

<img width="421" alt="Screenshot 2024-01-17 at 11 22 19" src="https://github.com/Clinical-Genomics/scout/assets/26309194/acd85d60-ac0b-4f38-8655-04d2a9dbc43e">

However, on the specific variant page, you'll see we're reporting cancer variants:

<img width="469" alt="Screenshot 2024-01-17 at 11 22 26" src="https://github.com/Clinical-Genomics/scout/assets/26309194/31f5d240-f4c2-4cc9-8d54-d5f848fe83f7">

I think we need to extend this part to include `local_obs_cancer_somatic_old` and `local_obs_cancer_germline_old`:

https://github.com/Clinical-Genomics/scout/blob/835dac88c81895a15249d02532ab927da95bd7b6/scout/server/blueprints/variants/templates/variants/components.html#L184-L186

**Comment by northwestwitch** [comment]
Ah I see, you are on the variantS page, not the variant one. Understood!

**Comment by northwestwitch** [comment]
Ok, point 2 should be fixed now. We merged [the fix](#4348) yesterday

**Comment by northwestwitch** [comment]
Regarding point 3 (Missing Pop freq), the stats shown are relative to Gnomad and ut's pretty common that these values are missing in SVs, see also rare disease cases. 

> Ok, point 2 should be fixed now. We merged [the fix](#4348) yesterday. The latest main branch is now deployed on stage (for a while at least)
