### ISSUE TITLE
Missing BAM files and chromograph 

### ISSUE THREAD

**Issue by Leif-glitch** [Clinical-Genomics/scout#4352]
HI!

BAM files for scout cases along with the chromographs on the first page are missing since this morning. On going issue? Important to fix for new cases comming up.
/L 

![image](https://github.com/Clinical-Genomics/scout/assets/63041167/f34d5dbb-5f8b-4eb2-923c-9269d0e4f919)
![image](https://github.com/Clinical-Genomics/scout/assets/63041167/478c87c9-18b0-4478-9e97-0965f9e4860e)

**Comment by dnil** [comment]
Oops: IT has has several small incidents with hasta following yesterdays service window. I'll see what we can do!

**Comment by dnil** [comment]
Ok, should be all good now. IT had put the fs back after the last crash tonight, but forgot to restart the services afterwards. 😊
