### ISSUE TITLE
ClinVar HPO-terms only rarely possible as condition for the classification

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#4374]
Submission errors as follows for variants submitted with one or more HPO-terms.
```
                     "errors": [
                            {
                                "userMessage": "You submitted a variant classified for a clinical feature, \"Retinoblastoma\". Classifications in ClinVar are expected to be variant-level classifications for a disease, not patient-level interpretations. Please see our instructions for submitting the condition for the classification, and contact us at clinvar@ncbi.nlm.nih.gov with any questions."
                            },
                     {
                                "userMessage": "You provided multiple clinical features as the condition for the classification. This is only valid if the features define a novel disease that is not yet named; if that is the case, provide \"novel disease\" as multipleConditionExplanation. If these are observed features, not the condition for the classification, submit the features as observedIn.clinicalFeatures and provide a disease as the condition for the classification."
                            }]
```
This is a bit silly, as e.g. above the disease and the phenotype have a 1-to-1 mapping, but naturally that is not always the case.
So as it is, either we always flag as "novel disease" when submitting HPO, or better perhaps suggest the users to supply OMIM (or ORPHA soon @TereseBo 😸), and only have HPO on the patient level with observedIn.clinicalFeatures.

**Comment by dnil** [comment]
They keep changing this up, but we are well on track to submit often instead of in big batches. Should be more straightforward to keep up when it's one thing at the time. We tried like 10 variants now, and 4 worked out of the box.

**Comment by northwestwitch** [comment]
You think this can be closed now @dnil ?

**Comment by dnil** [comment]
Let's - the interface follows their instruction after the fixes. I think it may resurface again since clinvar often seems to return error even for one hpo term as condition. And at some point we may want to submit individual phenotype terms, but not as the condition
