### ISSUE TITLE
OMIM phenotype does not show in Scout

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/scout#438]
This variant has no OMIM phenotype according to Scout:
https://clinical-db.scilifelab.se:8083/cust003/16006/variants/67608f8e6eefbfda0e4090d12843a673

OMIM:
https://omim.org/entry/602166?search=AP3B2&highlight=ap3b2
https://omim.org/entry/617276

This disease is quite new dec 2016.

Do we need to update the OMIM files or could there be bug?

**Comment by moonso** [comment]
This disease is not in our files from HPO but it exists in the omim files

**Comment by moonso** [comment]
Ok so we will parse everything that has to do with diseases, inheritance etc from the omim files.
From HPO we will only get the hpo terms and what genes they are associated with

**Comment by moonso** [comment]
This was solved with the update to scout version 3
