### ISSUE TITLE
Case page pinned vars layout..

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#4382]
Layout on pinned variants broken:
![Screenshot 2024-01-31 at 07 30 58](https://github.com/Clinical-Genomics/scout/assets/758570/298e3375-3439-4bbe-9dad-dcf292e9bbc7)

Perhaps just the pinned col size from #4381?

**Comment by northwestwitch** [comment]
Ah yes, I have changed the layout of the pinned in that PR, I'll revert, sorry!

**Comment by dnil** [comment]
No worries! As you wish, or I'll do it after I finish checking the phenotype-groups.

**Comment by northwestwitch** [comment]
> No worries! As you wish, or I'll do it after I finish checking the phenotype-groups.

I've already opened a PR for it!

**Comment by dnil** [comment]
Right, page was not reloaded.. I've approved it now. 😸
