### ISSUE TITLE
Make backend API more strict

### ISSUE THREAD

**Issue by robinandeer** [Clinical-Genomics/scout#44]
I need to go over my code and remove any direct references to the ODM. I also think we should discuss if code like this:

```python
  @property
  def local_requency(self):
    """Returns a float with the local freauency for this position."""
    return (Variant.objects(variant_id=self.variant_id).count /
              Case.objects.count())
```

really belongs as a method in the ODM or fit better as a function call to the backend API?

**Comment by moonso** [comment]
This is something for the portable version
