### ISSUE TITLE
Matching causative not shown

### ISSUE THREAD

**Issue by MUebe** [Clinical-Genomics/scout#4401]
Hi!
For case credibleloon (23466), there is a matching causative which we previously found in case closemammal (20049). Shouldn't that variant be displayed on the start page?! 
Thanks! :)
Malin

**Comment by northwestwitch** [comment]
Hi Malin, should be visible, yes. We'll look into it!

**Comment by northwestwitch** [comment]
I might have found a case to replicate this behavior on stage: https://scout-stage.scilifelab.se/cust003/15035 and https://scout-stage.scilifelab.se/cust002/15035-validation

**Comment by dnil** [comment]
Perhaps connected to https://github.com/Clinical-Genomics/scout/issues/4321?

**Comment by northwestwitch** [comment]
In the end the example I found on stage was a bad one because even if it's the same case one was loaded for cust002 and one for cust003, but I might have found the issue anyway
