### ISSUE TITLE
Connection failure warning when you run scout --help command

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#4408]
`scout --config /home/proj/stage/servers/config/hasta.scilifelab.se/scout-stage.yaml  --help`

<img width="1253" alt="image" src="https://github.com/Clinical-Genomics/scout/assets/28093618/a9993c62-db80-4f4b-9605-5fbdd1b6f07c">

**Comment by dnil** [comment]
This is kind of odd. It goes back to the click start being given with `invoke_without_command` and `create_app=get_app` I guess, and then different handling applies when giving a `--help` option versus `--config 1 --config 2 --help` (note that the command above is with an alias including one `--config` already). We are aiming to deprecate the CLI config load anyway, so perhaps this could wait until we rework that?

**Comment by northwestwitch** [comment]
Yes, it's a really minor thing. We can also close the issue

**Comment by dnil** [comment]
Ok, let's tag it to #2357 and remember to recheck after refactoring the config file load?

**Comment by dnil** [comment]
Well, not complete, wontfix for now kind of. 😄
