### ISSUE TITLE
Add clinical variant view shortcut button to go to HPO variants

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/scout#441]
Now you have to:
1. first generate the HPO panel and then
2. go to clinical variants and 
3. then click HPO panels
4. and then HPO gene list. To get to the actual HPO variants.

It would be nice with a button (HPO variants) to go straight to from 1. to 4. and skip 2 and 3. One would also of course have to select clinical/research (snv/indel or SV) view at the same time as well.

**Comment by moonso** [comment]
Fixed!
