### ISSUE TITLE
Missing SO terms in `scout.constants.so_terms.py`

### ISSUE THREAD

**Issue by alkc** [Clinical-Genomics/scout#4417]
Hej, I'm tinkering with VEP 111.0 in our wgs pipeline and ran into the following error when adding a VEP111 re-annotated case into scout. 

```
Traceback (most recent call last):                                                                 
  File "/home/worker/app/scout/adapter/mongo/variant_loader.py", line 719, in load_variants        
    nr_inserted = self._load_variants(                                                             
  File "/home/worker/app/scout/adapter/mongo/variant_loader.py", line 436, in _load_variants       
    parsed_variant = parse_variant(                                                                
  File "/home/worker/app/scout/parse/variant/variant.py", line 175, in parse_variant               
    parsed_transcripts = add_gene_and_transcript_info(parsed_variant, variant, vep_header)         
  File "/home/worker/app/scout/parse/variant/variant.py", line 565, in add_gene_and_transcript_info
    for parsed_transcript in parse_transcripts(raw_transcripts):                                   
  File "/home/worker/app/scout/parse/variant/transcript.py", line 80, in parse_transcripts         
    transcript["region_annotations"] = get_regional_annotation(functional_annotations)             
  File "/home/worker/app/scout/parse/variant/transcript.py", line 292, in get_regional_annotation  
    regional_list.append(SO_TERMS[annotation]["region"])                                           
KeyError: 'coding_transcript_variant'                                                              
```

Seems like the `coding_transcript_variant` term together with `sequence_variant` is missing from:

https://github.com/Clinical-Genomics/scout/blob/1e4a09a674e5ea9518df2ac4313da1677505b3fb/scout/constants/so_terms.py#L2-L45

Can I go ahead and add them based on the current severity ranking in http://www.ensembl.org/info/genome/variation/prediction/predicted_data.html ?

**Comment by alkc** [comment]
... Also, I should probably have asked this before tinkering with the most recent version of VEP but: which is the most recent version of VEP supported by scout? >_>

**Comment by dnil** [comment]
Super!

Hihi, Im afraid I don't know precisely: MIP has been very stable, on 107, and the SO term changes are a major pain for us, as we are having trouble understanding the logic with which they prioritize the severity hierarchy. This makes it hard to convert them to proper ranking and filter options. Oh, well, let's look at it! Suggestions are welcome, and then we'll try to grab @jemten who is the other SO term officer here once he's back from overseas.

I did load a case with native VEP 107 last week from a LRS pipeline, which kind worked with the exception for a few annotation tags. Notably the gnomad ones had changed though.q

From VEP 110 and onwards we also have the annotation of both ends of BNDs. This is really great, but we'll likely need to modify the band parsing to take advantage.

**Comment by alkc** [comment]
Thank you for the swift reply!

We're going to have a meeting with our geneticists later this week. I'll bring up the question of the two annotations then and see what feedback I'll get!

**Comment by alkc** [comment]
The consequences were missing from our own ranking scripts as well, so we ended up discussing what to do with them. In the end we found no reason not to follow the VEP ranking: 

| SO Term | SO description | SO accession | Display term | IMPACT | VEP rank | Scout rank |
| ---- | ---- | ---- | ---- | ---- | ---- | ---- |
| coding_transcript_variant | A transcript variant of a protein coding gene | [SO:0001968](http://www.sequenceontology.org/miso/current_svn/term/SO:0001968) | Coding transcript variant | MODIFIER | 31 | SAKNAS |
| sequence_variant | A sequence_variant is a non exact copy of a sequence_feature or genome exhibiting one or more sequence_alteration | [SO:0001060](http://www.sequenceontology.org/miso/current_svn/term/SO:0001060) | Sequence variant | MODIFIER | 41 | SAKNAS |

**Comment by dnil** [comment]
Super! We had a short session today as well: in summary we agree we would follow VEP (111), softly for now inclusion, since we have most cases at 107 still, then validate with known causatives before full migration. Then later to create a structured resource similar to the rank files with relevant SO terms, detailed rank (for most severe consequence filter in pipelines), scout filtering, scores for rank model and so on. But not today. The resources could then be versioned to match the case VEP version used.

**Comment by alkc** [comment]
Good idea to centralize/version the SO ranking. We might steal the idea. 

Can I go ahead and open a PR with an updated ranking?

**Comment by dnil** [comment]
Do! Centralizing it will take time - presumably will stay on hold until after the switch to nf-raredisease.
