### ISSUE TITLE
sv variant view

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#443]
It would be good to be able to see

- [x] Size. Only in variants list view now.
- [ ] ISCN variant description (canonical clinical nomenclature - compare HGVS for SNV/MNV)
- [x] OR/AND, if too much for now, coordinates of variant close to type, size, cytogenetic coordinate (chromosomal band), zygosity.
- [x] Link to Decipher - the de facto clinical repository of SVs. Can be deep linked via coordinates at least: https://decipher.sanger.ac.uk/browser#q/15:78276969-79060601%20/location/15:78151969-79185601

**Comment by moonso** [comment]
Hi @dnil , are there any examples of ISCN descriptions? Can we collect these from the VCF? How should the filter look?

**Comment by dnil** [comment]
Emailed about ISCN; basically @J35P312 and I have an idea for that. Let's see how it pans out - and just shout if you would like to fix it first!

**Comment by moonso** [comment]
Maybe you could just add a function?
Like:
```python
def get_iscn(variant_obj):
    """Returns ISCN coordinates

    Args:
        variant_obj(dict)

    Returns:
        issn_coordinates(str)
    """
    pass
```

SV variant obj should include most information. Might be something for @J35P312 to contribute with 😸

**Comment by moonso** [comment]
Since most of these are in place I will open a new issue for the ISCN coordinates
