### ISSUE TITLE
Show the CSQ/Function of related MANE transcript in gene summary in variant view

### ISSUE THREAD

**Issue by alkc** [Clinical-Genomics/scout#4431]
Hej again from Lund,

Here comes a request from our geneticists:

If I understand it correctly, the variant consequence displayed in the summary table is the most severe consequence picked out from all associated transcripts. 

This leads to cases where—while the MANE transcript is associated with a low impact consequence—some sometimes really obscure transcript can steal the show with a frameshift. 

What was suggested during the meeting was something conveying the following info:

![bild](https://github.com/Clinical-Genomics/scout/assets/13668555/ae3daa29-d7f0-4132-92ef-73bb055f7549)

What do you think?

**Comment by dnil** [comment]
Sounds great - only MANE isn't just one transcript?

**Comment by ehre** [comment]
Hi!

I wasn't involved in the discussion leading to the request, but MANE Select is surely the most important to annotate. For the 50 or so genes that also have a Plus Clinical transcript it would be nice to display the most severe consequence in either one.
