### ISSUE TITLE
ORPHA phenotype

### ISSUE THREAD

**Issue by Leif-glitch** [Clinical-Genomics/scout#4442]
See below, the new orpha phenotype inheritance model seems to aggregate in the gene models OMIM inheritance. In this case it aggregated to say that an AR gene is inherited both as AD,AR and XR which is incorrect and confusing when interpreting in question.   

![image](https://github.com/Clinical-Genomics/scout/assets/63041167/83618ab9-8752-4da5-8628-83f26449eac7)

**Comment by dnil** [comment]
Thank you! We'll fix!

**Comment by northwestwitch** [comment]
I can take a look at this today, thanks for reporting!

**Comment by dnil** [comment]
To summarise, we are not able to use the inheritance modes from ORPHA directly in conjunction with genes. We can display them for the phenotype, but they should be clearly distinct from the gene. ORPHA appear to group different "disorders" for convenience. Here, several genetic disease entities have been grouped under one phenotypic umbrella, and they still present all the different inheritance modes. 

ORPHA to me appears to be more of a phenotype centric, diagnostic database with less understanding of genetics, and that we should at the very least not present the ORPHA as being OMIM inheritance, which happened as a side effect of introducing ORPHA as disorders.

**Comment by dnil** [comment]
Oh, sorry, I had the page open and didn't see you assign!

**Comment by northwestwitch** [comment]
> To summarise, we are not able to use the inheritance modes from ORPHA directly in conjunction with genes. We can display them for the phenotype, but they should be clearly distinct from the gene. ORPHA appear to group different "disorders" for convenience. Here, several genetic disease entities have been grouped under one phenotypic umbrella, and they still present all the different inheritance modes.
> 
> ORPHA to me appears to be more of a phenotype centric, diagnostic database with less understanding of genetics, and that we should at the very least not present the ORPHA as being OMIM inheritance, which happened as a side effect of introducing ORPHA as disorders.

Agreed, ORPHA groups conditions deriving from multiple genes under a certain disease umbrella. It was naive of us to display its inheritance just like the OMIM one!
