### ISSUE TITLE
nf-core raredisease separate MT files

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#4445]
- [ ] MT variants VCF
~MT variants rank model key~
~MT variants rank model file (link on e.g. reference-files)~

We keep the same variant type (SNV on the chromosome MT). 
We postpone making a new view until there are more explicit requests for this. The rank models will not match in sorting, but variants are already incorrectly scored with the same model although annotation completeness differs, so chances are this will be better even before introducing normalized scores.

**Comment by northwestwitch** [comment]
I was thinking that instead of separating MT VCFs and SNV VCFs, one could allow the SNV VCF key in the case config to accept an array of paths, so the feature'd become more general and VCF files could be of any type, not necessary automosomes and MT files

**Comment by dnil** [comment]
The counterargument would be that you may still specific rank models and load thresholds? Most other parsing would presumably be conditional on keys. Nothing is impossible: we could have rules for when to apply a certain rank model etc but it seems a bit easier to treat it as a special case. Or did you have a particular use case in mind for other SNV VCFs already?

**Comment by dnil** [comment]
No new rank model with nf-core/raredisease yet. Checked with @jemten and we keep using the same for now.
