### ISSUE TITLE
Malformed queries in DECIPHER links for SV variants

### ISSUE THREAD

**Issue by alkc** [Clinical-Genomics/scout#4447]
Hej!

The DECIPHER SV links are broken. Accessing them leads to a redirect to the DECIPHER homepage.

## hg37 - scout demo (some recent commit)

1. Go to `cust000/643594/sv/variants/84af935d282baeb23862b3c28670f9f9`
2. DECIPHER link points to: https://decipher.sanger.ac.uk/search/patients/browser?q=grch37:8:141468110-141468175

I guess it should should be: https://www.deciphergenomics.org/search/patients/results?q=grch37:8:141468110-141468175 ?

## hg38 - our dev setup of v4.77:

1. DECIPHER link for random SV variant looks like this: https://decipher.sanger.ac.uk/browser#q/6:32004301-32014300/location/6:32004301-32014300

Should be: https://www.deciphergenomics.org/search/patients/results?q=6:32004301-3201430

**Comment by dnil** [comment]
Let's see, they actually look all good, and the forwarding is in principle still working? I had a little bit of finicking with the landing page, opting to log in seemed to solve it, but maybe the forwarding to the newer deciphergenomics.org does something subtle today as well. We'll change it and let's see if your issue persists; they have moved to EBI after all.

For both, our intention was really to point to the browser. The patients list is good as well, but I guess here the visual overview is faster for triage, and they can just click to the "patients/results" view?
