### ISSUE TITLE
bug? missing manual and omim inheritence

### ISSUE THREAD

**Issue by Leif-glitch** [Clinical-Genomics/scout#4458]
This variant is missing its inheritance model. Both the omim and manual from our panel. 
https://scout.scilifelab.se/cust003/17137/9be56eb065481d1e3074824b87be4e39

Bug? :)

**Comment by dnil** [comment]
Ok, so far so good then! We'll check the logs and see if we can see anything out of the ordinary, but I guess we'll close this for now. Let us know if it happens again.
