### ISSUE TITLE
nf-core raredisease - peddy het check

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#4460]
We already do
```
peddy_check: /home/proj/stage/rare-disease/raredisease_output_justhusky_cache110/peddy_check/justhusky.ped_check.csv
peddy_ped: /home/proj/stage/rare-disease/raredisease_output_justhusky_cache110/peddy_check/justhusky.peddy.ped
peddy_sex: /home/proj/stage/rare-disease/raredisease_output_justhusky_cache110/peddy_check/justhusky.sex_check.csv
```
Is it of interest to do also eg 
```
justhusky.het_check.csv
justhusky.ped_check.rel-difference.csv
```
and perhaps to more generally show the peddy html report
```
justhusky.html
```
Are we keeping peddy or moving towards other pedigree checks?

**Comment by dnil** [comment]
Hi @jemten @ramprasadn! Any thoughts on loading additional peddy checks?

**Comment by jemten** [comment]
There is an issue in the rd repo about replacing peddy with [somalier](https://github.com/brentp/somalier)

**Comment by dnil** [comment]
Ok, so, let's skip that for now! Thanks!
