### ISSUE TITLE
MEI summary frequency badge could be populated

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#4464]
We do show frequency info in the Frequency section, so just a matter of condensing.
![Screenshot 2024-02-27 at 12 55 46](https://github.com/Clinical-Genomics/scout/assets/758570/116000db-6d80-42d2-a2b5-7baebdbbf0d0)

**Comment by northwestwitch** [comment]
I can work on this if you haven't started @dnil

**Comment by dnil** [comment]
Feel very free! I was in that meeting... 😅
