### ISSUE TITLE
Clinical HPO STRs-button

### ISSUE THREAD

**Issue by SofieCMD** [Clinical-Genomics/scout#4473]
Lund wishes for a "Clinical HPO STRs-button" similar to "Clinical HPO SNVs" and "Clinical HPO SVs", should be a minor thing?

**Comment by dnil** [comment]
Hi, it's not quite as minor as it might seem: since we didn't have proper genes associated to STR loci in the beginning, some things are missing, like loading HGNC symbols for HPO panels when opening the STR variants page. Not huge, but still. Now or sooner seems like a good time to fix it! 😸
