### ISSUE TITLE
Add Cust no to "Share cases"

### ISSUE THREAD

**Issue by KickiLagerstedt** [Clinical-Genomics/scout#4477]
Even us have now begun to refer to ourselves as different Cust...

Therefor it would be of great assistance if the Cust no could be added to the names of list of labs we want to share a case to

![image](https://github.com/Clinical-Genomics/scout/assets/17139607/8850ad72-bdc3-49d1-9cae-91e225bb36d9)

**Comment by KickiLagerstedt** [comment]
Just to clarify - I get a request to case to Cust150 - but for me it is not clear cut what lab that is...

**Comment by northwestwitch** [comment]
Right, good suggestion. Should also be quite easy to implement!
