### ISSUE TITLE
reduced penetrance information missing

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#448]
hi look into fam 17010. gene NPRL3 has incomplete penetrance ( annotate on dbCMMS9
this info is not coming up in Scout. it states no in the manual information window. 
![bild](https://cloud.githubusercontent.com/assets/12525201/23219954/c414f82c-f920-11e6-8615-8625658e6b93.png)

**Comment by moonso** [comment]
Hello! We are aware of these issues and will try to adress them asap, hopefully this week.

Best,

Måns

**Comment by robinandeer** [comment]
Look now! We just updated the info on the gene panels :)
