### ISSUE TITLE
transcript not appearing

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#449]
Hi. fam 17010. gene NPRL3.
we have transcript  NM_001077350 as reference transcript. it is not appearing in the variant.... it should. neither on the transcript overview nor in the transcript sheet where the ENSEMBLE transcript number are listed. the variant is inside an exon, so it is relevant to sort out this issue. 
![bild](https://cloud.githubusercontent.com/assets/12525201/23220377/1cc1b0f4-f922-11e6-95aa-27c1aac8d374.png)

**Comment by moonso** [comment]
Ok so I have done some investigation here and it is a bit surprising.
To begin with we have solved the issue with displaying the information from your gene panel.

What I found out was that one ensembl transcript can map to multiple refseq transcripts, which is the case here. So this is what it looks like in the raw data file:
```
ENSG00000103148	ENST00000399953	16	134273	188859	135806	188669	NPRL3	NM_001243247
ENSG00000103148	ENST00000399953	16	134273	188859	135806	188669	NPRL3	NM_001243248
ENSG00000103148	ENST00000399953	16	134273	188859	135806	188669	NPRL3	NM_001077350
ENSG00000103148	ENST00000399953	16	134273	188859	135806	188669	NPRL3	NM_001243249
```
So we represent ensembl transcript ENSG00000103148 with NM_001243247, the one that you represent with NM_001077350. I have no clear solution to this one, we could try to display all but that could make the table harder to look at.
According to [hgnc](http://www.genenames.org/cgi-bin/gene_symbol_report?hgnc_id=HGNC:14124) the primary transcript for NPRL3 is NM_001039476 which corresponds to ensembl transcript ENST00000399951.

Any suggestions?

There is a discussion about this here:
http://lists.ensembl.org/pipermail/dev/2016-March/011700.html

Måns

**Comment by 4WGH** [comment]
if more then one RefSEq transcript correspond to one ENS transcritpt it is good to list all of them. So it was in the old version of Scout. No RefSEq transcript should be left out. I do not Think it is good in general to choose to leave out info.
Michela
 
Michela Barbaro, M.Sc, PhD
Sjukhuskemist
Centrum för Medfödda Metabola Sjukdomar (CMMS)
L7:05
Karolinska Universitetssjukhuset Solna
17176 Stockholm 
-----Måns Magnusson <notifications@github.com> skrev: ----- 

Till: Clinical-Genomics/scout <scout@noreply.github.com>Från: Måns Magnusson <notifications@github.com>Datum: 2017-02-23 14:54Kopia: MichelaBarbaro <michela.barbaro@karolinska.se>, Author <author@noreply.github.com>Ärende: Re: [Clinical-Genomics/scout] transcript not appearing (#449)
Ok so I have done some investigation here and it is a bit surprising.To begin with we have solved the issue with displaying the information from your gene panel.
What I found out was that one ensembl transcript can map to multiple refseq transcripts, which is the case here. So this is what it looks like in the raw data file:
ENSG00000103148 ENST00000399953 16 134273 188859 135806 188669 NPRL3 NM_001243247ENSG00000103148 ENST00000399953 16 134273 188859 135806 188669 NPRL3 NM_001243248ENSG00000103148 ENST00000399953 16 134273 188859 135806 188669 NPRL3 NM_001077350ENSG00000103148 ENST00000399953 16 134273 188859 135806 188669 NPRL3 NM_001243249
So we represent ensembl transcript ENSG00000103148 with NM_001243247, the one that you represent with NM_001077350. I have no clear solution to this one, we could try to display all but that could make the table harder to look at.According to hgnc the primary transcript for NPRL3 is NM_001039476 which corresponds to ensembl transcript ENST00000399951.
Any suggestions?
There is a discussion about this here:http://lists.ensembl.org/pipermail/dev/2016-March/011700.html
Måns

**Comment by moonso** [comment]
Ok I understand. Where should we list all of them?
In all tables? Transcript overview? Gene page?

**Comment by 4WGH** [comment]
![bild](https://cloud.githubusercontent.com/assets/12525201/23749032/7fd5b9e2-04c6-11e7-9908-ae77240b0158.png)
here, one after the other in the REfSeq Columns. So it was before :)

**Comment by moonso** [comment]
👍

**Comment by moonso** [comment]
This is fixed! You can check NPR3 if you like @4WGH

**Comment by 4WGH** [comment]
super! thanks!

Michela

________________________________
Från: Måns Magnusson <notifications@github.com>
Skickat: den 21 april 2017 10:47:00
Till: Clinical-Genomics/scout
Kopia: MichelaBarbaro; Mention
Ämne: Re: [Clinical-Genomics/scout] transcript not appearing (#449)


This is fixed! You can check NPR3 if you like @4WGH<https://github.com/4WGH>
