### ISSUE TITLE
Fix visualization of custom annotations on cancer variants pages

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#4495]
See [here](https://github.com/Clinical-Genomics/scout/pull/1584#issuecomment-1991535225)

**Comment by northwestwitch** [comment]
hey @cogrho I wrote a fix to the missing custom annotations for cancer variants. Would you like to try it? You just need to switch to [this](https://github.com/Clinical-Genomics/scout/pull/4497) branch  and go to a cancer variant that has custom annotations!

**Comment by cogrho** [comment]
> hey @cogrho I wrote a fix to the missing custom annotations for cancer variants. Would you like to try it? You just need to switch to [this](https://github.com/Clinical-Genomics/scout/pull/4497) branch and go to a cancer variant that has custom annotations!

Hi @northwestwitch, thanks for fixing this so quickly! Unfortunately, now when I go to the variant with custom annotations  I'm encountering an Internal Server Error. The error from server: jinja2.exceptions.UndefinedError: the template 'variant/utils.html' (imported on line 3 in 'variant/cancer-variant.html') does not export the requested name 'custom_annotations'

**Comment by northwestwitch** [comment]
> Hi @northwestwitch, thanks for fixing this so quickly! Unfortunately, now when I go to the variant with custom annotations I'm encountering an Internal Server Error. The error from server: jinja2.exceptions.UndefinedError: the template 'variant/utils.html' (imported on line 3 in 'variant/cancer-variant.html') does not export the requested name 'custom_annotations'

Ah sorry, I didn't realise that there was a typo. Please try again now

**Comment by cogrho** [comment]
> Ah sorry, I didn't realise that there was a typo. Please try again now

I tried again and now I can see the annotations on the variant page! However, they don't appear in a table format. Is that the expected layout?
![scout_annot](https://github.com/Clinical-Genomics/scout/assets/122987117/84839684-8a95-4f9f-9aaa-fde70d1b20d2)

**Comment by northwestwitch** [comment]
> they don't appear in a table format. Is that the expected layout?

Mmm I just reused the code available for displaying custom annotation for structural variant. Since we don't use custom annotations in our facility I didn't realise they look so ugly 😆 
Let me d´fix it! Thanks for re-testing!

**Comment by northwestwitch** [comment]
Hello again. I fixed it so it should look like this now:

<img width="514" alt="image" src="https://github.com/Clinical-Genomics/scout/assets/28093618/113bab71-a3e9-44d9-bd75-4414b6c2d213">

Please give it another try @cogrho

**Comment by cogrho** [comment]
> Hello again. I fixed it so it should look like this now:
> 
> <img alt="image" width="514" src="https://private-user-images.githubusercontent.com/28093618/312393448-113bab71-a3e9-44d9-bd75-4414b6c2d213.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMjIyMzUsIm5iZiI6MTcxMDMyMTkzNSwicGF0aCI6Ii8yODA5MzYxOC8zMTIzOTM0NDgtMTEzYmFiNzEtYTNlOS00NGQ5LWJkNzUtNDQxNGI2YzJkMjEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDA5MjUzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmNTA4NzA3NjEyYTc0ZmM2MjUzMjk5YTk2NmYxNGZkZmIwMDRlOWY2NDE3MTkwNzY5OTZjOGQ4ZjA3YmY1ZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LIp-WI7DQBENzjaymTHy3Vjg03tx-UTi3cr_Hf2G0j0">
> Please give it another try @cogrho

It works now! Thank you very much for fixing it! 
![scout_annot_2](https://github.com/Clinical-Genomics/scout/assets/122987117/c027a00c-940e-4fa5-b9e2-acdacaf91711)

**Comment by northwestwitch** [comment]
> It works now! Thank you very much for fixing it!

Thank you for the tests! 🚀 
We are about to release a patch containing this fix now!

**Comment by northwestwitch** [comment]
Here's the patch release: https://github.com/Clinical-Genomics/scout/releases/tag/v4.79.1
