### ISSUE TITLE
Missing cases?

### ISSUE THREAD

**Issue by 1ctw** [Clinical-Genomics/scout#450]
Suddenly lots of cases are missing in old scout. For example I am now working to finish cases 16155 and 16156 but they are both missing. It looks like all sample from 2016 are missing?

**Comment by ingkebil** [comment]
Is this in scout-archive or scout?

**Comment by 1ctw** [comment]
It is in scout-archive:
https://clinical-db.scilifelab.se:8081/cust003

**Comment by ingkebil** [comment]
this has now been fixed!

**Comment by 1ctw** [comment]
Thank you! I also sent a ticket for this problem. Then you can close this too.
