### ISSUE TITLE
hg38 only genes not searchable, at least on fusion page?

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#4506]
Cf https://scout-stage.scilifelab.se/genes/51775 on https://scout-stage.scilifelab.se/cust000/Seraseq-W4PBRB-FUSION/fusion/variants. A tentative guess is that it is global for `38` cases, and due to defaulting to `"37"` when we call https://github.com/Clinical-Genomics/scout/blob/92e390ee660fc8013e31f72a9859e9c590b1f6ae/scout/server/blueprints/variants/views.py#L136 rather than checking the case build?

**Comment by northwestwitch** [comment]
I can take this one if you haven't started @dnil
