### ISSUE TITLE
explanation about SPIDEX info needed

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#451]
what does it mean "not reported" for the SPIDEX results in the severity window (see screening shot)
1. analysis not performed?
2. no splicing affected?

we need to look for a possible spicing mutation on a candidate genes so this infor would help us.

![bild](https://cloud.githubusercontent.com/assets/12525201/23500534/c0f39624-ff30-11e6-893a-468d7c683662.png)

**Comment by henrikstranneheim** [comment]
It means that the SPIDEX algorithm cannot calculate a splicing prediction score. Usually because the variation is too deep into an intron. I.e. for these variants SPIDEX does not add any value to the interpretation.
