### ISSUE TITLE
Loading alignment not working

### ISSUE THREAD

**Issue by 1ctw** [Clinical-Genomics/scout#452]
I need to look at the alignment in some cases, but it seems that it is not working. It says "Loading alignments...use index chunks to speed this up. Nothing is then happening....

**Comment by moonso** [comment]
Could it be that it is a old case where the bam files has been archived?

**Comment by 1ctw** [comment]
I think that could be the cause in those cases. We have been working on some cases more than 3 months now.





________________________________
Från: Måns Magnusson <notifications@github.com>
Skickat: den 16 mars 2017 10:32:46
Till: Clinical-Genomics/scout
Kopia: 1ctw; Author
Ämne: Re: [Clinical-Genomics/scout] Loading alignment not working (#452)


Could it be that it is a old case where the bam files has been archived?

**Comment by moonso** [comment]
Ok, so if you really need those you can open a ticket.
