### ISSUE TITLE
Make default panels easier to access / overview 

### ISSUE THREAD

**Issue by Jakob37** [Clinical-Genomics/scout#4526]
This is a quality of life feature requested by our geneticists.

In the Gene panels section of the case page, they often have a large number of optional panels.

The default panels are "hidden" among these. They are nicely highlighted, but still requires frequent scrolling to access.

Would it be possible to make accessing these even easier?

They suggested putting them at the top of the list, but one could also imagine a checkbox to toggle "show only default panels" or separating them out into a separate list.

Here is the Gene panels list for the demo case. Our geneticists commonly have 100+ panels here.

<img width="247" alt="1" src="https://github.com/Clinical-Genomics/scout/assets/7374399/9c166f5e-6d35-4614-a5f9-d9728962fa6f">

**Comment by northwestwitch** [comment]
> Our geneticists commonly have 100+ panels here.

:scream:

Noted!
