### ISSUE TITLE
Throwing out users???

### ISSUE THREAD

**Issue by KickiLagerstedt** [Clinical-Genomics/scout#4527]
One of our BMA can no longer log in to SCOUT " User not found in Scout database"

She is listed among our users and she used Scout last week

![image](https://github.com/Clinical-Genomics/scout/assets/17139607/3aa3351b-63ec-4794-a335-64e7d47d197b)

What has happened?

**Comment by northwestwitch** [comment]
> User not found in Scout database"

What's her name?

**Comment by dnil** [comment]
The most common explanation would be that she is selecting another Google account from the login dialog. Is she at the clinic today? Maybe I can look over the shoulder.. 😁

**Comment by dnil** [comment]
She was unintentionally trying to login to the dev version of Scout. Case closed.

**Comment by northwestwitch** [comment]
> She was unintentionally trying to login to the dev version of Scout. Case closed.

Your explanation would have also been a good one.. You have no idea how many times (in a week) I'm trying to log in with my personal gmail email 😆
