### ISSUE TITLE
CLIN SIGN

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#453]
should it look like this?
![bild](https://cloud.githubusercontent.com/assets/12525201/23750770/ca155474-04ce-11e7-98ec-dafeda561981.png)

how can we improve this? it seams that there are several links connected  to the same variant...

**Comment by henrikstranneheim** [comment]
Scout will display a link for every accession id, so there is nothing wrong with the above entry. 

@robinandeer However, it would be nice if we could collapse this to unique fields and then show a pop-up when hovering above a link that displays the accession links for each subcategory. This should avoid the rather cluttered appearance.

**Comment by moonso** [comment]
I will make a new issue with the suggestion above
