### ISSUE TITLE
Trouble getting /report calls going to the correct end point

### ISSUE THREAD

**Issue by Jakob37** [Clinical-Genomics/scout#4539]
Hi again!

Following up on an issue previously encountered during testing of the PR: https://github.com/Clinical-Genomics/scout/pull/4529

It initially looked like a CORS error, but at least a part of it seems to be a more straight forward issue. It might simply be a configuration issue on my side.

I have Scout and Chanjo2 running on two URLs. Let's call them http://scout and http://chanjo2

Navigating to each of these individually I successfully enter Scout and Chanjo2 start pages.

Now, let's say I am in a Scout case, preparing to view its Chanjo2 report. The case URL:

http://scout/cust000/643594

I can successfully access Chanjo2 for the case, and I do then end up on an URL in the following format:

http://scout/cust000/643594/chanjo2_report/report?panel_name=Test+panel+(1.0)

The issue is that when doing further requests to update coverage settings within Chanjo2, calls are made to "/report" which leads me back to:

http://scout/report

The correct location would (I guess) be http://chanjo2/report

I also had an issue with these fetch requests being upgraded to https (through `<meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">` I think). I removed that for now for testing, but might be multiple steps to take to solve this.

Thankful for any input! I'll meanwhile continue testing.

**Comment by northwestwitch** [comment]
Hello @Jakob37. I've created a fix to this issue both in Scout(fix #4553) and chanjo2 (https://github.com/Clinical-Genomics/chanjo2/pull/273). When you have time could you try the fix by using these 2 branches in combo?

**Comment by Jakob37** [comment]
> Hello @Jakob37. I've created a fix to this issue both in Scout(fix #4553) and chanjo2 ([Clinical-Genomics/chanjo2#273](https://github.com/Clinical-Genomics/chanjo2/pull/273)). When you have time could you try the fix by using these 2 branches in combo?

That sounds great @northwestwitch ! I'll have time to look at it early this week.

**Comment by northwestwitch** [comment]
Regarding the SSL error, yes, I think it's something that should be fixed in your server settings (we don't see it in out setup at least..).

I'm a bit lost on the following errors, as I don't understand where that submitAsJson comes from. The last changes I made in scout and chanjo2 would submit the form data as application/x-www-form-urlencoded data and not as json. Even so, json should be an accepted format when you create report data.

I need to investigate further 🤔 
Thanks for testing!

**Comment by northwestwitch** [comment]
@Jakob37 ahhhhh -----> https://github.com/Clinical-Genomics/chanjo2/blob/07c42bf8de5742854f54b10d28369a25f8c611d7/src/chanjo2/templates/report.html#L290

**Comment by Jakob37** [comment]
> Regarding the SSL error, yes, I think it's something that should be fixed in your server settings (we don't see it in out setup at least..).

OK I see. Yes, I think the SSL errors are due to us running http and the requests being upgraded due to the `upgrade-insecure-requests` directive in that HTML tag. But I think that will be resolved soon.

> @Jakob37 ahhhhh -----> https://github.com/Clinical-Genomics/chanjo2/blob/07c42bf8de5742854f54b10d28369a25f8c611d7/src/chanjo2/templates/report.html#L290

Hmm, did you figure it out?

**Comment by northwestwitch** [comment]
> Hmm, did you figure it out?

Not yet, but I'll continue tomorrow!

**Comment by northwestwitch** [comment]
On our stage server, when I click on a report link from scout:

<img width="1676" alt="image" src="https://github.com/Clinical-Genomics/scout/assets/28093618/ef2ddc2c-9fe1-4f23-aa51-b71dcac79e71">

I should fix the 2 errors but they don't seem to have an impact on the report creation for me.

If I for instance modify the the threshold cutoff and remove some genes from the query by using the cutomize panel, the statistics change and I get once again the illegal invocation error, but not the request POST error you posted in your comment above 🤔 

<img width="1666" alt="image" src="https://github.com/Clinical-Genomics/scout/assets/28093618/7f88bde5-f091-4da6-a4ce-25fb5033b52d">

**Comment by Jakob37** [comment]
I'll double check!

**Comment by Jakob37** [comment]
Looks like I hadn't pulled the latest version of the Chanjo2 branch, sorry about that. Will re-try right away.

**Comment by northwestwitch** [comment]
> Looks like I hadn't pulled the latest version of the Chanjo2 branch, sorry about that. Will re-try right away.

No worries :)

**Comment by Jakob37** [comment]
Aha, nice, now it seems to work!

Both changing transcripts and the coverage thresholds change the values displayed.

A minor detail is that the coverage threshold is reset to "10x" in the dropdown, but the header is updated anyway so looks like it works like it should.

Before

<img width="668" alt="chanjo2_1_2" src="https://github.com/Clinical-Genomics/scout/assets/7374399/480919c0-ef84-4401-a7f3-bed1c8255a08">

After changing to 20x and just a handful of IDs

<img width="664" alt="chanjo2_1_1" src="https://github.com/Clinical-Genomics/scout/assets/7374399/39fd2d71-5770-4b38-8d8a-b7931528c597">

**Comment by Jakob37** [comment]
Great job 💪
