### ISSUE TITLE
Add igh_dux4 as a caller type for cancer 

### ISSUE THREAD

**Issue by fevac** [Clinical-Genomics/scout#4541]
Add `igh_dux4` to a list of “valid” variant callers for balsamic: https://github.com/Clinical-Genomics/scout/blob/ac165c0463fbf985d54f6764666520c588b04e43/scout/constants/__init__.py#L197

`igh_dux4` is not a caller itself but a custom script that uses samtools to get evidence about these types of events

**Comment by fevac** [comment]
I believe this should be quick. Could someone have a look?

**Comment by dnil** [comment]
Absolutely! Do you have a test/stage case we could look at to see if the variants eg have something more of interest? 
Do you have a preferred display name for the caller, or perhaps a link to it so we can have a look? Cheers!

**Comment by fevac** [comment]
I just sent you the case ID internally
