### ISSUE TITLE
Gnomad v4 link not working for STR variants

### ISSUE THREAD

**Issue by Jakob37** [Clinical-Genomics/scout#4568]
I had a conversation today with our clinical geneticists. One thing they mentioned was that although most of the Gnomad links now correctly get them to Gnomad v4, it seems to not be working for STRs.

I navigated to an STR variant and it did indeed lead to a broken link (inside the Gnomad page).

Not sure whether I can share the actual variant I used, but here is an anonymized link:

```
https://gnomad.broadinstitute.org/variant/X-<pos>-A-%3CSTR23%3E?dataset=gnomad_r4
```

Which landed me on a page like this:

![1_str](https://github.com/Clinical-Genomics/scout/assets/7374399/02d9d764-9937-4341-b358-d9b80b401f4b)

**Comment by dnil** [comment]
Thank you, we will have a look. I guess they changed the URL again - it was working after the last change.. 😊

**Comment by dnil** [comment]
Ah, ok. It is working from the STR variantS page, but not from the variant page! We'll fix.

**Comment by dnil** [comment]
Hihi, np - also the same links are already added and working on the gene links on the variant page:
<img width="304" alt="Screenshot 2024-04-18 at 15 19 09" src="https://github.com/Clinical-Genomics/scout/assets/758570/faa4b4da-7cef-44f2-aebf-b3d7cd550e57">
