### ISSUE TITLE
Improve PDF view of the delivery reports

### ISSUE THREAD

**Issue by ivadym** [Clinical-Genomics/scout#4571]
We are updating the delivery report HTML ([#3118](https://github.com/Clinical-Genomics/cg/pull/3118)), so it would be great to synchronise the changes with the PDF conversion, as I've identified some issues:

- [ ] ~~Switch from landscape to portrait view~~ or reduce zoom of landscape view.
- [ ] Avoid page breaks inside table rows.
- [ ] Avoid page breaks within single lines of text, preventing words from splitting between pages.
- [ ] Fix the rendering of headings, which appear to lose their style during conversion.

**Comment by ivadym** [comment]
I've given up on https://github.com/Clinical-Genomics/scout/pull/4563 because I couldn't resolve most layout issues. While portrait orientation worked, pdfkit is ignoring the zoom argument and other directives added directly in the HTML.

In Balsamic, we also use pdfkit (v1.0.0) for the CNV reports and we found a solution for hte table page break issues [here](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2997). However, Scouts `html_to_pdf_file` seem to not recognise any of these styles from the HTML

**Comment by northwestwitch** [comment]
I can try to help if you want? I'm not an expert of pdfKit but I've written the code of that html_to_pdf_file function. Are the issues:

- Avoid page breaks inside table rows.
- Avoid page breaks within single lines of text, preventing words from splitting between pages.
- Fix the rendering of headings, which appear to lose their style during conversion.

?

**Comment by ivadym** [comment]
Yes, that would be great, thanks!

After trying a couple of things, I think some of the issues, like the headings, could be related to us using Bootstrap. However, we should be able to solve the page breaks. If we need to update the template, I can help you with that.

**Comment by northwestwitch** [comment]
I also think it might be bootstrap stuff. Let me know/tag me on stuff I might help with!

**Comment by ivadym** [comment]
I will close it for now since currently there is no real need to look into this further. To solve this issue, we need to identify whether wkhtmltopdf or Bootstrap is causing the poor rendering. It's a known issue in wkhtmltopdf, as pointed out in previous messages. If it eventually gets resolved, the solution could be as simple as updating to the latest version accordingly.
