### ISSUE TITLE
ClinVar submission dark mode

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#4580]
The dark style got reset again in a few places.
![Screenshot 2024-04-24 at 09 21 17](https://github.com/Clinical-Genomics/scout/assets/758570/8378145b-67e1-42b0-86e5-984c033b6e9b)
![Screenshot 2024-04-24 at 09 21 09](https://github.com/Clinical-Genomics/scout/assets/758570/6275c6a4-0729-4c20-8494-1f7fc0e11334)

**Comment by northwestwitch** [comment]
This is fixwd now. Closing!
