### ISSUE TITLE
ClinVar submission error - variant location for indel

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#4590]
Small indels apparently don't get their start-stop set correctly; perhaps we only use "position" missing adding the variant len to `stop`?
<img width="972" alt="Screenshot 2024-04-24 at 15 03 35" src="https://github.com/Clinical-Genomics/scout/assets/758570/323a09ea-664b-4a14-9315-396b817a0a32">

**Comment by northwestwitch** [comment]
> perhaps we only use "position" missing adding the variant len to `stop`?

That was exactly the case! Opened a PR to fix it
