### ISSUE TITLE
Shall we parse and add to DB obsolete HPO terms?

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#4604]
For instance go to Phenotypes and filter terms using the "obsolete" string. We have 425 of these. If you click on the link that should lead to HPO, the page is blank

**Comment by dnil** [comment]
Good question. They never appear associated to genes, do not link out and oftentimes correspond to entries there was good reason to remove. And we have the ORPHA and OMIM terms to cover for actual disease associations. That is good reason to skip them. Some reasons to keep them would be when they are already used on old cases, and compatibilty with external services (LIMS/orders, phenopackets) which may have a slightly different HPO set.

A compromise could parse them, as long as they are still kept in the HPO-files, but flag them clearly as obsolete - perhaps avoiding link out, and displaying clearly as obsolete on case pages etc?

**Comment by northwestwitch** [comment]
Can also be that HPO marks the obsolete terms as obsolete and they disappear in their next major release or something, so we don't have to do anything at all
