### ISSUE TITLE
Clearer warning for sample sex mismatch

### ISSUE THREAD

**Issue by Jakob37** [Clinical-Genomics/scout#4621]
Another suggestion from our local geneticists.

When the calculated sex doesn't match the assigned, this will be indicated with the lack of a checkbox on the case page.

For them, this is a big red flag, and they would have liked a much clearer warning (i.e. something like filling the background of that table cell with red).

<img width="27" alt="gender_check" src="https://github.com/Clinical-Genomics/scout/assets/7374399/9bbc9955-0027-411f-a8e0-97eef7dbdc44">

I guess this is a very minor task. If you guys think this is a good idea, maybe it could be a good warmup issue for me to contribute with.

**Comment by northwestwitch** [comment]
> I guess this is a very minor task. If you guys think this is a good idea, maybe it could be a good warmup issue for me to contribute with.

That's be great, please do! 🚀
