### ISSUE TITLE
chromograph view

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#4628]
![image](https://github.com/Clinical-Genomics/scout/assets/12525201/cc6b7ce3-fb0f-46dd-b4f5-9110d0fc121d)
  hi, what happend to chromossome 22?

bug?

**Comment by dnil** [comment]
Hi @4WGH! Perhaps your browser timed out while fetching the images? It shows all normal for me. 😿 Can you reproduce it after reloading the page?

![Screenshot 2024-05-16 at 10 58 48](https://github.com/Clinical-Genomics/scout/assets/758570/225bafff-c50a-498a-b384-39c36de47965)

**Comment by 4WGH** [comment]
now it works !!!!

ahha really weird.


Thanks,
Michela
________________________________
Från: Daniel Nilsson ***@***.***>
Skickat: den 16 maj 2024 11:01
Till: Clinical-Genomics/scout ***@***.***>
Kopia: Michela Barbaro ***@***.***>; Mention ***@***.***>
Ämne: Re: [Clinical-Genomics/scout] chromograph view (Issue #4628)


Hi @4WGH<https://github.com/4WGH>! Perhaps your browser timed out while fetching the images? It shows all normal for me. 😿 Can you reproduce it after reloading the page?

Screenshot.2024-05-16.at.10.58.48.png (view on web)<https://github.com/Clinical-Genomics/scout/assets/758570/225bafff-c50a-498a-b384-39c36de47965>

**Comment by dnil** [comment]
Cool! Let's keep an eye on it, but there are many images so I guess one getting lost once is ok. As long as it doesn't happen often!
