### ISSUE TITLE
Lost access to Scout

### ISSUE THREAD

**Issue by Lucpen** [Clinical-Genomics/scout#4649]
Since a couple of days ago I have been unable to log into Scout. I get the message: User not found in Scout database
I usually use the e-mail lucia.pena-perez@clinicalgenomics.se to log in.

**Comment by dnil** [comment]
Hi there! You are still in the db! Perhaps 1) double check you are using that user - its easy to pick the wrong one - and that 2) check that you can still log on to that user with google - else check with the google admin/file a local support ticket/IT issue!

**Comment by dnil** [comment]
Closing for now, but do reopen if it should for some reason persist after the two steps above!
