### ISSUE TITLE
Speeding up case page interactions

### ISSUE THREAD

**Issue by Jakob37** [Clinical-Genomics/scout#4655]
**Is your feature request related to a problem in the current program to new available techology or software? Please describe and add links/citations if appropriate.**

We would like to speed up interactions with the case page, such as adding comments and assigning yourself to the case.

**Describe the solution you'd like**

Possible approaches to speeding up subsequent interactions with the case page:

- Caching the currently active page (and invalidating it when data change or switching page, to avoid ram and outdated data issues).
- Using HTMX to update the UX when for instance adding comments, and doing db interactions asynchronously.

**Describe alternatives you've considered**

The ideal would be to reduce the initial page load time at a Mongo level or initial case load (for instance by having slow calculations precalculated). But suspecting this is hard nut, as this has been on the table for quite some time. Let me know if you have a different view.

**Additional context**

The loading time for certain pages such as the case page is perhaps the most pressing issues for our geneticists, and they constantly mention it. When working in their biggest institute (~5000 cases) a single page interaction does on a good day take ~7 seconds.

We recently tried moving out our mongodb to run "directly on the metal" instead of inside a VM + container. This did not do a huge difference to the case load for us for the case load. So I think we will need to address this somehow.

Here is a case load on a good day (heavily censored, wasn't sure what might be sensitive 😄 )

<img width="1280" alt="scout_performance" src="https://github.com/Clinical-Genomics/scout/assets/7374399/b70de10a-4436-4866-b5f2-58560ff76cc8">

Let us know what you think! I think we in Lund could be able to spend quite some time on helping out exploring this, as it is of such pressing need for us.

**Comment by northwestwitch** [comment]
Hi Jakob, thanks for the explanation! 
The image is a bit tiny and doesn't show if I try to open it in a new tab. But looks like you are measuring the time it takes to load the single components of case page? What's the slowest file to load (I think the one on top?)

**Comment by dnil** [comment]
Hi there! Sounds great with some extra hands - there is plenty fun to do on many fronts. 

I checked a few pages as well now, and note faster times than that, with 16k cases, but quite agree that the case page currently stands out as being sluggish. And agree with your image that the long wait is the first one in the flask view/controller before the main html document outline is in place. Let's start with profiling a bit in detail on the different case page component. I suspect we still could use a few projections for the variantS and panelS that are touched, and as you that some computation regarding eg panels need not be updated quite as often as it is now - by e.g. keeping track of the latest gene and panel changes.

**Comment by dnil** [comment]
On a sidenot you also need to update your certificates - your connections to your server show as unprotected.  ;)

**Comment by Jakob37** [comment]
> The image is a bit tiny and doesn't show if I try to open it in a new tab. But looks like you are measuring the time it takes to load the single components of case page? What's the slowest file to load (I think the one one on top), the case page itself?

Aha I see. I can open it, but see "private-user-images" in the URL. The main page load takes 6045 ms. The only other significant load time is from the images which takes in total ~1000 ms to load.

> I checked a few pages as well now, and note faster times than that, with 16k cases, but quite agree that the case page currently stands out as being sluggish. And agree with your image that the long wait is the first one in the flask view/controller before the main html document outline is in place. Let's start with profiling a bit in detail on the different case page component. I suspect we still could use a few projections for the variantS and panelS that are touched, and as you that some computation regarding eg panels need not be updated quite as often as it is now - by e.g. keeping track of the latest gene and panel changes.

OK yes, that sounds good!

> On a sidenot you also need to update your certificates - your connections to your server show as unprotected. ;)

🫣 Yes, well spotted. We are working right now (far too late) at transitioning to https!

**Comment by northwestwitch** [comment]
Functions to speed up:

- [ ] [Matching causatives](https://github.com/Clinical-Genomics/scout/blob/5c1fff3da03493a4f8e23983ccc4c1f08838ae53/scout/server/blueprints/cases/controllers.py#L1438). Takes most of the time for Lund instance  

- [Default panels](https://github.com/Clinical-Genomics/scout/blob/5c1fff3da03493a4f8e23983ccc4c1f08838ae53/scout/server/blueprints/cases/controllers.py#L521). Takes quite some time and it's the major problem for us

- [Safe genes filter] (https://github.com/Clinical-Genomics/scout/blob/778d58c20124ca5edabc14831662445fd38331e1/scout/adapter/mongo/institute.py#L161).

**Comment by Jakob37** [comment]
Yes, sounds good!
