### ISSUE TITLE
"scout setup demo" is loading also research variants, but they are not shown as a category of available vars on case page

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#4661]
**To Reproduce**
run `scout setup demo`
- Load the case clone of 643594 -> `scout --demo load case scout/demo/643595.config.yaml`
- Go on case 643595 and mark the usual POT1 variant as causative
- Go on case 643594 and see that when matching causatives contains 2 variants instead of one:

<img width="441" alt="image" src="https://github.com/Clinical-Genomics/scout/assets/28093618/153b722d-b3c7-4a3a-ab7f-6fd2f36f46c1">

One is a clinical variant and one is a research variant. 
BUT!
Case 643594 doesn't have research variants links:

<img width="1188" alt="image" src="https://github.com/Clinical-Genomics/scout/assets/28093618/f404d1d2-435a-4011-8c5c-28a14853b0b7">

**Comment by dnil** [comment]
Good catch! And this was from a clean install? Might be an error introduced by #4577 then? 😊

**Comment by northwestwitch** [comment]
> Might be an error introduced by #4577 then?

Yes, I think so
