### ISSUE TITLE
CLI option to link a panel to multiple institutes

### ISSUE THREAD

**Issue by Jakob37** [Clinical-Genomics/scout#4666]
We work with "validation" and "production" institutes, which means we often want to have the same panel linked to these two institutes.

It would be useful to be able to assign a list of institutes both when loading and and when updating the panel.

Right now, we have been assigning lists of institutes directly in mongodb it seems (which seems to be working OK, hopefully it is not a misuse of Scout's db..).

This could be done safer and more conveniently directly at the command line:

```
scout load panel --institute "Institute A" "Institute B"
scout update panel --update-institute "Institute A" "Institute B"
```

Does this make sense? I could take a look at this if you think so.

**Comment by northwestwitch** [comment]
I feel like this has been discussed before but I can't find where. Perhaps it was some meeting.. A workaround would be updating the users that are supposed to update the panel to be collaborating with both institutes. Then the can be assigned as panel maintainers. The drawback is that these users would have access to the cases of both institutes. But if this is finr then this could be a solution?

> Right now, we have been assigning lists of institutes directly in mongodb it seems (which seems to be working OK, hopefully it is not a misuse of Scout's db..).

How are you doing this, turning the institute field into an array os string instead of a string? Seems dangerous to me, but cool if it works, I guess.

<img width="339" alt="image" src="https://github.com/Clinical-Genomics/scout/assets/28093618/e78012f0-f8be-45b7-aec0-6b36b17d5b52">

**Comment by dnil** [comment]
Same here, but I also couldn't find it. The issue for us was research institutes wanting to have easier access to the clinical panels. I think the wooden clog solution became this: https://github.com/Clinical-Genomics/scout/issues/3822, where it's somewhat easy for the user to copy (and modify) a panel between institutes as needed.

In general, both this issue and #4665 reflect how we use a staging instance for testing and validation. Then it is less of an issue to delete test institutes or share panels in validation and production. You could even purge the whole staging instance and start fresh, or copy the prod one/selected parts onto it.

**Comment by Jakob37** [comment]
> I feel like this has been discussed before but I can't find where. Perhaps it was some meeting.. A workaround would be updating the users that are supposed to update the panel to be collaborating with both institutes. Then they can be assigned as panel maintainers. The drawback is that these users would have access to the cases of both institutes. But if this is fine then this could be a solution?

OK I see! Thank you for the context. I'll bring that to discussion here.

> > Right now, we have been assigning lists of institutes directly in mongodb it seems (which seems to be working OK, hopefully it is not a misuse of Scout's db..).
> 
> How are you doing this, by turning the institute field into an array of strings instead of a string? Seems dangerous to me, but cool if it works, I guess.

Yes, it is indeed how it seems we are doing. I am unaware of the history of this though, and asking around noone knew for sure how to do this, just that it was tricky when they set this up once in a time. Looking in the panel page, it appears as expected.

```
> db.gene_panel.findOne({}, {"institute": 1})
{
        "_id" : ObjectId("<ID>"),
        "institute" : [
                "klingen",
                "CMD"
        ]
}
```

But interesting and slightly concerning that it isn't intended as a feature. Might it screw things up somewhere else?

**Comment by Jakob37** [comment]
> Same here, but I also couldn't find it. The issue for us was research institutes wanting to have easier access to the clinical panels. I think the wooden clog solution became this: #3822, where it's somewhat easy for the user to copy (and modify) a panel between institutes as needed.

OK I see! Yes, it seems convenient to load a new panel with the same genes. Maybe that is fine for us as well.

> In general, both this issue and #4665 reflect how we use a staging instance for testing and validation. Then it is less of an issue to delete test institutes or share panels in validation and production. You could even purge the whole staging instance and start fresh, or copy the prod one/selected parts onto it.

Aha, yes, that makes sense. It seems like a more clean way to do things.

These two issues are not something pressing here, just points of convenience (at least at the moment). Thanks for enlightening me. I'll bring it to discussion here locally.

**Comment by northwestwitch** [comment]
> ```
> > db.gene_panel.findOne({}, {"institute": 1})
> {
>         "_id" : ObjectId("<ID>"),
>         "institute" : [
>                 "klingen",
>                 "CMD"
>         ]
> }
> ```
> 
> 
>     
>   
> 
> But interesting and slightly concerning that it isn't intended as a feature. Might it screw things up somewhere else?

It has the potential, but if the application hasn't crashed yet then you are probably fine 😄

**Comment by Jakob37** [comment]
As this one seems "off the map" right now, I'm closing.

**Comment by Jakob37** [comment]
I have a follow up on this question. We have now a situation where a bunch of panels needs to be shared across two separate production institutes.

This would be possible by uploading copies of all panels to both institutes. This would require extra work with all future updates though, to make sure all panels are updated in all places.

Alternatively (as we are doing for other panels right now), have the institute link to multiple panels as shown in the comment above. I am a bit concerned about this approach though, as you said before, this is currently not a "blessed feature" in Scout.

Do you think it could become an officially supported feature, to link multiple institutes for one panel? Or is the "wooden clog"-solution as mentioned above of export -> import (and continue doing so with future updates), the recommended way to go?

**Comment by northwestwitch** [comment]
> I have a follow up on this question. We have now a situation where a bunch of panels needs to be shared across two separate production institutes.

We have this situation as well in Stockholm: more than one institute is filtering the uploaded variants using a gene panel from another institute. The important is that the panel id is specified in the config file and it will be used regardless of the specific institute of the case. 

In the situation where users from different institutes want to contribute to the same panel, then I'd assign them all as panel maintainers, so they have access.

Would this solution work?

**Comment by Jakob37** [comment]
> We have this situation as well in Stockholm: more than one institute is filtering the uploaded variants using a gene panel from another institute. The important is that the panel id is specified in the config file and it will be used regardless of the specific institute of the case.

Hmm, aha, I see! So what you are saying is this:

* Panels are not constrained by its institute, they just have a "home" institutes.
* Panels outside the case institute can be used as well, simply by including them in the panel list in the yaml when loading cases.

Yes, I think this would work fine for us. The clinician who is maintaining the lists has access to both institutes. We would just need to update the script that pulls out what panels to include in the yaml to include this extra set of panels outside those contained in the institute. A bit messy, but should be OK.

Do you have a recommended way to add more panels to an already existing case? If we for instance want to add these panels to cases that already have been loaded. Previously I think we have either reloaded the whole case, or worked directly with the db (which I would like to avoid). I don't see any option for this in the `scout update case` CLI. Would it make sense to add `--add-panel` and `--remove-panel` flags? (I can open an issue).

Thanks 🙏

**Comment by northwestwitch** [comment]
> Hmm, aha, I see! So what you are saying is this:
> 
> * Panels are not constrained by its institute, they just have a "home" institutes.
> * Panels outside the case institute can be used as well, simply by including them in the panel list in the yaml when loading cases.

Exactly!

> We would just need to update the script that pulls out what panels to include in the yaml to include this extra set of panels outside those contained in the institute. A bit messy, but should be OK.

Yes, that would work.

>Do you have a recommended way to add more panels to an already existing case? If we for instance want to add these panels to cases that already have been loaded. Previously I think we have either reloaded the whole case, or worked directly with the db (which I would like to avoid). I don't see any option for this in the scout update case CLI. Would it make sense to add --add-panel and --remove-panel flags? (I can open an issue).

If the case has been already loaded then it's missing variants from the new panel, I guess, so it needs to be re-uploaded. I'd also avoid directly touching the database. 
We could add a cli command to update the panel in the case document, then you'd need to run the cli to re-upload the variants, both SNVs and SVs and whichever other type you have. Keep in mind that if you were to re-upload the case entirely in the future then you still have to change the .yaml config file.

For this reason I think **I'd rather directly edit the .yaml config file by adding the new panel(s) in it and then re-upload the case**. Comments/user actions performed on the variants will still be available after you re-upload the case. Like this:

`scout load case --update --keep-actions <path-2-config-file>`

**Comment by Jakob37** [comment]
> For this reason I think I'd rather directly edit the .yaml config file by adding the new panel(s) in it and then re-upload the case. Comments/user actions performed on the variants will still be available after you re-upload the case. Like this:
>
>scout load case --update --keep-actions <path-2-config-file>

OK I see! Didn't know about the `--update` and `--keep-actions` flag. I learned a lot here 😄 Will forward it to the other Scout-involved BNFs here in Lund as well.

I think we are using a catch-all panel to make sure all genes get in either way (for wgs), meaning that the genes would be there even if the panel isn't added. So we would not run into the issue you mention.

But I think the approach you outline above seems to nicely cover our needs. Let's stick with that.

Thanks again!

**Comment by northwestwitch** [comment]
> OK I see! Didn't know about the `--update` and `--keep-actions` flag. I learned a lot here 😄 Will forward it to the other Scout-involved BNFs here in Lund as well.

You need to have the --update flag if you are re-uploading because otherwise the upload will fail (it will say something like: the case is already present in the database). You can also omit the `--keep-actions` flag because it's the default behaviour, but better to specify it,  think!

You're welcome, nice that we found a solution!

**Comment by Jakob37** [comment]
Me and @alkc discussed a bit. Currently we assign the full set of panels within institutes to each loaded case (I realize this is a bit different from how you guys in Stockholm work). We automatically pull out this list by getting the latest version of each panel within the institute.

One way forward would be to maintain lists of panels that should be included from outside the case institute. This would work, and is our current fallback.

Something that would make things fully scriptable, and less error prone (and make it possible for the panel maintainers to do this without hunting down us BNFs), would be to have an optional drop-down on the panel page where "additional institutes" could be selected.

I.e. a drop-down multi-select on this page:

![panels_extra_fields](https://github.com/user-attachments/assets/700457ec-b05f-4f43-a59c-e51a1119cc15)

It would be kind of a tag, an expression of intent for the user. But also something we could work with from outside Scout.

What do you think? Would this be useful for you guys as well, or would it be a too Lund-customized solution? 😄

**Comment by northwestwitch** [comment]
> or would it be a too Lund-customized solution? 😄

Honestly, yes 😆 

I don't think we would have a use for such a setup. And it might even be confusing for the users that look at the panel, because it's not immediately clear why there might be selected institutes when the panel could be used by all institutes anyway.

We have a different system here, where users that order an analysis in the oder portal have a multiselect where they can choose which panels they want to run the analysis with. But I understand your situation. 🤔 

There is your current solution: a master list with all shared panels - this could be inserted into a database perhaps?

Other possible solutions:
- Edit the panel description by adding a list of institutes the panel will be used in. So you can parse the description when you collect the panels in your script
- Create a fake maintainer to be used by your script when collecting the panels, something like automation@whatever.com. Your script will collect all the panels with that maintainer?
- ??

**Comment by Jakob37** [comment]
> > or would it be a too Lund-customized solution? 😄
> 
> Honestly, yes 😆

I understand. It was worth a try 😅 We'll look into some other solution.

> I don't think we would have a use for such a setup. And it might even be confusing for the users that look at the panel, because it's not immediately clear why there might be selected institutes when the panel could be used by all institutes anyway.
> 
> We have a different system here, where users that order an analysis in the oder portal have a multiselect where they can choose which panels they want to run the analysis with. But I understand your situation. 🤔
> 
> There is your current solution: a master list with all shared panels - this could be inserted into a database perhaps?
> 
> Other possible solutions:
> 
>     * Edit the panel description by adding a list of institutes the panel will be used in. So you can parse the description when you collect the panels in your script
> 
>     * Create a fake maintainer to be used by your script when collecting the panels, something like [automation@whatever.com](mailto:automation@whatever.com). Your script will collect all the panels with that maintainer?
> 
>     * ??

Nice food for thought 🥗 We'll ponder!
