### ISSUE TITLE
Overlapping SV variant type on variant page

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#467]
Would be niffy. As it is, its is kind of hard to guess what is going on w/o clicking the link.

**Comment by moonso** [comment]
Sure that should be no problems

**Comment by dnil** [comment]
Actually, I can fix it myself! :)

**Comment by moonso** [comment]
Could you rebase the pull request @dnil ? (Sorry for being slow on merging)

**Comment by dnil** [comment]
No worries - you know how I love rebasing..
