### ISSUE TITLE
When updating the OMIM panel with --force, update also the date

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#4670]
Description of the issue:

- Given that you have an old OMIM gene panel (for instance a month old)
- Given that you have the downloaded files to create that panel

If a month later you want to create a new OMIM panel using the same files, if you run the command with --force you end up in a new panel with the same date as the old panel. This is wrong, because if for instance you had a bug in gene panel loading you end up with 2 panels with different genes that seem created the same day but they're not ---> See for instance [this example](https://github.com/Clinical-Genomics/scout/pull/4667#issuecomment-2158065547)

**Comment by dnil** [comment]
Agreed. It kind of makes sense when downloading one day for verification, then performing the live update the next day, but the principle is questionable, and can be made to look silly if updating with really old files. One could add an option to control the behaviour, but I don't know that we need it that fine grained right now. Let's go with `now()` until we have a proper use case for reusing the file dates.

**Comment by northwestwitch** [comment]
I think I'm going to close this issue. 

In situations like [this one](https://github.com/Clinical-Genomics/scout/pull/4667#issuecomment-2158065547), one can see that it's the same version but different in term of genes, so it should be clear enough I think. Otherwise updating the date to the current date when one updates the panel is going to mess up the system we have in place (we are using panel date as reference for the OMIM version of the loaded panel).
