### ISSUE TITLE
nf-core/raredisease MT variants loading

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#4672]
**Describe the bug**
MT vars from `nf-core/raredisease` not displaying.

**To Reproduce**

Load split out MT VCFs 
```scout load case -u scout_load.funkitten.yaml```
![Screenshot 2024-06-10 at 15 07 01](https://github.com/Clinical-Genomics/scout/assets/758570/aa75a753-857f-4a53-bb3b-de05067a87c2)
...
![Screenshot 2024-06-10 at 15 07 58](https://github.com/Clinical-Genomics/scout/assets/758570/dcf906d0-5924-42d2-ae13-1db237217545)
99 MT vars show inserted BUT no MT vars appear when filtering?!
![Screenshot 2024-06-10 at 15 13 00](https://github.com/Clinical-Genomics/scout/assets/758570/6cbd03fe-1d9a-4b2b-9a73-897155222c8a)
Chromosome naming, ranking or load error?

**Comment by dnil** [comment]
The variants appear to have contig MT so all good, but few with decent rank score...

**Comment by northwestwitch** [comment]
> The variants appear to have contig MT so all good, but few with decent rank score...

Perhaps the counter doesn't update then!

**Comment by dnil** [comment]
They are loaded at least:
<img width="442" alt="Screenshot 2024-06-10 at 15 29 13" src="https://github.com/Clinical-Genomics/scout/assets/758570/c0f639a7-c0f8-4f04-9a81-02c8d769dbd9">
And it shouldn't be the scores, we are committed to loading all on CHROM "MT".

**Comment by dnil** [comment]
False alarm! When unchecking panel, and showing also variants from unaffected individuals only, all is good:
![Screenshot 2024-06-10 at 15 35 11](https://github.com/Clinical-Genomics/scout/assets/758570/df857658-53fe-4c99-927c-ce34db633afc)
