### ISSUE TITLE
Add MSI score for tumor-normal cases

### ISSUE THREAD

**Issue by khurrammaqbool** [Clinical-Genomics/scout#4690]
Scout had a field to show MSI score. BALSAMIC added MSIsensor-pro to compute the MSI score that can now be added to Scout.
![image](https://github.com/Clinical-Genomics/scout/assets/5569347/c91c5415-6db3-4265-8abc-c58d49e0e715)

**Describe the solution you'd like**
MSIsensor-pro is added for tumor-normal cases in BALSAMIC workflows, which generates a TXT file given below:
```
Total_Number_of_Sites   Number_of_Somatic_Sites %
938254  10390   1.11
```
Where the last column (%) is the MSI score, which can be parsed to be shown in Scout.

**Describe alternatives you've considered**

**Additional context**

**Comment by dnil** [comment]
Hi, you can find instructions on how to load the MSI value here: https://clinical-genomics.github.io/scout/admin-guide/load-config/, I guess for Balsamic passed on via CG here: https://github.com/Clinical-Genomics/cg/blob/bbe5c6d396a7d8fcc88dd24b3c3dfc9547d4bf19/cg/models/scout/scout_load_config.py#L70. Unless you want to parse other values from that file I don’t see a good reason to change the number on the sample level for a file name on the same and add a parser? Closing this for now, but don’t be afraid to argue it and reopen if I missed something! Cheers!
