### ISSUE TITLE
REVEL score not reported if not present in the first CSQ-field transcript

### ISSUE THREAD

**Issue by Jakob37** [Clinical-Genomics/scout#4693]
**Describe the bug**

We have found that some variants do not display their REVEL_score in Scout, despite it being present for CSQ-field transcripts.

We retrieve these values using VEP and the `dbNSFP` plugin, using the `transcript_match=1` setting. This sometimes gives different REVEL_scores for different transcript, but can also lead to no REVEL_score being assigned for certain transcripts.

Here is one example, with subsets of one CSQ entry shown per row. Here the REVEL_score is present, but not for the first transcript. No score is thus shown in Scout.

```
Chrom  Pos       Allele  Feature          MANE_SELECT  REVEL_rankscore  REVEL_score
1      21890003  G/T     ENST00000374673               0.56024
1      21890003  G/T     ENST00000374695  NM_005529.7  0.56024          0.251
1      21890003  G/T     NM_001291860.2                0.56024
1      21890003  G/T     NM_005529.7                   0.56024
1      21890003  G/T     XM_011541318.2                0.56024
1      21890003  G/T     XM_017001120.1                0.56024
1      21890003  G/T     XM_017001121.1                0.56024
1      21890003  G/T     XM_017001122.1                0.56024
```

Digging around in the Scout source code, I found that it indeed seems to be selecting `REVEL_score` from the first transcript:

https://github.com/Clinical-Genomics/scout/blob/2373185c2c9d71cd1bbdaaba9add232d316612d1/scout/parse/variant/variant.py#L230-L233

What do you think. Do you have the same issue? Would it make sense to take the highest score, or the score on the MANE_SELECT instead? Or does Scout expect all transcripts to have the same REVEL_score, i.e. this should be fixed upstream.

**Comment by dnil** [comment]
Hi, thank you! It seems very nice to parse out the MANE_SELECT, or given that it is missing the highest scoring! It may have been different in older VEP, but the logic may also just be based around several other scores like CADD that are annotated only on the transcript level, but with the same value on all transcripts. We'll check what we currently have on VCFs but at the very least this is a good feature, if not a bug.

**Comment by dnil** [comment]
Ah, note e.g. that you have a fixed `REVEL_rankscore` on all transcripts, which I guess used to be the only one shown. I think that might have informed the "selection". 😸

**Comment by Jakob37** [comment]
Great, thanks :)

**Comment by northwestwitch** [comment]
I've create a PR for this issue. You can review it @Jakob37 when you are back to work and have time! :)
