### ISSUE TITLE
Allow toggling display of hidden panels for normal users

### ISSUE THREAD

**Issue by Jakob37** [Clinical-Genomics/scout#4696]
Conversation continued from #4695

@Jakob37 writes:

> A separate but related point which I am not sure whether an issue or not, is that while I can see the removed panels using "Hide removed panels", our lead geneticsts could not. When she clicked that button for the same institute for which I could see removed panels, nothing happened for her. She tested also in my browser with her account, so seems to be a user setting.
> 
> Is it only admin that could see the removed panels? It would be useful for her to be able to see them.

@dnil writes:

> Not being able to see the removed panels is at least partly apparently by design; the same `shall_display_panel()` is used, so if a panel is not visible, a user needs to have write access, which they only have to panels they are `maintainer` for, unless they are admins. I see no harm in showing these on request: on the panelS page, the option indicates they can already select if they want that extra clutter! They should still not be able to restore it without "write" permissions for it naturally. But yeah, let's make a new issue to keep the conversations easier to follow! 😅

**Comment by Jakob37** [comment]
> I see no harm in showing these on request: on the panelS page, the option indicates they can already select if they want that extra clutter! They should still not be able to restore it without "write" permissions for it naturally.

Yes, as you say the UI right now indicates that it would be possible. This is maybe not a critical feature, but something that our geneticists would appreciate, to be able to keep track of the different versions they have used for their panels.

Makes sense to require write permission to restore it.

**Comment by dnil** [comment]
And also seems quite correct to display it, regardless of write permissions! Visually inactivating the restore button must be better than fully hiding for users without permission.
