### ISSUE TITLE
Download DROP results from Scout

### ISSUE THREAD

**Issue by Lucpen** [Clinical-Genomics/scout#4701]
**Is your feature request related to a problem in the current program to new available techology or software? Please describe and add links/citations if appropriate.**
It would be great if the results from DROP could be downloaded from Scout so that they could be saved in LIMS if necessary

**Describe the solution you'd like**
A downloadable file containing DROP results

**Describe alternatives you've considered**

**Additional context**

**Comment by dnil** [comment]
Sure thing! A list of fileds the users are interested in would be appreciated!

**Comment by Lucpen** [comment]
These columns could be removed for both FRASER and OUTRIDER (PAIRED_END	DNA_ID,	DROP_GROUP,	SPLICE_COUNTS_DIR,	HPO_TERMS,	GENE_COUNTS_FILE,	GENE_ANNOTATION and	GENOME	isExternal)

**Comment by dnil** [comment]
The way this works is we write new files from db with whatever we parsed from the original file from the start, that was deemed useful throughout the diagnostic process. Thank you for those; I have a feeling there are a few more. I e.g. doubt you need both nonsplitProportion and nonsplitProportion_99quantile, abberant, AberrantBySample, or really ever AberrantByGene, but it could very well just be my ignorance shining through!

We'll make a suggestion for you and you can add back any columns that have a diagnostic use that we missed! 😊
