### ISSUE TITLE
In Scout DROP results are viewed with ACC numbers

### ISSUE THREAD

**Issue by Lucpen** [Clinical-Genomics/scout#4702]
**Is your feature request related to a problem in the current program to new available techology or software? Please describe and add links/citations if appropriate.**
It would be great if they were seen with the sample ID instead, as on the vcfs. It is related to this [issue](https://github.com/Clinical-Genomics/cg/issues/3368#issuecomment-2206437460)

**Describe the solution you'd like**
View sample ID instead of ACC number in DROP results

**Describe alternatives you've considered**

**Additional context**

**Comment by dnil** [comment]
Maybe Im missing something, but this seems like a pure LIMS and/or integration issue, if any? When the proper names/ids are given as `sample_name` and `sample_id` all should be good? We can double check, but note that the particular demo case we used `legalpecock` had really odd sample display names after downsampling of the original samples.

**Comment by Lucpen** [comment]
ok, then that might be the issue. If it is a normal case, I guess that the sample id (such as 26567-I-1A) would be seen, right?

**Comment by dnil** [comment]
Yes, the sample/individual display name (the customer provided one) would be used. It's the same logic as all pipelines. Use customer names where the customer is reading, and internal ids during pipeline processing as far as possible, exposing the key connection only where relevant.
