### ISSUE TITLE
MT (eklipse) display in Scout with RareDisease pipeline

### ISSUE THREAD

**Issue by Lucpen** [Clinical-Genomics/scout#4703]
**Is your feature request related to a problem in the current program to new available techology or software? Please describe and add links/citations if appropriate.**
It would be great to have access to the eklipse output on a sample by sample basis. It consist of an image and 2 tables per sample. It would be great to be able to download the tables so that they can be placed in LIMS if relevant to the case

**Describe the solution you'd like**
Be able to see and downlaod eklipse results sample by sample

**Describe alternatives you've considered**

**Additional context**

**Comment by Lucpen** [comment]
Here are the file name and headers:
- eKLIPse_earlycasualcaiman_deletions.csv
`"Title";"5' breakpoint";"3' breakpoint";"Freq";"Freq For";"Freq Rev";"5' Blast";"3' Blast";"5' Depth";"3' Depth";"Repetition"`
-eKLIPse_earlycasualcaiman_genes.csv
`"Gene";"Start";"End";"Type","earlycasualcaiman"`

**Comment by dnil** [comment]
It kind of looks like a very early stage of building towards an SV caller for MT? Wouldn't it be more relevant to get back when they produce VCFs? Did they resume work on the tool by the way - it kind of paused there after some student left?

**Comment by dnil** [comment]
I would prefer closing this as wont fix. The data in the first csv could be annotated a little bit better and then made VCF instead. Then it would both parse automagically in scout, and also could be combined with the other sv callers, local frequency collected in loqus etc. And if all that happens is someone taking a cursory look, then the images should be enough? But again, please explain the use cases, and we could work with what is given. It further complicates things that the tool is unmaintained. I am not happy about providing that to the clinic side.

**Comment by dnil** [comment]
Oh, and to be clear, eKLIPse images can and is already shown in scout per sample from some pipelines, as general images on the case.
