### ISSUE TITLE
names lost in comments and activity list

### ISSUE THREAD

**Issue by 1ctw** [Clinical-Genomics/scout#471]
The usernames are lost in the comments and activity list after the update.

**Comment by robinandeer** [comment]
Hej,

this is known and we have corrected for it - can you point to a case where the issue still persists?

**Comment by 1ctw** [comment]
Hej Robin!

Jag ser det i 15065 men det kanske finns fler som har samma problem

Mvh
Helene

Helene Bruhn
Sjukhuskemist
Centrum för medfödda metabola sjukdomar, L7:05
Karolinska Universitetssjukhuset, Solna
171 76 Stockholm
Tel 08-517 714 51

Helene Bruhn
Doktorand
Avdelningen för Molekylär metabolism
Institutionen för medicinsk biokemi och biofysik (MBB)
Karolinska Institutet

Från: Robin Andeer [mailto:notifications@github.com]
Skickat: den 11 april 2017 15:17
Till: Clinical-Genomics/scout <scout@noreply.github.com>
Kopia: 1ctw <helene.bruhn@karolinska.se>; Author <author@noreply.github.com>
Ämne: Re: [Clinical-Genomics/scout] names lost in comments and activity list (#471)


Hej,

this is known and we have corrected for it - can you point to a case where the issue still persists?

**Comment by moonso** [comment]
Hi,

seems to work now so I'm closing this. Please reopen if there are similar problems

**Comment by moonso** [comment]
Fixed now!!
