### ISSUE TITLE
NOt possible to DELETE a comment

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#4713]
![image](https://github.com/user-attachments/assets/0459a713-4d7e-4ee7-8866-d3006324465e)

The possiblity to delete a comment has diseappeared. 
At case and variant level

**Comment by northwestwitch** [comment]
We have modified that code recently, must have happened then. I'll check it
out tomorrow!

Chiara

**Comment by northwestwitch** [comment]
Ah it's the icon that is no longer visible, but the button is there. Will fix!

**Comment by northwestwitch** [comment]
Other code affected that is using the same icon:

### Remove case from case group:

<img width="958" alt="image" src="https://github.com/user-attachments/assets/53f25809-0947-43da-ac34-d3f7ade1e256">

### Un-assign user:

<img width="450" alt="image" src="https://github.com/user-attachments/assets/8951b2b3-10ca-420c-9e6d-2ef257fd5755">

### Remove pinned or causative from case page:

<img width="922" alt="image" src="https://github.com/user-attachments/assets/ab2d847c-6bfa-4db2-84a3-8e8ed652d9ed">

**Comment by 4WGH** [comment]
maybe connected to this bug 
![image](https://github.com/user-attachments/assets/84453c55-ca28-487d-bebd-b3ff845fbb76)
  I can not edit......the window I want to edit pop up empty

**Comment by northwestwitch** [comment]
> I can not edit......the window I want to edit pop up empty

Mmm I've tested on that case and it works for me. Perhaps it's a matter of different browser (I'm using chrome) which browser are you on again?

**Comment by 4WGH** [comment]
I use edge. not it works for me too, sorry!

**Comment by northwestwitch** [comment]
> I use edge. not it works for me too, sorry!

No problem! 😆
