### ISSUE TITLE
Missing OMIM entries on variant page, which are present in hover

### ISSUE THREAD

**Issue by Jakob37** [Clinical-Genomics/scout#4718]
**Describe the bug**

In the variants page, for one variant, when hovering over the gene name, three OMIM entries are displayed (these match what is present on the OMIM page).

![omim_hover](https://github.com/user-attachments/assets/7aec6e92-9d9d-49dd-b10b-22e2a15bae3d)

On the variant page, only one of these OMIM phenotypes are listed.

![omim_gene](https://github.com/user-attachments/assets/b1d16ca4-feb6-47ae-90f1-13b16dfa32ee)

This was reported to me from a geneticist, who was surprised to see two entries missing from the variant page but not from the hover.

On the OMIM page (https://omim.org/entry/104155) three entries are shown

![omim_web](https://github.com/user-attachments/assets/9921885f-f337-49bd-ae71-3d2ed621b5ac)

Is it a bug, or somehow expected?

**Comment by northwestwitch** [comment]
Which scout version are you using? 

Tested on the latest and we see this:

<img width="537" alt="image" src="https://github.com/user-attachments/assets/eb81c8a5-ff3a-435a-ab15-9262f3229ad6">

**Comment by Jakob37** [comment]
We are running 4.81, but I see the same in our dev instance (running one of the latest PRs, based on 4.84).

We might not have updated OMIM in a bit though, which we will do soon when people are back from vacation. Maybe we can see if the difference is still there after the update.

But I find it strange anyway that we see different entries in the two locations 🤔

**Comment by northwestwitch** [comment]
> But I find it strange anyway that we see different entries in the two locations 🤔

Yes, that's weird, especially because the 3 OMIM terms are shown when you hover on the gene on variantS page.. 🤔

**Comment by northwestwitch** [comment]
We should check for differences in the code probably. Might have to do with different builds? 🤔

**Comment by northwestwitch** [comment]
Labelling it as bug (I have a bad feeling about this one 😄)

**Comment by northwestwitch** [comment]
Do you have the possibility to check in the database, how does the gene in build 38 look like? 

<img width="1020" alt="image" src="https://github.com/user-attachments/assets/00390846-f8be-4c91-949d-b46c09ce2a7a">

**Comment by Jakob37** [comment]
Hmm, interesting. Here it only looks like one phenotype:

```
> db.hgnc_gene.findOne({"hgnc_symbol": "ZFHX3"})
{
        "_id" : ObjectId("5e7150ab37075218cb46d6da"),
        "hgnc_id" : 777,
        "hgnc_symbol" : "ZFHX3",
        "ensembl_id" : "ENSG00000140836",
        "chromosome" : "16",
        "start" : 72816784,
        "end" : 73093597,
        "length" : 276813,
        "description" : "zinc finger homeobox 3",
        "aliases" : [
                "FLJ26184",
                "ZNF927",
                "C16orf47",
                "ZFHX3",
                "ATBF1"
        ],
        "primary_transcripts" : [
                "NM_006885"
        ],
        "phenotypes" : [
                {
                        "mim_number" : 176807,
                        "description" : "Prostate cancer somatic",
                        "inheritance_models" : [ ],
                        "status" : "established"
                }
        ],
        "entrez_id" : 463,
        "omim_id" : 104155,
        "ucsc_id" : "uc002fck.4",
        "uniprot_ids" : [
                "Q15911"
        ],
        "vega_id" : "OTTHUMG00000137599",
        "pli_score" : 0.999999999859262,
        "incomplete_penetrance" : false,
        "build" : "37"
}
```

Also interested in why we have build 37, and whether that might be an issue..

**Comment by Jakob37** [comment]
Aha, that is because of my `findOne`. Looks like we have build 38 as well. Here three phenotypes.

```
{
  "hgnc_id": 777,
  "hgnc_symbol": "ZFHX3",
  "ensembl_id": "ENSG00000140836",
  "chromosome": "16",
  "start": 72782885,
  "end": 73891871,
  "length": 1108986,
  "description": "zinc finger homeobox 3",
  "aliases": [
    "ZNF927",
    "ZFHX3",
    "C16orf47",
    "ATBF1",
    "FLJ26184"
  ],
  "primary_transcripts": [
    "NM_006885"
  ],
  "inheritance_models": [
    "AD"
  ],
  "phenotypes": [
    {
      "mim_number": 176807,
      "description": "Prostate cancer somatic",
      "inheritance_models": [],
      "status": "established"
    },
    {
      "mim_number": 613055,
      "description": "Atrial fibrillation 8 susceptibility to",
      "inheritance_models": [
        "AD"
      ],
      "status": "susceptibility"
    },
    {
      "mim_number": 600223,
      "description": "Spinocerebellar ataxia 4",
      "inheritance_models": [
        "AD"
      ],
      "status": "established"
    }
  ],
  "entrez_id": 463,
  "omim_id": 104155,
  "ucsc_id": "uc002fck.4",
  "uniprot_ids": [
    "Q15911"
  ],
  "vega_id": "OTTHUMG00000137599",
  "pli_score": 1,
  "incomplete_penetrance": false,
  "build": "38",
  "constraint_lof_oe": 0.14639,
  "constraint_lof_oe_ci_lower": 0.113,
  "constraint_lof_oe_ci_upper": 0.189,
  "constraint_lof_z": 12.237,
  "constraint_mis_oe": 1.0077,
  "constraint_mis_oe_ci_lower": 0.983,
  "constraint_mis_oe_ci_upper": 1.031,
  "constraint_mis_z": -0.19639
}
```

**Comment by northwestwitch** [comment]
> Also interested in why we have build 37, and whether that might be an issue..

It's OK, we had build 38 even before having data in build 38.

BUUT this means that the data in the hover is taken from build 37, which is wrong (so bug label is correct). 
I think the issue should be solved on variant page if you update the genes tho.

**Comment by Jakob37** [comment]
OK I see!

**Comment by northwestwitch** [comment]
> OK I see!
> 
> Looks like the hover is correct though, so from 38. While the one on the variant page is from 37.

Ah yes, the other way around. Bug it is. I'll work on it tomorrow! Thanks for reporting!

**Comment by northwestwitch** [comment]
I'm trying to reproduce it locally so we can test with the demo sample. What about the variant document, how does `genes` look like in there?

**Comment by Jakob37** [comment]
> I'm trying to reproduce it locally so we can test with the demo samples. What about the variant document, how does `genes` look like in there?

I'll check! 

The ID in the URL, i.e. "ID" in `http://cmdscout2.lund.skane.se/<institute>/<case>/<ID>`. Is this the "document_id" in the variant collection? (It takes quite some time to do lookups in our variant collection, just want to make sure I am looking for the right one :) )

**Comment by northwestwitch** [comment]
Yes, or directly the _id. Consider installing a GUI to make it easier --> https://www.mongodb.com/products/tools/compass

**Comment by Jakob37** [comment]
> Yes, or directly the _id. Consider installing a GUI to make it easier --> https://www.mongodb.com/products/tools/compass

Aha, I see! I'll try it. It didn't complete after half an hour search for the "document_id" now 🤔 Maybe "_id" is indexed differently, will try.

Thank you for the tip! I have used it previously, but not for the Scout db. Sounds like a good idea to set it up.

**Comment by Jakob37** [comment]
I haven't managed to get the variant data yet, sorry. Will have to try again when Scout isn't in action, extra slow for the geneticists today.

The `disease_term` query returned quickly though. Here is the result:

```
db.disease_term.find({"genes": 777})
{ "_id" : "OMIM:176807", "disease_id" : "OMIM:176807", "disease_nr" : 176807, "description" : "Prostate cancer somatic", "source" : "OMIM", "genes" : [ 644, 777, 6762, 1101, 7534, 16627, 9588, 1748, 2235 ], "inheritance" : [ "AD" ], "hpo_terms"
 : [ "HP:0000006", "HP:0000812", "HP:0007379", "HP:0001428", "HP:0008775", "HP:0010787", "HP:0000078", "HP:0002664", "HP:0011793", "HP:0000022", "HP:0012125", "HP:0033019", "HP:0010461", "HP:0034345", "HP:0000119", "HP:0012243", "HP:0034335", "
HP:0100787" ] }
```

Looks like we only have one entry here.

**Comment by northwestwitch** [comment]
> The `disease_term` query returned quickly though. Here is the result:
> 
> ```
> > db.disease_term.find({"genes": 777})
> { "_id" : "OMIM:176807", "disease_id" : "OMIM:176807", "disease_nr" : 176807, "description" : "Prostate cancer somatic", "source" : "OMIM", "genes" : [ 644, 777, 6762, 1101, 7534, 16627, 9588, 1748, 2235 ], "inheritance" : [ "AD" ], "hpo_terms"
>  : [ "HP:0000006", "HP:0000812", "HP:0007379", "HP:0001428", "HP:0008775", "HP:0010787", "HP:0000078", "HP:0002664", "HP:0011793", "HP:0000022", "HP:0012125", "HP:0033019", "HP:0010461", "HP:0034345", "HP:0000119", "HP:0012243", "HP:0034335", "
> HP:0100787" ] }
> ```
> 
> Looks like we only have one entry here.

OK! Then I think the issue might be simply that you have to update the database with the latest genes and diseases. Here in Solna we try to do regular updates, in general soon after we get notified the HPO updates are available, see our usual update procedure: https://github.com/Clinical-Genomics/scout/issues/4572#issuecomment-2099996595

**Comment by Jakob37** [comment]
Aha, I see! Thank you for finding it out. Yes, I haven't been involved in the updating previously, but will bring this to discussion. We should definitely look into doing regular updating.

Closing this issue then.

But still curious about the mismatch. Why is there only one entry in this collection while being two in the other? I.e. is it due to us having done an incomplete update or something else.

**Comment by northwestwitch** [comment]
> But still curious about the mismatch. Why is there only one entry in this collection while being two in the other? I.e. is it due to us having done an incomplete update or something else.

What comes to my mind is that the 2 missing diagnoses were associated with the genes only recently, specifically:

Atrial Fibrillation 8 in 2023 and Spinocerebellar Ataxia 4 in 2024, see also in [the OMIM page of the gene](https://www.omim.org/entry/104155?search=zfhx3&highlight=zfhx3):

<img width="811" alt="image" src="https://github.com/user-attachments/assets/c8c095ca-866a-4f51-9e76-b2e0d50ec67f">

**Comment by Jakob37** [comment]
OK, I see! Maybe we only have done a partial update then recently. Will look into it. Thanks again for digging and enlightening me here.
