### ISSUE TITLE
Add CoLoRSdb and gnomAD keys

### ISSUE THREAD

**Issue by fellen31** [Clinical-Genomics/scout#4742]
Would it be a good idea to add allele frequencies from [Consortium of Long Read Sequencing Database (CoLoRSdb)](https://zenodo.org/records/13145123), preferably as `colorsdb_af`? 

Could I also get `gnomad_af` and `gnomad_popmax_af` added as gnomAD keys? 😃

**Comment by dnil** [comment]
Yes, let's CoLoRSdb. Is the lower case string its standard key?

And what's with the gnomAD lower case INFO keys? 😆 Is this from a new VEP version, or are you freestyling a little? Could we expect to see them from other pipes as well?

**Comment by dnil** [comment]
Don't get me wrong, it does make sense - Im pretty annoyed with things like `gnomADg_AF_POPMAX` - not to mention happy not to have to add a case sensitive `CoLoRSdb`. 😄

**Comment by fellen31** [comment]
The lowercase gnomAD keys come from using [echtvar](https://github.com/brentp/echtvar) instead of VEP to add the frequencies. They supply a pre-encoded gnomad database at a handy size (~7 GB), where the keys are encoded as lowercase. 

The CoLoRSdb VCF key is `AF` so I set it to `colorsdb_af`.

**Comment by dnil** [comment]
Supporting Brents stuff out of the box sounds nice, and following the pattern for CoLoRSdb seems like a plan. It will be the first set of AFs that don't end in capital AF. 😆

**Comment by dnil** [comment]
Do we have sample files somewhere?

**Comment by fellen31** [comment]
> Do we have example files somewhere?

`/home/proj/development/rare-disease/felix/scout_test/filtered.vcf.gz`

This one has `gnomad_popmax_af` and `colorsdb_af` but no `gnomad_af`. If you want to have all I can update it.

**Comment by northwestwitch** [comment]
> This one has `gnomad_popmax_af` and `colorsdb_af` but no `gnomad_af`. If you want to have all I can update it.

Hi @fellen31 I'm working on this issue now. Would be nice to have an example with all 3, also super small would be fine, so I can copy one variant from it to include in the automatic tests of scout. But we can also add the test for `gnomad_af` later, so no rush!

**Comment by fellen31** [comment]
Hi, I've updated the same file with to include all three!

**Comment by northwestwitch** [comment]
> Hi, I've updated the same file to include all three!

Nice, thanks!
