### ISSUE TITLE
Annotation for synonymous not correct

### ISSUE THREAD

**Issue by NicoleCMMS** [Clinical-Genomics/scout#476]
https://clinical-db.scilifelab.se:8083/cust003/17038/00a0adecf3d0bdb68d60539f1a978685
If you look at the above example you will see that the annotation for a synonymous change instead of being = is now %3D

**Comment by moonso** [comment]
Ok I see, it is in the hgvs description..

**Comment by moonso** [comment]
This is a string formatting problem, right @robinandeer ? Something with encoding utf-8...

**Comment by ingkebil** [comment]
Looks more liKE URL encoding problem: https://www.w3schools.com/tags/ref_urlencode.asp

**Comment by henrikstranneheim** [comment]
Actually, this probably comes from VEP. It is done to not brake the vcf format spec and is done intentionally.

@robin: we used to reverse this back to the original format in Scout. Has this been removed?

Skickat från min iPhone
