### ISSUE TITLE
Splice junction track needs gene track enabled, otw does not show junctions.

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#4769]
**Describe the bug**
Genes track needs to be on for the current implementation of igv-sashimi in scout. 

If it is unchecked in DNA Settings, IGV rendering stops with an error
<img width="515" alt="Screenshot 2024-08-21 at 14 42 15" src="https://github.com/user-attachments/assets/cf6d2925-057a-4d77-8dd4-2b5b086860f9">

**To Reproduce**
1. Go to DNA Settings
2. Uncheck all tracks
3. On a junction track case, click IGV RNA view; eg https://scout-stage.scilifelab.se/cust000/109311fam

**Comment by northwestwitch** [comment]
This one is probably the same issue as #4770

**Comment by dnil** [comment]
Very possibly related, but not quite necessarily. This view is not working when the gene track is missing. The other issue is with the DNA view not quite respecting the disabling of certain (non-default) tracks.
