### ISSUE TITLE
17049 Sanger order doesn't work. "Server error"

### ISSUE THREAD

**Issue by Martinengvall** [Clinical-Genomics/scout#477]
Se title

**Comment by robinandeer** [comment]
I did fix an error in the sanger email recently - can you try again? :)

**Comment by moonso** [comment]
Closing, please reopen if it does not change

**Comment by Martinengvall** [comment]
Hello Robin

Sorry for answering late.

I tried to order Sanger just now from 17059 but I saw that Michela already ordered Sanger so I didn’t want to mess things up by doing it again. Is there any other way I could test if it works?

Best regards
Martin

Från: Robin Andeer [mailto:notifications@github.com]
Skickat: den 19 april 2017 11:15
Till: Clinical-Genomics/scout <scout@noreply.github.com>
Kopia: Martin Engvall <martin.engvall@sll.se>; Author <author@noreply.github.com>
Ämne: Re: [Clinical-Genomics/scout] 17049 Sanger order doesn't work. "Server error" (#477)


I did fix an error in the sanger email recently - can you try again? :)
