### ISSUE TITLE
Settings DNA does not respect disabling certain tracks.

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#4770]
Current prod dbVar cannot be removed by unselecting all. Same with cosmic tracks on currents stage / v4.86 candidate.

**Describe the bug**

**To Reproduce**
1. Go to a variant for a case with DNA IGV tracks
2. Click on Settings DNA, unselect all
3. Go to alignment view
4. Note that the dbVar track (and custom cosmic tracks) are still visible

**Expected behavior**
Clearing tracks should be reflected on the IGV view.

**Comment by northwestwitch** [comment]
I can take this one if you haven't started @dnil
