### ISSUE TITLE
Issues to access IGV from variant page

### ISSUE THREAD

**Issue by sofievonlanthen** [Clinical-Genomics/scout#4782]
When trying to access the IGV page from the variant page, the page doesn't load. The same experience from several users. 

Accessing the IGV page from the case page works fine.

**Comment by dnil** [comment]
Sorry, we missed that one - thank you for reporting. In our defence, most variants are working! This happens for a subset of variants, and if I'm not mistaken, specifically MNVs (e.g. frameshifts)?

**Comment by dnil** [comment]
Ah, no. But perhaps it is the sex chromosomes?

**Comment by sofievonlanthen** [comment]
Yes it was a frameshift variant in X-bound gene BTK that didn't load. Case 524701400219 in cust004.

**Comment by dnil** [comment]
I'm able to reproduce it with a variant on X for a stage case, but not for general indels.
