### ISSUE TITLE
Unscrollable splice junctions track

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#4787]
**Describe the bug**
I'm not sure it's a bug yet

**To Reproduce**
1. Go to a variant of this case --> https://scout-stage.scilifelab.se/cust000/ACC8869A1-1M-FUSION
3. Open the RNA splicing view on igv.js and notice that:
- There is a big unused white space at the end of the page
- Zoom in and see that genes track is missing, when you scroll down the sample track
- Sample track might be glitching

It looks like this:

<img width="1680" alt="image" src="https://github.com/user-attachments/assets/636a1403-1029-4d05-9263-ed9abb8ec591">

**Comment by northwestwitch** [comment]
Bug is also in production, check out this variant for instance : https://scout.scilifelab.se/cust175/F0063570-RNAseq/48afd87e4ca2438448b19e238303d6fe

**Comment by dnil** [comment]
Interesting; it does work sometimes: 
https://scout.scilifelab.se/cust000/F0062137-TN-Watchmaker-downsampled/4ec6768405ce63cc24d5ab725d740169/igv

**Comment by northwestwitch** [comment]
I'm trying to reproduce it demo: I want a browser with the track of only one sample, so I figured I could remove the `splice_junctions_bed` key from the case config file for the mother and father of the trio. It stills tries to show the tracks of these 2 samples anyway:

<img width="1654" alt="image" src="https://github.com/user-attachments/assets/99163b44-4957-48b4-be71-af0e346daf63">

**Comment by northwestwitch** [comment]
> I'm trying to reproduce it demo: I want a browser with the track of only one sample, so I figured I could remove the `splice_junctions_bed` key from the case config file for the mother and father of the trio. It stills tries to show the tracks of these 2 samples anyway:

Ah you need to remove both `rna_alignment_path` and `splice_junctions_bed` and the tracks of the parents disappear. But the one track browser on demo works fine.
