### ISSUE TITLE
Coloring alignments by base modification removes read grouping

### ISSUE THREAD

**Issue by fellen31** [Clinical-Genomics/scout#4789]
**Describe the bug**
Coloring alignments by base modification removes (HP) tag grouping, and groups by strand instead. 

**To Reproduce**
1. Go to IGV-view
2. Click on group by tag -> HP
3. Click on color by base modification

**Expected behavior**
Coloring alignments by base modification should keep the current read grouping. 

**Screenshots**

**Additional context**
Let me know if this issue should be on the igv.js GitHub instead.

**Comment by northwestwitch** [comment]
Hi @fellen31, I've clicked around a bit but I can't seem to reproduce the issue, in which case did you see this?

**Comment by northwestwitch** [comment]
Ah perhaps this case? https://scout-stage.scilifelab.se/cust000/sighthound

**Comment by dnil** [comment]
Interesting - not quite finished perhaps! As a workaround, you can apparently do it in the reverse order; base mod, then group by tag.

**Comment by northwestwitch** [comment]
I'll open an issue in igv.js if you haven't done it already @dnil

**Comment by dnil** [comment]
@fellen31, since it appears we have the data loaded more or less ok into igv.js, I doubt there is much we can do on just the config side without modifying it itself. If you have time, maybe you could check over at https://github.com/igvteam/igv.js/issues to see if they have it as an issue, and perhaps if it could be recreated with their demo data?

**Comment by dnil** [comment]
> I'll open an issue in igv.js if you haven't done it already @dnil

Nope, all good - I was trying to shuffle it over to @fellen31; go ahead if you like!

**Comment by northwestwitch** [comment]
Here --> https://github.com/igvteam/igv.js/issues/1877

**Comment by fellen31** [comment]
Thanks, I guessed it would be an IGV issue, just wanted to double check with you if it could be any config stuff. Thanks for opening the issue @northwestwitch!

**Comment by fellen31** [comment]
And as @dnil says, it works if you reapply the grouping.

**Comment by northwestwitch** [comment]
This has neen fixed in igv.js now, see [PR](https://github.com/igvteam/igv.js/commit/3db773b3d2d1d56a79bf8b3226fd0233a84aa257). Closing this issue!

**Comment by fellen31** [comment]
Nice!
