### ISSUE TITLE
Ugliness on variantS list: multiple gene names get squished together, and overflow to nearby column

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#4792]
Not intended, perhaps from latest gene cell change? Or other older indirect effect?
![Screenshot 2024-08-28 at 09 23 47](https://github.com/user-attachments/assets/d70d624b-c997-45e9-b1f1-4f63c72fea78)

**Comment by dnil** [comment]
Yeah, no, upgrading this to a bug.
![Screenshot 2024-08-28 at 09 33 52](https://github.com/user-attachments/assets/1013689e-0d88-4cda-8ec9-9caf1e48ebf1)

**Comment by dnil** [comment]
I suspected that as well.

**Comment by northwestwitch** [comment]
Sorry I missed this, when I checked the effects

**Comment by dnil** [comment]
Yeah, we dont have enough of those multi gene vars on the standard demo case.

**Comment by northwestwitch** [comment]
I can fix it it if you haven't started yet

**Comment by dnil** [comment]
It's a quick one, only one might have to fiddle with the alignment on the wts page then? But, less important obviously.
