### ISSUE TITLE
Upload coverage step in GitHub actions seems broken

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#4809]
Tests pass but coverage is not uploaded to Codecov:

https://github.com/Clinical-Genomics/scout/actions/runs/10668199076/job/29595227956?pr=4711

Might be a temporary glitch

**Comment by dnil** [comment]
Hm, yes, let's keep an eye on it. The error message is kind of as if the test coverage thing wasn't run. Maybe it went outdated?

**Comment by dnil** [comment]
The failure goes back to the coverage upload step, and possibly to the production of .coverage artifacts in the first place?
![Uploading Screenshot 2024-09-03 at 09.33.41.png…]()

**Comment by northwestwitch** [comment]
I think the reason might be this: https://github.com/actions/upload-artifact/issues/602

I'll attempt a fix!

**Comment by dnil** [comment]
`‘include-hidden-files’` huh?! 😸

**Comment by northwestwitch** [comment]
> `‘include-hidden-files’` huh?! 😸

It broke the internet, they should have made it a major

**Comment by dnil** [comment]
Indeed! 
https://xkcd.com/2347/
