### ISSUE TITLE
AKUT!!!!

### ISSUE THREAD

**Issue by 29vd** [Clinical-Genomics/scout#481]
"Clinical filter" tar bort varianter som inte har frekvens i 1000G!!!!!!!!!!!!!!!!

**Comment by dnil** [comment]
Gäller både SV och SNV/MNV vyerna. 

// Daniel

**Comment by robinandeer** [comment]
This looks odd, right Måns?

https://github.com/Clinical-Genomics/scout/blob/master/scout/adapter/mongo/query.py#L77

**Comment by robinandeer** [comment]
Hej,

skulle ni kunna ge exempel på detta? I en familj t.ex.

När jag testar i en random familj behåller den varianter utan 1000G annotering

**Comment by 29vd** [comment]
Kolla F0001819 - NMD panel

**Comment by 29vd** [comment]
F0001819



Helena Malmgren
Klinisk genetik
Karolinska Universitetssjukhuset
S-171 76 Stockholm
________________________________
Från: Robin Andeer [notifications@github.com]
Skickat: den 19 april 2017 12:05
Till: Clinical-Genomics/scout
Kopia: Helena Malmgren; Author
Ämne: Re: [Clinical-Genomics/scout] AKUT!!!! (#481)


Hej,

skulle ni kunna ge exempel på detta? I en familj t.ex.

När jag testar i en random familj behåller den varianter utan 1000G annotering

**Comment by moonso** [comment]
Hi,

I think I found the problem, when you press `clinical_filter` it automatically fills in `0.01` in the frequency column. This is not interpreted as the number 0,01 (notice the dot instead of the comma).
So if you fill in the clinical filter but change `0.01` to `0,01`, that is replacing the dot(.) to comma(,) it works. 
Really sorry about this and we will fix it asap, meanwhile you can use the above solution.

**Comment by 29vd** [comment]
OK TACK.



Helena Malmgren
Klinisk genetik
Karolinska Universitetssjukhuset
S-171 76 Stockholm
________________________________
Från: Måns Magnusson [notifications@github.com]
Skickat: den 19 april 2017 14:37
Till: Clinical-Genomics/scout
Kopia: Helena Malmgren; Author
Ämne: Re: [Clinical-Genomics/scout] AKUT!!!! (#481)


Hi,

I think I found the problem, when you press clinical_filter it automatically fills in 0.01 in the frequency column. This is not interpreted as the number 0,01 (notice the dot instead of the comma).
So if you fill in the clinical filter but change 0.01 to 0,01, that is replacing the dot(.) to comma(,) it works.
Really sorry about this and we will fix it asap, meanwhile you can use the above solution.

**Comment by robinandeer** [comment]
okej this is an easy fix from my point of view I believe

**Comment by robinandeer** [comment]
but it stills to work as expected for "cust000/P5357-1004fam" for example which I don't understand why...

**Comment by robinandeer** [comment]
if you fill in `0,01` it won't filter the frequency at all... at least in my brief testing - I will look into that as soon as I can

isn't the problem that the field always exists but sometimes is filled in with `None` @moonso? Perhaps that's something to try in the query build function?
