### ISSUE TITLE
design principles, extensions

### ISSUE THREAD

**Issue by parlar** [Clinical-Genomics/scout#4810]
Regarding topic https://github.com/Clinical-Genomics/scout/issues/4798 I have a design question. We would rather avoid implementing a separate flask app for our third-party integration / export tool, but a view will be required.

Would you prefer encapsulating all functionality needed by the tool in the extension such that it also includes blueprints and views?  

Like that:
```
export_extension/
│
├── __init__.py
├── views.py
├── blueprints.py
└── templates/
    └── export_extension/
        └── export.html
```
This is probably a silly question. I have zero experience of flask development and don't know how things are usually done.

**Comment by dnil** [comment]
In practice that would work, but the way we have been approaching it is to have extension view support integrated in the regular view / blueprint hierarchy and calling on the extension code as needed to communicate with the external service api.

**Comment by parlar** [comment]
super!

**Comment by parlar** [comment]
bye

**Comment by northwestwitch** [comment]
> bye

bye! 😄
