### ISSUE TITLE
IGV hangs while loading sample tracks

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#4818]
Or is very slow. Possibly happening only in Solna

**To Reproduce**
On stage, go the the IGV browser of this variant --> https://scout-stage.scilifelab.se/cust000/G1A1471p10_Balsamic/cancer/324ea313cf0a2108e2cb51d61e91b7ea?cancer=yes

**Comment by northwestwitch** [comment]
They're having problems with their server, see  https://github.com/igvteam/igv/issues/1556 and https://github.com/igvteam/igv/issues/1557

**Comment by northwestwitch** [comment]
I've opened a dedicated issue in igv.js --> https://github.com/igvteam/igv.js/issues/1885

**Comment by dnil** [comment]
Again, we should at least consider a local mirror for genome and related tracks now that we can.

**Comment by dnil** [comment]
Looks snappy and nice now. Closing for now, but we should discuss local mirroring more.
