### ISSUE TITLE
Compound top 20 does not show correct order, and shows "not loaded"

### ISSUE THREAD

**Issue by Jakob37** [Clinical-Genomics/scout#4823]
**Describe the bug**

Our geneticists asked whether the compound top 20 on the SNV/indel page works as intended.

Here is one example:

![compound_page](https://github.com/user-attachments/assets/b3180832-329f-4d69-8da5-5927ec7fa644)

Several of the variants are shown as "not loaded".

They mentioned that they could see higher ranked variants not included in the list.

The variants are not sorted according to their ranking.

Do you guys see this as well? Let me know if not and I'll see if I can help out with pinpointing the issue.

**Comment by northwestwitch** [comment]
Hi! We also see a lot of not loaded. Thanks for reporting, we'll investigate!

**Comment by northwestwitch** [comment]
Ah but you have 0 as combined score for all compounds! Are you ranking your variants?

**Comment by northwestwitch** [comment]
We see a situation like this, with the highest compound score on top:

<img width="703" alt="image" src="https://github.com/user-attachments/assets/db2e4d3a-57a4-404b-8ca4-eb8aba9a8368">

**Comment by northwestwitch** [comment]
> They mentioned that they could see higher ranked variants not included in the list.

And these variants are following the right inheritance model of the variant in question?

**Comment by Jakob37** [comment]
> Ah but you have 0 as combined score for all compounds! Are you not ranking all your variants?

Aha, interesting. We have "RankScore" assigned to all. Do you have a separate field for the compound score? (Maybe this is in the Scout docs somewhere how it is supposed to look, I'll check ...)

> And these variants are following the right inheritance model of the variant in question?

I'll ask!

**Comment by northwestwitch** [comment]
Combined score should be the variant's score + compound variant's score. I'm not super familiar with this part of the pipeline but we are using [genmod](https://github.com/Clinical-Genomics/genmod) to annotate the compounds.

**Comment by Jakob37** [comment]
> Combined score should be the variant's score + compound variant's score. I'm not super familiar with this part of the pipeline but we are using [genmod](https://github.com/Clinical-Genomics/genmod) to annotate the compounds.

OK, I'll investigate. I suspect the other issues we have here are follow-up issues of us not adding the combined score in the same way ...

**Comment by dnil** [comment]
I believe you are using a local scoring tool instead of genmod? Perhaps it has been updated and lost the combined compound score?

**Comment by northwestwitch** [comment]
Check also the score of the compounds, because looks like that combined_score is set as compound score when loading the variant, see [this code](https://github.com/Clinical-Genomics/scout/blob/64a94958dfa1522bebeba5e5553c583e7d01cefb/scout/build/variant/compound.py#L33)

**Comment by dnil** [comment]
This is what it looks like over here:
<img width="1111" alt="Screenshot 2024-09-04 at 15 21 00" src="https://github.com/user-attachments/assets/d96696ab-1448-4077-9324-425c3bbcf969">

**Comment by dnil** [comment]
You are so right, both of you. Here is where the Compounds field gets parsed, and split on `">"` before going to that `compound_score` build routine @northwestwitch pointed to! Remains to be seen why it is removed or not set in the first place in your prod pipe (right now, hopefully).

**Comment by dnil** [comment]
(And I'm very glad I don't have to dig into this every day. It has a legacy touch to it. 😅 )

**Comment by Jakob37** [comment]
> And I'm very glad I don't have to dig into this every day. It has a legacy touch to it. 😅

Relatable 😃 

It seems actually our trios have the ">4" compound scores, and their score table looks like the ones you show above.

Seems like the difference is that for singles we for them aren't running `genmod compound`, which I suspect is adding the compound scores. Looks like the solution to run this also for singles.

Also after pondering, I also suspect the "not loaded" means that they have been present in the initial VCF, just not loaded into Scout.

I think this resolves the mystery on our part. Thanks a lot for the help debugging 🐛🙏

**Comment by Jakob37** [comment]
A follow up here. I tested running `genmod compound` on our single samples. It did indeed add the compound scores, but also adjusted the rank score (which for our single cases is not desired).

It seems our geneticists use this table for singles just to see whether there are other variants with a rank score above a threshold (maybe 12) within the same gene. They are not interested in the compound score for these. 

Right now they risk missing these, as the compounds are all "0" and the table show max 20. (I realize this might be using the table beyond its original purpose).

We are pondering now whether it is better to solve this at pipeline level or in Scout. Two alternatives:

- Add a flag to genmod so `genmod compound` can be run without modifying the rank score itself, just adding the compound scores to the variant's compounds.
- Update the table in Scout to meet their use case (for instance by doing a secondary sort on rank score after compound score).

What do you guys think - what is the correct solution. Poking around in Genmod, Scout, or do you see a completely different solution?

Thanks 🌱

**Comment by dnil** [comment]
Ok, good to know! I'm not entirely sure what is best. It is probably comparatively straightforward to patch in Scout, since it is a single tool, and you would not have to update images for pipelines etc. For the variant and variantS page, that should be easy. But I have a feeling we would have to perform the secondary sort on the compounds also on load, since we truncate the list? Meaning it would only work fully for new cases.

**Comment by Jakob37** [comment]
> Ok, good to know! I'm not entirely sure what is best. It is probably comparatively straightforward to patch in Scout, since it is a single tool, and you would not have to update images for pipelines etc. For the variant and variantS page, that should be easy. But I have a feeling we would have to perform the secondary sort on the compounds also on load, since we truncate the list? Meaning it would (also) only work fully for new cases.

I see! Hmm, if not a trivial fix in Scout, I'm leaning towards making `genmod compound` more flexible. We have anyway discussed adding flags to control the thresholds / exact scores there as well used for trios. I can open an issue / PR in the genmod repo then.

**Comment by northwestwitch** [comment]
Who's maintaining on genmod at the moment @dnil ?

**Comment by dnil** [comment]
@torbjorgen is probably the closest we have to a maintainer there. He has done most recently - but he also has his work cut out on the next big thing in the ranking area. 🙌

 It is an OSS repo, and at the very least @jemten @ramprasadn and I have also looked at in the past. I’m sure you would find the python dialect very familiar from the scout load and parse routines if you needed to fix something! 😸We will solve it together if need be.

**Comment by Jakob37** [comment]
> @torbjorgen is probably the closest we have to a maintainer there. He has done most recently - but he also has his work cut out on the next big thing in the ranking area. 🙌
> 
> It is an OSS repo, and at the very least @jemten @ramprasadn and I have also looked at in the past. I’m sure you would find the python dialect very familiar from the scout load and parse routines if you needed to fix something! 😸We will solve it together if need be.

Great, thanks 😊 The code looks OK to work with. I'll poke around and see if I can put together a PR. Should be a small change.
