### ISSUE TITLE
Search by similar case might not work as intended

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#4839]
Make sure that the functionality returns what's expected. We have the feeling that the search is returning similar and dissimilar cases in no specific order

**Comment by dnil** [comment]
I tried a few searches and both similar case and similar phenotype, and the results are not trivial. The functionality was never great, in particular it was sorely lacking an explicit lowest similaritly cutoff. But it probably also relied on some functionality of the caseS adapter search that is no longer working the same way. 🫤

**Comment by northwestwitch** [comment]
Ok, testing this on stage, cust003.

for instance there is [this case](https://scout-stage.scilifelab.se/cust003/17111) which shares a phenotype with [this case](https://scout-stage.scilifelab.se/cust003/16018#phenotypes_panel). It's the HPO term HP:0000519.

If you look for cases similar to the first you find none, while if you search cases similar to the second you find 480. The ones on top (that should be more similar) have phenotypes, but not that specific phenotype.

You get for instance these phenotypes:

<img width="403" alt="image" src="https://github.com/user-attachments/assets/838760ed-f44f-4c35-b662-9dd47361124a">

<img width="406" alt="image" src="https://github.com/user-attachments/assets/e7a8c223-4037-49a2-8a59-c897033ad029">

<img width="418" alt="image" src="https://github.com/user-attachments/assets/02458d5e-0c7f-4f78-b8bc-b1999eb2d2f7">

Ok, so you might think that if you pick one of these cases with  Abnormality of metabolism/homeostasis (which looks recurring) )and search for similar cases you'll get plenty.

But no, NONE

This is so broken!
