### ISSUE TITLE
Add ISCN coordinates on SVs

### ISSUE THREAD

**Issue by moonso** [Clinical-Genomics/scout#484]
Add a function that takes a variant and returns ISCN coordinates. See #443

**Comment by moonso** [comment]
@J35P312 any time estimation for this one?

**Comment by J35P312** [comment]
I'll Have a look at it next week!

**Comment by J35P312** [comment]
Aloha!
I started working on the ISCN coordinate thingy:

> def get_iscn(variant_obj):
>     """Returns ISCN coordinates
> 
>     Args:
>         variant_obj(dict)
> 
>     Returns:
>         iscn_coordinates(str)
>     """
>     iscn_coordinates=""
>     variant_type=variant_obj["sub_category"]
>     if variant_type == "del" or variant_type == "inv" or variant_type == "dup":
>         start=variant_obj["position"]
>         end=variant_obj["position"]+variant_obj["length"]-1
>         chromosome=variant_obj["chromosome"]
>         iscn_coordinates="{}({})({}-{})".format(variant_type,chromosome,start,end)
>     
>     return(iscn_coordinates)

The problem is, that I do not know were to put the code. Maybe you could insert it wherever you want it, then I can continue to work on it!

**Comment by moonso** [comment]
Hi,

you can add the function to the file `scout/parse/variant/coordinates.py`
Is that ok?

**Comment by J35P312** [comment]
That's great, I'll do so and then I will send you a pull request!
By the way, for inter chromosomal translocations, how are the two chromosomes stored? Am I correct that one of the chromosomes is stored in the "chromosome" field and the other in the field "mate_id" of the variant_obj dictionary?

**Comment by J35P312** [comment]
Hello there!
I'm back, and I have continued to work on the code, now it is almost finnished, with proper and up to date format. However, I need the cytoband positions for the interchromosmal translocations. Where can I find them?
Oh, and here's the code, perhaps it is more convenient if you finish it up =P
//Jesper
```
import re

def get_iscn(variant_obj):
    """Returns ISCN coordinates

    Args:
        variant_obj(dict)

    Returns:
        iscn_coordinates(str)
    """

    start=variant_obj["position"]
    end=variant_obj["end"]
    chromosome=variant_obj["chromosome"]
    variant_type=variant_obj["sub_category"]
    posB = None

    if ":" in variant_obj["alt"] and not ">" in variant_obj["alt"]:
        B=re.split("[],[]",variant_obj["alt"]);
        for string in B:
            if string.count(":"):
                lst=string.split(":");
                chromosomeB=lst[0]
                posB=lst[1]

    iscn_coordinates=""
    #del, dup, and inv are printed in a similar fashion
    if variant_type == "del" or variant_type == "inv" or variant_type == "dup":
        
        iscn_coordinates="{}:g.{}_{}{}".format(chromosome,start,end,variant_type)

    #print interchromosomal translocation
    elif not chromosome == chromosomeB and posB:
        ter_A=[]
        ter_B=[]

        iscn_coordinates += "g.[{}:{}_{}::{}:{}_{}]\n".format(chromosome,ter_A[0],start,chromosomeB,posB,ter_B[0])
        iscn_coordinates += "g.[{}:{}_{}::{}:{}_{}]".format(chromosomeB,posB,ter_B[1],chromosome,ter_A[1],start)
    
    return(iscn_coordinates)
```

**Comment by dnil** [comment]
Nice! To be complete, the cytobands should also be on the intrachromosomal events. Support for cytobands was a bit thin before, but I think @moonso has amended that with #486 // #487?

**Comment by moonso** [comment]
Yes we should add this asap, I will try to merge that pull request. 
How do we handle cytoband coordinates for intrachromosomal events @dnil ? Do they need a start and a stop position?

**Comment by moonso** [comment]
@J35P312 hehe you are trying to get away the easy way! Please create a pull request where this function is in a file called `scout/parse/variant/iscn.py`.
Then I can go and edit/comment on the PR. Tell me if you need any help.

Also it would be nice with some more comments to the code, for example what happens in the block
```python
if ":" in variant_obj["alt"] and not ">" in variant_obj["alt"]:
```
What does it mean?

**Comment by moonso** [comment]
@J35P312 could you pretend that cytoband coordinates exist by adding `variant_obj['cytoband']` or something so I understand where you will use it=

**Comment by dnil** [comment]
Cheers! Easiest just to include start and stop always? Its perfectly legit to say e.g. del(22)(q11q11) or if more bands involved e.g. del(X)(q21.31q22.1).

**Comment by J35P312** [comment]
That sounds great!
I will pretend that we have something like variant_obj['cytoband']["start"], variant_obj['cytoband']["end"]. I'll fix the last stuff and make a pull request!

**Comment by moonso** [comment]
👍

**Comment by henrikstranneheim** [comment]
@dnil Still relevant? Also one of the last issues on the SV goal for CG.

**Comment by moonso** [comment]
I'm closing this, please reopen if it seems important again
