### ISSUE TITLE
Version date for removed gene panel 

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#4840]
**Describe the bug**
When a panel is removed, the creation date for the current version is replaced with the date of the latest change (no other new version...), I e the deletion date. Deletion date is useful information, but it would be preferable to keep also the initial version creation date.

**To Reproduce**
1. Go to a panel, note the latest version creation date
2. Click on delete
3. Scroll down to the panel and 
4. See the current deletion date instead of the latest version creation date

**Expected behavior**
Ideally display both dates, at least somewhere. 

**Screenshots**
![Screenshot 2024-09-11 at 16 49 03](https://github.com/user-attachments/assets/23ddf3a3-99d4-42d1-b004-46e51ae9f7fd)
![Screenshot 2024-09-11 at 16 49 19](https://github.com/user-attachments/assets/bbee4700-6589-4313-bfb1-09370951f7ae)

**Comment by dnil** [comment]
Tagging it a bug, but it is probably more like a feature that wasn't fully thought through. It is unlikely to have a huge impact, but was considered important by at least one analyst.

**Comment by northwestwitch** [comment]
Working on this now!

**Comment by dnil** [comment]
Hihi, I was just checking it out too, but that is great - I'll fix sth else! :

**Comment by northwestwitch** [comment]
Ah it seems that the panel date gets replaced when it's deleted, so if I delete an old panel today it gets todays date:

<img width="436" alt="image" src="https://github.com/user-attachments/assets/1e343b59-5767-48d7-8b0f-b2aee193d8ba">
