### ISSUE TITLE
Scout user meeting, 24-11-06 9.00

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#4848]
## Long due user meeting

A virtual meeting link will be posted and sent to the user mail lists closer to the meeting. You are invited to add discussion points on this issue!

**Comment by dnil** [comment]
Those of you near by are welcome to K Rum NKS J8-10 Tantal, where we will host the Teams meeting.

**Comment by dnil** [comment]
## Discussion topics
- Ok to remove the free text portion of gene panel manual inheritance patterns? We have a controlled vocabulary manual inheritance (drop down menu) as well as an overall Gene comment.

**Comment by SofieCMD** [comment]
Another user request, prediction score - BayesDel!

**Comment by northwestwitch** [comment]
Suggestion: improve filters on SNVs and SVs genes pages.

**Comment by dnil** [comment]
Thank you for today! Next meeting is scheduled for 250312. See you!
