### ISSUE TITLE
Scout meeting 26/4

### ISSUE THREAD

**Issue by moonso** [Clinical-Genomics/scout#485]
Hi all, I will start the agenda here. If there is something that you know now that you would like to discuss please post a comment here. It would also be nice if you can tell that you will participate so that we can get a estimation for the number of people.

## Agenda

- [ ] Mosaicism tag button
- [ ] Partial causative feature and associated HPO-terms
- [ ] Clinical Report, big interest? Structure?
- [ ] Use of multiple family ids for different combinations of family constellations
- [ ] Cohort tag button 
- [ ] Cytoband coordinates for SVs

## From earlier meeting

- [ ] New order portal and StarLims export.
- [ ] add p-position to SV variants view
- [x] SV filters: gene, panel, size, chromosome/chr band
- [ ] run every analysis with all panels
- [ ] re-enable upload of custom gene panel (don't save)
- [ ] warn if filtering by gene not in clinical variants!
- [ ] add button to upload all variants in a gene directly from Scout
- [ ] add max to each rank score result? e.g. 5/10

**Comment by vwirta** [comment]
Header date incorrect. Should be 26th

Topic:
Use of multiple family ids for different combinations of family constellations

**Comment by henrikstranneheim** [comment]
- [ ] Cohort tag button
