### ISSUE TITLE
Cytoband coordinates for SVs

### ISSUE THREAD

**Issue by moonso** [Clinical-Genomics/scout#486]
We should add cytoband coordinates and make them searchable.
How would you like to search on cytobands @dnil ? Is it perfect match?

**Comment by moonso** [comment]
More for @dnil : how should we think with large SVs that span multiple cyutobands? Should we only annotate for where the start is or do they have a start and stop coordinate?

**Comment by dnil** [comment]
At least default to wildcard on search term: e.g. 22q11 would return also 22q11.21. Ideally also return events that completely span the query: eg vcf event would be del(1q11;1q31) and search term 1q2 we’d still like to return the event.

Start and stop is a little clunky for most events, isn't it? Often one might generalise instead: e.g. a del(1q11;1q12) could be described instead as del(1q1)?Perhaps we should look into a couple of older microarry softs - they must have dealt with this before.

**Comment by moonso** [comment]
Ok it sounds a bit messy to implement.
I have prepared so that we can start annotating this but we need to discuss a bit more before applying.
I'll add it to the agenda
