### ISSUE TITLE
Update in ClinVar json submission schema probably responsible for failing submissions

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#4868]
If you provide any text in that field then you submission fails. This is because The select above contained 2 fields that now are gone: "drug response" and "other". You were supposed to fill in "Comment on clinical significance" only if one of these 2 fields were provided.

![image](https://github.com/user-attachments/assets/8b909a61-2af1-409b-b340-e8b998da4c62)

**Comment by northwestwitch** [comment]
@ehre

**Comment by ehre** [comment]
I'm unsure. Please see email with details, @northwestwitch

**Comment by northwestwitch** [comment]
I've tested again the submission from yesterday and it went through:

<img width="934" alt="image" src="https://github.com/user-attachments/assets/e186f28c-150c-423b-aea0-81116dfb7ce6">

I've also noticed that their pages that yesterday were offline are working today:

<img width="1081" alt="image" src="https://github.com/user-attachments/assets/bc14e09f-97b0-4489-a54d-54fec556c35a">

So perhaps it's not our fault after all?

I'm m the update of the json submission schema, see the [PR in preclinVar](https://github.com/Clinical-Genomics/preClinVar/pull/131) but I've noticed that the new schema is not breaking our test, which means our way of submitting should still be supported!

**Comment by northwestwitch** [comment]
Closing this issue as submitting worked also for Lund!
