### ISSUE TITLE
ACMG classification on ClinVar form to reflect the classification of the variant

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#4874]
User request:

`On the page where we are supposed to enter the ACMG classification (1-5), I have noticed that the default choice is “Pathogenic” regardless of the actual classification. Since you also display information about the classification in Scout, perhaps this could also be reflected in the default suggestion in the dropdown list? I have made this very error, I accidentally reported a variant as P even though the Scout classification was LP.`

This was supposed to work as described in the request, but perhaps the functionality was changed or it's broken now?

**Comment by dnil** [comment]
Hi, sorry, maybe I'm missing part of the discussion here, but where is you mean Pathogenic the default ACMG classification?
At least on our end the ACMG classification page unfilled defaults to "Uncertain significance"?

<img width="1393" alt="Screenshot 2024-09-19 at 10 49 36" src="https://github.com/user-attachments/assets/96798017-8b0a-4938-9e08-ede0175a12da">

Or do you mean for the manual rank `Variant tag` dropdown on the variant page? This one is not intended to reflect ACMG, rather a mix of old array standards and other tags useful but not within the scope of automated classification.

We have that long waiting project of #582 as well. I get a bit itchy wanting to spend time on it whenever someone mentions, but it will require a few weeks once started.

**Comment by ehre** [comment]
@dnil I mean on the ClinVar submission form. If it looks different on your side I can return with a screenshot, but I don't have Scout access right now.

**Comment by dnil** [comment]
I could have read the subject heading as well...  😂  Thank you, good point!
