### ISSUE TITLE
Search subject ID from case list

### ISSUE THREAD

**Issue by eliottBo** [Clinical-Genomics/scout#4878]
**Is your feature request related to a problem in the current program to new available technology or software? Please describe and add links/citations if appropriate.**

"As we discussed today at the GMS logistics meeting, we would need the “subject ID” to be searchable from the Case list.
Hope it can be easily implemented in Scout" (Request from Bianca Tesi iin  Ticket #590195)

**Describe the solution you'd like**
Be able to search a subject ID from the case list in Scout
**Describe alternatives you've considered**

**Additional context**

**Comment by northwestwitch** [comment]
I think it is already searchable. For instance if you have [this case](https://scout-stage.scilifelab.se/cust000/solidfawn), you'll notice that the sample is named `A00187`. If you go to the cases of cust000 and search for `A00187` or `ACC8869A1` then the case should be returned.  

Case individual looks like this in the database:

<img width="264" alt="image" src="https://github.com/user-attachments/assets/1f359d53-b046-414d-821c-b3031a715aed">

Or perhaps I misunderstood and sample ID is something else?

**Comment by northwestwitch** [comment]
Ok, speaking with @moahaegglund now I understood. There is an additional `subject_id` key in the individual dictionary, and THAT should be searchable.

**Comment by dnil** [comment]
Yes, it will be quite handy for finding matching WTS cases, but a new index will be required to avoid iteration through all individuals in all cases. Did you misplace your GitHub login btw @genecracker? 😜
