### ISSUE TITLE
Exon level coverage information

### ISSUE THREAD

**Issue by Jakob37** [Clinical-Genomics/scout#4894]
I put the latest Chanjo2 in the hands of our geneticists and asked them what they would need to put this into clinical routine. It seems close to meet their needs, but they had a bunch of questions on updates to make it fully solve their situation. Let's see what you think - if reasonable or not.

**Describe the solution you'd like**

For incompletely covered genes / transcripts they would like to see what parts that do not reach the coverage level.

The ideal would be to be able to show for a transcript:

* What exons are not fully covered

Would this be possible?

**Comment by northwestwitch** [comment]
Regarding the `(Ideally) What parts (bp positions) of these exons do not reach the coverage level` request, I guess one could work on it, but it's not super easy to implement I'm afraid. And I guess watching alignments in IGV might still be more reliable in the end?

**Comment by Jakob37** [comment]
> Regarding the `(Ideally) What parts (bp positions) of these exons do not reach the coverage level` request, I guess one could work on it, but it's not super easy to implement I'm afraid. And I guess watching alignments in IGV might still be more reliable in the end?

Yes, this was just wild wishes from the geneticists. I guessed it would be hard to achieve. I think we can leave that part aside.

Getting the exon coverage running though would be great 😄

**Comment by northwestwitch** [comment]
Hi @Jakob37, now that exons coverage is available on gene overview is this issue solved?

**Comment by Jakob37** [comment]
> Hi @Jakob37, now that exons coverage is available on gene overview is this issue solved?

Yes, thanks a lot 🙏
