### ISSUE TITLE
Missing caller info for SNVs in cancer-cases (except for VarDict)

### ISSUE THREAD

**Issue by mathiasbio** [Clinical-Genomics/scout#4901]
Hi guys! 

I've been looking a bit into the SNVs uploaded to Scout from the cancer side and I can see that from the TGA cases they have this label "VarDict: PASS"  but from the WGS calls made by TNscope there's none. 

![image](https://github.com/user-attachments/assets/70f52303-0c28-48dd-a5f8-3df66e560ed7)

I've been looking into the VCF to try to understand where it's reading this info of which caller made the call but can't find anything except in the VCF header under "source". For the next release of balsamic we're merging the TNscope and VarDict calls, and I can see from the test case I've uploaded to stage that this caller info is missing there too. Is there something we need to do on our side to get this info into Scout?

Thanks!

**Comment by dnil** [comment]
Well, we have it for cancer SNVs, either `TNscope` or `TNscope_UMI`. Did you specify it with `FOUND_IN` or `SET`?

**Comment by mathiasbio** [comment]
I see! I needed to search with case-insensitive. But ok! Then I just need to add this FOUND_IN to my merged VCF with the correct callers? Does it matter if I add it as "tnscope" or "TNscope"?

**Comment by dnil** [comment]
It just might! 😅 The tag should be the lower case version.

**Comment by dnil** [comment]
But, sounds good, caller tags are coming to these files as well! Closing this for now, right?

**Comment by mathiasbio** [comment]
Yes! Added to balsamic PR here: https://github.com/Clinical-Genomics/BALSAMIC/pull/1475
