### ISSUE TITLE
OMIM gene missing HGNC id?

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#4902]
**Describe the bug**

![Screenshot 2024-10-01 at 10 22 07](https://github.com/user-attachments/assets/682a73dc-03ff-4c53-898d-197ca8b5908a)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by dnil** [comment]
No, not sure it is on OMIM really. The HGNC lookup is ours; OMIM provide symbols and ENTREZ gene ids. It may still be some file format thing I suppose, but overall, data looks good enough, and it is leaning more to an issue with the gene alias routines?
```
[daniel.nilsson@hasta:scout_update_241001] [S_base] $ grep POPDC1 mim2genes.txt
604577	gene	11149	POPDC1	ENSG00000112276
[daniel.nilsson@hasta:scout_update_241001] [S_base] $ grep POPDC1 genemap2.txt
chr6	105096822	105137157	6q21	6q21	604577	BVES, HBVES, POPDC1, LGMDR25	Blood vessel epicardial substance	POPDC1	11149	ENSG00000112276		Muscular dystrophy, limb-girdle, autosomal recessive 25, 616812 (3), Autosomal recessive	Bves (MGI:1346013)
[daniel.nilsson@hasta:scout_update_241001] [S_base] $ grep POPDC1 hgnc.txt
HGNC:1152	BVES	blood vessel epicardial substance	protein-coding gene	gene with protein product	Approved	6q21	06q21	"HBVES|POP1|POPDC1"	popeye domain containing 1					2000-01-10			2024-08-12 	11149	ENSG00000112276	OTTHUMG00000015291	uc003pqy.4	AF124512	NM_147147	CCDS5051	Q8NE79	"10441744|10882522"	MGI:1346013	RGD:1561100			604577					470014					      										HGNC:1152	"ENST00000314641.10|NM_001199563.2"	HGNC:1152
```

**Comment by northwestwitch** [comment]
I can help looking into it if you want

**Comment by dnil** [comment]
On the hgnc_gene collection the only thing I notice is a different order of the aliases. Perhaps sth going wrong with that 

Stage (updated):
<img width="418" alt="Screenshot 2024-10-01 at 10 58 34" src="https://github.com/user-attachments/assets/8a69f3d7-0c02-467c-88c6-82586caea9b2">

Prod:
<img width="277" alt="Screenshot 2024-10-01 at 11 26 50" src="https://github.com/user-attachments/assets/53707749-c955-4b26-8b18-0df0d0706e60">

**Comment by northwestwitch** [comment]
Downloading the files now..

**Comment by dnil** [comment]
Im currently on the hunch that this is due to the newish double looping for both builds, but not sure in any way!
