### ISSUE TITLE
disease associated transcript giving wrong information

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#491]
see this variant 
https://clinical-db.scilifelab.se:8083/cust003/17047/afe8321ff37fa43714ce4be64ca99605

there is only one associated transcript registered in our dbCMMSv10, while there are 2 appearing here.

**Comment by moonso** [comment]
Hi, it looks like two transcripts because they both point to the same ENST.
You can see this by looking at the detailed gene information https://clinical-db.scilifelab.se:8083/genes/6617.

There is really no good way to get around this so hope it is ok, it is just extra information.

**Comment by henrikstranneheim** [comment]
Yes, for the transcript overview I think this is fine. However, under disease associated transcript the information should be collected from the gene panel (right?). And there is only one transcript there (NM_000235).

**Comment by 4WGH** [comment]
exactly!

the issue is with the  disease associated transcript


________________________________
Från: henrikstranneheim <notifications@github.com>
Skickat: den 25 april 2017 13:38:27
Till: Clinical-Genomics/scout
Kopia: MichelaBarbaro; Author
Ämne: Re: [Clinical-Genomics/scout] disease associated transcript giving wrong information (#491)


Yes, for the transcript overview I think this is fine. However, under disease associated transcript the information should be collected from the gene panel (right?). And there is only one transcript there (NM_000235).

**Comment by moonso** [comment]
Ok, we can have a look and see if it is possible

**Comment by 4WGH** [comment]
how is it going with this? several persons at our WGS meeting wonder why so many transcripts appear, instead  of the one(s) we have personally curated i´n our database.
