### ISSUE TITLE
problem with cosmic ids in demo data

### ISSUE THREAD

**Issue by parlar** [Clinical-Genomics/scout#4918]

**Comment by parlar** [comment]
Potential solutions I can see:

1. Negotiate an agreement with Sanger to allow the inclusion of Cosmic IDs in the demo data.
2. Dispute the claim that including Cosmic IDs violates Sanger's intellectual property.
3. Publish a paper on Scout.

**Comment by dnil** [comment]
Hi, we include variant files annotated with VEP (https://github.com/Ensembl/ensembl-vep), licensed under Apache 2.0. As far as I am aware, there is no further license attached to its use, be that commercial, research of general public health. I am not sure how such a claim can be made; we do not store any data from COSMIC, IDs are in the public domain - in many bioinformatics databases - and are just a short string starting with "COS" "M"/"V"/"N" and an integer. If this is taking up time and effort from the community, I think Sanger/GRL should discuss this internally with ENSEBL. I don't know that I would want to bother them with this, but we could pass it on to them if we want to start up your option 1. 

I was under the impression COSMIC included publicly funded and available research, but I suppose there may have been some huge amount of data added by QIAGEN then? Anyhow, we would very much prefer to focus on development, helping patients and doing research and leave legal issues to other departments. If the COSMIC devs truly feel their data should be private now, we can try to run VEP to produce an annotation without COSMIC ids for the cancer demo file.

Not sure how 3 would help? 😊 Scout would still be useable both for research and public health. Or commercial use if someone is so inclined.
