### ISSUE TITLE
BA is currently not quite stand alone...

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#4921]
**Describe the bug**
When adding ACMG `BA`, I expect to see the ACMG prediction be `Benign`. 

**To Reproduce**
1. Go to ACMG classify
2. Click on BA1
3. Fill in some other benign criteria that will have an impact, but less so, eg a BS and a BP
4. See error (classification changes to Likely Benign)
![Screenshot 2024-10-09 at 16 20 47](https://github.com/user-attachments/assets/868b619c-9bb7-4a52-a0db-bfa3ea6dce71)

**Comment by northwestwitch** [comment]
If you haven't I can start with this @dnil

**Comment by dnil** [comment]
Ah, did you start already? I've been mangling those pages for a bit now so it would feel natural to just do it otherwise. I didn't assign since I was unsure how much time I would have, but it looks decent right now.

**Comment by northwestwitch** [comment]
> Ah, did you start already? I've been mangling those pages for a bit now so it would feel natural to just do it otherwise. I didn't assign since I was unsure how much time I would have, but it looks decent right now.

No, I haven't started. It's all yours! :)
