### ISSUE TITLE
VariantS page easier to use for dismissal

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#4922]
**Is your feature request related to a problem in the current program to new available techology or software? Please describe and add links/citations if appropriate.**
Here is a nice suggestion and request from @alieden.

When going through the variantS list to dismiss variants in bulk, a few key facts are not evident from the list but require hover over. While good, it still requires a bit of scrolling. In particular OMIM gene inheritance patterns, and local frequency are common dismissals.

At the same time, expanding them will take up real page real estate. It would be possible to adjust the columns dynamically based on the case type (e.g. the case "inheritance model" column is not as relevant for singletons). But the simplest solution is probably to 1) merge the Gene/Region annotation and Functional annotation. The exonic/splicing/intronic/ncRNA region call is often evident from the functional annotation and could eg be in a hover on it.

**Describe the solution you'd like**
Expand the OMIM inheritance pattern and local frequency.

At the same time, expanding them will take up real page real estate. The simplest solution is probably to merge the Gene/Region annotation and Functional annotation. The exonic/splicing/intronic/ncRNA region call is often evident from the functional annotation and could eg be in a hover on it. Also the inheritance pattern and local frequency may not require separate columns; badges with inheritance models next to the genes for OMIM and the local counts/freq in the Local badge and not in hover would only take so many % of the page width.

**Describe alternatives you've considered**
It would be possible to adjust the columns dynamically based on the case type (e.g. the case "inheritance model" column is not as relevant for singletons). Or allow individual settings, but that is a whole different can of worms.

**Comment by alieden** [comment]
I understand the reasoning behind not permitting individual settings on the VariantS page. At the same time I guess it would perhaps be difficult to have a VariantS page that is "perfectly suitable" for all gene panels (with few or many genes) etc? Do you think it could be reasonable to allow panel specific settings of the VariantS page? Or would this type of feature require to much work from the development team compared to the potential benefits? I understand that there is a long list of request.......:)

**Comment by dnil** [comment]
Few things are proven impossible. Perhaps we try the desired change first, and feel very free to wish for more that would really help you. It is not necessary to  think about other use cases (trios, single gene, single variant testing, cancer, wts, …) but that is ofcourse appreciated. If needed a first level of customization can be at the track level, then trio vs singleton etc. panels is also not impossible, but since they differ at different sites etc it would be preferable to talk about panel character - ie more than 1000 genes or such.
