### ISSUE TITLE
Move panel edit action buttons closer to gene symbol/id

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#4933]
**Is your feature request related to a problem in the current program to new available techology or software? Please describe and add links/citations if appropriate.**
It's a long way over to the right of the screen. Not really any risk of getting it wrong, since you get the gene name when you open the edit or delete dialog, but feels like an unnecessary mouse skill task.

**Describe the solution you'd like**
Move the action buttons further to the left, closer to an identifiable symbol or id.

![Screenshot 2024-10-11 at 08 17 25](https://github.com/user-attachments/assets/7cf23480-3fd3-47e6-acf4-ce0968287a15)

**Comment by northwestwitch** [comment]
Yes, and also edit the title of that table so "Transcripts" becomes "Disease-associated transcripts"
