### ISSUE TITLE
Link rank model version to corresponding rank model ini file uploaded in scout

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/scout#494]
For transparency and traceability

**Comment by moonso** [comment]
Ok

**Comment by robinandeer** [comment]
See henrikstranneheim/MIP#127

**Comment by dnil** [comment]
Should we simply close this issue knowing we have 1) rank model versions 2) at least a partial attribution of rank score sources on each variant? 
If not, @henrikstranneheim do we have a store of these somewhere? The doc website pages seem a bit dated and not all versions are present. MIP git?

**Comment by henrikstranneheim** [comment]
I think it would be good to have a link and perhaps even a md5sum (at least at the location the link points to).

We can create a new folder in: https://github.com/Clinical-Genomics/reference-files/rare-disease 

and I add them there and you could point Scout there. What do you think?

**Comment by dnil** [comment]
Sure, that's doable; to generalise it a little bit we could e.g. give a config option that gives a base urls for rank_model and sv_rank_model, and then name the files according to version. It might add a little bit of installation complexity for off site users, but we will make it optional naturally.

**Comment by henrikstranneheim** [comment]
Sounds good!
Would this work (just showing most modern ones for brevity)
 https://github.com/Clinical-Genomics/reference-files/rare-disease/rank_model/1.23.ini
 https://github.com/Clinical-Genomics/reference-files/rare-disease/rank_model/1.23.ini.md5sum
 https://github.com/Clinical-Genomics/reference-files/rare-disease/svrank_model/1.7.ini
 https://github.com/Clinical-Genomics/reference-files/rare-disease/svrank_model/1.7.ini.md5sum

**Comment by henrikstranneheim** [comment]
Added rank models present in Scout to reference-files on format above: https://github.com/Clinical-Genomics/reference-files/tree/master/rare-disease/rank_model

**Comment by dnil** [comment]
@henrikstranneheim I added a link-out now, but old versions are missing. See https://github.com/Clinical-Genomics/reference-files/issues/11.
