### ISSUE TITLE
Show CoLoRSdb frequency in the Pop Freq column 

### ISSUE THREAD

**Issue by fellen31** [Clinical-Genomics/scout#4949]
Hi,

Many SVs can only be found in long-read data, and does not exist within gnomAD, for example: 

<img width="1410" alt="Screenshot 2024-10-16 at 09 52 08" src="https://github.com/user-attachments/assets/86145417-b81b-4bb5-9f3f-6356a640f909">

Would it be good to show the ColoRSdb frequency instead of `~`?

Additionally, when a variant has no frequency, the tooltip still shows gnomAD but not CoLoRSdb, could this be confusing? 

<img width="153" alt="Screenshot 2024-10-16 at 09 55 26" src="https://github.com/user-attachments/assets/85c3a3be-f81d-400d-89cc-0ea4123fb444">

**Comment by dnil** [comment]
I see where you are coming from, but ColoRSdb is teeny tiny so far. In this particular case, filtering and ranking on the pipeline side will be more crucial - the user should never have to consider a variant at 9% of any continental subpopulation.

**Comment by dnil** [comment]
Thank you for thinking about it though! Tentatively closing this as a `wontfix` but we can revisit it if it turns out CoLoRSDb grows and becomes a major resource!

**Comment by fellen31** [comment]
9% was a bad example :-) but I see what you mean!

**Comment by dnil** [comment]
Let's leave it for now, but we can revisit later if it turns out to be a lot of variants also after ranking and filtering.  We could do something like show them in a prio ladder, and add a tag/badge saying from which db they are e.g.

**Comment by fellen31** [comment]
> Let's leave it for now, but we can revisit later if it turns out to be a lot of variants also after ranking and filtering. We could do something like show them in a prio ladder, and add a tag/badge saying from which db they are e.g.

Sure, this was excluding > 10% for colorsdb and > 1% for gnomad.. Let's look through it after we have an initial SV rank model!
