### ISSUE TITLE
Entry version for genes in OMIM-AUTO panel

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#4956]
Perhaps we had this discussion already but I forgot. Entry version Is systematically set to the version before, for all genes. but it's wrong, no?

**Comment by dnil** [comment]
You mean as in pending updates or after it's applied? I'll have a look, but laters! 😅

**Comment by northwestwitch** [comment]
> You mean as in pending updates or after it's applied? Ah the auto one! I'll have a look, but laters! 😅

No, like just now that you updated the panel via the command line

**Comment by dnil** [comment]
Yes, got it at last, but no, I think it's all good. We only got 7 completely new genes this time, and they do appear as v31:
![Screenshot 2024-10-17 at 11 33 41](https://github.com/user-attachments/assets/68e7261e-7351-4081-8fc9-531e7b8af17b)

**Comment by dnil** [comment]
Compare e.g.
![Screenshot 2024-10-17 at 11 36 36](https://github.com/user-attachments/assets/eda94dd4-4eb1-42ed-aeda-e511c67e4c0d)
![Screenshot 2024-10-17 at 11 36 53](https://github.com/user-attachments/assets/ef030d66-8a4c-4b96-bcfa-5347983ce04a)

**Comment by northwestwitch** [comment]
> Yes, got it at last, but no, I think it's all good. We only got 7 completely new genes this time, and they do appear as v31:

But it's impossible that all the other genes were intrduced in v 0.29

**Comment by dnil** [comment]
> But it's impossible that all the other genes were intrduced in v 0.29

But they were not, compare POT1 above? 

It would be cool to deep dive each gene and fetch the first appearance for each line, instead of current and last - but I'm kind of guessing it would be too slow right now unless we refactor it, like storing the first appearance in db on each panel, and set it on creation or the first time its re-computed if it doesn't exist already.

**Comment by dnil** [comment]
It's like a linked list currently - you have to follow it back from the end to find the first node.

**Comment by northwestwitch** [comment]
> It would be cool to deep dive each gene and fetch the first appearance for each line, instead of current and last - but I'm kind of guessing it would be too slow right now unless we refactor it, like storing the first appearance in db on each panel, and set it on creation or the first time its re-computed if it doesn't exist already.

yes, that's what I mean. As we write it now, it seems that the genes were new in the panel before, but they weren't

**Comment by dnil** [comment]
Not really, but I see how one could interpret that as such. What it does is expose some db internals which isn't super cute, but compare how you e.g. see the next pending update on earlier, frozen versions. It works as a diff, and a history, so all good and clever, but isn't super clear to a random user. It's exactly the same thinking, or well, maybe lack thereof, and just reusing. 😁

**Comment by northwestwitch** [comment]
Perhaps we could just find a smarter name for that column, lnstead of "entry version". Entry version/previous version or something?

**Comment by dnil** [comment]
Perhaps, or a tooltip with a small essay? We could also hide the previous version number, or like super highlight the ones that match the selected panel version? The only thing the feature does realistically is show if a gene was changed with this version, or was there unchanged in the previous one.

**Comment by northwestwitch** [comment]
I like the idea of hiding the field if it's old and having instead something "new in the panel version" for the new genes n the panel
