### ISSUE TITLE
IGV Viewer Scout

### ISSUE THREAD

**Issue by 47KW** [Clinical-Genomics/scout#4958]
Suggest that the IGV Viewer buttons are named:

IGV DNA
IGV RNA

( Håkan And Hafdis)

**Is your feature request related to a problem in the current program to new available techology or software? Please describe and add links/citations if appropriate.**
A clear and concise description of what the problem is or what the advance you would like us to incorporate is. Ex. when triaging structural variantS, I would like to [...]

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by northwestwitch** [comment]
Good suggestion!

**Comment by dnil** [comment]
We could also take the opportunity to add a shortcut "IGV MT" button to the collapsible actionbar. The IGV.js MT view exists, but is somewhat hidden currently.

**Comment by 47KW** [comment]
Great!
”IGV Viewer” is acctually a tautology
H

21 okt. 2024 kl. 17:56 skrev Daniel Nilsson ***@***.***>:

﻿

We could also take the opportunity to add a shortcut "IGV MT" button to the collapsible actionbar. The IGV.js MT view exists, but is somewhat hidden currently.

**Comment by dnil** [comment]
Maybe more of legacy from when we had a "pileup viewer", but sure is. 👍
