### ISSUE TITLE
Are matching causatives looking for matchings in all categories?

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#4964]
Like a SNV that is causative, is searched among the SVs of the case? - I can look in the code by myself as well, but I drop the question here so we remember to make sure

**Comment by dnil** [comment]
In case the simple id is the same, they should match: https://github.com/Clinical-Genomics/scout/blob/868323944055f899b2c5b6542c2f8da5cbbb18c0/scout/adapter/mongo/variant.py#L581

**Comment by dnil** [comment]
If we truly intended this as a feature, there would be a caveat for SVs having poor genotyping from at least the RD side.
We do check if the matching variant was really from an affected: https://github.com/Clinical-Genomics/scout/blob/868323944055f899b2c5b6542c2f8da5cbbb18c0/scout/adapter/mongo/variant.py#L475-L504
In general the rule of matching gt is probably not fantastic for the somatic pipeline cases?

**Comment by northwestwitch** [comment]
> n case the simple id is the same, they should match:
> 
> https://github.com/Clinical-Genomics/scout/blob/868323944055f899b2c5b6542c2f8da5cbbb18c0/scout/adapter/mongo/variant.py#L581

Let's check if the cases from that ticket if the use of causative matching would have suggested the variant among the SVs! We could use it as an argument in general when these things happen

**Comment by northwestwitch** [comment]
> In case the simple id is the same, they should match:

Right, and simple_id is not built based on variant type. I'm convinced. Closing this issue!
