### ISSUE TITLE
Add support for classifying oncogenicity according to ClinGen-CGC-VICC Guidelines

### ISSUE THREAD

**Issue by muabnezor** [Clinical-Genomics/scout#4967]
Currenty, the user can only classify a variant according to the ACMG guidelines. However, for somatic variants it would be good to also have support for the [ClinGen-CGC-VICC Guidelines](https://pubmed.ncbi.nlm.nih.gov/35101336/)

A solution would be to change the classification system for cancer cases (or have the option to classify according to both guidlines?)

**Comment by dnil** [comment]
This looks really cool, and easy to implement! We love ClinGen, and will be happy to look at (or receive PRs for 😁) their system.

For somatic variants, we do not encourage the use of the ACMG RD classifications; instead we currently provide the AMP/ACMG Tier classification system.
![Screenshot 2024-10-18 at 15 39 39](https://github.com/user-attachments/assets/d6e1d127-f87c-4a70-971d-9b5c2c6068e4)
![Screenshot 2024-10-18 at 15 39 51](https://github.com/user-attachments/assets/5103a33e-01be-4bd7-832f-431343e94ab2)

**Comment by dnil** [comment]
To be clear, we would still like to keep an option to show an ACMG button on the cancer variant page, as one may occasionally like evaluate to evaluate a variant as a potential inherited germline variant.

**Comment by dnil** [comment]
I like this one in particular, I must say. Do remember to assign yourself to the issue @muabnezor and ML whenever you start. If you want some quick overview of the codebase in regards to this, Im sure we could arrange it as well. But in this particular case, I think you have a very decent learning target, where you can "just" follow the Tier or ACMG events (and full ACMG classifications, if you want to make a fill-in-your-terms kind of page for it) through the code.

**Comment by muabnezor** [comment]
Hi, 

Glad you feel this would make sense. As you mentioned it should be very easy to implement.
