### ISSUE TITLE
Manual gene names/panels: Filters / Hgnc Symbols

### ISSUE THREAD

**Issue by KickiLagerstedt** [Clinical-Genomics/scout#497]
I can enter a non existing genename in this field and there is no warning, as it used to be, regarding that this is not an valid genename.

Ex Gene name "1234"
![bild](https://cloud.githubusercontent.com/assets/17139607/25433644/67e6b942-2a89-11e7-96d3-48afbe752e36.png)

Would be 👍 if You could fix this! 😃

**Comment by KickiLagerstedt** [comment]
OR gene name WRPQ for instance (if 1234 is a HGNC gene no)

**Comment by moonso** [comment]
It should be possible, we will try to fix this

**Comment by robinandeer** [comment]
This should display a warning

We can also try to add autocomplete to the gene name box

**Comment by robinandeer** [comment]
a warning will now be displayed again in the next update - see #530
