### ISSUE TITLE
Space -> comma separate positions in RNA-seq module

### ISSUE THREAD

**Issue by Jakob37** [Clinical-Genomics/scout#4980]
**Is your feature request related to a problem in the current program to new available techology or software? Please describe and add links/citations if appropriate.**

One of our CLGs have started working on Tomte/DROP cases using the Scout module. Seems to work very well for her 😄 

She had a super minor request, with a moderate impact on her quality of life.

Working with Scout, she copies positions into regular IGV. Currently numbers are space separated. When pasted directly into IGV, it does not understand this, and spaces have to be removed.

Seems comma separated numbers on the other hand are understood by IGV.

I.e. `3 785 204` -> `3,785,204`

![scout_tomte_2](https://github.com/user-attachments/assets/934b058f-8fb1-4cb6-b65a-3ff8b67d01ad)

Would it make sense to change this format? (I would be happy to provide a tiny PR!)

**Comment by dnil** [comment]
I know, I feel it: I really hate that useless half-space format. It’s hard to read and requires a lot of work to use in other apps. Very non-Unix. But I have been voted down on this before, so here we are. “It looks pretty”. 🙄We have solved this for some pages (variant eg) with a dedicated copy to clipboard button as needed. What number in particular is she using and perhaps redundantly, why isn’t she clicking the IGV RNA button instead?

**Comment by Jakob37** [comment]
> I know, I feel it: I really hate that useless half-space format. It’s hard to read and requires a lot of work to use in other apps. Very non-Unix. But I have been voted down on this before, so here we are. “It looks pretty”. 🙄We have solved this for some pages (variant eg) with a dedicated copy to clipboard button as needed. What number in particular is she using and perhaps redundantly, why isn’t she clicking the IGV RNA button instead?

I see! There is often a story behind why things are as they are 😄 

The numbers are the positions of identified DROP features (i.e. both splicing and expression). I think she typically uses both the "RNA splicing" button to get to Scout-IGV, and copies the coordinates when going to regular IGV (which for instance gives a bit easier-to-view multiple tracks for the sashimi plots).

I.e. to the right in this figure:

![drop_3](https://github.com/user-attachments/assets/c22db0b4-caa0-43f2-81ac-b6ca609a762c)

I am unsure where the "IGV RNA" button you mention is, so I suspect I am missing something. Maybe you can point me to it?

**Comment by Jakob37** [comment]
OK, thanks for this input! Got some things to digest here.

Adding a copy button seems like an easy and useful thing to do here right now. I can see if I can put together a small PR.

**Comment by dnil** [comment]
Compare here if you start thinking about that IGV desktop extension. Several paths possible, but the HTTP one is perhaps the most familiar in this context: https://igv.org/doc/desktop/#UserGuide/advanced/external_control/
