### ISSUE TITLE
Different number of PanelApp panels in /api and /WebService paths

### ISSUE THREAD

**Issue by Jakob37** [Clinical-Genomics/scout#4988]
I am investigating starting to run Scout's built in method to update the PanelApp Green panel, similarly to how we are updating the OMIM-AUTO panel.

When looking closer, I found that although most genes are shared between our panels, a significant number differ. We have a few hundred additional genes in our local panel, while missing a handful. (Both end up ~4000).

Looking closer, the difference seems to be where we access the PanelApp services. 

Scout it seems is using this one end-point to grab panels (yielding 175 panels):

* https://panelapp.genomicsengland.co.uk/WebServices/list_panels/

While in Lund we are using the `/api` end points. The panel ones here yields 400+ panels:

* https://panelapp.genomicsengland.co.uk/api/v1/panels/

Looking at the names, the 400+ is mostly (except one panel) a superset of the 175 ones.

Are you guys familiar with this difference? Any reason for why you are getting the data from the `/WebServices` URL rather than the `/api`? Unsure whether I am overlooking something fundamental here 🤔 Would like to start using the Scout-based PanelApp Green update tool, but would of course need to understand where all the panels and genes go first ...

**Comment by dnil** [comment]
Thats a bit odd, thank you for checking! From a cursory look I have the feeling the "api" urls are their new API, and "web services" the old one. But the latter has not been discontinued, and certainly returns also new updates, so the difference in retrieval is not super clear. There is some mention of "old style" and "new style" panel ids. Let's check some FAQs and then ask them?

**Comment by dnil** [comment]
A clue might also be found in the signed-unsigned panels? The official NHS signed ones are somewhere around 175 (173?).

**Comment by Jakob37** [comment]
> From a cursory look I have the feeling the "api" urls are their new API, and "web services" the old one. But the latter has not been discontinued, and certainly returns also new updates, so the difference in retrieval is not super clear.

Yes, I got the same feeling.

> There is some mention of "old style" and "new style" panel ids. Let's check some FAQs and then ask them?

Sounds good!

I'll poke around a bit more in the JSON-data as well and see if some more patterns emerge.

**Comment by Jakob37** [comment]
Under API on the main site, it seems they are pointing towards using the Swagger (i.e. `/api`) endpoint: 

https://panelapp.genomicsengland.co.uk/

Didn't find anything about the `WebServices`.

Anyway, I'll send them an email and ask!

**Comment by Jakob37** [comment]
I got a response from the PanelApp people now. Looks like the `/api` end-points are they ones to use. Also looks like there are known bugs in the `/genes` endpoint, but that the `/entities` endpoint would work 🤔 

> Hi Jakob
> 
> Please use the api v1 following the user docs here https://panelapp.genomicsengland.co.uk/api/docs/. The webservices is in the process of being de-commissioned as it was built for the 100,000 Genomes Project (and I believe only returns panels relating to it) which has now finished.  Also note that we are aware of a bug in the /genes endpoint in which variable results are returned, so please instead use the /entities endpoint and then filter for genes if this is the information you need. 
>  
> Let us know if you have any other queries. 
>  
> Best wishes
> Eleanor

**Comment by northwestwitch** [comment]
Quite alarming, especially the de-commissioning thing. We should fix scout then!

**Comment by dnil** [comment]
This is pretty close to bugged, with the deprecation not really being noticeable for a long time. Let’s fix soonish anyway!

**Comment by Jakob37** [comment]
Yes, agree. Strange that it isn't made clearer on the web page and/or in the API page.

Sounds good with getting it fixed! Looking forward to start using the Scout CLI to update the PanelApp panel when this is resolved.

**Comment by northwestwitch** [comment]
I've been reading a bit of documentation and the situation is the following:

**Currently, scout creates the PanelApp green panel based only on panels included in the category: Rare Disease 100K**

The types of panels available in PanelApp are the following:

Available types:
- [ ] **Rare Disease 100K**: a gene panel used for the Rare Disease programme of the 100,000
Genomes Project.
- [ ] **Cancer Germline 100K**: a gene panel used for the Germline Cancer programme of the
100,000 Genomes Project.
- [ ] **GMS Rare Disease**: a panel developed for the NHS Genomic Medicine Service; may be
delivered by whole exome sequencing, whole genome sequencing, or as a ‘wet lab’
panel.
- [ ] **GMS Rare Disease Virtual**: a panel developed for the NHS Genomic Medicine Service;
will be used as a virtual panel for whole genome sequencing.
- [ ] **GMS Cancer Germline Virtual**: a panel developed for the NHS Genomic Medicine
Service for analysis of germline cancer susceptibility from whole genome sequencing
(WGS)
- [ ] **Super Panel**: A panel made up of two or more component panels. When the
component panels are updated, the Super panel is automatically updated.
- [ ] **Component of Super Panel**: A panel that is a constituent of a Super panel. Changes to
this panel will automatically update the Super panel.
- [ ] **Actionable**: A panel containing actionable information related to genes or genomic
entities, such as clinical trial information.
- [ ] **Research**: A panel from a research project.
- [ ] **External Diagnostic Lab**: a gene panel from a diagnostic lab or other source, external
to Genomics England and not directly used for genome analysis for the 100,000
Genomes Project or the NHS Genomic Medicine Service

A refactory of the scout functionality will allow us to include more categories. Question is, which ones do we want to include? Do we want to create more than one panelApp green panel, based on the different panel types included? Do we want to improve the flexibility of the functionality and allow the maintaner to specifically select which types to collect genes from, along with the option to collect only signed off panels or not?

**Comment by ehre** [comment]
From a clinical standpoint, the reason we included PanelApp Green in the first place was from a realization that OMIM-AUTO doesn't catch all clinically relevant genes (due to slow updates, primarily). So we decided to just add any gene that is "green" in any category in PanelApp to cast a wider net for our broadest clinical questions (typically trios). I would recommend that we continue along with these principles. When we need more narrow lists, we should anyhow use more manual curation than we get from the PanelApp categories, IMHO.

**Comment by northwestwitch** [comment]
> From a clinical standpoint, the reason we included PanelApp Green in the first place was from a realization that OMIM-AUTO doesn't catch all clinically relevant genes (due to slow updates, primarily). So we decided to just add any gene that is "green" in any category in PanelApp to cast a wider net for our broadest clinical questions (typically trios). I would recommend that we continue along with these principles. When we need more narrow lists, we should anyhow use more manual curation than we get from the PanelApp categories, IMHO.

I understand. But what about the risk of incidental findings when including for instance the Cancer Germline 100K type of panels? Wouldn't be better then to have different categories of PanelApp green panels?

**Comment by ehre** [comment]
It's not that easy, several cancer predisposition genes also have recessive phenotypes relevant for syndrome investigations. We only use OMIM-AUTO + PanelApp Green for "global" analyses, in all other circumstances we use curated gene lists (see https://genpaneler.genetiklund.se)
