### ISSUE TITLE
Coverage report - single gene search

### ISSUE THREAD

**Issue by KickiLagerstedt** [Clinical-Genomics/scout#499]
If I want to customize my coverage report using specific genes I have to write the HGNC ID (number) instead of the letters ie I have to write "12796" instead of "WT1"

Would it be possible to change it back to what is was before - the gene name / Approved symbol

//

**Comment by moonso** [comment]
Sure we will look into this asap

**Comment by robinandeer** [comment]
Will require an update to Chanjo with some JavaScript magic but I will look into it soon :)

**Comment by robinandeer** [comment]
- [ ] Show which genes are search for

**Comment by moonso** [comment]
I will assign you @adrosenbaum to some chanjo related stuff, don't panic 🍡

**Comment by dnil** [comment]
If you agree, with #1388 we transfer this to chanjo report/close it and reopen it there.
