### ISSUE TITLE
strange order of the compound variants?

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#500]
https://clinical-db.scilifelab.se:8083/cust003/17040/392193cd802b72b753fe331e484ca3d7

see link :)

the compound variants used to be listed with according to rank score, with the not uploaded at the end (this was very good and helping). now they are mixed....

Has something happened?

**Comment by moonso** [comment]
We will try to fix that today!

**Comment by 4WGH** [comment]
thank you Måns [😊]


________________________________
Från: Måns Magnusson <notifications@github.com>
Skickat: den 27 april 2017 08:43:44
Till: Clinical-Genomics/scout
Kopia: MichelaBarbaro; Author
Ämne: Re: [Clinical-Genomics/scout] strange order of the compound variants? (#500)


We will try to fix that today!
