### ISSUE TITLE
ACMG criteria - PP1

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#5001]
![image](https://github.com/user-attachments/assets/65a82ee6-f76e-458b-9f7c-2b56a5203184)

The reference here is to the last publication from SVI gruop (ClinGen).  Here the system is very dependent on determinig the phenotype specificity.
I would add also Jarvik PMID: 27236918 for AD disease, It is independet from CLinGen. And not focus on thephenotype specificity. So good to have different possibilities depending on what can be applied :)

There are some other publications but more focused on cancer or specific disease that I would skip.

**Comment by dnil** [comment]
Mm, it will be good to have a new, shiny integrated approach again. 😄 

Biesecker et al mention Jarvik, but I think they mostly agree with you that those criteria could be applied, and potentially independently in addition to the co-segregation criteria, under specific circumstances (AD inheritance etc...). Ok, so lets add it - thank you!
