### ISSUE TITLE
Open WTS variants in new tabs

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#5002]

**Comment by northwestwitch** [comment]
I think they already do, no? Or you mean the outliers? In that case the gene link should open in a new window you mean?

**Comment by northwestwitch** [comment]
I think we we have fixed this one, so closing the issue. But please re-open if needed!

**Comment by dnil** [comment]
Yes, it is a duplicate of https://github.com/Clinical-Genomics/scout/issues/5070!
