### ISSUE TITLE
Add "low_penetrance" to REV_CLINSIG_MAP

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#5048]
I got this warning while loading variants from a test case:

`WARNING Clinsig value low_penetrance does not have an internal representation`

<img width="1238" alt="image" src="https://github.com/user-attachments/assets/d306f78e-d082-440f-ab4f-ed9f3d1657fe">

Add to [this variable](https://github.com/Clinical-Genomics/scout/blob/f3a97783c658479c95025b34acf6452a7262a10d/scout/constants/clnsig.py#L19)

**Comment by dnil** [comment]
Nice that the warning is working! 😁 Crash or no crash is the question...

**Comment by northwestwitch** [comment]
> Nice that the warning is working! 😁 Crash or no crash is the question...

This time I was looking specifically, but perhaps it's not always the case with prod?

**Comment by dnil** [comment]
No, if I understood the rundown correctly, `cg` just pipes the scout log to nothing, so noone could see it. 🙄

**Comment by dnil** [comment]
They would see a crash though. 😁

**Comment by dnil** [comment]
(which is uncalled for for "incomplete_penetrance" but would be vital for like "pathognomonic" if that ever happened.

**Comment by northwestwitch** [comment]
Here is a variant for testing, taken from the case that raised that warning:

1	94473807	1_94473807_C_T	C	T	49	.	CSQ=T|missense_variant|MODERATE|ABCA4|ENSG00000198691|Transcript|ENST00000370225|protein_coding|42/50||ENST00000370225.3:c.5882G>A|ENSP00000359245.3:p.Gly1961Glu|5969|5882|1961|G/E|gGa/gAa|||-1||HGNC|34|YES|||CCDS747.1|ENSP00000359245|ABCA4_HUMAN|Q86V62_HUMAN&Q0QD48_HUMAN&F5H5R2_HUMAN|UPI000012511C|||Ensembl||C|C||deleterious|probably_damaging|PROSITE_profiles:PS50893&PANTHER:PTHR19229&PANTHER:PTHR19229:SF97&Gene3D:3.40.50.300&Pfam:PF00005&TIGRFAM:TIGR01257&Superfamily:SSF52540|||||||0.0107|8.236|7.075|10.236|10.512|-2.508|-13.132|-3.454|-15.640|-3.916|-5.897|-9.813|-9.813||||5.35|5.35|0.91951|0.760|1.000000|5.885000|rs1800553|0.00|46|26|-16|-20|0.00|0.00|0.00|0.00|ABCA4|7888|Pathogenic/Likely_pathogenic/Pathogenic&_low_penetrance|7888|criteria_provided&_multiple_submitters&_no_conflicts|,T|non_coding_transcript_exon_variant|MODIFIER|ABCA4|ENSG00000198691|Transcript|ENST00000465352|processed_transcript|3/6||ENST00000465352.1:n.298G>A||298|||||||-1||HGNC|34|||||||||||Ensembl||C|C|||||||||||0.0107|8.236|7.075|10.236|10.512|-2.508|-13.132|-3.454|-15.640|-3.916|-5.897|-9.813|-9.813|||||||||||0.00|46|26|-16|-20|0.00|0.00|0.00|0.00|ABCA4|7888|Pathogenic/Likely_pathogenic/Pathogenic&_low_penetrance|7888|criteria_provided&_multiple_submitters&_no_conflicts|,T|upstream_gene_variant|MODIFIER|ABCA4|ENSG00000198691|Transcript|ENST00000484388|processed_transcript|||||||||||499|-1||HGNC|34|||||||||||Ensembl||C|C|||||||||||0.0107|||||-2.508|-13.132|-3.454|-15.640|-3.916|-5.897|-9.813|-9.813|||||||||||0.00|46|26|-16|-20|0.00|0.00|0.00|0.00|ABCA4|7888|Pathogenic/Likely_pathogenic/Pathogenic&_low_penetrance|7888|criteria_provided&_multiple_submitters&_no_conflicts|,T|missense_variant|MODERATE|ABCA4|ENSG00000198691|Transcript|ENST00000535881|protein_coding|5/13||ENST00000535881.1:c.239G>A|ENSP00000443203.1:p.Gly80Glu|464|239|80|G/E|gGa/gAa|||-1||HGNC|34|||||ENSP00000443203||F5H5R2_HUMAN|UPI0002065064|||Ensembl||C|C||deleterious|probably_damaging|PROSITE_profiles:PS50893&PANTHER:PTHR19229&PANTHER:PTHR19229:SF97&Gene3D:3.40.50.300&Pfam:PF00005&Superfamily:SSF52540|||||||0.0107|8.236|7.075|10.236|10.512|-2.508|-13.132|-3.454|-15.640|-3.916|-5.897|-9.813|-9.813||||5.35|5.35|0.91951|0.760|1.000000|5.885000|rs1800553|0.00|46|26|-16|-20|0.00|0.00|0.00|0.00|ABCA4|7888|Pathogenic/Likely_pathogenic/Pathogenic&_low_penetrance|7888|criteria_provided&_multiple_submitters&_no_conflicts|,T|missense_variant|MODERATE|ABCA4|ENSG00000198691|Transcript|ENST00000536513|protein_coding|7/15||ENST00000536513.1:c.692G>A|ENSP00000439707.1:p.Gly231Glu|785|692|231|G/E|gGa/gAa|||-1||HGNC|34|||||ENSP00000439707||F5H5R2_HUMAN&B4DWY6_HUMAN|UPI00017A8227|||Ensembl||C|C||deleterious|possibly_damaging|PROSITE_profiles:PS50893&PANTHER:PTHR19229&PANTHER:PTHR19229:SF97&Pfam:PF00005&Gene3D:3.40.50.300&Superfamily:SSF52540|||||||0.0107|8.236|7.075|10.236|10.512|-2.508|-13.132|-3.454|-15.640|-3.916|-5.897|-9.813|-9.813||||5.35|5.35|0.91951|0.760|1.000000|5.885000|rs1800553|0.00|46|26|-16|-20|0.00|0.00|0.00|0.00|ABCA4|7888|Pathogenic/Likely_pathogenic/Pathogenic&_low_penetrance|7888|criteria_provided&_multiple_submitters&_no_conflicts|,T|missense_variant|MODERATE|ABCA4|24|Transcript|NM_000350.3|protein_coding|42/50||NM_000350.3:c.5882G>A|NP_000341.2:p.Gly1961Glu|5985|5882|1961|G/E|gGa/gAa|||-1||EntrezGene|34|YES||||NP_000341.2||||||RefSeq||C|C||deleterious|probably_damaging||||||||0.0107|8.236|7.075|10.236|10.512|-2.508|-13.132|-3.454|-15.640|-3.916|-5.897|-9.813|-9.813||||5.35|5.35|0.91951|0.760|1.000000|5.885000|rs1800553|0.00|46|26|-16|-20|0.00|0.00|0.00|0.00|ABCA4|7888|Pathogenic/Likely_pathogenic/Pathogenic&_low_penetrance|7888|criteria_provided&_multiple_submitters&_no_conflicts|;SWEGENAAC_Het=1;CADD=28.4;AF=0.166667;Hom=6;FOUND_IN=deepvariant;SWEGENAF=0.0005;AQ=49;SWEGENAAC_Hemi=0;SPIDEX=2.133;Frq=0.01889;SWEGENAAC_Hom=0;Obs=276;GNOMADAF_popmax=0.0059655;GNOMADAF=0.0035036;most_severe_consequence=34:T|missense_variant;Annotation=ABCA4;RankScore=justhusky:24.0;RankScoreNormalized=justhusky:0.6666666666666666;RankScoreMinMax=justhusky:-30.0:51.0;RankResult=1|7|2|-12|5|3|3|3|7|5	GT:DP:AD:GQ:PL:RNC	0/1:27:13,14:49:49,0,68:..	0/0:25:25,0:50:0,93,929:..	0/0:20:20,0:48:0,78,779:..
