### ISSUE TITLE
Missing track item, bug 3

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#5049]
To reproduce, go to [this case](https://scout-stage.scilifelab.se/cust000/SWEDAC-2019-HG-05-Trio-NovaSeq) and click on this button:

<img width="300" alt="image" src="https://github.com/user-attachments/assets/9855e58a-afcb-4ea2-915e-a40d5229c58e">

**Comment by northwestwitch** [comment]
One of the individuals has a null bam file:

<img width="336" alt="image" src="https://github.com/user-attachments/assets/edb55959-994c-45c0-8d8b-993d22b387f9">

**Comment by dnil** [comment]
OMG. Slightly different than before, but still!
