### ISSUE TITLE
PyPi PEP 625 deprecation

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#5053]
This email is notifying you of an upcoming deprecation that we have determined may affect you as a result of your recent upload to 'scout-browser'.

In the future, PyPI will require all newly uploaded source distribution filenames to comply with [PEP 625](https://peps.python.org/pep-0625/). Any source distributions already uploaded will remain in place as-is and do not need to be updated.

Specifically, your recent upload of 'scout-browser-4.91.tar.gz' is incompatible with PEP 625 because it does not contain the normalized project name 'scout_browser'.

In most cases, this can be resolved by upgrading the version of your build tooling to a later version that supports PEP 625 and produces compliant filenames.

**Comment by dnil** [comment]
Maybe it's just the dash to underscore, or maybe it's about the scout - scout_browser naming scheme?

**Comment by northwestwitch** [comment]
> Maybe it's just the dash to underscore, or maybe it's about the scout - scout_browser naming scheme?

I think so!
