### ISSUE TITLE
DockerHub Scout scout images rating

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#5054]
We appear to be down to a "D" rating on docker image security. Perhaps we could switch to a more recent base image, and look at signing, which appears a bit wonky atm

**Comment by northwestwitch** [comment]
Fix also the base image

**Comment by northwestwitch** [comment]
I'll start on this one!

**Comment by northwestwitch** [comment]
I found this cute linter for Dockerfiles : https://hadolint.github.io/hadolint/ ❤️
