### ISSUE TITLE
Confirmation of paternity and maternity

### ISSUE THREAD

**Issue by 29vd** [Clinical-Genomics/scout#508]
We have previously discussed that we would apprechiate that maternity and paternity could be confirmed for TRIO analyses. Can this be visualized somewhere in Scout? If the MPS can confirm that the analysed individuals are the mother and father of the proband, the detected sequencevariants can get a higher pathogenic score...(ACMG)

**Comment by dnil** [comment]
Peddy? http://www.cell.com/ajhg/fulltext/S0002-9297(17)30017-4

**Comment by 29vd** [comment]
Går det att implementera i Scout vore  det ju utmärkt- eller vad tror du?

Skickat från min iPhone

12 maj 2017 kl. 17:05 skrev Daniel Nilsson <notifications@github.com<mailto:notifications@github.com>>:


Peddy? http://www.cell.com/ajhg/fulltext/S0002-9297(17)30017-4

**Comment by dnil** [comment]
Jepp - på gång också, delvis av andra anledningar. Dessutom produceras faktiskt ett par tre rätt hyggliga mått för varje prov nu, men det syns inte riktigt i Scout. Blir toppenbra!

// Daniel

**Comment by moonso** [comment]
We are working on including peddy in the analysis and then display relevant results

**Comment by moonso** [comment]
We will display the peddy information on the case page.
That is `confirmed sex`, `confirmed parent` and `predicted ancestry`🕺
