### ISSUE TITLE
Wide image destroys the case page layout

### ISSUE THREAD

**Issue by Jakob37** [Clinical-Genomics/scout#5086]
**Describe the bug**

When the image is wide enough, it pushes itself to a new row, leaving the sidebar behind.

**To Reproduce**

Upload a wide enough image with a case and toggle it open on the case page.

**Expected behavior**

Don't break the layout. Probably a scroll-box would be my recommended approach.

**Screenshots**

<img width="360" alt="large_image_destroys_layout" src="https://github.com/user-attachments/assets/692de32b-cb15-46a2-9897-5579f5681aa8">

**Additional context**

I would be happy to provide a PR for this, if you agree with this issue (as it is easier for me to test, having the image already available).

**Comment by northwestwitch** [comment]
Oh that's ugly!

**Comment by dnil** [comment]
Yes, we have had similar issues with the sidebar layout in the past; I seem to recall while developing `chromograph`.
Now frames weren't that bad, were they? 😜

**Comment by Jakob37** [comment]
I'll give this one a go today!

**Comment by Jakob37** [comment]
Hmmm. This seems to go deeper than I thought (as CSS always does).

Getting it scrolling within the width of the full screen width is easy enough.

Adding `max-width: 100%; overflow-x: auto;` to the div used as the custom image container:

```
<div id="{{image.path|safe}}" style="max-width: 100%; overflow-x: auto;"></div>
```

Getting it to scroll nicely within the contraints of the right-of-panel area seems to require a more structural change though.

A quick-fix to solve the immediate issue for us would be to just reduce the size used to display the image.

I am cowardly retreating from this one 🐔

**Comment by northwestwitch** [comment]
> I am cowardly retreating from this one, for now at least 🐔

No worries, we've all been there 😆

**Comment by northwestwitch** [comment]
I'm testing loading a quite big image, And it's all about the size you give it [in the config file](https://github.com/Clinical-Genomics/scout/blob/6b7a4a3d8e507f1e840f6658f14f69c9731489f7/scout/demo/643594.config.yaml#L111), I guess? Perhaps we should make sure that:
- Scout will re-size images that are too big
- All images could be opened in another tab, where they will be shown in their original size

**Comment by Jakob37** [comment]
> I'm testing loading a quite big image, And it's all about the size you give it [in the config file](https://github.com/Clinical-Genomics/scout/blob/6b7a4a3d8e507f1e840f6658f14f69c9731489f7/scout/demo/643594.config.yaml#L111), I guess? Perhaps we should make sure that:
> 
>     * Scout will re-size images that are too big
> 
>     * All images could be opened in another tab, where they will be shown in their original size

Yes, that sounds like a sensible approach!
