### ISSUE TITLE
Genes on panel counter on variantS page gene cell repeated

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#5087]
**Describe the bug**
When displaying multiple genes in the same gene cell, the count of panels is for the both of them, but displayed twice.
This is slightly misleading, and maybe it wasn't even so before we merged the inheritance pattern into the cell?
![Screenshot 2024-11-28 at 17 21 59](https://github.com/user-attachments/assets/798ef713-396a-44c1-a5b7-5f3c224352a6)
Three panels for one gene, one panel for the other:
![Screenshot 2024-11-28 at 17 22 35](https://github.com/user-attachments/assets/a50f1c31-5ee9-4447-9f09-fa80847c01d6)

Thank you for the heads up @alieden!

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by northwestwitch** [comment]
Claiming this one if nobody has started on it yet?
