### ISSUE TITLE
Error message when attempting to update gene panels

### ISSUE THREAD

**Issue by ielvers** [Clinical-Genomics/scout#5106]
Hi!

I'm attempting to update some gene panels by uploading a file to add new genes, and I keep getting this error message:

Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

I've gotten this error message for the last about three hours. I've tried using both new update files and files that we successfully used last year, and I've tried with multiple panels. Manually adding and editing genes seems to be working fine. Is this an intended down-time?

Thanks!
ingegerd

**Comment by northwestwitch** [comment]
Hi and thanks for reporting this problem, see #5104! 

We are aware that the functionality is not working as it should (it's a bug) and we have already fixed it today. Unfortunately the fix won't be effective until we release and install a new version of Scout, which we plan to do soon, hopefully this week. Until then, unfortunately, we have to ask you to either wait for updating your panel using a file or to update the genes of your current panel one by one manually.

Apologies! 🙏🏻

**Comment by ielvers** [comment]
Thanks so much for the explanation!

**Comment by dnil** [comment]
Closed by #5105
