### ISSUE TITLE
Remodel variant priority tag

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/scout#512]
- [ ] Rename to more generic "variant tag"
- [ ] Make it specific for each institute
- [ ] Add labels and/or numbers as categories
- [ ] Save in format for statistic aggregation in future cohort view

**Comment by moonso** [comment]
Could you provide the labels?

**Comment by moonso** [comment]
We will send a suggestion to all users to start with and then change 0-5 to the suggestion if no one objects. If institutes want to have different labels in the future we will handle the situation then.
We could need a suggestion for labels if anyone have one @henrikstranneheim @dnil ?

**Comment by robinandeer** [comment]
ping @henrikstranneheim

**Comment by henrikstranneheim** [comment]
I have asked CMMS for tags. I will post them here asap

**Comment by dnil** [comment]
Seemed from the meeting last time “Other” might be on the shortlist?

**Comment by moonso** [comment]
Any news here @henrikstranneheim ? This is the last small thing that we have to fix

**Comment by henrikstranneheim** [comment]
Here are the CMMS tags:

7 - known pathogenic 				(Previously known pathogenic in Clinvar Hgmd literature etc)
6 - pathogenic					(Novel mutation but overlapping phenotype with known pathogenic, no further experimental validation needed)
5 - novel validated pathogenic		(Novel mutation and validated experimentally)
4 - pathogenic partial phenotype	 	(Pathogenic variant explains part of patients phenotype, but not all symptoms)
3 - likely pathogenic 				(Experimental validation required to prove causality)
2 - possibly pathogenic				(Uncertain significance, but cannot disregard yet)
1 - likely benign					(Uncertain significance, but can discard)
0 - benign						(Does not cause phenotype)
