### ISSUE TITLE
Export table with cases info

### ISSUE THREAD

**Issue by terestahl** [Clinical-Genomics/scout#5123]
Hi
 would like to suggest a feature that allows users to export a table containing information for multiple cases in a structured format. The table should include fields such as:

Case
Sample Name
Sequencing Data
Protocols
Each sample should appear as a separate line in the report, designed as a delivery report.

This feature would be incredibly useful, as currently, different institutions use their own coding systems to identify patients. Retrieving such information often requires clicking multiple times, which can be quite time-consuming.

Having a straightforward export option would save significant time and improve efficiency.

Thank you for considering this request, and I look forward to your response.

Best regards,

teresita
**⚠️ Important:** Please avoid sharing any sensitive or personal information, including text or images, in this issue.

**Is your feature request related to a problem in the current program to new available techology or software? Please describe and add links/citations if appropriate.**
A clear and concise description of what the problem is or what the advance you would like us to incorporate is. Ex. when triaging structural variantS, I would like to [...]

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by northwestwitch** [comment]
Nice suggestion @terestahl. We already have something similar that works from the command line, so it shouldn't be that hard to implement also from the web portal!

**Comment by terestahl** [comment]
[heart]         Teresita Díaz de Ståhl reacted to your message:
________________________________

**Comment by terestahl** [comment]
[0]     Teresita Díaz de Ståhl reacted to your message:
________________________________

**Comment by terestahl** [comment]
[like]  Teresita Díaz de Ståhl reacted to your message:
________________________________

**Comment by terestahl** [comment]
Thanks!
I guess it will be available after next update?
Where to find the tool? Is it going to be placed in the first page of scout?
thanks

teresita



________________________________

**Comment by dnil** [comment]
Yes, with the next update! There will be a new button on the institute cases page, where you can choose to export the cases/samples you filter for! Like so, as in the PR if you follow the link above in the GitHub page.
 
<img width="1009" alt="image" src="https://github.com/user-attachments/assets/a4bf7783-4393-429a-ac4d-b42225f03b3c" />

cheers, and thank you for the suggestion!

**Comment by northwestwitch** [comment]
> Thanks! I guess it will be available after next update? Where to find the tool? Is it going to be placed in the first page of scout? thanks teresita

Exactly, it will be available from the next release, which we aim to create before Christmas.
 
You will find the button on the Institute page, in the form used to filter for cases. Note that if you want to export more than 100 cases (default setting) you need to filter to display more, i.e. 1000. Then you click on Filter and export:

<img width="1104" alt="image" src="https://github.com/user-attachments/assets/f2434b20-1c12-4ed3-9994-11c581a36aa1" />

Happy holidays! 🎄 🎆

**Comment by northwestwitch** [comment]
Ah @dnil beat me! 😆

**Comment by dnil** [comment]
Barely! 😅

**Comment by terestahl** [comment]
thanks a lot


________________________________

**Comment by terestahl** [comment]
yes God Jul soon!


________________________________
