### ISSUE TITLE
Research variantS page popovers not respecting data-html

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#5126]
**Describe the bug**
Seems only to be for the research variantS, and for all tooltips - popovers are ok.
![Screenshot 2024-12-16 at 17 07 02](https://github.com/user-attachments/assets/2d7284f3-a402-4194-abc4-a51298c232c5)

**Comment by dnil** [comment]
I was about to write one for the cancer variantS page as well, but let's guess they have a common root. The cancer variantS page comments popover, frequency tooltip are not working. Observed etc have also stopped respecting html data.

**Comment by northwestwitch** [comment]
Working on this one now!
