### ISSUE TITLE
Chromosome region search for fusions

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#5127]
**Describe the bug**
Chromosome search for fusions/translocations (events on more than one chromosome) is too inclusive. Likely it tries a little too hard to get matches to both start and end chromosome (which it should) but the hits should be within the same region for start and end.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by northwestwitch** [comment]
Claiming this one now!

**Comment by northwestwitch** [comment]
Loaded [this case](https://scout-stage.scilifelab.se/cust110/F0055865-TN-re) on stage, so we can test using the variant we discussed yesterday

**Comment by northwestwitch** [comment]
The query of yesterday, which returned too many results, looks like this:

```
'$and':
	[
		{'$and':
			[
				{'$or':
					[
						{'chromosome': '14'},
						{'end_chrom': '14'}
					]
				},
				{'$or':
					[
						{'end': {'$gte': 106032600, '$lte': 106032700}},
						{'position': {'$lte': 106032700, '$gte': 106032600}},
						{'$and':
							[
								{'position': {'$gte': 106032600}},
								{'end': {'$lte': 106032700}}
							]
						},
						{'$and':
							[
								{'position': {'$lte': 106032600}},
								{'end': {'$gte': 106032700}}
							]
						}
					]
				}
			]
		}
	
```]

The second $or, that takes care of the coordinates, is set [here](https://github.com/Clinical-Genomics/scout/blob/e089dd6912e179cb8bd6eb6540c542c6c445b93f/scout/adapter/mongo/query.py#L493). It is a list of 4 elements that take care of different overlapping situations:

 ```
       # 1
        # filter                 xxxxxxxxx
        # Variant           xxxxxxxx

        # 2
        # filter                 xxxxxxxxx
        # Variant                    xxxxxxxx

        # 3
        # filter                 xxxxxxxxx
        # Variant                   xx

        # 4
        # filter                 xxxxxxxxx
        # Variant             xxxxxxxxxxxxxx
```

I have to think a bit about this
