### ISSUE TITLE
Add ACMG variant category in variant page

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/scout#513]
- store in database + API: as strings @moonso 
- interface: new box+form, `<select>` @robinandeer
- show instead of manual rank in variants list @robinandeer

pathogenic = P
likely pathogenic = LP
uncertain significance = US
likely benign = LB
benign = B

**Comment by robinandeer** [comment]
is this meant to replace manual rank?

should it be customizable by customers?

**Comment by henrikstranneheim** [comment]
No, I was thinking to add this as new function. ACMG is quickly becoming a standardised method, used in almost all clinics, so I think it is relevant to add this as a separate categorisation scheme. 

However, the manual rank should be customizable by the users. To add flexibility, great idea!

**Comment by moonso** [comment]
This is more or less done 😄
