### ISSUE TITLE
Cannot access IGV and GENS reports

### ISSUE THREAD

**Issue by ielvers** [Clinical-Genomics/scout#5139]
Hi,

Right now Scout isn't available at all so maybe this is irrelevant, but five minutes ago I could open cases and view variant pages but I couldn't view chromographs, access IGV ("Alignment file(s) missing") or view GENS reports ("Error - FileNotFoundError
/home/proj/production/housekeeper-bundles/mightyescargot/2024-09-16/ACC15640A2_lanes_2345678_fastp_sorted_md.baf.bed.gz")

![image](https://github.com/user-attachments/assets/a11c39bc-7e66-4e70-a0fe-4a0c6bf6a1de)

I checked two very recent cases and one that is a few months old.

Anyway, could be related to something bigger going on so feel free to ignore.

thanks!

**Comment by northwestwitch** [comment]
Hi @ielvers we are having problems with the server. I've restarted the service and scout should be available now. We'll keep an eye on it. Thanks for reporting!

**Comment by dnil** [comment]
IT apparently notified prod this morning that the network went down sometime during the night, and servers- and services restarted during the morning. So far so good; closing for now, but thank you for reporting @ielvers - and restarting @northwestwitch. Just ping again if you notice anything out of the ordinary!
