### ISSUE TITLE
PyPi - trusted publishing setup

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#5145]
I assumed we had trusted publishing set up for the scout-browser pypi, but maybe we didn't? At least the `uv publish` with trusted failed. I could change it back to use the tokens, but it seems more prudent to actually reconfigure on PyPi. 

Now, for the near term that will have to be someone else. 😊 I seem to have lost manager/owner on scout-browser? I hope it's only me, and that we didn't miss some send out? My other repos are fine.

![Screenshot 2024-12-19 at 17 00 43](https://github.com/user-attachments/assets/ca351498-c16f-4d74-a1d2-3b05ed013492)
![Screenshot 2024-12-19 at 17 02 01](https://github.com/user-attachments/assets/27535c7b-4f2f-4347-b88e-b8f87f27ab6a)

**Comment by northwestwitch** [comment]
I can try. What should I do exactly?

**Comment by northwestwitch** [comment]
Ok I managed:

<img width="1509" alt="image" src="https://github.com/user-attachments/assets/5d79d686-fbd0-4b1c-863c-96652a4b0468" />

I've also made you owner instead of maintainer on PyPI
