### ISSUE TITLE
Filtering against ExAc - How???

### ISSUE THREAD

**Issue by KickiLagerstedt** [Clinical-Genomics/scout#519]
If I filter against ExAc "0.01" I get very few variants to look at
If I filter against ExAv "0,01" I get a lot of variants

My guess is that filtering with "0.01" removes all variants with no data in the ExAc db as well as those with a frequency above 1%?

Could You fix this so that it is impossible to do the wrong filtering....????

// Kicki

**Comment by moonso** [comment]
This could be the same as for 1000G, we'll have a look

**Comment by dnil** [comment]
Oh, and exactly there it would still be great to have ExAC as well in the customer adjustable part of the clinical filter. We discussed that in issue #233, but only 1000G actually ended up on the customisable list. I don't dare touch that part right now. 😅

**Comment by henrikstranneheim** [comment]
Fixed in 4809f93
