### ISSUE TITLE
Check out the "competition"

### ISSUE THREAD

**Issue by robinandeer** [Clinical-Genomics/scout#52]
What can we learn from these impressive projects? How can we possibly work together?
- [ ] https://github.com/chop-dbhi/varify
- [ ] Solvebio: https://www.solvebio.com/variant-explorer/chr7:117199644-117199647:A
- [ ] https://github.com/macarthur-lab/xbrowse
- [ ] https://github.com/robinandeer/puzzle
- [ ] https://github.com/hammerlab/cycledash

**Comment by dandanxu** [comment]
Hi there! Glad we made it on the list =). Please do check out our variant explorer! We're adding more data modules and a nifty search feature. We're also building some pretty visualizations for summarizing VCFs. Let us know if you'd be interested in working together - everything we make is designed to be modular, to fit into pre-existing pipelines.

- Dandan from SolveBio

**Comment by robinandeer** [comment]
Hi @dandanxu!

Hehe, of course you made it on the list! From what I've seen so far SolveBio looks very impressive :smiley: Certainly miles away from the usual interfaces in the healthcare sector ^^

I'm trying to find more time to check out SolveBio and I would be very interested if seeing if we could work together, that would be awesome. I guess you are working on a commercial solution, but seeing that you have a presence on GitHub is refreshing - how does your plans around open source look like?

I also think it would be great to discuss how we can unify input of data across solutions. That is something we are thinking a lot on at the moment.

**Comment by ohofmann** [comment]
Will be following this interest. Robin, was going to reach out to you anyway as I'm in the process of evaluating CycleDash and your work (collaborating with Guillermo). More soon.

**Comment by robinandeer** [comment]
Exited to hear that, @ohofmann! We have serious plans to make Scout a lot simpler to install and use by other developers and clinics. Count me in as intrigued.

PS. I dig your avatar :smile: DS.
