### ISSUE TITLE
Overlapping SVs not detected/displaying?

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#520]
Anna H just found a likely causative LMX1B inversion from the SV view. Very cool! But, it does no show as an overlapping SV from the SNV/MNV view?

Compare:

https://clinical-db.scilifelab.se:8083/cust002/F0005864/sv/variants?variant_type=clinical&hgnc_symbols=LMX1B&size=&chrom=&thousand_genomes_frequency=

https://clinical-db.scilifelab.se:8083/cust002/F0005864/b9c8f0b65b90bbef54fbd6b508368e2c

Variant too large? If so, what's the cutoff?

**Comment by moonso** [comment]
We will look into this and see if we need to update how to search for overlapping variants

**Comment by 4WGH** [comment]
Hi!
this is an example of issue that would be good to notify to all.
we will try to inform you when this is applicable.

CMMS+ ClinGen

**Comment by moonso** [comment]
At the moment we are using gene symbols to get the overlapping variants. I will change that so coordinates are used instead, things should work then.
