### ISSUE TITLE
Project details, Order portal BETA

### ISSUE THREAD

**Issue by KickiLagerstedt** [Clinical-Genomics/scout#521]
Kan inte skapa "Project details" och vet ej heller hur det ska skapas. Rutan som ska beskriva detta är tom:

**Comment by KickiLagerstedt** [comment]
[Project details.docx](https://github.com/Clinical-Genomics/scout/files/987149/Project.details.docx)

**Comment by robinandeer** [comment]
Hej!

Vad bra att du hjälper oss att testa portalen 👍 

Enligt [instruktionerna](http://www.clinicalgenomics.se/bestallningar/):

> Fill in the ticket ID that you copied in Step 1 as the “Project name”.

Du kan fortfarande döpa den ticket i SupportSystems till vad du vill men iaf för nu skulle vi vilja:

1. öppna en ticket i SupportSystems
2. kopiera ticket id:t och ange det som "Project name" i orderportalen

**Comment by robinandeer** [comment]
Annars ser det ut som att du fyllt i allt korrekt!

**Comment by moonso** [comment]
Hej @KickiLagerstedt , det finns en sida för issues som gäller orderportalen, jag öppnade samma issue här: https://github.com/Clinical-Genomics/cgadmin/issues/9
Vi ska lägga upp en länk dit från orderportalens hemsida.
Stänger här så länge...
