### ISSUE TITLE
Local freq db filtering

### ISSUE THREAD

**Issue by KickiLagerstedt** [Clinical-Genomics/scout#522]
Something must have happened with the clinical filter - we get a lot of variants with a high freq i our local db. Has something been changed???

https://clinical-db.scilifelab.se:8083/cust002/F0003853-2/2c399f9c29005a3b13e27d867e3273d9

**Comment by moonso** [comment]
That looks  a bit strange, we will have a look asap

**Comment by 4WGH** [comment]
how is it going with this?
(CMMS+ CLinGen)

**Comment by moonso** [comment]
I'm not really sure why these are not down prioritized in the ranking process, do you have any idea @henrikstranneheim ? Anyway there is currently no filter in Scout that uses the local observations, but this will be added.

**Comment by moonso** [comment]
We will discuss this further at the scout meeting 1/6

**Comment by moonso** [comment]
Ok so this was discussed. There will be a new dump of the local observations database with the new release of MIP which will correct this problem. Also there is already a filter for local observations. Closing.
