### ISSUE TITLE
feature ideas

### ISSUE THREAD

**Issue by parlar** [Clinical-Genomics/scout#523]
After getting updated about the latest in Scout at yesterday's "bioinformatiknätverketsmöte", I decided to fire it up. Looks great!

A piece of functionality that I think would be very useful, at least for us, would be to be able to add/remove columns in the SNP/Indel view (perhaps also dynamically). 

This could enable the user to:

- display previous pathogenicity assessments for variants directly in that table, 
- add columns to with Alamut links (for viewing variants and, opening bam files in Alamut / IGV),
- add more detailed positional information.

If Scout would be used also for assessing molecular pathology samples, it would further allow:
 
- viewing COSMIC IDs +  other annotations,
- viewing variant frequencies (in the alignment),
- and remove the 'Inheritance model' column, which would then normally serve no purpose.

Finally, have you considered using some javascript table, such as jquery datatables (jquery is already loaded)? Or, something based on React? Would further allow improved sorting / filtering on displayed columns. Or perhaps you decided for a good reason to not go down that path.

cheers

Pär, Umeå

**Comment by moonso** [comment]
Hi Pär,

I'm glad you managed to set it up!
So for your questions:

We have left the idea with dynamic columns, I think as the community grows, different types of analysis gets more mature and the number of scout developers increases we can find consensus solutions to questions like these. It has worked well this far 😄.

> display previous pathogenicity assessments for variants directly in that table
Not quite sure what you mean here, we display links to clinvar with all previous classifications from there. Also there is something called `global comment`, everything that is written there will show up in this particular variant for all cases. Please specify if there is anything else you are missing.

> add columns to with Alamut links (for viewing variants and, opening bam files in Alamut / IGV)
As @dnil mentioned yesterday it is an easy add on that we could implement when needed.

> add more detailed positional information
Please elaborate more on this. I do not see any problems to implement when we know what to add

For the pathology part we hope to include those things when we get the collaboration with Lund started.

Best,

Måns

**Comment by parlar** [comment]
Thanks @moonso for a quick respose!

Maybe I have not spent enough time with Scout (obviously I haven't!). 

The columns that I can see in the SNP/Indel view are: rank, score, chr, gene, 1kg, cadd, g.anno, f.anno, inheritance model. I meant that adding colums for local classifications (+ clinsig) for variants would be valuable. And perhaps also pos, ref, and alt fields, for orientation, as well as the links I mentioned. 

A local classification filter might also be useful, I think.

Yes, @dnil mentioned it should not be difficult to add fields.

One way to deal with it not being possible to dynamically add/remove columns would, I guess, be to simply run multiple differently configured Scout instances.

The general ranking system I think is useful, but something I think that we would prefer would be to add that as a filter option and instead display variants in chromosomal/positional order.

I guess that should be simple too, to configure.

**Comment by moonso** [comment]
I'm closing this for now. You can reopen if it get's relevant in the future. Or you can make smaller issues when there is something that you know more exact.
