### ISSUE TITLE
Display autozygous region size from rhocall in Scout

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#524]
Display AZLENGTH and AZQUAL; fits best under inheritance model.

**Comment by henrikstranneheim** [comment]
This is available from MIP v5.0.0

**Comment by moonso** [comment]
👍

**Comment by henrikstranneheim** [comment]
right!

**Comment by dnil** [comment]
Just below inheritance model was our idea - when AZLENGTH and AZQUAL are set for a variant, display a line label like "Autozygous region" and a field with "Length" one with "Qual". Cheers!

**Comment by moonso** [comment]
Again things like this are hard to work on when we do not know how the entries look in the VCF and how they should be displayed

**Comment by dnil** [comment]
I can take it instead if there are any issues - actually intended to, but you beat me to assigning.. 😄

**Comment by moonso** [comment]
Perfect! Remember you have to modify both parse (scout/parse/variant/) and build (scout/build/variant)

**Comment by dnil** [comment]
I'll give it a try! 😸

**Comment by dnil** [comment]
Closing - solved and done with #542.
