### ISSUE TITLE
panel mall

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#526]
Hi!
It would be very good if we get a "mall" text file for importing gene panels.
So we can work in Excell and then save it with the right format for importing in Scout.

Michela

**Comment by moonso** [comment]
Hi,

great idea, we could add that to the documentation and send a mail when we're done

**Comment by 4WGH** [comment]
👍

________________________________
Från: Måns Magnusson <notifications@github.com>
Skickat: den 12 maj 2017 13:36:44
Till: Clinical-Genomics/scout
Kopia: Michela Barbaro; Author
Ämne: Re: [Clinical-Genomics/scout] panel mall (#526)


Hi,

great idea, we could add that to the documentation and send a mail when we're done
