### ISSUE TITLE
Next Scout meeting - points from CMMS and Clin Genet

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#528]
points to discuss at next Scout meeting (CMMS+ KlinGen)
- [x] 1. priority point system and possibilty for a AMCG classification
- #512 and #513 
- [ ] 2. show if a trio is a trio. (Peddy)
- #508 
- Peddy has been added to MIP. Need evaluation/validation. (Henrik)
- [x] 3. "," or "." how is the program working when filtering for freq
- #519 
- [x] 4.  gene name is case sensitive, good to inform everybody about this.
- [x] 5.  we want a message when wrong gene name is written!
- #528
- [x] 6. filtering on local freq is wished @moonso 
- The local freq is already in the rank model, but set at cut-off off 40 counts. This threshold will be lowered to 20 with the next MIP update. This is due to removal of potential duplicated observations in the old data base that has now been removed.
- [x] 7. on the gene variants list we wish to see both the inheritance based on the gene as well (in a different column) the phenotype inheritance.
- Need to discuss
- [x] 8. Clin VAr annotation is missing in some variant
- #335 
- [x] 9. discuss the validation procedure for a new release
- [x] 10. swap p. and c. in HGVS description view, keep the size of p. as is it, bigger :)
- [x] 11. for splicing mutation show the intron n. in the Sanger order
- [x] 12. re-runs keep the sharing permission and all gene panel should be open. 
- [x] 13. list of customers/users exp. in sharing data (by hovering with the mouse?)
- [ ] 14. Coverage report: we want to create it by gene name not number
- #552 
- [ ] 15. Coverage report: we want to customize by gene panel.
- #553
- [ ] 16. Delivery report: save the old version upon re-run, add the panel version. (Very good to have panel version, MIP version, status in the pedigree)
- #550

**Comment by robinandeer** [comment]
4. this is just how HGNC defined it - not all gene names use capital letters but we could handled it without considering case if you would like? @moonso 

5. sorry for this - re-implemented in #530!

6. with the next update we will get this data and implement the filter. The local frequency is already part of the rank score!

**Comment by moonso** [comment]
Ok most of the stuff here is fixed. **2** will be fixed soon and has been added to release 3.3.0.
**14,15,16** are bigger features and will be added later, these now have their own issues so I'm closing this.
