### ISSUE TITLE
comments on variant

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#535]
https://clinical-db.scilifelab.se:8083/cust003/15126/variants?gene_panels=EP&gene_panels=IEM&variant_type=clinical

look into variant with tank score 142. 

there is a "global" comment. but no sign on the above page about it. there used to be a little dot near the variant if the was a global comment if I remember well.
that was usefull. 
what happened with that?

**Comment by moonso** [comment]
Yes that should appear...
