### ISSUE TITLE
inheritance model missing from OMIM

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#539]
https://clinical-db.scilifelab.se:8083/cust003/203/aee2609d244a989242f627dcb2855535

for our genes in the dbCMMS there is a inheritance model annotation manually curated by us, that could be used when the information is missing from OMIM as in this case.

**Comment by moonso** [comment]
I was pretty sure that we have added a table to display both omim and manual inheritance right @robinandeer ?
