### ISSUE TITLE
Scout depends on ped-parser==1.2.4

### ISSUE THREAD

**Issue by robinandeer** [Clinical-Genomics/scout#54]
As I'm writing the automation script for loading data into Scout I notice that it seems like ``load_mongo_db`` indirectly makes a call to:

```python
for case in case_parser.to_json():
```

... but this fails since the ``to_json`` method in the current release of ``ped-parser`` requires an argument ``outfile``. I've downgraded ped-parser in the mean time.

**Comment by moonso** [comment]
This is fixed in #65
