### ISSUE TITLE
Classification of somatic variants

### ISSUE THREAD

**Issue by bjhall** [Clinical-Genomics/scout#548]
In the cancer variant view the variants should be classified according to the four-tiered system recently suggested by Association for Molecular Pathology et al. [1]. 

This is similar to the current "Priority" feature, but the classications should to be "global" for cases of the same indication. So if I classify a variant in a case with the indication "acute myeloid leukemia" the classification should apply for that variant in all cases with the same indication.

This would require an indication/diagnosis/whatever field in the sample document, which as far as I can tell does not presently exist?

[1] http://jmd.amjpathol.org/article/S1525-1578(16)30223-9/fulltext

**Comment by moonso** [comment]
Ok, this is a new way of thinking for us, we need to think a bit on how to solve this.
Would it be possible for you to use a `cohort tag` on case level to group cases in "indication"?
What would be the different indications?

**Comment by bjhall** [comment]
Sure, using the cohort  tag should be fine. Unless you think it is abusing that feature :)

The indications are different cancer types such as "lung cancer", "acute myeloid leukaemia" or "melanoma". I think it should be up to the user how fine-grained they want it to be. 

The reason this is important is that some variants are highly recurrent in cancer, so you wouldn't want to classify them each time. However the classification could be different depending on the indicatin.

**Comment by moonso** [comment]
Ok, it is fine to use the cohort tag. Our idea about that tag is to have it institute specific, guess that would work in your setup as well?

**Comment by moonso** [comment]
Could you also have a look at this @hassanfa ?

**Comment by moonso** [comment]
@hassanfa could you read through this issue and see if you agree? I think we should implement a classification according to the article then store the classification for every variant and display if the variant shows up again in another case just like @bjhall suggests

**Comment by hassanfa** [comment]
There was also a simple classification idea in BALSAMIC, which was inspired from MSK IMPACT: https://github.com/Clinical-Genomics/BALSAMIC/blob/develop/BALSAMIC/config/MSK_impact.json

I'll check out the article here and some other sources and get back to this issue. Lets keep it open.

**Comment by dnil** [comment]
Do we have a full or partial auto-classification for this scheme now as well? Otw the manual version is now ready for review, just a couple of months later - or years, depending on how you view it.. 😅

**Comment by hassanfa** [comment]
We do have a partial one, just some 🐍 script to do that. Ill put it somewhereon GitHub soon ™

**Comment by hassanfa** [comment]
But if someone else a more stable one, please do share it as well. 🤣 My classification code is ancient

**Comment by dnil** [comment]
Meh, for all those tests there was still one more place; the case page also calls the tier_cell macro for pinned variants.. I'll fix it in a related PR: I'm touching it when working on showing clinical assessments on the research page..
