### ISSUE TITLE
Persistent filter settings

### ISSUE THREAD

**Issue by bjhall** [Clinical-Genomics/scout#549]
At least in the cancer variant list view, it would be useful to be able to save the filter settings for a case.

This would be useful for the "reporting module" I'm trying to implement. Let's say you don't want the report to contain any somatic variants that are synonymous and/or with a tumor variant frequency below 10%. Instead of somhow manually marking which variants should/shouldn't be included in the report, you would just set and save a filter.

Not 100% certain if this is the optimal solution though.

**Comment by moonso** [comment]
Would that be "last filter used"? Or would you like to create a filter, name it and save it?

**Comment by bjhall** [comment]
Yes "last filter used" is how I've implemented it. Naming and having multiple filters saved seems like overkill?

**Comment by moonso** [comment]
Sure we could do both, depends on how you work. I guess that if you often use the same filter/filters there is a point in saving the settings and name it.
There is a preset filter that is used by the rare disease people here that is called "Clinical Filter", so they only need to press one button and the parameters gets autofilled.

**Comment by dnil** [comment]
Generalising persistent filters will be helpful for the development on the ID-screening side as well! :+1:

**Comment by moonso** [comment]
Could you take over this one @dnil ?

**Comment by dnil** [comment]
Probably, yes! I really like the idea, at least!
