### ISSUE TITLE
Plan for a "third-party" API to Scout

### ISSUE THREAD

**Issue by robinandeer** [Clinical-Genomics/scout#55]
We should probably (during the next refactor) this about how to expose an API to Scout for other services to import. It would be good if we could use the same API internally as well. Mainly to extract data from the database I guess.

This will be in addition to the CLI "scouttools" but I think we should keep it Python native and perhaps just use it in the CLI interface.

Related to: Clinical-Genomics/pymip#2

**Comment by moonso** [comment]
This will happen in the portable version
