### ISSUE TITLE
New SV annotations from clinical genetics

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/scout#557]
- [x] decipher
- [x] clingen_cgh_benign
- [x] clingen_cgh_pathogenic
- [x] clingen_ngi
- [x] clingen_ngiAF

```
##INFO=<ID=decipher,Number=1,Type=Integer,Description="The number of occurances of the event in the database">
##INFO=<ID=clingen_cgh_benign,Number=1,Type=Integer,Description="The number of occurances of the event in the database">
##INFO=<ID=clingen_cgh_pathogenic,Number=1,Type=Integer,Description="The number of occurances of the event in the database">
##INFO=<ID=clingen_ngi,Number=1,Type=Integer,Description="The number of occurances of the event in the database">
##INFO=<ID=clingen_ngiAF,Number=1,Type=Float,Description="The frequency of the event in the database">
```

**Comment by moonso** [comment]
Perfect!

**Comment by moonso** [comment]
Ok I'm implementing this right now but it is a bit confusing...
What does these mean? `clingen_cgh_benign`, `clingen_cgh_pathogenic`
Are there two different databases? Aren't we interested in knowing if the variant is common or not.
And also each of the annotations have a count and a AF. We should choose one of those, which one do you think is most informative @henrikstranneheim , @dnil ?

**Comment by moonso** [comment]
Why are this annotated all the time even if the count and frequency is 0?

**Comment by dnil** [comment]
Those are from the KlinGen arrayCGH databases; curated events from a different technology. Think of it as a kind of ClinVar, DGV or Decipher track. Different beast.
 
Jesper, have you compared AF vs counts? It’s by no means obvious what is best. I would lean towards counts. They are more informative for rare events. DB AF will likely be a biased estimate of true AF if no joint calling has been performed. I like the previous locusDB concept, keeping track of events seen and chromosomes seen.

// Daniel

**Comment by moonso** [comment]
Ok my part is done, waiting for @robinandeer ..

**Comment by J35P312** [comment]
Hello there!
I have not compared AF vs counts, maybe we should present both of them? I think both could be useful since we have many databases of different sizes and from different technologies, and the user might get very different AF values from each one of these.

**Comment by moonso** [comment]
Aha all of them, fine for me but it will be a lot of information. What do the others of you think?

**Comment by henrikstranneheim** [comment]
I think we should start with counts as above except for Swegen, which for me is okay to have only frequency. 

I also think it would be nice to not record lots of 0 in the vcf as we talked about earlier.
