### ISSUE TITLE
Flag structural variants causative

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#559]
Should be possible to
- [x] flag a struct var causative
- [x] classify it
- [x] pin it

**Comment by moonso** [comment]
Yes, good point, I thought these things worked since variants are variants according to the database, we'll have a look. Do you know if there is a reason why this is not added @robinandeer ?

**Comment by dnil** [comment]
Manual rank now ok. Official ranking systems will have to wait.
