### ISSUE TITLE
Don't fail on missing madeline file

### ISSUE THREAD

**Issue by robinandeer** [Clinical-Genomics/scout#56]
Hi @moonso,

will you have time to look into this or should I try to fix it?

```python
IOError: [Errno 2] No such file or directory: u'/home/scout/new/analysis-data/14044/madeline_14044.xml'
```

**Comment by moonso** [comment]
I have not looked at it, please go ahead if you have time:)

**Comment by robinandeer** [comment]
I saw you had already done something to this but I also made it so that pointing to a non-existent file doesn't give an error. Should probably log something in the future though...
