### ISSUE TITLE
Migration Issues

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#560]
on the re-run just uploaded for fam 15037 that are no old comments.
this is strange. 
Were comments missing or no comments have been kept as it is a old fam?

Michela

**Comment by moonso** [comment]
Ok I'm not sure, do you know @robinandeer ?

**Comment by robinandeer** [comment]
I believe this has to do with the migration script from old scout

we will have a look at this

**Comment by moonso** [comment]
From what I know this works now. I'll close this and we can reopen if it is an issue
