### ISSUE TITLE
no compunds in pat 17089. Is it possible? 

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#562]
look  here in the inherintance model column.
https://clinical-db.scilifelab.se:8083/cust003/17089/variants?variant_type=clinical&gene_panels=EP

it is OK or something has happend during analysis?

**Comment by moonso** [comment]
Hi, I have studied this case a bit now. The problem here is the setup of the analysis with 2 children only. There are a lot of compounds in the raw analysis, problem is that when there are only two children all variants that are heterozygous in the affected and hom ref in healthy will be annotated as AD_dn and scored based on this. The AR and AR_comp variants will be pushed down in the list and this explains why we do not see them.
If one or both parents where present the vast majority of the AD_dn variants would be downgraded and not seen at all.

**Comment by 4WGH** [comment]
Hi.
not follwing you.
It is not a case with 2 children only. there is a child and his father...

**Comment by moonso** [comment]
Sorry I missed that, but I still think that one can make the same reasoning. 99% of the AD_dn variant that we see are probably present in the mother.
There are so many high scoring ones so the compound pairs are way down the list. When I look at the raw data I can see that there are compounds present but they have to low rank score to be seen in scout. 

There is a problem here that we should work out some kind of solution to...

**Comment by 4WGH** [comment]
I can follow your thinking but if you compare this case with cases 17017 or 17018 where there are 2 siblings,

 case 17089 look totally different. (I'm not the only one reacting to this, I was charged to make the issue).


I've found 2 more cases where we have an index and one parental sample but they are not loaded in SCout (16034 and 15145)


If you say that all is correct with this analysis we will answer it out. We wanted an official comfirmation that the results are correct and nothing strange has happened.



________________________________
Från: Måns Magnusson <notifications@github.com>
Skickat: den 23 augusti 2017 12:50:43
Till: Clinical-Genomics/scout
Kopia: Michela Barbaro; Author
Ämne: Re: [Clinical-Genomics/scout] no compunds in pat 17088. Is it possible? (#562)


Sorry I missed that, but I still think that one can make the same reasoning. 99% of the AD_dn variant that we see are probably present in the mother.
There are so many high scoring ones so the compound pairs are way down the list. When I look at the raw data I can see that there are compounds present but they have to low rank score to be seen in scout.

There is a problem here that we should work out some kind of solution to...

**Comment by moonso** [comment]
No I'm terribly sorry, you are right. We are investigating it now.

**Comment by 4WGH** [comment]
great! thanks,


Michela

________________________________
Från: Måns Magnusson <notifications@github.com>
Skickat: den 23 augusti 2017 13:49:47
Till: Clinical-Genomics/scout
Kopia: Michela Barbaro; Author
Ämne: Re: [Clinical-Genomics/scout] no compunds in pat 17088. Is it possible? (#562)


No I'm terribly sorry, you are right. We are investigating it now.

**Comment by robinandeer** [comment]
we will rerun these cases with an updated version of genmod, see email
