### ISSUE TITLE
dbCMMS update

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#563]
Hi 
i need to add 40 genes to the dbCMMS, belonging to different panel.
How do I do now? :)

Michela

**Comment by 4WGH** [comment]
I also need to update the information on some genes already in with info about penetrance/mosaicism; adding to another panel, etc

**Comment by robinandeer** [comment]
Hej,

you can add genes to _individuals_ panels using the interface - for example for IEM:
https://clinical-db.scilifelab.se:8083/panels/5858f2ec0aa1e2b791c23b72

Just find the gene under "Pending changes" and update the information about penetrance/mosaicism and/or add new genes.

At the moment you would have to do this for each gene _and_ panel if the same gene is part of multiple panels.

If this is not possible we ask you to submit a file on the format described here:
http://www.clinicalgenomics.se/scout/user-guide/panels.html

It's fine to submit an Excel file if the headers and named properly and cells are already formatted :-)

You can open a new ticket and I will look into it

**Comment by 4WGH** [comment]
I have 40 genes... So I will submit a file.  Just with the new genes or only the nee ones?


Do you have a "mall" to fill in? Mans sadi you had done it but I can not  find it 😊


One more questions: I need also to update info on the genes.... this i can so online afterward, but how does this affect the versioning?



________________________________
Från: Robin Andeer <notifications@github.com>
Skickat: den 18 juli 2017 11:15:04
Till: Clinical-Genomics/scout
Kopia: Michela Barbaro; Author
Ämne: Re: [Clinical-Genomics/scout] dbCMMS update (#563)


Hej,

you can add genes to individuals panels using the interface - for example for IEM:
https://clinical-db.scilifelab.se:8083/panels/5858f2ec0aa1e2b791c23b72

Just find the gene under "Pending changes" and update the information about penetrance/mosaicism and/or add new genes.

At the moment you would have to do this for each gene and panel if the same gene is part of multiple panels.

If this is not possible we ask you to submit a file on the format described here:
http://www.clinicalgenomics.se/scout/user-guide/panels.html

It's fine to submit an Excel file if the headers and named properly and cells are already formatted :-)

You can open a new ticket and I will look into it

**Comment by robinandeer** [comment]
So every time you update information we will update the version of the gene panel

Here's a template for filling in the gene panel information:

[scout-3-panel-file-example.xlsx](https://github.com/Clinical-Genomics/scout/files/1155924/scout-3-panel-file-example.xlsx)

Justs fill in the genes that are either new or have updated information and we will copy the rest from the previous version :)

**Comment by 4WGH** [comment]
thanks! perfect!



Michela

________________________________
Från: Robin Andeer <notifications@github.com>
Skickat: den 18 juli 2017 15:08:18
Till: Clinical-Genomics/scout
Kopia: Michela Barbaro; Author
Ämne: Re: [Clinical-Genomics/scout] dbCMMS update (#563)


So every time you update information we will update the version of the gene panel

Here's a template for filling in the gene panel information:

scout-3-panel-file-example.xlsx<https://github.com/Clinical-Genomics/scout/files/1155924/scout-3-panel-file-example.xlsx>

Justs fill in the genes that are either new or have updated information and we will copy the rest from the previous version :)

**Comment by moonso** [comment]
Is this done now @robinandeer ?

**Comment by 4WGH** [comment]
the panels have been updated.
Thanks!
