### ISSUE TITLE
STAG2 instead of SH2D1A

### ISSUE THREAD

**Issue by Bianca-T** [Clinical-Genomics/scout#565]
Hi,

In case A1386 we found a mutation in _SH2D1A_. The mutation is known and everything is OK with it, but the alignment viewer annotate the exon as belonging to _STAG2_, which is a neighbour gene. Can you check?

We wanted to send a screenshot to the physician, but it is a bit confusing that the viewer states _STAG2_ instead of _SH2D1A_.

![screen shot 2017-07-27 at 13 08 04](https://user-images.githubusercontent.com/5881356/28667748-1b617aee-72cd-11e7-9efa-b6a15506bb39.png)

Thanks, 

Bianca

**Comment by moonso** [comment]
Could you email or open a ticket with information on case and variant? Preferably a link

**Comment by moonso** [comment]
Hi @Bianca-T ,
we have now done some investigation and could see that the two genes overlap, in fact SH2D1A is included in STAG2

 Gene | Start | Stop
 --- | --- | --- 
  SH2D1A | 123480193 | 123507005
  STAG2 | 123094061 | 123556514

So when pileup.js show the gene(s) it seems to choose one of the gene names. If one zooms out enough you will see both gene names.

Nothing we can solve, we fill open a issue on pileup.js to see if they can fix it
