### ISSUE TITLE
Reloading data

### ISSUE THREAD

**Issue by robinandeer** [Clinical-Genomics/scout#57]
Right now when I just rerun the load script for Scout, e.g. the case information will not be updated even if it's changed on the file system.

We need a clear path to reloading a case. Both taking into consideration possible new data as well as persisting comments and events and any other more temporary data.

Does the wipe script already offer this functionality?

**Comment by moonso** [comment]
Ok I will look into reload case

**Comment by robinandeer** [comment]
A new interesting case has come up. I've accidentally run MIP with incorrect institute tag. I noticed this after uploading to Scout. So what is the path to update a case such as that?

I was thinking of just changing MIP output and deleting the case manually from the database. Will that leave variants in the database that aren't tied to any case?

**Comment by moonso** [comment]
We will need to develop scouttools in such a way that we can do 
```bash
scouttools delete_case P109_coriell
```
And delete the case and its variants. I can fix this soon.
I'm closing this issue and open a new one since #57 is solved.
