### ISSUE TITLE
Comments not working?

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#573]
Hi, 
having trouble commenting (locally or globally). 
https://clinical-db.scilifelab.se:8083/cust002/F0012957/c5387df12a271d4361451d262d5b05d5
(Trying to add a note that the gene RECQL4 is broken in hg19: no full NM cDNA transcript available and >99,99% frameshift variants present. Gives artefactual fs annotations from VEP.

**Comment by robinandeer** [comment]
Review here @moonso : 5218b60930d1778925
