### ISSUE TITLE
ACGM classification

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#574]
https://clinical-db.scilifelab.se:8083/cust003/17097/f91382d9b50c55abc2aa12175f4b8a81

1. I can not unselect it... would be good if  possible in case of mistake/regrets :)
2. I've click classify but in the new page I could not select anything...
3. minor comment: can we have the classification in a gradiante order?
P, LP, VUS, LB, B ? 
4. Same thing in the classification page. 

Michela

**Comment by moonso** [comment]
Thanks, we will try to fix these!

**Comment by 4WGH** [comment]
point 4 from top to down PVS, PS,PM,PP for pathogenic
BA,BS,BP for benign

**Comment by robinandeer** [comment]
2. are you using the toggles next to each evidence criteria? The buttons on the top will reflect the ACMG classification based on the selection you make.

![screen shot 2017-08-30 at 09 39 44](https://user-images.githubusercontent.com/1220232/29860709-2e24318a-8d67-11e7-8995-ee6113563778.png)
