### ISSUE TITLE
Search genes with HGNC id

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#579]
If I use a correctly updated HGNC gene symbol but in Scout there is the old HGNC symbol I get a message that the gen could not be found. 

see 
https://clinical-db.scilifelab.se:8083/cust003/17130/986e69ab21545acf10d7e92c2e1c13ef 

symbol used in Scout "PROSC", updated gene symbol according to HGNC "PLPBP" (symbol used in the update of the panel and listed in the website, and that a scout user will use as first try). 
If I filter using the symbol "PLPBP" I get an error message "HGNC symbol not found: PLPBP ".

to avoid the issues about HGNC update in scout a faster solution could also be to add the possiblity to filter also by HGNC ID (to use when the filter by HGNC symbol doesn't work).

Michela

**Comment by moonso** [comment]
Hi I think it is an excellent idea, will try to add it asap
