### ISSUE TITLE
Update filter name for local obs

### ISSUE THREAD

**Issue by KickiLagerstedt** [Clinical-Genomics/scout#587]
We would like to be able to filter in the active local db (not in the archived one)

![bild](https://user-images.githubusercontent.com/17139607/29924300-d62227fc-8e5c-11e7-9d1a-b081f0bc70cc.png)

**Comment by moonso** [comment]
The filter works on the dump of the local database, we do a dump at certain intervals.
So the filter is not on the archived version but the dumped one, we should update the name on that field!

**Comment by robinandeer** [comment]
Which name for this "dump" would make most sense? Is "dumped" good enough?
Perhaps we should add the date instead?

**Comment by henrikstranneheim** [comment]
I think we should use the date like Local obs (archive DATE)
