### ISSUE TITLE
Gene panel view - add latest change date

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#590]
Some confusion ensued today due to gene panels not displaying latest change date. Would be nifty to add a latest version date stamp - or at the very least mark the creation dates clearly as such.

**Comment by KickiLagerstedt** [comment]
Se tex här:
![bild](https://user-images.githubusercontent.com/17139607/30019497-13544036-9161-11e7-9e17-217ad11571f0.png)

Dvs man tror att panelen inte är uppdaterad sedan 2016-04-22, med e facto uppdaterades den förra veckan

**Comment by KickiLagerstedt** [comment]
e facto = de facto

**Comment by robinandeer** [comment]
Mistake by us, but we have the information so we will curate the information a little and display the correct dates

We are pushing an update to resolve the issue - thanks for your feedback!

**Comment by robinandeer** [comment]
We can get the date from the objectId:
https://steveridout.github.io/mongo-object-time/
