### ISSUE TITLE
Scout user meeting 6/9

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/scout#592]
- Blog post [3.3](http://www.clinicalgenomics.se/scout/blog/new-3.3.html)
- https://github.com/Clinical-Genomics/scout/issues/587
- https://github.com/Clinical-Genomics/scout/issues/588

Coming up 3.4:
- Pin, mark https://github.com/Clinical-Genomics/scout/issues/559
- New SV annotations https://github.com/Clinical-Genomics/scout/issues/557
- Aggregate view https://github.com/Clinical-Genomics/scout/issues/320

Information points
- Reruns
- Hardware purchases

Discussion points
- Genes "lacking" transcripts https://github.com/Clinical-Genomics/scout/issues/570
- ACMG auto https://github.com/Clinical-Genomics/scout/issues/582
- Clinical filter https://github.com/Clinical-Genomics/scout/issues/577
- SNV/SV overlap https://github.com/Clinical-Genomics/scout/issues/567
- Nordic variant sharing workshop (Nov 16-17 in Oslo)
- SV training / workshop / discussion within community (2nd week of November)
- Future development projects - Discussion
  - SV Scout view
  - Aggregate statistics in Scout
  - Clinical Report feature in Scout
  - Clinical data sharing
  - WTS (Whole Transcriptome Sequencing)

**Comment by vwirta** [comment]
Made some additions

**Comment by robinandeer** [comment]
New  issues:

"Sanger email for SV": https://github.com/Clinical-Genomics/scout/issues/597

**Comment by robinandeer** [comment]
- [ ] Show on variant if a gene doesn't have an NM transcript
