### ISSUE TITLE
Show which gene was on panel for SV

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#598]
From Michaela at SCOUT meeting!
- on both pages? specific panel most important on the sv-variants view, all panels ok on sv-variant.

**Comment by robinandeer** [comment]
What do you mean with "specific panel"? Is this the "default panels" for the case or something different?

**Comment by dnil** [comment]
Ideally the one(s) from the query I guess, but the default panel (or any panel) will help.

**Comment by robinandeer** [comment]
@dnil: Would it work if we display the gene panels for each variant in the filter-view as a pop-up when hovering over the gene-cell in the table?

**Comment by robinandeer** [comment]
We can investigate if we can make a more advanced query on the individual variant view were we display for each gene if they belong to any of the panels.

**Comment by dnil** [comment]
Sounds like a plan! Hover highlighting gene of disease interest/panel will help considerably.

**Comment by robinandeer** [comment]
this is too big, we need more time to solve this issue in a maintainable way :)
