### ISSUE TITLE
Setup testing

### ISSUE THREAD

**Issue by robinandeer** [Clinical-Genomics/scout#6]
Once the MVP is complete we should move to more proper development and keep testing and peer review in mind.

TravisCI is a continuous testing tools with GitHub integration. Coveralls is tied into Travis and calculated test coverage which is reported back to the repo as a comment on pull requests.

- [ ] TravisCI
- [ ] coveralls.io
- [ ] https://pythonhosted.org/Flask-Testing/

**Comment by moonso** [comment]
I've started to do this in the portable version where I think everything should be tested.
To avoid duplication of code as much as possible we can wait with this in Scout

**Comment by robinandeer** [comment]
Testing in Flask:
https://realpython.com/blog/python/the-minimum-viable-test-suite/
