### ISSUE TITLE
Show INFO key 'set' in GT table for SV

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/scout#600]

**Comment by moonso** [comment]
What does it mean "vcf info key set"? Is this not the same as #601 ?

**Comment by henrikstranneheim** [comment]
No. It is the set=Intersect or set=manta-tiddit flag from svdb. Like the one we have for gatk, freebayes etc in the snv/indel view.

**Comment by moonso** [comment]
Ah ok
