### ISSUE TITLE
Link to mitomap seach query

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/scout#607]
Would it be possible to add a link to the seach result for alleles in mitomap from the variant page?

https://www.mitomap.org/foswiki/bin/view////Main/SearchAllele

**Comment by moonso** [comment]
It looks like it is not possible but @robinandeer should check it out

**Comment by henrikstranneheim** [comment]
Otherwise let's fallback to just link to the search page without filling in the positions

**Comment by henrikstranneheim** [comment]
Also it would be nice if this link only showed for MT variants as it is only relevant there

**Comment by robinandeer** [comment]
We can only link to the site where the user has to put in the query... it's using a POST form with some kind of validation it seems 😛  #dontBreakTheWeb 🚫
