### ISSUE TITLE
Use downsampled bam to display MT alignments

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/scout#608]
For chrMT the alignment view never loads any reads because there can be 50 000 of them. Can one put a constraint on the loading process to terminate after loading say 500 (random) reads from the BAM file?

**Comment by moonso** [comment]
I think that will be hard, maybe MIP can create a MT-bamfile? I can look into it soon

**Comment by henrikstranneheim** [comment]
The best would be if the j.s.pileup?? has the feature to limit the loading of reads.

**Comment by moonso** [comment]
Hmm this is a tricky one, we'll see when we can solve it

**Comment by moonso** [comment]
Could we agree that this is a MIP issue? There should be an alternative in scout config to point at a downsampled bam file for MT

**Comment by henrikstranneheim** [comment]
Yes, I will try and fix this on my end

**Comment by henrikstranneheim** [comment]
MIP will now produce a downsampled MT.bam and MT.bam.bai for the alignment view. This is recorded in the qc_sampleinfo.yaml file under the "samtools_subsample_mt/path=file_path".

**Comment by moonso** [comment]
Fixed
