### ISSUE TITLE
ACMG not working

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#612]
bottons not active.
see https://clinical-db.scilifelab.se:8083/cust003/17139/aafee5813505c5416c264205cea8ee5d/acmg

**Comment by robinandeer** [comment]
Can you explain further?

The button on top are only for previewing the automatically calculated ACMG code base on your selection of criteria.

Can you select different criteria?

**Comment by 4WGH** [comment]
i could not select the criteria


________________________________
Från: Robin Andeer <notifications@github.com>
Skickat: den 19 september 2017 14:26:33
Till: Clinical-Genomics/scout
Kopia: Michela Barbaro; Author
Ämne: Re: [Clinical-Genomics/scout] ACMG not working (#612)


Can you explain further?

The button on top are only for previewing the automatically calculated ACMG code base on your selection of criteria.

Can you select different criteria?

**Comment by moonso** [comment]
@4WGH can you try again now?

**Comment by 4WGH** [comment]
not it is working,
the graphic is misleading. If I click it works , but if  I try to pull the bottom from left to right it doesn't work. :)
