### ISSUE TITLE
Visualise large scale UPD, auto/hemi/homozygosity, ploidy - and document these features

### ISSUE THREAD

**Issue by moonso** [Clinical-Genomics/scout#613]
We need to add what is collected from Scout to show UDP etc

**Comment by dnil** [comment]
Aneuploidy, UPD, etc?

**Comment by moonso** [comment]
Could you elaborate on this one @bjhall ?

**Comment by bjhall** [comment]
Sure, I'll try. I am not exactly sure what you're after, but I'll make a guess :) I am guessing you want to know what information needs to be imported into Scout to represent UPD data? The two things I can think of that need to be be collected for a UPDs are:

* Isodisomy or heterodisomy
* Parent of origin (the same UPD can lead to different diseases if the chromosomes come from the mother or the father)

But the bigger question is probably how to present the data in Scout. At the moment you present it per variant, right? This is useful information, but I think clinicians will want the results in the form of "the long arm of chromosome 15 is affected by UPD from the mother". So perhaps it is more useful to somehow represent them as structural variants?

**Comment by dnil** [comment]
The leukaemia cases (and solid tumors for that matter) would benefit from also showing any gross anueploidy as well in a similar manner. Data for the latter can be exported from TIDDIT as a polidy tab. However, there is no standardised way to convert this to a VCF that I know of, short of adding "fake" chromosome level CNVs to a SV track. I would initially propose reading the TIDDIT tabs anyway and show chromosome-arm level events on a separate view. That could include ploidy changes and UPD. For UPD we would read in a similar table from rhocall. If someone comes up with a nice chromosome-tab-to-VCF conversion later, I'd be happy to switch to reading it instead. Sounds good? Other suggestions?

**Comment by TJO-Lund** [comment]
WGS-gSNP (visualizing UPDs segmental and whole chromosome, and parental origin of de novo deletions) and Gens (with BAF for SNPs), developed in Lund solves this beautifully as well :)

**Comment by dnil** [comment]
Have you released WGS-gSNP somewhere yet? Cant find it on GitHub?

**Comment by bjhall** [comment]
Technically there is no such thing as WGS-gSNP. It is basically bcftools roh, UPD.py, some GATK stuff to normalize read depth data and finally a makeshift Perl script to generate a static plot with all these things. 

My plan is to visualize these things in Gens instead at some point and get rid of the static plot.

However, I think it would be interesting to show these sorts of things in a tabular format in scout as well, to allow adding comments and all that traceability goodness.

**Comment by dnil** [comment]
We could definitely do that with the UPD calls (and rho blocks, though they are a bit noisier). The discussion usually ebbs around where we discuss wether to put those on the sv view directly, or make a separate list. I would guess the latter if we want to make it happen sooner.
