### ISSUE TITLE
Guidelines for docstrings

### ISSUE THREAD

**Issue by moonso** [Clinical-Genomics/scout#62]
There are slight differences in how we write the docstrings.
Is there any guidleines for how we should write them?
For example:
Should we use 'Arguments', 'Args' or 'Input' when describing the arguments?

**Comment by robinandeer** [comment]
I've been using the more readable (yet parseable by Sphinx) "Google docstrings":

http://sphinxcontrib-napoleon.readthedocs.org/en/latest/example_google.html

**Comment by moonso** [comment]
Perfect! I like readable lets try to follow this as much as possible.
