### ISSUE TITLE
Add GNOMAD AF and AF_POPMAX fields

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/scout#625]
MIP 5.1 now produce these fields in the VCF INFO:

##INFO=<ID=GNOMADAF,Number=A,Type=Float,Description="Allele Frequency among genotypes, for each ALT allele, in the same order as listed">
##INFO=<ID=GNOMADAF_POPMAX,Number=A,Type=Float,Description="Maximum Allele Frequency across populations (excluding OTH)">

In scout they can replace the EXAC freq info and I think we should display both fields.

**Comment by moonso** [comment]
Replaced by #626
