### ISSUE TITLE
Replace EXAC or simply add GNOMAD VCF INFO keys to freq pop-ups

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/scout#626]

**Comment by dnil** [comment]
Also correct typo gnomeAD -> gnomAD 😊

**Comment by moonso** [comment]
MIP 5.1 now produce these fields in the VCF INFO:

##INFO=<ID=GNOMADAF,Number=A,Type=Float,Description="Allele Frequency among genotypes, for each ALT allele, in the same order as listed">
##INFO=<ID=GNOMADAF_POPMAX,Number=A,Type=Float,Description="Maximum Allele Frequency across populations (excluding OTH)">

In scout they can replace the EXAC freq info and I think we should display both fields.

**Comment by robinandeer** [comment]
@moonso: you can assign me when you've added parsing for these keys 👍

**Comment by robinandeer** [comment]
@moonso: I still don't think this is parsed during scout load

Have you settled on some keys to use for the variant document?

**Comment by henrikstranneheim** [comment]
Supported from next MIP update

**Comment by moonso** [comment]
Fixed
