### ISSUE TITLE
Search for a gene by HGNC:ID does not work

### ISSUE THREAD

**Issue by AnnHam** [Clinical-Genomics/scout#632]
When adding a gene to a gene panel (pending changes) searching for a gene by HGNC:ID does not work, only for the first two numbers then it tries to find aliases/synonyms etc. 

I also had one gene that had a too short name to be found, since the gene's name was included in many other gene names. Shouldn't a perfect match be found? (The gene was ICK, eventually I could find it by searching for synonyms to the gene - and found that it was already included in the gene panel...).

**Comment by moonso** [comment]
Thought we fixed this before.. We will try again
