### ISSUE TITLE
Show warning if filtering on a non-clinical gene

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#633]
I look for variants in the genes NDUFA5 and RFK in patient 17120 using the filter tool.
I get a message that there are not variants in this genes. I've checked if the genes where in the OMIM-auto list v.1 2017-03-21 and I could not find them.

Nicole and I understood that only genes in OMIM are visible in a clinical subject, otherwise we need to wish the research list to be opened in order to look at other genes.

So the question now is for the RFK gene that is not in the OMIM list the message no variants means
1. no variants
2. variants can not be shown

This is a very important difference when we look for variants in candidate gene outside the panel in our patients.

**Comment by moonso** [comment]
Hi,

if the genes do not exist in omim or any of the other panels there will not be any variants in those genes unless one opens research.

If I understand correct you would like a way to know if a particular gene exists in omim or any other panel?

Or would you like the search result to display "no variants"/"variants can not be shown" ?

**Comment by 4WGH** [comment]
We want that if we search for a gene and we get the answer not variants are present this is because there are No variants. So if it is not in OMIM I'd like to be notified.

Otherwise I get a sort of false negative answer :)
There could be variants but they can not be seen in the clinical setting.

So the answer "variants, if any, can not be shown" would be a  good answer :)

**Comment by 4WGH** [comment]
By the way the gene is in OMIM but is NOT connected to a disease
