### ISSUE TITLE
error in load_database.py prevents creation of users in 3.5 (pip)

### ISSUE THREAD

**Issue by marchoeppner** [Clinical-Genomics/scout#638]
Hi,
just started trying to use Scout and ran into a small bump. 

My setup: Fresh Install of Ubuntu Xenial in a Singularity Container with a minimal system, Python2.7 and pip 9 and the current stable release of scout from pip. 

When trying to create a user, I got an error saying that the global variable institute_name was not defined; this seems to trace back to line 55 in load_database.py where the method accepts the institute ID from the command line, and then tries to re-assign institute_id=institute_name, which does not exist in this context. 
Changing this to institute_id=institute_id fixes the issue for me. 

Best,
Marc

**Comment by moonso** [comment]
Hi,

nice to hear that you are trying out Scout!
Ok that procedure is a bit confusing, I will fix that.
Thx

**Comment by moonso** [comment]
Feel free to open a Pull Request if you find more like these 😄
