### ISSUE TITLE
Enabling authentication?

### ISSUE THREAD

**Issue by marchoeppner** [Clinical-Genomics/scout#640]
Hi,

I was wondering how to enable OAuth Authentication (vs Google)? I followed the setup instructions at http://www.clinicalgenomics.se/scout to the letter and am now able to log in with any white-listed email address without providing any password (3.5 stable from pip). It just logs me in.

Obviously, that wouldn't be any good in a production setting ;)

/M

**Comment by robinandeer** [comment]
Hi! Great to get confirmation that the setup instructions are working for you at least

Being able to login without a password is the intended case. We are using Google OAuth in production, however, and this is enabled by providing a `GOOGLE` dict in the Scout/Flask server config.

You have to register as a Google developer and obtain a few details like consumer key and consumer secret to make it work. The dict should look like this:

```python
GOOGLE = dict(
    consumer_key='??????????????',
    consumer_secret='??????????????',
    # Prepend to all (non-absolute) request URLs
    base_url='https://www.googleapis.com/oauth2/v1/',
    authorize_url='https://accounts.google.com/o/oauth2/auth',
    request_token_url=None,
    request_token_params={
        'scope': ("https://www.googleapis.com/auth/userinfo.profile "
                  "https://www.googleapis.com/auth/userinfo.email"),
    },
    access_token_url='https://accounts.google.com/o/oauth2/token',
    access_token_method='POST'
)
```

I will take some time to update the documentation to explain this a bit clearer!
