### ISSUE TITLE
Chanjo: add MT transcripts to database

### ISSUE THREAD

**Issue by robinandeer** [Clinical-Genomics/scout#642]
- [ ] export MT exons/transcripts from Scout @moonso 
- [ ] update prod chanjo4 database
- [ ] update pipeline files

**Comment by moonso** [comment]
Hi @adrosenbaum , this is one of the main tasks for you to start with. It will be a milestone when this issue is solved:=)

**Comment by moonso** [comment]
Move this to [chanjo](https://github.com/Clinical-Genomics/chanjo/issues/205)
