### ISSUE TITLE
disease associated transcript not showing

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#643]
look at the link below
https://scout.scilifelab.se/cust003/14045/994e5710384a92220cea2d6f830a5fb1

according to my table the disease associated transcript was registered at submission. Could you cross chekc why it is not coming up?

thank
Mic

**Comment by robinandeer** [comment]
There is a disease casusing transcript showing up - has this fixed your issue?

**Comment by 4WGH** [comment]
probably someone has already fix this ! O_0



________________________________
Från: Robin Andeer <notifications@github.com>
Skickat: den 8 november 2017 15:00:28
Till: Clinical-Genomics/scout
Kopia: Michela Barbaro; Author
Ämne: Re: [Clinical-Genomics/scout] disease associated transcript not showing (#643)


There is a disease casusing transcript showing up - has this fixed your issue?
