### ISSUE TITLE
Use scout to export Exons for chanjo

### ISSUE THREAD

**Issue by moonso** [Clinical-Genomics/scout#644]
See also #642

**Comment by moonso** [comment]
This is blocked at the moment since we are not sure how to define the exon boundaries

**Comment by robinandeer** [comment]
Here's the code for parsing Biomart output including the URL to generate it in the first place.

I parse out the UTR regions and store everything in a dict with each of the exons as a key with a list of transcripts/genes appended to it.

[parse-ensembl-exons.zip](https://github.com/Clinical-Genomics/scout/files/1390968/parse-ensembl-exons.zip)

**Comment by moonso** [comment]
This is more of a Chanjo issue. We will add functionality to export exon definitions from Scout. New issue is [open](https://github.com/Clinical-Genomics/chanjo/issues/204) in chanjo

**Comment by moonso** [comment]
We will add exons and a cli command for exporting those

**Comment by dnil** [comment]
Done with #1295?

**Comment by moonso** [comment]
Yes
