### ISSUE TITLE
Why is a pathogenic variant from ClinVar not shown in SCOUT?

### ISSUE THREAD

**Issue by AnnHam** [Clinical-Genomics/scout#651]
Why is a pathogenic variant from ClinVar not shown in SCOUT?

https://scout.scilifelab.se/cust002/F0013626-2/286717ce1d61848c0c18380786aa5d87
https://www.ncbi.nlm.nih.gov/clinvar/variation/381575/

//Anna

**Comment by dnil** [comment]
Nice catch Anna! 

Looks like the ClinVar entry is from January 2017. Could be a question for MIP / production: how often is the ClinVar reference updated? If so, for Scout: perhaps display references versions somewhere - like an extended delivery report?

**Comment by robinandeer** [comment]
This is a MIP related Issue - we have notified @henrikstranneheim

**Comment by henrikstranneheim** [comment]
We plan to update some references more frequently (perhaps once a month). Clinvar is included in this.

I have updated clinvar (clinvar_20171029.vcf) in the development branch and are running tests. Should be just a change in config to make into production if no tests fail.
