### ISSUE TITLE
local obs filter is currently not 0-inclusive

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#652]
3.4.1 has an issue with filtering on local obs. Needs to be made 0-inclusive again.

**Comment by dnil** [comment]
db issue? see case 2017-05797 / 16166

**Comment by robinandeer** [comment]
Might be because some cases don't have the key and other cases have a key with value "null"...

**Comment by robinandeer** [comment]
I found a way to do this in pymongo but it seems to work slightly different from Pymongo

just pointing it out:

```python
{'local_obs_old': None}
```

is not the same as:

```javascript
{local_obs_old: null}
```
