### ISSUE TITLE
CSV - length -1 for a deletion of 80 genes

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#654]
https://scout.scilifelab.se/cust003/17159/sv/variants?variant_type=clinical&gene_panels=EP&hgnc_symbols=&size=&chrom=&thousand_genomes_frequency=

please have a look. Something doesn't fit here.
A deletion of 1 bp can not contain 80 genes.

thanks,
Michela

**Comment by robinandeer** [comment]
This is how it's annotated in the VCF - but we will investigate how to better display it in Scout

**Comment by moonso** [comment]
Hi @4WGH , unfortunately the SV analysis is not as simple as SNV/INDEL so there are cases like these where the callers say that there is a insertion or deletion of unknown length. We have chosen to represent this with `-1`  so that it is clear that the length is unknown.

**Comment by moonso** [comment]
I will have a look anyway and see if there is anything we can do about it 👍

**Comment by 4WGH** [comment]
ok. good to know.

Maybe a "n.d." (not determined)  instead of "-1" could be more clear for the user who can not know how is the analysis behind scout.


I've thoughtit was a bug.



Michela

________________________________
Från: Måns Magnusson <notifications@github.com>
Skickat: den 9 november 2017 12:58:04
Till: Clinical-Genomics/scout
Kopia: Michela Barbaro; Mention
Ämne: Re: [Clinical-Genomics/scout] CSV - length -1 for a deletion of 80 genes (#654)


Hi @4WGH<https://github.com/4wgh> , unfortunately the SV analysis is not as simple as SNV/INDEL so there are cases like these where the callers say that there is a insertion or deletion of unknown length. We have chosen to represent this with -1 so that it is clear that the length is unknown.

**Comment by moonso** [comment]
There are cases where we can improve on this so we'll fix that

**Comment by moonso** [comment]
Yes, good point with `n.d.` could you convert `-1` to `n.d.` @robinandeer ?
