### ISSUE TITLE
Matching causative not showing on family page

### ISSUE THREAD

**Issue by NicoleCMMS** [Clinical-Genomics/scout#655]
The following two families have a matching causative variant in the POLG gene, 17042 and 17126.  When you go to the variant page you can see that this variant has been previously found as a causative variant and in which family but on the first page for each of these families it states that there are no matching causatives.  Is this a bug?

**Comment by moonso** [comment]
Thank you for discovering this serious problem, we will try to fix it before the weekend

**Comment by moonso** [comment]
@robinandeer could you try to figure out where the problem occurs. It doesn't seem to be a problem on the variant page so the adapter is probably doing it right...

**Comment by robinandeer** [comment]
We queried on the unique "_id" instead of the "variant_id" - but I fixed it now

**Comment by robinandeer** [comment]
but we really should make a page for displaying all of these matches together!

it should be hard or slow and it would be really cool use of the data in Scout

**Comment by dnil** [comment]
Sorry, did we loose the checking of self here? Note e.g. on case F0012102: gives matching other for its own causative for what can't really be anywhere else (and only one case noted on loqus).

**Comment by moonso** [comment]
Thanks @dnil I'll create a new issue for this
