### ISSUE TITLE
allignment view not loading

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#659]
in none of the fam I've tried.

https://scout.scilifelab.se/cust003/17175/e20a3996809e46086559f1613e8fd8db

this is just one of them to try at your side

Michela

**Comment by moonso** [comment]
I had no problem loading the alignment view in this example...
Could it be a temporary problem?

**Comment by henrikstranneheim** [comment]
I believe Robin has fixed this!
