### ISSUE TITLE
Can not add samples in Orderportal...

### ISSUE THREAD

**Issue by KickiLagerstedt** [Clinical-Genomics/scout#661]
New version of orderportal?
Can not add samples...
![bild](https://user-images.githubusercontent.com/17139607/32827822-aef313cc-c9ed-11e7-9616-d99d81fd98e5.png)

**Comment by robinandeer** [comment]
Hej Kicki!

I emailed about a new version of the portal was upcoming a week ago or so. I hope it reached you, I sent it on the scout email list.

Like the previous version of the portal you first need to add a family before you can add a sample to the family.

If you only want to order FASTQ files you can add samples right away but for analysis of the samples we need the family info for all samples 🙂
