### ISSUE TITLE
Auto-display default gene lists

### ISSUE THREAD

**Issue by robinandeer** [Clinical-Genomics/scout#68]
This still doesn't seem to work as expected...

**Comment by robinandeer** [comment]
I think I've located the issue to ``get_case.py``. It reads the default gene list(s) from a field "Clinical_db" which I've named "Clinical_db_gene_annotation"...

We should decide if we want to read this type of case-level information from the pedigree file in the future or the standard Scout INI-config. What do you think @moonso?

```python
for clinical_db in individual.extra_info.get('Clinical_db', '').split(','):
        default_gene_lists.add(clinical_db)
```

I believe the downstream processing should work as long as the database contains the correct gene lists name.

**Comment by moonso** [comment]
Ok, I think we should avoid to stuff things into the ped file as much as possible.
This is perfect for the scout config, right?

**Comment by robinandeer** [comment]
I do agree!

What do you want to use for key in the config? "default_gene_lists"?

**Comment by moonso** [comment]
sure thing!

**Comment by robinandeer** [comment]
Now we just need to figure out how we are going to get it automatically into Scout... I guess I need to start interfacing with LIMS :disappointed:

**Comment by moonso** [comment]
Haha we all knew that day would come...

**Comment by moonso** [comment]
So I change this in the branch that I'm currently working on.

**Comment by robinandeer** [comment]
Yes, I don't have to make any Scout changes for this anyways.
