### ISSUE TITLE
Coverage report for family 17057--2

### ISSUE THREAD

**Issue by NicoleCMMS** [Clinical-Genomics/scout#682]
There are two individuals sequence in this family but the coverage report seems to have got mixed up.  According to the report both individuals are females (incorrect) and have the exact same coverage.  Can somebody look into this for me? Thanks!

**Comment by robinandeer** [comment]
This seems to have been fixed: now a male and female shows up in the report

https://scout.scilifelab.se/reports/report?panel_name=Inborn+Errors+of+Metabolism+%2811.0%29&sample_id=ACC3170A9&sample_id=SVE2645A12&level=10
