### ISSUE TITLE
How to update panels for a case?

### ISSUE THREAD

**Issue by PeterARBork** [Clinical-Genomics/scout#684]
After looking around in the documentation it is still not clear to me if its possible and how I can update the panels available to a particular case.

It would be nice with this stuff in the documentation somewhere.

Is there already a way to do this without re-loading the case?

Thank you.

**Comment by moonso** [comment]
Hi @PeterARBork , it is not possible to change the panel for a case that is already loaded. When we have a situation like that we reanalyze the case with the new/updated panel(s) and reload them into scout.

**Comment by PeterARBork** [comment]
Alright, this situation arose in playing with scout, so I'll close this issue and open a new one if the situation comes up in "real life."

**Comment by moonso** [comment]
Ok, we have a long term plan to solve this within scout. It will take a lot of work since all variants has to be reranked etc...
