### ISSUE TITLE
String misformat in case loading warning (minor)

### ISSUE THREAD

**Issue by PeterARBork** [Clinical-Genomics/scout#685]
I think the author of the line below intended a '%' rather than a ',':
https://github.com/Clinical-Genomics/scout/blob/f9fef6c4d18a8b68b16be704a588c543bcefda08/scout/adapter/mongo/case.py#L221

The line comes out as
```
2017-12-06 10:44:16 risoe-r04-cn089 scout.commands.load.case[7863] WARNING ('Case %s already exists in database', '57PGF')
```

**Comment by moonso** [comment]
Nice catch
