### ISSUE TITLE
VCF preparation steps

### ISSUE THREAD

**Issue by PeterARBork** [Clinical-Genomics/scout#687]
Can you share what steps you take to generate the vcf's, i.e. from after you run variant calling?

I.e. do you run haplotypecaller, then VQSR, then SnpEff, and if so, with which settings?

It would be nice with a description of what the vcf's should (not) contain for Scout to fill in the variant columns.

Thank you.

**Comment by moonso** [comment]
Sure we can expand on that in the documentation, unfortunately it will take a while.
Meanwhile you can check out the [MIP documentation](http://mip-api.readthedocs.io/en/latest/index.html) and also ask @henrikstranneheim

**Comment by PeterARBork** [comment]
@henrikstranneheim would it be possible for you to share the sequence of commands which annotates the vcf files?

**Comment by henrikstranneheim** [comment]
Well it all depends on what you are analyzing. But we support Rhocall, Vt, VEP, SnpEFF, SnpSift, Vcfanno, Svdb, Genmod. There are nummerous annotations and parameters but some of the more important ones are Inheritance models, frequency, CADD, Spidex, CSQ, Clinvar.

**Comment by moonso** [comment]
@PeterARBork have you read [this](http://www.clinicalgenomics.se/scout/admin-guide/annotations.html) from scout docs? 

If it is lacking information we could expand that.

**Comment by PeterARBork** [comment]
It's warming up and with the latest changes to the repo I managed to add some of our own vcf content.

Thank you for working on this.

How can I access the scout database to see what annotations scout has successfully read from a given vcf?

I'm using VEP release 90 and getting a CLIN_SIG column in the CSQ-field which is seemingly not read by scout. The value benign(0), which I get for some variants, is not in the REV_CLINSIG_MAP constant, and [clnsig.py](scout/scout/parse/variant/clnsig.py) uses a different column name:
https://github.com/Clinical-Genomics/scout/blob/a94149dc7da54e0f4c477993800eb89719da3c72/scout/parse/variant/clnsig.py#L41

I tried changing these, but based on the filter in the web-interface, I still did not manage to make my clinsig annotation available for the filter.

**Comment by moonso** [comment]
Ok could you email a part of your vcf or show here exactly how this field is annotated in your file?
What is the VEP column name, what are the different options for the value and if the value has separators, what are they?

**Comment by PeterARBork** [comment]
The VEP CSQ column name is CLIN_SIG with clinvar version from june this year, and options for values include: benign(0), not_provided and more.

I'm not quite sure why there's a "(0)" on the benign tag in this version - at the moment we are moving to vep version 90. I'll return with a better understanding of the options for the value.

Here's an example of vcf-file:

```
##VEP="v90" time="2017-12-11 00:13:48" cache="/.../.vep/homo_sapiens/90_GRCh38" db="homo_sapiens_core_90_38@ensembldb.ensembl.org" ensembl-funcgen=90.743f32b ensembl=90.4a44397 ensembl-io=90.9a148ea ensembl-variation=90.58bf949 1000genomes="phase3" COSMIC="81" ClinVar="201706" ESP="V2-SSA137" HGMD-PUBLIC="20164" assembly="GRCh38.p10" dbSNP="150" gencode="GENCODE 27" genebuild="2014-07" gnomAD="170228" polyphen="2.2.2" regbuild="16" sift="sift5.2.2"
##INFO=<ID=CSQ,Number=.,Type=String,Description="Consequence annotations from Ensembl VEP. Format: Allele|Consequence|IMPACT|SYMBOL|Gene|Feature_type|Feature|BIOTYPE|EXON|INTRON|HGVSc|HGVSp|cDNA_position|CDS_position|Protein_position|Amino_acids|Codons|Existing_variation|DISTANCE|STRAND|FLAGS|VARIANT_CLASS|SYMBOL_SOURCE|HGNC_ID|SOURCE|SIFT|PolyPhen|MAX_AF|MAX_AF_POPS|CLIN_SIG|SOMATIC|PHENO|PUBMED|gnomADg|gnomADg_AF_AFR|gnomADg_AF_AMR|gnomADg_AF_ASJ|gnomADg_AF_EAS|gnomADg_AF_FIN|gnomADg_AF_NFE|gnomADg_AF_OTH">
##INFO=<ID=gnomADg,Number=.,Type=String,Description="/.../gnomad.genomes.r2.0.1.sites.GRCh38.noVEP.vcf.gz (exact)">
##INFO=<ID=gnomADg_AF_AFR,Number=.,Type=String,Description="AF_AFR field from /.../gnomad.genomes.r2.0.1.sites.GRCh38.noVEP.vcf.gz">
##INFO=<ID=gnomADg_AF_AMR,Number=.,Type=String,Description="AF_AMR field from /.../gnomad.genomes.r2.0.1.sites.GRCh38.noVEP.vcf.gz">
##INFO=<ID=gnomADg_AF_ASJ,Number=.,Type=String,Description="AF_ASJ field from /.../gnomad.genomes.r2.0.1.sites.GRCh38.noVEP.vcf.gz">
##INFO=<ID=gnomADg_AF_EAS,Number=.,Type=String,Description="AF_EAS field from /.../gnomad.genomes.r2.0.1.sites.GRCh38.noVEP.vcf.gz">
##INFO=<ID=gnomADg_AF_FIN,Number=.,Type=String,Description="AF_FIN field from /.../gnomad.genomes.r2.0.1.sites.GRCh38.noVEP.vcf.gz">
##INFO=<ID=gnomADg_AF_NFE,Number=.,Type=String,Description="AF_NFE field from /.../gnomad.genomes.r2.0.1.sites.GRCh38.noVEP.vcf.gz">
##INFO=<ID=gnomADg_AF_OTH,Number=.,Type=String,Description="AF_OTH field from /.../gnomad.genomes.r2.0.1.sites.GRCh38.noVEP.vcf.gz">
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  57PGF
chr1    13613   .       T       A       11.12   LowQual AC=1;AF=0.5;AN=2;BaseQRankSum=0.974;ClippingRankSum=0;DP=15;ExcessHet=3.0103;FS=6.99;MLEAC=1;MLEAF=0.5;MQ=27.44;MQRankSum=-1.526;QD=0.74;ReadPosRankSum=1.032;SOR=2.807;CSQ=A|non_coding_transcript_exon_variant|MODIFIER|DDX11L1|ENSG00000223972|Transcript|ENST00000450305|transcribed_unprocessed_pseudogene|6/6||||575/632|||||rs879980801||1||SNV|HGNC|HGNC:37102||||||||||1:13613-13613|8.52411e-04|1.38889e-03|0.00000e+00|5.57880e-03|1.24224e-03|7.01481e-04|2.49377e-03,A|non_coding_transcript_exon_variant|MODIFIER|DDX11L1|ENSG00000223972|Transcript|ENST00000456328|processed_transcript|3/3||||861/1657|||||rs879980801||1||SNV|HGNC|HGNC:37102||||||||||1:13613-13613|8.52411e-04|1.38889e-03|0.00000e+00|5.57880e-03|1.24224e-03|7.01481e-04|2.49377e-03,A|downstream_gene_variant|MODIFIER|WASH7P|ENSG00000227232|Transcript|ENST00000488147|unprocessed_pseudogene||||||||||rs879980801|791|-1||SNV|HGNC|HGNC:38034||||||||||1:13613-13613|8.52411e-04|1.38889e-03|0.00000e+00|5.57880e-03|1.24224e-03|7.01481e-04|2.49377e-03,A|downstream_gene_variant|MODIFIER|MIR6859-1|ENSG00000278267|Transcript|ENST00000619216|miRNA||||||||||rs879980801|3756|-1||SNV|HGNC|HGNC:50039||||||||||1:13613-13613|8.52411e-04|1.38889e-03|0.00000e+00|5.57880e-03|1.24224e-03|7.01481e-04|2.49377e-03   GT:AD:DP:GQ:PL  0/1:12,3:15:39:39,0,294
chr1    69511   rs2691305       A       G       83.03   VQSRTrancheSNP99.90to100.00     AC=2;AF=1;AN=2;DB;DP=4;ExcessHet=3.0103;FS=0;MLEAC=2;MLEAF=1;MQ=30.51;QD=20.76;SOR=0.693;VQSLOD=-37.15;culprit=MQ;CSQ=G|missense_variant|MODERATE|OR4F5|ENSG00000186092|Transcript|ENST00000335137|protein_coding|1/1||||457/1054|421/918|141/305|T/A|Aca/Gca|rs2691305||1||SNV|HGNC|HGNC:14825||tolerated(0.82)|benign(0)|0.9995|gnomAD_EAS|||||rs2691305|5.88652e-01|9.41038e-01|9.67213e-01|1.00000e+00|9.91848e-01|9.63751e-01|9.40426e-01,G|missense_variant|MODERATE|OR4F5|ENSG00000186092|Transcript|ENST00000641515|protein_coding|3/3||||544/2618|421/918|141/305|T/A|Aca/Gca|rs2691305||1||SNV|HGNC|HGNC:14825||tolerated(0.82)|benign(0)|0.9995|gnomAD_EAS|||||rs2691305|5.88652e-01|9.41038e-01|9.67213e-01|1.00000e+00|9.91848e-01|9.63751e-01|9.40426e-01 GT:AD:DP:GQ:PL  1/1:0,4:4:12:111,12,0
```

**Comment by moonso** [comment]
@PeterARBork I think that CLIN_SIG does not have any value in the two variants that you have included.
`benign(0)` refers to SIFT and polyphen and is the readable term and the numeric.
At least if I understand correct. So please get back when you know how CLIN_SIG annotation looks like with VEP. If I'm right we annotate clinvar with SnpEff, is that correct @henrikstranneheim ?

**Comment by henrikstranneheim** [comment]
Yes, that is correct! 

Skickat från min iPhone

**Comment by PeterARBork** [comment]
That's a blunder on my part, thanks for the correction.

**Comment by moonso** [comment]
No problems!

**Comment by PeterARBork** [comment]
I'm having a bit of difficulty getting the annotated frequencies to appear in Scout.

Whether I use the key `1000G` or `1000GAF` in the vcf-file, Scout doesn't present the frequency of a variant I chose at random (details below).

The documentation says the key for 1000 genomes frequency should be `1000G`,
https://github.com/Clinical-Genomics/scout/blob/master/docs/admin-guide/annotations.md#annotation-keys-and-tool-suggestions

The code (below) seems to say the key should be `1000GAF`:
https://github.com/Clinical-Genomics/scout/blob/a94149dc7da54e0f4c477993800eb89719da3c72/scout/parse/variant/frequency.py#L17

The vep headers in the vcf file look like this:
```
##VEP="v90" time="2018-01-30 14:01:44" cache="/home/databases/variant_effect_predictor/.vep/homo_sapiens/90_GRCh38" db="homo_sapiens_core_90_38@ensembldb.ensembl.org" ensembl-variation=90.58bf949 ensembl=90.4a44397 ensembl-io=90.9a148ea ensembl-funcgen=90.743f32b 1000genomes="phase3" COSMIC="81" ClinVar="201706" ESP="V2-SSA137" HGMD-PUBLIC="20164" assembly="GRCh38.p10" dbSNP="150" gencode="GENCODE 27" genebuild="2014-07" gnomAD="170228" polyphen="2.2.2" regbuild="16" sift="sift5.2.2"
##INFO=<ID=CSQ,Number=.,Type=String,Description="Consequence annotations from Ensembl VEP. Format: Allele|Consequence|IMPACT|SYMBOL|Gene|Feature_type|Feature|BIOTYPE|EXON|INTRON|HGVSc|HGVSp|cDNA_position|CDS_position|Protein_position|Amino_acids|Codons|Existing_variation|DISTANCE|STRAND|FLAGS|VARIANT_CLASS|SYMBOL_SOURCE|HGNC_ID|SIFT|PolyPhen|AFR_AF|AMR_AF|EAS_AF|EUR_AF|SAS_AF|gnomAD_AF|gnomAD_AFR_AF|gnomAD_AMR_AF|gnomAD_ASJ_AF|gnomAD_EAS_AF|gnomAD_FIN_AF|gnomAD_NFE_AF|gnomAD_OTH_AF|EXAC_MAX_AF|1000GAF|MAX_AF_POPS|CLIN_SIG|SOMATIC|PHENO|PUBMED">
```
I've changed the `1000GAF` to `1000G` (and other things), without luck.

The variant I'm looking at as example is:
```
chr4    54263911        rs2229307       T       C       568.77  PASS    AC=1;AF=0.5;AN=2;BaseQRankSum=-5.167;ClippingRankSum=0;DB;DP=43;ExcessHet=3.0103;FS=2.659;MLEAC=1;MLEAF=0.5;MQ=60;MQRankSum=0;POSITIVE_TRAIN_SITE;QD=13.54;ReadPosRankSum=-2.64;SOR=0.368;VQSLOD=19.77;culprit=MQRankSum;CSQ=C|synonymous_variant|LOW|PDGFRA|ENSG00000134853|Transcript|ENST00000257290|protein_coding|4/23||||943/6576|612/3270|204/1089|N|aaT/aaC|rs2229307&COSM4416371||1||SNV|HGNC|HGNC:8803|||0.2776|0.3487|0.2034|0.1233|0.2505|0.1855|0.2587|0.4145|0.0715|0.1776|0.1241|0.121|0.1578|0.2225|0.4145|gnomAD_AMR|benign|0&1|1&1|25741868,C|downstream_gene_variant|MODIFIER|PDGFRA|ENSG00000134853|Transcript|ENST00000503856|protein_coding||||||||||rs2229307&COSM4416371|135|1|cds_end_NF|SNV|HGNC|HGNC:8803|||0.2776|0.3487|0.2034|0.1233|0.2505|0.1855|0.2587|0.4145|0.0715|0.1776|0.1241|0.121|0.1578|0.2225|0.4145|gnomAD_AMR|benign|0&1|1&1|25741868,C|downstream_gene_variant|MODIFIER|PDGFRA|ENSG00000134853|Transcript|ENST00000504461|protein_coding||||||||||rs2229307&COSM4416371|138|1|cds_end_NF|SNV|HGNC|HGNC:8803|||0.2776|0.3487|0.2034|0.1233|0.2505|0.1855|0.2587|0.4145|0.0715|0.1776|0.1241|0.121|0.1578|0.2225|0.4145|gnomAD_AMR|benign|0&1|1&1|25741868,C|intron_variant|MODIFIER|AC058822.1|ENSG00000282278|Transcript|ENST00000507166|protein_coding||12/23||||||||rs2229307&COSM4416371||1||SNV|Clone_based_ensembl_gene||||0.2776|0.3487|0.2034|0.1233|0.2505|0.1855|0.2587|0.4145|0.0715|0.1776|0.1241|0.121|0.1578|0.2225|0.4145|gnomAD_AMR|benign|0&1|1&1|25741868,C|synonymous_variant|LOW|PDGFRA|ENSG00000134853|Transcript|ENST00000508170|protein_coding|4/4||||760/2202|612/657|204/218|N|aaT/aaC|rs2229307&COSM4416371||1||SNV|HGNC|HGNC:8803|||0.2776|0.3487|0.2034|0.1233|0.2505|0.1855|0.2587|0.4145|0.0715|0.1776|0.1241|0.121|0.1578|0.2225|0.4145|gnomAD_AMR|benign|0&1|1&1|25741868,C|non_coding_transcript_exon_variant|MODIFIER|PDGFRA|ENSG00000134853|Transcript|ENST00000509092|retained_intron|3/15||||430/2417|||||rs2229307&COSM4416371||1||SNV|HGNC|HGNC:8803|||0.2776|0.3487|0.2034|0.1233|0.2505|0.1855|0.2587|0.4145|0.0715|0.1776|0.1241|0.121|0.1578|0.2225|0.4145|gnomAD_AMR|benign|0&1|1&1|25741868,C|synonymous_variant&NMD_transcript_variant|LOW|PDGFRA|ENSG00000134853|Transcript|ENST00000509490|nonsense_mediated_decay|4/18||||729/2991|612/2232|204/743|N|aaT/aaC|rs2229307&COSM4416371||1||SNV|HGNC|HGNC:8803|||0.2776|0.3487|0.2034|0.1233|0.2505|0.1855|0.2587|0.4145|0.0715|0.1776|0.1241|0.121|0.1578|0.2225|0.4145|gnomAD_AMR|benign|0&1|1&1|25741868,C|downstream_gene_variant|MODIFIER|PDGFRA|ENSG00000134853|Transcript|ENST00000512143|protein_coding||||||||||rs2229307&COSM4416371|2499|1|cds_end_NF|SNV|HGNC|HGNC:8803|||0.2776|0.3487|0.2034|0.1233|0.2505|0.1855|0.2587|0.4145|0.0715|0.1776|0.1241|0.121|0.1578|0.2225|0.4145|gnomAD_AMR|benign|0&1|1&1|25741868,C|downstream_gene_variant|MODIFIER|PDGFRA|ENSG00000134853|Transcript|ENST00000512522|protein_coding||||||||||rs2229307&COSM4416371|149|1|cds_end_NF|SNV|HGNC|HGNC:8803|||0.2776|0.3487|0.2034|0.1233|0.2505|0.1855|0.2587|0.4145|0.0715|0.1776|0.1241|0.121|0.1578|0.2225|0.4145|gnomAD_AMR|benign|0&1|1&1|25741868   GT:AD:DP:GQ:PL  0/1:19,23:42:99:597,0,567
```

I can find this variant in Scout, but it has no other annotations than it's rs number:
![image](https://user-images.githubusercontent.com/11392762/35571415-5e42d892-05d2-11e8-97d2-b4559cb0cf21.png)

@moonso can you see what my problem is, or what can I do to make it clearer?

@henrikstranneheim if you have the time, it would be great and very helpful if you could show how to use your MIP program to take a "naked" vcf coming right out of haplotypecaller or VQSR and annotating it for Scout consumption. That way I can start adopting your pipeline.

**Comment by moonso** [comment]
Hi @PeterARBork , 
we annotate frequencies outside VEP but scout should definitely handle VEP annotations.
I know @bjhall worked on this some time ago.
Anyway I will see tomorrow if there is anything obvious that I can fix.

**Comment by bjhall** [comment]
We ended up annotating frequencies with both Genmod and VEP, but only the ones from Genmod end up in the database. The bugfix I submitted the other month just prevented a crash while loading VCFs with ExAC-annotations from VEP. Would be great if it could use the VEP freqs though, to avoid the double annotation.

**Comment by moonso** [comment]
@bjhall @PeterARBork what are the frequency keys that we would expect in the VEP entry?
Is VEP always annotating with the same keys or is it up to the user to define what the keys should look like? It is no problem if we expect the keys to always look the same...

**Comment by bjhall** [comment]
@moonso The key names are predefined by VEP. Unfortunately the key names have changed in recent versions (between v87 and v90). And they have also replaced ExAC with gnomAD exomes (ie not WGS). I've summarized the key names for v87 and v90 below (with links to the documentation)

VEP 87
------
**GMAF** - 1000G all popluations combined
**xxx_MAF** - 1000G (or NHLBI-ESP) individual populations
**ExAC_MAF** - ExAC all popluations
**ExAC_Adj_MAF**- ExAC all popluations (adjusted)
**ExAC_xxx_MAF** - ExAC individual populations
[http://dec2016.archive.ensembl.org/info/docs/tools/vep/vep_formats.html](http://dec2016.archive.ensembl.org/info/docs/tools/vep/vep_formats.html)

VEP 90
------
**AF** - 1000G all populations combined
**xxx_AF** - 1000G (or NHLBI-ESP) individual populations
**gnomAD_AF** - gnomAD exomes, all populations combined
**gnomAD_xxx_AF** - gnomAD exomes, individual populations
**MAX_AF** - Max of all populations (1000G, gnomAD exomes, ESP)
[https://www.ensembl.org/info/docs/tools/vep/vep_formats.html](https://www.ensembl.org/info/docs/tools/vep/vep_formats.html)

**Comment by moonso** [comment]
Thanks a lot!! Makes the problem much easier. The only thing I don't like is that we have to loop aver all transcripts but I guess the information will be identical for these entries.
Can it still be multiple entries for one frequency? (separated by `&`)

**Comment by dnil** [comment]
The AFs from 90 and onwards are supposed to be given only for the variants on that entry - so presumably only one for spit VCFs.

**Comment by bjhall** [comment]
Yes the frequencies are identical for all transcripts. I usually just use the values from the first transcript to avoid the looping.

And dnil is correct about it showing frequencies only for the relevant allele.

**Comment by moonso** [comment]
Ok, I guess we want to support version 87 so we still need to split then

**Comment by moonso** [comment]
I break out the frequency part to another issue and close this one
