### ISSUE TITLE
Why refer to case from institute?

### ISSUE THREAD

**Issue by moonso** [Clinical-Genomics/scout#69]
Whe should not need this, the case in itself have all information that is necessary.
So when removing a case we do not need to update institutes, seems like a more mongodb way of doing it.

**Comment by moonso** [comment]
@robinandeer what do you think?
Would that cause any troubles for you?

**Comment by robinandeer** [comment]
No, not as long as you replace the field with an "institutes" property that asks the question to the database I guess :smiley:

**Comment by moonso** [comment]
Where in the code do you get all cases for a institute?
Shouldn't this be a method in the mongo adapter?

**Comment by robinandeer** [comment]
I think we should have a more in depth discussion around this for the refactor of the portable version of Scout.

But right now I just do:

```python
for case in institute.cases:
   pass
```

Perhaps keep it similar to that for now? Even if it isn't ideal.

**Comment by moonso** [comment]
What do you think of this:
```python
def cases(self, institute):
  if institute:
    return Case.objects(collaborators = institute)
  else:
    return Case.objects()  
```

**Comment by robinandeer** [comment]
I can't speak for the MongoEngine implementation but the interface looks fine to me!
