### ISSUE TITLE
Parsing CLNACC from clinvar in Scout

### ISSUE THREAD

**Issue by patrikgrenfeldt** [Clinical-Genomics/scout#695]
"Here is a heads up for parsing CLNACC from clinvar in Scout:

- Clnvar has removed the CLNACC and replaced it with a variant id in the vcf ID column. When MIP downloads clinvar it will preprocess the clinvar vcf as follows: 
   1. Relay the clinvar variant id from the clinvar vcf ID column as a vcf info key in the same file.
   2. Add a new vcf INFO key pair and header as; '##INFO=<ID=CLNVID,Number=1,Type=Integer,Description="ClinVar Variation ID”>'

i.e I am replacing the CLNACC (which has been deprecated by clinvar) with CLNVID.

Also now it is structured as one line per alt. allele, which is a great improvement."

Contact: @henrikstranneheim

**Comment by moonso** [comment]
When will this change happen in the VCFs?

**Comment by henrikstranneheim** [comment]
Next update of MIP (v6.0.0). We cannot update this outside of MIP now since there is a major change of format.

**Comment by henrikstranneheim** [comment]
Here are the header from clinvar:
```
##INFO=<ID=CLNREVSTAT,Number=.,Type=String,Description="ClinVar review status for the Variation ID">
##INFO=<ID=CLNSIG,Number=.,Type=String,Description="Clinical significance for this single variant">
##INFO=<ID=CLNVID,Number=1,Type=Integer,Description="ClinVar Variation ID">
```
and some vcf info fields:
```
CLNREVSTAT=criteria_provided,_single_submitter;CLNSIG=Uncertain_significance;CLNVID=296280
CLNREVSTAT=criteria_provided,_multiple_submitters,_no_conflicts;CLNSIG=Benign/Likely_benign;CLNVID=262791
```

Here is an address for linking to the hompage:
https://www.ncbi.nlm.nih.gov/clinvar/variation/95677/

where: 95677 is the CLNVID.

**Comment by moonso** [comment]
I am sorry but these fields does not really make sense to me...
What should we actually display? Is it enough with a link to clinvar?

How should we display the above example?

or how should we display:

```
CLNREVSTAT=criteria_provided,_single_submitter;CLNSIG=Likely_benign;CLNVID=295823
```
?
