### ISSUE TITLE
Coverage for family 17094 not correct

### ISSUE THREAD

**Issue by NicoleCMMS** [Clinical-Genomics/scout#696]
I just downloaded the coverage report for this family and discovered a mistake.  The index patient is a male but in the coverage report appears as a female.  Can you confirm that the analysis is correct and if so correct the coverage report?  Thanks!
[Coverage_17094.pdf](https://github.com/Clinical-Genomics/scout/files/1588909/Coverage_17094.pdf)

**Comment by moonso** [comment]
Could anyone have a look on this one @emmser or @emiliaol ?

**Comment by emmser** [comment]
Now correct
[17094-180102.pdf](https://github.com/Clinical-Genomics/scout/files/1742969/17094-180102.pdf)
When I looked in the old tickets for this case, I found a ticket regarding this problem (355180). It says that this was only a problem for the coverage report and not for the analysis.

**Comment by moonso** [comment]
Ok can you close then?
