### ISSUE TITLE
Local obervations no decreased

### ISSUE THREAD

**Issue by KickiLagerstedt** [Clinical-Genomics/scout#697]
When looking at a variant the no regarding local observations has decreased from 898 to 347... 
How is that possible?

![bild](https://user-images.githubusercontent.com/17139607/34562075-189952c4-f14d-11e7-9f59-f7d4f0773852.png)

**Comment by dnil** [comment]
Launch of the new loqusdb (now with SV support)? Will be a little while until it has seen all cases again, I guess.

**Comment by moonso** [comment]
Yes that is correct @dnil , I don't think SV-support is there yet. @KickiLagerstedt it will catch up...
