### ISSUE TITLE
PDF coverage report empty

### ISSUE THREAD

**Issue by emmser** [Clinical-Genomics/scout#698]
Coverage report PDF-download generates empty reports

**Comment by moonso** [comment]
@emmser I think you need to be more specific. What case? Is it always like this?

**Comment by emmser** [comment]
@moonso all cases I have checked are the same. On the case-page, when you use Download PDF, the report that is generated contains no data, only an empty table. For example case 18005

**Comment by northwestwitch** [comment]
I'll try to fix this one!

**Comment by moonso** [comment]
👍
