### ISSUE TITLE
Analysis date in Coverage report for re-runs doesn't update

### ISSUE THREAD

**Issue by emmser** [Clinical-Genomics/scout#699]
Coverage report doesn't update analysis date after re-run

**Comment by northwestwitch** [comment]
I'll try to fix this

**Comment by northwestwitch** [comment]
Nevermind I've found one!

**Comment by northwestwitch** [comment]
I've checked the code and this is more a cg bug than a scout one. I'll open an issue there as well. Correct me if I'm wrong but whenever an analysis is ready it is uploaded to scout via "cg upload". "cg upload" calls in turn all the other modules like validate, genotypes, observations, scout and COVERAGE. if you call "cg upload coverage" manually and you want to produce an updated coverage report you pass it the parameter -r True , which stands for replace=true. When coverage is called by "cg upload" no -r parameter is passed, so replace=False. I think this might be the reason why the coverage data is not replaced after a re-run. If this is the case then all re-runs in scout have no updated coverage data, except for when in production it has been called "cg coverage -r manually".

**Comment by northwestwitch** [comment]
Thisbug was fixed in cg https://github.com/Clinical-Genomics/cg/issues/95. I close this issue.
