### ISSUE TITLE
HPO term problem

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#702]
we got the following answer when trying to add the HPO term: "HP:0012335"

Bad Request

unable to add phenotype: HP:0012335

what does it mean?

this seams to be a general problem, as we tried with several other numbers.

**Comment by moonso** [comment]
Will check

**Comment by northwestwitch** [comment]
@moonso if you have not starting working on this one I can take a look at it!

**Comment by moonso** [comment]
@northwestwitch yes please 🌾 🥋

**Comment by moonso** [comment]
The reason is that the term has been created after we updated the HPO terms in scout.
So the term is not in scout.
I've created a new issue #774
