### ISSUE TITLE
Enable HPO list filter for SV list

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#710]
I have not tested this explicitly yet. Anyone else?

**Comment by dnil** [comment]
Ok checked. Not working. Adding to todo.

**Comment by northwestwitch** [comment]
Hi @dnil, I don't know if you discussed about this issue with someone else already but if nobody is doing it I can work on this. You want to display some HPO terms in the same table as the SVs ..?

**Comment by dnil** [comment]
Thanks @northwestwitch!

It’s about connecting the HPO-queries over to the SV-view as well. 

Let’s talk about this today; I’ve got a few things to sort at the clinic in the morning, but will be over at Clinical Genomics by 10.30 or so.

// Daniel

**Comment by northwestwitch** [comment]
👍
