### ISSUE TITLE
Automate "Request research" to avoid having to wait for the data

### ISSUE THREAD

**Issue by patrikgrenfeldt** [Clinical-Genomics/scout#715]
As a Clinician 
I want the Research data to be available immediately after requesting it
so that I don't have to wait for it

Suggested solution:
Automate the handling of "Research request"'s

**Comment by moonso** [comment]
The process of uploading research variants will always take some time so it will not be instant. At the moment there is a cronjob running once per week that checks which cases have requested research and then upload the variants for those. We can change the interval for the automatic job so it runs once every day or something.
@emiliaol can you close this when you're done?

**Comment by emiliaol** [comment]
The upload has been changed so it will check once every day. If needed we can do this more frequently in the future.
