### ISSUE TITLE
no coverage report

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#720]
for fam 18002.
I get this error message:
502 Bad Gateway

can you help? thanks,
Michela

**Comment by ingkebil** [comment]
Please refresh! Should work :)

Does this happen a lot or was this the first time?

**Comment by 4WGH** [comment]
not the first time, 
but I would not say a lot :)
working now! thanks!

I see I'm not he only one working evenings ;)

**Comment by ingkebil** [comment]
OK then. I'll fiddle around with the setting and hopefully I can make it go away.

Of course! Kids asleep: time for satisfying work :)
