### ISSUE TITLE
Missing variants in mtDNA

### ISSUE THREAD

**Issue by 1ctw** [Clinical-Genomics/scout#731]
We have decided that all variants in mtDNA should be loaded in Scout in all cases. It has been like that for a while, but now they are not there anymore. One example is 17137 which has only one variant in mtDNA loaded. There are also cases, example 131, which has only variants in coding regions loaded but the ones in non-coding regions are missing.

**Comment by moonso** [comment]
@henrikstranneheim can you check how the VCF:s looks like for these?

**Comment by moonso** [comment]
Ok then I guess we have some kind of bug

**Comment by 1ctw** [comment]
Now you have done some changes in the presentation av mtDNA, that connect the mutations to all possible transcripts. This makes the analyzing of mtDNA in Scout almost impossible. Could you please check this out and change this back...

**Comment by moonso** [comment]
@1ctw I do not really follow here, what do you mean?
Should we not display all transcripts that a variant affects?

**Comment by moonso** [comment]
I'm closing this issue since I have fixed the problem with missing mt variants, they should all be uploaded. If there is another problem please open a new issue.
