### ISSUE TITLE
date on delivery report is not updated

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#745]
I look into fam 17074
the are 2 delivery report dated 
2017-06-02
2018-02-02

inside the date in both of them is 2017-06-03
and they look identical. is this OK?

Michela

**Comment by emmser** [comment]
The delivery report function disappeared in the update in September 2017, so the report is the one that was created in June. We are working hard to get the delivery report function back as soon as possible. We're sorry about this and hope for this to work during the nearest weeks.
