### ISSUE TITLE
Add button for remove sanger

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#746]
how can  I remove a Sanger order?

**Comment by 4WGH** [comment]
See fam 18021. we would like to remove the  Sanger order on the  variant on VPS11, but keep the  variant pinned.

**Comment by moonso** [comment]
Hi,

we don't have any functionality for that implemented

**Comment by moonso** [comment]
Fixed in #788

**Comment by 4WGH** [comment]
how does it work?

Michela

**Comment by moonso** [comment]
It will be obvious when we install the updated code

**Comment by 4WGH** [comment]
great!

you closed the issue so I though all was ready, but so it is not 😊

when it is goign to be?


thanks

Michela

________________________________
Från: Måns Magnusson <notifications@github.com>
Skickat: den 20 april 2018 09:55:21
Till: Clinical-Genomics/scout
Kopia: Michela Barbaro; Author
Ämne: Re: [Clinical-Genomics/scout] Add button for remove sanger (#746)


It will be obvious when we install the updated code

**Comment by moonso** [comment]
Yes it is a bit confusing, we have solved the issue but we need to update the code on the server for you  to see it. In the future we will update often, like once per week. At the moment we are waiting for some things before we can update but we will soon...
