### ISSUE TITLE
genes not deleted from panel!!! urgent

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#757]
Hi, in fam 18033 I filtered for IEM and EP I can see variants in the PAX8 gene and DUOX2 gene. these genes are in our ENDO lit not in the IEM version 12. these 2 genes were in version 11! 
They do not appear in the IEM panel v 12 in Scout, however at the PAX8 variant level it states this gene is in the IEM panel too! and is coming up.
The panel list really used by Scout is still including these genes.....
I've deleted at least 10 genes that were present in v11 and should NOT be in version 12.

Could something had gone odd when Måns corrected the version of the panel back to 12? (it went up to 14 when I had deleted the genes). Hope this can help to solve the problem.

something is not synced here.

**Comment by moonso** [comment]
Hi this is a bug already reported in #754 I will try to fix that asap, think we know what is wrong

**Comment by 4WGH** [comment]
Good!

does this imply any othet issue?

Or is it restricted to deleted genes?


Michela+

________________________________
Från: Måns Magnusson <notifications@github.com>
Skickat: den 2 mars 2018 11:26:28
Till: Clinical-Genomics/scout
Kopia: Michela Barbaro; Author
Ämne: Re: [Clinical-Genomics/scout] genes not deleted from panel!!! urgent (#757)


Closed #757<https://github.com/Clinical-Genomics/scout/issues/757>.

**Comment by moonso** [comment]
No this would only affect deleted genes
