### ISSUE TITLE
Rank score treshold for WGS samples

### ISSUE THREAD

**Issue by robinandeer** [Clinical-Genomics/scout#76]
How many variants from the clinical list is relevant to load?

When setting the rank score threshold to 0 I'm still loading > 38,000 variants and this is taking considerably longer than a normal WES case.

**Comment by moonso** [comment]
Hmm yes this is a problem, I can only imagine how many that would go into research...
We need to discuss the treshold with @henrikstranneheim , meanwhile we can set it higher. 
Maybe 7?

**Comment by robinandeer** [comment]
Yes, I will try to build this into the automatic loader. The final variant number was around 54,000.

**Comment by moonso** [comment]
Was 54000 with rank score treshold of 7?

**Comment by moonso** [comment]
I will create some plots for distribution of rank scores and post them here so that we can choose what treshold that is reasonable

**Comment by moonso** [comment]
We should consider to set a count treshold instead..

**Comment by robinandeer** [comment]
I don't mind either way :smile:

**Comment by moonso** [comment]
We have agreed to load 5000 variants to start with.
Users can request for more whenever they like
