### ISSUE TITLE
Change the submission email for re-runs requested through scout

### ISSUE THREAD

**Issue by emiliaol** [Clinical-Genomics/scout#766]
Today the requests for re-runs are submitted to SuSy using RAs sciliflab email, we need to change that to a mail that won't dissappear soon.

**Comment by moonso** [comment]
Sure that shouldn't be a problem. What email should we use? Yours @emiliaol ?

**Comment by moonso** [comment]
@patrikgrenfeldt could you fix this since you've just worked on that part of the code?

**Comment by moonso** [comment]
ping @emiliaol

**Comment by moonso** [comment]
should we use scoutbrowser@gmail.com for this?

**Comment by emiliaol** [comment]
Yes! 
Sorry for ignoring you.

**Comment by northwestwitch** [comment]
But gmail.com doesn't look professional at all

**Comment by moonso** [comment]
Ok do you have any other suggestion @northwestwitch ?

**Comment by patrikgrenfeldt** [comment]
It has been changed
