### ISSUE TITLE
coverage report missing one family member

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#777]
in this fam F0003928 (trio!)
the coverage report show the results for only for the index patient (2016-04539) and his father (2016-04541).
it is missing for the mother (2016-04541).

a bug?

Michela

**Comment by northwestwitch** [comment]
On it!

**Comment by northwestwitch** [comment]
Try now!

**Comment by 4WGH** [comment]
working ! thanks

Michela

________________________________
Från: Chiara Rasi <notifications@github.com>
Skickat: den 23 mars 2018 16:11:07
Till: Clinical-Genomics/scout
Kopia: Michela Barbaro; Author
Ämne: Re: [Clinical-Genomics/scout] coverage report missing one family member (#777)


Try now!

**Comment by northwestwitch** [comment]
Prego! Buon weekend! :)

**Comment by 4WGH** [comment]
anche a te 🎈


________________________________
Från: Chiara Rasi <notifications@github.com>
Skickat: den 23 mars 2018 17:01
Till: Clinical-Genomics/scout
Kopia: Michela Barbaro; Author
Ämne: Re: [Clinical-Genomics/scout] coverage report missing one family member (#777)


Prego! Buon weekend! :)
