### ISSUE TITLE
delete case fails on auth...

### ISSUE THREAD

**Issue by robinandeer** [Clinical-Genomics/scout#78]
I recognize this error from before... I don't know if you need to connect with MongoEngine in a special way to get admin access. I'm pretty sure I'm authenticating as an admin user.

```python
pymongo.errors.OperationFailure: command SON([('listDatabases', 1)]) on namespace admin.$cmd failed: not authorized on admin to execute command { listDatabases: 1 }
```

I don't know what you think about the solution to just handle a non-existent database using "try/catch"? I think it's a little strange that deleting a case should require a superuser/admin - proper authentication to the database in question should be OK, right?

**Comment by moonso** [comment]
This was a problem with permissions right?

**Comment by robinandeer** [comment]
Yep. It's when the script tries to access the list of all databases on the database server that you get the permission error.

**Comment by robinandeer** [comment]
Just skip the check whether the given database exists on the server
