### ISSUE TITLE
PanelApp again

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#784]
It's panel update season again, and we are doing a lot of comparing to PanelApp. It is maturing well, and may be time to add import to Scout. We tentatively think "level 3" aggregation is a good panel level, and important to be able to pull only "Green" reviewed gene symbols.

API instructions available [here](https://panelapp.genomicsengland.co.uk/#!Webservices).

**Comment by moonso** [comment]
Hi @dnil , I have played around with the API before and it should be fairly easy to add a functionality to scout. Perhaps we can discuss more on Friday?

**Comment by moonso** [comment]
Should we display all panels from panel app or how could this be done?

**Comment by moonso** [comment]
In PanelApp there are two indications on gene level that indicates confidence in the gene. There is `Evidence: ['Expert list', 'Expert Review Green']` and also `LevelOfConfidence: 'HighEvidence'` (examples). You mention only green genes @dnil , is it ok to instead collect only **HighEvidence** gene.
Evidence levels are:
-  HighEvidence 
-  ModerateEvidence 
-  LowEvidence 

I guess the result would be more or less the same but easier for me to parse.

**Comment by moonso** [comment]
Regarding number of panels. We could group them according to disease group, in that case we would get the following:

| Disease Group | Number of panels |
| ------------- | ---------------- |
| No group | 17 |
| Cardiovascular disorders | 16 |
| Ciliopathies | 3 |
| Dermatological disorders | 13 |
| Dysmorphic and congenital abnormality syndromes | 12 |
| Endocrine disorders | 15 |
| Gastroenterological disorders | 6 |
| Growth disorders | 2 |
| Haematological and immunological disorders | 1 |
| Haematological disorders | 1 |
| Hearing and ear disorders | 4 |
| Infectious diseases | 1 |
| Metabolic disorders | 9 |
| Neurology and neurodevelopmental disorders | 35 |
| Ophthalmological disorders | 8 |
| Renal and urinary tract disorders | 10 |
| Respiratory disorders | 3 |
| Rheumatological disorders | 3 |
| Skeletal disorders | 9 |
| Tumour syndromes | 14 |
| Ultra-rare disorders | 2 |

Those numbers are more manageable, don't you think @dnil ?

**Comment by moonso** [comment]
Otherwise I don't really have any suggestion for how to group them

**Comment by moonso** [comment]
be able to cherry pick panels (panelApp or local custom ones) into own aggregate panels/panel groups - much like the old lists and panels.

This is how I thought this will be used. Clinicians choose among these panels and then a aggregated panel is constructed, just like we do today so the support is already there.

I don't know about level 2 and levet 3, when I parse the panels it Is disease group and disease subgroup. If we look at sub groups there are a huge number of them (83).

**Comment by dnil** [comment]
E.g. the NMDs. To replace the current list, I could use 20 PanelApp panels. They are all from the same group (level 2) - but I don't want all 38 panels from that group. They are from several different subgroups (level 3), but again not the full subgroups either. I can accomplish this *once* using the current PR - taking great care to pick the right 20. That is a good step forward. But, tomorrow I will have a new patient with the same somewhat imprecise indication, so would want to store the new set.

I could get a panel set grouped for orders in the order portal (but involving manual intervention), or I could dump gene symbols from the sub panels, merge them as text and upload as a new panel. But it would be nice to just check the component panels once and create a new one for reuse.

**Comment by dnil** [comment]
Oh, and when you are at PanelApp: have you seen their "region" and "STR" type entries? Really nice: we should mirror that: its just what we need for the new STR view, and for region filtering SVs in e.g. leukaemia.

**Comment by moonso** [comment]
Ok there is, as always, a lot of suggestions here 😅 . Let's start with something fairly easy that works.

>E.g. the NMDs. To replace the current list, I could use 20 PanelApp panels. They are all from the same group (level 2) - but I don't want all 38 panels from that group. They are from several different subgroups (level 3), but again not the full subgroups either. I can accomplish this once using the current PR - taking great care to pick the right 20. That is a good step forward. But, tomorrow I will have a new patient with the same somewhat imprecise indication, so would want to store the new set.

The problem that I can see with this one is that if you change your mind and remove 2 small panels and add another one, what do you have then? There are numerous ways this could get complicated. Shouldn't we just start with grouping them like they have done to begin with and see how that works in clinical practice?
