### ISSUE TITLE
only E! transcript for a variant when it is on a NM_ transcript

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#785]
https://scout.scilifelab.se/cust003/18045/063a5d00d6f7850a5bb1cfcd132f82f3

the variant is on this transcript (NM_006086) when I follow the UCSC link in Scout but the NM number  doesn't come in scout
 a simple bug ?

**Comment by moonso** [comment]
Hi @4WGH , the transcript NM_006086 only exists in build 38 in the ensembl database. This is why ot does not show up here.

**Comment by 4WGH** [comment]
thanks

________________________________
Från: Måns Magnusson <notifications@github.com>
Skickat: den 11 april 2018 14:32:46
Till: Clinical-Genomics/scout
Kopia: Michela Barbaro; Mention
Ämne: Re: [Clinical-Genomics/scout] only E! transcript for a variant when it is on a NM_ transcript (#785)


Hi @4WGH<https://github.com/4WGH> , the transcript NM_006086 only exists in build 38 in the ensembl database. This is why ot does not show up here.
