### ISSUE TITLE
Polyphen missing for most cases?

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#786]
We seem to be missing polyphen calls for most cases. If this is intended, perhaps time to drop that line from the interface, otw time to troubleshoot! VEP, loading, ...?

**Comment by dnil** [comment]
Tentatively not a scout problem: plenty of missing polyphen annotations in VCFs, and at least in dev version, polyphen loads ok for a variant.

**Comment by henrikstranneheim** [comment]
It is an old problem with the VEP cache (not related to MIP - actually we pointed it out to them :), it is been around a while and have been fixed now by VEP. It will be present again with MIP v6.0.0.
