### ISSUE TITLE
Nucleotide repeat expansion (STR) view

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#787]
ExpansionHunter is almost ready in MIP (see eg https://github.com/Clinical-Genomics/MIP/issues/252) so soon time to add a view for STR VCFs. Potentially ranked (https://github.com/moonso/genmod/issues/84), but as long as we stay with known clinically relevant, they will fit on a page in list view anyway. 

- [x] load STR VCF
- [x] STR variants list view
- [x] STR variant view

**Comment by henrikstranneheim** [comment]
Yeah, we are practically done (just merged) thx to @jemten . We have now put them in the SV vcf with no special treatment in the rank model. They are so few that it seems unnecessary, what do you think? We were think that these could be detected in the loading phase and added to a separate collection for display in the STR views. Let's discuss the best approach @dnil @moonso .

**Comment by dnil** [comment]
If I could get access to an environment/sample files from a test case where this has been run, I could give making a draft page a go? Sounds like much fun! Otherwise, perhaps an "extreme programming" style paired session would be a good way forward? I could guide someone who has access to a suitable env?

**Comment by moonso** [comment]
Could you provide that @henrikstranneheim ?

**Comment by henrikstranneheim** [comment]
Expansion hunter is now a seperate file (one per family).
https://github.com/Clinical-Genomics/MIP/issues/252

Recorded in qc_sampleinfo.yaml:
```
[FAMILY_ID]:
  expansionhunter:
    Path: [path/file.vcf]
```
