### ISSUE TITLE
Evaluate other Decision Support Tools

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/scout#789]
https://amelie.stanford.edu/

https://www.biorxiv.org/content/early/2017/08/02/171322

**Comment by moonso** [comment]
Who is on this one? It does not necessarily have to be a scout person. What do you think @henrikstranneheim ?
I'm converting this to an larger issue where we can gather information about similar tools.

**Comment by moonso** [comment]
# AMELIE
## Resources
- https://amelie.stanford.edu/
- https://www.biorxiv.org/content/early/2017/08/02/171322
## Comments
any comments...

# Other tool
## Comments
More comments...

**Comment by dnil** [comment]
Perhaps this was not so apt for the git anyway? I'll close it, but very feel free to reopen / move to projects if you disagree!
