### ISSUE TITLE
Add ranking ranges to Rank score results

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#791]
Suggestion from @KickiLagerstedt: 
At the variant level, Rank score results table, it would be better to know where the tank score numbers lay. For instance: Splicing: 3 (out of?), Consequence: 5 (range?). it would help to understand the weight that the scoring has on the ranking sum.

**Comment by moonso** [comment]
Sure this is possible but then we need a way to transfer the rank models into scout so I would not label it `Easy`

**Comment by dnil** [comment]
I think we are about to get/partly have that functionality; see  #494?

**Comment by moonso** [comment]
This will be solved when the ranking module gets tightly coupled to Scout. I'm slowly working on it.

**Comment by dnil** [comment]
Well done! Perhaps change the range dash to e.g. an ellipsis ... or something like < x < to make the -12 - 4 a bit easier to parse? 😊

**Comment by dnil** [comment]
Yes, like on a row below/above the values perhaps? I like the fat vs plain.

**Comment by fc-io** [comment]
![image](https://user-images.githubusercontent.com/757478/149571534-8b7ede5c-7be3-48ba-af19-a9396d0b1ea3.png)

🤔

**Comment by fc-io** [comment]
any favorites? or new suggestions?

**Comment by henrikstranneheim** [comment]
I vote for the rank strikes back
