### ISSUE TITLE
Visa alla varianter i mtDNA i Scout

### ISSUE THREAD

**Issue by 1ctw** [Clinical-Genomics/scout#792]
Enligt tidigare diskussion med Henrik och Anders önskar vi att alla varianter i mtDNA (m.1 till m.16569) ska presenteras i Scout. Anders har i testfall tagit fram alla varianter, d.v.s. även de som saknar transkript. 

Se även nästa issue som jag kommer skapa angående mtDNA, där vi önskar möjlighet att ta ut en rapport på alla varianter i mtDNA.

**Comment by dnil** [comment]
any chances of getting some annotation along with that? Eg ClinVar or some such source indicating previously known pathogenic positions for us that do not know them by heart? 😊

**Comment by 1ctw** [comment]
Vissa mtDNA varianter finns i ClinVar men det lägger vi ingen vikt vid i vår bedömning, då det sällan stämmer. Vi behöver fortsättningsvis göra en manuell bedömning av alla varianter. Det verktyg vi har är Mitomap.org. Där finns en del varianter som har status "Confirmed", som vi räknar som säkert patogena, men även en stor mängd varianter som har status "Reported", som oftast slutar i en tolkning som "Normalvariant" eller möjligtvis "Oklar" då inga experimentella studier finns. Dessa hamnar ofta som "Pathogenic" i ClinVar.

Vi gör en manuell bedömning av det som finns rapporterat i Mitomap samt tar hänsyn till frekvensen som rapporterats i Mitomap, den lokala databasen i Scout samt frekvensen i vår tidigare sammanställda databas av alla varianter som påvisats i mtDNA på CMMS vid sangersekvensering sedan 2005.

**Comment by 1ctw** [comment]
Detta är exempel på utdrag från Mitomap. Nu tog jag ut dem i .pdf format men de går att få som .csv eller .xls m.fl.

Den information som finns här är alltså vilken status den har i Mitomap och vilken "GB frequency" den har. Den visar också om tidigare påvisade fall har varit i heteroplasmi eller homoplasmi. För varianter i mRNA visar den också en kolumn för hur prediktionsverktyget "MitoTIP" har bedömt varianten. 

Denna information uppdateras ganska ofta på Mitomap tror jag. Vad jag kan se är informationen i dessa båda filer från 2 mars respektive 17 mars 2018.

Om ni skulle lägga in sådan information i Scout, är det då möjligt med direkt uppdatering från Mitomap eller blir det statisk information från filer?

[MutationsRNA lt MITOMAP lt Foswiki.pdf](https://github.com/Clinical-Genomics/scout/files/1973681/MutationsRNA.lt.MITOMAP.lt.Foswiki.pdf)
[MutationsCodingControl lt MITOMAP lt Foswiki.pdf](https://github.com/Clinical-Genomics/scout/files/1973682/MutationsCodingControl.lt.MITOMAP.lt.Foswiki.pdf)

**Comment by moonso** [comment]
Hi we could have a look on if it is possible to add information from MITOMAP in Scout.
For now this issue will be closed. All variants from MT is uploaded to scout(when the new version is installed on rasta.
