### ISSUE TITLE
mtDNA variant report

### ISSUE THREAD

**Issue by 1ctw** [Clinical-Genomics/scout#793]
Enligt överenskommelse på ett möte 2018-03-29 mellan Nicole och Chiara skapar jag nu en issue för önskemålet att få ut en rapport med mtDNA-varianter från Scout.

Bifogar en excelfil med som visar vilka delar vi behöver få ut i rapporten.

Vi önskar en rapport i excelformat.
Titel på rapporten ska innehålla "Sample name" från Scout.
Icke-kodande delar får bli tomma i kolumnen för "Gene".
Icke-proteinkodande gener får bli tomma i kolumnen för "HGVS Description".
I kolumnen "HGVS Description" ska det bara vara p.
Det ska vara en rapport per prov även om det är en trio som körts.

[Report from Scout of variants in mtDNA.xlsx](https://github.com/Clinical-Genomics/scout/files/1973540/Report.from.Scout.of.variants.in.mtDNA.xlsx)

**Comment by northwestwitch** [comment]
AD Reference and AD Alternative is the number of reads with with either the reference of the alternative allele?

**Comment by 1ctw** [comment]
I mean the part shown under GT call in Scout, number of reads of Reference or Alternative allele. From this we can quantify the level of heteroplasmy of a heteroplasmic mutation.

![bild](https://user-images.githubusercontent.com/15033593/39690317-edf00a98-51d9-11e8-95e9-aefd0616bacf.png)

I will get back to you regarding your first question after discussion with Nicole. I will meet her after lunch today.

**Comment by 1ctw** [comment]
Please also see my other issue #792. We will need all variants in mtDNA to be loaded in Scout to get a report with all information about mtDNA.

**Comment by northwestwitch** [comment]
Ok, thanks for the explanation! When we had that meeting on the 2018-03-29 I remember I was told that all mtDNA variants are already loaded into scout now, so that would not be an issue!

**Comment by 1ctw** [comment]
Sorry but that is an issue! Nicole had missed that they are not. We have got all variants in some test cases manually from Anders but they are not in Scout. The variants in the D-loop region of mtDNA are missing in Scout. The D-loop region contains essential transcription and replications elements that could be of importance, but this part does not have transcripts and are not picked up.

The missing variants are for sure in the regions m.1-576 and m.16024-16569 (D-loop parts).

Probably variants in the small parts of mtDNA which are non-coding also are missing, for example m.7515-7517, m.8270-8294 or other small parts, but that is harder for me to see.

That is why I wish all variants from m.1 to m.16569 to be loaded, so that we can make our own evalution of the importance of the variants in mtDNA. 

The attached table shows a case which I got manually from Anders, which contains variants in the D-loop.

[mtDNA_Varianter_SaknasiScout.docx](https://github.com/Clinical-Genomics/scout/files/1979065/mtDNA_Varianter_SaknasiScout.docx)

**Comment by northwestwitch** [comment]
Ok, I was sure that the whole MT contig was uploaded to scout. @moonso are we excluding regions from this chromosome for some reason?

**Comment by 1ctw** [comment]
Now I have mentioned your first question to Nicole. CMMS has at the moment no wish to export all variants from chromosomal regions except mtDNA.

If you feel it is necessary we could have a meeting next week to explain exactly what we want in the export and why we need it?

**Comment by northwestwitch** [comment]
Hi again, the idea of exporting variants from custom regions was entirely mine so I don't know if there is an actual need for it. I guess I have to discuss about it with my colleagues and see if it could be useful for other groups. I reasoned that it would have been convenient to have a general export since to export variants mapping to the mitochondria or other chromosomes would require the same code.. Let me talk to my colleagues and I'll get back to you!

**Comment by henrikstranneheim** [comment]
The entire MT contig is analysed regardless of transcript info and I also think that Scout should load all variants regardless of transcript info. However, If you are in the clinical part the region most probably have to be part of a gene panel. If the D-loop is not included in a gene panel it will not be shown (my guess). @moonso Can you confirm this!

**Comment by moonso** [comment]
Hi, we have implemented that all variants from MT should be loaded. Just like it is with many other problems we have solved, this is not working since the code on the server has not been updated in a long time. Clinical Genomics is working hard on solving that at the moment. As soon as the new version is deployed all mt variants will be loaded.

Regarding the report I think this should be a small expansion to #800 , maybe you can have this in mind while implementing @northwestwitch ?

**Comment by northwestwitch** [comment]
@moonso we can discuss about it but personally I don't think the general case report and the MT variants should go together.
First reason is that not all users that want to generate a case report would like to see the MT variants (or general variants from genomic coordinates) in it. I think the idea of the case report is to show phenotype-related data and ONLY the variants of interest (marked in any way or commented or classified). If you show all the MT ones it becomes a huge report where most of the variants are not of interest.

Second reason is that they specifically want an excel sheet of the MT variants. The case report is an HTML page that can be exported in an PDF. It's not something you are supposed to work extensively afterwards.
I suggest we put this other report somewhere else..

**Comment by moonso** [comment]
Hi @northwestwitch , I totally agree😃 Just thought that you might be able to reuse some code from #800 so when implementing that you could have this in mind.

**Comment by 1ctw** [comment]
I agree that mtDNA report should be something else than the general case report. The mtDNA report needs specific information in a special format to be able to be imported in our LIMS.

Do I understand you right @moonso:
Will we get all variants in mtDNA (even the ones in D-loop) in the next version of Scout, even in the clinical part? What is the time plan for this?
Can we today be 100% sure that all variants connected to transcripts in mtDNA are presented in Scout, and not ranked down so much that they are not loaded? For mtDNA we want to do our own evaluation of all variants.

**Comment by moonso** [comment]
@1ctw All variants with chromosome name 'MT' will be loaded, regardless if it is clinical or research variants, regardless of rank score. This will work after we update scout.

**Comment by moonso** [comment]
Fixed in #926

**Comment by 1ctw** [comment]
Finally I have had time to check the function of ”The filter and export” function that we first of all want to use for export of mtDNA variants from Scout.

In my first comment May 4, 2018, I wrote a specification of our wishes for the report, see points below. The report must present everything we need to import to our LIS in the right format. I again attach my example .xls file from then.
[Report from Scout of variants in mtDNA.xlsx](https://github.com/Clinical-Genomics/scout/files/2562096/Report.from.Scout.of.variants.in.mtDNA.xlsx)

•	We wish a report in excel format 
The report is now a .csv file which is openable in Excel but there is some extra work to make it useable for us (to change from comma separated to column based file inside excel).

•	The title of the report should include “Sample name” from Scout
The title of the report is now “Case name” in Scout which is not possible since the data must be presented per Sample and not per Case. The report is only important for the affected individual in the case, so it is not needed to include the parents as it is done now.

•	Non-coding parts will be empty in column “Gene”
The non-coding parts seem still to be missing in Scout. As I wrote in my comment May 7, 2018 the variants in the D-loop region are missing. There are no variants presented in regions m.1-576 and m.16024-16569 (D-loop parts). Probably not other non-coding variants in m.7515-7517, m.8270-8294 or other small parts. I have still only seen them in the cases in which I got data manually from Anders. 

@henrikstranneheim and @moonso you seem to have different opinions about these non-coding parts. If there is a need to somehow change the gene panel to include the D-loop we will have to do that somehow. But according to your comment @moonso Jun 4, 2018 it should not be necessary. It should according to you work after updating Scout, but apparently it is not. @monsoo you also mention May 30, 2018 in #792 this will happen when “when the new version is installed on rasta”. Is it?

•	Non-protein coding genes will be empty in column for “HGVS description”.
The non-protein coding genes have information in the “HGVS description” field that is not relevant for us (for example n.105C>T). It is better this column is empty as we said from the beginning.

•	In column “HGVS description” only p. should be presented
I column “HGVS description” p. is not presented at all, only c. We do normally not use c. for mtDNA. We present variants on m. level and then add p. level for the protein coding genes.

•	There will have to be one report per sample even if it has been run as a trio.
Now one report for the Case is created, which means the variants from the father are mixed with variants from the patient. Since mtDNA is maternally inherited those variants are not relevant at all for us. We only need a report for the affected individual in a Case.

I will do another issue for mtDNA also. They are partly connected. If you want to merge them it is ok of course.

**Comment by northwestwitch** [comment]
Hello! We should discuss about this during the next user meeting. I tried to make a report that is usable by any scout user but I see that what you need is something  a bit more customized and ready to work with the software at your facility (and probably not so useful for other users?).

I'm not saying this can't be done but it would require several days of work and we should coordinate it a bit. An option would be to deliver the MT analysis that you require as specific files when we deliver the sequencing results.

Regarding the other points we'll take  a look ASAP!

**Comment by 1ctw** [comment]
Thanks Chiara! Good to discuss at next user meeting and maybe good to deliver the MT analysis report as specific files. The file we need is not usable for anytning else than for mtDNA I guess.

**Comment by moonso** [comment]
I might not have been clear enough here. All variants that exists in the VCF are loaded from MT. If the variants is not in the VCF they will not be uploaded. I can not answer if variants from the D-loop are in the selected VCF. We should ask @henrikstranneheim about that

**Comment by 1ctw** [comment]
Yes, if the variant hits multiple genes I think that will be the best solution.

There will not be multiple transcripts of genes encoded from mtDNA, so that will not be a problem as far as I understand.

**Comment by northwestwitch** [comment]
Ok! I've done some developing and there is a demo of this functionality on the test server of scout:

https://scout-stage.scilifelab.se

You could give it a try. You can download the excel reports by clicking on the new button on the side panel at the case level:
![image](https://user-images.githubusercontent.com/28093618/49019537-6fe92300-f18e-11e8-8d10-0a2ceb4b83b3.png)

Let me know if it's OK or anything is missing!

**Comment by northwestwitch** [comment]
Woa I didn't expect the preview to be so huge! :)

**Comment by moonso** [comment]
Great work @northwestwitch ! I'm closing this since the branch is merged. Lets create new issues in the future if there are other problems/requests with the MT report

**Comment by 1ctw** [comment]
Thanks Chiara! 

I know finally had some time to check the report. It looks great! The only thing is that silent variants are presented strange at protein level in the report. Instead of for example p.Gly203= it is prestented as p.Gly203%3D. 

I can not check that the column "Gene" gets empty in those cases where the variant is outside a gene, since we don´t get those variants in Scout yet. Issue #1070 is still open. and I guess someone is working on that issue, Hopefully it will be presented ok when this is solved.

Another thing would be the name of the button for the report in Scout. "mtDNA report" would be better than "Mitochondrial report".

**Comment by northwestwitch** [comment]
@1ctw nice! And thanks @henrikstranneheim, the weird protein symbol is an easy fix, and I'll change the code today so we can have it right in the next scout release. 
I also like the suggestion to rename the button to mtDNA report, I'll change this as well! :)

**Comment by northwestwitch** [comment]
This should be up and running in the next release  so I'm closing this issue.
