### ISSUE TITLE
no access to SCOut _ PRIO PLEASE!!!!!

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#795]
this the message:

*****
Anslutningen avbröts

Servern på scout.scilifelab.se svarar inte.

    Webbplatsen kan tillfälligt vara nere eller upptagen. Försök igen om en stund.
    Om du inte kan öppna sidor, kontrollera datorns nätverksanslutning.
    Om datorn eller nätverket skyddas av en brandvägg eller proxy, kontrollera att Firefox har tillstånd att ansluta till webben.
******

I would appreciate a fast feedback on the situation as we have a WGS meeting today at 12:00

**Comment by northwestwitch** [comment]
The problem is solved now so I'm closing the issue. Sorry for the inconvenience!
