### ISSUE TITLE
migrate cases

### ISSUE THREAD

**Issue by ingkebil** [Clinical-Genomics/scout#797]
When a case from 'scout archive' is rerun, all comments from that case should be migrated to the scout in production. This used to be achieved with `migrate-cases.sh` which is now defunct.

Is this functionality still needed?

**Comment by northwestwitch** [comment]
I'm sure, but we could handle the migration in some other way, directly at the moment of the upload of the new variants perhaps. Let's discuss about it tomorrow.

**Comment by moonso** [comment]
https://github.com/Clinical-Genomics/scout/blob/master/scripts/transfer-archive.py
