### ISSUE TITLE
Display absolute dates for latest upload in cases list

### ISSUE THREAD

**Issue by robinandeer** [Clinical-Genomics/scout#80]
This is easier to interpret

**Comment by robinandeer** [comment]
What level of detail is needed? Just the date or some kind of time included?

**Comment by henrikstranneheim** [comment]
Date should be fine.

On 21 May 2015, at 10:02, Robin Andeer <notifications@github.com> wrote:

> What level of detail is needed? Just the date or some kind of time included?
> 
> —
> Reply to this email directly or view it on GitHub.
> 

Henrik Stranneheim Ph.D.
Department of Molecular Medicine and Surgery
Karolinska Institute
Science for Life Laboratory


E-mail: henrik.stranneheim@scilifelab.se
Visiting address: 
Science for Life Laboratories - SciLifeLab
Gamma building
Tomtebodavägen 23A
Delivery address:
Science for Life Laboratories - SciLifeLab
Gamma building
Tomtebodavägen 23B
171 65 Solna
