### ISSUE TITLE
Delivery report?

### ISSUE THREAD

**Issue by KickiLagerstedt** [Clinical-Genomics/scout#805]
Can not find this report any more - has it been removed by accident of by choice?

// Kicki

**Comment by northwestwitch** [comment]
Hi! We made some changes in the code and the delivery report creation is one of the things we are still working on. For the time being delivery reports are not created automatically ( we will reintroduce the functionality soon ). If you need reports for some cases we can create them manually. Lets us know which cases you are interested in. 
Sorry for the inconvenience!

**Comment by moonso** [comment]
Ok so can we close this for now then?

**Comment by northwestwitch** [comment]
I guess so
