### ISSUE TITLE
Persist variants query in variant view

### ISSUE THREAD

**Issue by robinandeer** [Clinical-Genomics/scout#81]
- [ ] Communicate to users

EDIT: updated goals for "feature"

**Comment by moonso** [comment]
Do you have an idea for how to solve this one?

**Comment by robinandeer** [comment]
Well, I'll think about it a little and decide if it's possible to include in the next release

**Comment by robinandeer** [comment]
This isn't usually handled in these kinds of applications and will add a lot of complexity compared to the usefulness.

We'll communicate to the users what the actual functionality is and still keep the links to quickly navigate in the whole list of variants.

To move between filtered variants, users need to use the browser back button to go back and forth from the variants list.
