### ISSUE TITLE
Fix scout cli to collect OMIM key from conf file

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#814]
So you don't have to type --api-key all the time maybe? At least check if the user doesn't provide any key than it checks into the conf file

**Comment by moonso** [comment]
That functionality is already in place. If you run with `scout --config scout_config.yaml update genes` for example it will collect the omim api key from there if there is a line in the yaml file like:
```yaml
---
omim_api_key:  lasjfghalskjghlkjfg
```

**Comment by northwestwitch** [comment]
Ah ok, sorry, I didn't know that!
