### ISSUE TITLE
Handle incorrect OMIM phenotype entries

### ISSUE THREAD

**Issue by robinandeer** [Clinical-Genomics/scout#82]
We've had a few issues with weird OMIM phenotype entries lately. The same line is affected in ``get_genes.py``. See below.

It might be OK to quit the import but we should be defensive and log a more informative error/exception.

It might also be worth discussing weather we should try to do a rollback and remove already uploaded if the upload fails for some reason?

```python
import logging
logger = logging.getLogger()

# ...

try:
    phenotype_id = int(splitted_record[
except ValueError:
    logger.warning("Couldn't create phenotype model: %s", gene_annotation)
    continue
```

**Comment by moonso** [comment]
Yes you are right about the rollback..
Hmm maybe we should accept this and just log warnings?

**Comment by robinandeer** [comment]
Maybe, but it's more of academic reasons since @ingkebil has implemented a fix to make sure it doesn't happen in the gene lists anymore

I did notice a noticeable slowdown of the loading when I put this block in there though...

**Comment by moonso** [comment]
Is there a decision on this one? Should scout upload fail?

**Comment by robinandeer** [comment]
For this particular issue I think we can just exclude the problematic annotations

For other, unexpected, issues I think it would be nice to develop a rollback feature :+1:

**Comment by moonso** [comment]
Ok let's handle it that way for now.
