### ISSUE TITLE
Provide family specific default filenames for generated pdfs

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#821]
If a user downloads more than one a mixup risk ensues. Better to suggest naming according to family / sample name in addition to covereage, delivery, analysis etc.

**Comment by northwestwitch** [comment]
where, in the delivery report?

**Comment by dnil** [comment]
The issue with file name pollution is most pressing for all that auto-generate downloading pdfs - like the coverage report pdf. It would be nifty if the delivery report did that as well though.

**Comment by dnil** [comment]
Closed with #1037?

**Comment by northwestwitch** [comment]
This was fixed by https://github.com/Clinical-Genomics/chanjo-report/pull/2
