### ISSUE TITLE
Matching causatives from other cases

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#822]
to discuss at the user meeting:

Should we restrict this to appear for variants in affected cases? in order to avoid to see patogenic variants in unaffected parental samples?

**Comment by moonso** [comment]
Hi @4WGH , I've added it to the agenda (#826 ). 🥇

**Comment by dnil** [comment]
@northwestwitch and I think its fixable.. Lets give it a shot at low prio.

**Comment by dnil** [comment]
@moonso if you are anyway working on the observations & matching causatives code, this is a good one to deal with at the same time!
