### ISSUE TITLE
Agenda 2018-06-20

### ISSUE THREAD

**Issue by moonso** [Clinical-Genomics/scout#826]
## Fixed
- Adapts CLINVAR parsing to new format, this means CLINVAR is back:)
- Makes it possible to give a bam file that is specific for MT region. Previously it was not possible to view variants from MT since the read depth was to large
- Compound links are added when case is uploaded

## Added
- Added an analysis report page (html and PDF format) containing phenotype, gene panels and variants that are relevant to solve a case.
- Filter for spidex scores
- Filter for chromosomes
- All HPO terms are now added and fetched from the correct source (github.com/obophenotype/human-phenotype-ontology/blob/master/hp.obo)
- HPO terms will now be displayed in more intelligent way when searched for
- New command scout update hpo will fetch all the latest information about hpo terms and update them
- New command scout update genes will fetch all the latest information about genes and update them
- Load all variants found on chromosome MT
- Created a Clinvar submission tool, to speed up Clinvar submission of SNVs and SVs
- It is now possible to remove sanger order
- Dismissing variants
- Panel history

## Discussions
- Matching causatives from other cases. Should we restrict for variants to appear in affected only?

We will wait and see if this is a big problem.

- Sharing of cases between different institutes. Who should share the cases, CG or the owner (clinic) of the case?

We should be careful about who can share cases. We can add a role for some people that can share cases. Each institute can share with a limited number of institutes.

- Mosaicism tag button (#377 )

**Comment by dnil** [comment]
Also added 
- Dismissing variants
- Panel history

**Comment by 4WGH** [comment]
see a comment at #377 with suggestion ;)
