### ISSUE TITLE
SCOUT-STAGE: 502 bad gateway when trying to access Chanjo report for some gene panels

### ISSUE THREAD

**Issue by emiliaol** [Clinical-Genomics/scout#829]
Trying to access the Coverage report for certain gene panels from the following case returns a 502 bad gateway error. The log file is attached.
[scout.log](https://github.com/Clinical-Genomics/scout/files/2097808/scout.log)

Some gene panels are OK to open. Examples below.

**case:** https://scout-stage.scilifelab.se/cust000/15035-validation

**Panels with 502 error**: OMIM (auto), PID Candidates, ID
**Panels without 502 error**: Primary Immune Deficiency, Inborn Errors of Metabolism, Mitochondrial nuclear

@moonso, @northwestwitch is this a bug? Needs a fix before validation in that case.

**Comment by northwestwitch** [comment]
The PDF version works tho!

**Comment by emiliaol** [comment]
Alright, but how come it works in production right now for those gene panels? More info being sent in v4?

**Comment by ingkebil** [comment]
There was a configuration error for scout-stage CLI, not for the UI.

**Comment by ingkebil** [comment]
The actual error from the nginx error.log is:
```2018/06/13 21:48:28 [error] 908#908: *186402 upstream sent too big header while reading response header from upstream, client: 130.229.48.10, server: scout-stage.scilifelab.se, request: "POST /reports/report?sample_id=ADM997A4&sample_id=ADM997A2&sample_id=ADM997A3&panel_name=OMIM-AUTO+%281.1%29&level=10 HTTP/1.1", upstream: "https://130.237.80.53:7073/reports/report?sample_id=ADM997A4&sample_id=ADM997A2&sample_id=ADM997A3&panel_name=OMIM-AUTO+%281.1%29&level=10", host: "scout-stage.scilifelab.se", referrer: "https://scout-stage.scilifelab.se/panels/58d141c70aa1e275b62cc970?case_id=usablemarten&institute_id=cust000"
```

**Comment by ingkebil** [comment]
Fixed it by increasing the proxy_buffer_size of nginx:

```
  proxy_buffer_size   128k;
  proxy_buffers   4 256k;
  proxy_busy_buffers_size   256k;
```
