### ISSUE TITLE
SCOUT-STAGE: lower case to upper case conversion for filtering of HGNC symbol does not work

### ISSUE THREAD

**Issue by emiliaol** [Clinical-Genomics/scout#834]
Searching for snc2a in the HGNC Symbols/Ids field in Filters gives the error:
```HGNC symbol not found: scn2a```

Expected behaviour:
When entering a HGNC symbol in lower case this should be automatically converted to upper case in the search. The search returns the results for SCN2A

**Comment by moonso** [comment]
The search function should be case sensitive
