### ISSUE TITLE
SCOUT-STAGE: 502 bad gateway on the Clinvar sumission page when pressing `Generate clinvar submission form`

### ISSUE THREAD

**Issue by emiliaol** [Clinical-Genomics/scout#837]
Issue occurred here: https://scout-stage.scilifelab.se/cust000/15035-validation/23ee9c72b1aa788cbbe4c234fc25f88d/clinvar

Selected `Submit all pinned variants for this case` and checked `Submit case data for this variant`. Then pressed the create form button with a 502 bad gateway error as a result.

@moonso @northwestwitch is this something we can fix before the validation?

**Comment by ingkebil** [comment]
Works for me. Fixed together with #829.

From the logs:
```
2018/06/13 17:16:11 [error] 908#908: *184989 upstream sent too big header while reading response header from upstream, client: 130.229.48.182, server: scout-stage.scilifelab.se, request: "POST /cust000/15035-validation/23ee9c72b1aa788cbbe4c234fc25f88d/clinvar HTTP/1.1", upstream: "https://130.237.80.53:7073/cust000/15035-validation/23ee9c72b1aa788cbbe4c234fc25f88d/clinvar", host: "scout-stage.scilifelab.se", referrer: "https://scout-stage.scilifelab.se/cust000/15035-validation/23ee9c72b1aa788cbbe4c234fc25f88d/clinvar"
```
