### ISSUE TITLE
SCOUT-STAGE: information about variant caller missing from SV genotype table?

### ISSUE THREAD

**Issue by emiliaol** [Clinical-Genomics/scout#838]
Example: https://scout-stage.scilifelab.se/cust000/15035-validation/sv/variants/04fa42a549a0d9358865a4abd2bffc29

Under the genotype and allele table I was expecting badges telling me which caller called the variant. Missing or not implemented?
@moonso and @northwestwitch

**Comment by northwestwitch** [comment]
I think this might be a feature you find only in the recent runned samples: for instance in this one there is a reference to Manta : https://scout-stage.scilifelab.se/cust003/18080/sv/variants/4e23126635b1ec0b97d89b99f2ffd4fa 

And in this one Manta and Delly: https://scout-stage.scilifelab.se/cust003/18050/sv/variants/db824d95340668980f567dc374c391cd

**Comment by moonso** [comment]
Hi, it seems like something fishy is going on here.. In the case you point to @emiliaol there are only 60 variants and all of them are `Intersection` that means that al variants where found in all callers which can not be right for SVs.
For example in the case that @northwestwitch points to there are 4241 variants but only 7 are found by all callers.

**Comment by moonso** [comment]
I think you are right @northwestwitch ! There was probable a bug in the code when those samples where uploaded but it seems to work now.
