### ISSUE TITLE
SCOUT-STAGE: ensembl link in Genes table in SV variant view links to incorrect page

### ISSUE THREAD

**Issue by emiliaol** [Clinical-Genomics/scout#839]
Example: https://scout-stage.scilifelab.se/cust000/15035-validation/sv/variants/04fa42a549a0d9358865a4abd2bffc29

Clicking the Ensemble transcript link in the Genes table just opens the variant page in an new window.

@moonso and @northwestwitch bug or intended behaviour?

**Comment by northwestwitch** [comment]
No, it was a bug, but we've fixed it. Only the scout stage is not
updated.but good that you noticed it!

**Comment by emiliaol** [comment]
Super! Then I'll just close this again :)

**Comment by ingkebil** [comment]
I've added instructions on how to update scout-stage to the scout validation checklist.

I've checked this now on scout-stage and the ensembl link oens ensembl.
