### ISSUE TITLE
Save automatically the selected options when dismissing a variant

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#846]

**Comment by moonso** [comment]
Could you elaborate on this @northwestwitch , perhaps we should have input from @dnil as well. I don't understand the issue...

**Comment by northwestwitch** [comment]
Someone wanted the possibility to automatically update the database when a dismiss option is clicked, without selecting all the desired options first and having to click save to trigger the action.

**Comment by northwestwitch** [comment]
I can do this, but it's not an urgent one

**Comment by moonso** [comment]
Wow is that really necessary? I think it works perfect atm, what do you say @dnil . We don't have to obey for every small request from the customers. Some functionality could just be in a certain way

**Comment by dnil** [comment]
I sort of see the point, but it is a usability tradeoff issue. Personally I relatively often check more than one, which would have me waiting for the first to save before checking the next - and next. Possibly quite annoying. At a low prio, we could run a little query on the db to see how many dismissed variant have only one reason, and how many have more? If everyone else is just checking one, thats fine with me..

**Comment by northwestwitch** [comment]
Ok this is a really a low priority one and I think you are right: it's very likely that one checks more checkboxes at the same time, so I close the issue for now. We can always re-open it of anyone feels like this should be changed.
