### ISSUE TITLE
scout sv view BND end coord should show target chromosome if not self

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#861]
Pertains to both SV-variant and SV-variants views. Same with cytoband.

**Comment by northwestwitch** [comment]
Could you explain it a bit more extensively, so I fix it? :)

**Comment by dnil** [comment]
BNDs sometimes have their start and end coordinates on different chromosomes. This is not well represented everywhere.

**Comment by northwestwitch** [comment]
What's BND?

**Comment by dnil** [comment]
Jargon.. Break-eNDs; the way ectopic joining of DNA is represented in the VCF 4.x standards when they don’t quite fit any of the other categories (INV,DEL,DUP). Can represent translocations, interspersed duplication (hence two different chromosomes sometimes), more complex rearrangements - or in general just a lazy variant caller that didn’t quite figure out the far apart joining was indeed caused by a deletion.

**Comment by northwestwitch** [comment]
Ah OK! I never noticed those SV with type BNV! I'll look into it!

**Comment by northwestwitch** [comment]
Open a pull request #887

**Comment by northwestwitch** [comment]
It was merged, so I'm closing this
