### ISSUE TITLE
Between institute sharing only easy within same legal unit

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#864]
Each institute defines which units they can easily share with. Other sharing by more guarded process.

**Comment by moonso** [comment]
Ok up for discussion next scout meeting

**Comment by moonso** [comment]
Each institute should have a list of institutes that are open for sharing. Think we will start there. If cases needs to be shared with other institutes we can solve that problem later.

**Comment by dnil** [comment]
Good to do together with #988!

**Comment by dnil** [comment]
Closed by #1603!
