### ISSUE TITLE
gene panel upload - replace option

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#866]
- [x] Add option to allow replacing gene panel on upload 
- [x] Multiple changes should be possible on same
- [x] UI should be clearly separated for what can be changed on edit, upload versus on creation of new panel
- [ ] Upload file should be able to have options `add`, `modify`, `replace`and `delete`

**Comment by dnil** [comment]
Partly overlaps #850

**Comment by northwestwitch** [comment]
Since I'm working on this I'll fix also the issue of the same gene saved multiple times among the pending changes when you update a panel.

**Comment by moonso** [comment]
@northwestwitch are you still working on this? In that case could you merge the issues?

**Comment by northwestwitch** [comment]
I'm not actively working on this right now. But yes, feel free to merge the issues!
