### ISSUE TITLE
Notation on gene level regarding existance of pseudogenes?

### ISSUE THREAD

**Issue by KickiLagerstedt** [Clinical-Genomics/scout#868]
Regarding some genes / some regions of genes annotation could be false positive / difficult due to the presence of duplicated region. Would it be possible to annotate this on the gene page or something like that?

For inspiration see list here
https://blueprintgenetics.com/pseudogene/

// Kicki

**Comment by dnil** [comment]
One solution would be to view a mappability score, e.g. one of 
http://rohsdb.cmb.usc.edu/GBshape/cgi-bin/hgFileUi?db=hg19&g=wgEncodeMapability

Another perhaps just to instruct chanjo / sambamba not to count reads with MAPQ == 0 towards coverage, I e value non-uniquely mapping reads as little as not existing ones.

**Comment by dnil** [comment]
..or we could provide a link to the good old seg_dup track from the Eichler lab - which appears to be exactly what BluePrint Genetics has intersected with.

**Comment by moonso** [comment]
@KickiLagerstedt @dnil Could you elaborate on this? Where would the information be to help analysis? If chanjo we should open the issue there instead...

**Comment by moonso** [comment]
Ok so please close this or make it more clear what should be done

**Comment by dnil** [comment]
How about we settle for flagging the Eichler segmental duplication regions for now: that together with the Chanjo coverage should give a decent picture? The UCSC genomicSuperDups that is. @henrikstranneheim is that annotated somewhere already, or should we try to query automatically? BluePrint settled on a static page with a list of regions, but personally I would prefer a flag on the variant page..

**Comment by henrikstranneheim** [comment]
Available in MIP 7.0 as:
VCF key in CSQ field: "genomic_superdups_frac_match". For a variant found in overlapping multiple segdups the annotation uses "&" to split each annotation record within the field.

Should be displayed at the variant level even though the information is present in each transcript in the CSQ field.

**Comment by dnil** [comment]
We will consider this solved with #1253 for now. It is not unlikely that someone will wish for aggregate lists from this feature, perhaps in combination with average (expected) mapped coverage for genes on a panel, but that may be better solved by e g Chanjo development.
