### ISSUE TITLE
Get a list of all Sanger ordered, and those evaluated or not

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#871]

**Comment by northwestwitch** [comment]
It would be useful to somehow get a list of all variants with Sanger ordered, but especially those with Sanger ordered but not yet evaluated

**Comment by dnil** [comment]
:+1: Good also for later bulk data extraction before phasing out Sanger. Also note that not all use the Confirmation order email, but do validate all causative and some pinned. Ideally those would then be marked true/false positive: will be nice to see if this happens.

**Comment by northwestwitch** [comment]
@dnil I see your point but I don't think it's a good idea to show on top of the "cases" page also all those cases that are not solved but have pinned variants (that can be potentially validated), because that would be a huge list.. But can discuss about this more!

**Comment by dnil** [comment]
Right you are! So separate view - or specifically asking for it on the cases page. And the same goes for the ongoing Sanger orders, don’t you think? It’s probably not something one would like to see first in the list anyway. Perhaps a fifth category: not quite “active” anymore, but clearly not “solved”?

**Comment by northwestwitch** [comment]
So, so far I've done this:

![image](https://user-images.githubusercontent.com/28093618/42274378-bce51610-7f8c-11e8-8b98-56c06edca316.png)

And then you click and you get this:

![image](https://user-images.githubusercontent.com/28093618/42274423-e7cb00b0-7f8c-11e8-90c9-971f6c282542.png)

We could add a collection of checkboxes on the top of the cases page were we leave it to the users to choose what they want to see. Active cases should be displayed by default and maybe some other group as well?

**Comment by moonso** [comment]
Done!
