### ISSUE TITLE
Visualize structural variants

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#879]
Some of them might be shown using IGV, but I've found this package: https://github.com/svviz/svviz . It might be worth a try! This is the link to the official paper: https://academic.oup.com/bioinformatics/article/31/24/3994/196848

Any other suggestion @dnil ?

**Comment by hassanfa** [comment]
I have added a new module to BALSAMIC to plot static snapshots of SVs using a new tool called samplot : https://github.com/ryanlayer/samplot maybe this one might of an interest for scout as well.

**Comment by dnil** [comment]
Yeah, Ive had a look at svviz and samplot before. 

While none are as good as IGV in the general case, they have many strong features for specialized cases. The bulk of the events that we will confidently interpret as causative today do fall into a limited number of specialized cases. 

IGV is still going to be much needed for interspersed duplications, inversions with a little more than the most common complications and more complex rearrangements.

I’d say samplot or svviz is a good substitute for the sv aspect of pileup.js, but IGV covers that as well as more complex cases - and the SNV role of pileup. Still, none of the above is really good at e.g. insertions.

**Comment by northwestwitch** [comment]
It's really nice plots you are  creating with samplot! Correct me if I'm wrong but you export static images with that software, right? The advantage of svviz would be that it creates interactive web pages on the fly. You have an interface that allows you to zoom in and out on the SV, like IGV. The current version has support for translocations, deletions and insertions and I think they're working on the inversions.

**Comment by northwestwitch** [comment]
So which viewer(s) would you like to have implemented in Scout for visualizing SVs?

**Comment by hassanfa** [comment]
You're right. I am using samplot for an static report, so it is quite ideal. If there are only a handful of SVs samplot is useful, otherwise it'll be troublesome to generate and store all those images.

**Comment by henrikstranneheim** [comment]
@northwestwitch Let's go for IGV, which you also have implemented so nicely.

**Comment by northwestwitch** [comment]
Someone suggested svviz2, which is actively developed: https://github.com/nspies/svviz2

**Comment by northwestwitch** [comment]
Ok, I'm closing this for now, we can always re-open it at a later moment!

**Comment by northwestwitch** [comment]
Hi! Today I've been having a nice discussion with @szilvajuhos and they use NGB (tps://github.com/epam/NGB)to visualize different tracks for each sample. 

There is a demo here: http://ngb.opensource.epam.com/catgenome/#/

Looks more advanced than IGV, and supports the same tracks (wig among them). You need to install it on your server but you can embed it into your browser window using iFrame. 

Here's some more documentation: http://ngb.opensource.epam.com/distr/latest/docs/index.html

@szilvajuhos correct me if I'm wrong but you guys are creating static files with [pathFinder](https://github.com/NBISweden/pathfindr) out of your results from Sarek. You visualize multitracks composed of bam files, snvs and indels, copy number profiles (created with Control Freec), sashimi plots with chromosomal rearrangements, all together in a single window (1 chromosome), right?

Could you attach a screenshots of the pages you showed this morning? Thanks :)

**Comment by szilvajuhos** [comment]
Hej, sorry for the late answer, yes, pathfindr makes static files _and_ CSV files in the moment. The purpose of static HTML to have a complete report that we can send around, but the CSV files and different plots can be integrated to other software. Have to find some test data to show without patient information.
