### ISSUE TITLE
New looks for Scout?

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#884]
Switching to Bootstrap 4 and playing a bit with the website colors would improve the looks of Scout.

**Comment by moonso** [comment]
It's up to you @northwestwitch , please submit a PR if you feel like it

**Comment by dnil** [comment]
Close with #1283 !

**Comment by moonso** [comment]
SOOOOOON!!

**Comment by northwestwitch** [comment]
Fixed in #1283. Closing the issue

**Comment by moonso** [comment]
Felt good 😄
