### ISSUE TITLE
Reset variant validation status to null if you change your mind?

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#886]
It looks like that after you have decided that a validation if either a true or a false positive you can't reset its status to null (not existing key in the variant document I think). I took a look at the past issues but haven't found out if this was discussed before.
Do you think it would be useful to include a validation reset option?

**Comment by moonso** [comment]
Closing this and add it to the agenda for next shout user meeting. If there is a need we can reopen. Need to do some issue cleaning 😅
