### ISSUE TITLE
SCOUT-STAGE: global variant comments are not shown globally

### ISSUE THREAD

**Issue by emiliaol** [Clinical-Genomics/scout#891]
Example: variant X_67414426_C_T_clinical has a global comment in cust002 cases that does not show up in a cust002 case.
[cust002 case 1](https://scout-stage.scilifelab.se/cust002/F0015268/5f1a00e07c8e84db619883bbc1f30a9d)
[cust002 case 2](https://scout-stage.scilifelab.se/cust002/F0015456/7f870a4f94db24ef34b14bc04edc99e7)
[cust003 case](https://scout-stage.scilifelab.se/cust003/126/4ce6af6a0d8e0849ffd438a5d86ec560)

Expected behavior: the global comment from the cust002 cases should show up in the cust003 case as well.

**Comment by northwestwitch** [comment]
I'm not really sure that this isn't the expected behavior. Could it be that:
1) when the comment is local then it is seen only for that case
2) when the comment is global then it's seen for all cases of that institute?

Because that's what you observe.

Is it so, or a global comment should be seen across institutes as well? @moonso ?

**Comment by northwestwitch** [comment]
Ok! @dnil what you describe makes a lot of sense but it doesn't seem to work like that in scout-stage. And @emiliaol you are right: it looks like they behave the same way. 
I'm not really understanding how this 2 levels comments work so I'll need to dig into the code. I'll keep you updated! Thank you both!

**Comment by northwestwitch** [comment]
I've updated scout-stage with the code from this pull request (directly from the branch, without merging into master). @emiliaol give it a try when you have time! :)

**Comment by northwestwitch** [comment]
I've removed the previous comments and re-commented the variants above, and it seems to work. However I see a problem with this GLOBAL comments visible by anybody: being private data and all, would it problematic by the GDPR point of view? Maybe we should make global comments visible only across cases from the same institute..
