### ISSUE TITLE
scout v4 cannot parse vep92 annotations.

### ISSUE THREAD

**Issue by nvteja** [Clinical-Genomics/scout#894]
Hello,
I cannot get scout v4 to parse vep92 annotations specifically CADD_Phred, gnomAD frequencies. Here is my vep92 header.

##INFO=<ID=CSQ,Number=.,Type=String,Description="Consequence annotations from Ensembl VEP. Format: Allele|Consequence|IMPACT|SYMBOL|Gene|Feature_type|Feature|BIOTYPE|EXON|INTRON|HGVSc|HGVSp|cDNA_position|CDS_position|Protein_position|Amino_acids|Codons|Existing_variation|DISTANCE|STRAND|FLAGS|VARIANT_CLASS|SYMBOL_SOURCE|HGNC_ID|CANONICAL|TSL|APPRIS|CCDS|ENSP|SWISSPROT|TREMBL|UNIPARC|REFSEQ_MATCH|SOURCE|GIVEN_REF|USED_REF|BAM_EDIT|GENE_PHENO|SIFT|PolyPhen|DOMAINS|miRNA|HGVS_OFFSET|AF|AFR_AF|AMR_AF|EAS_AF|EUR_AF|SAS_AF|AA_AF|EA_AF|gnomAD_AF|gnomAD_AFR_AF|gnomAD_AMR_AF|gnomAD_ASJ_AF|gnomAD_EAS_AF|gnomAD_FIN_AF|gnomAD_NFE_AF|gnomAD_OTH_AF|gnomAD_SAS_AF|MAX_AF|MAX_AF_POPS|CLIN_SIG|SOMATIC|PHENO|PUBMED|MOTIF_NAME|MOTIF_POS|HIGH_INF_POS|MOTIF_SCORE_CHANGE|CADD_phred|FATHMM_pred|MetaSVM_pred|MutationTaster_pred|Polyphen2_HVAR_pred|SIFT_pred">

when I manually replace CADD_Phred with CADD_PHRED (just capitalize the word Phred), scout is able to load CADD properly. Also, regardless of the capitalization, I could not get gnomAD frequencies to load at all. Is this a bug or am I missing something fundamental in the way the vcf should be formatted for scout?

Thank you,
Teja.

**Comment by northwestwitch** [comment]
Hi! Scout should support the VEP annotation keys for VEP 90+ (https://www.ensembl.org/info/docs/tools/vep/vep_formats.html). Do you get any error message while loading the variants into scout or it just skips the fields?

**Comment by nvteja** [comment]
It does not give me any errors - it just skips the fields..

Teja

**Comment by moonso** [comment]
Hi @nvteja, I will try to do the parser a bit more intelligent. Could you send a minimal example file with a few variants so I can test that it works?

email: mans.magnusson@scilifelab.se or a [GitHub gist](https://gist.github.com)

Måns

**Comment by nvteja** [comment]
Just emailed the file.

Thank you,
Teja.

**Comment by nvteja** [comment]
Hello Måns,

Looks like Scout still isnt parsing/recognizing  gnomad_AF column from the VEP header. I can see CADD_Phred and 1000G frequencies however. Could you please look into it?

Thank you,
Teja

**Comment by moonso** [comment]
I'll have a look
