### ISSUE TITLE
Verification bug report

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#909]
Looking very good, but a couple of minor issues spotted:
- [ ] Rank model versions not displayed (SNV and SV)
- [ ] 15x coverage not filled in on coverage report?
- [ ] Direct links to pileup views of start and end of SVs went missing, presumably with the IGV-beta update? These are quite nifty for large variants.

And a more long term issue of the rank models  [1.20 / SV 1.2 :-)]
- [ ] Rank of in particular frameshift mutation has gotten worse. Also rank model for SVs is performing poorly with regard to the rank of pathogenic calls. We should revisit this during autumn.

**Comment by northwestwitch** [comment]
We've created 4 smaller issues from this one, thanks @dnil !
