### ISSUE TITLE
Rank of in particular frameshift mutation has gotten worse.

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#913]
Rank of in particular frameshift mutation has gotten worse. Also rank model for SVs is performing poorly with regard to the rank of pathogenic calls. We should revisit this during autumn. Fourth point of #909

**Comment by moonso** [comment]
Is this something you can fix @henrikstranneheim and @dnil ?

**Comment by northwestwitch** [comment]
If you want I could join the discussion as well, I've got experience with SVs and I remember that when I studied how the ranking was assigned for this category I noticed that yes, it could be improved.

**Comment by moonso** [comment]
This is a MIP issue, opened [here](https://github.com/Clinical-Genomics/MIP/issues/594)
