### ISSUE TITLE
Report visualisation fails on current production 4.0.0??

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#917]
Another one interaction issue, somewhere between a production issue and a potential scout bug. 

While everything looked fine on stage-scout we seem to have an issue with reports on the production version? Anyone around to check logs when @ingkebil is away? Takes a long time, so could be a timeout, but as this was fairly quick on stage I'm leaning toward something else going amiss? 

Cheers!

**Comment by northwestwitch** [comment]
Good that you noticed, I'll look into it!

**Comment by northwestwitch** [comment]
It worked! I close the issue :)
