### ISSUE TITLE
Generate pdf from gene panel

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#922]
We would like to be able to export gene panels (of a given version) to pdf, for easy retrieval and linking from answer reports. Add a weasy-pdf view for the panels?

**Comment by northwestwitch** [comment]
I'm working on this. Would you like to have the HGNC ids of the PDF report to be linked to some other external pages, like HGNC database, NCBI .., or the scout gene page?

**Comment by dnil** [comment]
Thank you! Yep, external pages is the way to go: the beneficiaries would not have scout access and HGNC/genenames, ensembl, Ncbi, Omim or panelApp should all be nice sources.

**Comment by northwestwitch** [comment]
HGNC/genenames, ensembl, Ncbi, Omim etc is all contained in the genenames archive, so for now I'll just add a link to that, then we can discuss about other useful links to include

**Comment by moonso** [comment]
Closed by #932
