### ISSUE TITLE
Have `scout update genes` perform index rebuild in the background

### ISSUE THREAD

**Issue by ingkebil** [Clinical-Genomics/scout#925]
As someone running `scout update genes` I do not want scout to be irresponsive while the index are being rebuilt.

According to https://docs.mongodb.com/manual/reference/command/createIndexes/ you can pass in the parameter `background` so the indexes get built in the background. That function translates to http://api.mongodb.com/python/current/api/pymongo/collection.html#pymongo.collection.Collection.create_indexes in python.

**Comment by moonso** [comment]
Use command `scout index` when this is deployed to rebuild indexes with `backgroud=True`
