### ISSUE TITLE
Set missing rank model and chromosome build.

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#927]
All samples runned since Sept 2017 are missing rank model and chromosome build info in mongodb. After  a cg fix all new runned samples will get these params from the cg upload by default, but the old cases will still be missing them. We should introduce these key-values in the database for these.

**Comment by northwestwitch** [comment]
@moonso I was thinking about you because you are good with the db, but we can do it together! :)

**Comment by moonso** [comment]
I wonder if it really is a problem, as long as the new samples are working. Customers could ask us for those old cases it they are really interested.
What do you think @henrikstranneheim ?

**Comment by henrikstranneheim** [comment]
@moonso Agreed, let's see if this is requested by customer first before spending time on it.

**Comment by northwestwitch** [comment]
Good, I close the issue then!
