### ISSUE TITLE
Something wrong with the compound filter???

### ISSUE THREAD

**Issue by KickiLagerstedt** [Clinical-Genomics/scout#937]
Trio analysis  - looking at one variant and then looking at compound variants - BUT when looking the variants are inherited from the SAME parent

Variant 1:
https://scout.scilifelab.se/cust002/F0015588/516541efcc88b4d0cac832448669dade
Variant 2 (from list):
https://scout.scilifelab.se/cust002/F0015588/00128c3f3bf51531f9be0338f4bde354

The list of compounds are much longer than usual....

**Comment by dnil** [comment]
O_o! For a possible clue, one of the variants is a low qual indel? The same apparently goes for at least another cis-pair. @moonso this is hardly to do with the compound loading, is it? Rather an issue to pass along to MIP?

**Comment by emmser** [comment]
![screen shot 2018-09-06 at 08 36 47](https://user-images.githubusercontent.com/659228/45139465-205b1280-b1b0-11e8-99d0-edcbe9db91ed.png)
![screen shot 2018-09-06 at 08 36 57](https://user-images.githubusercontent.com/659228/45139466-205b1280-b1b0-11e8-8ef4-900ae07b7341.png)

If we look at the genotypes it looks like the variants have been inherited from different parents, or have we missed something?

**Comment by northwestwitch** [comment]
It is. The heterozygous one has no alternative reads and the other way
around..!

**Comment by dnil** [comment]
The bam file appears to confirm the Allele Depth calls. (Although the indel appears slightly out of place in that repeat, hence the Filtered status and low GQ.)

**Comment by dnil** [comment]
What does it look like in the VCF?

**Comment by moonso** [comment]
Hi, genmod who does the genetic models looks at the genotype calls have done the correct conclusion. It seems to be a problem with the genotype calling process. The variant is filtered by all callers but (at least) one of them have called it a variant. Most probably this is a complex position with multiple alternatives. I point this to @henrikstranneheim

**Comment by henrikstranneheim** [comment]
It is unclear why mpileup assigns the GT as 0/0, for 2018-17381-02 looking at the PL it should be assigned as a 0/1 and for 2018-17380-02 it looks like it should be 0/0 and not 0/1.

I do not see anything wrong in either MIP or Scout (as they are just faitfullt relaying the info). I guess you have to decide if you want to go with the mpileup version of the GT or make an own call in judging this variant.

**Comment by moonso** [comment]
Can we close this? This problem needs to be adressed outside scout

**Comment by KickiLagerstedt** [comment]
Jepp

Skickat från min iPhone

7 sep. 2018 kl. 14:26 skrev Måns Magnusson <notifications@github.com<mailto:notifications@github.com>>:


Can we close this? This problem needs to be adressed outside scout
