### ISSUE TITLE
Update OMIM "window" in SCOUT

### ISSUE THREAD

**Issue by KickiLagerstedt** [Clinical-Genomics/scout#938]
Looking at that variant page - one phenotype is visible under OMIM
https://scout.scilifelab.se/cust002/F0015588/eccaeae31d8067363bd798edeb91f0cc

Looking in OMIM  - three phenotypes are visible
http://omim.org/entry/604392

Would be good to see all the phenotypes in the SCOUT window

**Comment by dnil** [comment]
Tricky one! If you look closely on the OMIM page you will find that all are the same, and also have merged to the same pheno number.

**Comment by KickiLagerstedt** [comment]
You mean the same Phenotype MIM number? In that case I understand.

Kärt barn har många namn??? As we say in swedish...
