### ISSUE TITLE
IGV view would be lovely

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#94]
Title says it all. ;-)

**Comment by dnil** [comment]
[macarthur-lab/igv_plotter] (https://github.com/macarthur-lab/igv_plotter)

igv_plotter - python interface to IGV that simplifies creating screenshots of BAMs, VCFs, BEDs, etc for one-off spot checking or automated / scripted image collection

What do you think?

**Comment by moonso** [comment]
Sounds lovely, thanks!!

**Comment by moonso** [comment]
We will begin to get the dynamic coverage part done first.
Then we will try to fight the IGV beast...

**Comment by dnil** [comment]
Looks rather straight-forward as long as the bam files are available to the web server for rendering. Should be easier to make them accessible there for the package to render them as html, compared to streaming them to an IGV instance on the users machine. Good luck with the beast slaying! :-)

**Comment by dnil** [comment]
And cheers to Vasilios Z for pinging me on the IGV_plotter package!

**Comment by robinandeer** [comment]
https://github.com/igvteam/igv.js/blob/master/examples/api.html

**Comment by robinandeer** [comment]
We are using pileup.js right now and are awaiting feedback if IGV is a needed feature

**Comment by northwestwitch** [comment]
Are we interested in switching directly to igv viewer of do we want to keep both pileup and IGV for a while? I was thinking that it would be smoother to do the transition if we keep pileup and ww show a beta igv viewer. Than if nobody complains for a while we just keep igv. What do you think?
