### ISSUE TITLE
coverage for gene look odd

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#947]
https://scout.scilifelab.se/reports/genes/2592?sample_id=ACC4698A11

see link in fam 18177
variant in CYP11B2
I try to get the coverage for the gene and the 15X does not appear

**Comment by northwestwitch** [comment]
Hi Michela! The coverage for this sample was probably analysed with the wrong settings (see this issue: https://github.com/Clinical-Genomics/scout/issues/912). How do we fix this @henrikstranneheim, we re-run it from a certain point of the pipeline?

**Comment by northwestwitch** [comment]
It is solved but it has been pushed into production only today. So If you need the 15X coverage for this sample I'm afraid you need to go through the usual procedure: open a ticket and ask for a re-run, sorry!

**Comment by 4WGH** [comment]
thank for the update.


I do not need the 15X for this I just reported as a general issue.


thank for the fast replay



________________________________
Från: Chiara Rasi <notifications@github.com>
Skickat: den 13 september 2018 11:17:53
Till: Clinical-Genomics/scout
Kopia: Michela Barbaro; Author
Ämne: Re: [Clinical-Genomics/scout] coverage for gene look odd (#947)


It is solved but it has been pushed into production only today. So If you need the 15X coverage for this sample I'm afraid you need to go through the usual procedure: open a ticket and ask for a re-run, sorry!

**Comment by northwestwitch** [comment]
You're welcome! :)

**Comment by northwestwitch** [comment]
I'm going to close this one
