### ISSUE TITLE
Display exon number (range) on SV variant view 

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#957]
More or less on SNVs. Can immediately carry meaning for the clinician: the common deletion of exon something in such and such gene, or the particular fusion between exon this and that in a form of leukaemia.

**Comment by dnil** [comment]
I think I'll take this as an excuse to merge the variant and sv-variant views then!

**Comment by henrikstranneheim** [comment]
@dnil Any timeplan for this one? It is one of the last issues on the CG goals. Would be nice to be able to close soon.

**Comment by dnil** [comment]
Merging was just too much for now. That will have to remain on the refactor wish-list. Quite possible, but many little things that can go wrong.
