### ISSUE TITLE
Add link to CLING. FIXED

### ISSUE THREAD

**Issue by moonso** [Clinical-Genomics/scout#96]

**Comment by robinandeer** [comment]
Just link to ClinVar page

@henrikstranneheim: we need the CLINVAR id for the variation to "deep-link", possible?

**Comment by henrikstranneheim** [comment]
One should probably be able to use: http://www.ncbi.nlm.nih.gov/clinvar/RCV000064926.2/

Using this key in the vcf:
CLNACC=RCV000064926.2

I wil add the CLNACC to the annotations collected by MIP from CLINVAR.

On 21 May 2015, at 13:40, Robin Andeer <notifications@github.com> wrote:

> Just link to ClinVar page
> 
> @henrikstranneheim: we need the CLINVAR id for the variation to "deep-link", possible?
> 
> —
> Reply to this email directly or view it on GitHub.
> 

Henrik Stranneheim Ph.D.
Department of Molecular Medicine and Surgery
Karolinska Institute
Science for Life Laboratory


E-mail: henrik.stranneheim@scilifelab.se
Visiting address: 
Science for Life Laboratories - SciLifeLab
Gamma building
Tomtebodavägen 23A
Delivery address:
Science for Life Laboratories - SciLifeLab
Gamma building
Tomtebodavägen 23B
171 65 Solna

**Comment by moonso** [comment]
Add the CLINSIG information on variant level

**Comment by robinandeer** [comment]
accesion not provided in the model @moonso

**Comment by robinandeer** [comment]
pushed a branch "add-clnsig-link" which adds the link if accession is provided

**Comment by moonso** [comment]
It is still a bit unclear how this should be handeled

**Comment by robinandeer** [comment]
Oki, I will keep that branch atomic then :+1:

**Comment by henrikstranneheim** [comment]
Let's only display patogenic clinvar variants (CLNSIG=5) and their corresponding accession. NOTE: there can be multiple patogenic annotations per variant.
