### ISSUE TITLE
Rank model shows wrong version

### ISSUE THREAD

**Issue by patrikgrenfeldt** [Clinical-Genomics/scout#961]
The rank model is a string in the case-config but is handled as a number in scout: 
E.g. In config:
'rank_model_version': '1.20'
In Scout: 
 Rank model
Version 1.2 

Steps to reproduce: 
1. start scout
2. open newly uploaded case

Expected outcome: 
Rank model
Version 1.20

Actual outcome: 
Rank model
Version 1.2

**Comment by dnil** [comment]
I had a quick look: it is actually the PyYAML parser that (correctly, according to the yaml re definition) returns this as a float. The most correct (and easiest for Scout developers :stuck_out_tongue_winking_eye:) is probably to quote it already when dumping it from CG / MIP. Would you happen to know where it is written out? @patrikgrenfeldt

**Comment by dnil** [comment]
- [ ] Issue to CG
- [ ] Check that all downstream use of semantic versions in Scout are with string type where relevant.

**Comment by patrikgrenfeldt** [comment]
If one runs the command cg upload scout --print [family_id] for any recently uploaded analysis one can see the data that is passed to scout and that it has quotations, i.e. 'rank_model_version': '1.20'. Looking at the same case in scout gives Rank model Version 1.2 This issue seems to be somewhere downstream of cg, closed the issue in cg.

**Comment by dnil** [comment]
Thanks for checking! Seems the demo files are out of date here too then, and likely a remaining float somewhere downstream. Me fix.
