### ISSUE TITLE
UCSC link goes to browser hg38 insterad of hg19  

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/scout#963]
links to UCSC in fam 18182 link to UCSC hg38 and not hg19 as it used to do
so does NOT link to the right position !

This is a major issue, as we use the link for several checks 

MichELA

**Comment by moonso** [comment]
Hi, something has went wrong when adding the genome build. I have added a fix for this.

**Comment by 4WGH** [comment]
will the fix be retroactive?

can you flag all samples affected by this?



________________________________
Från: Måns Magnusson <notifications@github.com>
Skickat: den 26 september 2018 22:18:59
Till: Clinical-Genomics/scout
Kopia: Michela Barbaro; Author
Ämne: Re: [Clinical-Genomics/scout] UCSC link goes to browser hg38 insterad of hg19 (#963)


Hi, something has went wrong when adding the genome build. I have added a fix for this.

**Comment by northwestwitch** [comment]
It's not retroactive, I'm afraid. But you should be able to identify those without the genome build because this info is missing in the side bar at the case level: 
![image](https://user-images.githubusercontent.com/28093618/46135050-9baa6400-c244-11e8-8de4-d0fb85d8a81a.png)

Am I right @moonso ??

**Comment by moonso** [comment]
Hi @northwestwitch, it should say '37' or '38'.
@4WGH This will affect all cases regardless of when they where sequenced. If genome build is not `37` or `38` (like in the picture) the wrong link is in production now.
When we update scout **ALL** cases will have the correct link

**Comment by 4WGH** [comment]
when will you update scout?
We are depending on our routine work on the link.....

This is very inconvenient for us. Can this issue get priority?

**Comment by moonso** [comment]
Hi @4WGH , we are working on it. Can get back tomorrow with info on when.
If you really want it is super easy to get to the correct build. If you right click the link and then `copy` and then paste the link in the browser it looks like: `
http://genome.ucsc.edu/cgi-bin/hgTracks?db=hg20&position=chr4:996535-996535&dgv=pack&knownGene=pack&omimGene=pack`

If you look in the beginning it says `...db=hg20...` just change that `20` to `19` and you will get to the correct place!

**Comment by 4WGH** [comment]
thank for the update!

**Comment by moonso** [comment]
Fixed now! 🍾
