### ISSUE TITLE
Adapt filter to use best fred available (exac/1000G/gnomAD)

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/scout#966]

**Comment by dnil** [comment]
Hm, this does not work well for current and older cases where gnomAD frequencies are missing?! We need a workaround until we get these values populated. As in heading, use best available for case rather?

**Comment by moonso** [comment]
Do you have any idea how to solve this @dnil ? It fails a little tricky to create different filters depending on what is annotated. My suggestion is that we consider 1000G/ExAC as deprecated, these cases can be reanalysed to get the correct information.

**Comment by dnil** [comment]
Another year has passed without this becoming a major issue. Lets close this until someone objects.
