### ISSUE TITLE
Show Change instead of Amino Acid in transcript overview

### ISSUE THREAD

**Issue by moonso** [Clinical-Genomics/scout#97]
Show cdna if no amino acid change

**Comment by robinandeer** [comment]
Does this mean I should sometimes show cDNA and other times Amino acid change?

**Comment by moonso** [comment]
Yes, everytime ther is no amino acid change (when outside exons) we should show cDNA change.
So the name of the column should be "Change" or something..

**Comment by robinandeer** [comment]
One more question - should this be on variant or transcript level?
Like determine if the variant is exonic in some transcript or *per* transcript?
Should I use the "biotype" if I do it per transcript?

**Comment by henrikstranneheim** [comment]
On transcript level, but I only for RefSeq transcripts (@Måns: Correct me if I am wrong).

How about calling the column “HGVS Description”. It is after all what we are displaying, be it on cDNA or protein level.


On 21 May 2015, at 09:49, Robin Andeer <notifications@github.com> wrote:

> One more question - should this be on variant or transcript level?
> Like determine if the variant is exonic in some transcript or per transcript?
> Should I use the "biotype" if I do it per transcript?
> 
> —
> Reply to this email directly or view it on GitHub.
> 

Henrik Stranneheim Ph.D.
Department of Molecular Medicine and Surgery
Karolinska Institute
Science for Life Laboratory


E-mail: henrik.stranneheim@scilifelab.se
Visiting address: 
Science for Life Laboratories - SciLifeLab
Gamma building
Tomtebodavägen 23A
Delivery address:
Science for Life Laboratories - SciLifeLab
Gamma building
Tomtebodavägen 23B
171 65 Solna

**Comment by moonso** [comment]
@henrikstranneheim sounds right
