### ISSUE TITLE
Update Pymongo to 3.7.1

### ISSUE THREAD

**Issue by moonso** [Clinical-Genomics/scout#971]
This might take some effort...

**Comment by ingkebil** [comment]
Will you lock it to that version or always use the latest release?

**Comment by moonso** [comment]
We can lock it, guess that will be easiest

**Comment by mikaell** [comment]
Drafted a PR here: #2102

Please have a look and come with feedback.

**Comment by dnil** [comment]
Fixed by #2152! Well done @mikaell.
