### ISSUE TITLE
Collecting refseq versions to build improved clinvar submission files

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#974]
This is not so easy, but in order to submit complete info via clinvar variant submission files we need to add  the refseq version to the submission. So far we save in Scout just the refseq code. Maybe it's easily fixable by querying some external database on the fly..

**Comment by northwestwitch** [comment]
I forgot to add that if users decide to add a refseq code (and they should, because it adds a lot to the submission) without specifying the version, then the submission is rejected until they don't add the missing field.

**Comment by henrikstranneheim** [comment]
Here is a flat file with a genbank=NM.version that one can use: ftp://ftp.ncbi.nlm.nih.gov/refseq/H_sapiens/annotation/GRCh37_latest/refseq_identifiers/GRCh37_latest_genomic.gff.gz

One could add this to the VEP annoation, and I will look into if I can include this in the MIP analysis. Other option is to add this to Scouts internal database of transcripts.

**Comment by henrikstranneheim** [comment]
MIP 7.0 now uses VEPs merged cash to add the refseq transcript version which can then be picked up by Scout in the CSQ field.
@northwestwitch There was another field required as well which scout do not have right? Was it the refseq for the entire build?

**Comment by northwestwitch** [comment]
It was just that I think, the other problem was much simpler to fix, see #901

**Comment by henrikstranneheim** [comment]
Excellent! Thx

**Comment by northwestwitch** [comment]
Thank you! :)

**Comment by henrikstranneheim** [comment]
@northwestwitch @moonso What is the status on this one? Do you need any more info from the raw data?

**Comment by northwestwitch** [comment]
> @northwestwitch @moonso What is the status on this one? Do you need any more info from the raw data?

I'm not sure, I'll check!
