### ISSUE TITLE
Analysis report; Add OMIM phenotype to variants

### ISSUE THREAD

**Issue by KickiLagerstedt** [Clinical-Genomics/scout#975]
Would appreciate if "OMIM window" 
![bild](https://user-images.githubusercontent.com/17139607/46402367-d0fcf900-c6ff-11e8-8bdf-2b140e3ace98.png)

could be included in the "variant box" for variants that are causative, pinned, ACMG classified, other manual ranked variants, other commented variants.

// :=)

**Comment by northwestwitch** [comment]
This will be quite easy. OMIM id code is currently displayed only for structural variants, but I can add some more info including the OMIM term (not only the id) for all variants.

**Comment by northwestwitch** [comment]
And the phenotype!
