### ISSUE TITLE
sv_variant page error with demo data

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/scout#977]
Hi! I'm working on something unrelated to this but I noticed that there is the following error message when trying to visualize a structural variant using the demo data:

``
 File "/Users/chiararasi/Documents/work/GITs/scout/scout/server/blueprints/variants/views.py", line 165, in sv_variant
    data = controllers.sv_variant(store, institute_id, case_name, variant_id)
  File "/Users/chiararasi/Documents/work/GITs/scout/scout/server/blueprints/variants/controllers.py", line 152, in sv_variant
    gene_obj['ensembl_link'] = ensembl_link(ensembl_id, build=build)
TypeError: 'str' object is not callable
``

This occurs while using the current master, after PR #976 (but has nothing to do with it). It does not affect the current stage.

**Comment by northwestwitch** [comment]
It's a potential bug, I've assigned you @moonso because you have been working on this specific code recently!

**Comment by moonso** [comment]
Ok I'll check the links again later today 👍

**Comment by northwestwitch** [comment]
It doesn't have to do with the fact that I'm using the demo data. I think the error is triggered when from the code is called a function that is a string instead
