### ISSUE TITLE
Report issue - coverage also in general case report

### ISSUE THREAD

**Issue by AnnHam** [Clinical-Genomics/scout#978]
1. Dismissed variant description in report does not agree with what I want to say... 

If I use "Common variation type" in the "dismiss-variant-rullgardin" - the text on the report says: "Found in a gene with much benign such (e.g. missense) variation" - Spelling(?) and is it obvious that "common variation type" means that?

AND 

"no protein function" meaning "Not likely to alter protein function - e.g. benign polyQ expansion" - why not just write "Repeat sequence" or else in the rullgardin. No protein function could also mean that the variant is not affecting the coding sequence or it might be a technical issue... 

We might need to discuss this further on a Scout user meeting. 

2. Another request for the report is that I would like to have the 20X coverage stated or the delivery report in the end of the report. 

//Anna Hammarsjö

**Comment by dnil** [comment]
1. We did discuss these extensively at a couple of meetings, but I'm to blame (😊) for the final touches. New input is welcome!

First, would you perhaps rather also have the short form of the option repeated on the report?

Then, for "common variation type": I cant see the spelling error? Please help! 😊 Please also suggest an alternative text - that would be lovely!

"No protein function". Some changes to repeats do affect the function as you well know, so I don't think that "repeat sequence" in it self is a good dismiss option. Some expansions are common benign nuisances, like the intermediate size polyQ expansions, and hence the option. We reasoned it could then be used for e.g. known benign variants in splice sites. Again, please suggest an alternative label and I can argue with you about it! 😜

We could easily add more options if you want to be able to say sth else, or say it with more precision. For the two you list I might  have selected "no protein function" or possibly "no refseq transcript" and "technical issue" respectively. For non-exonic variants not likely affecting splicing, you might consider just ignoring them and consider them not in your investigation target?

2. Yes, me like! We had that in the initial suggestion, but it was deemed technically comparatively difficult, as it is called by an external application (Chanjo).

**Comment by AnnHam** [comment]
"Found in a gene with much benign such (e.g. missense) variation"



- It's the explanation on the report I find a little bit odd (not the dismiss label)... I see what it means, but would re-phrase.



Some "dismissed options" I might just have to learn what it means for the report, but now when we start using it - I think we will find alternative labels that are more useful. Since I have done a lot of research lately I've missed the discussions for this, but when I have a better suggestion I'll get back to you 😊



________________________________
Från: Daniel Nilsson [notifications@github.com]
Skickat: den 4 oktober 2018 17:51
Till: Clinical-Genomics/scout
Kopia: Anna Hammarsjö; Author
Ämne: Re: [Clinical-Genomics/scout] Report issue (#978)


  1.  We did discuss these extensively at a couple of meetings, but I'm to blame (😊) for the final touches. New input is welcome!

First, would you perhaps rather also have the short form of the option repeated on the report?

Then, for "common variation type": I cant see the spelling error? Please help! 😊 Please also suggest an alternative text - that would be lovely!

"No protein function". Some changes to repeats do affect the function as you well know, so I don't think that "repeat sequence" in it self is a good dismiss option. Some expansions are common benign nuisances, like the intermediate size polyQ expansions, and hence the option. We reasoned it could then be used for e.g. known benign variants in splice sites. Again, please suggest an alternative label and I can argue with you about it! 😜

We could easily add more options if you want to be able to say sth else, or say it with more precision. For the two you list I might have selected "no protein function" or possibly "no refseq transcript" and "technical issue" respectively. For non-exonic variants not likely affecting splicing, you might consider just ignoring them and consider them not in your investigation target?

  1.  Yes, me like! We had that in the initial suggestion, but it was deemed technically comparatively difficult, as it is called by an external application (Chanjo).
