### ISSUE TITLE
Analysis report: Order of variants

### ISSUE THREAD

**Issue by KickiLagerstedt** [Clinical-Genomics/scout#980]
Variants that are causative, pinned, ACMG classified, other manual ranked variants, other commented variants. when in the pdf report are in a complete random (at least for me) order ie; within commented variants the list are variant rank; 36, 194, 72, 57, 71, 20, 196, 10, 11, 1, 239

https://scout.scilifelab.se/cust002/F0008261

Would it be possible to get them in variant rank order?

**Comment by northwestwitch** [comment]
Yes, that is easy!
