### ISSUE TITLE
Annotation of compunds lacking 

### ISSUE THREAD

**Issue by KickiLagerstedt** [Clinical-Genomics/scout#983]
When hoovering (?) over the list of compound variants annotation of compound variants are lacking (empty boxes) (page 2-) (I showed Daniel) but are there when I go back to repeat..
![bild](https://user-images.githubusercontent.com/17139607/46600595-e81a5d00-caea-11e8-8689-587a407815a1.png)

I´ll get back to this issue if I can repeat it on a new case...

**Comment by KickiLagerstedt** [comment]
compunds = compounds ...

**Comment by KickiLagerstedt** [comment]
![bild](https://user-images.githubusercontent.com/17139607/46608892-75b77600-cb06-11e8-8d37-ae3301675e42.png)

**Comment by KickiLagerstedt** [comment]
Efter reload:
![bild](https://user-images.githubusercontent.com/17139607/46608939-95e73500-cb06-11e8-94a2-a066462620d2.png)

**Comment by moonso** [comment]
So could it not be ok that it works after a reload?

**Comment by moonso** [comment]
I think this will happen for old cases, new cases should include this information right away

**Comment by dnil** [comment]
We tested it with a decently recent case, but please remind me to show you tomorrow! The user did not realise that something was missing, which is risky. We should at least have a reasonable understanding of why this happened before dismissing it.

**Comment by moonso** [comment]
@dnil  need to show this, when do you have time?

**Comment by moonso** [comment]
Any more information on this @dnil

**Comment by dnil** [comment]
@KickiLagerstedt do you still see this happening?

**Comment by moonso** [comment]
I'm closing since we haven't heard anyone complaining for a long time. Please reopen if it still happens
