### ISSUE TITLE
Can not "Download PDF" Report

### ISSUE THREAD

**Issue by KickiLagerstedt** [Clinical-Genomics/scout#984]
https://scout.scilifelab.se/cust002/F0013129/case_report

"504 Gateway Time-out"

I have tried x3

**Comment by northwestwitch** [comment]
I'll look into it. For the time being if the HTML version of the report is working (for me it woks but the page is slow to load), you might save a PDF of the report by pressing "print" and then "save as pdf" from the browser page. Not optimal I know, but it should work!

**Comment by northwestwitch** [comment]
The query optimization in #985 is still not fixing the issue, so I reopen it and I'll find a real solution!

**Comment by northwestwitch** [comment]
The 2 query optimizations I make didn't make much difference so I was thinking that we could try to do something at the level of the server configuration. Could we try to increase the Gateway timeout in the conf file (ngix?, I don't understand much of this stuff I'm afraid) @ingkebil ?

**Comment by northwestwitch** [comment]
When there are a lot of variants involved like in the case above the server takes more time then 5 minutes. I can see if I find some other place where the code could be improved, I'll let you know!

**Comment by KickiLagerstedt** [comment]
504 Gateway Time-out
https://scout.scilifelab.se/cust002/F0026810/case_report

When I try to print the report from the browser page suggested by Chiara @northwestwitch I do not get the whole report - only a few pages... ; everything BUT the commented variants (only two pages out of X pages) that I am interested in- Possibly also only two pages from dismissed variants.

**Comment by northwestwitch** [comment]
@moonso what is slowing down the queries and the case report creating might be the search of the sanger sequenced variants. 
I'm testing something else and a stupid query like this:
sanger_vars = db.variant.find({ 'case_id': 'blablabla', sanger_ordered:true }) takes ages. 
Could we index the field?? To be certain we should create the same report with the Sanger sequenced info and see if it's faster!
