### ISSUE TITLE
Create a view for institutes

### ISSUE THREAD

**Issue by moonso** [Clinical-Genomics/scout#988]
This would simplify updates to institutes, e.g.

- [ ] Update institutes to share cases with
- [ ] Update phenotype groups
- [ ] Set rank score tresholds

**Comment by moonso** [comment]
Could you start on this one when you have time @northwestwitch ?

**Comment by northwestwitch** [comment]
Ok!

**Comment by dnil** [comment]
Goes well with #864

**Comment by northwestwitch** [comment]
I'm working on this right now but I need some indication: what about the phenotype groups? What should I add to this page that would customize pheno groups for the institute? Do you mean cancer phenotypes VS rare disease phenotypes?

**Comment by northwestwitch** [comment]
Oh, maybe I understood!

**Comment by northwestwitch** [comment]
Ak ok, these ones!

PHENOTYPE_GROUPS = {
    'HP:0001298': {
        'name': 'Encephalopathy',
        'abbr': 'ENC'
    },
    'HP:0012759': {
        'name': 'Neurodevelopmental abnormality',
        'abbr': 'NDEV'
    },
    'HP:0001250': {
        'name': 'Seizures',
        'abbr': 'EP'
    },
    'HP:0100022': {
        'name': 'Abnormality of movement',
        'abbr': 'MOVE'
    },
    'HP:0000707': {
        'name': 'Neurology, other',
        'abbr': 'NEUR'
    },
    'HP:0003011': {
        'name': 'Abnormality of the musculature',
        'abbr': 'MUSC'
    },
    'HP:0001638': {
        'name': 'Cardiomyopathy',
        'abbr': 'CARD'
    },
    'HP:0001507': {
        'name': 'Growth abnormality',
        'abbr': 'GROW'
    },
    'HP:0001392': {
        'name': 'Abnormality of the liver',
        'abbr': 'LIV'
    },
    'HP:0011458': {
        'name': 'Abdominal symptom',
        'abbr': 'GI'
    },
    'HP:0012373': {
        'name': 'Abnormal eye physiology',
        'abbr': 'EYE'
    },
    'HP:0000077': {
        'name': 'Abnormality of the kidney',
        'abbr': 'KIDN'
    },
    'HP:0000951': {
        'name': 'Abnormality of the skin',
        'abbr': 'SKIN'
    },
    'HP:0001939': {
        'name': 'Abnormality of metabolism/homeostasis',
        'abbr': 'METAB'
    },
    'HP:0000118': {
        'name': 'As yet undefined/to be added',
        'abbr': 'UND'
    },
    'HP:0002011': {
        'name': 'Abnormal CNS morphology',
        'abbr': 'MRI'
    }
}

**Comment by dnil** [comment]
:+1: And presumably the "cohorts" as well. Makes a lot of sense to ge a dynamic version of them out of the constants and into the db. But this then becomes a large-ish PR! 😊

**Comment by northwestwitch** [comment]
Who put the easy label again?? :)

**Comment by dnil** [comment]
Well, you have to interpret him as in mathematics. If it is, in principle, possible to arrive at the solution with just hard work, it must still be trivial. Only if it is essentially proven impossible or at least non-convergent will it become hard. Actually, just reintroducing a page and change of rank score thresholds again would perhaps still be easy, even to the non-mathematician.

**Comment by dnil** [comment]
I might be guilty of putting it on the "Fixing small issues"-list at one point.. 🙄

**Comment by northwestwitch** [comment]
> I might be guilty of putting it on the "Fixing small issues"-list at one point.. 🙄

It's OK, but expect a **WTF** (WTForm) :D

**Comment by dnil** [comment]
Perhaps we need a new set of labels indicating the amount of work, not just its theoretical intricacy. 😜

**Comment by northwestwitch** [comment]
Intermediate will do! 👍
