### ISSUE TITLE
Create a Scout mailing list

### ISSUE THREAD

**Issue by moonso** [Clinical-Genomics/scout#99]
Send mails for planned downtime

**Comment by vwirta** [comment]
This could also be used when we notice that the service is down are unable to bring it back online in short time.

**Comment by robinandeer** [comment]
I've been looking for a reason to build a Twitter bot, hehe

**Comment by ingkebil** [comment]
Ah, twitter bot! Somehow that idea makes me happy :+1:

**Comment by moonso** [comment]
@emmser did you fix this today?

**Comment by ingkebil** [comment]
Aha, I did. Well, SoS did, and then I sent an email from that solution. We have now an account on chipmonkey.

**Comment by moonso** [comment]
:+1:
