### ISSUE TITLE
Missing transcript

### ISSUE THREAD

**Issue by 1ctw** [Clinical-Genomics/scout#997]
I recently found a variant in ETFDH in case 18188.

https://scout.scilifelab.se/cust003/18188/ecc12041f2f3e62f7eeed08fceaa0fd0

Those are the only transcripts shown in Scout as it is now:
![bild](https://user-images.githubusercontent.com/15033593/46741982-6d963c80-cca6-11e8-82ff-983f9c5066c8.png)

The disease associated transcript NM_004453 is now missing, but it has been there before. I can see from earlier sanger orders that it has been in Scout earlier.

![bild](https://user-images.githubusercontent.com/15033593/46742149-bc43d680-cca6-11e8-8c13-9cce451c9ff7.png)

![bild](https://user-images.githubusercontent.com/15033593/46742254-eeedcf00-cca6-11e8-8a16-264b9fa300bb.png)

Could you please check how and when this could have happened.

**Comment by moonso** [comment]
Hi @1ctw , I am not 100% sure when this changed but I guess it was when we started to handle genes and transcripts in a more exact way.
Transcript `NM_004453` does only exist in build 38. In build 37 the same transcript has refseq id `NM_001281738`.

Hope that is fine. Please close issue if there are no other questions

**Comment by moonso** [comment]
![skarmavbild 2018-10-12 kl 12 39 34](https://user-images.githubusercontent.com/405278/46864914-f7b3e180-ce1b-11e8-9626-84b7a4c12fdb.png)

You can confirm from this picture that they have the same ensembl id

**Comment by 4WGH** [comment]
![etfdh](https://user-images.githubusercontent.com/12525201/47138522-f4a46f80-d2b9-11e8-9f3e-b58ec33b4a9d.PNG)


the transcript NM_004453 exist in hg38...... and is not the same as transcript NM_001281738

Something else is happening here, unfortunately.

**Comment by moonso** [comment]
Hi, yes we are saying the same thing. The NM transcript exists in build 38 but in build 37 it does not exist. In 37 it has another NM id. Since the case is run with 37 we can not see the NM id.

**Comment by 4WGH** [comment]
no Måns...

NM_004453 exists in both bilds 37 and 38


It has disappeared!

Look at the Sanger order in fam 18147 and 18188.

Look into Scout for fam 18147 NM_004453  is not appearing any longer.

(By the way the "Disease associated transcripts" is also empty and so should not be )


Something else has happened and we can not undestand it but it is removing important information for us .



________________________________
Från: Måns Magnusson <notifications@github.com>
Skickat: den 18 oktober 2018 10:06:42
Till: Clinical-Genomics/scout
Kopia: Michela Barbaro; Comment
Ämne: Re: [Clinical-Genomics/scout] Missing transcript (#997)


Hi, yes we are saying the same thing. The NM transcript exists in build 38 but in build 37 it does not exist. In 37 it has another NM id. Since the case is run with 37 we can not see the NM id.

**Comment by dnil** [comment]
Hm, that it exists in hg38 was pretty much what @moonso said, but the funny thing is that there used to be a merged entry in hg19 including NM_004453, but primarily NM_001281738 - which appears in ENSEMBL as a preferred name for the same entity:
![screenshot 2018-10-18 at 09 59 40](https://user-images.githubusercontent.com/758570/47139672-aa70bd80-d2bc-11e8-97bf-1e8bba7a7f32.png). 
Perhaps we could get those "aliases" back inte the gene view at least?

The transcript suggested for reporting is still NM_001281737, which is ok:
![screenshot 2018-10-18 at 09 50 51](https://user-images.githubusercontent.com/758570/47139223-8d87ba80-d2bb-11e8-868c-6917ae43abec.png).

**Comment by dnil** [comment]
Oh, but the conceptual translations of NM_004453 (the nice 617 aa) and NM_001281738 (some funky 556 aa) actually differ! So the ENSMBL transcript table is broken - or at least I understand it wrong. Didn't you introduce a length check on peptides at some point to confirm identity @moonso?

**Comment by moonso** [comment]
Ok so I think there will always be problems like this whichever method we choose to use when defining the transcript/gene dataset. According to the rules we decided on to build the gene and transcript data in scout everything is right. We stated that each transcript will have one refseq id (if any is available) and we use HGNC as our anchor. So when HGNC says that NM_001281738 is the primary transcript this is the one we choose. To get around this we need to redefine how we setup the gene/transcript database in scout.

@dnil we do not do any length checks

@1ctw the transcript has disappeared either after we started to do this more accurate or after an update in ensembl/hgnc where NM_001281738 became the canonical transcript. Hard for me to say exactly which one of those. 

For your other question (why does not the transcripts from you panel file show up) I thought Robin had fixed this a long time ago but we need to check it again.

**Comment by 4WGH** [comment]
Sorry but I still don't understand why NM_004453 has disappeared.

It is in build 37 and 38.

 for each variants there are several NM_xxx trancripts listed in the transcript overview with the corrisponding HGVS Description.

why NM_004453 doesn't come up anylonger? it did Before....

When you write "We stated that each transcript will have one refseq id (if any is available)" do you mean that if an ENSEBLa transcript has more then 1 corresponding NM_XXXXX trascript only one is shown?




Michela




________________________________
Från: Måns Magnusson <notifications@github.com>
Skickat: den 19 oktober 2018 08:05:25
Till: Clinical-Genomics/scout
Kopia: Michela Barbaro; Comment
Ämne: Re: [Clinical-Genomics/scout] Missing transcript (#997)


Ok so I think there will always be problems like this whichever method we choose to use when defining the transcript/gene dataset. According to the rules we decided on to build the gene and transcript data in scout everything is right. We stated that each transcript will have one refseq id (if any is available) and we use HGNC as our anchor. So when HGNC says that NM_001281738 is the primary transcript this is the one we choose. To get around this we need to redefine how we setup the gene/transcript database in scout.

@dnil<https://github.com/dnil> we do not do any length checks

@1ctw<https://github.com/1ctw> the transcript has disappeared either after we started to do this more accurate or after an update in ensembl/hgnc where NM_001281738 became the canonical transcript. Hard for me to say exactly which one of those.

For your other question (why does not the transcripts from you panel file show up) I thought Robin had fixed this a long time ago but we need to check it again.

**Comment by moonso** [comment]
Yes, there is only one NM identifier per transcript in Scout. This is why we don't see NM_004453. We see NM_001281738 instead because it is stated as canonical in HGNC

**Comment by 4WGH** [comment]
yes!


thanks


Michela


________________________________
Från: Måns Magnusson <notifications@github.com>
Skickat: den 29 oktober 2018 15:25:33
Till: Clinical-Genomics/scout
Kopia: Michela Barbaro; Mention
Ämne: Re: [Clinical-Genomics/scout] Missing transcript (#997)


[skarmavbild 2018-10-29 kl 15 24 20]<https://user-images.githubusercontent.com/405278/47656116-c151c280-db8e-11e8-99cc-c853c75bd36e.png>

@4WGH<https://github.com/4WGH> this picture is from the variant in latest production release in scout. Is this what you would expect to see?
